### ISSUE TITLE
Cannot select model

### ISSUE THREAD

**Issue by grantcoultrup** [Ultimaker/Cura#10054]
### Application Version

4.10.0

### Platform

macbook pro m1

### Printer

none

### Reproduction steps

I just upgraded my previous version of cura to cura 4.10.0.

The first thing I did was drag and drop an stl file onto the build plate. This was successful.
Next I clicked on the object but the object would not be selected. I attempted this with my trackpad as well as my bluetooth mouse.
A right click successfully reveals a context menu. From here I was able to click "select all models" which successfully outlined the object.
I deselected the object.
Next I opened the object list and selected my object. This proved successful and the object was again outlined.  From here I attempted to drag the red x-axis arrow to reposition the model but the cursor would not select the arrow and deselected the model.
I could successfully change the position, size, and rotation by entering numerical values in the sidebar but any attempt to select an object or function helper on screen failed.

Also, the menu looks like this:
![Screen Shot 2021-06-29 at 4 23 10 PM](https://user-images.githubusercontent.com/71242310/123879727-4cfaee80-d8f6-11eb-8bb8-8ca3a15c16d0.png)

### Actual results

above

### Expected results

I should be able to select and manipulate the objects on the build plate with my mouse.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

n/a

**Comment by fvrmr** [comment]
Hi @grantcoultrup thank you for your report. 
These are two different issues. For the selecting part this is the duplicate: https://github.com/Ultimaker/Cura/issues/9912 do you have an external monitor?
And for the screen: https://github.com/Ultimaker/Cura/issues/8993 this is happening because of there are incompatibilities between M1 and the Qt library we are using. 

I will close this issue as a duplicate. But feel free to reach out if you have more questions.
