### ISSUE TITLE
Support is generated horizontally.

### ISSUE THREAD

**Issue by twinclouds** [Ultimaker/Cura#10079]
### Application Version

4.9.1

### Platform

Windows 10

### Printer

Creality Ender 3 Pro

### Reproduction steps

To generate support for a stature.

### Actual results

For the particular stature, the ![Cura bug](https://user-images.githubusercontent.com/5117656/124369539-82b71480-dc21-11eb-9b8a-7c6d9c032493.jpg)  But for others it works fine.
![Cura bug](https://user-images.githubusercontent.com/5117656/124369457-e260f000-dc20-11eb-8875-2936594a92e8.jpg)

### Expected results

It should be vertical.

### Checklist of files to include

- [ ] Log file
- [x] Project file

### Additional information & file uploads

You will see once you open the file.  I cannot attach the project file.

**Comment by fvrmr** [comment]
Hi @twinclouds could you add your project file (file - save project) as a zip here on Github? And are you adding the support with the custom support plugin?

**Comment by twinclouds** [comment]
Yes.  The support plugin is installed.  The file is too big to be included.  It's link is:  https://drive.google.com/file/d/1YF8dDWixDLjYEQ06KKiiiQ7xEreGuaks/view?usp=sharing
Thank you for your help.

**Comment by fvrmr** [comment]
Thank you, I think that this is happening because the model is grouped. Do you have this with other models? When I ungroup everything and add support it is working fine. ![Screenshot (209)](https://user-images.githubusercontent.com/77000924/124571877-782a9400-de48-11eb-9abd-1acc935685b8.png)

But when it is grouped it adds indeed the support horizontal. In that case it is best to report this to the plugin developer: https://github.com/lokster/cura-custom-supports
