### ISSUE TITLE
Skirt/Brim/Raft prints at odd position

### ISSUE THREAD

**Issue by alunmj** [Ultimaker/Cura#10106]
### Application Version

4.10.0

### Platform

Windows 10

### Printer

Creality Ender 3 Pro

### Reproduction steps

I added an STL file I've printed several times before to the bed, asked it to Slice in Super Quality mode, viewed the preview

### Actual results

The raft/brim/skirt is a circle around one end of the object.
<img width="305" alt="Screenshot 2021-07-08 131253" src="https://user-images.githubusercontent.com/22458124/124984601-46ebc880-dfee-11eb-933e-54ad114f9bd4.png">

### Expected results

The raft/brim/skirt should surround the entire object and print in that position.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

Added: Project file CE3PRO_Diable fillet 1.3mf, and the STL file used to slice, Fillet 1.stl. 
[CE3PRO_Diable fillet 1.zip](https://github.com/Ultimaker/Cura/files/6787045/CE3PRO_Diable.fillet.1.zip)

**Comment by fvrmr** [comment]
Hi @alunmj this has to do with your model. If I open your model in blender you can see that its not a straight line that would touch the buildplate. And with super quality mode the circle is the bottom of your model. 
![Screenshot (214)](https://user-images.githubusercontent.com/77000924/125061035-3b130b80-e0ad-11eb-8cd6-db2ececc6081.png)

If you change the quality to dynamic, it is a straight line because the layer height is changed. 
So you could change the quality or drop the model -0.13mm in the build plate. 
I hope this makes sense to you. I will close this issue, but please let me know if you have more questions.
