### ISSUE TITLE
this setting has been hidden by the active machine and will not be visible

### ISSUE THREAD

**Issue by BPcoxy** [Ultimaker/Cura#10194]
### Application Version

4.10.0

### Platform

windows 10

### Printer

BLV mgn cube

### Reproduction steps

Added printer (BLV mgn cube 300 and 350) using the simple guide and right from the get go relative extrusion is hidden by the active machine. ??

Added 5 random printers from tronxy, voron, creality, kay3d and geeetech and none hide "relative extrusion" 

Added a custom FFF printer and used all the settings and info generated for the BLV and now the relative extrusion option is available.

Tested on 2 pc´s and 1 fresh install of cura same result.

Google didn't help and online the opinion is normal bug and or broken BLV profile 

### Actual results

Ingen ting! 

nothing happened,  BLV is still hiding relative extrusion option.

used the custom fff profile to get access to relative extrusion, some print profile tweaking  and all is ok.

### Expected results

?? 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![cura_1](https://user-images.githubusercontent.com/86995763/127076308-0767d32c-1bac-4557-8b8c-702433776943.jpg)
![cura_2](https://user-images.githubusercontent.com/86995763/127076311-8b3667fc-db20-4c66-9b66-7b55a873970f.jpg)
![cura_3](https://user-images.githubusercontent.com/86995763/127076312-ab70f142-8384-4fe0-9fa0-f60560366ef6.jpg)

**Comment by fvrmr** [comment]
Hi @BPcoxy not all printer firmware supports relative extrusion. Read here more about the relative extrusion: https://github.com/Ghostkeeper/SettingsGuide/blob/master/resources/articles/blackmagic/relative_extrusion.md

If it is related to the profile, this is something we won't change, since we don't maintain these profiles. So I will close this issue, but please reach out if you have more questions about this.
