### ISSUE TITLE
Please add a way to see the filament change in the preview so multiple color prints can be seen better

### ISSUE THREAD

**Issue by yourbuddydinec** [Ultimaker/Cura#10238]
### Is your feature request related to a problem?

When using the post processing script I've found no way to be able to show that filament change so that I can preview what the final product will look like. It just shows one color normally.

### Describe the solution you'd like

On the post processing script for filament change at layer make it so you can optionally select the color it will be represented by in the preview and then allow the preview to reflect that when showing it in material color mode. 

### Describe alternatives you've considered

I've tried going through the other color schemes in preview but none of them show the filament change at all since its just a change of filament and not a change to the way the printer is acting. 

### Affected users and/or printers

Anyone who wants to use filament change post processing.

**Comment by fvrmr** [comment]
Hi @yourbuddydinec thank you for your feature request. Unfortunately this is something we won't do because the post processing script is added after you save/send the gcode to the printer. The post processing script is not added when you press slice so it is not the preview. If we want to add this we need to rewrite the way the post processing is added. 
I hope this makes sense to you.
