### ISSUE TITLE
Installation, Add Printer Error

### ISSUE THREAD

**Issue by akaMOTU** [Ultimaker/Cura#10277]
### Application Version

4.10.0

### Platform

Windows 7 Pro 64

### Printer

THIS IS THE PROBLEM

### Reproduction steps

Installed your software.

### Actual results

Running installation file. Asks for printer model/type. I see A LOT OF PRINTERS, some I've never heard of. WHERE is the option for QIDI????

### Expected results

I should see an option for QIDI 3D printers.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

That's it.

**Comment by fvrmr** [comment]
Hi @akaMOTU we don't maintain 3rd party printers. Thanks to our community all the other printers are added in Cura. In 4.10 is one Qidi printer: 
![Screenshot (232)](https://user-images.githubusercontent.com/77000924/129319174-f3f7addf-aefd-4d08-8b76-265a01007f60.png)

You can also use the option custom and there you can create your own printer. 
I will close this issue since this is something we won't do since we are depended on our community to add these files.
