### ISSUE TITLE
2.3: Wall Speed Locked

### ISSUE THREAD

**Issue by CCS86** [Ultimaker/Cura#1034]
Hi guys, any idea what's going on here? I'm locked out from changing wall speed.

![image](https://cloud.githubusercontent.com/assets/12439543/19215122/cb4cd84e-8d5a-11e6-82f1-57a8fc6567a1.png)

**Comment by fieldOfView** [comment]
I think that in the profile you have selected, a value is set for both the inner wall speed and the outer wall speed. Together these override the wall speed setting. So entering a number there would not have any effect

**Comment by CCS86** [comment]
You can see here though, that only the outer wall speed child setting is enabled, and the values don't match. A hidden child setting shouldn't drive, right?

Tried enabling it. Something still not right:

![image](https://cloud.githubusercontent.com/assets/12439543/19215225/c32ff4ea-8d5d-11e6-9dcc-84877e6424aa.png)

**Comment by fieldOfView** [comment]
Could you click on the "i" buttons for both inner and outer wall speed?

**Comment by CCS86** [comment]
It doesn't affect the wall speed lockout

**Comment by CCS86** [comment]
I've tried exporting the current profile, then modifying the values for those speeds, renaming, then importing; but I get an "invalid argument" error.

**Comment by CCS86** [comment]
I think it was something about the existing profile.

I scrapped the whole Cura appdata folder, and started everything from scratch. Now the field is unlocked.

**Comment by fieldOfView** [comment]
In 2.4 we're going to have to be more clear about why a value is disabled. Too late for 2.3 though.

**Comment by CCS86** [comment]
I'm still struggling with this in 2.4:

![image](https://cloud.githubusercontent.com/assets/12439543/21755977/cae1acd0-d5e0-11e6-9842-59b78f4e7575.png)

**Comment by Ghostkeeper** [comment]
The setting is disabled because it has no effect on the print any more. Both `Outer Wall Speed` and `Inner Wall Speed` have customised settings (as indicated by the rotating arrow). `Wall Speed` does nothing but to affect the default of `Outer Wall Speed` and `Inner Wall Speed`. So now that those settings are different from the default, the setting does nothing any more.

I believe we give a warning message on the bottom of the screen if there are hidden settings that are different from the default.

> A hidden child setting shouldn't drive, right?

No, hiding a setting does nothing to affect the slice. A hidden child setting still drives.

I can't find the Jira ticket related to this issue though. Did we make one? I don't think it is really clear yet why a setting is disabled if all its child settings are hidden.

**Comment by ianpaschal** [comment]
No more work will be done on versions 2.x. If this is still occurring in versions 3.2 or newer, we can re-open this issue.

**Comment by Ghostkeeper** [comment]
This is still a problem. It's a bit of a user experience problem that the setting is greyed out and nothing explains why.

**Comment by Vandrasc** [comment]
Devs see CURA-5083

**Comment by Ghostkeeper** [comment]
Our project manager decided to remove this from our planning. It's a problem but not important enough to spend time on now until we get to make some time for rethinking this part of the UI.
