### ISSUE TITLE
First bridge layer no longer spans gap

### ISSUE THREAD

**Issue by logiccrazy** [Ultimaker/Cura#10348]
### Application Version

4.10.0

### Platform

Windows 10

### Printer

Ender 3

### Reproduction steps

Load in any model with bridging

### Actual results

The first layer of the bridge has the extruder go around the perimeter and then diagonally between the outer walls
![Capture](https://user-images.githubusercontent.com/89707251/131229320-4e7fdf6d-7f17-4fb2-b489-4da149cb9f4e.PNG)

### Expected results

The first layer of the bridge in 4.9 went back and forth along the length of the bridge right through it causing less sag (I drew red lines showing the extruder path in 4.9 which yielded superior results.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[CE3_Branch.zip](https://github.com/Ultimaker/Cura/files/7071396/CE3_Branch.zip)

**Comment by fvrmr** [comment]
Hi @logiccrazy thank you for your report. 
In your project file the bridge settings are not enabled. 
If you enable bridge settings it works!
![Screenshot (248)](https://user-images.githubusercontent.com/77000924/131312882-8c7c8540-705c-458f-8242-763abf040317.png)

I will close this issue since that will fix it. But please reach out if you have more questions.
