### ISSUE TITLE
Cura turning fan off when printing mid air

### ISSUE THREAD

**Issue by deebeo-blip** [Ultimaker/Cura#10376]
### Application Version

4.10.0

### Platform

Windows 10

### Printer

Voron 2_300

### Reproduction steps

Sliced a model with 90 degree overhangs further up the model and initial layer fan speed 0% and regular fan speed 100%. See yellow overhang next to the top of each column.
![image](https://user-images.githubusercontent.com/60131095/131698306-49b4c11a-4327-4fa8-9617-ce31a988a9d9.png)
![image](https://user-images.githubusercontent.com/60131095/131699272-bef2fd3e-d8cb-4911-8ebc-198da3c8773a.png)

### Actual results

Cura turned the fan off when reaching the yellow bottom layer parts in mid air which causes the print to fail. the gecode shows several M107 I don't understand. They are in the following combination
;TYPE:SKIN
;BRIDGE
M107
I can not find a setting to control the fan speed differently for these occasions so I'm assuming it's a bug.
[V2_Aspect-of-the-Gods-Lv7-v1.0.gcode.txt](https://github.com/Ultimaker/Cura/files/7092432/V2_Aspect-of-the-Gods-Lv7-v1.0.gcode.txt)
[V2_Aspect-of-the-Gods-Lv7-v1.0.3mf.zip](https://github.com/Ultimaker/Cura/files/7092439/V2_Aspect-of-the-Gods-Lv7-v1.0.3mf.zip)

### Expected results

Fan should stay on for 100% of the time onwards form layer 2 since the manual states that "fan speed initial layer" only affects layer which are actually connected to the build plate. 

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

Please review the attached Project an Gcode. I never noticed the fan turning off in mid print when printing bridges/overhangs. What is the reason for this?

**Comment by nallath** [comment]
Well, you seem to have bridging enabled and that does set the fan to 0%

![image](https://user-images.githubusercontent.com/3922611/131704998-f6729324-26d2-4255-b8fc-54115745c9a3.png)

**Comment by GregValiant** [comment]
I don't think those flat areas can qualify as a bridge.  When the inner and outer wall loops go down they are completely over air and there is no opposite abutment that they can connect to.
This is the first layer of those overhangs and it is doomed to failure without support.  It is air printing and no amount of cooling is going to help this.
![image](https://user-images.githubusercontent.com/64202104/131840269-b007e64f-a7c9-47ac-bc11-b85e8fefb4b0.png)

**Comment by GregValiant** [comment]
With matching 2.2mm holes in each part you can split it, drop 6mm pieces of filament into two of the holes, and glue it together.  There is still some hard to remove support being generated in the Arch part.
[GV_V2_Aspect.zip](https://github.com/Ultimaker/Cura/files/7099183/GV_V2_Aspect.zip)

![Untitled](https://user-images.githubusercontent.com/64202104/131852748-72fc1df2-991e-4260-a3df-9ecbff7540b1.png)

**Comment by Ghostkeeper** [comment]
So the problem is then that those areas are being misclassified as a bridge. On the other hand, generic overhang might as well be printed as bridging.

One problem with our bridging algorithms at the moment is that they don't look at where the individual lines are going. It can know the general direction of lines, but doesn't know whether lines are resting on 0, 1, 2 or more spots along their paths. That would be expensive to calculate for each line. And you'd want to use bridging if there are at least 2 resting places, but only for the part of the line that is between those two places. The experimental bridge detection in general needs more attention; we basically imported that from a PR and never really updated it significantly ever since.

I'm currently unable to import this project file by the way because it depends on the `Voron_2_300` definition which doesn't exist. The one that ships with Cura is called `voron2_300`. It may be a different definition. Reading through the profiles I don't see the `bridge_settings_enabled` setting being overridden. Maybe Nallath didn't realise that it had just imported the models, not the whole project file?

But yes, bridging is a likely candidate.

**Comment by GregValiant** [comment]
Is this still an issue in current versions of Cura (5.8.0 and up)?  Can this be closed?
