### ISSUE TITLE
Intent profile is displayed even though the nozzle of the right extruder is deactivated. 

### ISSUE THREAD

**Issue by x40-Community** [Ultimaker/Cura#10393]
### Application Version

Master

### Platform

Linux

### Printer

Weedo X40 / Idex printer

### Reproduction steps

Open a project file from a dual extruder printer with the following setup:
The extruder on the left is set to a 0.4mm nozzle. The left extruder is set to a nozzle 0.6mm and deactivated. 

### Actual results

The intent profiles of the 0.6mm nozzle are displayed, although the nozzle is deactivated. 

### Expected results

If the nozzle is or will be deactivated, the associated profiles should no longer be displayed. 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![bug](https://user-images.githubusercontent.com/87263830/132135521-b084e7aa-f904-494f-8189-eda7690d0f07.jpg)
![No_Bug](https://user-images.githubusercontent.com/87263830/132135525-6c19400f-b881-4cde-ab25-fdfe9e7719c8.jpg)

**Comment by fvrmr** [comment]
Hi @x40-Community could you share a project file? It is easier to reproduce your issue with a project file.

**Comment by Ghostkeeper** [comment]
Your issue can't be reproduced in our Master version because we don't have intent profiles yet with the Weedo X40 printer. A project file wouldn't be sufficient then; we'd need the intent profiles too (and any other profiles you may have changed).

It seems to be behaving fine as far as I can see in the Ultimaker S5. Here I put PLA on the right extruder which has intent profiles, but PP on the left extruder which doesn't have intent profiles. Disabling the right extruder causes the intent profiles to disappear. The horizontal slider remains unchanged because both extruders support the same quality levels in this case. The drop-down with profiles reflects this too; it is the same set of profiles, in both cases, as the sliders in Recommended Mode. Recommended Mode visualises it a bit nicer though.
![image](https://user-images.githubusercontent.com/2448634/133250119-d00095d5-9a46-43f1-84df-c2bb597b8eb9.png)
[intent_profiles_disabling_extruders_s5.zip](https://github.com/Ultimaker/Cura/files/7161491/intent_profiles_disabling_extruders_s5.zip)

**Comment by Ghostkeeper** [comment]
Ah, the intent profiles seem to be the ones provided here? https://github.com/Ultimaker/Cura/pull/10345

**Comment by x40-Community** [comment]
The quality and intent profiles are only just gradually being added to Cura.

**Comment by x40-Community** [comment]
[bug.zip](https://github.com/Ultimaker/Cura/files/7163997/bug.zip)
Here is the project file for the error

**Comment by Ghostkeeper** [comment]
> [bug.zip](https://github.com/Ultimaker/Cura/files/7163997/bug.zip)
> Here is the project file for the error

Thanks! But this zip archive is corrupt? File Unroller can't read it in any case :(

> Do you always have to create the profiles for all nozzle sizes, even if they don't work with the printer?

No, preferably you'd only have profiles that work.

These are the relevant requirements we have:
* The available quality levels is the *intersection* of the quality levels available for each individual (enabled) extruder. For instance, if one extruder has quality levels Fine and Normal, and the other extruder has quality levels Normal, Draft and Sprint, then the user can only select Normal, since that is the only quality type available for all extruders.
* The available intent categories is the *union* of the intent categories available for each individual (enabled) extruder. So if an intent profile is available for any extruder, the user can select it. If a different extruder doesn't have an intent profile with that intent category, the intent profile will be left empty (in the interface listed as "default").

**Comment by GregValiant** [comment]
Is this still an issue in current versions of Cura (5.8.0 and up)?  Can this be closed?
