### ISSUE TITLE
Cura app can't connect Anet A8

### ISSUE THREAD

**Issue by skabrits** [Ultimaker/Cura#10411]
### Application Version

4.11.0

### Platform

Mac OS (Catalina)

### Printer

Anet A8

### Reproduction steps

Join printer to Mac by cable. Open Cura. Go to page Monitor.

### Actual results

No printer appears, white field with no interface (as if it was not connected).
<img width="1436" alt="Снимок экрана 2021-09-08 в 19 00 11" src="https://user-images.githubusercontent.com/17362018/132544647-87efb2c4-7d30-4090-9cad-e666854e8ff3.png">

### Expected results

The printer should be detected and standard monitor interface should appear.
<img width="1438" alt="Снимок экрана 2021-09-08 в 19 01 06" src="https://user-images.githubusercontent.com/17362018/132544737-1688f6cc-bae1-4383-8b16-be52b6f423ea.png">

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

To fix problem in file /Applications/Ultimaker Cura.app/Contents/Resources/plugins/plugins/USBPrinting/AutoDetectBaudJob.py line 77 should be changed from:
if b"ok" in line and b"T:" in line:
<img width="795" alt="Снимок экрана 2021-09-08 в 18 58 57" src="https://user-images.githubusercontent.com/17362018/132544873-94799fb9-d7b3-4d35-89e3-e532da753407.png">
to:
if b"ok" in line or b"T:" in line:
<img width="790" alt="Снимок экрана 2021-09-08 в 19 02 32" src="https://user-images.githubusercontent.com/17362018/132544975-09eddab5-7049-400b-98f1-d889f3428a72.png">
As 3d printer send "ok" and "T:" on different lines, Cura can't detect it.

Unfortunately I can't attach fixed file as markdown does not support attaching python files.

**Comment by fvrmr** [comment]
Hi @skabrits thank you for your report and solution. Did you also tested your solution?

**Comment by skabrits** [comment]
Yes I have tested — it it works

**Comment by Ghostkeeper** [comment]
Nice report. I'm a bit wary though that this change could cause other devices to also be detected as a printer, if they happen respond to something with `ok`. Or even `nokeyerror` or anything else that happens to have `o` and `k` next to each other. It would be safer to include more of the response in the check. Do you know what the complete response is of the printer?

And then to also fix the temperature read-out because if the message just contains `ok` then it won't parse a temperature for the monitor either.

Be aware that Ultimaker also doesn't maintain the USB printing workflow at all any more. We're merging fixes for it (like this one) but we have no way of testing it so we need to rely on the community to provide fixes for their printer models, like this.

**Comment by GregValiant** [comment]
Is this still an issue in current versions of Cura (5.8.0 and up)?  Can this be closed?
