### ISSUE TITLE
Don't wait for bed to heat between sequential-order prints if the temperature did not change.

### ISSUE THREAD

**Issue by smhanov** [Ultimaker/Cura#10463]
### Is your feature request related to a problem?

Between objects in a sequential print, the print head first moves to the next object position, then waits for the bed to achieve temperature.  During this time, filament oozes from the nozzle and falls onto the bed where the next part would be printed.

This happens even if the temperature did not change.

### Describe the solution you'd like

If the bed initial layer temperature, and the bed temperature are the same, do not issue the command to wait for the bed to achieve temperature.

### Describe alternatives you've considered

An alternative would be to alter Marlin itself to not wait for the new temperature if the bed has already stabilized to that temperature. However, this behaviour may be in Marlin for a reason. In any case, Cura does not need to issue the unnecessary command.

### Affected users and/or printers

Users of Marlin based printers who print multiple parts using the sequential ordering feature.

**Comment by Ghostkeeper** [comment]
I'd consider this a bug. That temperature command is unnecessary and may negatively affect the print. These are the reproduction steps:

1. Use a single extrusion printer or disable all but one extruder.
2. Load two models.
3. Set the Print Sequence to "One at a Time".
4. Ensure that the Build Plate Temperature and Build Plate Temperature Initial Layer are the same.
5. Slice and inspect the g-code. Search for `M190 `.

Expected result: Only one `M190` command at the start.
Actual result: There's another `M190` in the middle where it starts with the next object. That `M190` has the same temperature as the last `M190` or `M140` command.
A project file to reproduce the issue more easily: [unnecessary_bed_temp_one_at_a_time.zip](https://github.com/Ultimaker/Cura/files/7216686/unnecessary_bed_temp_one_at_a_time.zip)

I think the issue will be a bit problematic to solve, since the implementation of One at a Time is effectively to repeat the entire slice process for every object separately, minus the start and end sequence. It doesn't currently remember state in between like the build plate temperature. But we'll see, maybe it turns out easier than I expect.
