### ISSUE TITLE
ver 411 saving filename issue (s)

### ISSUE THREAD

**Issue by Dvrys** [Ultimaker/Cura#10478]
### Application Version

4.11

### Platform

Windows 10

### Printer

Creality Ender 3

### Reproduction steps

Win 10 PC with internal hard drive (c:)and a USB MicroSD card (f:), Ender 3v2 printer with stock firmware. My File to print is called Body.stl but problem repeats with any  printable file.
 
1. Load new instance of Cura each time (with Gcode Filemane Format Plus extension installed)
2. install a microsd into the usb slot on PC.
3. Load and Slice a model. (Body.stl) 
4. Save to Removable Drive.
5. Save to Disk.

6.  Close Cura and remove Micro sd card
7. Reload Cura 
8. load and Slice a model

9 Save to Disk

10. insert the MicroSD card into the USB.

11. Related but separate issue; install Micro SD card in Ender 3v2 printer and try to load the saved long name file. 

### Actual results

From Step 4.  this first save after slicing follows the extension's rules (ie. "Saved to Removable Drive 1sc (f:) as Body Generic PLA lw 0.4mm lh 0.2mm if 20% ext 1 200C bed 50c.gcode".)

From Step 5. "save to disk window" appears AND the file name is shorten to CE3_Body.gcode.

From Step 9 The "Save to disk" window appears AND the file name is "Body Generic PLA lw 0.4mm lh 0.2mm if 20% ext 1 200C bed 50c.gcode" Note: Subsequent Save to disk will yield the same long name UNTIL you perform step 10.

From Step 10  The "save to removable drive" window appears AND the file name is shortened to CE3_Body.gcode

From Step 11 File does not appear on my printer unless it is renamed to something shorter like CE3_body.gcode. then it may or not print. 

### Expected results

with the extension in place, I expected the save function should always follow the extension rules.ie long file name. (steps 1-10)

Step 11 the file should print. but see 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

The two problems are:
1. the changing Save file name as I described
2. The long file never appears on my Printer Controller so I cant select it AND if I rename the long filename to the shorter version, there is a good chance it will hang up during print. HOWEVER, IF the first save is the short filename, CE3_Body.gcode. the file will print flawlessly.

**Comment by Ghostkeeper** [comment]
I tried your steps, but without the plug-in these steps don't really make sense. As far as I found (with your reproduction steps and with my own extra related steps around it) it's all saving correctly as the project name with .gcode extension, which is Cura's own behaviour.

I didn't try this with the plug-in, but for that I'll have to refer you to the [issue tracker of that plug-in](https://github.com/fieldOfView/Cura-CustomJobPrefix). Since the problem occurs with the plug-in only and it's about the behaviour of the plug-in, it's not up to us to fix it. Of course if the plug-in is using Cura's APIs for its implementation and it turns out those APIs are behaving weirdly (like, maybe we're not emitting all of the correct signals when saving to removable drive or something), we'll be able to make a fix.
