### ISSUE TITLE
Skin expand not working as it should

### ISSUE THREAD

**Issue by DragonFlyer007** [Ultimaker/Cura#10488]
### Application Version

4.11.0

### Platform

Win 10

### Printer

Cr10S

### Reproduction steps

When printing like a logo with two surfaces. A base, and extruded text on top.

The "skin expand distance" will not make the skin layers/top layers on the base part to print in one piece. It will fill in to the edge where the text will be, once all hat is done, then it will fill in the text area, this result in not as good surface as possible if the skin layer was all printed in one go. Even with extreme value here, still the same result.

Like a full clean surface, then the text on top. This i can not get to work what i do, ironing or not ironing, the same result.

I hear some people might make this work, with same settings, so might be a bug.

### Actual results

Not as good finish as i could be if the surface layer was printed in one continius move.

### Expected results

To have the surface layer print in one go, and not around the text, then inside the text.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[ezyzip.zip](https://github.com/Ultimaker/Cura/files/7197529/ezyzip.zip

![5555](https://user-images.githubusercontent.com/90724902/134045974-d1342657-de97-4105-8731-47e4961397db.JPG)
)

**Comment by Ghostkeeper** [comment]
The issue you're facing here is that you have Top Surface Skin Layers set to 1, so it's going to print the highest layer of skin with different settings (in your case, 100% flow instead of 95%). To do this, it separates the top surface skin layers. This prevents having constant flow changes halfway through lines. It also allows using different line width, which is the major intended use case for the Top Surface feature.

The letters are separate because the model is higher there. So the part underneath the letters is not at the top surface.

Setting the Top Surface Skin Layers to 0 is a workaround, but you'll have 95% flow again then. Perhaps it's better to use 100% flow for the skin.

But really this is behaving as expected.
