### ISSUE TITLE
Layer issue - Nozzle hit the print 

### ISSUE THREAD

**Issue by Tiflo62** [Ultimaker/Cura#10631]
### Application Version

4.10

### Platform

Windows 10

### Printer

Ender 3

### Reproduction steps

Import the stl
Ask me to fix it (didn't ask with older version)
Fix it using 3D builder
Reimport
Slicing

### Actual results

Issue during printing, the nozzle hits the last layer and moves the print from the bed. Always at the same height

### Expected results

The nozzle doesn't hit the last layer

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![IMG_20211017_235338](https://user-images.githubusercontent.com/74988027/137648159-665c3bd9-0954-4465-b35e-c111a2f318b1.jpg)

**Comment by GregValiant** [comment]
I wrote a little macro in Excel and read in all the Z values and then checked them to see if there was a glitch and the Z went down.  It did not.  The problem isn't in the gcode.
Here are the line numbers from the file along with the Z value in the line.  You can see that they keep going up.  They are oddball numbers because you used a raft.
789615	115.49000    Layer 571
791394	115.69000
793225	115.89000
795189	116.09000
797058	116.29000
798944	116.49000
800914	116.69000
802794	116.89000
804723	117.09000
806650	117.29000
808668	117.49000
810693	117.69000
812745	117.89000
814823	118.09000
816928	118.29000
819107	118.49000
821286	118.69000
823454	118.89000
825597	119.09000
827798	119.29000
829969	119.49000
832070	119.69000
834244	119.89000   Layer 593
If the SD card has bad memory sectors your computer can't tell.  When you copy a file to the SD card the computer can (and will) copy the file, or parts of the file, to bad sectors.  The printer is going merrily along and then sees gibberish but can react to some random text that looks like a gcode command.  If you still have the Gcode file on that SD card then open it in Notepad or some other text editor and quickly scroll through it.  If you see computer gibberish or if the file ends abruptly, then the file is corrupt and that was the problem.  You can try re-formatting the card or get a new one 32gb or smaller (Ender's don't like cards over 32gb).
Anyway, I'm confident that gcode file wasn't the problem.
