### ISSUE TITLE
Custom Gcode in Material So chamber heater can be set by Material 

### ISSUE THREAD

**Issue by nfored** [Ultimaker/Cura#10655]
### Is your feature request related to a problem?

I see for years people have asked for the simple ability to have some gcode stored in the material and it seems someone always says how useless that is and there are better places.  I am sure everyone that says that of course has a multi million dollar printer that does everything for them. 

The rest of use use things like octoprint and its many plugins to make our humble printers better.  I for one use octo print to enable me to have a enclosure heater. Now every time I have to print ABS I have to go in start my heater wait for it to heat up, then send the print job which cancels the heater and then start back up. 

If I had the ability to store a single line of gcode in my custom ABS and custom PC  meterials I could simply select my material and hit print. Then octoprint could say oh look they want to heat the chamber up and it would heat the chamber before processing the print.  There would be no more failed prints due to user error of forgetting to set the heater. 

### Describe the solution you'd like

I think a very simple start gcode inside the material profile would be amazing.

### Describe alternatives you've considered

What I have to do now is simply remember to turn on my chamber heater manually.  I guess something else you could do is have some kind of scripting ability in the normal start gcode that can activate additional gcode based on the selected filament. 

### Affected users and/or printers

I am sure there are many other use cases for this as its been asked for years. Would I rather this than the continued awesome improvements in cura? NO but it would be welcome improvement.

**Comment by GregValiant** [comment]
There are a couple of workarounds that aren't terribly complicated.

Assuming you are using M191 and assuming you want the enclosure to heat to 70° then put ";M191 S70" into your StartUp G-Code.  You can then activate an instance of the Search and Replace plugin when you use ABS:
Search = ;M191 S70
Replace = M191 S70
That would result in the line being un-commented and the temperature set.  You would probably need an M141 S0 in your End G-Code.
Another alternative is to have a second instance of your printer installed in Cura just for ABS.  The StartUp G-Code of that second instance would be slightly different because it would have the chamber heating command in it.  Printing ABS?  Select your ABS printer in Cura.  Printing PLA?  Select the first printer.
