### ISSUE TITLE
Cura navigates nozzle to right back end of my print bed for some files. Some files work, some don't (settings stay the same) In other slicing sofware these work perfectly.

### ISSUE THREAD

**Issue by NielsBE95** [Ultimaker/Cura#10691]
### Application Version

4.11.0

### Platform

Mac OS Catline

### Printer

Ender Creality 3 v2

### Reproduction steps

Opened STL file like usual to place it in a gcode format.

### Actual results

Some prints work like normal.
Others have weird output results even though the settings are still the same.
Some files were not printable at all, the nozzle and hotend navigated to the back right end of my print bed. No problems in the gcode whatsoever. 

The temperature is not the same as I put in cura.
Even the speed and temperature changed, when I try to change them manually in the printer it keeps resetting to the weird value cura selected (sometimes 948% speed) 

When I test it in other slicing software it works like normal. So it has 100% to do something in Cura.

### Expected results

A normal print with the settings I used in Cura

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![249186305_4766946023324134_7516067055736642111_n](https://user-images.githubusercontent.com/93288640/139140274-aec456c5-8450-490b-8a64-2eb602c1cc47.jpg)

nozzle positioning after selecting the gcode

![249588285_311215503767162_4306278326619488090_n](https://user-images.githubusercontent.com/93288640/139140279-d1fa4636-0abe-4ad0-bf45-1a1c37b8fd09.jpg)

print speed output even though it should be 100%

**Comment by NielsBE95** [comment]
Ofcourse [https://we.tl/t-Pyf3FUpR3e](https://we.tl/t-Pyf3FUpR3e )

**Comment by Ghostkeeper** [comment]
That is not a project file. That is a toolpath. To save a project file, you'd go to File -> Save Project and share the resulting file from there. That file contains the models in the scene and their placement, the profiles it's using and the setting overrides.

However from this g-code I can see also that there is a move towards the back left (seemingly, though your printer's coordinate system might be different) saying:

    G1 X0 Y235 ;Present print

This is not anywhere in Cura, and Cura doesn't generate comments on its g-code like that. It seems this is part of the end g-code in your printer's profile. Cura doesn't currently have a profile specific to v2 of the Ender 3 and the "v1" doesn't have this in the end g-code. So it is part of whatever profile you downloaded for the printer.

The objective of this travel moves seems to be to allow you to take the print off more easily.

It's expected behaviour, in any case, that Cura puts the entire end g-code at the end of the print, including this travel move if it's in the profile.

**Comment by Ghostkeeper** [comment]
I can't read the display of the printer on your picture, but I can't explain why the firmware doesn't say 100% (if it doesn't). There are no M220 commands in this g-code. But the M220 might have been in a previous print and remembered.
