### ISSUE TITLE
New profile for 4.12 ?

### ISSUE THREAD

**Issue by 0r31** [Ultimaker/Cura#10699]
### Is your feature request related to a problem?

I would like to add a profile for a brand new printer (Dagoma Pro430).

### Describe the solution you'd like

I have a full batch of files (printer, extruder, quality, filament profiles) tested against 4.11

### Describe alternatives you've considered

There is no alternative

### Affected users and/or printers

It will affect people using this brand new printer.

### Additional information & file uploads

My question to @Ghostkeeper : Is it too late to add this profile to Cura 4.12 ?

**Comment by Ghostkeeper** [comment]
I'm one of the 4 programmers working on Cura at the moment. Fvrmr is the community manager and would probably respond more quickly. I'm explicitly one week behind to broom up issues that have been forgotten.

We don't accept new features any more after about one week before the beta is released. So since the beta of 4.12 is released we'll not add new features to it, including new printers.

Of course, the profiles are more than welcome for the next release.
