### ISSUE TITLE
Resume failed prints from given layer over USB connection.

### ISSUE THREAD

**Issue by cfontes** [Ultimaker/Cura#10713]
### Is your feature request related to a problem?

It would be very helpful if one could resume on a given layer when a print fails because of a clog for example when printing over USB.

Currently you have to use hacky methods like manually editing gcode and using a SD card.

### Describe the solution you'd like

The feature would be like a filament change but for starting the print, you just select the layer you are in ( by counting them or measuring the layer height you stopped at ) and the printer should be able to resume from the start of that given layer.

### Describe alternatives you've considered

Manually editing the gcode to start from that layer and using a SD card but it's very error prone and labor intensive to do, and you already have a hardware problem on your hands to solve so software helping would be great!

### Affected users and/or printers

Everyone that prints over USB, on all printers in this universe.

### Additional information & file uploads

Cura is great, thanks for it!

**Comment by fvrmr** [comment]
Hi @cfontes thank you for your feature request. 
Unfortunately we don't maintain USB printing anymore, since our printers don't use USB printing. So we can't test this feature.  
Also when your nozzle is clogged, it is hard for the software to know where exactly the print failed.
And when you want to resume your print is cooled, it could be that it is not exactly at the same position. Which could cause other issues. So it is a bit tricky to do this.

Based on that we won't add this feature in Cura and I will label this as won't do and close this request. I hope you understand!
