### ISSUE TITLE
Bad Skirt on a print of multiple parts

### ISSUE THREAD

**Issue by Joachim-R** [Ultimaker/Cura#10747]
### Application Version

4.12.0 Beta

### Platform

macOS Catalina

### Printer

Ender 3v2

### Reproduction steps

using https://www.thingiverse.com/thing:3796670:

Slicing the https://cdn.thingiverse.com/assets/da/23/14/40/38/Slotter_1.stl leads to a wrong skirk around only one of the 5 dishes.
![Bildschirmfoto 2021-11-05 um 12 40 56](https://user-images.githubusercontent.com/93771482/140505253-55ef7924-1eee-4004-b845-8af3f91e704d.png)

### Actual results

See image

### Expected results

Skirt around all dishes

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

-

**Comment by fvrmr** [comment]
Hi @Joachim-R thank you for your report.
Looking at your model in Blender, you can see that the five sticking out 
![Screenshot (292)](https://user-images.githubusercontent.com/77000924/140530663-a215c961-77d3-4dd0-b12e-d9bb959081f1.png)
So Cura see this as the first layer. If you change your profile to dynamic quality it will print the skirt correctly.

See also https://github.com/Ultimaker/Cura/issues/9420

I will close this issue since it is a duplicate. But please let me know if you have more questions.

**Comment by Joachim-R** [comment]
Just a note:
You/Me must not print this stuff using "Super Quality". That is all.
Thanks for the hint.
