### ISSUE TITLE
Raft does nor generate on smaller parts under the wall size

### ISSUE THREAD

**Issue by neofuture** [Ultimaker/Cura#10765]
### Application Version

4.11.9

### Platform

macOS M1

### Printer

CR10/Ender3

### Reproduction steps

Using models that are very small  (less than 5 mm as tested, may be treated) are excluded from the raft and a raft is not generated and the raft is ignored and left out of the print, leaving prints to fail

Add a small part around 3 mm in diameter, duplicate this 50 times then add a new object 20mm and duplicate this 20 times, the 20 mm Object gets a raft the 3mm object does not

### Actual results

Rafts do not get calculated for tiny parts

### Expected results

Rafts !!!

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

Add a small part around 3 mm in diameter, duplicate this 50 times then add a new object 20mm and duplicate this 20 times, the 20 mm Object gets a raft the 3mm object does not

**Comment by fvrmr** [comment]
Hi @neofuture thank you for your report.
Could you share a project file? I could not reproduce this with your reproduction steps.

**Comment by neofuture** [comment]
[CE3V2_TUMBLER.3 Brokenmf.3mf.zip](https://github.com/Ultimaker/Cura/files/7499345/CE3V2_TUMBLER.3.Brokenmf.3mf.zip)

Slicing this only results in a raft on the later tumblers and the small ones do not get a raft

**Comment by fvrmr** [comment]
Hi @neofuture thank you for your project file.
So looking at your models. The first layers of those small models are not printed. If you enable thin walls, they are printed and also on the raft. 

![Screenshot (296)](https://user-images.githubusercontent.com/77000924/141315858-9b4b0c17-bb17-4cf9-b75d-7f03b1f52da8.png)

The best way to print this is using our Arachne build since that will have variable line widths. See here more about Arachne: https://github.com/Ultimaker/Cura/releases/tag/Arachne_engine_beta 

![Screenshot (297)](https://user-images.githubusercontent.com/77000924/141315901-ed2c51f8-2ea7-4c96-8596-9d9f5b589f47.png)

Let me know if that works for you!
