### ISSUE TITLE
Duplicate Preheat Buttons in Prepare Window

### ISSUE THREAD

**Issue by GLewisesq** [Ultimaker/Cura#10761]
### Is your feature request related to a problem?

Not a problem, just a constant inconvenience.

### Describe the solution you'd like

Adding the Preheat buttons to the Prepare window would eliminate the need to change windows every time you want to preheat or cancel preheating nozzle, bed, enclosure, etc.

### Describe alternatives you've considered

There are no alternatives other than preheating from the printer's controller itself.

### Affected users and/or printers

Benefits most if not all users.

**Comment by fvrmr** [comment]
Hi @GLewisesq thank you for your feature request.
I have discussed this with a colleague and we decided to reject this feature. 
The reason why is, we believe this will only benefit users who are using USB printing. And since we don't maintain USB printing anymore this is not something we would like to add. Also this will change our user interface a lot. 
I hope you understand!
