### ISSUE TITLE
Add CR-100 to the printer range please

### ISSUE THREAD

**Issue by bodyboarder2528** [Ultimaker/Cura#10771]
### Is your feature request related to a problem?

I got my kids a CR-100 and the Creality Slicer isn't nice to work with IMO.

### Describe the solution you'd like

Add support for the CR-100.

### Describe alternatives you've considered

I have tried other slicers and they don't support it either and I can't seem to get the custom FFF to work for the CR-100

### Affected users and/or printers

Kids learning to 3D print on these small cheaper machines.

### Additional information & file uploads

https://all3dp.com/1/creality-cr-100-review-3d-printer-specs/

**Comment by fvrmr** [comment]
Hi @bodyboarder2528 thank you for your feature request.
We don't maintain these profiles, we are depend by the community for committing these profiles.
You can create them your self and create a pull request or wait till someone else create them.
Read here more about creating those machine profiles: https://github.com/Ultimaker/Cura/wiki/Adding-new-machine-profiles-to-Cura 
If you have questions about creating them, please reach out. 

I will close this issue since this is something we won't do, I hope you understand!
