### ISSUE TITLE
Create Sets of Code to send to the Printer using "Send GCode"

### ISSUE THREAD

**Issue by marius-lu** [Ultimaker/Cura#10803]
### Is your feature request related to a problem?

It is hard to send repetitive codes to the printer when you want to test something.
I always have to save them separately in a file.

### Describe the solution you'd like

It would be nice to have a few sets of code that contains a few command lines and send those GCodes to the printer by a click of a button.
For example create a few lines of code and save those lines with a title.
This titles shows like a button , and when you click it, those set of code will be send to the printer.
It would be useful when you want to test something or send some repetitive codes.
For example "move Print bed to front and move X axis up" it would be like a button with a set of commands saved that you can customize and run any time by click of a button.

It would be nice to be able to create and save any sets of commands.
Location: in "Monitor" tab, near "send gcode" command.

### Describe alternatives you've considered

N/A

### Affected users and/or printers

N/A

**Comment by fvrmr** [comment]
Hi @marius-lu thank you for again a feature request. :) 
Like the other feature request this is also related to USB printing and is not a priority for us, since we don't maintain the USB printing anymore. 
A good solution for this is to use Printrun: https://www.pronterface.com/ where you have a better control of your printer via USB. Which is easier than sending a file. 
I will also close this issue and mark it as won't do. I hope you understand!
