### ISSUE TITLE
adding materials 

### ISSUE THREAD

**Issue by nevington** [Ultimaker/Cura#10808]
### Application Version

4.12.0

### Platform

windows 10

### Printer

creality cr6se

### Reproduction steps

tried to add a material from the store 

### Actual results

was not added to the dropdown menu however the files  were added to the destination folder but are not being read and seen by the program so that when i look up filements it isnt there 

### Expected results

the filement should have been in the drop down menu

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

.

**Comment by fvrmr** [comment]
Hi @nevington thank you for your report. 
The materials in the Marketplace are compatible for Ultimaker printers with 2.85mm filament. Since you're printer is using 1.75mm filament it is not showing up.
See also https://github.com/Ultimaker/Cura/issues/6236

I will close this issue since it is a duplicate.
