### ISSUE TITLE
Cura Crashes when clicking file open, or drag and drop file to open

### ISSUE THREAD

**Issue by HobdenDesign** [Ultimaker/Cura#10830]
### Application Version

4.12

### Platform

Windows 10

### Printer

Ender 3

### Reproduction steps

https://www.loom.com/share/ebf512421b6d4b1995dc2af56d443b66

Please respond to hobdendesign@gmail.com!

Thanks 
Arhtur

### Actual results

Program Crashes

### Expected results

I should be able to open a file

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/7535055/cura.log)

**Comment by fvrmr** [comment]
Hi @HobdenDesign thank you for your report and video! 
In your video I noticed you also have Chitubox installed and the thumbnail previewer of Chitubox is causing this issue.
See also here: https://github.com/Ultimaker/Cura/issues/9668
There are two workarounds to fix this:
1. Uninstall Chitubox completely and continue using Ultimaker Cura

2. Uninstall the Chitubox thumbnail preview, by following these steps:
 - Open cmd with administrator rights
 - Enter the command: regsvr32 /u "C:\Program Files\<path to CHITUBOX_Thumbnail.dll>"
 - Restart the resource manager

I will close this issue since it is a duplicate. But please reach out if you have more questions.
