### ISSUE TITLE
cura 4.12 Bounce

### ISSUE THREAD

**Issue by yomyong2** [Ultimaker/Cura#10844]
### Application Version

4.12

### Platform

windows 10

### Printer

custom fff

### Reproduction steps

When I go into "cura" and bring in the stl file, "cura" bounces right away.

### Actual results

Cura bounce.

### Expected results

Even if I upload all the other files, it won't budge.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

There's no file to upload

**Comment by vipertech17** [comment]
mine does the same. program shuts down when trying to import an stl file. weather i drag and drop or use the folder icon on upper left hand corner of cura.

**Comment by yomyong2** [comment]
I solved that problem. When Korean is included in the cura installation path, errors come out.

**Comment by fvrmr** [comment]
Hi @yomyong2 thank you for your report. Good to know that you already solved it. See also this issue: https://github.com/Ultimaker/Cura/issues/9644

@vipertech17 is this also the case for you? Or do you have Chitubox installed? See otherwise here: https://github.com/Ultimaker/Cura/issues/9668

I will close this issue since it is a duplicate.
