### ISSUE TITLE
Gcode from manual settings different than gcode from saved project 3mf

### ISSUE THREAD

**Issue by Wikunia** [Ultimaker/Cura#10986]
### Application Version

4.11.0

### Platform

Linux

### Printer

Custom FFF Printer

### Reproduction steps

1. Downloaded https://www.thingiverse.com/thing:1682665
2. Opened cura and imported files: 
- TurdEmoji-dual-mat1.stl
- TurdEmoji-multi-mat2.stl
- TurdEmoji-multi-mat3.stl
3. Created custom FFF printer with three extruders (PLA, Nylon, TPU 95A)
4. Merged models 
5. Moved to 0,0,1
6. Generate support for dual mat 1
7. Nylon for mat2
8. TPU for mat3
9. Slice
10. Saved as stl_sliced.gcode
11. Save project as emoji.3mf
12. Restart cura
13. Open emoji.3mf as project and create new printer settings (see summary-cura-project.png)
14. Slice
15. Save as 3mf_sliced.gcode

### Actual results

The gcode files aren't identical which is unexpected. In this small example they are only off after about 50% of the gcode in the third decimal place but afterwards they are of course incomparable.
 

### Expected results

I expected that the gcodes will be the same as otherwise it doesn't seem that saving it as a 3mf file stores all the information.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

The project file, two gcodes, the screenshot and the cura log for both runs combined.
[cura_bug_report.zip](https://github.com/Ultimaker/Cura/files/7640468/cura_bug_report.zip)

I'll open another issue shortly as the 3mf also produces completely different results on a Mac. #10987

**Comment by Ghostkeeper** [comment]
In the g-code diff, it can be seen that the difference is that the E value is off by 10-20 nanometres in some of the lines, because some of the model's coordinates ended up 1 micrometre differently at some point halfway.

I believe this is a rounding error due to the 3MF format. When re-saving models to a different format, rounding errors are bound to occur. Different formats have different precision levels. In this case, the STL is stored in binary STL format, which uses 32-bit floats. The 3MF format doesn't specify a precision level as far as I know, but it does specify that the coordinates need to be stored as decimal text. Cura effectively stores it as fixed-point with 7 decimals, so down to 0.1nm precision. Conversion from floating point to fixed point has rounding errors. In this case, in those half a million lines of g-code, one of them was rounded differently.

I agree that they are different and it makes them difficult to compare with text-based diff tools, but I think this is not something we can really solve since decimal is never going to map to floating point without rounding errors. What's more, there is no practical difference between these g-code files. Arguably, to get a meaningful diff between g-code files you'd have to show only the differences that are significant enough to at least land on different steps of some of the motors.
