### ISSUE TITLE
Add pull tab to skirt.

### ISSUE THREAD

**Issue by Slopecarver** [Ultimaker/Cura#11004]
### Is your feature request related to a problem?

I'm always frustrated when the print removes easily but the skirt is difficult to get a grip on, always requiring a tool to get under the edge to peel it off.

### Describe the solution you'd like

Add a half round tab to the skirt the full line count width of the skirt, maybe have some customizable attributes like radius and  center offset.

### Describe alternatives you've considered

A non-spiral interrupted skirt with a tiny tab on one end would serve the same purpose.

### Affected users and/or printers

any FDM with a skirt

**Comment by fvrmr** [comment]
Hi @Slopecarver thank you for your feature request. 
I have discussed it with the team and we decided to reject this request because we think that if you want to remove the skirt easily with a pull tab you need multiple layers. And this is not something we want to implement. 
I will close this issue, I hope you understand.
