### ISSUE TITLE
Cura 12.4.1 Support Fail 

### ISSUE THREAD

**Issue by RickCam20** [Ultimaker/Cura#11026]
### Application Version

4.12.1

### Platform

Windows 10

### Printer

Ender 3 Pro

### Reproduction steps

1. Upload STL
2. Enable Support Material 
3. Select Slice 

### Actual results

Support Material is broken up or unsupported. Likely resulting in a failed print 

### Expected results

To have unbroken and fully supported and connected support material 

My co worker still had Cura 4.11.0 installed on his computer and it sliced the part perfectly 

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

![bug](https://user-images.githubusercontent.com/95660861/144941104-5779065f-cb37-42e2-8ab4-f94ccd674cd1.JPG)
[bug.zip](https://github.com/Ultimaker/Cura/files/7664273/bug.zip)

**Comment by fvrmr** [comment]
Hi @RickCam20 thank you for your report.
If you change your `Support x/y distance` to 0.4mm and disable the `support roof`. The support will be printed correctly.
The support x/y distance indicates how much distance must be kept horizontally between the support and the model. And since the upper part was really thin. 0.8mm was to far from the model resulting in support not showing up correctly.
If you want to use the support roof you can change the support roof pattern.
![Capture-support](https://user-images.githubusercontent.com/77000924/144999563-aeb99fa6-bbfc-41e4-b411-480df49723fd.PNG)

I will close this issue since this would solve your problem. But please feel free to reach out if you have more questions.
