### ISSUE TITLE
Cura Quitting right after installation

### ISSUE THREAD

**Issue by cloudy-fem** [Ultimaker/Cura#11039]
### Application Version

4.12

### Platform

OS X Yosemite & OS X EI Capitan

### Printer

Ultimaker 2

### Reproduction steps

I downloaded the file directly from the website, then make the file appear as an application in the Applications folder.
Once I try to open Cura it immediately quits unexpectedly. Maybe look into this?

### Actual results

A report is sent to Apple in which I try again so I can read over the "details" section.

### Expected results

It should Open like it normally does, but it refuses to do so.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Recently, our Imac's and windows computers have not been working as they should. Only one turns on correctly, but it refuses to run cura as it closes/quits unexpectedly when trying to open. Maybe check that out? (this is what happens from our side)

**Comment by fvrmr** [comment]
Hi @cloudy-fem thank you for your report. 
We don't support MacOS Yosemite and MacOS El Caption anymore since Apple stopped supporting this as well.
See here which operating systems we support: https://support.ultimaker.com/hc/en-us/articles/360011889579-On-what-operating-systems-is-Ultimaker-Cura-available- 
I will close this issue since this is something I can't help you with.
