### ISSUE TITLE
"Brim only on Outside" does not work

### ISSUE THREAD

**Issue by normkawakami** [Ultimaker/Cura#11064]
### Application Version

4.12.1

### Platform

Windows10

### Printer

Ender3 V2

### Reproduction steps

1. Sliced with CURA 4.12.1 with "Brim only on outside" checked, but inner brim were also made. 
![CURA_BRIM](https://user-images.githubusercontent.com/58285095/145772016-e1cf3012-05de-4a3a-ae38-d660d9e13594.png)

2. With other model,  "Brim only on outside" was un-checked, but only outside brim was made. 
![CURA_Brim2](https://user-images.githubusercontent.com/58285095/145772273-7b011c62-6f92-49cd-b065-9653c65058f0.png)

### Actual results

1. Inner brims were made.
2. Only outer brim was made.

### Expected results

1. Only outside brim should be made.
[CE3_eagle-Wing5_LW-left-profile3.zip](https://github.com/Ultimaker/Cura/files/7702876/CE3_eagle-Wing5_LW-left-profile3.zip)

2. Inner brims should be made.
[CE3_eagle-Wing6_LW-left-profile3.zip](https://github.com/Ultimaker/Cura/files/7702877/CE3_eagle-Wing6_LW-left-profile3.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[CE3_eagle-Wing5_LW-left-profile3.zip](https://github.com/Ultimaker/Cura/files/7702926/CE3_eagle-Wing5_LW-left-profile3.zip)
[CE3_eagle-Wing6_LW-left-profile3.zip](https://github.com/Ultimaker/Cura/files/7702927/CE3_eagle-Wing6_LW-left-profile3.zip)

**Comment by fvrmr** [comment]
Hi @normkawakami thank you for your report. 
Both your files show model errors and probably this is related to the brim only on outside not showing up correctly.
![Capture-model-errors](https://user-images.githubusercontent.com/77000924/145961348-354ad73d-838f-4045-a19e-8ba96aaa987d.PNG)

Because if I slice a model with your settings it is working correctly.
Brim only on outside disabled: 
![Capture-brimoutside-disabled](https://user-images.githubusercontent.com/77000924/145961482-7e23fbb8-cf47-4688-ba8d-d948b55b478a.PNG)

Brim only on outside enabled:
![Capture-brimoutside-enabled](https://user-images.githubusercontent.com/77000924/145961605-0dc3e00d-3869-4c19-9e0f-5eafcdc7fc9c.PNG)

So I think you need to check your models and make sure that there are no model errors.

**Comment by normkawakami** [comment]
Hi Fenne,
Thank you for your investigation.
I have understood that the reason is model error. 
I will ask this issue to the model maker.

Norm Kawakami
Japan  

Windows の メール から送信

差出人: Fenne
送信日時: 2021年12月14日 18:09
宛先: Ultimaker/Cura
CC: normkawakami; Mention
件名: Re: [Ultimaker/Cura] "Brim only on Outside" does not work (Issue #11064)

Hi @normkawakami thank you for your report.
Both your files show model errors and probably this is related to the brim only on outside not showing up correctly.

Because if I slice a model with your settings it is working correctly.
Brim only on outside disabled:

Brim only on outside enabled:

So I think you need to check your models and make sure that there are no model errors.
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Ghostkeeper** [comment]
I think the first one is a case of https://github.com/Ultimaker/Cura/issues/4222.

The second one is indeed possibly a model error. It should produce a brim on the inside, but if the model is not manifold, Cura may think that the hollow inside gets filled with infill/skin.
