### ISSUE TITLE
Remove settings on by default

### ISSUE THREAD

**Issue by ptrakk** [Ultimaker/Cura#11105]
### Application Version

4.13 beta

### Platform

windows 10

### Printer

creality

### Reproduction steps

upgrade cura. it removed all my profiles by default. 
Why would you ever do this?
it's lost.. my profiles..

### Actual results

Fresh Cura, no custom printers, no material profiles, settings gone. 

### Expected results

it should have a check box (default unchecked) on the uninstaller to ask to clear settings and files.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

pls wow

![image](https://user-images.githubusercontent.com/2153952/147014885-9272b520-a50d-408a-99c3-47f92e558ba8.png)

**Comment by fvrmr** [comment]
Hi @ptrakk thank you for your report.
When installing a new version of Cura you will get the question keep old configurations of Cura. But we are aware that this is not clear for our users. See https://github.com/Ultimaker/Cura/issues/8233
Also good to know is that you can have multiple versions of Cura on your computer.
I will close this issue since it is a duplicate.

**Comment by ptrakk** [comment]
thanks
