### ISSUE TITLE
TypeAMachines Cannot create custom materials

### ISSUE THREAD

**Issue by darkbushido** [Ultimaker/Cura#11156]
### Application Version

4.12.1

### Platform

Windows 11

### Printer

TypeAMachines Series 1 2014

### Reproduction steps

1. Open Preferences
2. Add a new printer
3. Add a non-networked printer
4. Select TypeAMachines Series 1 2014
5. Make sure the new printer is activated
6. Goto Materials

### Actual results

All of the Material options are disabled

[prnt.sc](https://prnt.sc/2558fe8)

### Expected results

Using a TypeAMachine shouldn't prevent me from creating materials.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

The only reason to use the TypeAMachines type is the Cool build plate so this isn't a large issue.

**Comment by fvrmr** [comment]
Hi @darkbushido thank you for your report.
All our third party printers are contributed by our community. So this how we received the printer definitions. 
When you check the definition file `tam.def.json` you can see `"has_materials": false`: https://github.com/Ultimaker/Cura/blob/master/resources/definitions/tam.def.json#L12

This is something we won't change since we don't maintain third party printers. I hope you understand.
