### ISSUE TITLE
Unsupported High Sierra

### ISSUE THREAD

**Issue by kpishere** [Ultimaker/Cura#11189]
### Application Version

4.9+

### Platform

MACOS

### Printer

Custom

### Reproduction steps

Build does not work with High Sierra.  

Sorry, guys, you lost me.  I'm not upgrading past High Sierra because I need 32bit app support for various maker projects on micro controllers and I'm not about to move away from build chains that are 32 bit.

So, you've lost me.  SuperSlicer makes ARM and i386 based releases and they work just fine on High Sierra.

I think you are making a mistake.

### Actual results

Does not work

### Expected results

Expected it to work

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

none.

**Comment by fvrmr** [comment]
Hi @kpishere thank you for your report. 
We don't support High Sierra anymore because Apple stopped supporting this OS with security updates. That is a choice we made because we can't keep supporting older versions unfortunately. For us it means that we don't test Cura on older OS's but that doesn't mean Cura is not working on those OS's. In your case it is unfortunately. 
The latest version of Cura that is supported on High Sierra is 4.10: https://github.com/Ultimaker/Cura/releases/tag/4.10.0

I will close this issue since this is something we won't change. I hope you understand.
