### ISSUE TITLE
Option to select other languages or at least option to set in config file

### ISSUE THREAD

**Issue by VladimirVecera** [Ultimaker/Cura#11183]
### Application Version

4.12

### Platform

Windows 10 64bit

### Printer

Creality Ender 3 v2

### Reproduction steps

The language setting does not contain everything from the ./i18n/ languages folder 

### Actual results

Nothing, I can't choose the other languages I would like to choose. Although the language is probably a beta version, I would like to be able to choose it. Which, of course, is not the case. 

### Expected results

Possibility to select other languages or at least the possibility of setting in the config file. Just have a choice! 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

How do I set up other languages that are in the i18n folder and can't be selected directly in the program itself?

![image](https://user-images.githubusercontent.com/64955913/147861997-38f702f5-4048-42be-8bb4-87179f457911.png)

**Comment by fvrmr** [comment]
Hi @VladimirVecera thank you for report.
I will bring this up with the team. Keep you posted!

**Comment by Ghostkeeper** [comment]
The Cura interface explicitly hides some languages because they are not complete. That is not up to our quality standards so languages that are not complete will not get shown.

You can still change the language in the `cura.cfg` file to languages that are not complete. In `C:\Users\<username>\AppData\Roaming\cura\<version>\cura.cfg`, you would add a field called `language` under `[general]` that refers to the language code, like so:

![image](https://user-images.githubusercontent.com/2448634/149128649-199b03a1-b83b-44a4-9413-01a6aa5aee2b.png)

This allows you to select the languages that are incomplete (currently `fi_FI` and `hu_HU` and `pl_PL`).

**Comment by fvrmr** [comment]
We have discussed it with the team and all the languages are selectable in the next release even if they are not completely translated. See the linked pull request above.
