### ISSUE TITLE
Support interface has gaps if z-distance is set to 0

### ISSUE THREAD

**Issue by Doccos** [Ultimaker/Cura#11190]
### Application Version

4.12.1

### Platform

Windows 10

### Printer

Selfmade

### Reproduction steps

Set Support interface extruder to EXT2
Set Support z Distance to 0 (i use soluble material)
Slice

### Actual results

When z-distance is 0 then there are gaps in the support interface.
If z-distance > 0 there are no gaps

### Expected results

a clean support interface when z-distance is set to 0

With z-distance 0.1
<img width="1414" alt="z-dist-1-l0" src="https://user-images.githubusercontent.com/20592470/147903033-a80f3085-0e04-4266-834b-bca8ac8f4600.PNG">
<img width="1446" alt="z-dist-1-l1" src="https://user-images.githubusercontent.com/20592470/147903041-f9477628-ad56-4734-9595-fa44351ea1c0.PNG">

With z-distance 0

<img width="1367" alt="z-dist-0-l0" src="https://user-images.githubusercontent.com/20592470/147903059-72f8ab37-aaff-43ce-a6d7-337c75da89c3.PNG">
<img width="1430" alt="z-dist-0-l1" src="https://user-images.githubusercontent.com/20592470/147903064-c2a612f7-9ac0-42e5-9d30-13b674ee9a0f.PNG">

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

Project file:
[blende.zip](https://github.com/Ultimaker/Cura/files/7800584/blende.zip)

**Comment by fvrmr** [comment]
Hi @Doccos thank you for your report.
Could you share your printer definition file with me? I can't open your project file because it is missing your printer definition. 
And if I follow your reproduction steps I am not able to reproduce this.

You can find your printer definition here: `C:\Program Files\Ultimaker Cura 4.12.1\resources\definitions` and the definition files for your extruders here: `C:\Program Files\Ultimaker Cura 4.12.1\resources\extruders`

**Comment by Doccos** [comment]
Thanks for the answer.

I tried it now with a clean installation of cura on a other PC.
As printer a choosed "Raise3D N2 Plus Dual"

I attach the new screenshot and project file here
[blende2.zip](https://github.com/Ultimaker/Cura/files/7829394/blende2.zip)
![cura_gap](https://user-images.githubusercontent.com/20592470/148559309-ac217588-ef2f-4991-aa30-47c59ab2778b.PNG)

**Comment by fvrmr** [comment]
Thank you, I can now reproduce your issue. 
I will bring it up for discussion. Keep you posted!

**Comment by fvrmr** [comment]
I have discussed it with the team and decided to defer this issue. Since we believe it is an edge case and model specific. Also we think that it would affect the print quality, since the gaps are small.
I hope you understand.

**Comment by sebastiankuzminsky** [comment]
Hi there, this bug is affecting us as well.
I can reproduce this by slicing in 4.13.1 for an Ultimaker S5, using the "Default / Fast" profile but with "Support Z Distance" set to 0.  (I also disabled Build Plate Adhesion and changed the Support Density to 100% to make the problem clearer, it happens without these changes but is harder to see.)
My model looks like this:
![Screenshot from 2022-04-12 11-48-30](https://user-images.githubusercontent.com/46073098/163002873-db17cdb8-932d-4171-957e-3c808a6553f6.png)
The top layer of the support has the most obvious problem, though there are glitches on lower layers as well.  The problem occurs whether or not Support Roofs are enabled:
![Screenshot from 2022-04-12 11-50-17](https://user-images.githubusercontent.com/46073098/163003075-ef277ae3-b865-4148-b6eb-0d60bf2ccfdb.png)
This view from below shows the top layer of the support and the layer immediately above, showing clearly how parts of the model are unsupported:
![Screenshot from 2022-04-12 11-50-40](https://user-images.githubusercontent.com/46073098/163003234-58d3eaec-24f3-46ea-bec6-120cc62aebfc.png)

[UMS5_35_10113_40_r24 (mm).3mf.zip](https://github.com/Ultimaker/Cura/files/8474574/UMS5_35_10113_40_r24.mm.3mf.zip)

**Comment by sebastiankuzminsky** [comment]
Setting `Support Stair Step Height` to 0 works around the problem for me (and note that in my case, the faulty support is resting on the print bed, not on the model, so support stairs are not relevant).
