### ISSUE TITLE
USB printer connection

### ISSUE THREAD

**Issue by petethefree** [Ultimaker/Cura#11194]
### Application Version

4.12.1

### Platform

Windows 10

### Printer

Flashforge Finder

### Reproduction steps

Attached Flashforge Finder to my PC via USB
Used Flashprint and it could see the printer.
Used Cura and it could not.

### Actual results

Inability to control the printer via Cura

### Expected results

I should be able to use the printer via Cura

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

No additional files are needed I think
[cura.log](https://github.com/Ultimaker/Cura/files/7804457/cura.log)
Random project file

![James'_blue_cat](https://user-images.githubusercontent.com/64787155/147990351-3d98289d-1a1d-4f41-a620-0fd93523228d.png)

**Comment by fvrmr** [comment]
Hi @petethefree thank you for your report (and the cat 🐱 )
We don't maintain USB printing anymore since our printers doesn't use USB printing.
You can check if the USB printing plugin is disabled. Go to marketplace - installed. If it is disabled you can enable this. 

![image](https://user-images.githubusercontent.com/77000924/148086011-23c0b6ac-f8f1-4d0d-b237-eedf8387136a.png)
_When this is enabled Cura can interacts with other microcontrollers: https://support.ultimaker.com/hc/en-us/articles/4407742254610-Ultimaker-Cura-interacts-with-microcontrollers_

However printing via USB in Cura is not something I would recommend, it is better to use a SD card or Octoprint. If you want to use USB print you can use Printrun. 

I will close this issue since this is something we won't fix. I hope you understand.
