### ISSUE TITLE
Error de configuración de Cura

### ISSUE THREAD

**Issue by jpinto845** [Ultimaker/Cura#11212]
### Application Version

4.12.0 y 4.12.1

### Platform

windows 10

### Printer

i3

### Reproduction steps

Buenos días
 Al insertar el archivo  *.stl me sale en miniatura o con un escalado exagerado. El archivo stl no sale escalado
Gracias y un saludo

### Actual results

![image](https://user-images.githubusercontent.com/36484249/148529841-f1f7a9df-5bca-40ee-b5e1-440d617ed088.png)
![image](https://user-images.githubusercontent.com/36484249/148530041-cc972ef8-b590-4b6b-8a89-c60ef6d876a8.png)

### Expected results

Arreglo del sistema o decir como se arregla en mi caso

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

[PI3_Enr cabl ext m12.zip](https://github.com/Ultimaker/Cura/files/7828215/PI3_Enr.cabl.ext.m12.zip)

**Comment by fieldOfView** [comment]
Please use english in this issue queue. If you need support in spanish, I can recommend the spanish subsection of the Ultimaker Community forum here: https://community.ultimaker.com/forum/125-espa%C3%B1ol/

It looks like you may be modeling in inches. Unfortunately the STL format has no way to specify a unit, and Cura assumes the unit to be mm. There are a couple of ways around this:

* save your model as 3mf instead of stl; the 3mf format can specify the units, which will be properly interpreted by Cura
* model in mm, not in inches
* install the Barbarian Units plugin from the marketplace, and use it to set the scale after importing
* install the Mesh Tools plugin from the marketplace, and set the option to automatically interpret the STL file to use inches instead of mm, scaling the model as it is imported
