### ISSUE TITLE
Slice incomplete

### ISSUE THREAD

**Issue by DeCaff24** [Ultimaker/Cura#11234]
### Application Version

4.12.1 and 4.8.0

### Platform

Windows 10

### Printer

Malyan M200

### Reproduction steps

1: I made a test cube 20x20x20mm with a few fillets. I added debossed "Text" to one side and embossed "Text" to the (top)side.
2: saved it to stl and alligned it as described above in Cura 4.12.1 and 4.8.0. Sliced it and printed it. 
3: Printer started on making the embossed first T but stopped there.
4: I checked the slicer and saw that Cura didn't completely finish the Text on top.

![image](https://user-images.githubusercontent.com/88878619/148793990-36dfb9b4-2257-4732-b915-46eec0d16883.png)
stl file

![image](https://user-images.githubusercontent.com/88878619/148794140-efc73315-9442-4f4e-befc-0520b3820a5b.png)
prepare screen Cura

![image](https://user-images.githubusercontent.com/88878619/148794265-377d8664-1452-4b0c-ab8c-7bc548107c00.png)

Slicer Preview. see that it diDn't include the embossed text on the top

### Actual results

Printed object was missing the embossed text

![image](https://user-images.githubusercontent.com/88878619/148795195-e1bffaba-b55e-4485-9661-40a6b52ce8ab.png)

### Expected results

The slicer should have included the embossed text and it should have been on the printed object

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[MM_Cube 20x20.zip](https://github.com/Ultimaker/Cura/files/7840055/MM_Cube.20x20.zip)

**Comment by fvrmr** [comment]
Hi @DeCaff24 thank you for your report.
This is probably happening because your text is too thin. Slicing your model in our Arachne release, it will show the text perfectly. Because with Arachne uses variable line width. 
![Capture(237)](https://user-images.githubusercontent.com/77000924/149318012-cd3bd496-3210-480e-9597-2802a8b13061.PNG)

Read here more about the Arachne release: https://github.com/Ultimaker/Cura/releases/tag/Arachne_engine_beta_2

I will close this issue since we planned to implement the Arachne Engine in Cura 5.0
I hope you understand!

**Comment by Ghostkeeper** [comment]
For the stable release, Print Thin Walls may also help (but tends to produce worse results than Arachne for such things).
