### ISSUE TITLE
This setting has been hidden by the active machine and will not be visible

### ISSUE THREAD

**Issue by houtanmovafagh** [Ultimaker/Cura#11237]
### Application Version

4.13.0 beta

### Platform

Windows 10

### Printer

Creality Ender 3 Pro

### Reproduction steps

Hi,

When i click on the setting visibility view, there are multiple parameters that have an "i" icon next to it.  When i hover over the icon, i get a pop up that says, "This setting has been hidden by the active machine and will not be visible".  When i select the box to show the setting, and close the view, that setting still does not appear in my slicer settings.  This was also occurring in 4.12.x.  Can you please tell me how to get these settings to appear after i have selected the checkbox?

Thanks,
houtan

### Actual results

The parameter does not appear in my slicer settings.

### Expected results

Per my online research, the setting should appear after i have put a check in the checkbox.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

NA

**Comment by GregValiant** [comment]
Not all settings are available for all printers.  For instance the Dual Extrusion settings are not available for a single extruder printer.  What is the particular setting(s) you are trying to enable?

**Comment by houtanmovafagh** [comment]
Hi Greg,

Thanks for the reply!

The setting is “scaling factor shrinkage compensation” under the Material header.  Picture is attached as well. 

Thanks,
Houtan

**Comment by GregValiant** [comment]
That setting is disabled for all printers by default.  There might be a printer out there it is enabled for but it would have to be an explicit override in that printer's definition file.
A workaround is to manually scale the model up by the shrink factor of the material you are using.

**Comment by houtanmovafagh** [comment]
Thanks Greg.  I am printing a file with some tight tolerances and someone posted they set X, Y shrinkage in CURA to .2 mm which provided enough clearance for a few parts to not be fused together.  Am I looking at the wrong option?

Thanks,
Houtan

**Comment by GregValiant** [comment]
With your model selected - on the left is a column of buttons.  The second from the top is the scale tool.  When you click on the scale tool a dialog pops up and you can set either % scale, or numeric scale.  A check box indicates whether you want the Axes locked together or you can scale them separately.  There are also grips on the model when the tool is selected.
It is always better to take care of tolerancing in CAD but we don't always have the CAD model, just an STL.  MS 3D Builder can be used to scale a model as well.  After scaling remember to use the Translate Tool (move tool) and check the Z because dependent on what other options you have set the model may not be exactly on the build plate after scaling.

**Comment by Ghostkeeper** [comment]
> The setting is “scaling factor shrinkage compensation” under the Material header.  Picture is attached as well.

This setting was originally added under the name "Shrinkage factor" and was set by some material profiles to make Cura give a warning when printing big things with materials that have big shrinkage factors.

For Cura 4.8 we wanted to implement something that would compensate for this shrinkage, and made that setting visible as a compensation setting. To not suddenly make all ABS prints 2% bigger for everyone we set the defaults for all materials to 0% (planning to set them back after testing exactly how much it shrinks in practice). However the compensation didn't work well so we hid the setting again. We left the profiles at 0% so this warning currently doesn't trigger sadly. But we left the setting in since we do intend to complete the implementation.

**Comment by Ghostkeeper** [comment]
I'll close this since the hiding of settings seems to be working as expected.

**Comment by houtanmovafagh** [comment]
Sorry for the late reply. I just wanted to say thank you for taking the time to reply to my request and help me understand what’s going on. I really appreciate it. Have a great week. 

Thanks,
Houtan
