### ISSUE TITLE
Don't iron sacrificial layers

### ISSUE THREAD

**Issue by Matszwe02** [Ultimaker/Cura#11281]
### Is your feature request related to a problem?

every perfectly printed sacrificial layer gets destroyed during ironing, even the ironing isn't useful at all

### Describe the solution you'd like

detect if there's more than 2 solid infill layers in a row (in the area where there will be ironing added), and only then iron them.

### Describe alternatives you've considered

-

### Affected users and/or printers

everyone

### Additional information & file uploads

![image](https://user-images.githubusercontent.com/49353902/149771440-8c96d3ec-4e68-4ff0-aa31-c935009a2b03.png)

**Comment by fvrmr** [comment]
Hi @Matszwe02 thank you for your feature request.
I have discussed it with one of the Cura developers and we decided to reject this feature request. 
It would be very complex to implement this, since you need to create a setting to detect if there are 2 solid infill layers which is not very easy and also not something we would like to have.

A workaround for this is using modifier meshes where you can overlap with your model and then select ironing for that selected area. Read here more about modifier meshes: https://support.ultimaker.com/hc/en-us/articles/360013370140-How-to-adjust-print-settings-of-a-part-of-my-model-in-Ultimaker-Cura
