### ISSUE TITLE
ERROR WITH THE PRINT

### ISSUE THREAD

**Issue by PopiTech** [Ultimaker/Cura#11325]
### Application Version

4.13.0

### Platform

Windows 10

### Printer

Geeetech A20T

### Reproduction steps

The software connects to the printer as I see the functions, but does not invade the printing

### Actual results

USB printer connection to pc and open the software

### Expected results

should print the object

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

no other comment

**Comment by fvrmr** [comment]
Hi @PopiTech thank you for your report.
You can check if the USB printing plugin is disabled. Go to marketplace - installed. If it is disabled you can enable this.

![image](https://user-images.githubusercontent.com/77000924/151009911-b2484293-81c1-4ac7-907a-f305d7f22d66.png)

_When this is enabled Cura can interacts with other microcontrollers: https://support.ultimaker.com/hc/en-us/articles/4407742254610-Ultimaker-Cura-interacts-with-microcontrollers_

However printing via USB in Cura is not something I would recommend, it is better to use a SD card or Octoprint. If you want to use USB print you can use Printrun.

I will close this issue since this is something we won't fix. I hope you understand.
