### ISSUE TITLE
Color Scheme: Temperature

### ISSUE THREAD

**Issue by c9498** [Ultimaker/Cura#11432]
### Is your feature request related to a problem?

Not related to a problem. 

### Describe the solution you'd like

It would be nice to have a graphical representation of hot end temperature in the color scheme dropdown, (like flow). It would be useful for to verify where temperature changes  are occurring particularly when setting up calibration. (Temp towers etc)
Thanks

### Describe alternatives you've considered

None

### Affected users and/or printers

All

**Comment by fvrmr** [comment]
Hi @c9498 thank you for your feature request.
I will bring this up with the team. Keep you posted.

**Comment by fvrmr** [comment]
I have discussed it with the team and we decided to defer this request. I would be a nice to have though, but it will not get a high priority to implement this. Also temp towers will not work for this, since that is with the post processing script. And post processing scripts are not in visible in the preview, they will be processed while creating the gcode.

**Comment by tripletto** [comment]
This missing feature is actually the reason, I need to use Prusa Slicer as well. An implementation of a visual temperature preview would be greatly appreciated!

**Comment by donoit** [comment]
CURA does not have a temperature color scheme in its preview mode; feature is rejected - thats a pitty !!
