### ISSUE TITLE
Wall problems (very bad Quality) Cura 4.13

### ISSUE THREAD

**Issue by Bastlwastl84** [Ultimaker/Cura#11438]
### Application Version

4.13.1

### Platform

win10

### Printer

Voron 350

### Reproduction steps

Nozzle 0.6 and 0.8 (a bit lower with 0.4, but also happens here)

### Actual results

artefacts at rendered previe
![capture_20220208_220150_004](https://user-images.githubusercontent.com/69717507/153075712-41b30a8f-6b24-4b25-9809-436b6c9b2e76.jpg)
![capture_20220208_220218_005](https://user-images.githubusercontent.com/69717507/153075721-2f0cd524-b85d-4044-be69-77f8e50efe33.jpg)
w

### Expected results

no artefacts

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

also happens with prconfigured basic profiles

**Comment by GregValiant** [comment]
The white "artifacts" represent the Z seam location.  On the right side those look like an interference between the inner and outer walls and possibly Cura is showing it that way because the flow has been adjusted.  It could also be a defect in the model, or possibly a display issue.  A project file would likely tell the story.

**Comment by Ghostkeeper** [comment]
The adjusted flow on the right there is caused by the Wall Overlap Compensation setting. It is meant to give a more accurate result, at the cost of more flow changes.
