### ISSUE TITLE
Plugin SentryLogger Error

### ISSUE THREAD

**Issue by zawier-git** [Ultimaker/Cura#11509]
### Application Version

4.13.1

### Platform

Linux Garuda (5.16.10-zen1-1-zen #1 ZEN SMP PREEMPT Wed, 16 Feb 2022 19:35:21 +0000 x86_64 GNU/Linux)

### Printer

Cr10 S4

### Reproduction steps

Hi,
After running Cura  
![image](https://user-images.githubusercontent.com/81773334/154804233-d98e4afa-3408-4374-9696-41c03333d51e.png)

I see information like bellow:
![image](https://user-images.githubusercontent.com/81773334/154803659-61041d42-fe93-46bf-9ad8-d7e88d09f464.png)

Then when I remove it using button:
![image](https://user-images.githubusercontent.com/81773334/154803765-152a105b-5a6e-4798-b96c-64d7d076b369.png)

### Actual results

And after shutting down Cura and opening it one more time I still see the same problem with plugin.
Please , could you write a fix for that?

### Expected results

I was expecting that plugin will be removed and error message be gone. 

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

Here is my log file:
[cura.log](https://github.com/Ultimaker/Cura/files/8102310/cura.log)

**Comment by fieldOfView** [comment]
Use the AppImage provided by Ultimaker instead of the package you use now. Whoever built that package forgot to include required dependencies.

**Comment by zawier-git** [comment]
Ok, thank you for information.
Is there any instruction how to install it properly from AppImage? 
My attempt failed and error message was lead me into https://github.com/AppImage/AppImageKit/wiki/FUSE where I wasn't able to figure it out how to handle that on Garuda Linux (Arch based distro).

**Comment by fieldOfView** [comment]
The idea is you download the file, make it executable and double click the AppImage.

**Comment by fieldOfView** [comment]
You may want to read both answers here:
https://superuser.com/questions/1306621/install-appimage-under-arch-linux

**Comment by Ghostkeeper** [comment]
We don't maintain the Arch package. Please report this issue with the Arch package maintainers instead of here. We only support the AppImage. Arch Linux should support AppImages out of the box (as it only requires Fuse). I'm not aware what the changes would be for your flavour of Arch. Perhaps the suggestions here help as well: https://superuser.com/questions/1306621/install-appimage-under-arch-linux . We'll close this issue since it's a problem outside of our control.

The reason why you're getting the error is because even though Uranium doesn't create the PluginObject any more when the plug-in is disabled, it still registers the plug-in. To be able to provide the PluginObject, the register function imports the SentryLogger module, which has `sentry_sdk` in its imports (which it may assume exists in its runtime environment).
