### ISSUE TITLE
Cubic and tetrahedral infill patterns incorrect?

### ISSUE THREAD

**Issue by skepters** [Ultimaker/Cura#1150]
Maybe I'm wrong about what a tetrahedral and cubic pattern is, but I believe these two infill patterns are showing the other's actual pattern in layers view. In other words, with cubic selected the pattern looks tetrahedral in layers and with tetrahedral selected the patterns looks like it is cubic. I attached some pictures to help explain better. Maybe I'm not seeing these correctly or don't know what tetrahedral and cubic mean. Thanks.
![cubic](https://cloud.githubusercontent.com/assets/23490726/20332872/7c100bec-ab74-11e6-9f65-9868320f5999.JPG)
![tetrahedral](https://cloud.githubusercontent.com/assets/23490726/20332873/7c58c5b2-ab74-11e6-955c-8e1ab0b0f457.JPG)

**Comment by Ghostkeeper** [comment]
This gets asked once in a while, but they are correct.

The tetrahedra and cubes are oriented in such a way that there is as little overhang as possible.
* The tetrahedra are oriented such that one of the ribs is parallel to the build plate on the bottom, and the opposite rib is orthogonal to it, but still parallel to the build plate, on the top. It doesn't place one of the triangular sides parallel to the build plate because that would cause overhang. This results in rectangular cross-sections in Layer View. Note that it is impossible to be space-filling with regular tetrahedra, so between the tetrahedra are octagons.
* The cubes are oriented such that one of the corners points to the bottom, to minimise overhang. Since there are 3 sides touching each corner, the result is that the cross-section has triangles. The opposite corner of the cube points to the top (with again 3 sides adjacent to it). If you take a slice around the "tropics" of this cube, you get an irregular hexagon (6 corners).

People always associate "tetrahedron" with "triangle" and "cube" with "square", but that is not always the case if you take cross-sections.
