### ISSUE TITLE
writings

### ISSUE THREAD

**Issue by superfigo01** [Ultimaker/Cura#11523]
### Application Version

4.13.1

### Platform

Windows 10

### Printer

Ender3pro

### Reproduction steps

I have tried to slice an object with a flat written face placed on the bed (writings are embedded). When slicing it does not create the upper face of some of the writings
[CE3PRO_BUSSOLA_SX_OB_OFFSET_0.zip](https://github.com/Ultimaker/Cura/files/8112511/CE3PRO_BUSSOLA_SX_OB_OFFSET_0.zip)

### Actual results

When slicing it does not create the upper face of some of the writings

### Expected results

Create an upper face for the writings

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

doesn't work even when slicing it upside down. It works with other slicers

**Comment by GregValiant** [comment]
Cura is slicing the model according to your settings.

The "SX_0B" text is so narrow that your "Skin Removal Width" of 0.8 is interfering with the addition of skins on top of the letters.  Set "Skin Removal Width" to 0.4 and see how it looks in preview.

You have Initial Layer Horizontal Expansion set to -0.15.  Because the bottom lettering is so close to the edge of the model the outside loop is disappearing on the first layer.  I would set I.L.H.E. to "0" for this model.

Lastly, I would also enable support or the ceiling of the lower counterbore feature will print very poorly because the initial circles that comprise the inner and outer walls will be printing over air.

![image](https://user-images.githubusercontent.com/64202104/155139232-a2eecfcc-cf57-4517-8ab8-08dbca7e57e8.png)
