### ISSUE TITLE
Gaps in "top" layer. Only solution is clean slate fresh install.

### ISSUE THREAD

**Issue by pixie-wrangler-irl** [Ultimaker/Cura#11553]
### Application Version

4.13.1

### Platform

Windows 10

### Printer

FLSUN Super Racer

### Reproduction steps

Fresh install, add octoprint, side bar gui, enable dark mode, import saved profile.

Default profiles work, but changing number of top layers to any integer 7 or higher leads to this top layer defect.  Fresh install allows any number of "top layers" as expected.

### Actual results

![Cura Gap](https://user-images.githubusercontent.com/88962270/155837844-cf41e36f-a4fe-44b1-8094-62c3f0d1dc02.PNG)
.

The STL is a simple cylinder on top of another. The "top" layers of the lower cylinder do not go under the walls of the upper cylinder. Leading to parts with zero structural integrity if its even successful.

### Expected results

Expected result is top layers that go under the upper walls regardless of top layer count.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

[fail top layergcode.txt](https://github.com/Ultimaker/Cura/files/8146313/fail.top.layergcode.txt)
[failtoplayerSTL.txt](https://github.com/Ultimaker/Cura/files/8146314/failtoplayerSTL.txt)

**Comment by Ghostkeeper** [comment]
Indeed, both FLSUN SR profiles set that setting to 20°, [here](https://github.com/Ultimaker/Cura/blob/0e2848796c4f85a826bbcdd8e96c0c4504f74454/resources/quality/flsun_sr/flsun_sr_fine.inst.cfg#L30) and [here](https://github.com/Ultimaker/Cura/blob/0e2848796c4f85a826bbcdd8e96c0c4504f74454/resources/quality/flsun_sr/flsun_sr_normal.inst.cfg#L30).

We can remove that override so that it defaults back to 90°. You've tested that this works better and it's probable that this indeed extrapolates to other models. At worst, it'll cost a bit more time to print. I'll change it for you.
