### ISSUE TITLE
Unnecessary Support Generated in one direction only

### ISSUE THREAD

**Issue by balloonhotair** [Ultimaker/Cura#11692]
### Application Version

4.13.1

### Platform

Windows 7

### Printer

Custom Qidi X-Max

### Reproduction steps

Created supports for the model. An extra support on the left side outside the model is created that goes no where. If you rotate the model 90 degrees in any direction the extra support is not created.

### Actual results

You get an extra support.

### Expected results

No extra support.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[Bat_3_holder.zip](https://github.com/Ultimaker/Cura/files/8311755/Bat_3_holder.zip)

**Comment by fvrmr** [comment]
Hi @balloonhotair thank you for your report.
If you disable Use Towers that extra support will not be generated.
![Capture(304)](https://user-images.githubusercontent.com/77000924/159270562-a244b439-2cc3-479d-979e-85b065ad2ec7.PNG)
I will close this issue, since that will solve your issue. If you have questions feel free to reach out.
