### ISSUE TITLE
Incorrect slicing

### ISSUE THREAD

**Issue by jmgk77** [Ultimaker/Cura#11702]
### Application Version

4.13.1

### Platform

windows, linux

### Printer

ender 3, others

### Reproduction steps

Hi,

i got users reports that the file [borboleta2.stl](https://github.com/jmgk77/LAMPADA/blob/main/STL/borboleta2.stl) is wrong, that the thread is filled. The model is a FreeCad generated one.

![borboleta2](https://user-images.githubusercontent.com/46632344/159765749-1fd0ed78-eee7-45d7-9b15-f7238bb0c9dd.png)

Investigating, i found that Cura isnt generating correct gcode. The cura gcode in a [viewer](https://gcode.ws/):

![cura](https://user-images.githubusercontent.com/46632344/159766289-a69d6985-774e-4342-8be2-caba72af146f.png)

The PrusaSlicer (or SuperSlicer) gcode in the same viewer:

![other](https://user-images.githubusercontent.com/46632344/159766520-4a46b2b0-7e5c-4fe5-ba87-02086fea1965.png)

### Actual results

File isnt sliced correctly

### Expected results

File should be sliced correctly

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[CE3_borboleta2.zip](https://github.com/Ultimaker/Cura/files/8335464/CE3_borboleta2.zip)

**Comment by smartavionics** [comment]
The model isn't watertight (aka manifold) and needs fixing to be printable.

![Screenshot 2022-03-23 20 54 52](https://user-images.githubusercontent.com/585618/159794155-7b3d618d-f6c9-4937-b47f-44da77009a1c.png)

**Comment by GregValiant** [comment]
The model on the left has been repaired.  There were a total of 1,530,079 errors in the model of which 673,037 were duplicate faces.  That is a very high resolution model and so the high number of errors.
![image](https://user-images.githubusercontent.com/64202104/159799545-f599a7e0-27b1-4092-9329-9d73d26c9fa7.png)

**Comment by Asterchades** [comment]
Slic3r and its derivatives (both SuperSlicer and PrusaSlicer) have built-in fixers that try to correct for common issues. They aren't perfect, though, and can create new and different issues of their own in some cases as they have to "guess" what the modeller actually wanted. There will be an indicator in the "Info" section in the lower right of the Platter view showing how many fixes have been applied, listed as "Auto-repaired **** errors".

Cura has a few automatic fixes built in which mostly default to being off (again because they can only "guess" as to what is correct), and there's a Mesh Tools plugin with some more.

**Comment by fvrmr** [comment]
Closing this issue, since it is not an issue with Cura.
