### ISSUE TITLE
Linking an account to a website

### ISSUE THREAD

**Issue by houcles17** [Ultimaker/Cura#11708]
### Is your feature request related to a problem?

-

### Describe the solution you'd like

I would like to find out where I can change the website where I can log in to my profile so that I do not log in through Ultimaker, but through some of my own website

### Describe alternatives you've considered

-

### Affected users and/or printers

-

### Additional information & file uploads

-

**Comment by Ghostkeeper** [comment]
The link to Ultimaker's account is hard-coded in Cura. It's not intended to be changed. This could pose a security risk, as people could be tricked into making Cura send your stored log-in token to a bad actor. I don't think we should implement this.

**Comment by MariMakes** [comment]
We are constantly working on making Ultimaker Cura better. Our community is a big part of that by requesting new features and reporting bugs.
To be able to focus on the most requested and needed features and bug fixes from our community and from Ultimaker, we have decided to remove this bug from our backlog. We believe we will not work on this anytime soon and will therefore defer/close this issue.
Since Cura is open source, you or anyone else is more than welcome to work on this issue and create a pull request yourself.

**Comment by MariMakes** [comment]
Hey @houcles17,

Welcome to the Ultimaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

We don't see value in enabling this feature in Ultimaker Cura. To be able to focus on the most requested and needed features and bug fixes from our community and from Ultimaker. We believe we will not work on this anytime soon and will therefore close this issue.

I hope you understand 🙏
