### ISSUE TITLE
problem adding material profiles

### ISSUE THREAD

**Issue by DavidGom1** [Ultimaker/Cura#11739]
### Application Version

4.13.1

### Platform

Windows 10 Pro 21H2

### Printer

Artillery Sidewinder X2

### Reproduction steps

1. I log in with my Ultimaker account to access the marketplace.
2. I access the materials section.
3. I access the brand and install the materials.
4. I restart Ultimaker Cura 4.13 and make sure I'm logged into my account and sync (they don't appear)
5. I restart PC and make sure I am logged into my account and synchronize (they do not appear)
6. I ask the materials manufacturer (in this case Smart Materials) for the .xml.fdm_materials files and the same thing happens.

### Actual results

Materials not listed

### Expected results

Materials appear in the list

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

I hope you can help me

**Comment by fvrmr** [comment]
Hi @DavidGom1 thank you for your report.
The materials in the Marketplace are compatible for Ultimaker printers with 2.85mm filament. Since you're printer is using 1.75mm filament it is not showing up.
See also https://github.com/Ultimaker/Cura/issues/6236

I will close this issue since it is a duplicate.
