### ISSUE TITLE
Top Bar showing wrong bed adhesion setting 

### ISSUE THREAD

**Issue by vikky999** [Ultimaker/Cura#11779]
### Application Version

4.13.1

### Platform

Mac

### Printer

Creality CR-10

### Reproduction steps

Change the bed adhesion option from anything to anything. It doesnt matter what you do, the top bar still shows, bed adhesion as off even though the actual selection does work. 

### Actual results

Cura slices the model as expected, only the UI doesn't show the bed adhesion setting i choose on the top bar

### Expected results

Update the UI

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

<img width="996" alt="Screen Shot 2022-04-07 at 6 20 31 PM" src="https://user-images.githubusercontent.com/2762144/162204146-ba6fec5f-6eb3-43c5-ad92-88b22180e31c.png">

**Comment by fvrmr** [comment]
Hi @vikky999 thank you for your report.
Could you share a screenshot of your settings? At your current screenshot I can't see what you have selected.

**Comment by vikky999** [comment]
I've selected Skirt as seen in the screenshot, but the bar above shows "Off"

<img width="1782" alt="Screen Shot 2022-04-08 at 5 51 33 PM" src="https://user-images.githubusercontent.com/2762144/162434642-4cad4510-24ad-4302-b3ea-5988369ad16b.png">

**Comment by Ghostkeeper** [comment]
This is expected behaviour. Brim and Raft are considered "on", while Skirt and None are considered "off". That is because the skirt doesn't really add to the adhesion of the print, and many printers simply use it to prime and to ensure the bed is level. Novice users shouldn't be expecting that any effort is being done to improve the adhesion.

The implementation of this is here:

https://github.com/Ultimaker/Cura/blob/6f7145bb12e3f8c03a16447bcb5d689d6f82b2f8/resources/qml/PrintSetupSelector/PrintSetupSelectorHeader.qml#L87
