### ISSUE TITLE
cx_Freeze: Python error in main script

### ISSUE THREAD

**Issue by notnot75** [Ultimaker/Cura#11836]
### Application Version

4.10.0

### Platform

Windows 7

### Printer

none

### Reproduction steps

Hello, I installed Cura and when I launch it then I get the following pop-up windows with an error message about cx_freeze:python, impossible to start Cura. I searched through different forums and other website but can't see any response fixing this issue. Any idea?
![cura_error](https://user-images.githubusercontent.com/7278858/164450423-8738988c-72a1-44dd-9167-e6c4a45f282b.jpg)

Thx

### Actual results

-

### Expected results

-

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

-

**Comment by fvrmr** [comment]
Hi @notnot75 thank you for your report.
This is a duplicate of https://github.com/Ultimaker/Cura/issues/11680 
Could you also check if you have this folder `C:\\Program Files\\Ultimaker Cura 4.10.0` on your computer?

I will close this issue, since it is a duplicate. Please continue the thread in the other issue, so we keep everything in one issue.
