### ISSUE TITLE
Errore DLL 1114

### ISSUE THREAD

**Issue by 2G3D** [Ultimaker/Cura#12005]
### Application Version

5 beta+1

### Platform

win 10 pro 64bit

### Printer

Geeetech A10

### Reproduction steps

open program Cura

### Actual results

![278502171_1762984447240731_2291477982526320096_n](https://user-images.githubusercontent.com/73384915/165699513-edd3906a-21f5-44f9-99a5-d3d9a9fe6b2f.jpg)

### Expected results

program not opened

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Radeon HD7400M notebook HP Pavilion G6 8GB RAM

**Comment by DoganM95** [comment]
Try a reinstall. Looks like just a missing dll (failed installation).

**Comment by fvrmr** [comment]
Hi @DoganM95 thank you for your report.
Could you try to reinstall like @DoganM95 suggested, let us know if that works for you.

**Comment by mMerlin** [comment]
For others landing here from a search. I had the same error on Windows 10 with version 5.2.1 and 5.6.0. Both installed fine, but failed on first (and every) run. Reinstall did not help.

Summary: It's a graphics software problem.
FIX3 from
https://www.minitool.com/data-recovery/how-to-start-windows-10-in-safe-mode-009.html
worked for me. Using AMD Catalyst Control Center instead of NVIDA Control Panel. Change the power setting to maximum performance for ultimaker-cura.exe.

Warning: FIX1 from that page made my laptop unbootable. I had to go through safe mode to undo the global change. Which only undid one of the 2. I had to do it again the 'nomal' way after another reboot.
