### ISSUE TITLE
Install successful, but when Cura 5.0 is started, files are missing

### ISSUE THREAD

**Issue by KevinGroninga** [Ultimaker/Cura#12024]
### Application Version

5.0.0

### Platform

Windows 7 Home Premium

### Printer

Ender 3 v2

### Reproduction steps

1. Downloaded and installed the Win64 version of Cura 5.0.0 beta 1
2. During install everything appears fine.
3. Start Cura 5.0.0 and I encounter 2 errors about missing files and Cura cannot start.
![Error1](https://user-images.githubusercontent.com/102394455/166072148-a2abefa2-9473-4f6a-9593-17cdb866a5e7.JPG)
![Error2](https://user-images.githubusercontent.com/102394455/166072150-c1c869a5-a8fa-41d1-b536-8fecc030cc15.JPG)

### Actual results

Cura 5.0.0 fails to start because of files missing.

### Expected results

Cura 5.0.0 should start and allow me to import and slice STL files.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![Error1](https://user-images.githubusercontent.com/102394455/166072260-35ac6b84-06a5-4d13-8fe6-983ed4773180.JPG)
![Error2](https://user-images.githubusercontent.com/102394455/166072262-a66e7bd5-183c-47e6-b4d4-a27d20f7e3f3.JPG)

**Comment by fieldOfView** [comment]
Unfortunately, Cura 5 will not run on Windows 7. In order to support newer (current) versions of operating systems, support for older versions (that are no longer supported by their respective vendors) was dropped. 

Cura is built using Python and Qt, and the current version of neither Python nor Qt support Windows 7.

**Comment by fvrmr** [comment]
Hi @KevinGroninga thank you for your report.
Like @fieldOfView mentioned we don't support Windows 7 anymore. The latest Cura version that is supported on Windows 7 is Cura 4.10, which you can find here: https://github.com/Ultimaker/Cura/releases/tag/4.10.0

I will close this issue since this is not something we will change.
