### ISSUE TITLE
Is there a IDE or debug tool for Cura developer？

### ISSUE THREAD

**Issue by elviswoo** [Ultimaker/Cura#1210]
when i clone this Cura repo in my disk， i have found i cannot how to import this project with a IDE. so, 
1) Which IDE does Cura developers use frequently?
2) I want to add a button or editbox in Cura, how should i debug it?
3) How should i build this Cura project?
4) Can i launch Cura in command line?

Is there anyone can help me? thanks!

**Comment by fieldOfView** [comment]
1. We all use different IDEs. Some of us use a text-editor instead of a true IDE; I use Sublime Text, some use PyCharm. Pretty sure there are others who use other tools. The repository is "IDE-agnostic".

2. Buttons are added by editing QML files, mostly by hand (ie: text/source editor vs GUI-based tool)

3. There's the cura-build repository, which may help you on your way. It should check out all the different repositories you need (Cura, Uranium, libArcus, CuraEngine) and install most of the dependencies.

4. Once you have installed all the dependencies, you can start Cura with ```python3 cura_app.py```
