### ISSUE TITLE
cura 5 has hijacked my thermal (paper) printer

### ISSUE THREAD

**Issue by Chong-McBong** [Ultimaker/Cura#12243]
### Application Version

5

### Platform

windows 10

### Printer

ender 3

### Reproduction steps

opened new cura, while thermal (paper) printer is connected to com9 (usb RS232 thing)

after a moment, cura takes over the thermal printer, raises baud to 115200, and starts printing "M105" repeatedly

i normally print via octoprint, so cura has no direct connection to the printer, maybe it sees this paper printer as being the only device, i'm not sure. 

### Actual results

this is too complicated, i don't know why i have to fill in 3 boxes, i explained in the first box.

### Expected results

it should not print a com port that has not been specifically selected, 
what if it started another machine unexpectedly? this could be really dangerous

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

i don't know why i have to type in this box too :| why is everything so complicated

**Comment by fvrmr** [comment]
Hi @Chong-McBong thank you for your report.
You need to disable the USB printing plugin, read this support article how: https://support.ultimaker.com/hc/en-us/articles/4407742254610-Ultimaker-Cura-interacts-with-microcontrollers

I will close this issue, since I expect that this will solve your issue. Feel free to reach out if it doesn't solve your issue.
