### ISSUE TITLE
Keine Rückmeldung

### ISSUE THREAD

**Issue by Rimichrisa** [Ultimaker/Cura#12282]
### Application Version

5.0

### Platform

windows10, Intel HD Graphics 4000

### Printer

Ender 5 Plus

### Reproduction steps

Seit der Version 4.12 friert cura nach ein bis drei Aufrufen plötzlich ein. Eine Neuinstallation brachte auch keinen Erfolg.
Eine Deinstalltiion mit nachfolgendem Neustart von windows 10 und nocmaliger Neuinstallation von cura 5 brachte, wie bei den vorherigen Versionen auch nichts. Ein cleanup von windows 10 und der Festplatte brachte auch keinen Erfolg.
Es ist egal welches Projekt ich versuche zu öffnen, cura bringt sofort "keine Rückmeldung" ...

### Actual results

einfrieren von cura mit der Meldung "keine Rückmeldung"

### Expected results

![grafik](https://user-images.githubusercontent.com/105949109/169610568-d54f8980-1f53-483f-836f-bdfb971e3e81.png)

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/8744073/cura.log)

**Comment by nallath** [comment]
Please report issues in English. My German is barely good enough to order a beer in a pub, but not nearly close to being able to handle bug reports, sorry!

**Comment by usernametakenaaaa** [comment]
Do you have two monitors ? In that case you need to disable one.

The situation described happens when you move Cura after the first start to the second monitor (where the splash screen appears on start). When you start Cura again it will instantly crash with "no response", also reinstallation won't help because the cura.cfg file survives uninstallation and it includes the X coordinates which cause the instant crash.
