### ISSUE TITLE
Camera view disappears 

### ISSUE THREAD

**Issue by Spirou42** [Ultimaker/Cura#12309]
### Application Version

5.0.0

### Platform

macOS Monterey

### Printer

Ultimaker 3

### Reproduction steps

Start a print
switch to monitor

open the camera view  by clicking on there camera icon.
click on the window background

### Actual results

The camera view disappears

### Expected results

the camera view should stays open.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

https://user-images.githubusercontent.com/759145/169699129-e59de3e8-47b4-4c84-a210-40febb695b5a.mov

**Comment by Vandresc** [comment]
Hi @Spirou42 , unfortunately, this is somehow the expected behavior, did you experience it differently in older builds? 
It is just another way to close the window, though I do agree it is somehow confusing, and not very user friendly  Due to all the high prio issues we have currently on our backlog, we will have to reject this one. I do want to thank you for your feedback!
