### ISSUE TITLE
cora 5.0 ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by vidmo91** [Ultimaker/Cura#12349]
### Application Version

5.0.0

### Platform

Windows 11 21H2 22000.675

### Printer

custom

### Reproduction steps

logging in

### Actual results

cannot log in, browser displays: 
```
This site can’t provide a secure connection
localhost sent an invalid response.
Try running Windows Network Diagnostics
ERR_SSL_PROTOCOL_ERROR
```

### Expected results

logging in

### Checklist of files to include

- [x] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/8770333/cura.log)

**Comment by Ghostkeeper** [comment]
I'm unable to reproduce this error myself. Logging in works fine.

For context about that message, when logging in, Cura sends the user to the Ultimaker website and then immediately starts a miniature webserver that listens to localhost (127.0.0.1). The Ultimaker website, when logging in, sends the browser to localhost as well, sending the log-in token there. Cura can then receive the log-in token and store it securely to be able to request information about the account and use those features. This error message basically says that the local webserver that Cura creates doesn't respond properly like the browser expects.

Since it's different on your computer than with our testers, we'll have to look for the differences.

A bit of a technical question perhaps, but do you know if you've got any self-signed SSL certificates installed on your computer? Some firewalls install that to be able to inspect network connections you're making.

We might have to wait until more people get this issue to be able to investigate what causes this issue. To see the pattern.
