### ISSUE TITLE
Cura 5: 1st layer temperature not handled correctly

### ISSUE THREAD

**Issue by Triangulix** [Ultimaker/Cura#12417]
### Application Version

5.0.0

### Platform

Windows 10

### Printer

Custom

### Issue description
When I set Printing Temperature and Printing Temperature Initial Layer to different values then most of the first layer is printed with the temperature for layer 2+ because Cura inserts the GCODE command for the temperature change shortly after the commands for the skin part of layer 1 start.
I have 2 project files and GCODE files from Cura 4 and 5 which show the problem. Unfortunately the zipped files are 5MB of size and this seems to much to attach here.
I believe this is related to Issue #11954.

**Comment by GregValiant** [comment]
Within the Printer Settings (a plugin from the MarketPlace) is "Heat Up Speed" (and Cool down Speed) and the default is 2°/sec.
You first layer takes 23 minutes.  With a 17second heat time to go from 210 to 245 it seems to me that the M104 should be a lot closer to the end of Layer:0.  When I sliced your project in 5.0 I got the same thing you did.  The M104 is about 10 minutes before the start of Layer:1.
No matter how I set the "Heat Up Speed" the M104 turns up in line 1193 of the gcode.  I think something might be broken there.

**Comment by tlhintoq** [comment]
Closed or not, its still not fixed.
Cura 5.2.1 still doing the same thing.  Switching temp well and long before end of layer.
Just a thought... Instead of trying to guess how long it will take the head to cool down how about just taking the head off the job and use an m109 instead of m104, at the start of the next layer?
![image](https://user-images.githubusercontent.com/11351506/201550199-bb73bd9a-0002-4485-aa9a-a9c7f0d76077.png)

cc: @nallath

**Comment by GregValiant** [comment]
In 5.2.1 it appears that both "Initial Printing Temperature" and "Final Print Temperature" are ignored.
Going just by their descriptions what I expect to see (in every gcode file) starting from the top of the gcode is:
M109 S{material_initial_print_temperature}
M104 S{material_print_temperature_layer_0}
near the end of layer 0:
M104 S{material_print_temperature}
near the end of the file:
M104 S{material_final_print_temperature}

The first two only seem to work if I put them in the StartUp Gcode as shown.

I can't get the {material_final_print_temperature} to show up in the gcode at all and so all prints end with the material_print_temperature as the set point.

With no temperature replacement patterns in the StartUp Gcode I get:
M109 Sxxx ;print temperature layer 0
and then at the end of layer 0
M104 Sxxx ;print temperature
(this line does not appear when print temperature layer 0 = print temperature)

@nallath are you sure closing this wasn't premature?

**Comment by tlhintoq** [comment]
@GregValiant 
My Startup code:
`G28 ;Home
G1 Z15.0 F1200 ;Move the printhead up 15mm before heating
;Prime the extruder
G92 E0
G1 F200 E3
G92 E0

M117 Warming...
M107 ;start with the fan off
M140 S{material_bed_temperature_layer_0} ; start preheating the bed
M104 S{material_print_temperature_layer_0} ; start preheating hotend
M104 S{material_print_temperature_layer_0} ?T1; start preheating hotend

G28 ;Move to home
G1 Z60.0 F9000 ;move the gantry up to allow for nozzle cleaning
M84 X Y E ;Disable all steppers but Z

M190 S{material_bed_temperature_layer_0} ; heat to bed setting in Cura and WAIT
M109 S{material_print_temperature_layer_0} ; heat hotend to setting in Cura and WAIT
;M109 S{material_print_temperature_layer_0} ?T1; heat hotend to setting in Cura and WAIT

G28 ;Move to home
M117 Priming line...
M300 S1000 P500 ; chirp to indicate starting to print
G1 F200 E3 ;Prime the extruder with 3mm
G92 E0; zero the extruded length counter
G1 X0.1 Y20 Z0.3 F5000.0 ; Move to start position
G1 X0.1 Y200.0 Z0.3 F1500.0 E15 ; Draw the first line
G1 X0.5 Y200.0 Z0.3 F5000.0 ; Move to side a little
G1 X0.5 Y20 Z0.3 F1500.0 E30 ; Draw the second line
G92 E0 ;zero the extruded length again
G1 E-1 F500 ; Retract a little
G1 X80 F4000 ; Quickly wipe away from the filament line
M117 ; Printing…
G5
; End of custom start gCode
;
`

> The first two only seem to work if I put them in the StartUp Gcode as shown.
> M140 S{material_bed_temperature_layer_0} ; start preheating the bed
> M104 S{material_print_temperature_layer_0} ; start preheating hotend
Confirmed

> I can't get the `{material_final_print_temperature}` to show up in the gcode at all 
@GregValiant Are you trying to insert the Cura variable into the post-processing script?  I don't think that's going to work.  I'd bet the gCode is created at *at that time* Cura variables are evaluated and inserted.  But the post-processing gCode script is just that *POST* processing; meaning no *processing* of the gCode is done.  So no Cura variables are evaluated.

But I did notice this.  Depending on whether or not you check the RegEx box in the script dialog you get this extra zero at the end of your inserted line.  

![image](https://user-images.githubusercontent.com/11351506/201759874-8e257dac-cb78-48a2-b247-06fdab8f5ade.png)

![image](https://user-images.githubusercontent.com/11351506/201759926-7fddc7d5-ee8d-4ffd-ba10-11ed647cae59.png)

I think what's happening is the text within the curly braces is being evaluated per RegEx like any other RegEx computation, not Cura variable.  `{material_final_print_temperature}` according to RegEx is a computation that calculates to zero when run
![image](https://user-images.githubusercontent.com/11351506/201759787-f1d28824-0e7e-4f21-960a-5c1f1f9e159d.png)

So I don't think you'd ever be able to just insert a Cura variable into the *POST* processing scripts.

BUT - I think it does give hope.  I wonder if it might be possible through a more elaborate RegEx to locate the first usage of the normal print temp from the first object and store that as a RegEx  $1 $2 kinda variable, then insert _that_ later for the rest of the objects.

**Comment by GregValiant** [comment]
"Are you trying to insert the Cura variable into the post-processing script?"
No.  I was just commenting that it never showed up in any gcode I created.  You are correct that replacement keywords won't work in a post-processor like Search and Replace.
In that first screen shot of yours I see "M104 S\{material_print_temperature} ;normal print temperature0
The backslash that follows the "S" is also an error as is the ending "0".  Something wasn't right with your Search and Replace.  You have to hard code the temperature when you do it with Search and Replace as it is a Post-Processor and so Cura has already entered the number values where the keywords were.

In my snippet:
M109 S{material_initial_print_temperature}
M104 S{material_print_temperature_layer_0}
I was pointing out (for Nallath actually) that it was the only way I could get "Initial Print Temperature" to show up in the gcode.  The printer will heat to the Initial temperature and then start to print while it continues to heat up due to the M104 line that follows with print temperature.  That may actually be the way it is supposed to work, but the tooltip doesn't explain that.

I'm an amateur hack at programming (VB) but I only know enough Python and other languages to make a mess.

**Comment by tlhintoq** [comment]
The ending zero is the interesting part because that's being inserted by the RegEx
The slash was left over as part of a couple attempts to escape-sequence the braces.
