### ISSUE TITLE
Can't scale specific model via numbers

### ISSUE THREAD

**Issue by gageoleighton** [Ultimaker/Cura#12464]
### Application Version

5.0.0

### Platform

Windows 10

### Printer

Cherry Pi IIIs

### Reproduction steps

1. Download model https://www.thingiverse.com/thing:3793849
2. Attempt to scale via number pad
3. Fail

### Actual results

Can only scale model via dragging scaling handles by mouse.

### Expected results

Type in the box to scale by a known value.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

Can't attach project file directly. If Cura really want's to use github as a bug reporting platform you need to requisition that these files be allowed.

**Comment by mranvick** [comment]
I have the same issue with Cura 5.4.0. MacOS Ventura 13.2, system language is French.

I tried with different keyboard layouts (French, French PC, US) without effect. Note that the issue is not present with the `Location` section, nor with the different printing parameters.

Overall the "Scale" window is extremely buggy:

  - I cannot enter any text or number in the different fields.
  - Pressing different keys (trying to write anything) tend to make the "Uniform Scaling" toggle flicker and tick / untick itself (it just ticks / unticks every time I press and release the "CMD" key, for instance)
  - I have the ability to select one field, and then to select another one (see picture below), i.e. I have some text selected at two different places in the window (which is normally not possible in most apps)
  
![image](https://github.com/Ultimaker/Cura/assets/17085178/bfe80e8e-f44a-4820-b5d4-d88d73360f86)
