### ISSUE TITLE
mks wifi plugin hidden

### ISSUE THREAD

**Issue by Siriogv** [Ultimaker/Cura#12507]
### Application Version

4.13.1

### Platform

Ubuntu

### Printer

Flying Bear Ghost 5

### Reproduction steps

i don't see the plugin in the market and i don't will able to connect cura to my 3d in wifi

### Actual results

control and restore all plugin in market

### Expected results

i can install the plugin and connect to my 3d printer

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

nn

**Comment by fieldOfView** [comment]
Unfortunately it looks like the creators of the MKS Wifi plugin submitted a version of the plugin to the Marketplace that is _only_ compatible with Cura 5.0, not with Cura 4.13. Since only one version of a plugin can be in the Marketplace at any time, there is no version of the plugin in the Marketplace that is compatible with Cura 4.13.

It looks like you can download an older release of the plugin here:
https://github.com/Jeredian/mks-wifi-plugin/releaes

Since this is not an issue with Cura, but with a 3rd party plugin, I will close this issue.
