### ISSUE TITLE
GcodeFilenameFormat plugin not loading

### ISSUE THREAD

**Issue by JPM2000867** [Ultimaker/Cura#12514]
### Application Version

5.0

### Platform

windows 10

### Printer

Creality Ender 3

### Reproduction steps

1. When starting Cura 5.0 , is gives the error below: 
2. ![image](https://user-images.githubusercontent.com/98710057/173427974-6c2338c1-148b-4b93-b2a4-e0b98aaece01.png)
3. Reinstalling did not fixed the error
4. The plugin **GcodeFilenameFormat** was working with the previous versions of Cura

### Actual results

![image](https://user-images.githubusercontent.com/98710057/173428229-2240b90a-45f8-47a1-b795-7bf90215140a.png)

### Expected results

1. Should have loaded the plugin.
2. Plugin was working on the previous versions of Cura

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

This plugin **GcodeFilenameFormat** was working with previous versions of Cura

**Comment by Asterchades** [comment]
Cura 5.0 updated the framework the program uses. Pretty much every existing plugin needs to be updated in order to support this new framework.

To that end you'll need to wait for the plugin author to update it before it will work with Cura 5.0. If you'd like to make such a request to the author, or update the plugin yourself, the repository is available here: https://github.com/rgomezjnr/GcodeFilenameFormat
