### ISSUE TITLE
Material... Build plate temperature

### ISSUE THREAD

**Issue by DanielSJRP** [Ultimaker/Cura#12578]
### Application Version

5.0.0

### Platform

Windows 10

### Printer

Ultimaker

### Reproduction steps

After enabling the options
- Build plate temperature 
- Build plate temperature initial layer

### Actual results

They do not appear in the list.

### Expected results

That it was possible to change

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

no

**Comment by fieldOfView** [comment]
What Ultimalker printer?

If it is an Ultimaker 2 printer, then this is "by design". For those printers, material temperatures are normally handled by the printer by selecting a material on the printer. If you want full control over the material in Cura instead, then go to the Machine Settings and change the GCode flavor from "Ultimaker 2" to "Marlin".
