### ISSUE TITLE
Bug in  Cura Dashboard

### ISSUE THREAD

**Issue by simaduse** [Ultimaker/Cura#12581]
### Application Version

4.13.1

### Platform

Mac 12,4 Montery

### Printer

Ender 3

### Reproduction steps

The dashboard in the preference of CUra can be selectet to preview

### Actual results

Yo cant scroll the options in the panel

### Expected results

To be able to scroll the opcions in the panel

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Scroll to see the other opcions is not working. 
![Captura de Pantalla 2022-06-21 a la(s) 15 42 28](https://user-images.githubusercontent.com/107957955/174893789-b5056746-f6d0-4a8e-b09b-3cf5e5c1d8b9.png)

**Comment by GT-Geo** [comment]
It's because you're in Basic, switch to Custom Selection.

**Comment by simaduse** [comment]
Thank you so much!!!

**Comment by MariMakes** [comment]
Hey @simaduse 
Thank you for sharing our first bug report on Github.
Sorry, it took a while to get back to you. 😢 

I'm having some trouble recreating your issue, maybe because I'm on Windows.
Can you please try again with the latest version of Cura? 
[Cura 5.1 can be downloaded here.](https://ultimaker.com/software/ultimaker-cura)

If it's not too much effort, do you mind making a short video of what you are encountering? That makes it easier to troubleshoot in this case. 

Thank you! 👼
