### ISSUE TITLE
Can't open files in newly installed Cura 5.0.0

### ISSUE THREAD

**Issue by jld46** [Ultimaker/Cura#12584]
### Application Version

5.0.0

### Platform

ChromeOS (AppImage)

### Printer

Artillery Sidewinder X1

### Reproduction steps

Ctrl-O
Nothing happens

### Actual results

Nothing

### Expected results

See file system and select a file

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

I can't open a file (except with File/Open Recent), and then I can slice it, but not save.

**Comment by MariMakes** [comment]
Hey @jld46,
Thank you for opening your first issue with us. 🎉 
Sorry, we took a while to get back to you. 😢 

We don't officially support ChromeOS so that is why it slipped through.
There have been some changes in Cura 5.1 which are related to opening files on AppImages. 
[You can download it here. ](https://github.com/Ultimaker/Cura/releases/tag/5.1.0) 

Do you mind checking again and letting us know if you are still encountering it in the latest version of Cura? 
Thank you! 🤞
