### ISSUE TITLE
Slicing Failed Error

### ISSUE THREAD

**Issue by cht685** [Ultimaker/Cura#12591]
### Application Version

5.0.0

### Platform

Windows 11

### Printer

Ender 400XL

### Reproduction steps

1. Added files
2. Changed the Print Settings
3. Clicked on "Slice"
4. Get annoying "Slicing failed" pop up

### Actual results

I receive this pop-up message:

Slicing failed
Slicing failed with an unexpected error. Please consider reporting a bug on our issue tracker.

### Expected results

Cura Slices the print and I start printing like every version prior to this one.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

This is the latest issue I have on top of all the others I keep getting with Cura 5.0.0 now. Previous to this, if I opened a STL and tried to change the Print Settings after, it stops responding and goes full white until I Force Close it. I kept 4.13.1 as that is a stable release and 5.0.0 seems like it is still in BETA.

[cura.log](https://github.com/Ultimaker/Cura/files/8968668/cura.log)
[CURA 5_File That Causes Error.zip](https://github.com/Ultimaker/Cura/files/8968678/CURA.5_File.That.Causes.Error.zip)

![Screenshot_CURA FAILURE](https://user-images.githubusercontent.com/96957195/175338016-b5652465-e6f4-4b52-bad1-24e5e27de486.jpg)

**Comment by GregValiant** [comment]
I moved the large model off the build plate and the small ones sliced.
I switched them around and the large model sliced.
With all the models on the build plate but the large model off to the side (rather than in the middle) it sliced.
Selecting all models and then rotating the group 45° allowed it to slice correctly.
Someone from the Cura Team will take a look at this.
(BTW...I didn't find any errors in the models (it appears you fixed them) but when a model slices in one orientation but not in another it has been my experience that there is a problem with the model.  That being said - if there is a problem with these models, it's very well hidden.

Split apart:
![image](https://user-images.githubusercontent.com/64202104/175364284-3dd396b0-6a34-4a38-b0af-2decd9b6150d.png)

Rotated 45°:
![image](https://user-images.githubusercontent.com/64202104/175365781-c4d0cce8-029a-4031-8100-66b59e5a1eb9.png)

**Comment by GregValiant** [comment]
Using 5.1 Beta this sliced fine
There were a lot of these types of problems reported with 5.0.  I've been going back over the problem files and so far all of them have sliced with 5.1Beta.
I'll close this but if you have further comments you can post them and I'll be notified.
