### ISSUE TITLE
when i put my print that i designed it puts every thing in one spot and it makes it 10000% bigger and you cant even see 

### ISSUE THREAD

**Issue by mrnobodyXD** [Ultimaker/Cura#12633]
### Application Version

the latest one 

### Platform

windows 10

### Printer

ender 3

### Reproduction steps

i tried to shrink it 
then rebuild it

### Actual results

it worked but come on i don't want to have to rebuild my whole design all over again

### Expected results

i should be able to just put my designs in there and not have to rebuild it 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

1

**Comment by Asterchades** [comment]
Without a project file demonstrating the issue so it's able to be replicated there's not much that can reasonably be done about this. I can't say I've ever seen that happen and it wouldn't surprise me if the devs were in the same boat.

All I can tell you for now is that Cura imports STL files assuming the base unit is millimetres (mm), as the STL format does not (officially) allow for units to be stored. If the program you're exporting from is different (I'm aware Fusion360 likes centimetres) this is going to affect the results. There is an option in Cura called "Scale extremely small models" which might be having an impact, so you could try toggling it (I believe the intent of that setting is for output which has accidentally been scaled for whole metres or above).

It may also be worth exporting to 3MF instead of STL. 3MF can store the unit as well as the values.
