### ISSUE TITLE
Cura 5 slicing example like the old engine (4.13)

### ISSUE THREAD

**Issue by YardenNaveh** [Ultimaker/Cura#12650]
### Application Version

5.0.0

### Platform

MacOs Big Sur

### Printer

Ender 3

### Reproduction steps

Uploaded my model and sliced it. 

### Actual results

The perimeter is printed with very tiny lines instead of long lines along the sides. 
My understanding is that this is exactly what the new engine should resolve, so I'm sending this as an example. 

### Expected results

Perimeter should be printed with long lines along the sides. 

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[CE3PRO_Body1.3mf.zip](https://github.com/Ultimaker/Cura/files/9026597/CE3PRO_Body1.3mf.zip)
<img width="1269" alt="Screenshot at Jun 30 23-22-20" src="https://user-images.githubusercontent.com/20970210/176836562-503bbe63-6a6c-4224-828e-0441e3d01c8d.png">

**Comment by GregValiant** [comment]
I opened your project file in 5.0 and sliced it.  I didn't get that skin area.  You can see below that there are parallel lines there.  I'm not sure what to make of this as I can't duplicate it even using your project.
![image](https://user-images.githubusercontent.com/64202104/176880257-f63d9bcd-8b24-4649-b635-ac6266413511.png)

This is the project sliced in 4.13.1.  Looks the same as 5.0 with lines around the perimeter.  I sliced it in 4.8 as well and didn't get the problem.  
I don't know what information you could add, but if you can think of something pass it along. 
![image](https://user-images.githubusercontent.com/64202104/176882915-5c5eef19-6b89-4eb3-acb6-0983fd365bd1.png)

**Comment by GregValiant** [comment]
In the image below you can see that Section B-B is a narrow ring and Section A-A is a lot wider.  The extra width of A-A would mean that the Cura Outer Walls on that layer are far apart and the area between those outer walls would be filled with skin (not infill) in order to maintain the wall thickness through that area.  It is the same thing that is happening with your model (though the image is on a larger scale and has larger radii).
![Dims](https://user-images.githubusercontent.com/64202104/177038538-e29ba7e8-3215-46f4-b412-5b3a75c389f6.png)

I'm inclined to close this as it is "expected behavior" and a function of the geometry of your model coupled with the settings you are using.  Let me know what you think.
