### ISSUE TITLE
Visual Bug

### ISSUE THREAD

**Issue by armandoPoveda** [Ultimaker/Cura#12674]
### Application Version

5.0.1

### Platform

windows 10

### Printer

Ender 3

### Reproduction steps

Wall ordering in spanish language it's in english

### Actual results

Nothing

### Expected results

Change this name to spanish

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Nothing

**Comment by MariMakes** [comment]
Hey @armandoPoveda 

Thanks for opening your first issue with us! 🎉 
Sorry you had to wait a while 😢 

It really helps us if natives help with the translations. 
I just checked in Cura 5.1 and I believe Wall Ordering is translated as Orden de Paredes.
![image](https://user-images.githubusercontent.com/40423138/186186972-d8fd7aa3-4692-4fbe-9b38-a720ca52ea91.png)

If there are new words introduced between releases, usually they are translated during the Beta period. 
This means that during the Beta not all words are translated yet. 

If you have any suggestions for the translations you can make suggestions as a pull request.
If that is something you would like to do, please leave a comment and I would love to run you through the process. 🗣️ 

I'm closing this issue since it's resolved. ✅
