### ISSUE TITLE
Unexpected error during slicing 

### ISSUE THREAD

**Issue by Didou78** [Ultimaker/Cura#12684]
### Application Version

5.0.0

### Platform

windows 10

### Printer

Tenlog TL-D3 PRO

### Reproduction steps

[cura.log](https://github.com/Ultimaker/Cura/files/9057046/cura.log)
Slicing

### Actual results

![image](https://user-images.githubusercontent.com/108809676/177610506-b04c97cc-a217-4dac-8fab-31ee08691275.png)
!!!

### Expected results

[TD3PDE_Harry_Potter_Egg_Inner_Transparent.zip](https://github.com/Ultimaker/Cura/files/9057070/TD3PDE_Harry_Potter_Egg_Inner_Transparent.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Working fine with 4.13.1 french version
[TD3PDE_Harry_Potter_Egg_Inner_Transparent.zip](https://github.com/Ultimaker/Cura/files/9057099/TD3PDE_Harry_Potter_Egg_Inner_Transparent.zip)

[TD3PDE_Harry_Potter_Egg_Inner_Transparent.zip](https://github.com/Ultimaker/Cura/files/9057100/TD3PDE_Harry_Potter_Egg_Inner_Transparent.zip)

**Comment by GregValiant** [comment]
The form is a Github thing.
This problem occurred with 5.0 but in my limited experience with 5.1 beta it appears to have been fixed.
It did come up a lot for 5.0 though.  I'll mark this as a duplicate and I'm going to close it because it does seem to no longer be an issue.  If you feel that is premature let me know here.

I was able to slice the model after moving it on the build plate.  Other workarounds for this problem in 5.0 are to rotate the model, or sometimes a slight change in the Initial Layer Height would allow models to slice (like from 0.20 to 0.21).
In addition, the model has errors in it.  Windows 10 includes a program called MS 3D Builder that has a fair repair utility built into it.  You can open the model in 3D Builder and fix the errors.
