### ISSUE TITLE
ender 3 pro won't connect

### ISSUE THREAD

**Issue by hello89-o** [Ultimaker/Cura#12716]
### Application Version

5.0.0

### Platform

Windows 10

### Printer

ender 3

### Reproduction steps

i pluged my printer into my computer and tried to print from usb and it wont work

### Actual results

did not recognize printer

### Expected results

will not recognize ender 3 pro

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

i have tried everything and it wont work

**Comment by GregValiant** [comment]
Problems with "USB Printing" have been reported numerous times.  Since no Ultimaker printers use it anymore, it is an un-maintained legacy function still included with Cura.  Even when it works it has problems.  If you absolutely feel you need this sort of remote printing capability then the Octoprint/Raspberry PI system is probably your best option.
There are a couple of things you can check.
Make sure the USB cable you are using has data capability.  Some are just for charging phones and tablets and simply don't work for printing.
Your USB port must be enabled with the correct "USB to Serial" drivers.  With the printer plugged into the computer with a data-capable cord - open the Device Manager and it should look something like mine in the image below.  If the "Ports (COM and LPT)" heading is not available then you would need to install the driver that enables the USB port for serial communication.
![Untitled](https://user-images.githubusercontent.com/64202104/178144742-b953c1bb-bd67-440d-8461-add4b04885f3.png)
I do all communication with my Ender 3 Pro through the USB port, but I print from the SD card (utilizing M23 and M24) as it is much more reliable.
This may or may not be a bug.  I'll leave this open for now and mark it as a duplicate.  Maybe someone from the Cura team has an update on the status of USB Printing.
Let us know if you have any additional information or comments.
