### ISSUE TITLE
Cura is causing the printer to hit already printed material

### ISSUE THREAD

**Issue by gbarbehenn** [Ultimaker/Cura#12727]
### Application Version

5.0.0

### Platform

Windows 10

### Printer

Monoprice Maker Select V2/Wanhao Duplicator I3

### Reproduction steps

Try to print Thingiverse Thing: 4117257, as the author suggests.  There is a large hexagonal structure on the left of the thing.  This means that the right hand side of the thing has a support structure under it.  Cura slices the thing, in such a way that it prints the central piece last, so it prints the support first, and returns to the center *at the same Z position*.  This causes the nozzle to strike the support, eventually knocking it loose from the bed.
This is also happening with the support on the left side of the thing.
The essential point is that the nozzle should be raised and moved to the far right hand side of the thing, then the support printed.  This way the nozzle would not strike the support(s).  Alternatively, the nozzle could return around the thing.  In any event, moving over a structure printed at the same Z axis is bad
![4117257 sliced](https://user-images.githubusercontent.com/109034829/178153004-85334772-eda0-43bb-b245-1c863d456bcb.jpg)
[Inductive bed leveling probe mount.zip](https://github.com/Ultimaker/Cura/files/9079417/Inductive.bed.leveling.probe.mount.zip)
.

### Actual results

![Uploading 20220710_092243.jpg…]()

### Expected results

Thing printed correctly.  But hitting the supports has damaged them, and resulted detached layers and unsupported structures misprinting.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

slice settings:
0.1mm including initial layer
100% fill
support touching bed
[WDI3_induction_probe_mount.zip](https://github.com/Ultimaker/Cura/files/9079440/WDI3_induction_probe_mount.zip)

Raft attach
195°/60°

**Comment by GregValiant** [comment]
There are two settings under "Travel" that you can enable.  "Avoid Supports when Traveling" and "Z-Hop when Retracted".
I think either one will do what you want.
Since the other area of the large support is open to space you could also enable Support Wall Count at 1.
It doesn't need a raft if you enable the support brim.
I'd do it this way..
[GV_induction_probe_mount.zip](https://github.com/Ultimaker/Cura/files/9079684/GV_induction_probe_mount.zip)

I'll leave this as a bug but I think it's mostly a settings issue.
Let us know if you are able print it to your satisfaction.
.
