### ISSUE TITLE
баг режима вазы в кура 5.0

### ISSUE THREAD

**Issue by Danbaz1983** [Ultimaker/Cura#12774]
### Application Version

5.0.0

### Platform

windows10

### Printer

two trees bluer

### Reproduction steps

режим вазы
![2022-07-16_20-36-26](https://user-images.githubusercontent.com/109428127/179361694-4f14a238-9315-4d94-a8a8-bea93886a33b.png)

### Actual results

нарезка создает более одной стенки, добавляя странные перегородки внутри
![2022-07-16_20-35-48](https://user-images.githubusercontent.com/109428127/179361719-e54ae05a-0aa1-4071-8047-067640fc7e48.png)
![2022-07-16_20-35-48](https://user-images.githubusercontent.com/109428127/179361891-91a320ac-a55d-4438-a570-6af28a85b9ba.png)

### Expected results

должна была получиться ваза в одну стенку, 
![2022-07-16_20-35-10](https://user-images.githubusercontent.com/109428127/179361759-33c79f93-0e93-4459-ab7b-03910890ca0d.png)
а получилась фигура с добавлением несуществующих в модели перегородок
![2022-07-16_20-35-10](https://user-images.githubusercontent.com/109428127/179361913-f24b6b41-15d9-4c0e-adc7-ecaf792de8ad.png)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

не могу добавить файл проекта

**Comment by GregValiant** [comment]
You must zip a project file to post it.  It's a Github rule.
Without the project file what I'm guessing is that you are trying to spiralize a model that is hollow.  It won't work.
To be suitable for spiralize a model must be solid through and through and the top must be flat.

You can try enabling "Remove All Holes" in the Mesh Fixes section.  I believe you will still have a problem because the top of the model is cut at an angle.  When the nozzle gets above that cut then spiralize will no longer work as the path becomes a horseshoe shape rather than continuous loops around the part.

That interior wall is being built because Cura is extruding the wall that faces outwards, then traveling to the wall facing inwards, and extruding that, then traveling back to the wall facing outwards again.
This is "expected behavior" rather than a bug.  Not all models can be spiralized.

I will leave this open for you to add the project file but I'll remove the "Bug" label for now.
