### ISSUE TITLE
неправильная нарезка кура 5 нескольких моделей

### ISSUE THREAD

**Issue by Danbaz1983** [Ultimaker/Cura#12781]
![2022-07-17_18-27-17](https://user-images.githubusercontent.com/109428127/179400667-65e58f89-5d77-404f-a676-47b104ec6b8d.png)
### Application Version

5,0,0

### Platform

windows10

### Printer

Two trees SP

### Reproduction steps

Загрузил две модели, размножил, нарезал. В модели звезды нарисовано 4 тоннеля. Они печатаются нормально, когда печатается одна звезда.

### Actual results

После размножения модели часть тоннелей исчезла при нарезке
![2022-07-17_18-13-54](https://user-images.githubusercontent.com/109428127/179400418-0e125555-8c33-4b54-92d7-9d81c9e0c301.png)

### Expected results

Тоннели должны быть напечатаны так, как нарисованы.  Любое изменение модели приводит к невозможности нормальной печати, кроме увеличения. Любое масштабирование или изменение приводит к катастрофическим результатам.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[TWOTSPLUS_!Звезда_160_с_вырезом.zip](https://github.com/Ultimaker/Cura/files/9127718/TWOTSPLUS_._160_._.zip)

**Comment by GregValiant** [comment]
Please use English for your posts.  I have no way of knowing if I translated your report correctly.

The setting "Make Overhangs Printable" adds chamfers to overhanging areas (like you have within the channels) so that those areas don't require support.  This is expected behavior from that setting.
DIsable "Make Overhangs Printable" and you should get the print you want.  I'll remove the bug label and leave this open so you can let us know if that worked.

**Comment by Danbaz1983** [comment]
Я не могу использовать английский, так как это все равно будет машинный перевод. Да, это помогло, спасибо!

**Comment by GregValiant** [comment]
Can this issue be closed?
