### ISSUE TITLE
Show configuration files doesn’t work

### ISSUE THREAD

**Issue by Filmman586** [Ultimaker/Cura#12784]
### Application Version

5.1.0

### Platform

Windows 10, latest update.

### Printer

Anycubic Vyper

### Reproduction steps

Clicked help, clicked show configuration files.

### Actual results

Nothing. No file location shows up.

### Expected results

I’m assuming file locations

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

No files to upload, or should I upload something specific.

**Comment by fieldOfView** [comment]
>  should I upload something specific.

Please upload the logs. The cura.log file can be found in `%APPDATA%\cura\5.0` which, incidentally, is the configuration folder that fails to open.

**Comment by Filmman586** [comment]
[cura.log](https://github.com/Ultimaker/Cura/files/9128479/cura.log)

Hope it helps, is there another one?

**Comment by Ghostkeeper** [comment]
That's the correct file, thank you.

However there is nothing that seems to be going wrong that's logged in that log. Nothing about the `showConfigurationFolder` action. I hoped there would be some QML error about that then, but nothing seems to happen.

I'm not getting the error myself so I can't verify.

One possible cause would be that your Windows username (which I'll not repeat here for possible bots scanning personal info) has a space in it. Perhaps it's actually trying to open `C:\Users\<part before the space>` and then fails on that because that folder doesn't exist. I believe Windows warns you upon creating your Windows user account that it might give trouble with some applications.

**Comment by MariMakes** [comment]
Hey @Filmman586 

You can just copy paste %APPDATA%\cura\5.1 in your file explorer bar to navigate to the configuration folder: 
![image](https://user-images.githubusercontent.com/40423138/186462209-d97efe24-487a-4bf2-bce1-57ab029b58d3.png)

Can you let me know if it works for you?

**Comment by ki4glx** [comment]
I had this exact same issue today. I resolved it by using %APPDATA%\cura\5.1. When clicking "Show Configuration Folder" absolutely nothing happens.
