### ISSUE TITLE
Slicing failed

### ISSUE THREAD

**Issue by luxnox** [Ultimaker/Cura#12785]
### Application Version

5.0.0

### Platform

Windows 10

### Printer

Creality CR-10s Pro V2

### Reproduction steps

1. Slicing of a model worked fine
2. Changed "Slicing Tolarance" to "Exclusive"

### Actual results

Slicing failed with a prompt to report bug
Restarted Cura and tried again with the same result :-
[cura.log](https://github.com/Ultimaker/Cura/files/9128497/cura.log)
/

### Expected results

Successful slicing

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

cura.log attached

**Comment by Ghostkeeper** [comment]
I tried loading a cube model, changed the Slicing Tolerance to Exclusive, and sliced it. It slices fine.

How can I reproduce your problem? Perhaps it only occurs with certain models? Could you share your project file with us so that we may reproduce your scene and settings? You can create a project file by going to File -> Save Project.
