### ISSUE TITLE
Support concentric not working

### ISSUE THREAD

**Issue by thmbremser** [Ultimaker/Cura#12808]
### Application Version

5.1.0

### Platform

Windows 10

### Printer

CL-260

### Reproduction steps

- Load a part
- set support mode to "concentric"

### Actual results

Only the corner of the model gets support. The rest of the model is not supported. V 4.12.1 does it correctly

### Expected results

Dupport in the density of the density-setting

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![support](https://user-images.githubusercontent.com/109670919/179986795-2edb5759-49b9-4447-beeb-91ef5e1f74e7.JPG)

**Comment by GregValiant** [comment]
Thanks for the report.  I can't get it to work either.

**Comment by Ghostkeeper** [comment]
This is something that we found ourselves as well and is listed as a bug in our backlog since May. Developers, see issue CURA-9263.

The concentric pattern doesn't work if there are any Support Wall Lines. Setting Support Wall Line Count to 0, you do get a concentric pattern (though with the wrong offset).

**Comment by thmbremser** [comment]
As you can see in my screenshot, I have a line count of 1. If I increase it I only get mor wall lines at the outer side but no in the free space under the part needed to support.

**Comment by Ghostkeeper** [comment]
Indeed, it only generates if the line count is 0. And that is a confirmed bug.
