### ISSUE TITLE
Allow comma as decimal mark (again)

### ISSUE THREAD

**Issue by Fass-ohne-Hoden** [Ultimaker/Cura#129]
Cura 15.06 only accepts a dot as decimal mark (or did I miss a setting?)
This is annoying if your Numpad layout has a comma (as, perhaps, you live in a country where the comma is THE decimal mark)

The older Cura accepted both comma and dot as decimal mark. Which is as it should be (unless both were required for different purposes, which isn't the case here). Make the new Cura the same.

**Comment by BagelOrb** [comment]
You request is valid, but currently low priority. There are a lot of pressing issues at the moment.

**Comment by nallath** [comment]
This has something to do with your locale settings I believe. Your operating system decides what can be used as a decimal point.

**Comment by awhiemstra** [comment]
Actually, in this case it sounds more like a keyboard layout thing. The locale issues were solved by enforcing using . everywhere. Since we now enforce using . everywhere, a keyboard that uses , instead of . on the numpad will be a bit more annoying to use.

**Comment by Fass-ohne-Hoden** [comment]
It's neither an issue with locale settings nor keyboard layout - both are just right the way they are. It is a program issue if the program that is aimed at and used in numerous countries doesn't adopt (either by fully accepting both comma and dot as decimal mark or by converting one into the other internally). However, I do understand that there are more pressing issues right now and some things need to wait.

**Comment by MarcusWolschon** [comment]
if texts are translated into the users locale (in 2.1beta I can select a language), 
then the formatting of dates, times and numbers of that chosen locale or in the absence thereof of system locale of the current used must be used. 
If my locale uses a comma for decimal point and a dot as thousand separator, then that is how all numbers must be entered and displayed.

**Comment by BagelOrb** [comment]
I don't agree. My locale suggest using the cons as decimal separator, but
I'm used to using dots. I think handling both as decimal separator is more
permissive towards users.

I don't see much use for a thousand separator in Cura; values generally
don't go that high.
Op 1 mei 2016 22:32 schreef "Marcus Wolschon" <notifications@github.com>:

if texts are translated into the users locale (in 2.1beta I can select a
language),
then the formatting of dates, times and numbers of that chosen locale or in
the absence thereof of system locale of the current used must be used.
If my locale uses a comma for decimal point and a dot as thousand
separator, then that is how all numbers must be entered and displayed.

—
You are receiving this because you commented.
Reply to this email directly or view it on GitHub
<https://github.com/Ultimaker/Cura/issues/129#issuecomment-216070127>

**Comment by daid** [comment]
The old code allowed math as well as commas, for reference:
https://github.com/daid/Cura/blob/SteamEngine/Cura/util/profile.py#L913

**Comment by nallath** [comment]
The new one simply uses dots for decimals and forces everything to that. So it doesn't matter what you enter, the result is the same.

**Comment by daid** [comment]
I noticed with older Betas the behaviour is a bit undefined if you fill in commas. But the open beta seems to behave as Nallath describes. (It replaces any entered comma with a dot when you enter it)

**Comment by nallath** [comment]
A few of the closed beta testers also noticed this behavior, so it was fixed at some point.
