### ISSUE TITLE
Slicing error

### ISSUE THREAD

**Issue by Madman8594** [Ultimaker/Cura#12916]
### Application Version

5.1.0

### Platform

Macbook

### Printer

Anycubic Vyper

### Reproduction steps

1. I loaded the model. 2. I hit slice.

### Actual results

After I hit slice I get an error saying slicing failed

### Expected results

Slicing should be done

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

I am using cinderwing baby flying serpent

**Comment by GregValiant** [comment]
In order to investigate bug reports we need to know the model and your settings along with the Cura.log file that will tell what happened within Cura.  Without them nothing can be done.
In Cura click on the Help menu and then "Show configuration folder".  That will take you to the location of Cura .log on your system.
With the model loaded and Cura ready to slice select "File | Save Project" to create a 3mf file.  Zip the 3mf and the log file and post the zip file here.
