### ISSUE TITLE
Skirt Issue

### ISSUE THREAD

**Issue by spyscouter** [Ultimaker/Cura#12938]
### Application Version

5.1.0

### Platform

Windows 10

### Printer

Creality Ender 3

### Reproduction steps

1. I added two different parts to the build plate and used CHEPS profile for 0.2mm layer with 0.4mm nozzle. 
2. I clicked slice and went to preview tab
3. I noted that the skirt was interfering with the parts and not going around properl
[CE3_blade.zip](https://github.com/Ultimaker/Cura/files/9252828/CE3_blade.zip)

### Actual results

I printed anyways, and it reproduced with the parts overlapping the skirts.
![image](https://user-images.githubusercontent.com/34991341/182645763-bf83b09a-d6ec-4bd6-a6e4-56d3424a7235.png)

### Expected results

Skirt overlapping with parts.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

n/a

**Comment by GregValiant** [comment]
Thanks for the report.
That happens when the parts aren't flat on the build plate in Cura.
One of the options of the "Rotation Tool" is "Lay Flat".  Give that a try and see if it changes the behavior. If those two parts are in the same STL file then they may have to be split up first if their bottoms aren't coplanar.
