### ISSUE TITLE
Make overhang printable in spiralize outer contour mode does not work properly

### ISSUE THREAD

**Issue by fkiliver** [Ultimaker/Cura#12931]
### Application Version

5.1.0

### Platform

Windows 11

### Printer

Voron 2.4

### Reproduction steps

1. Import a model with large angle overhang
![IMG_20220802_184217](https://user-images.githubusercontent.com/48873439/182414652-fe08e3f7-512f-4820-9428-c1aff4d50ee1.jpg)
2. Enable spiralize outer contour
3. Enable overhang printable
4. Slice

If not enable overhang printable,it like this
![IMG_20220802_184229](https://user-images.githubusercontent.com/48873439/182415119-20826d45-b054-4fc0-bd14-67be2afe7e51.jpg)
![IMG_20220802_184241](https://user-images.githubusercontent.com/48873439/182415142-a3939f10-2e5b-4545-9fe0-88b2a5006b81.jpg)

### Actual results

The overhang of the lower surface of the model is modified to be printable, but the upper surface is ignored
![IMG_20220802_184259](https://user-images.githubusercontent.com/48873439/182414901-bc6971c6-669b-4bc2-ae55-2ca9edebfad7.jpg)

![IMG_20220802_184310](https://user-images.githubusercontent.com/48873439/182414939-bbb4e085-a73d-485b-9bf8-2bc682b37038.jpg)

### Expected results

The overhang of the upper and lower surfaces should both be made printable
![IMG_20220802_234209](https://user-images.githubusercontent.com/48873439/182415866-f872c76b-6d53-4468-92a2-88042621162d.jpg)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[test.zip](https://github.com/Ultimaker/Cura/files/9243709/test.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
"Make Overhangs Printable" acts on overhangs.  That's why the underside was altered.  It needed support and now it doesn't.  The top surface is not an overhang and never needed support and so it isn't altered.  Spiralize never puts _top skins_ on a model and so you end up with an open space that will allow what's above to fall inside and the print will fail.
What you want to do really needs to be done in CAD.  It appears as if you want to print a different model than what you are giving Cura to work with.  Cura is not a CAD program and there is only so much modification that it can do.
What I see here is "Expected Behavior" rather than a bug.  You could submit a Feature Request (but I don't think it would get much traction with the Cura team as it starts to cross the line into CAD functions).
I'll remove the Bug label but leave this open for a bit so you can respond here.

**Comment by fkiliver** [comment]
> 

Thank you for your replay.
Well, sometimes I need to print oversized sculpture models. Any filling and support will cause the cost and printing time to get out of control, so I need to use spiralize outer contour, but this will lead to the loss of support on the upper surface and the printing failure. In this case, cura just need to make the overhang printable modify the upper surface, just like what it does to the lower surface.
When the model is upside down, the upper surface becomes the lower surface. This is not the field of CAD. You can think that what I need is to combine the modification of the model by making overhang printable when the model is upright with the modification of the model by making the overhang printable when the model is upside down

**Comment by GregValiant** [comment]
By definition, that upper surface is not an overhang.  Whether it is right side up, upside down, or laying on it's side, an overhang has air below and the top surface never does.  It has "part" below.
I'll close this now.
