### ISSUE TITLE
Retraction value on Machine Setting page

### ISSUE THREAD

**Issue by Ser-filco** [Ultimaker/Cura#12942]
### Is your feature request related to a problem?

Yes, I know that I can set the retraction under print settings, what I'm saying "I shouldn't have to".
My CR-6 have custom print head that requires retraction 3.5 not your default 7.5, so every time I try new material and /or print profile I have to remember to adjust this setting .

### Describe the solution you'd like

What I'm proposing is simply adding retraction field under "Machine Settings" to drive the retraction value under "Print Settings", where you can overwrite it if needed.  After all this is hardware constrain value just as the print bed dimensions are.

### Describe alternatives you've considered

Flood Cura with tons of printing profiles the will be obsolete with next upgrade  

### Affected users and/or printers

both

**Comment by Vandresc** [comment]
Hi @Ser-filco, I do thank you for your request, as we are constantly working on making Ultimaker Cura better. Our community is a big part of that by requesting new features and reporting bugs.
To be able to focus on the most requested and needed features from our community and from Ultimaker, we believe we will not work on this anytime soon and will therefore defer this issue.
Since Cura is open source, you or anyone else is more than welcome to work on this issue and create a pull request yourself.

If for some reason the upgrade doesn't work for your profiles, please raise a bug and we will look into it. For now the workaround of creating a profile is the best option indeed.
