### ISSUE TITLE
Slicing Failed with an unexpected error

### ISSUE THREAD

**Issue by Autoextrude** [Ultimaker/Cura#12974]
### Application Version

5.1.0

### Platform

MacOS Monterrey

### Printer

Anycubic Vyper

### Reproduction steps

Simple STL to print. 
Changed retraction to a lower amount. 
No supports. 
Went to slice it so I can preview the print and it failed. 

### Actual results

Failed. Says to report the bug. 

### Expected results

It's suppose to slice the file. 

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[AV_ZR1_Block_Card_Holder.3mf.zip](https://github.com/Ultimaker/Cura/files/9277337/AV_ZR1_Block_Card_Holder.3mf.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
This model is not watertight and has a lot of errors.
--> 0 Naked edges (?)
--> 0 Planar holes (?)
--> 0 Non-planar holes (?)
--> 3376 Non-manifold edges (?)
--> 5025 Inverted faces (?)
--> 192 Degenerate faces (?)
--> 120 Duplicate faces (?)
--> 0 Disjoint shells (?)
-> Repairing: 100.00%
----- Repair completed in 16486ms ------
-> Vertex count changed from 17672 to 23185 (+5513)
-> Triangle count changed from 42268 to 54780 (+12512)
I'm attaching the repaired file from [Formware](https://formware.co/OnlineStlRepair).
In the Cura Marketplace is the Mesh Tools plugin.  You should install that so you can check the models right in Cura.  It has some repair capability, but this model needed extensive repair.  MS 3D Builder is pretty good at repairs as well.
The repaired model sliced fine for me.  Try it and then get back with the results.  I'll leave this open but it's a model problem rather than a bug.
[AV_ZR1_Block_Card_Holder_fixed.zip](https://github.com/Ultimaker/Cura/files/9277729/AV_ZR1_Block_Card_Holder_fixed.zip)

![image](https://user-images.githubusercontent.com/64202104/183314536-afed1ecf-1598-4b1f-bc83-386844f16bcf.png)
