### ISSUE TITLE
Layer Irregularities in slicer

### ISSUE THREAD

**Issue by yviccc** [Ultimaker/Cura#12992]
### Application Version

5.1

### Platform

Windows 11

### Printer

Ender 3

### Reproduction steps

If you select .6 nozzle size with .6 line width and try to slice this particular model with the face with the " + " (best reference I thought) facing the bed, you will get this issue.

### Actual results

Layer lines seens to be inconsistent, some short others long

### Expected results

a diagonal without inconsistencies is expected

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

I tried to slice with every default and non-default profile
[model.zip](https://github.com/Ultimaker/Cura/files/9294349/model.zip)
![4](https://user-images.githubusercontent.com/110938310/183755922-92b3213b-3847-4302-82bb-a53c007b18b1.png)
![6](https://user-images.githubusercontent.com/110938310/183755926-87802775-46e9-4070-ac33-22e696678478.png)

**Comment by GregValiant** [comment]
Thanks for the report.
The variable line width of Cura 5.x has some new features that you need to consider.
In the Walls settings are "Minimum Wall Line Width", and the related "Split Middle Line Width", and "Add Middle Line Width".  They will default to percentages of the Nozzle Size rather than the line width.
When you chose the .4 nozzle and a .6 line width then the default "Minimum" line width was .34 and it gave the full shape of those edges.  When you picked the .6 nozzle and the .6 line width then the default minimum is .51mm and at that line width the slice isn't smooth.
Decrease the "minimum line width" to .3 and see how it looks.
