### ISSUE TITLE
Support generation insconsistencies

### ISSUE THREAD

**Issue by thekojent** [Ultimaker/Cura#13007]
### Application Version

5.1.0

### Platform

Windows 10

### Printer

Ultimaker S5

### Reproduction steps

1. Import model
2. Add support blocker in center of model
3. Generate supports for entire model (ignoring support blocker)

### Actual results

Support generation is inconsistent. Support interfaces generate properly, but preview shows poor support placement and missing material.
![image](https://user-images.githubusercontent.com/75548272/184208314-d43aedbb-93b2-425b-98a9-8e95a3d9cb1a.png)
Adjusting the support pattern changes how much of the support material is missing, but the material is still incomplete:
![image](https://user-images.githubusercontent.com/75548272/184208533-f999a0d6-14d2-4d32-a3be-3a825235beb1.png)

### Expected results

Support material should be consistent throughout the height

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[UMS5_Buggy support.zip](https://github.com/Ultimaker/Cura/files/9311065/UMS5_Buggy.support.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
You have some settings that just don't work well with that model.  In particular is "Gradual Support Infill Steps" and "Support Wall Line Count".  The "Triangles" pattern isn't the best either.
Long narrow support structures need a wall around them because the infill is sparse and may not make it to the edges.  Support Infill Steps always causes some support to print over air.  With walls around that's OK as it will bridge, but you don't have any walls so it will fail.  "Lines" pattern works well in small areas.
So enable "Generate Support" and then set the "Gradual Infill Steps" to 0, change the infill type to "Lines", and change the Support Wall Line Count to 1.  Disable "Generate Support".  The changes you make will apply to your Per Model settings.
In this screenshot I've also dropped the Support Density to 7% as anything else is overkill.
I'm inclined to close this as it's a Settings issue rather than a bug.  Let me know what you think.
![image](https://user-images.githubusercontent.com/64202104/184343117-c98b3cb4-b7be-4cea-9163-e94db8b6b8e5.png)
