### ISSUE TITLE
Slicing failed for print with 20 small objects

### ISSUE THREAD

**Issue by DarioCattelan** [Ultimaker/Cura#13043]
### Application Version

5.1.0

### Platform

Windows 11 Pro

### Printer

Ender 3

### Reproduction steps

Loaded 28mm_Ryleh_Base_1.stl from this link: https://www.thingiverse.com/thing:4686194/files
Changed scale (non-uniformly) so that X and Y were 25mm (Z unchanged)
Multiplied model 19 times
Tried to slice with Standard Quality profile with Nozzle temp 210C, Bed temp 60C and 10% infill

### Actual results

Slicer began to slice, but then failed with an unexpected error.

### Expected results

Slicer should have completed slicing.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/9339802/cura.log)

project file:
https://drive.google.com/file/d/1ItGDprFD4MdaJWrmZduyuavYbopHpkOa/view?usp=sharing

**Comment by GregValiant** [comment]
Thanks for the report.
Each model I checked has errors.  After repairing them with MS 3D Builder they sliced.
That first model is 18.3mb so 20 is 366mb of models.  The 5th model is 115mb so 20 of them would be 2.3gigabytes of models. 
 That will bring a lot of computers to their knees.  The files are so large because of the extremely high resolution of the models.  Scaling them down from 27.5 to 25 makes the triangle density of the STL files even higher.
This is the repair report the the "28mm_RylehBase_2B.stl" file:

--> 24 Naked edges (?)
--> 3 Planar holes (?)
--> 3 Non-manifold edges (?)
--> 5 Inverted faces (?)
--> 4 Degenerate faces (?)
-> Vertex count changed from 188037 to 140828 (-47209)
-> Triangle count changed from 375362 to 281670 (-93692)

I will leave this open but I'll remove the bug label as it appears to be a model problem rather than a Cura problem.  Let me know if that works for you.
Here are 20 instances of the "28mm_Ryleh_Base_1.stl" model repaired and sliced.
![image](https://user-images.githubusercontent.com/64202104/184921677-eaaaec8a-d044-4081-b3e7-df42f3da9ced.png)
