### ISSUE TITLE
slicing problem

### ISSUE THREAD

**Issue by kshitiz1996** [Ultimaker/Cura#13057]
### Application Version

5.1.2

### Platform

window 10

### Printer

anet et4

### Reproduction steps

1. load stl file the slice it 
2. while slicing it stops in between 
3. dialoug pop ups and error while slicing 
![Screenshot (33)](https://user-images.githubusercontent.com/48486507/185204120-5ad31b05-a8dc-46e5-b93f-b434a2ea6a97.png)

### Actual results

cura shut down

### Expected results

cura shut down

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

yes

**Comment by GregValiant** [comment]
Thanks for the report.
In order to investigate these reports we need a project file and a cura.log file.
Under the Help menu is Show Configuration Folder.  That will take you to the location of the Cura.log file.
Load your model and get Cura ready to slice and use the "File | Save Project" command to create a project file.
Put those two files into a Zip folder and post the folder here.
