### ISSUE TITLE
Ajouter un matériel

### ISSUE THREAD

**Issue by Ziksax** [Ultimaker/Cura#13069]
### Application Version

5.0.1

### Platform

Windows 11

### Printer

JGMaker

### Reproduction steps

Lorsque l'on ajoute un filament dans cura, via la marketplace celui-ci n'apparaît pas dans la liste des filaments.

### Actual results

Lorsque l'on ajoute un filament dans cura, via la marketplace celui-ci n'apparaît pas dans la liste des filaments.

### Expected results

Lorsque l'on ajoute un filament dans cura, via la marketplace celui-ci n'apparaît pas dans la liste des filaments.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Lorsque l'on ajoute un filament dans cura, via la marketplace celui-ci n'apparaît pas dans la liste des filaments.

**Comment by MariMakes** [comment]
Hey @Ziksax ,

The Ultimaker Marketplace only offers print profiles for Ultimaker printers. 
https://support.ultimaker.com/hc/en-us/articles/360011968360-Using-the-Ultimaker-Marketplace
Most material suppliers share the settings you need to change in their websites. So I suggest you check there. 

I hope you understand, but since this is per design, I'm closing this issue.
