### ISSUE TITLE
Skirt neglects objects printed with single line

### ISSUE THREAD

**Issue by dansity** [Ultimaker/Cura#13084]
### Application Version

5.1.0

### Platform

Windows 10

### Printer

BLV Mgn Cube

### Reproduction steps

1. Place a thin object that will print with a single line.
2. Place another object that will print with infill
3. Turn on skirt. The skirt will neglect the object with a single line

### Actual results

https://i.imgur.com/mD8asb3.png
Skirt clashes with the thin line object

### Expected results

Skirt to go around the thin line object

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

Files can be found here: https://drive.google.com/drive/folders/10XicJE8SajFqNGR4Cgrk9aMmmrowm1Vo?usp=sharing

**Comment by Asterchades** [comment]
This is not being caused by the single-line pieces. This is the result of those parts simply not having a presence on the bottom layer. And a skirt will only go around things which are present on the bottom layer.

Reducing the negative Initial Layer Horizontal Expansion of -0.6mm to match the regular Horizontal Expansion of -0.3mm not only has it printing the initial layer but also having it contribute to the skirt generation. The part of the first layer which is printed with the higher provided setting is the part which corresponds to the thicker portion of the thread - the rest is simply too thin given your specified Minimum Feature Size of 0.1mm after 1.2mm has been subtracted.
