### ISSUE TITLE
slice problem

### ISSUE THREAD

**Issue by Dady12345** [Ultimaker/Cura#13096]
### Application Version

5.1.0

### Platform

windows 10

### Printer

anycubic vyper

### Reproduction steps

1.i started slicing

### Actual results

1.i went to preview
2.i saw more that half of my model not being sliced

### Expected results

all my model being sliced

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[2 (1).zip](https://github.com/Ultimaker/Cura/files/9401356/2.1.zip)
[AV_2 (2).zip](https://github.com/Ultimaker/Cura/files/9401361/AV_2.2.zip)

**Comment by MariMakes** [comment]
Hey @Dady12345 

I took a look at your model.
Do you see all the discolored face in the prepare screen? 
![image](https://user-images.githubusercontent.com/40423138/187238234-6bc130f1-6f62-4cf3-a14a-89813f98b34d.png)

That means that there is something wrong with your model.
I used [the meshtools plugin ](https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/MeshTools) and it indicates that it is not watertight. 
You'll have to go back to your CAD software to fix it. 
It depends on your CAD software how you can best resolve it. 
Sometimes loading your model into TinkerCAD and downloading it again might already do the trick. 

Since it's not a Cura issue I'm closing this ticket. 
Good luck!
