### ISSUE TITLE
Cura 5.1 less big bad layers, much more smaller ones than 4.12

### ISSUE THREAD

**Issue by DuckersMcQuack** [Ultimaker/Cura#13121]
### Application Version

5.1

### Platform

Windows 10

### Printer

ender 3 pro but custom firmware and parts.

### Reproduction steps

Just changing print temp to 235, bed to 80, retraction to 0.39, speed at 65mm's, rest of the speed all stock draft setting with PETG

e3d V6 and bondtech LGX in directdrive with skr 1.3 with 2209 silent steppers

Left is cura 5.1, right is cura 4.12

![20220826_004929](https://user-images.githubusercontent.com/9039370/186783305-dd5c60c2-3b5b-449d-aeec-23a40f503b75.jpg)
![20220826_004944](https://user-images.githubusercontent.com/9039370/186783311-fd592b8b-f27b-4d52-b0df-0fd91eedd2f3.jpg)
.

### Actual results

Results in pictures has been achieved.

### Expected results

Walls to not have inconsistent layers and actually being fine and flat like the right pic of cura 4 in the middle part next to the Y.

### Checklist of files to include

- [ ] Log file
- [x] Project file

### Additional information & file uploads

e3d V6 and bondtech LGX in directdrive with skr 1.3 with 2209 silent steppers

[Desktop.zip](https://github.com/Ultimaker/Cura/files/9428675/Desktop.zip)

**Comment by MariMakes** [comment]
Hey @DuckersMcQuack,

I'm going to be honest, this is a really tricky issue to troubleshoot. 
Between 4.12 and 5.1 we've had at least 9 months of fulltime development if not more if you include the Arachne Beta's. 

You can read about all the introduced changes here. 
https://github.com/Ultimaker/Cura/releases?page=1

The biggest change is that we have a completly different engine in Cura 5.x which changes the way that the walls are being deposited since it has a variable linewidth. But next to that, we have had our research team make improvements in the profiles. 

I printed your model with default settings in 4.12 and 5.1 on my S5 and I'm having only slightly similar results compared to yours.
![image](https://user-images.githubusercontent.com/40423138/187473171-a5f415c1-a0ef-4e67-b89d-bf620111aa26.png)

Print quality can be the result of a number of things. It can also be degration of material over time, combination of settings or just screws that have gotten loose over time. 

Can you please be more specific in where you think the problem is? 
Is there a setting that you think it might be related to? 🤔 

Sorry I can't help you more 😞
