### ISSUE TITLE
Slicing error with Tree support

### ISSUE THREAD

**Issue by busa-blade** [Ultimaker/Cura#13138]
### Application Version

4.13.1

### Platform

Linux

### Printer

Creality Ender 3 Pro

### Reproduction steps

Slicing a part with support turned on with Tree, Everywhere and 45 degree overhang angle.

### Actual results

An error occurred and model didn't get sliced.

### Expected results

Geometry should have been sliced so it could be sent to the printer
[CE3PRO_Handle_Middle_Part.zip](https://github.com/Ultimaker/Cura/files/9438421/CE3PRO_Handle_Middle_Part.zip)
[cura.log](https://github.com/Ultimaker/Cura/files/9438424/cura.log)

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

No more information.

**Comment by MariMakes** [comment]
Hey @busa-blade,

Welcome to the Ultimaker Cura Community 🚀 

I took a look at the file you shared, but it slices succesfully for me in the latest version of Cura 5.1
![image](https://user-images.githubusercontent.com/40423138/187460402-801c51d6-ba5c-420b-a1c8-394dff1a6507.png)

I also noticed that you don't have supported profiles, that's because your custom material has an incorrect Material Type. 
If you change PLA+ to PLA you'll be able to select multiple layerheights and have settings closer to PLA settings than to Default settings. 
![image](https://user-images.githubusercontent.com/40423138/187460997-64712fc4-87ad-44f5-83e5-39144de29fe7.png)
I hope this helps.

Can you check your file again for me in the latest version of Cura and confirm if it slices for you? Than we can close this issue. Thank you! 😊
