### ISSUE TITLE
Support x/y distance/override not respected.

### ISSUE THREAD

**Issue by PhilBaz** [Ultimaker/Cura#13203]
### Application Version

5.0

### Platform

win 10

### Printer

Voron 2.4

### Reproduction steps

use & change support x/y distance on print with support.

### Actual results

X/y distance doesn't change

### Expected results

changes..

### Checklist of files to include

- [x] Log file
- [x] Project file

### Additional information & file uploads

![Screenshot 2022-09-03 200738](https://user-images.githubusercontent.com/21558241/188294057-5b65969a-e552-46e4-af47-c058696531d5.jpg)
[support xy.zip](https://github.com/Ultimaker/Cura/files/9483697/support.xy.zip)

**Comment by Asterchades** [comment]
Try updating to 5.1. I'm unable to reproduce your issue with the provided project and profile, meaning if there was an issue with 5.0 it has since been corrected - and updating would be the only way you would get any fixes anyway.

![image](https://user-images.githubusercontent.com/29810435/188301625-ba20dda1-0978-4156-ae5c-1468d3514dad.png)
2.0mm

![image](https://user-images.githubusercontent.com/29810435/188301635-66285c98-4173-46a3-8973-876cb252f04e.png)
0.4mm

**Comment by PhilBaz** [comment]
@Asterchades 

But what about the initial layers? They would fuse to the print. they have not moved.

**Comment by PhilBaz** [comment]
@Asterchades 
Oh, no...im sorry. you are right. bad model.
