### ISSUE TITLE
Purge tower remains active when only one extruder is active

### ISSUE THREAD

**Issue by felipelaydner** [Ultimaker/Cura#13202]
### Application Version

5.1.0

### Platform

Windows 10

### Printer

Geeetech A10T

### Reproduction steps

I wanted to set the printer to print one piece at a time instead of all at once. So i deactivated all extruders except the one  I wanted to used. Then I pressed to prepare the code and then previewed the result. I realised the printer was printing the brim of the purge tower. I couldn't deactivate the purge tower because it was hiding this setting while only one extruder was active. So I had to reactivate the second extruder to allow the option to use a purge tower. Then I deactivated the function and then I deactivated the second extruder again. 

### Actual results

The print goes as expected, not spending plastic with a purge tower that was not needed

### Expected results

 The best alternative, would be to allow the setting to print one part at a time at all times, even with all nozzles active. Doesn't make sense pushing people into keeping only one active nozzle just to tur on the print one part at a time feature.
I also think the purge tower function could be automatically deactivated when only one extruder is active. 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Hope you guys fix this.

**Comment by MariMakes** [comment]
Hey @felipelaydner ,

Welcome to the Ultimaker Cura Gitub! 🎉 

Can you share a project file that illustrates your problem? 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

I tried a couple of things, but I can only recreate your problem if I 
1. enable the prime tower 
2. disabling the core. 
= faulty primetower
3. enable the core again
4. turn off the prime tower 
5. disable the core again
= no primetower 

![image](https://user-images.githubusercontent.com/40423138/189151707-c9f2fe36-45f0-4513-8a32-ec9d8d433b70.png)

That's a bug 🐛A disabled core should not have any influence on the print job if it's disabled. 

I'll check with the team. But I suspect that if it's not a quick fix we'll probably not work on issues that involve more than 2 extruders.

But since Cura is open source, you or anyone else is more than welcome to work on this issue and create a pull request yourself. 
Fingers crossed 🤞
