### ISSUE TITLE
It won't let me open files on the AppImage 64 Bit

### ISSUE THREAD

**Issue by GhostPisces** [Ultimaker/Cura#13225]
### Application Version

5.1.0

### Platform

Linux App Image

### Printer

Neptune 2

### Reproduction steps

I went to open my files and it wouldn't open them. I deleted the file and redownloaded it and that still didn't work.

### Actual results

I still cant open my files to slice them in the program.can't

### Expected results

I should be able to open my files and slice them to print them.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

It just won't let me open files for slicing.

**Comment by notfood** [comment]
I have the same issue.

Tested the following:
- `PASS` Ultimaker_Cura-4.13.1.AppImage
- `FAIL` Ultimaker-Cura-5.0.0-linux.AppImage
- `FAIL` Ultimaker-Cura-5.1.0-linux.AppImage
- `FAIL` Ultimaker-Cura-5.1.0-linux-modern.AppImage 

Anything above 5.0 fails to open the file browser. You can open files by drag and drop, but then you can't export the gcode because it doesn't open either.

OS: ArchLinux
Kernel: 5.19.3
DE: KDE Plasma Desktop 5.25.5

**Comment by notfood** [comment]
After further investigation, I got it to show the file browser panels by prepending `LD_PRELOAD=/usr/lib/libstdc++.so.6` to the command.

Information here: https://aur.archlinux.org/packages/cura-appimage-bin

**Comment by MariMakes** [comment]
Hey @notfood,

Thanks for the report 👍 
Sorry, it took us a while to get back to you. 😞 
I'm happy to see you were able to do some troubleshooting on your own 💪 

Can I interpret your last comment as your issue is resolved?
Or do you need someone from the team to look at your issue? 🤔

**Comment by notfood** [comment]
For me it has a workaround, probably other's will have the issue in the future.
