### ISSUE TITLE
Cura-2.3.1-win32 crashing

### ISSUE THREAD

**Issue by 1ngwpower** [Ultimaker/Cura#1323]
![16-1-8 cura error](https://cloud.githubusercontent.com/assets/25013255/21776178/225791f6-d64e-11e6-9ae1-1dbf532ab2b2.jpg) 
Have been using This version for 2 months no problems. Running Windows 7 Pro 32 bit. 
Have removed all cura files from C and restarted the downloaded a fresh copy. 
Went through C in Users deleted every thing looking like Cura on my computer. Reboot fresh from web and still not running.

**Comment by awhiemstra** [comment]
This is a more common problem that was fixed in 2.4. There is a log file in C:\Users\<username>\Local\AppData\cura that is going to be very big. Delete this file and things should start properly again.

See also https://github.com/Ultimaker/Cura/issues/1107 and https://github.com/Ultimaker/Cura/issues/1312
