### ISSUE TITLE
Slicing Failed

### ISSUE THREAD

**Issue by Baro0060** [Ultimaker/Cura#13242]
### Application Version

5.1.0

### Platform

Windows 11

### Printer

BeeVeryCreative B2X300

### Reproduction steps

Imported a model - Slicing failed
Rotated the model - Slicing Failed
Changed the model size (made it smaller) - Slicing Failed

### Actual results

Slicing Failed

### Expected results

It should slice

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

I cannot figure out why some of the STL files slice perfectly, and others don't slice at all. I have messed with many settings to figure this out, but nothing helped. All of these STL files did slice in the older version of Cura (4.XX.XX)
[Desktop.zip](https://github.com/Ultimaker/Cura/files/9527119/Desktop.zip)

Please give suggestions or recommendations.
NOTE: These will slice when selecting a different printer, it must have something to do with my printer settings. I just can't figure out what setting I need to look at.

**Comment by GregValiant** [comment]
Thanks for the report.
It looks like the setting profile "B2X300 PLA" is for a dual extruder printer.  The Dual Extruder settings section is available for it, but your printer is configured as a single extruder machine.  I don't know how that could have happened.  Maybe something went wonky when you installed the printer in Cura???
If you change to the "Draft" profile the model will slice.
I'm going to take the bug label off of this but I will leave it open.  If you feel that is premature let me know here.

**Comment by Baro0060** [comment]
That has solved my slicing issue for all models.
I just want to share why I use a single extruder when I have 2. When selecting more than 1 extruder, Cura doesn't allow printing multiple models simultaneously (it can only do one at a time).
Please review the attached picture and let me know what setting you think is causing the slicing issue. 
![Profile Settings](https://user-images.githubusercontent.com/48608778/189191629-6ea8ae66-1a00-45f0-b760-ecc519c6246b.jpg)

Thank you for your help.

**Comment by GregValiant** [comment]
My knowledge of IDEX machines is limited to what I've picked up in passing.  The general feeling is that Cura does not support IDEX printers but sometimes the printer can provide it's own workarounds.
The Raise3D IDEX printers use a special gcode line to tell the printer what mode to interpret the gcode as.  If an owner wants to use Cura it is necessary to install three printers that are identical except for the StartUp Gcode.
Printer 1 has normal startup gcode and so operates in "Normal Mode".
Printer 2 has the line "M605 S1" which for Raise3D firmware means "Mirror Mode".
Printer 3 has the line "M605 S2" which for Raise3D firmware means "Duplicate Mode".
So in that example - if you want to mirror a print you would select "Printer 2" and the printer would know how to handle the incoming gcode because it would see M605 S1.

Troubleshooting from far away ain't easy.  Maybe you could set up a printer that you would always use for "Single Extruder" prints and another for "Dual Extruder" prints.  Each would have it's own set of profiles that you would create for it.  That should avoid any conflicts like you are experiencing now.

As for where the error is, I really don't know.  I saw that the Prime Tower was enabled even though you had a single extruder printer active.  Maybe that was the issue as Cura tried to call the second extruder, realized there wasn't one, and so had to stop slicing.  That may not be the exact problem but I have a feeling it's something like that.
Cura is pretty flexible and so you should be able to come up with a satisfactory solution.  It might be a bit clunky, but if it works, it works.
So I guess we can leave off the Bug label.  I think you'll be able to come up with a system that allows you to utilize all the printer's capabilities and that won't be too confusing to use.
I'll close this but I will be notified if you want to add more comments.
