### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by seb449** [Ultimaker/Cura#13267]
### Application Version

5.1

### Platform

WINDOWS 11

### Printer

D12 500

### Reproduction steps

Decoupage

### Actual results

Echec de la decoupe

### Expected results

Decoupe

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/9542387/cura.log)
[WD12500PROMAX_lowpolyhipppppo2.zip](https://github.com/Ultimaker/Cura/files/9542393/WD12500PROMAX_lowpolyhipppppo2.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
When I open the 3mf file your printer would not import.  I must not have a proper definition file on my computer.  I had to use a different printer.
I increased the size of my build plate to allow the model to fit at 100% scale and I had no trouble slicing the model.  I am unable to reproduce the behavior.
Are you scaling the model down in order to slice it?  That would change the resolution and may make a difference.  Let me know if that is the case.
![image](https://user-images.githubusercontent.com/64202104/189526888-125306ae-a2e5-4e99-8ace-71ada950a5b5.png)
