### ISSUE TITLE
v5.1.1 shows as v5.1.0 in APP Menu(uninstall program menu).

### ISSUE THREAD

**Issue by BakeJake** [Ultimaker/Cura#13337]
### Application Version

5.1.1

### Platform

Windows 11

### Printer

Ender 3 S1

### Reproduction steps

If you look in the app menu on windows to uninstall the old version you'll notice that it says 5.1.0 and not 5.1.1.

### Actual results

The wrong Version number is in the app list from windows settings.

### Expected results

To show the correct version.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Just wanted to let you know of this little bug, probably just an oversight.

**Comment by klepp0906** [comment]
yea i removed cura via add/remove after upgrading 5.1.0 to 5.1.1 due to the presumed mismatch in label.

i reinstalled 5.1.1 and no entry was created at all.  I checked on another pc still on windows 10 that had never had cura before.  5.1.1 installer is creating no entry in HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall
