### ISSUE TITLE
Ultimaker 4.2 app crashes while loading plugins

### ISSUE THREAD

**Issue by ftalaver** [Ultimaker/Cura#13391]
### Application Version

4.2

### Platform

Windows 11 Home Version 21H2

### Printer

Ultimaker 4.2

### Reproduction steps

When I click to open the Ultimaker 4.2 app, it starts to load the plugins and crashes immediately. 

I reset the Cura data to no avail. 

### Actual results

The app does not open. It crashes immediately.

### Expected results

The app should open

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/9659225/cura.log)

The app has never opened and has not created a cura.log file. Only the Text document is available.

I do not have Chitubox installed on my computer and, thus, that is not the problem. 

I just purchased this system last week and have not been able to open the app from the beginning. This is the first time I installed this type of app as well, so I do not think that there could be a conflict between apps since none of the other apps are similar to this one. Please let me know what I can try to make it work.

The system components that I have include the following

OS: Windows 11 Home Version 21H2
NVIDIA GeForce MX230
Intel Core i7
Display resolution: 1920 X 1080
16 GB RAM memory
Available hard disk space: 63 GB

**Comment by GregValiant** [comment]
Thanks for the report.
I'm unsure of the printer you have.  Creality and some other printer manufacturers have their own forks (proprietary versions) of Cura that are different than UltiMaker Cura.  Those forks aren't supported here so you would need to go back to the provider of the slicer you are trying to install.
The current UltiMaker Cura version is 5.1 so that program you are trying to install is about 10 versions out of date.  You could download the UltiMaker version and try to install and run it.  It may depend on the printer model though.  Some manufacturers don't provide UltiMaker with printer definitions if the manufacturer happens to provide their own forks of Cura.

We need more information here.  Specifically what printer do you have (UltiMaker, Creality, Longer, Artillery, etc.) and where did you get your Cura installation program from?
