### ISSUE TITLE
Modify Gcode Pause At Height Inconsistency

### ISSUE THREAD

**Issue by SaschaUncia** [Ultimaker/Cura#13412]
### Application Version

5.1

### Platform

Windows 10

### Printer

Ender 3

### Reproduction steps

Last version of gcode can be found here - https://drive.google.com/file/d/1QA2-2_DphS7VlyO95bsHZBW-j-nOCJnY/view?usp=sharing

The model is a red panda toothpaste squeezer, it is intended to pause at height to allow for filament colour changes. The model is intended to print 0-3mm in black, 3mm - 4mm in white, and 4mm - 5mm in red.

I seemed to remember pause gcode being added at the end of the specified layer (I use it infrequently), so with 0.25mm thick layers I set the height for pause to 3mm. (Later to 3.25mm and Layer 13 to troubleshoot)

### Actual results

Setting the pause to 3mm, the solid layer of white was printed over what was supposed to be black. So I think, ok, it must be pausing at the start of the layer at the specified height, not after. 

So then I set the layer pause height to be 3.25mm, but I got the same result.

Finally I thought that maybe it just doesn't like the height being specified in millimeters, so I change from mm to layer number. I double check mathematically  and in Slice Preview that layer 13 is the first layer that should be printed in white. Selecting layer 13 for the pause, In this case layer 13 actually printed in black and layer 14 was paused to change the filament. 

It's very inconsistent 

### Expected results

Expected results would be that CURA would remain consistent when selecting layers and height, and a height of 3.25 should have printed layer 13 in the new colour when 3mm failed. 

Clarifications should also be provided in the dialogue box on whether, say, when selecting layer X, whether it pauses at the start of that layer or after it is complete.

Neither a height of 3mm or 3.25 mm produced correct results, with both printing the last 1-2 black layers in white.

### Checklist of files to include

- [ ] Log file
- [x] Project file

### Additional information & file uploads

[CE3_red panda toothpaste tube squeezer v1 thin slot.zip](https://github.com/Ultimaker/Cura/files/9680650/CE3_red.panda.toothpaste.tube.squeezer.v1.thin.slot.zip)

**Comment by GregValiant** [comment]
Welcome back.
In the 3mf file you provided you are using "By Layer".  As I explained in the other thread, gcode uses Base0 numbering and Cura uses Base1 numbering.  All slicers are built that way.
So you look at the Cura preview and see that when Layer 13 starts you want to pause because you want layer 13 in Red.  But gcode starts at 0 and not 1 so there is an "extra" layer.  Instead of the pause occurring at the start of layer 13, it pauses at the end of layer 13.  This will happen every time.  I use pause at height a lot and it takes some getting used to (or a sticky note on the side of your monitor) but it works.
This is a gcode snippet file from your project but I've inserted my own port-processor that sends the Cura layer height to the LCD.
M25 ; Do the actual pause
**m300 s6000 p500**  _The letters must be capitalized or your firmware will ignore the command._  M300 S6000 P500 will work.
M109 S224 ; resume temperature
G1 F300 Z3.5
G1 F9000 X97.584 Y83.158
G1 F300 Z3.5 ; move back down to resume height
G1 F2700 ; restore extrusion feedrate
M82 ; switch back to absolute E values
G92 E1600.34144
**;LAYER:13
M117 14/20** | ET 56M
You see that the pause is at the start of Cura layer 14 which is not what you wanted.  Remember that the pause will occur at the END of the Cura Preview Layer Number you enter in the Pause At Height dialog box.  If you want layer 13 to be a different color then enter 12 in the dialog box.

Pausing at a Height:
When Cura puts in the Pause snippet it will always include a line:
G1 F300 Z4 ; **move up a millimeter** to get out of the way
In this example the pause occurred at 3mm, then Cura adds the line to move up to 4mm (a 1mm move) to clear the print for the move to the park position.  There is the problem.  Because your second pause is at 4mm, as the post-processor runs - it comes across that line and says "AHA...4mm.  Put the pause here.".  And it's wrong.

To get it to work you put the 4mm pause first in the Post-Processor list and then put in the 3mm pause.  When the 4mm script runs the only Z4.0 in the file is the actual print move to 4.0 and not the travel move that pause at height adds.  That is provided you do not have Z-hops enabled which confuses things even further.

The attached zip file contains two project files.  One is pause "at height" and the other is pause "at layer".
I did not correct the small case letters in the beep lines in "Gcode Before Pause" box.

I don't see a bug here.  You have a special situation with the 1mm difference from one pause to the next and it is coincidental that Cura uses a 1mm Z move to clear the part that is causing the glitch.  When using "By Layer" (which I always use) you have to remember to subtract 1 from the layer number of the preview to the number you put into the Pause dialog.
I'll leave the Bug label on this until we hear back from you.
