### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by Angelus3d** [Ultimaker/Cura#13424]
### Application Version

5.1.1

### Platform

windows 11

### Printer

anycubic mega pro

### Reproduction steps

I just recently updated from cura 4 to cura 5, I have copied over exactly the same settings I was using on cura 4 to cura 5 but when I go to slice it just gives me an error saying that it can not slice due to an unexpected error so close down application and then boot up and retry 

### Actual results

After booting up and retrying i get the same results

### Expected results

It should slice exactly the same as it did not cura 4

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

can not upload

**Comment by GregValiant** [comment]
Thanks for the report.
Without a Project File or Cura log file there can be no investigation.  Github requires that files be zipped in order to be posted here so if you could zip the files that would be good.
In the meantime, if you could move and or rotate the model on the build plate that will sometimes fool the bug.  So far 5.2 beta seems to not have the issue.
