### ISSUE TITLE
Failed to Slice

### ISSUE THREAD

**Issue by Lp801313133131** [Ultimaker/Cura#13444]
### Application Version

5.1.1

### Platform

Windows `10

### Printer

Creality Ender 3

### Reproduction steps

When ever I try to slice any file it says this "Slicing failed with an unexpected error" It is not out of build plate size or anything

### Actual results

It still says that same thing

### Expected results

Not say that and allow me to slice the files and 3d print

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

e

**Comment by GregValiant** [comment]
Thanks for the report.
There were a lot of bug reports about 5.1 not wanting to slice error-free models.  A workaround was to move and/or rotate the model on the Cura build plate.  That would often fool the bug.
That bug was worked on and should be fixed in 5.2 beta.  I haven't done enough slicing in 5.2 to be sure but so far it looks promising.
I'll mark this as a duplicate and close it in favor of the previous reports.  Without a Project File there isn't much to work on.
