### ISSUE TITLE
Nondescript error while slicing

### ISSUE THREAD

**Issue by Embercide** [Ultimaker/Cura#13469]
### Application Version

5.1.0

### Platform

Windows 11

### Printer

Ender 3

### Reproduction steps

Attempted to slice an STL

### Actual results

Approximately 1/3 of the way through slicing I received a popup message that an error occured and suggested I submit it here

### Expected results

Slicing should complete
[torana.zip](https://github.com/Ultimaker/Cura/files/9703404/torana.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

Project and log attached

**Comment by GregValiant** [comment]
Thanks for the report.
This bug has been noted many times and occurs with 5.1 on Windows systems.  I believe it has been fixed in 5.2beta.
A workaround for 5.1 is to move and/or rotate the model on the Cura build plate.  That's how I got it to slice.
I will mark this as a duplicate and close it in favor of the previous reports.
![image](https://user-images.githubusercontent.com/64202104/193813012-132a0155-7f47-459e-8f0f-1c901485c63c.png)
