### ISSUE TITLE
First Layer Combing

### ISSUE THREAD

**Issue by ianrossg** [Ultimaker/Cura#13536]
### Application Version

5.1.0

### Platform

Windows 10

### Printer

Ultimaker 2+ Extended

### Reproduction steps

Cura is combing on the initial layer (makes no sense as nothing is printed yet. This can be reproduced in nearly if not all Travel > Combing Modes and instantly viewed in the gcode previewer.

### Actual results

Cura is combing on the initial layer (makes no sense as nothing is printed yet. This can be reproduced in nearly if not all Travel > Combing Modes and instantly viewed in the gcode previewer.

### Expected results

Cura is combing on the initial layer (makes no sense as nothing is printed yet. This can be reproduced in nearly if not all Travel > Combing Modes and instantly viewed in the gcode previewer.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[SL+20deg.R1.zip](https://github.com/Ultimaker/Cura/files/9760714/SL%2B20deg.R1.zip)

**Comment by MariMakes** [comment]
Hey @ianrossg,

Welcome to the Ultimaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

I'm having some trouble understanding your problem. 
Do you see this combing behavior influencing your printed part quality? 
Does this combing behavior impact your printing time?

**Comment by ianrossg** [comment]
Print time is impacted as it is essentially pre-tracing the footprint of the part. Additionally, the nozzle may ooze leaving material in the print path as well as a thin start to a print line.

**Comment by MariMakes** [comment]
Hey @ianrossg,

Do you have a picture of the nozzle that leaves the material in the print path or a thin start to a print line? 
Is it similar to this? Because we intent to improve this behavior. 
![image](https://user-images.githubusercontent.com/40423138/199006285-339e1d23-7e40-4ea8-8f48-00b38189af7b.png)

Or do you have a project file for us that shows this behavior? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
