### ISSUE TITLE
[5.2 beta] Slicing Tolerance artefacts in middle and exclusive

### ISSUE THREAD

**Issue by MrEd88** [Ultimaker/Cura#13552]
### Application Version

5.2 Beta

### Platform

Linux Mint 20.2

### Printer

Custom Printer

### Reproduction steps

Setting the profile from draft and slicing changing slicing tolerance

### Actual results

After playing with slicing tolerance to get better accuracy ( I like to use exclusive for not organic shapes) I noticed exclusive and middle have some issues in some parts of the print. Using Inclusive the issue is not observed.

### Expected results

Exclusive, Inclusive and Middle should show the same behavior in a straight segment like in the used model. 

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

MODEL
![Model](https://user-images.githubusercontent.com/19942461/195906206-fffda745-dd07-4784-9421-0b7d91db836b.png)
![XRAY](https://user-images.githubusercontent.com/19942461/195906219-7fd91da2-acec-4967-8186-0d7eeab4f8c5.png)

SLICING WITH EXCLUSIVE 
![Exclusive](https://user-images.githubusercontent.com/19942461/195906141-30e22738-485a-4669-91fc-58ccaa6f116f.png)

SLICING WITH INCLUSIVE
![Inclusive](https://user-images.githubusercontent.com/19942461/195906162-3cfd9db8-78f4-4e1e-b7db-5d52154b0854.png)

SLICING WITH MIDDLE
![Middle](https://user-images.githubusercontent.com/19942461/195906192-94504d24-bd23-4dce-b2da-7dc23eb31597.png)

### **PROJECT FILE:**

[Project.zip](https://github.com/Ultimaker/Cura/files/9788778/Project.zip)

**Comment by MariMakes** [comment]
Hey @MrEd88,

Sorry, it took us a while to get back to you 😞 

I took a look at your model but I don't believe the issue is related to your slicing tolerance but to your zseam preference.
Your zseam preference is Sharpest Corner + Smart Hiding by changing the tolerance some of the calulations change slightly and because of rounding issues some corners might not be the sharpest corner anymore.  

I believe that if you change your zseam to a different position you can move the artifacts to a more convenient place. 
![image](https://user-images.githubusercontent.com/40423138/197738093-877f5510-9aa3-448e-9ffa-777ab4ce7d03.png)

Can you let us know if this resolves your issue?
Thank you 👼
