### ISSUE TITLE
Not slicing larger files

### ISSUE THREAD

**Issue by flemball12** [Ultimaker/Cura#13563]
### Application Version

5.1

### Platform

windows 10

### Printer

ender 3 v2

### Reproduction steps

1. uploaded file
2. resized file
3. sliced file
4. unknown error occoured 

### Actual results

was given the option to slice again but same thing happened.

### Expected results

file should have sliced ready for me to save and print.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

n/a

**Comment by GregValiant** [comment]
Thanks for the report.
In order to investigate a report we need to see the model and how Cura was set up.  Load the model, set Cura up to slice, then use the "File | Save Project" command.  Zip the 3mf file and post the zip folder here.  To be thorough you can use the Help | Show Configuration Folder command and you will find the Cura.log file.  Put that into the zip folder as well.
