### ISSUE TITLE
The program cannot slicing the stl

### ISSUE THREAD

**Issue by Famed-C** [Ultimaker/Cura#13586]
### Application Version

5.0.0

### Platform

Windows 10

### Printer

Ender 6

### Reproduction steps

1. Open the STL
2. Press the segment button
3. I got the error

### Actual results

I keep getting error and can't segment my STL file

### Expected results

I keep getting error and can't segment my STL file

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

The STL file is https://www.thingiverse.com/thing:366813

**Comment by MariMakes** [comment]
Hey @Famed-C,

Welcome to the Ultimaker Cura Github 🚀 

I need more information for troubleshooting. 
Because I can slice your STL just fine in Cura 5.2

![image](https://user-images.githubusercontent.com/40423138/196411860-96a11afd-a68c-4666-b3b1-9e25048582e8.png)


Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
