### ISSUE TITLE
I have the plugin sidebargui  installed and every time Cura 5.2.0 starts it says that particular plugin cannot be loaded while it is.

### ISSUE THREAD

**Issue by homeyjo** [Ultimaker/Cura#13600]
### Application Version

5.2.0

### Platform

Windows 11

### Printer

Creality Ender 3

### Reproduction steps

All that has to be done is have that plugin installed and every time Cura 5.2.0 is started, it says there was a problem loading that particular plugin and maybe reinstalling it may help. The plugin had started even though Cura "thinks" it isn't working.

### Actual results

I close the error message and continue on working with the STL file.

### Expected results

The usual .gcode file is made for printing.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

It is not one particular file that this happens with. It is EVERY file and the results are the same. I just close the error message and continue.
![Cura_screenshot_bug](https://user-images.githubusercontent.com/67806391/196674374-06b56f1c-7457-48bc-b22d-9e9e2b023e48.png)

**Comment by MariMakes** [comment]
Hey @homeyjo,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report. 

The sidebar plug-in is actually contributed by one of our amazing community members. 
When there is a new version of Cura the plug-in might break. 

I believe @fieldOfView already released a new version of his plug-in, but it's still stuck somewhere in the reviewing process. 
I'll ask the team if they can take another look at it. 
You can however already download it here: https://github.com/fieldOfView/Cura-SidebarGUIPlugin/releases

I'll be closing this ticket since it's not something wrong inside of Cura.
