### ISSUE TITLE
Skirt/Raft/Brim are affected by support structures

### ISSUE THREAD

**Issue by anton-veretenenko** [Ultimaker/Cura#1360]
Application Version: 2.4.0-BETA2 Release date: 1/12/17
Platform: Ubuntu 16.04 64bit

Steps to Reproduce:
Enable Support and Brim, Skirt or Raft.
Noticed that it bugs out only if initial layer height set to <=0.1mm and layer height is set to >=0.2mm.
Also printer nozzle set to 0.35mm.

Actual Results:
Brim, Skirt or Raft appears only where support structures are projected to the build plate plane.

Expected results:
Brim, Skirt or Raft should appear under actual object.

Additional Information:
Screen 1: Expected results, but support is disabled.
![cura brim err 1](https://cloud.githubusercontent.com/assets/281043/22118023/fd3dd32e-de97-11e6-8d2e-c94b2e8e3439.png)

Screen 2: Support enabled, Brim is only under support structures and not actual object.
![cura brim err 2](https://cloud.githubusercontent.com/assets/281043/22118055/1b7cab94-de98-11e6-9a6f-6ab9c2e33d0b.png)

Screen 3: Support enabled, Skirt enabled, you can see that skirt is touching object now, but it should not.
![cura brim err 3 skirt](https://cloud.githubusercontent.com/assets/281043/22118102/47be6ddc-de98-11e6-941a-8799dfe80e8e.png)

Screen 4: Support enabled, Raft enabled, the same as with Brim.
![cura brim err 3 raft](https://cloud.githubusercontent.com/assets/281043/22118127/6a4077ba-de98-11e6-9ee8-0a51b7bf411d.png)

Object used for screenshots: https://www.amazon.com/clouddrive/share/6W4ESxmwCGnI78zdxfbI6Rg4F0nLgLFiTEkptXzXcd0
It is rotated, but it does not matter.

**Comment by anton-veretenenko** [comment]
Noticed that it bugs out only if initial layer height set to <=0.1mm and layer height is set to >=0.2mm.

**Comment by Ghostkeeper** [comment]
CuraEngine removes any empty layers on the bottom of the print, and moves the object down so that it lays on the bed. If support is enabled, it will provide support beneath anything that floats, causing the layers to be no longer empty. It therefore doesn't move the mesh down any more and only draws support on the first layer where it needs support. The first layer gets encircled by the brim/skirt/raft. Since the first layer consists only of support, it only encircles that bit of support.

This is ultimately the result of your mesh not being entirely flat on the bottom. This causes Cura to think support is necessary in a few places but not all. Cura won't move the mesh down automatically because there are corners protruding on the bottom, so it thinks the object is resting on those corners. Only the corners are too small to print, so CuraEngine won't draw any walls there.

You can work around the problem by moving the mesh down slightly, like 0.15mm seems to work. Or you have to modify the mesh so that it has a smooth underside.

**Comment by ianpaschal** [comment]
This is no longer an issue in 3.2.1.
