### ISSUE TITLE
S5: Unnecessary drive to Print-Head change

### ISSUE THREAD

**Issue by ManfredSchwarzAustria** [Ultimaker/Cura#13604]
### Application Version

5.2.0

### Platform

Windows 10

### Printer

Ultimaker S5

### Reproduction steps

Slice the project.
Print the job.

### Actual results

I work with latest Cura 5.2.0 and latest firmware of S5.

In my job are 4 different parts (attached). Until about 15% of the highness there is the second printer head necessary for the support of Breakaway.

Above of 15% there would be only head 1 necessare because there is no breakaway needed.

But the head is each layer driving to the right side and switch to head 2, switches immediately back to head one and prints the next layer.

### Expected results

Should not change the print header if it is not necessary.
[UMS5_SecuExBatt.zip](https://github.com/Ultimaker/Cura/files/9822456/UMS5_SecuExBatt.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

Project file attached

**Comment by GregValiant** [comment]
Thanks for the report.
One of the Ultimaker folks will take a look.  I was playing and created a gcode and this is a snippet from it.  Maybe it will give someone a clue.
T1
G92 E0
M104 T0 S195
M109 S220
M104 S230
M104 S220
;TIME_ELAPSED:10353.551898
;LAYER:89
;MESH:SecuExBatt_BattHalter.stl
G0 F9000 X330 Y219 Z20
G1 F600 Z20
G92 E0
T0
G92 E0
M104 T1 S194.9
M109 S195
G1 F1200 E9.5
G1 F600 Z20
G0 F9000 X192.913 Y100.045 Z20
M104 S205

**Comment by gr5** [comment]
I'm pretty sure this bug exists but the problem is I couldn't duplicate it in cura 5.0.0 so I tried running 5.2.1 (the latest) and it won't run for me.

Did you include a support blocker?  For me it's supporting this almost invisible ledge almost to the top of the tallest part and then about that everything is fine.

I suspect however that you have a support blocker mesh?  Sometimes when you open a newer project file in an older project you don't get quite everything loaded (like support blockers).

**Comment by ManfredSchwarzAustria** [comment]
Thank you for your effort. Hope Ultimaker staff finds the reason.

**Comment by gr5** [comment]
90% sure this is not a bug.  I thought he said it was switching the head without printing any support but it *is* printing support so this is not the bug I thought.  This issue should be closed.

**Comment by ManfredSchwarzAustria** [comment]
Don't understand your suggestion to close this issue.
The support is necessary only up to about 15% of the highness, but you can see in Greg images (thank you Greg) that in the second image the header still changes above of 15 % from 1 to 2 and back without printing any support.

**Comment by GregValiant** [comment]
@gr5 is an Ultimaker guy and I am not.  What I am though is persistent.
Because a thin line of support is being generated at around Layer 250 (to support the top edge of the shallow pocket on the side of the tall detail and which it fails to do) and since "Wipe Inactive Nozzle" is hidden but selected, it keeps going over to wipe the inactive nozzle until it is done printing the 4 or 5 layers of useless support.  After that it does not make any more trips to the purge station.
![image](https://user-images.githubusercontent.com/64202104/197239968-94cd2e3d-0982-453b-b306-26a761045456.png)

So if you put a support blocker on the top of the tall part to cover that little overhang, the issue goes away.
![image](https://user-images.githubusercontent.com/64202104/197238838-bbeff3c3-70e0-4544-85c6-2ff73b6840d5.png)

@gr5 I would be inclined to leave this open.  The movement occurs whether or not "Wipe Inactive Nozzle on Prime Tower" is enabled, whether or not the setting is visible, and whether or not the Prime Tower is enabled.  I also don't think that piece of support should be generated.  The X/Y distance is 1.0 and that pocket is only 0.20mm deep.

**Comment by gr5** [comment]
Lots of things will make the support go away.  It's only 0.2mm deep but it's still an overhang.  I found if layer height was 0.2mm and min support angle was 45 degrees it would do support.  But if you make the angle more horizontal such as 60 then it decides it doesn't need support because when you look at the angle from one layer to the next (0.2mm) and the overhang is 0.2mm so that's 45 degrees.  I also found if I changed it to 0.3mm layer height then I could leave min support angle at 45 and it wouldn't do support because now that overhang is looking more vertical.  Am I making sense?

Anyway this support feature is a feature and not a bug.  There is a "minimum overhang area" setting but no "minimum overhang distance" variable.  If there was then it should default to maybe 0.4mm and ignore overhangs like on your part.

**Comment by ManfredSchwarzAustria** [comment]
Thank you Greg and g5 for explanation and find out the reason of this behaviour.
For me its clear now. It is not really a bug and its on Ultimaker if they want to improve such situations.
My suggestions would be to suppress a header change in case of no printing whith the changed header, if it is not used in this layer. Also if the reason is a too thin printing width.
Anyway, I think I will close this topic.
Thank you.

**Comment by GregValiant** [comment]
It is impossible to catch everything that goes on in a slice.  The user has to be responsible for what the collection of settings is doing since the setup is the user's choice.  The software cannot determine "Is this what you really want?".

This particular problem was hard to find.  As gr5 says, several settings could affect what was going on.  In the case of the Support Horizontal Expansion:  at 1.0 SHE the support was moved into the area of that little overhang.  At 0.8 SHE it misses it since it is a 0.20 overhang.  Very subtle.  I found it when I did a comparison between a "virgin" Fast .2 profile and the Fast .2 profile overrides that are in the project file.
