### ISSUE TITLE
Bridging sometimes doesn't bridge

### ISSUE THREAD

**Issue by Triangulix** [Ultimaker/Cura#13623]
### Application Version

5.1.0

### Platform

Windows 10

### Printer

Custom

### Reproduction steps

Slice the attached project

### Actual results

Layer 4 is printed a normal layer.

### Expected results

The gap below layer 4 should be bridged.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[Bridging.zip](https://github.com/Ultimaker/Cura/files/9844646/Bridging.zip)
![Bridging](https://user-images.githubusercontent.com/43012099/197346574-bf793244-3901-4495-886c-4bb31b632ad0.PNG)

**Comment by MariMakes** [comment]
Hey @Triangulix,

Thanks for your report 👍

At first glance, it might be related to the Bridge Skin Support Threshold. 
The setting might be too low to actually show bridging. 

Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

**Comment by Triangulix** [comment]
The atttached zip file contains the project.

**Comment by MariMakes** [comment]
Hey @Triangulix,

You are correct. I must have overlooked it. 

I changed the Bridge Skin Support Threshold, and this results in the bridge being bridged. 
![image](https://user-images.githubusercontent.com/40423138/197982136-9ba9c9e3-4614-432b-a38d-58fd181ffcbd.png)

Does this resolve your problem? 👼

**Comment by MariMakes** [comment]
If you check the layer before the layer that needs to be bridged, you can see that about 75 percent does not need any bridging because it has a layer of skin underneath it. That is higher than the default 50 percent, which is why it's treated as normal skin instead of a bridge. 
![image](https://user-images.githubusercontent.com/40423138/198290471-d7267f79-216e-4a3a-8e8b-4511e5510242.png)

You can read more about the setting in the settings guide. 
https://github.com/Ghostkeeper/SettingsGuide/blob/master/resources/articles/experimental/bridge_skin_support_threshold.md

Would you agree it's intended behavior and we can close the issue? 👼

**Comment by Triangulix** [comment]
Okay, I understand.
