### ISSUE TITLE
Bad supports, allwais from builplate, 5.2.1 and 5.1.1

### ISSUE THREAD

**Issue by UMCURA** [Ultimaker/Cura#13693]
### Application Version

521 and 511

### Platform

Windows 10

### Printer

Custom

### Reproduction steps

Supports alwais from builplate, select 'normal' and 'everywere'. Nozle 0.2, layers 0.2

### Actual results

Don't work properly

### Expected results

If I select supports 'touchin buildplate' OK, from buildplate, but if I select 'From everywhere' , from objet, is what other software do (ej. Cura 15.04.6) and I can´t solve it in Ultimaker Cura.
Thanks.
![Mierda](https://user-images.githubusercontent.com/117018370/198879136-b4e75323-4863-40de-8330-54d6cc6e7471.jpg)
![Cura](https://user-images.githubusercontent.com/117018370/198879345-240ae6fd-db89-49f9-a8ad-9ca1c4519bd6.jpg)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

[U2.zip](https://github.com/Ultimaker/Cura/files/9895840/U2.zip)

**Comment by MariMakes** [comment]
Get @UMCURA ,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report 👍

Between Cura 15.04 and Cura 5.2 is at least 6 years of development. 
Probably even more. So you are bound to encounter some differences. 

But I'm having trouble recreating your first screenshot.
If I change my support horizontal expansion, this is the closest I can come.
![image](https://user-images.githubusercontent.com/40423138/199027040-3749e70c-c30e-4eca-bd96-128975c7fbc6.png)

Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.

**Comment by UMCURA** [comment]
Sorry, added.
[CFFFP_U2-02_02-2h43.zip](https://github.com/Ultimaker/Cura/files/9901884/CFFFP_U2-02_02-2h43.zip)

**Comment by MariMakes** [comment]
Hey! Thanks for sharing the project file. 💪 

I can see the setting that's impacting your quality.
It's Use Towers. If you disable it you get your old behavior back. 
![image](https://user-images.githubusercontent.com/40423138/199040645-6ffd499c-f8aa-4203-b407-81074b2f0e54.png)

For some unsollicited advice.
Personally I would increase your Wall Line Count to 3. 
I believe it would get a better result in this model because Cura is trying hard to fill a small space with zigzag infill. 
![image](https://user-images.githubusercontent.com/40423138/199041289-31587895-000d-4a2a-b1aa-70446911c62a.png)

Do you still believe it's a bug in Cura? Or would you agree to close the ticket?

**Comment by UMCURA** [comment]
Hello, thank you very much, I didn't even have that option visible. I have to investigate more this of the supports, too many options. Thanks again. I close.
