### ISSUE TITLE
crash error when slicing stl piece

### ISSUE THREAD

**Issue by vascocrocha** [Ultimaker/Cura#13695]
### Application Version

5.1.0

### Platform

windows 10

### Printer

custom printer Alfawise U20 Plus based

### Reproduction steps

slicing SLT file almost fullfilling the 400x400 whole bed size

### Actual results

nothing... after report the error just appears exactly as if the program was starting 

### Expected results

![screenshot 608](https://user-images.githubusercontent.com/12284164/198902396-3545d0f8-857d-4068-b104-85eba58be6f0.jpg)

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[report-cura-5.1.0-slicing.zip](https://github.com/Ultimaker/Cura/files/9896860/report-cura-5.1.0-slicing.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
The model has some errors (the "model is not watertight" warning came up when I checked the model with the Mesh Tools plugin) but it sliced fine in 5.2.1.
Cura 5.1 for Windows had a slicing bug that could be bypassed by moving and/or rotating the model on the Cura build plate.  You don't have much room to move it but rotating 90° often worked.

I'll note this as a slicing error and as a duplicate.  Since this was fixed in 5.2.1 I'll go ahead and close this report.  If you feel that this should remain open let us know.

BTW I attempted to fix the model but with over 1.1 million triangles and over 3.3 million vertices neither Mesh Mixer nor MS 3D Builder could handle the repair.  

Here it is sliced in 5.2.1
![image](https://user-images.githubusercontent.com/64202104/199008963-563f0618-6c9a-4b95-9064-50189d86ae84.png)
