### ISSUE TITLE
Support Blockers cause extrusion to halt for the whole print

### ISSUE THREAD

**Issue by Arson31** [Ultimaker/Cura#13726]
### Application Version

5.1.1

### Platform

Windows 10

### Printer

Voxelab Aquila

### Reproduction steps

1. Load any STL that requires supports to bed
2. Add supports everywhere (regular or tree doesn't matter)
3. Place support blockers
4. Print

### Actual results

Print starts out fine until it hits a certain layer with a support blocker. I thought it was heat creep, the extruder, a clog, or the STL and my print settings. I realized I used support blockers for my prints and whenever I use support blockers the printer stops extruding completely and continues to print in the air without any filament extruding.

### Expected results

Print as normal but omit printing supports on a particular region of the model and not the rest of the print.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

The latest version of Cura 5.2.1 wouldn't slice the model so I downgraded to 5.1.1. I do not believe there's something wrong with Cura itself but how it handles support blockers when printing so uploading the log file and project file wouldn't help. I am using a custom firmware on my printer https://github.com/alexqzd/Marlin (ManualMesh-3x3-G32.bin) but I'm not sure how to prove if it's the firmware.

**Comment by GregValiant** [comment]
Thanks for the report.
I can't duplicate this.  I have a print running right now with blockers and it's printing fine.  We really need a Project File for debugging.  The "model wouldn't slice in 5.2" is an interesting tidbit but shouldn't affect this bug report.

How did the Cura preview look?  Have you tried opening the gcode file in Cura?  The blockers won't be there but all the moves should be (unless you used Arc Welder as Cura gcode reader doesn't understand G2-G3 moves).

**Comment by Arson31** [comment]
@GregValiant The project file is too large even compressed as a 7z file (69.2 MB) and the project file size is 136.1 MB. I do have bridge settings enabled and changed the bridge fan speed to 50% and maybe that causes a stoppage? I did printed a different STL that had the same problem but without support blockers and bridge settings turned off and it printed fine for 8 hours.

**Comment by Arson31** [comment]
> How did the Cura preview look? Have you tried opening the gcode file in Cura?

@GregValiant The Cura preview looks fine and the gcode preview does what it should when I run the preview. I don't see anything wrong with the gcode in a editor other than `M82 ;absolute extrusion mode` near the beginning of the file and again near the end of the file.

**Comment by GregValiant** [comment]
Unless you have set Cura up to create a "relative" gcode file (Special Modes - Relative Extrusion) then there will be an M82 at the beginning of a file.  The M82 at the end might be there because it is in your Ending Gcode and might come after an M83 set the printer to "relative" mode for a retraction move.  (Pause at Height also does that).
When a printer is fed a command that it doesn't recognize (unsupported in the firmware) then it should just ignore it and move to the next command.
"Blockers" (no matter how they are configured) affect Cura's calculations but the printer doesn't know anything about their existence.  There are no blockers in a gcode file - only the commands that Cura generated in response to a blocker in the Preview screen.  It's just G1's and G0's with maybe a change in speed and/or Accel and Jerk.  That's normal and should not stop printing.
If you could use a simple model and recreate the "blocker situation" in it the same way as is affecting your huge file then you could post the simple file here.  The other possibility would be to post those large "problem" gcode and 3mf files on a site like Google Drive and post the download link here.

If this was a Cura bug hundreds of people (including me) would be complaining and I don't see that.  It's something to do with your printer or possibly (a very low percentage chance) it's the way your firmware is interpreting a gcode command.

Are you printing via:  SD card?  USB?  Octoprint?

**Comment by Arson31** [comment]
@GregValiant There must be partial clogging or some weird extrusion issues because I started a new print for a different STL that doesn't require supports and it stopped extruding late on the initial layer. I'm closing as it has nothing to do with support blockers.

**Comment by GregValiant** [comment]
It was constant clogs at the hot end of the bowden tube that caused me to move to an all metal hot end on my Ender 3 Pro.  It isn't maintenance free but it's a LOT better than the stock hot end.
