### ISSUE TITLE
Vase Mode

### ISSUE THREAD

**Issue by FlappyJOKER** [Ultimaker/Cura#13766]
### Application Version

5.2.1

### Platform

windows 11

### Printer

Artiller Genius pro

### Reproduction steps

when activating spiral mode for vase mode i get some weird strings

### Actual results

got the strings on the thing i printed

### Expected results

shouldnt get any strings

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

I dont have any

**Comment by GregValiant** [comment]
Thanks for the report.
Vase mode is different in 5.x than it was in 4.x.  Without seeing the model I'm guessing it has a hole in the center section.  You aren't getting strings but rather actual extrusions.
Take a look at bug report #13745 and you will see a couple of screenshots.  I'm sure they will look familiar.

I'll mark this as a duplicate and close it as I'm pretty sure from your description that this is "expected behavior" of vase mode in Cura 5.x .  If you would want me to re-open this then zip up and post a project file with that model and someone will take a look at what is going on.
