### ISSUE TITLE
Slice failure.

### ISSUE THREAD

**Issue by DagnosVera** [Ultimaker/Cura#13792]
### Application Version

5.0.0

### Platform

Windows 10

### Printer

Longer LK5 Pro

### Reproduction steps

loaded model from .stl file. moved it 5mm above build plate and copied it. scaled the copies. sliced.

### Actual results

slice resulted in 1 apparent layer (based on slider on right). Also shows print time of 0 minutes and material cost of 0, indicating that nothing would actually be printed.

### Expected results

Should have been at least 40-50. Expected print time of at least 30 minutes and material cost of maybe $0.25-$0.50

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[watch_back_tool.zip](https://github.com/Ultimaker/Cura/files/9991731/watch_back_tool.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
I guess that when all models are up off the build plate you can't use Adaptive Layers so turn that off.
With Adaptive Layers turned on - I dropped one model down to the build plate and slicing succeeded.  If you feel you really need adaptive layer heights for this then I suggest you add another model (a sacrificial model) and put it on the build plate.

A raft seems like overkill on this.  You might want to consider a brim.

**Comment by GregValiant** [comment]
If they are getting smashed looking then your bed may be too hot.  If you have kicked up the temperature because of problems getting the first layer to adhere to the bed you can try using hair spray (I use AquaNet Super Hold here in the US) or there are other adhesion promoters.
You want the bed below the "glass" temperature of the material you are using.  For PLA that is around 60°.  For a comparison I run my bed at 50° for PLA.  One of the signs of a bed that is too hot is elephant's foot where the lower layers spread out beyond what the model size is.
If your hot end temperature is too hot then the new material may be melting the layer below.  Have you done a temperature tower or other  temperature calibration?  Not all materials are created equal and there can be variation by color as well.  I print white PLA at 200 and most others at 205.  Silky PLA has poor layer adhesion so I print that at 210 or 215 depending on the size of the model.  Large models give the material more time to cool before the nozzle comes around again.

**Comment by GregValiant** [comment]
Your filament manufacturer should have suggested numbers for their PLA+.  That would give you a starting point.  The faster your print speed is the greater the flow rate through the nozzle and the filament has a cooling effect so there is a point at which a hot end can't keep up.  I didn't note anything excessive in your settings but every printer is at least a bit different.
One thing you can do is to move those pieces apart farther so they can be printed "One at a Time".  After slicing, check the Cura preview for the print order and make a little chart of that.  After creating the Gcode open the file in a text editor and search for "LAYER:0".  There will be one for each model.  Add a line right before each "Layer:0" line that will change the temperature a bit.  M109 Sttt (where ttt is the temperature) will cause the printer to pause while the temperature adjusts upwards.  The lowest temperature would go on the first model printed and each model's print temperature will increment upwards.  It's a "Temperature Basement" rather than a "Temperature Towerr".  I suppose you could do the same with the bed temperature but do one temperature test at a time.

Bed adhesion is a tricky combination of the material, bed temperature, any "adhesion promoter", and the bed leveling.  I level with my trusty piece of parchment paper and I'm very consistent but I still run my "Initial Layer Flow" at 105% just in case.
I'm also fastidious about printing on a clean bed (90% IPA (Isopropyl Alcohol, not beer)) although on parts that don't have a lot of bed contact I will use the hairspray and a brim.  (BTW - Setting the "Brim Distance" to a small number like 0.1mm makes it easier to break off.)
I believe white filament is colorized with titanium oxide (as are a lot of paints).  It's a metal and so the thermal properties will be different from what you would get with other colorants.

**Comment by jellespijker** [comment]
Thank you for your report. It seems that your uploaded project file slices correct on our latest unreleased 5.7.0-alpha.0+3abb5 which indicates that the issue you're experiencing seems to be fixed for the upcoming 5.7.0 release.
I'm closing this issue as fixed for the 5.7.0 release
![image](https://github.com/Ultimaker/Cura/assets/8535734/a4a10294-b961-4302-ba0c-4fbef4b09ead)
