### ISSUE TITLE
Slicing Error

### ISSUE THREAD

**Issue by lkrammes** [Ultimaker/Cura#13802]
### Application Version

5.2.1

### Platform

Windows 11

### Printer

Ender 5 Plus

### Reproduction steps

1. Tried to slice

### Actual results

1. slicing failed

### Expected results

2. slicing success

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[CE5PLUS_Fan_With_Supports.zip](https://github.com/Ultimaker/Cura/files/9995268/CE5PLUS_Fan_With_Supports.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
The 3mf file sliced for me quickly and with no problems so I can't duplicate the issue.
If you haven't tried yet - rotate the model and/or move it on the build plate.  There have been bug reports regarding non-slicing and movement/rotation can sometimes fool the bug.
There doesn't appear to be any errors in the model.  I ran it through MS 3D Builder which seems to have made it a single mesh instead of 23 separate meshes.  the "fixed" model sliced as well.

Let us know if that works for you so I know whether this should be marked as a duplicate.
![image](https://user-images.githubusercontent.com/64202104/201490775-f5d5d18e-5dfe-49a9-a542-4dda8474006e.png)
