### ISSUE TITLE
Multiple issues while slicing

### ISSUE THREAD

**Issue by Westboundbiker** [Ultimaker/Cura#13818]
### Application Version

5.2.1

### Platform

Windows 10

### Printer

Ultimaker S5

### Reproduction steps

Opened a file to slice, positioned it, sliced it to determine which height I needed to pause at in order to put in embedded nuts.  Added pause at height, and support blockers.  When I resliced, I realized that the layer height indicator in the upper left did not reflect what was selected (see attached image), not did the infill match.  Changing the Infill pattern or percent and resclicing did not change the infill.  Changing the profile to different layer heights did change the print time, but did not correct the upper number.
![image](https://user-images.githubusercontent.com/118201619/201708017-c2a9184f-275b-4be2-8fb5-c0d584e9a570.png)

### Actual results

Changing the Infill pattern or percent and resclicing did not change the infill.  Changing the profile to different layer heights did change the print time, but did not correct the upper number.

### Expected results

The upper number should correctly reflect what is selected, and the infill needs to change when selected.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[slicing issue.zip](https://github.com/Ultimaker/Cura/files/10004833/slicing.issue.zip)

**Comment by GregValiant** [comment]
Thanks for the report and the project file.
I can't duplicate the problem.  When I change the infill settings (both type and density) the preview reflects my changes.  You have the pause layer set to 222 and given the layer heights in the file, I agree that is the correct layer.  222 will print and the machine will pause.
This is with Grid at 10% density and the infill angle at 90°.
![image](https://user-images.githubusercontent.com/64202104/201737361-c88311c0-093f-44ee-9cf1-9bc13d25a5ed.png)

_"...the layer height indicator in the upper left..."_
I have to admit I don't know what that means.  I'm not aware of a "layer height indicator" in Cura but that might be because my video system uses OpenGL 4.0 and so I am in compatibility mode.  Could you describe where it is in your screenshot?

**Comment by Westboundbiker** [comment]
Yeah, after I submitted that, my coworker suggested restarting the
computer, and that did resolve the issue.

Yeah, the pause at later has always worked well for me, I just wanted to
include that in the event that it happened to be related.

I apologize- upper right, not upper left.  Yours doesn't quite match my
display, but my screenshot shows it, if only I hadn't mistyped it probably
would have been more clear!  It's not so much the later height indicator,
but on the prepare tab where the selected profile is displayed, vs what is
selected in the drop down menu under the advanced print settings.

**Comment by GregValiant** [comment]
OK.  The "Sprint - 0.2mm" is the name of the profile.  You can change the layer height but that "0.2" won't update.  It's part of the name rather than reflecting your settings.

Can I go ahead and close this then?

**Comment by Westboundbiker** [comment]
Sorry, the profile name wouldn't update correctly.

But yeah, you can close it.

**Comment by GregValiant** [comment]
Thanks.  I'll do that.
