### ISSUE TITLE
Slicing fails on Anycubic Kobra Max after scaling above 123%

### ISSUE THREAD

**Issue by SeraphMorningstar** [Ultimaker/Cura#13834]
### Application Version

5.2.0 - 5.2.1

### Platform

Windows 10

### Printer

Anycubic Kobra Max

### Reproduction steps

1. load in STL file
2. scale above 123% (works perfect at 123% and below)
3. Slice

### Actual results

notification:

<img width="305" alt="Capture" src="https://user-images.githubusercontent.com/24765983/202014167-60f0549b-f3e3-4937-b3d2-899a72d6a6f2.PNG">

### Expected results

File slices without issue

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

Log:
[cura.log](https://github.com/Ultimaker/Cura/files/10015873/cura.log)

Project:
[AKMAX_Galleon-Back-Top-v1.0.zip](https://github.com/Ultimaker/Cura/files/10015850/AKMAX_Galleon-Back-Top-v1.0.zip)
(file in project already scaled to 125%, error can be triggered by just slicing)

**Comment by GregValiant** [comment]
Thanks for the report and the files.
I wasn't able to slice this as received.  When I checked the model in MS 3D Builder it had errors and the app was able to repair it.  I deleted the "as received" model and loaded the repaired model and it sliced without problems.

So this appears to be a model issue.  MS 3D Builder is included with Windows so you can repair it yourself and try slicing it again.  Let me know how you make out since this doesn't appear to be a Cura bug and maybe we can close this.
![image](https://user-images.githubusercontent.com/64202104/202059798-1ba80d94-0c7d-48af-98a6-163518a9be97.png)

**Comment by SeraphMorningstar** [comment]
hey @GregValiant , thanks for looking into it so fast!
It was indeed a model issue.
I've re-downloaded it from the source and was able to scale to 125% and slice it.

**Comment by GregValiant** [comment]
Very good and thanks for getting back.
I'll go ahead and close this.
