### ISSUE TITLE
Cura 5.2.1 not usable under RDP sessions anymore. Massive slowdown of keystrokes

### ISSUE THREAD

**Issue by Marsupilani** [Ultimaker/Cura#13859]
### Application Version

5.2.1

### Platform

Windows 10

### Printer

Customr

### Reproduction steps

Since 5.x the application is usable by RDP anymore. Until 4.x I did not have an problems to use the application by RDP, but now sind 5.x (I use 5.2.1 at the moment) every keystroke use about 10-20 second over the RDP session. Memory and CPU and Network usabage are low (6% CPU (i7 6700);6 of 48GB RAM;about 100kbit Network usage; Nvidia Geforce 1650 with newest drivers (11/2022) and openglrdp.exe executed and rebooted...)
after stop of cura 5.2.1 the system is fast again...latest cura 4 did not have any such problem.... 
under 5.2.1 the problem begin at "Loading UI" during startup

### Actual results

cura 5.2.1 is not usable anymore for me

### Expected results

working over RDP possible like 4.x before.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

no logfiles...

**Comment by MariMakes** [comment]
Hey @Marsupilani,

Welcome to the Ultimaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

Your issue is very much outside my field of expertise.
Am I correct in assuming that RDP = Remote Desktop Protocol? Is that similar to a Virtual Machine?

We've had some community members brainstorming on how to improve the performance on virtual machines.
You can read more about it here: https://community.ultimaker.com/topic/21142-cura-running-on-virtual-machine/#comment-313163

Is this the type of information you are looking for? 
If it's not, feel free to let me know and we can bring it up to the team or find a solution together.
