### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by spacepiratedkk** [Ultimaker/Cura#13877]
### Application Version

5.0

### Platform

windos 10 

### Printer

anycubix xhrion 

### Reproduction steps

slice model 
https://www.thingiverse.com/thing:4082597 

### Actual results

the slicer charashed

### Expected results

to slice it and give me the g-code

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![Skærmbillede 2022-11-22 191746](https://user-images.githubusercontent.com/118845982/203391326-a53787d2-b8f9-4e76-95f5-3a9d36b060c5.jpg)
![Skærmbillede 2022-11-22 191855](https://user-images.githubusercontent.com/118845982/203391330-0b474608-5313-4feb-b7d6-140323c9db66.jpg)
![Skærmbillede 2022-11-22 191916](https://user-images.githubusercontent.com/118845982/203391333-7d93e01d-8961-4de3-ab0b-7411b4da5f0d.jpg)

**Comment by Asterchades** [comment]
You're going to need to include a project file for this to be diagnosed properly. I had no issue slicing under 5.2.1.

Note that several fixes for models failing to slice were implemented with both 5.1 and 5.2. It may simply be that updating to a newer version allows you to slice the model, which you would need to do in order to receive any fixes anyway.
