### ISSUE TITLE
Slicing failed

### ISSUE THREAD

**Issue by lollp** [Ultimaker/Cura#13900]
### Application Version

5.2.1

### Platform

Windows 10

### Printer

Ultimaker 3

### Reproduction steps

Try to slice the attached project.

### Actual results

Error slicing failed

### Expected results

Slicing done

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[Probelmatic slicing.zip](https://github.com/Ultimaker/Cura/files/10094535/Probelmatic.slicing.zip)

**Comment by GregValiant** [comment]
Thanks for the report and the project file.
Finally...a real model that doesn't involve scales or murder holes or hokey articulation.  An added bonus is that it sliced for me on the first try.
![image](https://user-images.githubusercontent.com/64202104/204056072-3bcf7b0d-142d-4217-9853-75f0a8b0ec03.png)

There have been several bug reports about good models that won't slice in the orientation that they come into Cura at.  A workaround that is pretty consistent at fooling the bug is to move and/or rotate the model on the Cura build plate.  When the slicer comes at it from a different angle there is enough of a difference that the bug often doesn't notice.
Try that and see if it works for you.  I'll mark this as a duplicate but I'll leave it open for now.  Someone from the Cura team may close it since there is a lot of evidence about this bug.
