### ISSUE TITLE
Rectangular model with penetrating features and an extra layer on the inner wall

### ISSUE THREAD

**Issue by CHAKone** [Ultimaker/Cura#13946]
### Application Version

5.2.1

### Platform

windows10

### Printer

vyper

### Reproduction steps

![Snipaste_2022-12-01_23-20-18](https://user-images.githubusercontent.com/68198756/205091853-da55763f-2929-48ec-bf4d-f0e915d5c66f.png)
![Snipaste_2022-12-01_23-19-20](https://user-images.githubusercontent.com/68198756/205091859-1b8dd7ed-d980-451b-8c3f-c5f519931b38.png)
![Snipaste_2022-12-01_23-17-57](https://user-images.githubusercontent.com/68198756/205091865-4a0a0285-9d9a-436c-b5f4-05f4973922d4.png)
![Snipaste_2022-12-01_23-16-45](https://user-images.githubusercontent.com/68198756/205091868-502b41ae-c14c-418e-9eb9-25667f5ae5d1.png)
![Snipaste_2022-12-01_23-20-47](https://user-images.githubusercontent.com/68198756/205091873-10da8429-a282-44eb-8dd3-42040abc4641.png)

### Actual results

As shown in the figure, if the rectangular inner wall has a through (penetration) feature in the model, the slice will appear to have an extra layer of inner wall at the location of the (penetration) feature. The problem is still the same in test version 4.13.

### Expected results

![Snipaste_2022-12-01_23-20-47](https://user-images.githubusercontent.com/68198756/205093435-2bee7a74-752d-40de-aae0-98c9854af8b2.png)
![Snipaste_2022-12-01_23-20-18](https://user-images.githubusercontent.com/68198756/205093443-91dc23d5-9110-4a88-8969-1d23a920b4ac.png)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

This problem occurs for all rectangles with (through) or through features

**Comment by GregValiant** [comment]
Thanks for the report.
You didn't include a project file so I will guess and say that you have "Hole Horizontal Expansion" enabled.  When Cura slices where those slots are then the hole isn't a hole anymore but some other shape.  Once it gets above the slots then it's a hole again and Hole Horizontal Expansion kicks back in and you get that ledge.  You will need to turn off Hole Horizontal Expansion to get rid of that step.
The @smartavionics fork of Cura (based on the 4.x versions of Cura) has a setting for this condition.

I'll remove the bug label as this is (for now) the expected behavior of UM Cura.  I hope you understand.

**Comment by CHAKone** [comment]
> 
Thanks for your reply to answer your question. After changing the settings as you suggested, the slice preview is now normal.
Thank you

**Comment by GregValiant** [comment]
I'm going to close this.  Let me know if you think that is premature.
