### ISSUE TITLE
Bad translation in French for printing settings

### ISSUE THREAD

**Issue by samy** [Ultimaker/Cura#13966]
### Application Version

5.2.1

### Platform

Windows 10

### Printer

Longer LK4 Pro

### Reproduction steps

- Open Cura
- Set French as language in settings
- Restart Cura 
- Open "Printing settings" panel on the right

### Actual results

"Risoluzione" is displayed for resolution settings label

### Expected results

"Résolution" is the right translation, "Risoluzione" is in Italian

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![image](https://user-images.githubusercontent.com/1282106/205509413-e859c6d7-1b3c-42dd-9b21-9bece3a57344.png)

**Comment by MariMakes** [comment]
Hey @samy,

Thanks for your report 👍

This issue confused me a little. 😅 
I can see that the correct translation is present in main: 
https://github.com/Ultimaker/Cura/blob/4a0711b66535bc3c0021a4cb140ff1b69aac799c/resources/i18n/fr_FR/cura.po#L6029

but the correct translation is present in 5.2.1
https://github.com/Ultimaker/Cura/blob/b81dfc320c73c50c482a6cee59c8652899d3f773/resources/i18n/fr_FR/cura.po#L5996

Since Cura 5.2.1 was a patch release to restore the french translations, because they were Italian this one might have slipped through. 

But since it's already resolved in Main it should show up correctly in Cura 5.3. But I'll keep an extra close eye during our next release.

To me, it doesn't seem like a bug in Ultimaker Cura, since we have a solution in place. Would you agree that we can close this issue?
