### ISSUE TITLE
Cura v5.2.1 - forever slicing

### ISSUE THREAD

**Issue by pportnawak** [Ultimaker/Cura#13976]
### Application Version

5.2.1

### Platform

Debian 11

### Printer

Monoprice Mini Delta V2

### Reproduction steps

Change settings for support

### Actual results

slicing ....

### Expected results

preview of stl

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[alfbug.zip](https://github.com/Ultimaker/Cura/files/10156288/alfbug.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
This is a shot from Mesh Mixer.  The red balls indicate errors in the model.  They can have an effect on the slice and the model might not print correctly.
![image](https://user-images.githubusercontent.com/64202104/205713691-3f413123-99bb-4991-ad5f-058b9a56c9c0.png)

This is Mexh Mixer's attempt at repair.  It looks like the repair was incomplete and there are holes in the model and Cura can't slice this as the model isn't solid.
![image](https://user-images.githubusercontent.com/64202104/205733229-1c2bfbe5-3ed7-45a8-aa76-3a866625bcbe.png)

I tried MS 3D Builder and it's repair finally got it to slice.

This might be a Cura bug but your model has some serious issues that are at least making the water muddy so it's hard to tell what is really going on.

Here is the repaired model sliced.  I had to remove the blockers because I replaced the model.
![image](https://user-images.githubusercontent.com/64202104/205733641-84ea66d8-263b-41af-8c9b-97b50c667847.png)

**Comment by pportnawak** [comment]
ok.
the original file (stl) didn't have holes. I opened it again and there it is.
IMHO  if there are holes in the model, there should be a warning somewhere in cura.
![curascreen](https://user-images.githubusercontent.com/19382654/205854597-11a6a9c5-3cdd-4beb-8cc3-574ff417a83f.png)

**Comment by GregValiant** [comment]
If you would go to the MarketPlace there is a very handy plugin called "Mesh Tools" that (when loaded) does perform a check when you load a model.  It also has some repair capability that is fine for small defects.  Your model needed some serious repair though.

**Comment by pportnawak** [comment]
Thank you for pointing me to the plugin.
The stl i loaded is - and was - whole as meshlab saw it.The export didn't and i don't know why.My first print was okay besides having no support.
regards

    Le mardi 6 décembre 2022 à 12:46:00 UTC+1, GregValiant ***@***.***> a écrit :  
 
 


If you would go to the MarketPlace there is a very handy plugin called "Mesh Tools" that (when loaded) does perform a check when you load a model. It also has some repair capability that is fine for small defects. Your model needed some serious repair though.
