### ISSUE TITLE
slicing failed

### ISSUE THREAD

**Issue by reakmal** [Ultimaker/Cura#14059]
### Application Version

5.1.1

### Platform

windows 10

### Printer

ultimaker 2+

### Reproduction steps

1. I put my 3D part for printing.
2. I click the slice button.
3. than has report bug popup.

### Actual results

1. I click that report button.
2. and here I am do the report.

### Expected results

1. this problem solves.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

[UM2_BOTTLE -A1.zip](https://github.com/Ultimaker/Cura/files/10243235/UM2_BOTTLE.-A1.zip)
![slice bug](https://user-images.githubusercontent.com/120705986/208038250-f81ca85f-af15-4ee0-a71f-8aa2079bd0a8.png)

**Comment by GregValiant** [comment]
Thanks for the report.
Slicing failed when I opened your project.  I slid both the models in the X and it sliced.
This bug was worked on and isn't as bad in 5.2.1 but it's still there.  It seems to only occur on Windows installations.
Hopefully it will be fixed in 5.3.
I'll mark this as a Duplicate and a Slicing Error and close this ticket as the Cura team has lots of examples of this bug to work with.  If you think that is premature let us know.

Here are the models in their new locations and sliced with your settings.
(BTW I think you could go to 3 walls and 15% infill and have robust prints.  It would knock an hour and a half off the print time as well.)
![image](https://user-images.githubusercontent.com/64202104/208103074-a5ec975e-e5b4-47c3-b0a3-6f756dc02121.png)
