### ISSUE TITLE
Failed slice 

### ISSUE THREAD

**Issue by Magic2226** [Ultimaker/Cura#14057]
### Application Version

5.2.1

### Platform

Windows 11

### Printer

Creality Ender 6

### Reproduction steps

Imported a model
Had already done the same for 2 others.
Same settings, hit SLICE
Slice starts to move then Slice fails.

### Actual results

Slice fails

### Expected results

Expected to slice as the 2 models before this one. Slices fine in Cura 4.13.1 Will not slice same settings in 5.2.1
![image](https://user-images.githubusercontent.com/42921935/207989970-91ecb605-667b-4235-b865-513be75e94a9.png)

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[CE6_model 1 failed slice.zip](https://github.com/Ultimaker/Cura/files/10241502/CE6_model.1.failed.slice.zip)
[cura.log](https://github.com/Ultimaker/Cura/files/10241503/cura.log)
![image](https://user-images.githubusercontent.com/42921935/207990858-2cd215c3-bc25-446f-bb1a-a4730b4921bf.png)

**Comment by GregValiant** [comment]
Thanks for the report and the file.
I didn't have any trouble slicing the project file so I can't duplicate the problem.
There have been numerous bug reports about models that won't slice when they are in the center of the build plate.  A workaround is to move and/or rotate the model in Cura.  That often gets it to slice.  The bug is being worked on and hopefully will be fixed in 5.3.
If (hopefully) you get it to slice - look at the torso from layers 295 to about 370.  Something doesn't seem right through there.
I took the liberty of making some adjustments to your settings and I'll include my project file.  You can always disregard it.
[GV_model 1.zip](https://github.com/Ultimaker/Cura/files/10246150/GV_model.1.zip)

Here it is sliced with your settings.
![image](https://user-images.githubusercontent.com/64202104/208108543-0e7dc114-1a6c-485f-8c8a-5c3e539716e3.png)

Here he is sliced with my settings.  I moved it down into the build plate by 0.5mm because one leg is longer than the other.  I added the cutting mesh to keep that loopy looking feature on the shoulder from slicing. It would probably fail anyway.
![image](https://user-images.githubusercontent.com/64202104/208108236-594a9d1d-f255-42e0-93da-b4f941712da8.png)

I'll mark this as a Duplicate and close it as the Cura team is aware of this bug.  Let me know if you think that is premature.
