### ISSUE TITLE
Combing/Travel move seems wrong

### ISSUE THREAD

**Issue by dgrat** [Ultimaker/Cura#14064]
### Application Version

5.2.1

### Platform

Windows 10

### Printer

Custom

### Reproduction steps

Load the project, review the combing/travel move

### Actual results

The top two travel moves are blue (?no retract?)

![grafik](https://user-images.githubusercontent.com/4668178/208172165-5bac2778-1470-49c7-b05e-307898270532.png)

### Expected results

The top two travel moves are grey (?retract?)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[combing_retract_issue.zip](https://github.com/Ultimaker/Cura/files/10248404/combing_retract_issue.zip)

**Comment by GregValiant** [comment]
Thanks for the report and the files.
It appears to be a display issue.  They might be a different color if they are on the top 5 layers and you have that option enabled in the line types.
I checked the gcode file and all those part-to-part moves are travels with no extrusions.  There are 1084 retractions in the gcode file created from your project.
You have coasting turned on and Cura displays the coasting part of an extrusion line as a travel because it has no E parameter in the gcode line.

So this looks like it might be a display thing rather than a bug.  If you turn off the "travel" lines do all those blue lines go away?
I've removed the bug label.  If you think that is premature let me know.
