### ISSUE TITLE
Slicing Failed

### ISSUE THREAD

**Issue by PolyPrintYT** [Ultimaker/Cura#14063]
### Application Version

5.1.1

### Platform

Windows 10

### Printer

Artillery Sidewinder x1

### Reproduction steps

1. Loaded my Model in
2. Infill to 0%
3. Hit Slice
4. Slicing Failed

### Actual results

Slicing fails and aborts, down on the screen comes a "pop up" which says:
Slicing Failed
Slicing failed with an unexpected error. Please consider reporting a bug to our issue tracker.

### Expected results

It should have sliced it normally and convert it to gcode

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![image](https://user-images.githubusercontent.com/107149801/208134994-c803d703-3080-461a-a7e7-1b607cf85eac.png)

**Comment by GregValiant** [comment]
Thanks for the report.
There was a problem with Lithophanes in Cura 5.1.  I suggest you update to 5.2.1 as the bug was reported to be fixed and there haven't been any reports about this behavior in 5.2.1.

I'll close this since the problem no longer exists.  If you upgrade and still have the problem this can be re-opened.
