### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Gabe212** [Ultimaker/Cura#14072]
### Application Version

5.0.1

### Platform

windows 10

### Printer

Ultimaker 2+

### Reproduction steps

Put the file in Cura 
tried to slice it 

### Actual results

error popped up

### Expected results

should slice the file

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

it was a folding baterang that is a STL so it wont let me put in in here but if you know what I can do please help.

**Comment by GregValiant** [comment]
Thanks for the report.
5.0.1 was a big change from the 4.x versions and had problems with both slicing and with some of the dialogs and controls.  I suggest that you upgrade to 5.2.1.  It is much better.
You can try a workaround in 5.0.1 - try moving the model around on the build plates and/or try rotating the model.  Sometimes that will fool the bug and the model will slice.  There is also a bug in 5.2.1 that has the same symptoms (good models that won't slice when in the middle of the build plate) and the workaround often fools the bug.
Since it is an older version and the update is already I'll mark this as a duplicate and close it.  The Cura team is working on the bug and hopefully it will be gone in 5.3.

**Comment by Gabe212** [comment]
I changed the cura version too but it still won't work. Do you know
anything else here is the error.

**Comment by Gabe212** [comment]
I changed it to 5.2.1

**Comment by Gabe212** [comment]
so when do you think 5.3 will be out

**Comment by GregValiant** [comment]
5.2.1 has been out for a while.  New versions are generally released every 3 months or so.  Maybe @MariMakes knows the schedule??
Did you check that model for errors in MS 3D Builder (Windows) or another repair utility?  If the slicer runs into problems within the model then slicing will often fail.

**Comment by Gabe212** [comment]
Thanks for the tip!
