### ISSUE TITLE
Skirt is intersecting my print

### ISSUE THREAD

**Issue by Username1414** [Ultimaker/Cura#14103]
### Application Version

5.2.1

### Platform

Linux Mint 20.3 (Cinnamon), Kernel 5.4.0-132-generic

### Printer

Anycubic Kobra

### Reproduction steps

1. Loaded two (!) models, where one had triangular shaped borders.
2. Selected "skirt" for "build plate adhesion type"
3. hit "slice"

==> Cura already showed my that the skirt will intersect my print

I printed it, and Cura was right. 

### Actual results

As cura showed in the preview - model was intersected by skirt.

### Expected results

Model would not be intersected by skirt and the preview would thus not show it.

### Checklist of files to include

- [ ] Log file
- [X] Project file
[cura skirt intersection bug.3mf.zip](https://github.com/Ultimaker/Cura/files/10273853/cura.skirt.intersection.bug.3mf.zip)

### Additional information & file uploads

The STLs have been created using Autodesk Tinkercad.

**Comment by Asterchades** [comment]
The Skirt (or any Bed Adhesion type) will only go around what is actually on the first layer of the print. The little "wings" you have sticking off to the side of the larger piece are angled upwards slightly, rotated around the bottom connection, causing them to only partially exist on layer 1 - and also not completely exist on the final layer, either.

You can already see on the Prepare screen that things might go South. There's a small but noticeable "shelf" visible on the top of the object, from the sides you can also make out the angle, and from underneath you can see the colour change from teal (touching against the bed) to red (overhang) as it goes further out.

If you need to maintain these angles on the side walls, try switching the `Slicing Tolerance` to `Inclusive`. Alternatively you could lower the object slightly below the print bed, but if dimensional accuracy is an issue you would then need to re-scale it on the Z axis to restore the full height. Otherwise you'll want to go back into TinkerCAD and correct the errant angles, making the whole object flat again.
