### ISSUE TITLE
(5.2.1) STL slices correctly when imported, but not when mirrored.  Tree supports

### ISSUE THREAD

**Issue by Austenite2** [Ultimaker/Cura#14138]
### Application Version

5.2.1

### Platform

Windows 10

### Printer

Voron2 300

### Reproduction steps

Created an STL, from Fusion 360
Import into Cura
Sliced with tree supports, works fine
Mirrored STL, try to slice again/
Error message: Slicing failed with an unexpected error.  Please consider filing a bug report

### Actual results

Error message: Slicing failed with an unexpected error.  Please consider filing a bug report

### Expected results

Should have sliced and produced gcode.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[V300_Hat stand_mirror.zip](https://github.com/Ultimaker/Cura/files/10305013/V300_Hat.stand_mirror.zip)

**Comment by Austenite2** [comment]
Object in attached project file was mirrored in Cura using the red horizontal arrows in the interface.  When mirrored using the green vertical arrows, slicing completes correctly.

**Comment by MariMakes** [comment]
Hey @Austenite2,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report 👍

I think I can help you! Something seems wrong with your normals after mirroring. 
You can fix that with the Meshtools plugin
You can get it here: https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/MeshTools

![image](https://user-images.githubusercontent.com/40423138/210822415-da1b1c48-6b36-4a1b-a105-abe12eb9030a.png)

After the fix I was able to slice your file succesfully.
![image](https://user-images.githubusercontent.com/40423138/210825120-742b357a-2465-4b93-a6c9-f651efa20e60.png)


Since you are slicing with tree support have you considered testing the new Tree Support Alpha and sharing any feedback with us? You can download a version here: https://github.com/Ultimaker/Cura/releases

To me, it doesn't seem like a bug in Ultimaker Cura, since we have a solution in place. 
Would you still like to keep this issue open or do you agree that we can close it?
