### ISSUE TITLE
Temperature not transferring to GCode properly.

### ISSUE THREAD

**Issue by trthskr4** [Ultimaker/Cura#14149]
### Application Version

5.2.1

### Platform

Windows 10

### Printer

Creality Ender 3 Pro

### Reproduction steps

Slice profile in Cura 5.2.1
Copy GCode to SD card
Insert SD card into printer and run GCode.
Temperature setting in slicer set to 245 but only heats up to 175 when printer heating up.
Temperature setting at 240 in slicer, only heats up to 170 in printer.

### Actual results

Must manually increase temps on printer.

### Expected results

Temperature in slicer should have been same as what transferred to printer

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

Would actually upload the sliced profile but no way to do so.

**Comment by Asterchades** [comment]
This was a deliberate change submitted and approved for the Ender-3 Pro profile over a year ago now. It will first heat to the material's Standby Temperature while also heating the bed. Afterwards it will heat to the Initial Layer Temperature without intervention - changing it yourself is superfluous.

If you don't want it to heat to the lower temperature at all you have two choices: In the start GCode you could change the part which reads `{material_standby_temperature}` to instead read `{material_print_temperature_layer_0}` to make it heat up to full temperature along with the bed, or remove/remark that same line to make it heat the bed and tool sequentially rather than concurrently.
