### ISSUE TITLE
Very strange lines that makes printing impossible

### ISSUE THREAD

**Issue by E3P2** [Ultimaker/Cura#14152]
### Application Version

5.0.0

### Platform

Windows 11

### Printer

ender 3 pro

### Reproduction steps

![image](https://user-images.githubusercontent.com/94670441/209847090-c439e568-1a97-4434-9af2-aa2bd5204e4f.png)
Just with normal config slicing the model

### Actual results

for some reasones it`s corrapting gcode how you could see it on preview

### Expected results

normal gcode without calulation with tons of plastic

### Checklist of files to include

- [x] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/10315420/cura.log)

**Comment by GregValiant** [comment]
Thanks for the report.
That behavior has been noted before in 5.0.0.  I have not seen a report of that in 5.1 or 5.2 so hopefully it was fixed.  Updating to 5.2.1 is the best bet.

I'll mark this as a duplicate.  Since the problem seems to have been fixed and since 5.0.0 was 4 versions ago, I'll go ahead and close this.  I hope you understand.
