### ISSUE TITLE
Floating support lines when Support Horizontal Expansion 3.0 mm

### ISSUE THREAD

**Issue by jasonrohrer** [Ultimaker/Cura#14184]
### Application Version

5.2.1

### Platform

Ubuntu 20.04.5 LTS

### Printer

Ultimaker S3

### Reproduction steps

1. PLA model with PVA supports.
2. Supports printed by Extruder 2 (PVA)
3. Default support pattern (Zig Zag)
4. Change default Support Horizontal Expansion from 1.0 mm to 3.0 mm
5. NOTE that default WAS 3.0 mm in Cura 4.13.1... curious that it was reduced to 1.0 mm in Cura 5.2.1
6. Slice.

### Actual results

The supports generated are much messier looking than the same supports in 4.13.1, and they contain little "floating bits" that aren't printable. See screen shot.

4.13.1 produces much cleaner, more reasonable-looking supports for the same model than 5.2.1

### Expected results

Supports should be at least as solid looking as what is generated by 4.13.1

There should be no floating, unprintable bits in the supports.
[curaLog.zip](https://github.com/Ultimaker/Cura/files/10329982/curaLog.zip)
![Screenshot from 2023-01-01 23-16-40](https://user-images.githubusercontent.com/12563681/210194959-07959185-44d0-4ba4-a5ac-81e84ef77d6b.png)
[floatingSupportLines.zip](https://github.com/Ultimaker/Cura/files/10329986/floatingSupportLines.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

Uploaded into Expected Results above.

**Comment by MariMakes** [comment]
Hey @jasonrohrer,

Thanks for your report 👍

We had a known issue where support was generated on top of the support interface. 
That has been resolved https://github.com/Ultimaker/CuraEngine/pull/1778 and can be expected in the next stable build. 

It looks like that it resolves your issue.
Left is a build with the fix, right is Cura 5.1
![image](https://user-images.githubusercontent.com/40423138/210789600-b902ddd8-3e86-4286-b7d7-99a4bb8a44bf.png)

To me, it doesn't seem like a bug in Ultimaker Cura, since we have a solution in place. 
Would you still like to keep this issue open or do you agree that we can close it?
