### ISSUE TITLE
Print file unable to be sliced when enlarged by a certain amount.

### ISSUE THREAD

**Issue by DragonClaw95** [Ultimaker/Cura#14207]
### Application Version

5.2.0

### Platform

Windows 11

### Printer

Anycubic Vyper

### Reproduction steps

1. Opened up Cura.

2. Brought in the poro-1 stl file.
<img width="1046" alt="image" src="https://user-images.githubusercontent.com/121980952/210653840-d984377f-f619-4880-b056-4f93256bf08b.png">

3. Enlarged object as shown.
<img width="1047" alt="image" src="https://user-images.githubusercontent.com/121980952/210653969-ddd1a15f-98b7-43c4-bd40-992d7486fc6c.png">

4. Tried to slice said object to print.

### Actual results

I got an error message stating:
<img width="292" alt="image" src="https://user-images.githubusercontent.com/121980952/210654178-91756fa6-8600-4de4-89e2-8da7918bec44.png">

### Expected results

The print should be sliced when the "Slice" button is clicked upon, allowing it to then be exported to the 3d printer.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[AV_poro-1.zip](https://github.com/Ultimaker/Cura/files/10347689/AV_poro-1.zip)

**Comment by MariMakes** [comment]
Hey @DragonClaw95,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report 👍

I can recreate your crash. 
![image](https://user-images.githubusercontent.com/40423138/210814203-da5d0c45-db8f-4f2a-bd20-cbe28dd417ae.png)

But it seems that this mesh seems faulty.
Have you tried doing a quick mesh fix with the Meshtools Plugin? 
You can get it here: https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/MeshTools
If that doesn't fix it you can try a more elaborate mesh fixer like https://myminifactory.github.io/Fast-Quadric-Mesh-Simplification/.

To me, it doesn't seem like a bug in Ultimaker Cura, since the mesh is faulty and Cura is not built to alter meshes in this way, that's what CAD software is for. 
Would you still like to keep this issue open or do you agree that we can close it?
