### ISSUE TITLE
The configuration GCode don't works

### ISSUE THREAD

**Issue by Darius124365** [Ultimaker/Cura#14212]
### Application Version

5.2.1

### Platform

Windows 11

### Printer

Creality Ender-3 / Ender-3 v2

### Reproduction steps

I cant do any thing

### Actual results

Don't work

### Expected results

Nothing

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![imagen](https://user-images.githubusercontent.com/115630166/210762009-4c7f3df0-b059-4e80-9016-329356b21597.png)

**Comment by Darius124365** [comment]
Thanks :)

**Comment by GregValiant** [comment]
Well, I'm not sure what doesn't work.
The warning I see in the screen shot looks like you loaded a Gcode file in Cura.  Cura can "display" a gcode file but cannot alter gcode files.  You need to load a model file (STL, 3mf, OBJ, etc.) in order to slice it.  Gcode is a text file and a list of commands for the printer.  There is no model information in a Gcode file.
If you want to alter a gcode you would need to do it in a text editor.

If you could spend a little time explaining what you did, and what you expected to happen, that would help.
