### ISSUE TITLE
cura adding a top layer when it shouldn't!

### ISSUE THREAD

**Issue by Salteedogg** [Ultimaker/Cura#14226]
### Application Version

5.3.0

### Platform

windows 10

### Printer

anycubic kobra max

### Reproduction steps

I created a drawer in fusion 360 and transferred it to cura 5.3.0

### Actual results

Once I slice this drawer it puts a top layer on it which makes it useless. I have tried on all other cura platforms with same results.

### Expected results

I expect it to print my drawer as it looks like, once sliced it has a top layer rendering it useless!
![Screenshot (1)](https://user-images.githubusercontent.com/98138273/211079673-2da8c243-e58f-4f3f-837b-53991777a984.png)
![Screenshot (2)](https://user-images.githubusercontent.com/98138273/211079686-4ecb77e2-c039-470b-9a0e-6e596924f7fd.png)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Please fix!

**Comment by GregValiant** [comment]
Thanks for the report.
Without the model we can't tell what might be going on.  That's why you were asked to provide a project file.

Just guessing I'd say you either need to turn off "Remove all Holes" or check the model for errors.  If I had the project file I wouldn't need to guess.
Since I can't confirm a bug I've removed the bug label as my guess is that this is a setting issue.
