### ISSUE TITLE
Cannot slice a model

### ISSUE THREAD

**Issue by Wintaru** [Ultimaker/Cura#14238]
### Application Version

5.2.1

### Platform

Windows 11

### Printer

Custom

### Reproduction steps

Try to slice the model attached.

### Actual results

Says Slicing failed, please consider filing a bug.

### Expected results

The model is sliced.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/10367145/cura.log)
[Project File](https://1drv.ms/u/s!Aosntn-xMzObipc1ypq_7i76NwEN3w?e=Rj7cMA)

**Comment by GregValiant** [comment]
Thanks for the report.
That model has 71 open seams so it isn't watertight.  Because of that it may not print correctly.
I moved the model and rotated it in Cura and managed to get it to slice.  There are enough errors in the model that I don't know if it would turn out right or not.
![image](https://user-images.githubusercontent.com/64202104/211174861-f2991e2d-74f8-419f-8c7d-f12870377d9a.png)

I'll mark this as a duplicate and close it as the Cura team has many reports about this bug.  The "Move or Rotate" workaround often fools the bug.  Let us know if it works for you.
