### ISSUE TITLE
Cura 5.3.0 Alpha "Slicing failed" Bug

### ISSUE THREAD

**Issue by dcresistance** [Ultimaker/Cura#14230]
### Application Version

5.3.0

### Platform

Windows 10 Pro 19044.2364 , RTX 2070

### Printer

Ender 3 V2

### Reproduction steps

I was trying to print a custom print on 5.3.0 in order to use the new tree supports
[CE3E3V2_vinyl holder.zip](https://github.com/Ultimaker/Cura/files/10365314/CE3E3V2_vinyl.holder.zip)

### Actual results

Got the error "Slicing failed with an unexpected error."
![Screenshot 2023-01-06 211327](https://user-images.githubusercontent.com/11627528/211126984-9aecd2a7-1c5d-41ba-b029-d96e4e952f36.jpg)

### Expected results

The slicing should've been successful

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/10365321/cura.log)

**Comment by GregValiant** [comment]
Thanks for the report.
I can see that a couple of vertical surfaces are shown red in the Prepare Screen.  That means that the surfaces are flipped inside-out.  It's possible that is what confused Cura.
There is a bug that might be involved.  The workaround for the bug is to move and/or rotate the model in Cura.  I think that your model needs repair though.  Let us know if you get it to slice.
