### ISSUE TITLE
Slicing Failed

### ISSUE THREAD

**Issue by MateMar04** [Ultimaker/Cura#14233]
### Application Version

5.3.0

### Platform

Windows 11

### Printer

Hellbot Magna 2 230

### Reproduction steps

1. Downloaded a .stl file and opened it with Ultimaker Cura 5.3.0
2. Tried to slice it but it won't

### Actual results

Keeps trying to slice bur without good results

### Expected results

Slice

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

Screenshot in prepare mode: <img width="1280" alt="image" src="https://user-images.githubusercontent.com/47880871/211157641-47fd7b87-f2c4-4182-90a7-eb711e1c8a7e.png">
Screenshot in preview mode: <img width="1280" alt="image" src="https://user-images.githubusercontent.com/47880871/211157674-3a706270-df17-4872-a60a-1dfade291183.png">
[HM2230_Dowel.zip](https://github.com/Ultimaker/Cura/files/10366571/HM2230_Dowel.zip)

**Comment by MateMar04** [comment]
If I lift the object, so it can rest on a support, it slices.
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/47880871/211158019-39b70751-1489-427d-b3a8-018f80c905d2.png">

**Comment by GregValiant** [comment]
Thanks for the report.
There is a persistent bug that has been reported numerous times that can keep a good model from slicing when it is in certain positions on the build plate.  Your project file sliced for me on the first try.
I had never thought of moving a model up, but moving it in the X Y or rotating the model will often fool the bug.
This bug is being worked on and the Cura team has numerous examples of this problem so I'll mark this as a duplicate and close this report.  I hope you understand.

**Comment by MateMar04** [comment]
I "solved" it duplicating the model and then deleting the original model

**Comment by GregValiant** [comment]
I'll try that on the next one of these reports that come through (there have been a lot).
