### ISSUE TITLE
Portable Cura

### ISSUE THREAD

**Issue by jignac05** [Ultimaker/Cura#14255]
### Is your feature request related to a problem?

I would like to use Ultimker Cura without installation on school computers (Windows). I can't install anything on computers and we have a 3d priter in school that i would want to slice for.

### Describe the solution you'd like

Could you create portable version for Windows? (that would work for example from flashdisk)

### Describe alternatives you've considered

Maybe if there already is a version, could somebody send me a link?

### Affected users and/or printers

Users that work on computers that can't install cura.

### Additional information & file uploads

Thank you

**Comment by Frickeldave** [comment]
Workaround: Download the executable and extract it with a tool like 7-Zip (when tool is not available, do that on an dedicated system). In the extracted folder you will find the ultimaker-cura.exe which you can start. It is not REALLY portable, because there is no option to move the %appdata%\cura and %localappdata%\cura folders to the application folder, so the request itself is valid, of you want to have a real portable application like for use in portableapps.com plattform. But this will solve you problem to use cura on a PC without administrative permissions.

**Comment by jignac05** [comment]
Thank you
