### ISSUE TITLE
Support overhang angle

### ISSUE THREAD

**Issue by LittleBeast11** [Ultimaker/Cura#14253]
### Application Version

5.2.1

### Platform

Windows 10

### Printer

Creality Ender 3

### Reproduction steps

Loaded the STL file now the areas that generally show red (which require supports) is showing on the top of the model
![image](https://user-images.githubusercontent.com/122301821/211365941-4b14eaee-c0b3-4f60-9708-85febdf31268.png)

### Actual results

The prepare screen shows the red faces on the top of the model and not where the supports are required

### Expected results

The red should be on the other side f the model as it should show which areas require supports

![image](https://user-images.githubusercontent.com/122301821/211366249-02283e66-a902-47ec-8d4a-8142a002e6e5.png)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

I have tried multiple files and they all do the same

**Comment by GregValiant** [comment]
When surfaces show red on the top of the model - that indicates flipped surfaces in the model itself.  Those need to be repaired before you can slice the model.  MS 3D Builder should be able to make the repairs.
When Cura encounters a flipped normal then the slicer can no longer figure out the inside from the outside and the slice will fail or just come out wrong.
If you would load the "Mesh Fixes" plugin from the Marketplace it has some tools that you might be able to fix your model with.
So this isn't a bug but rather it is expected behavior to inform the user that there is a problem with the model.
I'll remove the bug label but I'll leave this open so you can respond here.

**Comment by LittleBeast11** [comment]
Hi Greg,

Many thanks for the prompt response.

Will give it a try.

Warm regards

*Vincent Kruger*
*084 811 7117*

**Comment by GregValiant** [comment]
I think if you view that model in "X-Ray" view then the red problem areas would be highlighted better.
I'm going to close this as it does appear to be a problem with the model.
