### ISSUE TITLE
extruder unwanted offset in y direction after updating to 5.2.1

### ISSUE THREAD

**Issue by Sjawel123** [Ultimaker/Cura#14309]
### Application Version

5.2.1.

### Platform

windows 10

### Printer

BIBO2

### Reproduction steps

wanted to print 2 lines as level test with skirt 
slicer looks good
but when printing: 
the 2e extruder sets an offset of 2 mm in the Y direction on the skirt

Problem is only after updating to this newer version 

### Actual results

new version of cure puts an offset in the y direction where it should not have any offset of about 2 mm
in the slicer it looks good but the printer prints an ofset in Y of 2mm.

ps the box is checked (apply offset to gcode) 
ps the 2e extruder does not even need an offset in the y direction!!! only in the x direction which was good in the previous versions. i should not have updated :(

second bug:
and i can select a part to change the extruder, but after slicing it does not show the other color/filament for the 2e extruder. 
where cure 4.13.1 had no issues

### Expected results

fix extruder offset for bibo2 printer

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

You dont support your own project files for uploading? at least i cant here?
 
![lijn2](https://user-images.githubusercontent.com/122851876/212813877-91ecf85d-55a1-4765-8aec-1d466cdef9db.PNG)

ps one line is selected for extruder 1 the other for extruder 2

![lijn](https://user-images.githubusercontent.com/122851876/212813706-a51af49f-4fe7-4c7d-ad76-1a37ff814b78.PNG)

**Comment by GregValiant** [comment]
Thanks for the report.
It is a Github rule that non-supported file types must be Zipped in order to post them.  The instructions are on the initial page when you fill in a bug report.

The "bibo2_dual.def.json" file does not show an offset for the extruder.  Likewise, the Bibo extruder files do not show an offset.
In Cura, go to Manage Printers/Machine Settings and then select each extruder.  See if there are "X" and or "Y" offsets listed.  It sounds like they should both be "0" (but I don't know your printer).  Let us know if you find the problem.

When I install a Bibo Dual in Cura there is no offset and so I can't duplicate this.
