### ISSUE TITLE
(5.2.1) Slicing fails with unexpected error for 100% concentric infill

### ISSUE THREAD

**Issue by AgeevAlex89** [Ultimaker/Cura#14303]
### Application Version

5.2.1

### Platform

Windows 10, Ryzen 5600G, 32Gb RAM, nvidia 2070S

### Printer

Anet A8 (manually added)

### Reproduction steps

Tried to slice a model I exported from CAD software. This is a somewhat loaded part (handle for armwrestling training device), so my aim was to obtain a solid model with 100% infill. I set wall count to 0, infill to 100% concentric.
Slicing failed.
I deleted the log file and repeated slicing attempts to hopefully obtain some useful info for debug, taking screenshots after each attempt with system time visible. Please see the attached files for screenshots and Cura log file. 3MF project file and my model STL file are in archive I uploaded to WeTransfer: https://we.tl/t-DvvlHIAaIu
The Cura log contains messages that were generated while I made 5 attempts to slice with the following wall line count settings:
0 -- slicing failed
1 -- slicing failed
2 -- slicing failed
3 -- slicing failed
4 -- ran for 10 minutes as single thread, I clicked Cancel
5 -- finished successfully

Also, selecting another type of infill (not concentric) lets slicing finish without issues.

### Actual results

In several attempts with wall line counts from 0 to 4, slicing either continued infinitely or I got a message window inviting to report a bug.
Slicing was completed successfully only with wall line count 5.

### Expected results

I expected the slicing to complete successfully with any wall count.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/10421221/cura.log)
![Wall-0](https://user-images.githubusercontent.com/122739889/212567282-fb6763d3-88df-43e9-94a6-e49463c0f334.png)
![Wall-1](https://user-images.githubusercontent.com/122739889/212567284-9a012d98-e32c-4e14-9ec9-f0119b94132d.png)
![Wall-2](https://user-images.githubusercontent.com/122739889/212567285-81dee6e5-0833-4f7f-a432-bacb8d4e9a19.png)
![Wall-3](https://user-images.githubusercontent.com/122739889/212567286-6a792d16-b5a3-4034-aa49-6c7f85dc0fdd.png)
![Wall-4](https://user-images.githubusercontent.com/122739889/212567287-4e19e894-33ad-4157-922f-fbdaf86cc942.png)
![Wall-5](https://user-images.githubusercontent.com/122739889/212567289-5a3a3ab9-991e-4576-bdca-a94f3d8e2c3a.png)

**Comment by MariMakes** [comment]
Hey @AgeevAlex89,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your elaborate report 👍

Wow you changed a lot of settings from the default 😅 
I think your error might be caused by a certain combination of them. 
I believe it's the combination of 100% infill, having no walls but various wall setting changes. 

If 100% infill is important for you, I would go for 999 walls in this model. 
It slices properly, and you still have your wall-specific setting changes.  
![image](https://user-images.githubusercontent.com/40423138/213679379-476d1772-c7ac-4b09-a586-11d6f375327e.png)

I'll bring it up to the team to see what they can do to improve it. But I expect that if it's not a quick fix that it will not get a high priority to implement. Fingers crossed 🤞
