### ISSUE TITLE
Part Cooling Fan control issue

### ISSUE THREAD

**Issue by Marshalldog** [Ultimaker/Cura#14306]
### Application Version

5.2.1

### Platform

Windows 11

### Printer

CR-10 with duet 3 mini 5+

### Reproduction steps

![Screenshot 2023-01-16 172906](https://user-images.githubusercontent.com/99470771/212616749-514f1fc2-a9a4-48af-b866-a973da6350e5.png)
Note: the printer is running reprap, Firmware: RepRapFirmware for Duet 3 Mini 5+ 3.4.5, Duet Web Control 3.4.5
the fan settings in the screenshot were used

Duet fan config:
```
; Fans
M950 F0 C"!out3+out3.tach" Q500
M106 P0 C"Part Fan" S1 H-1
M563 P0 D0 H1 F0                                      ; define tool 0

```

### Actual results

The part cooling fan remained OFF during the entire print

### Expected results

The part cooling fan remained ON during the entire print

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

it seems that fan control isn't working for some RepRap motherboards, maybe.

**Comment by GregValiant** [comment]
Thanks for the report.
On a single extruder printer your "Extruder 1" - "Cooling Fan Number" would typically be "0".
The fan line M106 should have an "S" parameter indicating the speed (usually 0 - 255 PWM).  The "P" parameter default is "0" so it isn't added for a single extruder printer.  To set the fan to half speed you should see this in the gcode:
M106 S128
A dual-extruder printer with separate fans for each extruder might be:
M106 S128 P0 or M106 S128 P1
depending on which extruder was active.

From the RepRap Wiki for "M106":
_"Mandatory parameter 'S' declares the PWM value (0-255). M106 S0 turns the fan off. In some implementations like RepRapFirmware the PWM value may alternatively be specified as a real fraction: M106 S0.7."_

In Cura - The setting to use the 0 to 1 scale instead of 0 - 255 is located in the "Printer Settings" section which must be loaded from the MarketPlace.

Within your gcode file - what line did Cura enter for the fan?
