### ISSUE TITLE
Tab+Antiwarping 1.0.5

### ISSUE THREAD

**Issue by jwparks53** [Ultimaker/Cura#14316]
### Application Version

5.1.0

### Platform

Window 10

### Printer

Ender 3 V2

### Reproduction steps

Opened 3mf CE3PRO_lid_Butterflies into Cura 5.1.0.  Click on the icon for Tab+Antiwarping.  Size is set for 20 mm, X/Y 0.15 mm, layers 1, Set on adhesion area is checked.

### Actual results

When Automatic Addition is clicked on, "tabs" are displayed on screen that are not on the build plate.  Instead of being 20 mm in diameter, they are 508 mm in diameter.
![Tab Antiwarping](https://user-images.githubusercontent.com/105871050/213020354-12a1471d-eaf4-4718-8cc2-0bfb93137bda.png)

### Expected results

The tabs should have been placed on the adhesion area so that the tabs could be placed a desired.  This has only happened with this file type, this file is for a cover to a storage box.  When "Tabs' is attempted for the storage box, the same results occur.  
![Tab Antiwarping-Good](https://user-images.githubusercontent.com/105871050/213021265-9ba4dc6e-9c49-4502-aae4-7e7a8bae7195.png)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

I have tried to use the "TabAntiwarping" plugin, but still have the same results.  This problem only occurs with these particular files.  I am unable to attach the 3mf files.  Attached is a png  of the cover that I am trying to use the "Tabs" on.  Using a "brim" is not an option because the underside of the cover requires supports and using a "brim" adds a layer under the supports, even tho I check "outside only", and supports cannot be removed.  Hopefully, using tabs would be able to replace the "brim".
![Lid_Butterflies ‎- 3D Builder](https://user-images.githubusercontent.com/105871050/213024270-0108da45-5368-4ad4-af43-09d3b70c05c4.png)

**Comment by Asterchades** [comment]
Neither TabPlus nor TabAntiWarping are part of the base Cura feature set - these are both plugins created by 5axes. As such you'll need to report the issue to them instead, via the appropriate GitHub repository: https://github.com/5axes/TabPlus and/or https://github.com/5axes/TabAntiWarping

As this is an issue with a plugin, rather than the base Cura, I'll be closing this. Should you feel this is incorrect, you will need to upload a demonstration file showing the issue - you can either compress the 3MF to ZIP format or simply change the extension.
