### ISSUE TITLE
Slicing Failed

### ISSUE THREAD

**Issue by Jrev103096** [Ultimaker/Cura#14429]
### Application Version

5.2.2

### Platform

Windows 11

### Printer

Voxelab Aquila C2

### Reproduction steps

1. Scaled STL up in size
2. Sliced file
3. slicing failed.

### Actual results

File slicing fails after I scale a small file up to 550% and works fine at 549% and below. 

### Expected results

The file should have been sliced properly
![Before](https://user-images.githubusercontent.com/123967526/215676669-530de32e-48ce-4c66-bee2-de3c723dda2d.png)

![After](https://user-images.githubusercontent.com/123967526/215677823-73d7c7b4-6419-4167-83e2-120de24cff9b.png)
[CFFFP_DAREDEVIL SKULL.zip](https://github.com/Ultimaker/Cura/files/10543256/CFFFP_DAREDEVIL.SKULL.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

The file is still well within the printer's limits.

**Comment by MariMakes** [comment]
Hey @Jrev103096,

Welcome to the Ultimaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

I got this faulty mesh error when I opened your file.
![image](https://user-images.githubusercontent.com/40423138/218114370-6f647af7-2e79-47a3-b9ea-4a5738efefc1.png)

This mesh seems faulty
Have you tried doing a quick mesh fix with the Meshtools Plugin? 
You can get it here: https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/MeshTools
If that doesn't fix it you can try a more elaborate mesh fixer like https://myminifactory.github.io/Fast-Quadric-Mesh-Simplification/.
Or you can use the "Make Solid" feature in AutoDesk MeshMixer. https://meshmixer.com/download.html

To me, it doesn't seem like a bug in Ultimaker Cura, since the mesh is faulty and Cura is not built to alter meshes in this way, that's what CAD software is for. 
Would you still like to keep this issue open or do you agree that we can close it?
