### ISSUE TITLE
Lulzbot Taz pro Z hop speed issue

### ISSUE THREAD

**Issue by Manbearpig1497** [Ultimaker/Cura#14459]
### Application Version

5.2.1

### Platform

windows 10

### Printer

Lulzbot (Fargo additive manufacturing 3d) Taz Pro

### Reproduction steps

I added the printer from the non network drop down menu from an already installed Cura 
loading in a file to slice.

 

### Actual results

tried to slice said file and received "Unable to slice with the current settings. The following settings have errors : Z hop speed."
made sure i had the latest firmware update and sill no
tried to change z hop speed and no matter what combination between the two extruders it would still not slice. Tried other file types and still no result also tried to go back to 4.2.1 and no good either.

### Expected results

the STL file should slice it works fine with my CR-10 Smart it is a known good slice. 

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[LTAZPRODE_Bobblehand_Rock_On_-_Large.zip.zip](https://github.com/Ultimaker/Cura/files/10574570/LTAZPRODE_Bobblehand_Rock_On_-_Large.zip.zip)
[cura.log.zip](https://github.com/Ultimaker/Cura/files/10574609/cura.log.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
You cannot enter a "Z-Hop Speed" that is above your "Maximum Speed Z".
Go to the Cura Marketplace and load the "Printer Settings" plugin.
Quit Cura and then restart.
Enable the "Custom" settings.
At the bottom of the settings list will be Printer Settings and within that will be "Maximum Speed Z".  Set it to your preferred Z speed.  That will adjust the "Maximum" you can enter into the "Speed /  Z-Hop Speed" box and should allow you to slice.
Let us know if that works for you.
I think this is a settings issue rather than a bug.  "Maximum Speed Z" should come from the definition file you used.
