### ISSUE TITLE
Crash on slicing

### ISSUE THREAD

**Issue by frontrunnersoftware** [Ultimaker/Cura#14450]
### Application Version

5.2.1

### Platform

Windows 11

### Printer

Custom

### Reproduction steps

Press the slice button

### Actual results

Error message:
Slicing failed with an unexpected error. 

### Expected results

Slicing completes without error

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads
Issue relates to Use Adaptive Layers setting as there is no error when this setting is disabled. Error occurs even using the default values for this setting. 

[Bug report.zip](https://github.com/Ultimaker/Cura/files/10559991/Bug.report.zip)

**Comment by GregValiant** [comment]
Thanks for the report and the files.
There is a persistent bug in 5.1 and 5.2 that can keep good models from slicing when they are centered on the Cura build plate.
Right click and choose "Select all Models" and try moving the model and blockers around on the Cura build plate (sometimes rotating the model works).  I moved your assemblage to the left front and it sliced there.
The bug doesn't have anything to do with Adaptive Layers other than at certain layer heights the slicing was leaving miniscule slivers of model that confused Cura.  This has been addressed and hopefully it will be fixed in 5.3.
I'll mark this as a duplicate and a slicing error and go ahead and close this.  The Cura team has had lots of examples of this behavior.
Thanks again for the report.  More information is always a good thing.
![image](https://user-images.githubusercontent.com/64202104/216446347-27527a40-757d-4e67-87d0-0d3d33b33360.png)
