### ISSUE TITLE
Cura 5.3.0. refuses to slice

### ISSUE THREAD

**Issue by billiest** [Ultimaker/Cura#14465]
### Application Version

5.3.0.

### Platform

WIndows 10

### Printer

Anycubic Kobra Max

### Reproduction steps

loaded file, scaled file, slice button, slicing progress followed by error message

### Actual results

error message, send bug report

### Expected results

slicing completion
Slice button showsup as if slicing was never done.

[Final jet Robot.zip](https://github.com/Ultimaker/Cura/files/10580822/Final.jet.Robot.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

none

**Comment by GregValiant** [comment]
Thanks for the report and the file.
That model has serious issues.  All those red and magenta balls indicate errors.  particularly look at the legs (landing gear?).
![image](https://user-images.githubusercontent.com/64202104/216675791-b358ca47-e262-4d68-855d-e4179248a497.png)

Neither Mesh Mixer nor MS 3D Builder were able to repair the file.

I'm going to remove the bug label from this and go ahead and close it.  The model is full of errors and we can't tell if this is a slicing bug or if it won't slice because of all the problems in the model.  I hope you understand.
