### ISSUE TITLE
Slicong failed with an unexpected error

### ISSUE THREAD

**Issue by Nerbry72** [Ultimaker/Cura#14466]
### Application Version

5.2.2

### Platform

Windows 11

### Printer

Artillery Sidewinder X1

### Reproduction steps

- Imported my model
- scaled it up to 181%
- edited follwoing settings:

1.  Layer Height
2.  Infill
3.  enabled Infill travel optimisation
4.  enabled Z hop when Retracted (which ofc dosent work with 3. )

then i tried  to slice my model what led to an unexpected error

i disabled Z hop, then the travel optimisation appeared again i disabled it and reenabled the Z hop.
still the same error, even after restarting the application and the computer.

### Actual results

Slicing failed with an unexpected error

### Expected results

Sucsessfull slicing

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/10580964/cura.log)
[Project File](https://we.tl/t-mFDTYIq2tZ)

**Comment by GregValiant** [comment]
Thanks for the report and the files.
Here is a view of the model in Mesh Mixer.  The errors in the model are indicated by the red and magenta balls.  The problem appears to be the perimeter of the base.
![image](https://user-images.githubusercontent.com/64202104/216672093-b0852221-9686-44bd-accb-2c7e985d3342.png)

After repairing the model I still had to move it and rotate it on the build plate to get it to slice.

So I think there are two things going on here.  The model needs repair (Mesh Mixer, MS 3D Builder, etc.) and you've run into the "won't slice when centered" bug.  After repairing the model try moving it and rotating it and you may find a position where it will slice.

I'm going to mark this as a duplicate and a slicing error and I'm going to close the report as the Cura team has a lot of examples of this behavior and it should be fixed in 5.3.  Thanks again for reporting.

![image](https://user-images.githubusercontent.com/64202104/216673923-54e172c1-4a3a-441b-8efd-e9f40c1d9df6.png)
