### ISSUE TITLE
slicing failed

### ISSUE THREAD

**Issue by gelalalaholic** [Ultimaker/Cura#14505]
### Application Version

5.2.2

### Platform

windows 10

### Printer

Creality Ender 3/ Ender 3 v2

### Reproduction steps

1. imported file
2. changed print settings to a custom saved profile
3. resized to 80%
4. slice

### Actual results

![Screenshot 2023-02-07 103016 - slice failed](https://user-images.githubusercontent.com/124717862/217353989-ac503e64-56a5-4929-a35f-b939862a8c6d.png)

### Expected results

I should have been able to slice, preview, and save the GCode.
This is a part of a bigger print project. The other parts successfully sliced and printed, this is the only model that fails to slice.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[Project file.zip](https://github.com/Ultimaker/Cura/files/10679045/Project.file.zip)

**Comment by GregValiant** [comment]
Thanks for the report and the file.
There is a bug that can keep good models from slicing when they are at the mid-point of the Cura build plate.  Try moving the model and maybe rotating it.  Your file sliced on the first try for me and the model shows no errors so you should be able to find a place and orientation where it will slice.
I'll mark this as a duplicate and a slicing error.  This bug has been worked on and the fix is in place for 5.3 stable so I'll go ahead and close this.  I hope you understand.
![image](https://user-images.githubusercontent.com/64202104/217431319-2928bffb-0dcd-4da2-8362-d882976b93f9.png)
