### ISSUE TITLE
¨support blocker (E)¨ does not work!

### ISSUE THREAD

**Issue by ghost** [Ultimaker/Cura#14572]
### Application Version

5.2.1

### Platform

WIndows 10

### Printer

Creality Ender-3 / Ender -3 v2

### Reproduction steps

1. I select the object
2. I click in ¨support blocker (E)¨ 
3. I click on the object again and then it appears

### Actual results

Doesn't work, supports don't disappear!

### Expected results

The supports should disappear where you placed the  ¨support blocker (E)¨ .

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![image](https://user-images.githubusercontent.com/125494738/219114302-e1477831-810e-483e-ad42-594fb2d10887.png)
![image](https://user-images.githubusercontent.com/125494738/219114415-241bdf63-6f8c-490c-94a7-3282d0d13ff8.png)

**Comment by GregValiant** [comment]
Thanks for the report.
Without a project file it isn't really possible to see what is going on.  I've had no trouble with the support blockers and there have been no other reports.
Cura colors the underside of overhangs red.  The support blocker must touch that red area in order to block the support buildup.
Here I have a support blocker that touches a portion of the red overhanging area so no supports grow there.  The the other portion is not touched and so it is supported.  A support blocker does not have to touch the build plate, just the red portion of an overhang.
![image](https://user-images.githubusercontent.com/64202104/219150264-298d3a23-bd37-4d47-aa30-162db74ed7e4.png)

If you load a model, set Cura up, and use the "File | Save Project" command you can zip the 3mf file and post the zip folder here.
I'm not seeing a bug at this point but there may be a problem.  A project file will tell.
