### ISSUE TITLE
Minimum layer time below 2.5s has no effect

### ISSUE THREAD

**Issue by anoother** [Ultimaker/Cura#14583]
### Application Version

5.2.1

### Platform

Windows 11

### Printer

Custom

### Reproduction steps

1. Set print speeds such that layers should complete in under 2.5s
2. Verify that, on other layers, higher print speeds are easily reached
3. Set minimum layer time to 5s, 2.5s, 1s, 0s, slicing each time, to test behaviour
4. Observe that there seems to be a hard-coded lower bound for minimum layer time @ 2.5s, with values below this yielding no improvement.

### Actual results

- At minimum layer time >= 2.5s, print speed increases inversely-proportional to minimum layer time.
- **At minimum layer time < 2.5s**, print speed will not increase any further and layers will print at 2.5s regardless.

### Expected results

- Print speed increases inversely-proportional to minimum layer time, with the only upper-bound being configured speed/accelleration settings

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[CFFFP_CS_5.zip](https://github.com/Ultimaker/Cura/files/10758126/CFFFP_CS_5.zip)
![Screenshot_20230216_161749](https://user-images.githubusercontent.com/205690/219425812-37ec85be-4641-4723-a0fa-21a0eeb7ee97.png)
![Screenshot_20230216_161806](https://user-images.githubusercontent.com/205690/219425823-07a642ec-06c2-48b5-a324-4e0ece3c66ee.png)
![Screenshot_20230216_161814](https://user-images.githubusercontent.com/205690/219425831-0a07416f-dcb5-478e-9c81-fdafae403958.png)

**Comment by GregValiant** [comment]
Thanks for the report and the file.
You have a couple of things going on there and both are resulting in "Expected Behavior".
You have your Outer Wall speed at 90 and above about layer 31 that model is all Outer Walls.
You have your "Flow Equalization Ratio" at 100%.  The tooltip for that setting explains what you are seeing.
The bottom line is that "Minimum Layer Time" doesn't come into it.

I'll go ahead and remove the bug label and close this as it is a settings issue.  You can still respond here and let me know if you think that is premature.
The only setting I changed for this is the Flow Equalization Ratio at "0".  The speeds are 90 or 180 depending on the feature.
![image](https://user-images.githubusercontent.com/64202104/219798979-a18ab2b1-0e44-49e7-a69f-9daeeb546a18.png)
