### ISSUE TITLE
Bug remplissage couche 0.3 (impression en couche de 0.15)

### ISSUE THREAD

**Issue by judo26** [Ultimaker/Cura#14620]
### Application Version

5.2.2 et 4.13.1

### Platform

Win10

### Printer

Flsun SR et Ratrig Vcore 3.0

### Reproduction steps

Lors de l'impression de remplissage tout les 2 ou 3 couches.
Couche 0.15
Impression du remplissage tout les 0.3 mm

### Actual results

Les couches ou le remplissage s'imprime fonctionne correctement.
Cependant, pendant les couches ou le remplissages n'est pas censé s'imprimer, des petits "points" sont extrudés aléatoirement aux points de jonction avec la parois. Cela fait perdre un temps énorme a l'impression, et en plus  cela génère des beaucoup de rétraction avec très peu d'extrusion entre celles-ci ce qui créer des problèmes pour les couches suivante.

### Expected results

Lors des couches ou le remplissage ne devrait pas être imprimé, seul les parois et le dessus et dessous devrait être imprimé.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![bug](https://user-images.githubusercontent.com/123476368/220137811-225c2805-9751-407f-b026-eca6cdec1feb.png)

**Comment by judo26** [comment]
I use the "infill layer thickness" setting of course but the problem is that on the layers where the infill is not supposed to be printed, small extrusion dots are still made like on the picture I sent you. If you zoom in where the red arrows are pointing, there are two smalls oranges dots corresponding to infill when on this layer no infill should have been printed.

**Comment by judo26** [comment]
I will add a file, change the extension ".zip" to ".3mf".
Look at floor 204 for example.

**Comment by judo26** [comment]
[bug.zip](https://github.com/Ultimaker/Cura/files/10803241/bug.zip)

**Comment by MariMakes** [comment]
Hey @judo26,

Sorry, it took us a while to get back to you 😞 
It seems that this issue must have gotten lost in the pile.

I took another look and it seems that this issue seems to be resolved in the latest version of Cura. 
Could you test if that's the case for you as well? 
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.1

![image](https://github.com/Ultimaker/Cura/assets/40423138/9bde1655-2445-4bae-b3da-a8ca7f2b19ee)

To me, it doesn't seem like a bug in Ultimaker Cura anymore. 
Would you still like to keep this issue open or do you agree that we can close it?
