### ISSUE TITLE
Just updated and z-seam still not aligned

### ISSUE THREAD

**Issue by 16lionheart16** [Ultimaker/Cura#14622]
### Application Version

5.2.2

### Platform

Windows 10

### Printer

ender 3 v2

### Reproduction steps

imported model that had a cylinder.
used normal settings, with z seam set to user-specified & corner preference set to none, sliced.
z seam is not aligned, tried different positions and corner preference, no difference.
tried z seam relative, no difference
tried updating from 5.1.0, no difference
![image](https://user-images.githubusercontent.com/50107758/220209415-58854877-7774-42da-aaa8-8f8f9029ccd4.png)

### Actual results

z seam all over the joint
![image](https://user-images.githubusercontent.com/50107758/220209687-953610e0-f1cd-472f-a83f-ff2fe788c70f.png)

### Expected results

z seam to be a straight line along cylinder

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[Z Seam.zip](https://github.com/Ultimaker/Cura/files/10788241/Z.Seam.zip)

**Comment by MariMakes** [comment]
Hey @16lionheart16,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report 👍

We've made some significant improvements to the Zseam here https://github.com/Ultimaker/CuraEngine/pull/1762
Keep an eye out for the next 5.3 Beta release to try them out, your model will look like this: 
![image](https://user-images.githubusercontent.com/40423138/220323374-311e063e-42d2-4de2-9336-6a5a5c7419d5.png)

I'll be closing this issue since there is a fix in place.

**Comment by 16lionheart16** [comment]
Hi, would it be possible to get the gcode for that, or the project file,
thanks

**Comment by MariMakes** [comment]
Sure! Here you go:

[53_CE3E3V2_REELPART_V1.zip](https://github.com/Ultimaker/Cura/files/10794250/53_CE3E3V2_REELPART_V1.zip)
