### ISSUE TITLE
Slice terminated

### ISSUE THREAD

**Issue by CuriousBlackRedStart** [Ultimaker/Cura#14665]
### Application Version

5.2.2

### Platform

Windows 10

### Printer

Creality Ender3-Pro

### Reproduction steps

Downloaded [STL-File Baby Groot](https://www.thingiverse.com/thing:2610529)[](https://www.thingiverse.com/thing:2610529)
Sliced with Version Ultimaker 4.9.1 -> Everything okay
Got Notification to Update
Updated to Version 5.2.2
Sliced the same File -> Slicer crashed with "Failing to discretize parabola! Must add an apex or one of the endpoints."
Backend exited abnormally with return code 3221225477!

### Actual results

Nothing happened. Duh?

### Expected results

Something happens *Magic* -> Object-File

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[CE3PRO_Baby_Groot_Planter.zip](https://github.com/Ultimaker/Cura/files/10828958/CE3PRO_Baby_Groot_Planter.zip)
[cura.log](https://github.com/Ultimaker/Cura/files/10828966/cura.log)
[Baby_Groot_Planter.zip](https://github.com/Ultimaker/Cura/files/10828969/Baby_Groot_Planter.zip)

**Comment by MariMakes** [comment]
Hey @CuriousBlackRedStart,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

The new Cura 5.3 stable contains the fix for this for a number of slicing crashes. 
I was able to slice your model succesfully. Could you test if that's the case for your model as well? 
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0

![image](https://user-images.githubusercontent.com/40423138/226409342-83c256c8-1219-4ac4-96e6-175f88950927.png)

If you still have trouble slicing can you doublecheck if you shared the correct file and let us know? 
Than I'll take another look. 👍
