### ISSUE TITLE
Slicing keeps failing

### ISSUE THREAD

**Issue by tgressm1** [Ultimaker/Cura#14664]
### Application Version

5.3.0-beta.1

### Platform

Windows 11

### Printer

Ender-3

### Reproduction steps

1. Created new project in Cura
2. Adjusted print settings
3. Selected slice

### Actual results

1. Received error message that says: "Slicing failed: Slicing rfaile dwith an unexpected error. Please consider reporting a bug on our issue tracker"

### Expected results

1. It should slice the object

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Initially I was using customized print settings. I set everything back to default to see if that would resolve the slicing issue--it did not. I also tried closing out of Cura and restarting--this also did not fix the slicing issue

**Comment by MariMakes** [comment]
Hey @tgressm1,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

The new Cura 5.3 stable contains the fix for this for a number of slicing crashes. 
Could you test if that's the case for your model as well? 
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
