### ISSUE TITLE
Sliceing failed

### ISSUE THREAD

**Issue by RyzenSavior** [Ultimaker/Cura#14663]
### Application Version

5.3.0 -beta 1

### Platform

windows 11

### Printer

Tenlog D3 pro

### Reproduction steps

1. Load hydroponic garden funnel adapter. https://www.thingiverse.com/thing:4683594
2. Rotated 180 deg. so that large portion of funnel rests on build plate
3. print setting (e1 .6 nozzel e2 off) extra fast 0.3 profile, 20% infill, no supports, 8mm brim)

[CFFFP_Hydro_Tower_Funnel_v2.zip](https://github.com/Ultimaker/Cura/files/10828163/CFFFP_Hydro_Tower_Funnel_v2.zip)
[cura.log](https://github.com/Ultimaker/Cura/files/10828168/cura.log)

### Actual results

Upon pressing slice, moments later slicing failed for unknown reason window appears

### Expected results

project should slice

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

 observation: it seems to be the 0.6 nozzle size that triggers the error. if I keep everthing the same but change the nozzle size to 0.4 it slices without and issue. If I retain the 0.6 nozzle size but change other settings... print still fails to slice.

**Comment by MariMakes** [comment]
Hey @RyzenSavior,

Thanks for your report 👍
Sorry, it took us a while to get back to you 😞 
I'm an avid hydroponic farmer as well, [this is my balcony farm. ](https://community.ultimaker.com/topic/42019-best-material-for-a-working-prototype/?do=findComment&comment=314849) so you made my day sharing your hobby 🌱 

The new Cura 5.3 stable contains the fix for this for a number of slicing crashes. 
Could you test if that's the case for your model as well? I was able to slice your file succesfully
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0

![image](https://user-images.githubusercontent.com/40423138/226406711-f5665914-2c21-4d9c-98b6-9c33894083f0.png)

To me, it doesn't seem like a bug in Ultimaker Cura anymore.
If it still doesn't slice correctly for you, can you doublecheck if you shared the correct projectfile?
