### ISSUE TITLE
Failure to Slice

### ISSUE THREAD

**Issue by Jon-Praxis** [Ultimaker/Cura#14670]
### Application Version

5.2.1

### Platform

WIndows 11

### Printer

Ender 3

### Reproduction steps

Attempted to slice file after moving the objects off center.
This file had been previously sliced.

### Actual results

It gave me an error was unable to slice the file
[2D_15mm_Nose 2.zip](https://github.com/Ultimaker/Cura/files/10830296/2D_15mm_Nose.2.zip)

### Expected results

Should have sliced

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[2D_15mm_Nose 2.zip](https://github.com/Ultimaker/Cura/files/10830297/2D_15mm_Nose.2.zip)

**Comment by MariMakes** [comment]
Hey @Jon-Praxis,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

The new Cura 5.3 contains the fix for this for a number of slicing crashes. 
I was able to slice your model successfully in 5.3.0 Stable.
Could you test if that's the case for your model as well? 
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0

![image](https://user-images.githubusercontent.com/40423138/226415035-6207baea-29f4-4809-9f7c-6d316425b3ca.png)

If you still run into a crash, please doublecheck if you shared the correct file and let us know.
I'll take another look at what is going wrong. 👍
