### ISSUE TITLE
Strange layers

### ISSUE THREAD

**Issue by IngwarSa** [Ultimaker/Cura#14681]
### Application Version

5.3.0-beta2

### Platform

Windows 10

### Printer

Voron 2.4

### Reproduction steps

Wall thickness 2.5mm
Layer width 0.5mm

### Actual results

Why are the layers on the corners of this shape?

### Expected results

Sorry if I wrote to the wrong address.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

![1](https://user-images.githubusercontent.com/92488422/221372895-a81b6527-c5ce-466d-b5bc-debd331777f3.png)
![2](https://user-images.githubusercontent.com/92488422/221372897-bb440cac-138b-49e9-a5c8-6c239f7e52bb.png)
![3](https://user-images.githubusercontent.com/92488422/221372901-c9a6e2b4-53e7-445b-9d10-a7ce2dd75ebd.png)
![4](https://user-images.githubusercontent.com/92488422/221372903-33d588f4-b329-498b-b879-eb88b57cb321.png)
[V250_1.zip](https://github.com/Ultimaker/Cura/files/10831952/V250_1.zip)

**Comment by MariMakes** [comment]
Hey @IngwarSa,

Welcome to the Ultimaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

Ah, this seems related to the Variable Linewidth Engine in Cura 5.x .

​​​​​​​There are settings that you can change to improve this behavior.
You can read more about them here: 
https://support.ultimaker.com/hc/en-us/articles/4792077687068

To me, it doesn't seem like a bug in Ultimaker Cura, because this behavior is setting dependend. 
Would you still like to keep this issue open or do you agree that we can close it?

**Comment by MariMakes** [comment]
![image](https://user-images.githubusercontent.com/40423138/223435724-48a9a394-df47-4bf3-a5db-12832e414e18.png)

I think the setting you are looking for is the Wall Transitioning Threshold Angle. 

I'll close the issue! Good luck with your printjob and let us know if you run into anything else 👍
