### ISSUE TITLE
Slicer engine crashes

### ISSUE THREAD

**Issue by rd3dprt** [Ultimaker/Cura#14687]
### Application Version

5.3.0-beta1

### Platform

Windows 11

### Printer

Sovol SV05

### Reproduction steps

Just tried slicing this file.

### Actual results

The slicer crashes.

### Expected results

Successful slicing
[CuraErrors.zip](https://github.com/Ultimaker/Cura/files/10832764/CuraErrors.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[CuraErrors.zip](https://github.com/Ultimaker/Cura/files/10832772/CuraErrors.zip)

**Comment by MariMakes** [comment]
Hey @rd3dprt,

Thanks for your report 👍
Sorry, it took us a while to get back to you 😞 

The new Cura 5.3 contains the fix for this for a number of slicing crashes. 
I was able to slice your model successfully in 5.3 Stable.

![image](https://user-images.githubusercontent.com/40423138/226638751-2075b018-fb8d-474e-a311-6a61759ee0f5.png)

Could you test if that's the case for your model as well? 
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0

If you still run into a crash, please double-check if you shared the correct file and let us know.
I'll take another look at what is going wrong. 👍
