### ISSUE TITLE
Slicing failed

### ISSUE THREAD

**Issue by kiniad** [Ultimaker/Cura#14694]
### Application Version

5.3.0.beta.1

### Platform

Windows 11

### Printer

Tronxy X5SA 400 2E

### Reproduction steps

Loading a downloaded thing from thingiverse: https://www.thingiverse.com/thing:5784719/files
Hit the button "SLICE" so I get a "slicing failed" with a button to report a bug, what I have done with this report.

### Actual results

Error Message "slicing failed" with a button to report a bug

### Expected results

normally I want to have a sliced file, a gcode to save on SD card.
[cura.log](https://github.com/Ultimaker/Cura/files/10833828/cura.log)

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

none

**Comment by MariMakes** [comment]
Hey @kiniad,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

The new Cura 5.3 Stable contains the fix for this for a number of slicing crashes. 
Could you test if that's the case for your model as well? 
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.

**Comment by kiniad** [comment]
Hey MariMakes,
I have no issues anymore.
sorry, I'm late. In the meantime I switched tp the 5.3.0-alpha+xmas and now on 5.3.1. Slicing works fine on both versions.

**Comment by MariMakes** [comment]
That's great to hear!
Thanks for getting back to us 😄
