### ISSUE TITLE
Slicing Error

### ISSUE THREAD

**Issue by AlphaBull** [Ultimaker/Cura#14706]
### Application Version

 5.3.0-beta.2

### Platform

Windows 10

### Printer

Ender 3 Pro

### Reproduction steps

I try to slce a Model und became an error Slicing faild if i rotete it on the x axe it helps sometimes

### Actual results

Slicing is over and i can't print...

### Expected results

slice the model so i can send it to octopi and print it...

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![grafik](https://user-images.githubusercontent.com/123019400/221534926-fdc37f8e-79fd-44c8-8793-c7cc8c36a9c9.png)

**Comment by MariMakes** [comment]
Hey @AlphaBull,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

The new Cura 5.3 Stable contains the fix for this for a number of slicing crashes. 
Could you test if that's the case for your model as well? 
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
