### ISSUE TITLE
[AppImage Modern] Missing Workspace

### ISSUE THREAD

**Issue by tophers** [Ultimaker/Cura#14703]
### Application Version

5.3.0-beta.2

### Platform

Linux

### Printer

Custom

### Reproduction steps

1.) Open Modern AppImage (Curent Beta or Stable)
2) I can open a file, change slicer settings, even slice a file and export/save it
3.) no workspace displayed

### Actual results

Workspace not Displayed

### Expected results

To be able to see/Rotate object visually

### Checklist of files to include

- [X] Log file
- [x] Project file

### Additional information & file uploads

![Screenshot_20230226_224410](https://user-images.githubusercontent.com/3819786/221485264-8f6969ac-e8ce-4488-8ff0-ddd156c1bd31.png)
![Screenshot_20230226_224258](https://user-images.githubusercontent.com/3819786/221485302-80507efb-1431-4638-b48a-3cfde337497d.png)
[cura.log](https://github.com/Ultimaker/Cura/files/10836508/cura.log)

**Comment by tophers** [comment]
I've since found this happens on any version of Cura regardless of install method, Flatpak, Native (apt, older version), appImage Modern or not. I've tried with a new user, same effect. What would cause just the workspace to not appear?

**Comment by tophers** [comment]
> Could it be that the QML engine is not "seeing" the size of the window (and thusly sets some widths and heights to 0px)?
How would I verify or confirm this?

**Comment by Joseja8** [comment]
This is happening to me too. Let me know if I can help.

**Comment by tophers** [comment]
Console message FWIW:

$ ./UltiMaker-Cura-5.3.0-beta.2-linux-modern.AppImage 
PyInstaller/loader/pyimod02_importers.py:352: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
Cyclic dependency detected between "file:///tmp/.mount_UltiMaeaLbfP/share/cura/resources/qml/Actions.qml" and "file:///tmp/.mount_UltiMaeaLbfP/share/cura/resources/qml/Actions.qml"
QQmlEngine::setContextForObject(): Object already has a QQmlContext
file:///tmp/.mount_UltiMaeaLbfP/share/cura/resources/qml/PrintSetupSelector/Recommended/RecommendedPrintSetup.qml:96:17: QML QQuickItem: Binding loop detected for property "height"
file:///tmp/.mount_UltiMaeaLbfP/share/cura/resources/qml/PrintSetupSelector/Recommended/RecommendedPrintSetup.qml:96:17: QML QQuickItem: Binding loop detected for property "height"

**Comment by tophers** [comment]
> I cannot spot what is going wrong but I'll bring it up with the team. Maybe they can see what is happening or what information we need for troubleshooting.
> 
> Fingers crossed crossed_fingers

@MariMakes  Thank you. Willing to provide logs/test anything.

**Comment by MariMakes** [comment]
Hey @tophers,

We have a nightly build available that might fix what you are encountering.
There is a slime chance, but it's still a chance that this fixes your issue. 

Can you give it a go and let us know if this resolves your issue?
[You can download the build here.](https://github.com/Ultimaker/Cura/discussions/15098)

**Comment by tophers** [comment]
Still unable to see most windows within the application.  I honestly figure this is less of an application bug and more of something on my system -- but I don't know what or how those are generated or by what libraries may be an issue - or how to even setup an environment to troubleshoot. 

![1](https://user-images.githubusercontent.com/3819786/230434566-4531ae2a-e2c1-43e8-8f57-9aaf202c846f.png)
![2](https://user-images.githubusercontent.com/3819786/230434603-b452f3e8-a240-4e94-ab7f-8747373641aa.png)
![3](https://user-images.githubusercontent.com/3819786/230434632-1ef15d5d-5f89-4306-b7e1-395a09b68f4a.png)

**Comment by tophers** [comment]
Closing this as I'm no longer using Cura.

**Comment by jellespijker** [comment]
@tophers since this seem to affect more people than just you, I'm reopening it because it is still an issue.
For the 5.5.0 release I'm using a different tool to collect the libraries I'm hoping if you would be willing to test if this AppImage runs for you: [UltiMaker-Cura-5.5.0-alpha+cura_10951_2bc307-linux-X64-AppImage](https://github.com/Ultimaker/Cura/suites/15883868038/artifacts/907218000) 

Can you also test this @Joseja8 ?

The AppImage is build on the PR: https://github.com/Ultimaker/Cura/pull/16607

**Comment by MariMakes** [comment]
👋 Quick update on our side. 

This is resolved in the 5.5 Beta release 🎉 , you can download the Cura version with the fix here: [https://github.com/Ultimaker/Cura/releases/tag/5.5.0-beta.1](https://github.com/Ultimaker/Cura/releases/tag/5.5.0-beta.1)
I'll close this issue since it's resolved. 

Thanks again, and please let us know if you run into any other issues 💪

**Comment by quickishfm** [comment]
Hi, I'm facing this same issue on Cura 5.7.2. Running KDE Plasma 6.2.1 on Arch Linux (Appimage version - the one on the AUR does not build due to an orphaned dependency)

I'm using Nvidia graphics, in case that helps. I'm willing to provide logs and debug information to help get this fixed.

**Comment by jellespijker** [comment]
what happens when you start Cura with `QT_QPA_PLATFORM=xcb ./UltiMaker bladibla.AppImage` 

written on my phone, replace with actual AppImage filename

**Comment by quickishfm** [comment]
Thanks @jellespijker that makes it work!

I cannot remember if I wrote about the issue on X11 or Wayland (as during that time I was swapping back and forth due to some X11 KDE bugs) but I notice now that Cura launches fine on X11, but not on Wayland.
Using `QT_QPA_PLATFORM=xcb` fixes it on Wayland though.

**Comment by jellespijker** [comment]
@HellAholic do we have a ticket for Wayland support on the backlog already?
