### ISSUE TITLE
Slicing Error

### ISSUE THREAD

**Issue by plainpylut** [Ultimaker/Cura#14701]
### Application Version

5.3.0-beta.1

### Platform

Windows 10

### Printer

Creality Ender 5 Plus

### Reproduction steps

1.  Downloaded STL from Thingiverse.
2. Opened it in Cura.
3. Tried to slice it.  Error is reported " Slicing failed with an unreported error:  Please report a bug".
[Cura_Beta.zip](https://github.com/Ultimaker/Cura/files/10835442/Cura_Beta.zip)

### Actual results

Slicing failed.
Reverted to ver 5.2.2 and it slices.
I have a Slice Engineering hardened steel nozzle that requires +20C on all temps to print properly!
I installed 5.3.0-beta.1 with 5.2 installed, then removed 5.2.  Now the Beta appears to not find some subdirs???

### Expected results

Slice completion!

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

Cura_Beta.zip

Hope this helps.

**Comment by MariMakes** [comment]
Hey @plainpylut,

Thanks for your report 👍
Sorry, it took us a while to get back to you 😞 
That's a super cool model 😻 

The new Cura 5.3 contains the fix for this for a number of slicing crashes. 
I was able to slice your model successfully in 5.3 Stable.
![image](https://user-images.githubusercontent.com/40423138/226650119-9b3330a2-bf86-4943-b31b-ebc2cca0d179.png)

Could you test if that's the case for you as well? 
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0

If you still run into a crash, please double-check if you shared the correct file and let us know.
I'll take another look at what is going wrong. 👍
