### ISSUE TITLE
to slice bug

### ISSUE THREAD

**Issue by CarolBraulino** [Ultimaker/Cura#14718]
### Application Version

5.2.2

### Platform

macOS

### Printer

Ultimaker Cure

### Reproduction steps

tree support

to slice

error

### Actual results

tree support

to slice

error

### Expected results

tree support

to slice

sucess

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

https://user-images.githubusercontent.com/90408408/221875981-4078a08a-7e1d-4ddc-986e-fc6745ced07a.mov

**Comment by MariMakes** [comment]
Hey @CarolBraulino,

Welcome to the Ultimaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 
That's a pretty cool model 🙁 

The new Cura 5.3 contains the fix for this for a number of slicing crashes. 
Could you test if that's the case for your model as well? 
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
