### ISSUE TITLE
Issue slicing a file

### ISSUE THREAD

**Issue by TravisLangdale** [Ultimaker/Cura#14727]
### Application Version

5.2.2

### Platform

Windows 10

### Printer

Monoprice Maker select v2

### Reproduction steps

1.Downloaded and extracted following file https://www.thingiverse.com/thing:4164793
2.  Opened MU_modok in Ultimaker Cura 5.2.2
3. Clicked sliced button
4. recieved error "slicing failed with an unexpected error. Please consider reporting a bug on our issue tracker"

### Actual results

slice fails and nothing happens

### Expected results

File should be sliced

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![modok snip](https://user-images.githubusercontent.com/126680024/222144260-70924ab6-af81-4bfb-8bb5-cf61e6575d78.JPG)

**Comment by GregValiant** [comment]
Thanks for the report.
There was a persistent bug in 5.2 and 5.1 that can keep a model from slicing when it's at the mid-point of the Cura build plate.  You can try moving the model in Cura and maybe rotating it.
This bug was addressed for 5.3.  You might want to move up to it.
I'll mark this as a duplicate and close it.  It was a well known problem with previous versions.  I hope you understand.

This is with the 5.3beta release of Cura.
![image](https://user-images.githubusercontent.com/64202104/222227212-f0624e47-76ba-4619-8c59-717a299a60ca.png)
