### ISSUE TITLE
slicing error

### ISSUE THREAD

**Issue by Jamisus** [Ultimaker/Cura#14734]
### Application Version

5.2.2

### Platform

windows 10

### Printer

ender 3 v2

### Reproduction steps

tried to slice a model, got a slicing error. changed the size by 1%, then sliced super fast

### Actual results

sliced correctly

### Expected results

sliced correctly

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

no other comments

**Comment by MariMakes** [comment]
Hey @Jamisus,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report 👍

The new Cura 5.3 contains the fix for this for a number of slicing crashes. 
Could you test if that's the case for your model as well? 
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
