### ISSUE TITLE
housing with modellized threads

### ISSUE THREAD

**Issue by AP-Reinhard** [Ultimaker/Cura#14739]
### Application Version

5.2.2.

### Platform

Windows 10

### Printer

Ultimaker S5

### Reproduction steps

Loaded the stl-file
fixing printing options, using support structure
start slicing
![Screenshot 2023-03-02 143841](https://user-images.githubusercontent.com/126787032/222444623-463baf2f-fcaa-4d58-a8f2-637d63a3bf0b.jpg)
![Screenshot 2023-03-02 143908](https://user-images.githubusercontent.com/126787032/222444627-6a27da88-5fd3-4fbe-81ed-016d926ad8e7.jpg)
![Screenshot 2023-03-02 143942](https://user-images.githubusercontent.com/126787032/222444629-829ad046-1b30-4381-90fb-22170ed04e7f.jpg)
![Screenshot 2023-03-02 143804](https://user-images.githubusercontent.com/126787032/222444632-34a5eae6-a577-4ac3-ad3f-9a184be1ac5b.jpg)

### Actual results

Slicing does create failure

### Expected results

correct slicing

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[UMS5_Gehäuse 01-PR20025-05_Druckversion.zip](https://github.com/Ultimaker/Cura/files/10871923/UMS5_Gehause.01-PR20025-05_Druckversion.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
Your model sliced for me on the first attempt.  Since it was a model file and not a project file my Ender was the active printer.  It's not the same size as your S5 and so the model was not centered.  There is a bug in Cura that hates when the models are in the center of the build plate.  Try moving and/or rotating the model.  You may find a spot where it will slice.
I'll mark this as a duplicate report.

**Comment by jellespijker** [comment]
Thank you for your report. It seems that your uploaded project file slices correct on our latest unreleased 5.7.0-alpha.0+3abb5 which indicates that the issue you're experiencing seems to be fixed for the upcoming 5.7.0 release.
I'm closing this issue as fixed for the 5.7.0 release
![image](https://github.com/Ultimaker/Cura/assets/8535734/54948e9b-f042-4ba8-8575-dbefd30d0345)
