### ISSUE TITLE
mask wont slice

### ISSUE THREAD

**Issue by tonietirado** [Ultimaker/Cura#14735]
### Application Version

5.2.1

### Platform

windows 10

### Printer

creallity s1

### Reproduction steps

uploaded mask
sized it to 75%
rotated flat
sliced

### Actual results

wont slice error message pops up with link to this website

### Expected results

should slice

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

![snapshot](https://user-images.githubusercontent.com/126726938/222281806-4c609a2a-0b94-4621-9df5-af199922efd5.jpg)

**Comment by MariMakes** [comment]
HEy @tonietirado,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report 👍

The new Cura 5.3 contains the fix for this for a number of slicing crashes. 
Could you test if that's the case for your model as well? 
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
