### ISSUE TITLE
Slicing failed with an unexpected error

### ISSUE THREAD

**Issue by rpersak** [Ultimaker/Cura#14747]
### Application Version

5.3.0 Beta 2

### Platform

Windows 11

### Printer

Ender 3 pro

### Reproduction steps

1. Loaded model
2. clicked "slice"

### Actual results

I get an error: 
![image](https://user-images.githubusercontent.com/28995435/222667008-f40d9708-6d2d-4be0-a9f4-ab36bac5098f.png)

### Expected results

Sliced model

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[CE3PRO_gravity_feeder_tall.zip](https://github.com/Ultimaker/Cura/files/10879923/CE3PRO_gravity_feeder_tall.zip)
[cura - Copy.zip](https://github.com/Ultimaker/Cura/files/10879925/cura.-.Copy.zip)

**Comment by GregValiant** [comment]
Thanks for the report and the files.
I agree this model should slice as is.  I rotated it 90° and moved it but it still wouldn't slice.  Rotated to 45° it sliced right away so that might be your workaround.

I'll mark this as a slicing error and as a duplicate.  This bug was worked on for 5.3 but doesn't seem to be fixed yet.
![image](https://user-images.githubusercontent.com/64202104/222711709-edcc5bbd-55ba-4286-b639-7ea6b48cc49e.png)

**Comment by jellespijker** [comment]
Thank you for your report. It seems that your uploaded project file slices correct on our latest unreleased 5.7.0-alpha.0+3abb5 which indicates that the issue you're experiencing seems to be fixed for the upcoming 5.7.0 release.
I'm closing this issue as fixed for the 5.7.0 release
![image](https://github.com/Ultimaker/Cura/assets/8535734/965da71e-3842-42ee-96fe-0ca0cc01e65d)
