### ISSUE TITLE
 Cura sends "M105" to serial 2D printer

### ISSUE THREAD

**Issue by ikeji** [Ultimaker/Cura#14749]
### Application Version

5.3.0-Beta2

### Platform

Ubuntu 20.04

### Printer

Ender3 + Otoprint

### Reproduction steps

I have *2D* Receipt printer and attached to /dev/ttyS0.
https://www.adafruit.com/product/597

### Actual results

When I start cura, the printer keep prints "M105" repeatedly.

### Expected results

The cura doesn't touch the port that is not specified.

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

This was not happen in  Cura 5.2.2.

Can we disable the check by option?
Or can we specify the port?

[cura.log](https://github.com/Ultimaker/Cura/files/10881289/cura.log)

https://twitter.com/ikeji/status/1631639132899540993

**Comment by GregValiant** [comment]
Thanks for the report.
The USB Printing plugin can be disabled in the Cura MarketPlace.  That's your best option as you are using Octoprint.
Since USB Printing is a legacy plugin it isn't maintained by anyone but it continues to be included with Cura because some folks like to print via USB.

I'll remove the bug label from this.  It's expected behavior from "USB Printing".  Let me know if you feel differently about that.

**Comment by ikeji** [comment]
Thanks for reply.

I confirmed that when I disabled the plugin, there are no unexpected print.

Thanks,

**Comment by GregValiant** [comment]
The plugin sends M105 and waits for a response from the printer.  If it understands the response then it knows the baud rate is correct.  Since there was no response, or a garbled response from the receipt printer USB Printing just kept trying and the printer kept printing.
I'll go ahead and close this then.
