### ISSUE TITLE
slicing failed

### ISSUE THREAD

**Issue by squinty-eyes** [Ultimaker/Cura#14756]
### Application Version

5.2.1

### Platform

win 10

### Printer

cr6se

### Reproduction steps

tried to slice

### Actual results

failed

### Expected results

slice successful  

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

na

**Comment by MariMakes** [comment]
Hey @squinty-eyes,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report 👍

The new Cura 5.3 contains the fix for this for a number of slicing crashes. 
Could you test if that's the case for your model as well? 
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
