### ISSUE TITLE
Supports Not Working

### ISSUE THREAD

**Issue by KlajdiH** [Ultimaker/Cura#14757]
### Application Version

5.3.0 beta-2

### Platform

Windows 11

### Printer

Ender 3

### Reproduction steps

1. Upload any file to Cura 
2. Turn supports on and chose normal support style
3. Click Preview 

### Actual results

No supports generated at all, regardless of weither touching build plate or other settings in supports are changed

### Expected results

Generates regular supports

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

Same exact settings and file works with 5.2.1 cura

**Comment by GregValiant** [comment]
Thanks for the report.
I can't duplicate the problem and since you haven't provided a project file (instructions are on the page you filled out for this report) there is no way to tell what might be going on.
![image](https://user-images.githubusercontent.com/64202104/222902223-c32c0315-ba47-4fc5-b336-d87c7ceecd1c.png)
in the "Color Scheme" dialog - if you have "Helpers" turned off then the supports aren't shown.  This is the same slice as above but with Helpers off.
![image](https://user-images.githubusercontent.com/64202104/222902278-2a897a0b-cda6-44ed-be11-6397b83247aa.png)
