### ISSUE TITLE
Slicing Error

### ISSUE THREAD

**Issue by Gabrillllllll** [Ultimaker/Cura#14771]
### Application Version

idk

### Platform

windows 11

### Printer

ender v2

### Reproduction steps

internetinternet

### Actual results

it did not slice

### Expected results

your mom

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

Your dad

**Comment by Gabrillllllll** [comment]
you

**Comment by GregValiant** [comment]
Mom and Dad are in jars on the mantle.  Pretty sure it wasn't them.

**Comment by MariMakes** [comment]
Hey @Gabrillllllll,

Welcome to the Ultimaker Cura Github 🚀 
Your request is unclear, how can we help you? 

Did you have trouble slicing? Because we'll need a little bit more information from you to help you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
