### ISSUE TITLE
Slicing Failure

### ISSUE THREAD

**Issue by Theflopflop02** [Ultimaker/Cura#14799]
### Application Version

5.2.1

### Platform

Windows 10

### Printer

Ender-3 v2

### Reproduction steps

1. Opened Cura, along with the item to be printed
2. Clicked slice

### Actual results

A small message popped up saying report this issue;

### Expected results

Should have sliced the object, then allowed me to save it as a gcode. onto my disk

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![image](https://user-images.githubusercontent.com/127157742/223279123-db017725-e833-49c4-badf-c2d05633e933.png)

**Comment by MariMakes** [comment]
Hey @Theflopflop02,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report 👍

The new Cura 5.3 contains the fix for this for a number of slicing crashes. 
Could you test if that's the case for your model as well? 
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
