### ISSUE TITLE
cura crashing

### ISSUE THREAD

**Issue by LostNewfie** [Ultimaker/Cura#14825]
### Application Version

5.3.0

### Platform

mac

### Printer

creality ender 3 s1

### Reproduction steps

app crashed after a while

### Actual results

have to restart

### Expected results

reopened program

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

will send full report on next crash

**Comment by MariMakes** [comment]
Hey @LostNewfie,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

The new Cura 5.3 Stable contains the fix for this for a number of slicing crashes. 
Could you test if that's the case for your model as well? 
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.

**Comment by LostNewfie** [comment]
I am running 5.3 stable. Cuts crashes after sitting idle for a while. You can use it for a while. Close all projects. Minimize and after a while it will crash. You go to use it and it is crashed. Reopen and it will work again. Running the program on Mac iOS Monterey. Glenn Life should not be a journey to the grave with the intention of arriving safely in a pretty and well preserved body, but rather to skid in broadside, in a cloud of smoke, thoroughly used up, totally worn out, and loudly proclaiming, "Wow! What a Ride"On Mar 21, 2023, at 9:56 AM, MariMakes ***@***.***> wrote:﻿
Hey @LostNewfie,
Welcome to the UltiMaker Cura Github 🚀
Sorry, it took us a while to get back to you 😞
The new Cura 5.3 Stable contains the fix for this for a number of slicing crashes.
Could you test if that's the case for your model as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0
If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting.
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.
You'll need to open Github in your browser to attach any files to your ticket
You can click the view it on GitHub link at the bottom of your email to open GitHub in the browser.
