### ISSUE TITLE
Way too many supports being generated

### ISSUE THREAD

**Issue by derekslenk** [Ultimaker/Cura#14821]
### Application Version

5.3.0

### Platform

Windows 11

### Printer

Creality Ender 3 

### Reproduction steps

Uploaded a model to slice: https://www.thingiverse.com/thing:2683032
Turn on supports and slice.

### Actual results

Supports are generated for the threads only, lik eit did in 5.3.0-beta

### Expected results

Way tooo many support

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

![image](https://user-images.githubusercontent.com/42957/223738552-1cbba791-c5f7-4234-8418-624cfa40d06e.png)
[CE3E3V2_DnD_Dice_Box_Base.zip](https://github.com/Ultimaker/Cura/files/10921510/CE3E3V2_DnD_Dice_Box_Base.zip)

**Comment by MariMakes** [comment]
Hey @derekslenk,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report 👍

This support looks correct to me 😅 
If you check under your model, you can see that there are a lot of red pats that need support. 
![image](https://user-images.githubusercontent.com/40423138/223745255-b3610b43-f608-4d3c-b5b3-087bc5fa2358.png)

If you don't want those parts to be supported, and only the lid. 
You can change settings like Support Overhang Angle to reduce the support that is generated. 
![image](https://user-images.githubusercontent.com/40423138/223745083-f7f3886a-2ea6-4ee1-82af-06dc24e76e09.png)

To me, it doesn't seem like a bug in Ultimaker Cura, since we have a solution in place. 
Does this solve your problem and can we close the bug?

**Comment by derekslenk** [comment]
Yeah, that will work, I just was kind of shocked by default that the beta and new version generated such different support structures
