### ISSUE TITLE
5.1, 5.3 refuse to load stls that import in to 4.12 and 5.0

### ISSUE THREAD

**Issue by stev-e** [Ultimaker/Cura#14835]
### Application Version

5.1.0 5.3.0 

### Platform

Windows 10 64

### Printer

creality cr10-s5

### Reproduction steps

either as the initial task or from a cleared platen attempted to load the stl file.

### Actual results

error message pops up: "unable to open file" "failed to load file ******** file could be corrupt, inaccessible or did not contain any models"

### Expected results

the stl file should damn well load, it manages it in versions 4.12 and 5.0 and my other stl capable applications.
please note that i have reduced the file down to a small initial section, i am not expecting it to slice in a sensible manner.

i note that if i save it as a project then 5.1, 5.3 can load the projects
i have not tested 5.2

[_STL.zip](https://github.com/Ultimaker/Cura/files/10937073/_STL.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

i find this web form rather annoying, the "submit button" seems to be deactivated most of the time

**Comment by MariMakes** [comment]
Hey @stev-e,

Welcome to the Ultimaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

Thanks for sharing your files, I took a look. 
![image](https://user-images.githubusercontent.com/40423138/225928177-02a0280c-90f2-4e46-ba79-85f7597e402e.png)

This mesh seems faulty, do you see all the discolorations? They indicate that there is an error in your model. 
Do you have access to the original CAD file? Can you find other settings to export a watertight STL/3mf file?

You can also try a more elaborate mesh fixer like https://myminifactory.github.io/Fast-Quadric-Mesh-Simplification/, or https://www.nanodlp.com/repair-3d-stl-file/.
Or you can use the "Make Solid" feature in AutoDesk MeshMixer. https://meshmixer.com/download.html

To me, it doesn't seem like a bug in Ultimaker Cura, since the mesh is faulty and Cura is not built to alter meshes in this way, that's what CAD software is for. 
I'll be closing this issue. I hope you understand.
