### ISSUE TITLE
(5.3.0) Unexpected error while slicing Fusion 360 STL's

### ISSUE THREAD

**Issue by Sassythesasster** [Ultimaker/Cura#14839]
### Application Version

5.3.0

### Platform

MacOS Ventura 13.2.1 (2GHz QuadCore Intel Core i5, 16GB)

### Printer

Ender 3 Pro

### Reproduction steps

1. Import 4 small STL files exported from Fusion 360
2. Reload one of the models as suggested
3. Click slice

### Actual results

After a second of slicing, error message "Slicing failed with unexpected error" pops up, without having sliced my models

### Expected results

Proper sliced gcode file, ready to be uploaded to an sd card to print

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

My files contain private information. I would like to e-mail them instead. This is the first time I'm reporting a bug, please tell me if I did something incorrectly.

**Comment by MariMakes** [comment]
Hey @Sassythesasster,

Welcome to the Ultimaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

The new Cura 5.3 contains the fix for this for a number of slicing crashes. 
Sorry to hear you are still stuck. 

A common workaround we see that could help is rotating the model 90 degrees in xy or resizing it slightly. 
Is that an option for you?

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. 

If it's a secret you can send your details to community (at) ultimaker.com or reach out to me with a personal message on https://community.ultimaker.com/profile/385806-marimakes/

Hope this helps. 🤞
