### ISSUE TITLE
Slicing issue

### ISSUE THREAD

**Issue by HrishiWashi** [Ultimaker/Cura#14844]
### Application Version

5.2.2

### Platform

Windows 10

### Printer

Creality Ender-3/Ender-3 v2 

### Reproduction steps

1) I chose the printer type listed Creality Ender-3/Ender-3 v2 
2) Imported my project (obj file which can't be uploaded to this website) from blender
3) rotated it to 90 degrees
4) moved to the center and cut some parts off so they wouldn't get printer
5) Clicked Splice

### Actual results

It didn't splice and reported an issue
![Screenshot 2023-03-10 231830](https://user-images.githubusercontent.com/69818785/224471162-10cb2c4f-d0bd-4d33-a754-a444868aad5a.png)

### Expected results

It should have spliced properly so I could have gotten it printed. 

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

`
![Screenshot 2023-03-10 231830](https://user-images.githubusercontent.com/69818785/224471264-6e98128c-c311-415b-8de9-25ce172c7d56.png)

**Comment by MariMakes** [comment]
Hey @HrishiWashi,

Welcome to the Ultimaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

The new Cura 5.3 contains the fix for this for a number of slicing crashes. 
Could you test if that's the case for your model as well? 
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
