### ISSUE TITLE
Slicing engine crashes

### ISSUE THREAD

**Issue by rd3dprt** [Ultimaker/Cura#14842]
### Application Version

5.3.0-beta.1

### Platform

Windows 11

### Printer

Sovol SV03

### Reproduction steps

Tried to slice my design

### Actual results

The slicing engine crashes

### Expected results

Successful slicing

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[SSL_skeleton.zip](https://github.com/Ultimaker/Cura/files/10945373/SSL_skeleton.zip)

**Comment by MariMakes** [comment]
Hey @rd3dprt,

Thanks for your report 👍
Sorry, it took us a while to get back to you 😞 

The new Cura 5.3 Stable contains the fix for this for a number of slicing crashes. 
I took a look and it seems to go for your model aswell. 
![image](https://user-images.githubusercontent.com/40423138/225940321-47895f65-add6-4ed4-a618-f7416e4deded.png)

You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0

I'll close this issue since there is a solution in place. 
Thanks again for the report!
