### ISSUE TITLE
Sovol 04 not slicing

### ISSUE THREAD

**Issue by Ushoran86** [Ultimaker/Cura#14845]
### Application Version

5.2.1

### Platform

Windows 11

### Printer

Sovol 04

### Reproduction steps

Went to slice and it takes forever followed by it not and the error.

Used to be able to slice without issue.

### Actual results

Does not slice and returns to the button to slice with an bug error pop up

### Expected results

I'm able to slice.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

https://1drv.ms/u/s!AhUbzPehzxRQgZxa_M3bdoz31r8x-Q?e=12Bj9r

**Comment by MariMakes** [comment]
Hey @Ushoran86,

Welcome to the Ultimaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

The new Cura 5.3 contains the fix for this for a number of slicing crashes. 
Could you test if that's the case for your model as well? 
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
But I cannot open your OneDrive file. Can you share it as a Zip? 

To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
