### ISSUE TITLE
Slincing failed

### ISSUE THREAD

**Issue by PlayWithG** [Ultimaker/Cura#14855]
### Application Version

5.4.0-beta.2

### Platform

windows 11

### Printer

FLSUN Super Racer

### Reproduction steps

I just drop two file in cura, rotate one to 180 degree and I scale Z height to 25.5

### Actual results

I press Slice and show me one message saying Slicing failed

### Expected results

should Slice my proyect

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[cura5.3.log](https://github.com/Ultimaker/Cura/files/10950279/cura5.3.log)
[FSR_NSK_BullsEye.zip](https://github.com/Ultimaker/Cura/files/10950280/FSR_NSK_BullsEye.zip)

**Comment by MariMakes** [comment]
Hey @PlayWithG,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

The new Cura 5.3 contains the fix for this for a number of slicing crashes. 
I was able to slice your model successfully in 5.3 Stable.

![image](https://user-images.githubusercontent.com/40423138/226674936-26e1d1e4-b52b-4e60-a3a3-ff50a1e66059.png)

Could you test if that's the case for you as well? 
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0

If you still run into a crash, please double-check if you shared the correct file and let us know.
I'll take another look at what is going wrong. 👍
