### ISSUE TITLE
Error message displayed immediately after slicing.

### ISSUE THREAD

**Issue by cnanc3** [Ultimaker/Cura#14853]
### Application Version

5.3.0

### Platform

Windows 10

### Printer

Elegoo Neptune 2S

### Reproduction steps

1. Copied base.stl to Cura build plate.
2. Turned off supports (because model is flat and doesn't need supports)
3. Selected "Slice" button
4. Error displayed
[Base.zip](https://github.com/Ultimaker/Cura/files/10950095/Base.zip)

### Actual results

![error-1](https://user-images.githubusercontent.com/21316370/224527782-c77ee14e-74f0-415b-9f80-f28810682b7f.PNG)
Error message (attached) displays

### Expected results

File should slice successfully.
[Base.zip](https://github.com/Ultimaker/Cura/files/10950106/Base.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[System Summary.zip](https://github.com/Ultimaker/Cura/files/10950124/System.Summary.zip)

**Comment by MariMakes** [comment]
Hey @cnanc3,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

The new Cura 5.3 contains the fix for this for a number of slicing crashes. 
I was able to slice your model successfully in 5.3 Stable when I dropped the model -0.1 in the buildplate.
I would do that anyways because there seems to be a slight fillet at the bottom that is hard to print. 
![image](https://user-images.githubusercontent.com/40423138/226671499-213ae90a-a392-4a87-a2b7-5d7caaf4df15.png)

Could you test if that's the case for you as well? 
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0

If you still run into a crash, please double-check if you shared the correct file and let us know.
I'll take another look at what is going wrong. 👍
