### ISSUE TITLE
Slicing Error - Countryman

### ISSUE THREAD

**Issue by Grueschnuez** [Ultimaker/Cura#14857]
### Application Version

5.2.1

### Platform

Windows 11

### Printer

Creality Ender 6

### Reproduction steps

I want so slice a STL of https://cults3d.com/de/modell-3d/spiel/mini-coutryman-x-raid
but some error code does report

### Actual results

nothing

### Expected results

finish of slicing

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

https://cults3d.com/de/modell-3d/spiel/mini-coutryman-x-raid

**Comment by MariMakes** [comment]
Hey @Grueschnuez,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

The new Cura 5.3 Stable contains the fix for this for a number of slicing crashes. 
Could you test if that's the case for your model as well? 
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
