### ISSUE TITLE
Error Cura 5.2.2 when slicing

### ISSUE THREAD

**Issue by nikjones** [Ultimaker/Cura#14856]
### Application Version

5.2.2

### Platform

Windows 11

### Printer

Ender 3 v2

### Reproduction steps

1. Loaded mandohelmetcoaster.stl
2. Sliced

### Actual results

Got error message "Slicing failed with unexpected error. Please consider reporting a bug on our issue tracker"

### Expected results

Should slice - same .STL file slices and works on Creality Slicer 4.8

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/10950665/cura.log)
[mandohelmetcoaster.zip](https://github.com/Ultimaker/Cura/files/10950666/mandohelmetcoaster.zip)

**Comment by MariMakes** [comment]
Hey @nikjones,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

The new Cura 5.3 Stable contains the fix for this for a number of slicing crashes. 
Could you test if that's the case for your model as well? 
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0

I was able to slice the STL but probably did not have the settings that you have. 
![image](https://user-images.githubusercontent.com/40423138/226675914-5d2dcc86-8996-4deb-ae3b-88dd1a36a1b8.png)

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
