### ISSUE TITLE
Nie slice większych modeli

### ISSUE THREAD

**Issue by Karal11** [Ultimaker/Cura#14887]
### Application Version

5.3.0

### Platform

Windows 11

### Printer

Creality Ender 3 pro

### Reproduction steps

https://user-images.githubusercontent.com/127898306/225137771-5107dd40-55b6-4fed-bca9-ad6606e6d1db.mp4

### Actual results

Projekt się nie kroi 

### Expected results

Projekt powinien się pokroić 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Wymiary
Z 150mm
Y ok 125mm
X ok 56mm

**Comment by MariMakes** [comment]
Hey @Karal11,

Welcome to the Ultimaker Cura Github 🚀 
Thanks for your report 👍

This mesh seems faulty, you can see it from all the parts of the model that are not yellow. 

Have you tried doing a quick mesh fix with the Meshtools Plugin? 
You can get it here: https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/MeshTools

If that doesn't fix it you can try a more elaborate mesh fixer like https://myminifactory.github.io/Fast-Quadric-Mesh-Simplification/, or https://www.nanodlp.com/repair-3d-stl-file/.
Or you can use the "Make Solid" feature in AutoDesk MeshMixer. https://meshmixer.com/download.html

To me, it doesn't seem like a bug in Ultimaker Cura, since the mesh is faulty and Cura is not built to alter meshes in this way, that's what CAD software is for.  I'll close this issue, I hope you understand.
