### ISSUE TITLE
wouldn't slice

### ISSUE THREAD

**Issue by Aquaman7** [Ultimaker/Cura#14899]
### Application Version

5.3

### Platform

windows 10

### Printer

sovol sv03

### Reproduction steps

tried to slice a helmet

### Actual results

crashed

### Expected results

finished sliced file

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

[Batman Arkham Knight Helmet_3D Model.zip](https://github.com/Ultimaker/Cura/files/10986183/Batman.Arkham.Knight.Helmet_3D.Model.zip)

**Comment by MariMakes** [comment]
Hey @Aquaman7,

Welcome to the UltiMaker Cura Github 🚀 
Thanks for your report 👍

The new Cura 5.3 Stable contains the fix for this for a number of slicing crashes. 
Could you test if that's the case for your model as well? 
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0

![image](https://user-images.githubusercontent.com/40423138/226683873-9961e6be-7ca8-4bdb-ba97-42ead9ee22d3.png)

If that's not it, I'll need a little bit more information from you, because I can slice the model with the default settings. 
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
