### ISSUE TITLE
Slicing failed

### ISSUE THREAD

**Issue by pcairic** [Ultimaker/Cura#14898]
### Application Version

5.2.2

### Platform

Linux Mint

### Printer

Creality Ender 3 Pro

### Reproduction steps

Layer .28
Adaptive layers
Changed support normal to tree

### Actual results

Error message "Slicing Failed" "Slicing failed with an unexpected error. Please consider reporting a bug on our issue tracker."

### Expected results

A normal preview...

[Project.zip](https://github.com/Ultimaker/Cura/files/10985839/Project.zip)
[stderr.log](https://github.com/Ultimaker/Cura/files/10985873/stderr.log)

[35m2023-03-15 21:32:38,690[0m - [36mDEBUG[0m - [37m[EngineOutputThread] UM.Backend.Backend._backendLog [115]: [Backend] [2023-03-15 21:32:38.689] [warning] Failing to discretize parabola! Must add an apex or one of the endpoints.[0m

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

Instructions for Log file seem outdated. There is no cura/5.2.2 folder. A 5.2 folder contains log files that are 4 months old.

**Comment by MariMakes** [comment]
Hey @pcairic,

Welcome to the UltiMaker Cura Github 🚀 
Thanks for your report 👍

The new Cura 5.3 contains the fix for this for a number of slicing crashes. 
I was able to slice your model successfully in 5.3 Stable.
![image](https://user-images.githubusercontent.com/40423138/226682474-b64aa187-b430-4054-8476-b1556665f2c1.png)

Could you test if that's the case for you as well? 
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0

If you still run into a crash, please double-check if you shared the correct file and let us know.
I'll take another look at what is going wrong. 👍
