### ISSUE TITLE
перестала осуществлять нарезку на слои при изменении размера, раньше все было впорядке,что произошло

### ISSUE THREAD

**Issue by Katerina2323** [Ultimaker/Cura#14890]
### Application Version

5,3,0

### Platform

windows

### Printer

ender

### Reproduction steps

пользуюсь как обычно не режет на слои 
резко произошел глюк

### Actual results

модель всегда работала печаталась

### Expected results

нарезка а слои и запуск в печать
делаю все тоже самое что и всегда
результат непредвиденная ошибка не режет на слои не запускаю в печать

модель состоит из 3 деталей раньше глючила одна теперь - уже 2
с таким успехом предстанет работать вовсе 5,3,0 версия

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

мне необходимо решение проблемы

**Comment by MariMakes** [comment]
Hey @Katerina2323,

Welcome to the Ultimaker Cura Github 🚀 
I cannot speak Russian. but I can try to help you 😄 

The new Cura 5.3 contains the fix for this for a number of slicing crashes. 
That doesn't seem to be applicable in your case. Can you try some of the more common workarounds which is rotating the model with 90 degrees or slightly resizing it. It helps with rounding errors. 

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
