### ISSUE TITLE
Failed to slice

### ISSUE THREAD

**Issue by 0OJamesO0** [Ultimaker/Cura#14893]
### Application Version

5.1

### Platform

Windows 11 Home

### Printer

Lotmaxx Shark V2

### Reproduction steps

I scaled down all models and hit slice just as I have before, but this time nothing seemed to be happening as if it were hung up, and timing out. So, I hit cancel, then tried to slice again. The slice indicator went a short distance maybe a centimeter if that, and slicing failed with the following error message: "Slicing failed with an unexpected error. Please consider reporting a bug on our issue tracker."

### Actual results

![Screenshot (3)](https://user-images.githubusercontent.com/126958915/225395469-ca366c64-21c9-4e04-b45b-bd9579752f6f.png)

![Screenshot (4)](https://user-images.githubusercontent.com/126958915/225395620-7da90c6d-147c-47d0-9e39-c6011214c9c8.png)

![Screenshot (1)](https://user-images.githubusercontent.com/126958915/225395651-5213bdd6-00b8-4404-b32f-e9d03f6e6aab.png)

[LS_ShelbyGT500Car saved for bug report - Copy.zip](https://github.com/Ultimaker/Cura/files/10983063/LS_ShelbyGT500Car.saved.for.bug.report.-.Copy.zip)

[cura.log - Copy.1.txt](https://github.com/Ultimaker/Cura/files/10983216/cura.log.-.Copy.1.txt)

### Expected results

The model should have been sliced and ready to be printed.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

closed and reopened Cura and still no slice in this project. Slicing still works fine with other projects.

After experimenting with it just a bit, I learned that if I turn on spiralize outer contour it will slice. When I turn it back off, I get the error again.
If I select either of my two dual nozzles it will slice but one of them must be selected to spiralize though. If both are unchecked, it gets an error.

**Comment by MariMakes** [comment]
Hey @0OJamesO0,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

I took a look at your model in our latest Cura 5.3 that has a lot of fixes for crashes. This mesh for the wheels seems faulty. 
They consist out of four submeshes that have incorrect Normals. 

![image](https://user-images.githubusercontent.com/40423138/229461542-ac5c33b1-55f7-4562-b064-b76834c76670.png)

I was able to do a fix with the Meshtools Plugin.
You can get it here: https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/MeshTools
To me, it doesn't seem like a bug in Ultimaker Cura, since the mesh is faulty and Cura is not built to alter meshes in this way, that's what CAD software is for.
