### ISSUE TITLE
Slicing Failed

### ISSUE THREAD

**Issue by kevinater2007** [Ultimaker/Cura#14918]
### Application Version

5.1.0

### Platform

Windows 10

### Printer

Ultimaker S5

### Reproduction steps

Tried to slice a file. This file was previously made so I am at a loss of why it won't slice again correctly?
![Error](https://user-images.githubusercontent.com/128097032/225754730-88ff6dd2-8a0f-4b3c-9a46-97fe1ec8a944.JPG)
![Issue](https://user-images.githubusercontent.com/128097032/225755126-79fbeb7c-52c7-4d61-b3cd-4dd4c189db00.JPG)

### Actual results

Error code

### Expected results

This should slice!
[UMS5_Corner Cap - Mighty G - Stern REV 1.zip](https://github.com/Ultimaker/Cura/files/10995945/UMS5_Corner.Cap.-.Mighty.G.-.Stern.REV.1.zip)

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

It isn't slicing. Not sure what else to say...

**Comment by MariMakes** [comment]
Hey @kevinater2007,

Welcome to the UltiMaker Cura Github 🚀 
Thanks for your report 👍

The new Cura 5.3 contains the fix for this for a number of slicing crashes. 
I was able to slice your model successfully in 5.3 Stable.
![image](https://user-images.githubusercontent.com/40423138/226687307-e9642825-c45e-4e8a-a052-d63b9c70af8f.png)

Could you test if that's the case for you as well? 
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0

If you still run into a crash, please double-check if you shared the correct file and let us know.
I'll take another look at what is going wrong. 👍
