### ISSUE TITLE
failed to slice

### ISSUE THREAD

**Issue by wademartindale** [Ultimaker/Cura#14929]
### Application Version

5.3.0

### Platform

macbook pro

### Printer

ultimaker 3 extended 

### Reproduction steps

put stl file in program and it fails to slice

### Actual results

processes 3/4 the way then says failed to slice

### Expected results

print

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

[1 Deadpool.zip](https://github.com/Ultimaker/Cura/files/11003333/1.Deadpool.zip)

**Comment by MariMakes** [comment]
Hey @wademartindale,

Welcome to the UltiMaker Cura Github 🚀 
Thanks for your report 👍

The new Cura 5.3 Stable contains the fix for this for a number of slicing crashes. 
Could you test if that's the case for your model as well? 
Because I was able to slice it with the Ultimaker 3 Default settings
![image](https://user-images.githubusercontent.com/40423138/226689440-3bcdf90c-0d88-4529-b3d5-1f66e1acc2dd.png)

You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
