### ISSUE TITLE
Unable To Slice using Tree Support

### ISSUE THREAD

**Issue by Lakanya** [Ultimaker/Cura#14932]
### Application Version

5.3.0

### Platform

Windows 11

### Printer

Wanhao Duplicator D12 230

### Reproduction steps

I tried slicing a 3d model I put in Cura but it won't slice until I select Normal support instead of Tree.

### Actual results

It spits this error : 
![Error](https://user-images.githubusercontent.com/107959984/225988398-d4c2eb48-3183-4af2-a4da-669cf85cc594.png)

### Expected results

It should slice and give me estimations and a gcode file.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[ErrorSlicing.zip](https://github.com/Ultimaker/Cura/files/11004535/ErrorSlicing.zip)

**Comment by MariMakes** [comment]
Hey @Lakanya,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

Wow! That looks like a really difficult model. 
Are you sure it's the correct model? This mesh seems faulty.
Have you tried doing a quick mesh fix with the Meshtools Plugin? 
You can get it here: https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/MeshTools

If that doesn't fix it you can try a more elaborate mesh fixer like https://myminifactory.github.io/Fast-Quadric-Mesh-Simplification/, or https://www.nanodlp.com/repair-3d-stl-file/.
Or you can use the "Make Solid" feature in AutoDesk MeshMixer. https://meshmixer.com/download.html

To me, it doesn't seem like a bug in Ultimaker Cura, since the mesh is faulty and Cura is not built to alter meshes in this way, that's what CAD software is for.
