### ISSUE TITLE
Slicing large file

### ISSUE THREAD

**Issue by Rosinstein** [Ultimaker/Cura#14936]
### Application Version

5.3.0-alpha+xmas

### Platform

Windows 11 Pro

### Printer

CR10-S

### Reproduction steps

Slice file

### Actual results

Failed

### Expected results

Sliced Gcode

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[CFFFP_Assembly.zip](https://github.com/Ultimaker/Cura/files/11005443/CFFFP_Assembly.zip)

**Comment by MariMakes** [comment]
HEy @Rosinstein,

Thanks for your report 👍

This mesh seems faulty
Have you tried doing a quick mesh fix with the Meshtools Plugin? 
You can get it here: https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/MeshTools

If that doesn't fix it you can try a more elaborate mesh fixer like https://myminifactory.github.io/Fast-Quadric-Mesh-Simplification/, or https://www.nanodlp.com/repair-3d-stl-file/.
Or you can use the "Make Solid" feature in AutoDesk MeshMixer. https://meshmixer.com/download.html

The new Cura 5.3 contains the fix for this for a number of slicing crashes. 
I was able to slice your model successfully in 5.3 Stable.
![image](https://user-images.githubusercontent.com/40423138/229490094-a96166c5-fa5a-4ba7-b694-f17ec9857fd9.png)
[It's a really big file, so I saved the Gcode for you here. ](https://we.tl/t-YkWAetarXl) 

Could you test if that's the case for you as well? 
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0

If you still run into a crash, please double-check if you shared the correct file and let us know.
I'll take another look at what is going wrong. 👍
