### ISSUE TITLE
Tree Support Slicing fails with model

### ISSUE THREAD

**Issue by tbnorris** [Ultimaker/Cura#14938]
### Application Version

5.3.0

### Platform

Pop!_OS 22.04 LTS

### Printer

Ender 3 V2

### Reproduction steps

1. Setup: Download https://www.printables.com/model/152248-ender-3-v2-squash-ball-feet normal 0.2mm PLA settings, select Tree supports with 0.4mm nozzle.
2. Print any of the v2_ender3v2_*_raised.stl feet besides v2_ender3v2_left_pcu_foot_raised.stl with tree supports Slice success
3.  Remove all elements and place v2_ender3v2_left_pcu_foot_raised.stl and tree supports Slice.  This reports an error.

### Actual results

Fails to slice when Tree support selected.
There could be something wrong with this specific stl file, but I managed to slice and print 2 of the "normal raised foot v2" and one of the "right raised foot v2" with tree supports.  I also had one attempt (but it later failed for adhesion issues) where I sliced one normal, left, and right raised foot all at the same time.  That set sliced without error, as well.

### Expected results

Successfully slices model with tree supports.  This model is very much a mirror of right model and it works properly.
left model does slice when normal supports are selected.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

![image](https://user-images.githubusercontent.com/25255921/226056941-e7b7a477-d428-4bdc-b434-832968beabf7.png)
[cura.log](https://github.com/Ultimaker/Cura/files/11006543/cura.log)
[badslicingleftfoot.zip](https://github.com/Ultimaker/Cura/files/11006548/badslicingleftfoot.zip)

**Comment by MariMakes** [comment]
Hey @tbnorris,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

The new Cura 5.3 contains the fix for this for a number of slicing crashes. 
I was able to slice your model successfully in 5.3 Stable.
![image](https://user-images.githubusercontent.com/40423138/229503606-2ba7b4fa-5331-4f2e-afc4-e2b0a68f478c.png)


Could you test if that's the case for you as well? 
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0

If you still run into a crash, please double-check if you shared the correct file and let us know.
I'll take another look at what is going wrong. 👍

**Comment by tbnorris** [comment]
I can verify that 5.3.0 on Windows 11 seems to be working but not on the reported platform the non modern Linux AppImage of 5.3.0 does not work.  I downloaded it anew and re-integrated it and it still created the same error.

**Comment by MariMakes** [comment]
Hey @tbnorris,

I recognize this line in your log: Engine process is killed. Received return code -11
That seems to be Linux Specific. I'll have one of our Linux Developers take a look.
Fingers crossed 🤞

**Comment by nallath** [comment]
I've just tried this with 5.4 on linux and it sliced. Could you try again?
