### ISSUE TITLE
Slicing fails in v5.3.0 for a particular model.

### ISSUE THREAD

**Issue by slabua** [Ultimaker/Cura#14944]
### Application Version

5.3.0

### Platform

Fedora 37

### Printer

Ender 3 v2

### Reproduction steps

I simply imported the model and tried to slice it.

### Actual results

Slicing failed.

### Expected results

Slicing should complete successfully as it does in v5.2.1.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[Cura530SlicingBug.zip](https://github.com/Ultimaker/Cura/files/11008282/Cura530SlicingBug.zip)
[cura.log](https://github.com/Ultimaker/Cura/files/11008284/cura.log)
![Screenshot from 2023-03-18 19-39-44](https://user-images.githubusercontent.com/1002978/226100933-edba758c-7139-4ebf-830b-341ac1385bb2.png)

**Comment by MariMakes** [comment]
Hey @slabua,

Welcome to the UltiMaker Cura Github 🚀 
Thanks for your report 👍

The new Cura 5.3 contains the fix for this for a number of slicing crashes. 
I was able to slice your model successfully in 5.3 Stable.
![image](https://user-images.githubusercontent.com/40423138/226855311-6a0da3e1-a4bd-4064-8d8d-42b2b4b3aba4.png)

Could you test if that's the case for you as well? 
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0

If you still run into a crash, please double-check if you shared the correct file and let us know.
I'll take another look at what is going wrong. 👍

**Comment by slabua** [comment]
Hi @MariMakes thanks for your reply.
I was already on 5.3.0 stable, I tried to change the support setting to trees as in your screenshot but it still fails.

**Comment by MariMakes** [comment]
Hey @slabua,

I took another look and I see the following: 
Engine process is killed. Received return code -11

That also seems to be reported here: https://github.com/Ultimaker/Cura/issues/14938
I'll be closing this issue as a duplicate but you can follow the progress here:  https://github.com/Ultimaker/Cura/issues/14938
