### ISSUE TITLE
[CURA_53_RENDERING_ISSUE][SUNLU_S8_PRO]

### ISSUE THREAD

**Issue by g33ky00** [Ultimaker/Cura#14947]
### Application Version

5.3

### Platform

Windows 11

### Printer

Custom Profile - Sunlu S8 Pro

### Reproduction steps

1. Moved & adjusted model
2. Adjusted values (took the same as usual that fits for my printer)
3. Launched rendering and crashed

### Actual results

Had a message indicating that rendering failed and been invited to click on the link that moved me here

### Expected results

Correct rendering as usual

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

Nothing special to add but a lot of thanks for your work and help !
[cura.log](https://github.com/Ultimaker/Cura/files/11009610/cura.log)
[CFFFP_Upper_Wood.zip](https://github.com/Ultimaker/Cura/files/11009614/CFFFP_Upper_Wood.zip)

**Comment by MariMakes** [comment]
Hey @g33ky00,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

The new Cura 5.3 contains the fix for this for a number of slicing crashes. 
I was able to slice your model successfully in 5.3 Stable, after reverting some of your changed settings. 
I'm not sure but it might have to do with the support placement. 
![image](https://user-images.githubusercontent.com/40423138/229542446-d9580036-1aa8-4b26-8943-83f5108e2e92.png)

Could you test if that's the case for you as well? 
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0

If you still run into a crash, please double-check if you shared the correct file and let us know.
I'll take another look at what is going wrong. 👍
