### ISSUE TITLE
slicing

### ISSUE THREAD

**Issue by jkarranza** [Ultimaker/Cura#14967]
### Application Version

5.3

### Platform

windows 11

### Printer

ender 3/ v2

### Reproduction steps

1. I open the file for the bismuth dragon by hyp3d
2. The model was scaled to 70% and placed in the center
3. I press the slice button and the model wouldn't slice

### Actual results

The model would not slice

### Expected results

For the model to slice

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[CE3E3V2_The Bismuth Dragon - HYPED 3D.zip](https://github.com/Ultimaker/Cura/files/11013102/CE3E3V2_The.Bismuth.Dragon.-.HYPED.3D.zip)

**Comment by MariMakes** [comment]
Hey @jkarranza,

Welcome to the UltiMaker Cura Github 🚀 
Thanks for your report 👍
A Bimuth Dragon? That sounds so cool 🐉 

The new Cura 5.3 Stable contains the fix for this for a number of slicing crashes. 
Could you test if that's the case for your model as well? 
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0

If that's not it, I'll need a little bit more information from you. 
The gcode you shared is not sufficient. Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
