### ISSUE TITLE
Slicing error

### ISSUE THREAD

**Issue by Creddy23** [Ultimaker/Cura#14975]
### Application Version

5.3

### Platform

Win10

### Printer

FLSUN Super Racer

### Reproduction steps

Added Tab Plus Tabs (extension) to 6 points around the base of this model:  https://www.thingiverse.com/thing:2720237

Re-sliced and generated an error - "slicer engine Stopped
![error](https://user-images.githubusercontent.com/125032887/226400426-954061fd-f50e-43c1-b07c-98ee5e32a751.jpg)

### Actual results

slicing stopped and I tried again - program did not crash.

### Expected results

Model should get sliced
[labyrinth_puzzle_bank_2720237.zip](https://github.com/Ultimaker/Cura/files/11020431/labyrinth_puzzle_bank_2720237.zip)

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[stdout.log](https://github.com/Ultimaker/Cura/files/11020459/stdout.log)
[stderr.log](https://github.com/Ultimaker/Cura/files/11020460/stderr.log)
[cura.log](https://github.com/Ultimaker/Cura/files/11020461/cura.log)

**Comment by Creddy23** [comment]
I re-tested this and it only happens when using Tree Supports - either touching buildplate or everywhere - always fails.  Using normal supports, has no problem.

**Comment by MariMakes** [comment]
Hey @Creddy23,

Welcome to the UltiMaker Cura Github 🚀 
Thanks for your report 👍

The new Cura 5.3 Stable contains the fix for this for a number of slicing crashes. 
Could you test if that's the case for your model as well? 

You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0

![image](https://user-images.githubusercontent.com/40423138/226930609-a8dd81d3-65c5-48a1-a346-2ddc940180ec.png)
When I slice your STL with just the tree supports enabled I'm able to slice it. 

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
