### ISSUE TITLE
Postprocessing a temperature change for Extruder 2

### ISSUE THREAD

**Issue by Robert-AUL** [Ultimaker/Cura#14979]
### Application Version

5.3.0

### Platform

Windows 11

### Printer

Custom pour Tenlog TL D3 V2

### Reproduction steps

Je souhaite créer un post traitement particulier sur l'extrudeur 2, changement de température du filament et du bed au niveau 5 et il est impossible de sélectionner les actions à faire
![CaptureEcran Cura 5 3 0 Bug post traitement](https://user-images.githubusercontent.com/128434597/226489691-c92e0789-06b7-4aa0-a74d-d4cc2e663157.png)

### Actual results

Impossible d'ouvrir le menu pour sélectionner l'action souhaitée

### Expected results

Editer les choix que nous souhaitons faire
Dans mon cas changement de température à la couche 5

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Pas d'info

**Comment by MariMakes** [comment]
Bojour @Robert-AUL,

Je m'excuse, je ne parle pas français mais je pense que je peux vous aider.

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

If you want to introduce a temperature change for your second extruder at layer 5 I would do that like this:
![image](https://user-images.githubusercontent.com/40423138/229511836-c9f65f85-350e-4979-83c9-840a3c66cb1c.png)

Hope this helps.

To me, it doesn't seem like a bug in Ultimaker Cura, since we have a solution in place. 
Would you still like to keep this issue open or do you agree that we can close it?
