### ISSUE TITLE
cura 5.3 gcode error 2

### ISSUE THREAD

**Issue by qwerty8224** [Ultimaker/Cura#14970]
### Application Version

5.3

### Platform

win11

### Printer

Gustom FFF

### Reproduction steps

as always cut the detail.

### Actual results

Bubbles on the model are caused by microscopic movements of the nozzle. It is observed on Ultimaker printers of different versions if you change the number of walls from 2 to 3

### Expected results

Fix ASAP.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

[CFFFP_tronc_modifs_GITHAB.zip](https://github.com/Ultimaker/Cura/files/11017180/CFFFP_tronc_modifs_GITHAB.zip)

**Comment by qwerty8224** [comment]
the problem goes away by increasing (maximum resolution) in Cura

**Comment by orbitalr** [comment]
I had this start trying to remediate some issues I've had with some other prints. 

Custom printer setup (Klipper) running on a machine with buckets of resources. It looked like what happens when you push a board too far with too many gcode commands, moves start skipping and making sounds and appearance like this. 

Ive not tried again yet, I restarted my server hosting klipper and I'll try again. 

I had actually been slowing down the print speed. Image attached was faster then the one on the right. The one of the right has the issue. 

I'd not changed the resolution. I had been changing things like wall ordering, number, combing, but I honestly dont know what caused this. 

![IMG_20230320_113751](https://user-images.githubusercontent.com/114871676/226329623-7b1b18bc-b34c-447d-ba5b-3046fef80d4f.jpg)

**Comment by qwerty8224** [comment]
[орбитал](https://github.com/orbitalr) 
Thank you for showing the problem clearly. Play with the resolution and this problem is clearly visible in the slicer viewer. Do not rush there micro step or micro drop, good luck to you)))

**Comment by orbitalr** [comment]
Ok, thanks, then our issue is not similar. In my example the slicer preview was normal, as expected.

**Comment by qwerty8224** [comment]
Well, if it's okay, then close it.

**Comment by discip** [comment]
@qwerty8224
@MariMakes pointed out exactly what is causing your problem!

**Comment by discip** [comment]
@qwerty8224
@MariMakes pointed out exactly what is causing your problem!

So this can be closed. 😊

**Comment by qwerty8224** [comment]
> @qwerty8224 @MariMakesименно то, что решение вашей проблемы!
> 
> Так что это можно закрыть.😊

Let it be so )))
