### ISSUE TITLE
slicing error

### ISSUE THREAD

**Issue by LucasPanichella** [Ultimaker/Cura#14980]
### Application Version

5.2.2

### Platform

widows 11

### Printer

Hellbot magna se

### Reproduction steps

added 1 item with its parameters and sliced well
then multiplied the same itemsaved the 3mf file
then sliced

### Actual results

during slice error showed

### Expected results

succesfull slice

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[2 mate michelin.zip](https://github.com/Ultimaker/Cura/files/11024002/2.mate.michelin.zip)

**Comment by MariMakes** [comment]
Hey @LucasPanichella,

Welcome to the UltiMaker Cura Github 🚀 
Thanks for your report 👍

The new Cura 5.3 contains the fix for this for a number of slicing crashes. 
I was able to slice your model successfully in 5.3 Stable.
![image](https://user-images.githubusercontent.com/40423138/226932064-cdb48289-88cc-46a1-a070-c824735492c1.png)

Could you test if that's the case for you as well? 
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0

If you still run into a crash, please double-check if you shared the correct file and let us know.
I'll take another look at what is going wrong. 👍
