### ISSUE TITLE
Slicing Bug

### ISSUE THREAD

**Issue by AKlibur** [Ultimaker/Cura#14985]
### Application Version

5.3.0

### Platform

Windows 10

### Printer

Creality Ender 3V2

### Reproduction steps

1) Upload the model in Cura
2) Launch the slice with my standards parameters

### Actual results

Slice bugged around at 60% of the slicing

### Expected results

Should slice the model

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

![Capture d’écran (326)](https://user-images.githubusercontent.com/128495977/226653299-c20b454b-9f07-48ba-8524-a5abac85afca.png)

[CE3E3V2_VHse_BaseA.zip](https://github.com/Ultimaker/Cura/files/11029880/CE3E3V2_VHse_BaseA.zip)

**Comment by MariMakes** [comment]
Hey @AKlibur,

Welcome to the UltiMaker Cura Github 🚀 
Thanks for your report 👍

The new Cura 5.3 Stable contains the fix for this for a number of slicing crashes. 
Could you test if that's the case for your model as well? 
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
