### ISSUE TITLE
Slicing error

### ISSUE THREAD

**Issue by markghostrock** [Ultimaker/Cura#14981]
### Application Version

5.3.0

### Platform

Linux Mint

### Printer

FLSun Q%

### Reproduction steps

Open model in Cura.
Hit "Slice".

### Actual results

Got "Slicing failed with unexpected error"

### Expected results

Model sliced.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/11024209/cura.log)
[Objective.zip](https://github.com/Ultimaker/Cura/files/11024212/Objective.zip)

**Comment by markghostrock** [comment]
Thank you.

**Comment by MariMakes** [comment]
Hey @markghostrock,

Welcome to the UltiMaker Cura Github 🚀 
Thanks for your report 👍

The new Cura 5.3 contains the fix for this for a number of slicing crashes. 
I was able to slice your model successfully in 5.3 Stable.

![image](https://user-images.githubusercontent.com/40423138/226932646-4cb43878-8990-423a-86d1-65fe49c54a18.png)

Could you test if that's the case for you as well? 
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0

If you still run into a crash, please double-check if you shared the correct file and let us know.
I'll take another look at what is going wrong. 👍
