### ISSUE TITLE
Cura 5.3.0 Installs but won't open on Mac 10.15.7

### ISSUE THREAD

**Issue by Katmandieux** [Ultimaker/Cura#14999]
### Application Version

5.3.0

### Platform

Mac OS X 10.15.7

### Printer

Cura will not open so no printer installed yet

### Reproduction steps

-- Downloaded stable release Cura 5.3.0.
-- Opened DMG and added results to Applications.
-- Clicked to open Cura and gave permission to run app.

### Actual results

Absolutely nothing happens.

### Expected results

Cura 5.3.0 should open.

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

dalejones@22012-MacBook-Pro ~ % $USER/Library/Application Support/cura/<Cura version>/cura.log
zsh: no such file or directory: Cura
dalejones@22012-MacBook-Pro ~ %

**Comment by MariMakes** [comment]
Hey @Katmandieux,

Welcome to the UltiMaker Cura Github 🚀 

I'm sorry, Cura 5.3 supports Mac OSX 11 Big Sur or higher.
This is because the tools that we use to create Cura builds no longer support these versions of Mac OSx. 

You can learn more about which version is compatible with your OS here
https://support.makerbot.com/s/article/1667337917781

To me, it doesn't seem like a bug in Ultimaker Cura.
I'll be closing this issue. I hope you understand.
