### ISSUE TITLE
Does not slice large file - is idling/not using ressources

### ISSUE THREAD

**Issue by carhifitrier** [Ultimaker/Cura#14990]
### Application Version

5.3.0 (also with xmas alpha)

### Platform

Windows 11

### Printer

Tronxy X5SA (modified profile at speeds etc)

### Reproduction steps

Insert a large File, litho in form of en egg, 912MB
Put a support blocker
hit "slice"

### Actual results

Cura displays "slicing", but does nothing but take a bit more RAM. No reasonable CPU or SSD load, especially slicing engine process does not take any more than a very little RAM. The progress bar does nothing, even after several hours. I left it overnight last week, but same result (or rather: no result)
Got this problem with several of similar files, but some slice - take their time, but slice.

I can´t post a project file at this time, as it´s involving people who i want to give the result as a gift and cannot ask for permission. BTW, its 912MB ;)

### Expected results

Slice the file as it´s pretending it does.

### Checklist of files to include

- [x] Log file
- [ ] Project file

### Additional information & file uploads

<img width="1909" alt="Screenshot 2023-03-22 01 01 44" src="https://user-images.githubusercontent.com/42651956/226768896-86cf8d67-1a70-440e-9287-e9bdd4e2c79e.png">
<img width="1906" alt="Screenshot 2023-03-22 01 04 33" src="https://user-images.githubusercontent.com/42651956/226768913-5ae2e2db-ba92-42c8-a78e-b6e89137bc5b.png">
[cura.log](https://github.com/Ultimaker/Cura/files/11035047/cura.log)

Edit: I just saw - after about 15 minutes, it freed up about 5GB of RAM, but still doing "nothing"
Edit 2: about an hour "slicing", it freed up RAM, now using about 700MB only, console host 0,2, sclicing engine 0,2MB

**Comment by MariMakes** [comment]
Hey @carhifitrier,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

What you are describing looks like a slicing error, but one where the message disappeared. 
The new Cura 5.3 contains the fix for this for several slicing crashes, but it seems like you already tried this.

In my experience, three things can trigger a slicing error.
1. A combination of settings. You seem to have a lot of settings changed. Can you try to slice your model with the default settings? 
2. A broken mesh.  Have you tried doing a quick mesh fix with the Meshtools Plugin? You can get it here: https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/MeshTools
3. Location on the buildplate. You can have some bad luck with rounding based on the position of your model. Can you move the model away from the center of the buildplate and rotate it 90 degrees?

If it's not on this list I can't help you with troubleshooting without the project file. 
Can you let us know if your answer is in the list?
