### ISSUE TITLE
Slicing Crash

### ISSUE THREAD

**Issue by Volker1301** [Ultimaker/Cura#14994]
### Application Version

5.2.2

### Platform

Windows 10

### Printer

Anycubic Mega X

### Reproduction steps

Ein Freecad projeckt in eine Obj-Datei abgespeichert.
Cura gestartet.
Obj-Datei aufgerufen und in Cura übernommen.
Vorschau korreckt!

### Actual results

Versucht zu slicing und das slicing endetet nach einer weile mit der Fehlermeldung "unerwarteter Fehler"

### Expected results

Projekt auf SD -Karte nach dem Slicing speichern.
[cura.log](https://github.com/Ultimaker/Cura/files/11037166/cura.log)
![Nachher](https://user-images.githubusercontent.com/128575066/226823478-ecb4e52a-431a-409f-b953-707ed004e47e.PNG)
![Vorher](https://user-images.githubusercontent.com/128575066/226823484-4f789d48-eab2-43dc-be90-1c3e758d8d8e.PNG)
[cura.log](https://github.com/Ultimaker/Cura/files/11037191/cura.log)
![Nachher](https://user-images.githubusercontent.com/128575066/226824005-dacc615f-5061-4e77-8176-7584f91d745f.PNG)

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[Uploading cura.log…]()

**Comment by MariMakes** [comment]
Hey @Volker1301,

Entschuldigung, dass es nicht auf Deutsch ist, aber das könnte helfen.

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

The new Cura 5.3 Stable contains the fix for this for a number of slicing crashes. 
Could you test if that's the case for your model as well? 
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
