### ISSUE TITLE
Slicing failed

### ISSUE THREAD

**Issue by RenatoMaterializa** [Ultimaker/Cura#15010]
### Application Version

5.3.0

### Platform

Windows 10

### Printer

Custom FFF printer (Creatbot F430)

### Reproduction steps

Moved the part to a different orientation and tried to slice, it was slicing fine before I changed the orientation

### Actual results

the process bar starts to increase but the is a error
![image](https://user-images.githubusercontent.com/128747731/227345436-c987661b-f53f-4bfb-8e2a-7144e0e262e9.png)

### Expected results

the sliced part

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

The file is too big

https://drive.google.com/file/d/1pQyC41LEjERZeGRr6WD2TDK39IFQsX2m/view?usp=share_link

**Comment by MariMakes** [comment]
Hey @RenatoMaterializa,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

This mesh seems faulty. You can see it in the clear discolorations in the prepare window. 

![image](https://user-images.githubusercontent.com/40423138/229786012-33488223-69a9-4ab7-b77a-f004613a9d7f.png)


Have you tried doing a quick mesh fix with the Meshtools Plugin? 
You can get it here: https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/MeshTools

If that doesn't fix it you can try a more elaborate mesh fixer like https://myminifactory.github.io/Fast-Quadric-Mesh-Simplification/, or https://www.nanodlp.com/repair-3d-stl-file/.
Or you can use the "Make Solid" feature in AutoDesk MeshMixer. https://meshmixer.com/download.html

To me, it doesn't seem like a bug in Ultimaker Cura, since the mesh is faulty and Cura is not built to alter meshes in this way, that's what CAD software is for.

I'll close the issue, I hope you understand.
