### ISSUE TITLE
Ironing Ignores Small Spaces

### ISSUE THREAD

**Issue by Splunkon** [Ultimaker/Cura#15012]
### Application Version

5.3.0

### Platform

macOS Ventura 13.2.1

### Printer

Creality ender 3

### Reproduction steps

1. Turned on ironing everywhere
2. Noticed that a small space was not ironed

### Actual results

There was a small space that was not ironed but everything else was.
![IMG_4075F976460A-1](https://user-images.githubusercontent.com/110101421/227363379-fe64e117-c074-4722-96df-69e3e52cf2c2.jpeg)

(The picture shows the small space that wasn't ironed)

### Expected results

The small space should have been ironed.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/11056344/cura.log)
[CE3E3V2_Best Dad Ever Keychain.3mf.zip](https://github.com/Ultimaker/Cura/files/11056345/CE3E3V2_Best.Dad.Ever.Keychain.3mf.zip)

**Comment by MariMakes** [comment]
Hey @Splunkon.

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

Do I understand correctly that the part inside of the A is not ironed? 
Because if I check in Cura it seems to be the case: 
![image](https://user-images.githubusercontent.com/40423138/229796702-9821d5e5-f5e4-4108-b8ea-33a7e524df59.png)

Perhaps you are experiencing some compounding problems due to under-extrusion because of a lot of start and stops in a  small area. 
Can you try if any of the following settings will help with the under extrusion inside of the A? 
1. Ironing Inset
2. Top Skin Expand Distance
3. Skin Edge Support Layers
 
![image](https://user-images.githubusercontent.com/40423138/229797459-817d1bfd-cc8c-4039-af07-fa1682a74f88.png)
