### ISSUE TITLE
STL bodies all stack on top of each-other in Cura 5.3

### ISSUE THREAD

**Issue by MTL813** [Ultimaker/Cura#15024]
### Application Version

5.3

### Platform

Windows 11

### Printer

Creality Ender 3-Pro

### Reproduction steps

When I have multiple STL files that I drop / open on the same Cura "prepare/preview" mode (I 3D print cutters so the 3D bodies aren't that big), all the bodies stack on top of eachother when I drag and drop these STL bodies into Cura for my Ender 3-pro.

![2023-03-24](https://user-images.githubusercontent.com/128826770/227569806-fbd57161-6807-4686-b40b-c38e39d9c19d.png)

### Actual results

Now I have to manually move each of the STL bodies to a proper spaced distance and placement on the Cura view for the Ender 3-pro "prepare/preview" view.

![2023-03-24 (1)](https://user-images.githubusercontent.com/128826770/227570729-3f62f869-3937-474f-b5bc-98fb080e56ea.png)
![2023-03-24 (2)](https://user-images.githubusercontent.com/128826770/227570743-90c45d48-eca0-4b6c-9b8c-866d4006b18d.png)
![2023-03-24 (3)](https://user-images.githubusercontent.com/128826770/227570756-2c039bd3-fec3-42fa-9c17-76842576c612.png)

### Expected results

In all the other Cura editions I had 4.13, 5.1 and 5.2....when you add multiple STL files/bodies into the "prepare/preview" view, Cura immediately places each 3D body separately, on the space provided in the "prepare/preview" screen of the printer type selected (mine is the Creality Ender 3-pro).  

**See attached image - from version Cura 5.1 -- all the STL bodies when dropped / opened in this Prepare/Preview area are immediately placed separately, and spaced separately for maximum efficient use of the 3D print area space!  Currently in Cura 5.3...manually moving and placing each of these STL bodies is not efficient!

If there is not enough space on the Prepare/Preview - print area space for the printer selected, Cura use to automatically show it outside of the prepare/preview area, so that you can just delete it.

Please fix this feature?!  It's very cumbersome to have to manually move each and every STL body and space them equally.

![2023-03-24 (4)](https://user-images.githubusercontent.com/128826770/227571615-6f95c4a2-610a-4fe5-a04e-80074dce3dae.png)

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

Please see all the above comments & attached screenshots

**Comment by teafusion** [comment]
For a quick fix you can use CTRL+R or right click menu "Arrange All Models" for automatic arrange, that works well.

For a test I imported three .stl files at once and they were partially overlapping, haven't detected such prior to Cura 5.3.

**Comment by MTL813** [comment]
> For a quick fix you can use CTRL+R or right click menu "Arrange All Models" for automatic arrange, that works well.
> 
> For a test I imported three .stl files at once and they were partially overlapping, haven't detected such prior to Cura 5.3.

Thanks @teafusion!  The "CTRL+R" works well for the interim.  But it would be nice for Cura to work automatically to space these STL. files out as it did before, prior to Cura 5.3!

**Comment by PhilipW00** [comment]
I have seen this behavior plus if you drag and drop a model onto the build area it will "arrange" them by moving one out of the area all together or stacking them onto each other. This also happens if you use plugins like TAB Plus or Custom Supports, it will place the tab where you click briefly and then move the model and tab apart so that they are not colliding, sometimes forcing the model out of the build area.

**Comment by teafusion** [comment]
Thanks PhilipW00 for the heads up. Now that you said it, I started to doubt my perception of the stacking while loading many objects at once and think that it has been like that, maybe forever, definitely not a new thing, but perhaps gotten used to it, so that I don't even think about it. For me CTRL+R is in frequent use anyway and I don't depend on auto arrange while loading at all, but often arrange things even manually to my preferred order and alignment and sometimes may shave some minutes off of the printing time.

Some larger objects or bigger number of any size of objects easily colliding and some pushed out of the plate even when they fit nicely on the plate arranged manually can be frustrating at times. Sometimes you need even MeshTools to fix the model normals and/or reset the origin to the center of the mesh to make the automatic arrangement work properly. Wish there was a better algorithm for the auto arrangement or at least proper alignment tools to arrange the objects at will to their optimal positions.

Personally I've never used TAB Plus, just didn't figure out the proper use of that or Custom Supports, for which I've never found a use case myself, standard supports have been always enough.

**Comment by csterlin** [comment]
FWIW, I observed the stacking of multiple objects on the bed, then removed, completely, 5.3 from my computer (Win11), then reinstalled it and this behavior stopped. I have not repopulated the marketplace widgets yet but they may still be there from earlier (5.2.1, 5.3A) and have not checked this. Testing continues...

**Comment by fieldOfView** [comment]
Do you know about the option in the General preferences in Cura to "Ensure models are kept apart"? @csterlin, it sounds like you had that turned off before, and now that you have reisnatlled Cura (removing your configuration), the option is enabled again.

**Comment by csterlin** [comment]
Thank you for the information. I am aware of this option but didn't
consider it before reinstalling it, assuming a new bug had shown up. I
actually reinstalled to check out Ctrl-R, of which I was unaware, which
works as advertised, and found my supposed "bug" gone. You gave an
excellent analysis of my issue, and Thanks Again.
Chuck Sterling

**Comment by PhilipW00** [comment]
I have the option checked "Ensure Models are Kept Apart" I am assuming it's that option that is causing things to move off the build plate when I drop another model down or try to add TABs, 
If I uncheck the option everything stacks, if I check the option things move off the plate.
