### ISSUE TITLE
Fail to slice after changing project content

### ISSUE THREAD

**Issue by Ananiaskye** [Ultimaker/Cura#15029]
### Application Version

5.3.0

### Platform

Windows 10 Home

### Printer

Geeetech Mizar_S

### Reproduction steps

Sliced a project - exported G code to print (snake body)- Success.
Saved as project. 
Added 2 more objects (snake top head and rattle)
Adjusted print speed from 50 to 45mms
Adjusted print temp from 220 to 217
Removed some temps I previously enforced
Saved project
Saved new print setting profile - with new name (FlexiPla+_02)
Remove original STL ( already printed snake body)
Slice - Fail
Slice -fail

And here we are.

### Actual results

The project refuses to save as Gcode. 
![Screenshot 2023-03-25 094923](https://user-images.githubusercontent.com/104271546/227731092-9891ef33-320b-4936-8119-90c421c86964.png)

### Expected results

Result in Gcode file to save. 
Here is a copy of successful project before I made the changes.
https://www.3dprintlog.com/prints/157759  <- you should be able to see it

Project files before and after the error also attached in comments. 
Cura log included.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/11069491/cura.log)
[GMLYngRattleBody_precrash.zip](https://github.com/Ultimaker/Cura/files/11069493/GMLYngRattleBody_precrash.zip)
[YngRattleBody_postSliceFail.zip](https://github.com/Ultimaker/Cura/files/11069495/YngRattleBody_postSliceFail.zip)

I hope this helps, thanks for your work!

**Comment by MariMakes** [comment]
Hey @Ananiaskye,

Thanks for your report 👍
Sorry, it took us a while to get back to you 😞 

The new Cura 5.3 contains the fix for this for a number of slicing crashes. 
I was able to slice your model successfully in 5.3 Stable.
![image](https://user-images.githubusercontent.com/40423138/230073753-a6aea51b-cbca-483a-a6fe-b6e38d3c61ae.png)

Could you test if that's the case for you as well? 
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0

If you still run into a crash, please double-check if you shared the correct file and let us know.
I'll take another look at what is going wrong. 👍

**Comment by Ananiaskye** [comment]
I was able to slice and print the model as well. 
I have not experienced this type of slicing error since but I now save my work more often. Thank you!

**Comment by Ananiaskye** [comment]
This is closed.

**Comment by MariMakes** [comment]
Glad to hear your were able to slice and print.
I'll close the issue 👍
