### ISSUE TITLE
'scattered rectilinear' or other randomised infill option

### ISSUE THREAD

**Issue by nirurin** [Ultimaker/Cura#15033]
### Is your feature request related to a problem?

Check out 'scattered rectilinear' infill on SuperSlicer. Or the original version that was made back in 2019 by someone for Slic3r (it's tthe same code that the dev used to add to superslicer). - https://imgur.com/a/9IkDakc

I do a lot of translucent projects, that have LEDs shining through them. Normal infill is pretty bad because you can easily see the patterns through the material. But printing solid isn't always an option as it will block too much light and be a lot heavier (and more expensive). 

### Describe the solution you'd like

A randomised / scattered infill option. 

### Describe alternatives you've considered

There aren't any that I know of. 

### Affected users and/or printers

Everyone who prints translucent materials.

**Comment by MariMakes** [comment]
Hey @nirurin,

Thanks for your report 👍
Sorry, it took us a while to get back to you 😞 

I'm having some trouble understanding what you are requesting. I googled for it and the only things I found were these pictures:
![image](https://github.com/Ultimaker/Cura/assets/40423138/536a7259-8234-46f1-a1cc-7a17d4c2dbbb)
![image](https://github.com/Ultimaker/Cura/assets/40423138/8ac0ee6a-8dc2-46c0-b855-3d16aae81fd2)

Under these links 
https://www.printables.com/model/143776-dimmable-led-softbox
https://hackaday.com/2021/05/11/3d-printed-desiccant-container-exploits-infill/

Are you looking for a random infill? 
Have you considered using Spagethi infill? I that people use it for that purpose. It will print the infill every so often, so that it will end up in the model in a chaotic way. But it was removed in 4.7.0, so [you can download 4.6 here. ](https://github.com/Ultimaker/Cura/releases/tag/4.6.2)
