### ISSUE TITLE
Slicing a 3d model

### ISSUE THREAD

**Issue by Notorius2big** [Ultimaker/Cura#15049]
### Application Version

5.2.2

### Platform

windows 10

### Printer

GEEETECH A30

### Reproduction steps

1 loaded a STI file.
2. Try to slice the model
3. Failed with an unexpected error.

### Actual results

![afbeelding](https://user-images.githubusercontent.com/129003962/227800943-34577fd9-9305-42c8-98d2-9c599ee57b87.png)
error message

### Expected results

The slicing should complete  and the print command could be available.

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/11072876/cura.log)

**Comment by MariMakes** [comment]
Hey @Notorius2big,

Welcome to the UltiMaker Cura Github 🚀 
Thanks for your report 👍

The new Cura 5.3 Stable contains the fix for this for a number of slicing crashes. 
Could you test if that's the case for your model as well? 
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
