### ISSUE TITLE
Cannot Slice Mod

### ISSUE THREAD

**Issue by hitominagumo** [Ultimaker/Cura#15053]
### Application Version

5.2.1

### Platform

Windows

### Printer

AnyCubic Kobra Max

### Reproduction steps

1. Exported into STL. file 
2. Tried to slice
3. Doesn't work

### Actual results

1. "Slicing failed, with unexpected Error, Please report a bug on our issue tracker" note appeared after waiting for the slicing 
2. 

### Expected results

1. The STL. should be sliced
2. To save the sliced STL. into a G.CODE for a 3D print

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

[AKMAX_hopeisland.zip](https://github.com/Ultimaker/Cura/files/11074931/AKMAX_hopeisland.zip)

**Comment by MariMakes** [comment]
Hey @hitominagumo,

Welcome to the UltiMaker Cura Github 🚀 
Thanks for your report 👍

The new Cura 5.3 contains the fix for this for a number of slicing crashes. 
I was able to slice your model successfully in 5.3 Stable.
![image](https://user-images.githubusercontent.com/40423138/230090559-9a2d2cad-bd97-4775-9458-f840be34c541.png)

Could you test if that's the case for you as well? 
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0

If you still run into a crash, please double-check if you shared the correct file and let us know.
I'll take another look at what is going wrong. 👍
