### ISSUE TITLE
cura bug slicing project

### ISSUE THREAD

**Issue by KingotCastle** [Ultimaker/Cura#15068]
### Application Version

5,3,0 beta 2

### Platform

Mac

### Printer

flsun v400

### Reproduction steps

I downloaded the stl files from https://www.thingiverse.com/thing:5316996
the model that fails to slice = Eggshell_9_Hexagonal

### Actual results

fails to slice

### Expected results

get a gcode file to send to 3d printer

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

no extra info

**Comment by MariMakes** [comment]
Hey @KingotCastle,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

![image](https://user-images.githubusercontent.com/40423138/230102460-3a573286-b7ba-4997-86c7-b1040e7bc63f.png)
The new Cura 5.3 Stable contains the fix for this for a number of slicing crashes. 
Could you test if that's the case for your model as well? 
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
