### ISSUE TITLE
bug cura

### ISSUE THREAD

**Issue by jorgelozkov** [Ultimaker/Cura#15060]
### Application Version

5.0.0

### Platform

windows 10

### Printer

creality ender 3

### Reproduction steps

clicked slice and it wouldnt let me slice the file

### Actual results

doesnt let me slice the file

### Expected results

slice the file

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

![slicing problem](https://user-images.githubusercontent.com/129090305/227993812-dacb6dd8-0397-4c75-ae86-960964338f53.PNG)

**Comment by MariMakes** [comment]
Hey @jorgelozkov,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

The new Cura 5.3 Stable contains the fix for this for a number of slicing crashes. 
Could you test if that's the case for your model as well? 
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
