### ISSUE TITLE
Slicing Failed

### ISSUE THREAD

**Issue by Kladrin** [Ultimaker/Cura#15070]
### Application Version

5.2.2

### Platform

Windows 11

### Printer

Ender 3

### Reproduction steps

Uploaded file (__Morr_Temple_Base.stl)
Set "super quality - 0,12", remove tick from "cooling", no supports, build plate "brim"
Click "slice"

### Actual results

Slow loading and then bug report

### Expected results

Complete the slicing

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

![image](https://user-images.githubusercontent.com/542600/228384749-67ead01e-a0c5-474a-a2c3-64a91b71f058.png)

![image](https://user-images.githubusercontent.com/542600/228384700-bc385c54-cefa-45af-a329-543aa5eadb54.png)

**Comment by MariMakes** [comment]
Hey @Kladrin,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

The new Cura 5.3 Stable contains the fix for this for a number of slicing crashes. 
Could you test if that's the case for your model as well? 
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0

Have you tried reverting to the default settings?
Have you tried moving the model away from the center of the buildplate and rotating by 90 degrees?
Can you check if your mesh is faulty with the Meshtools Plugin? You can get it here: https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/MeshTools

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
