### ISSUE TITLE
can't slice the model

### ISSUE THREAD

**Issue by Skilless02** [Ultimaker/Cura#15080]
### Application Version

5.2.2

### Platform

windows 11

### Printer

Flsun SR

### Reproduction steps

import model
slice 

### Actual results

error

### Expected results

correct slicing

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

![image](https://user-images.githubusercontent.com/129325879/228639538-d5a2ee53-a446-443c-8f87-4fe30b557a49.png)
![image](https://user-images.githubusercontent.com/129325879/228639607-e31a5762-a9c0-4070-8a2e-fde6fe1fed0b.png)
[cura.log](https://github.com/Ultimaker/Cura/files/11104503/cura.log)
https://drive.google.com/file/d/14xRoPn_g4xXiCtNQJtqHVd07gdBAb2SK/view?usp=share_link

i also tried to repair the .stl using microsoft 3D builder but nothing changes

**Comment by MariMakes** [comment]
Hey @Skilless02,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 
![image](https://user-images.githubusercontent.com/40423138/230124897-3773e954-fd65-4ccb-86ef-24f01c8dd9ca.png)

This mesh seems faulty, you can see this in the parts that have a different color that the rest. 
Is this model made for 3D printing? 

Here are some things you can try: 
Have you tried doing a quick mesh fix with the Meshtools Plugin? 
You can get it here: https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/MeshTools

If that doesn't fix it you can try a more elaborate mesh fixer like https://myminifactory.github.io/Fast-Quadric-Mesh-Simplification/, or https://www.nanodlp.com/repair-3d-stl-file/.
Or you can use the "Make Solid" feature in AutoDesk MeshMixer. https://meshmixer.com/download.html

To me, it doesn't seem like a bug in Ultimaker Cura, since the mesh is faulty and Cura is not built to alter meshes in this way, that's what CAD software is for. I will be closing this issue, I hope you understand.
