### ISSUE TITLE
Won't slice!

### ISSUE THREAD

**Issue by DestinysCall** [Ultimaker/Cura#15086]
### Application Version

5.0

### Platform

macbook air

### Printer

Anycubic Kobra Mac

### Reproduction steps

1. loaded file
2. laid flat with desired configuration with support trees
3. pressed slice
4. FAILED

### Actual results

failed

### Expected results

should've sliced properly

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

.

**Comment by MariMakes** [comment]
Hey @DestinysCall,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

The new Cura 5.3 Stable contains the fix for this for a number of slicing crashes. 
Could you test if that's the case for your model as well? 
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0

Have you tried reverting to the default settings?
Have you tried moving the model away from the center of the buildplate and rotating by 90 degrees?
Can you check if your mesh is faulty with the Meshtools Plugin? You can get it here: https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/MeshTools

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
