### ISSUE TITLE
[5.3.0] Cura generates incorrect gcode which makes the printer print in the air

### ISSUE THREAD

**Issue by afiskon** [Ultimaker/Cura#15093]
### Application Version

5.3.0

### Platform

MacOS Monterey 12.6.3

### Printer

Prusa i3

### Reproduction steps

1. Open the attached project file
2. Export to gcode
3. Print the model

### Actual results

After a few hours when the printer reaches half of the rounded corner the Y axis is _decreased_ right to the edge of the table. The printer continues to print partially in the air, partially on top of the model. See the attached images that show when exactly this happens.

I checked several times that it wasn't some sort of power glitch or something. Also I made sure this is not a mechanical problem of the printer. Another model of the same height is printed successfully. I've been using the printer since 2017 and never seen anything like this. I'm pretty confident this is a problem of the slicer.

### Expected results

The model is printed successfully.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

Project file: https://drive.google.com/file/d/1lt_oNqtihyfAglBaP4rxJnmtLdRCCaEj/view?usp=sharing
Image 1: https://drive.google.com/file/d/1qsE8UXTMkW1P_S6TOha140_jMKc0Lswv/view?usp=sharing
Image 2: https://drive.google.com/file/d/1RPJoCJKZgH6V5i6UaNIKnZ_Nu9iOBER6/view?usp=sharing

**Comment by GregValiant** [comment]
Thanks for the report.
When I sliced your project everything is correct.  0.3 Initial Layer Height and 0.2 regular Layer Height.  This is a snippet from the gcode...
;LAYER:0
M107
G0 F1800 X62.183 Y24.765 **Z0.3**
;TYPE:SKIRT
G1 F1500 E0
G1 F1800 X62.454 Y24.338 E0.02523

So I'm unable to duplicate the problem here.  Your StartUp Gcode looks good as well.
If you have an ABL system maybe the Zoffset needs to be tweaked.  Another thing to look at is when you auto-home the print head the LCD should show a Z location of "0".  If it is something other than zero then you would need to adjust your home offset.
Did you open the gcode file and check the Z values?  Are they off?
I'll leave the bug report on this for now but I don't think this is a Cura problem or a lot of people would be complaining and this is the only report I've see of this behavior.

**Comment by afiskon** [comment]
I didn't check the Z values in the gcode. Frankly I know very little about gcode in order to validate it, sorry.

Please note that the problem occurs not in the layer 0. It happens in the middle of printing process. The attaches images show the moment when the printer starts to print in the air (after about 2 hours of printing). Did you try to actually print the model?

I could compare the G-code with yours if you tell me what to look for, but this definitely shouldn't be layer 0.

**Comment by GregValiant** [comment]
_"... I know very little about gcode in order to validate it, sorry."_
There are a few hundred G and M code commands.  Most aren't used.  There are a few that are used constantly.  G0, G1 G28, M104, etc.  Call it about 12 commands that always come up.  The [Marlin definitions are here](https://marlinfw.org/meta/gcode/).
Remember, you are programming a 4 axis robot.  You really need to have some idea of what is going on within the gcode.

There are two parts to this problem.  The first part are the commands that Cura puts in the gcode.  They need to be correct and I've been hanging around here for a couple of years and I haven't seen any complaints regarding the code involving Z movement being wrong.  I also haven't seen any problems with my own prints.  I'm not saying that it can't happen, but it is very unlikely.  I have some Excel macros for going through gcode and checking things.  You could use a program like NotePad or NotePad++ and search the file for " Z" ("{space}+Z").  Disregarding any Z-hops, the Z numbers should start at Initial Layer Height and then increment by "Layer Height" to the end of the model.  

Next, the printer needs to follow those gcode commands.  That means there are two things to look at.
Going through the gcode file the Z commands must be correct.  Provided your gcode is like the one from my slice, the printer is being given correct information.  That leaves us with the second part where the printer isn't following directions correctly.  That can be a few things but I think you need to look there first.  The chances of the gcode being wrong (in this instance) really aren't very good.

**Comment by afiskon** [comment]
Sorry, but I'm really confused... why do we discuss Z axis if the bug report is about Y axis?

**Comment by GregValiant** [comment]
That's my bad.  I look at a lot of these reports and I mixed yours up with another.

I generated a gcode from your project and read it into AutoCad.  You can see that the sides are vertical and parallel.
![Y](https://user-images.githubusercontent.com/64202104/230460662-daebb312-61ff-43fe-b182-6764bbb2cfb1.png)

If you ZIP and post the gcode file that is having trouble I will look through it.  In regards to the one I created - all the lines of that wall are at a Y of 26.46.  There is no skewing in either the Y or the X.

**Comment by afiskon** [comment]
Thanks!

Here is the gcode file I got https://drive.google.com/file/d/1Jc3NZdMiTgWoaUcH3lmd_FPFHkxs1cki/view?usp=sharing

**Comment by GregValiant** [comment]
Here are a couple of views of that wall that looks skewed.
Each layer goes to exactly the same "Y".  None fall short, and none go beyond.
![A1](https://user-images.githubusercontent.com/64202104/230587904-4bba2fbf-daba-49e1-ab75-6404ce1971c7.png)

Here I've erased the lines that go around that radius on top and only the vertical part of the wall remains.  There are 55 layers stacked up in this image.  You can see that all 55 toolpaths for that wall are colinear.
![Bwall](https://user-images.githubusercontent.com/64202104/230588172-f2124b5a-36fc-4e1d-8e3f-f0a2d85727eb.png)

If you do a search through the Gcode for "Y46.20" you will come up with 164 of them.  A lot of lines are right at that wall.

So I don't see any problem within the gcode.  You'll need to take a close look at the mechanicals of your printer and see if something can be causing that drift.  "Layer shifts" are abrupt steps and your print isn't showing that but something is going on.

Here is one of your images zoomed in.  That wall definitely is not described in the gcode.
![image](https://user-images.githubusercontent.com/64202104/230590840-234e9be7-e3dc-451e-9e3b-ebba3926a82e.png)

If the problem was in the "X" I would suspect a loose hot end.  Since it's in the "Y" you need to look at the table slide mechanicals and see if something has come loose.
If you hand edit the gcode and add a line "M201 Y150" to the right at the ";LAYER:0" line then you would limit the Acceleration in the Y axis.  That would be a good test.  It would soften the starts and stops in the "Y".  It isn't a good fix long term as it would slow the prints down considerably.

I'll leave this open for now but I don't see a Cura bug here.  The gcode is correct for your model.

**Comment by afiskon** [comment]
> If the problem was in the "X" I would suspect a loose hot end. 

Turned out the hot end was indeed loose. I corrected this and I get flat walls now. This didn't help with the originally reported problem though.

> The gcode is correct for your model.

After encountering the problem again with another model and testing that it reproduces with Cura 4.13.1 I used previously I'm inclined to agree.

Many thanks for all your help!
