### ISSUE TITLE
Slicing failed with an unexpected error

### ISSUE THREAD

**Issue by Cormac-Anglade** [Ultimaker/Cura#15129]
### Application Version

5.3.0-alpha+xmas

### Platform

windows 10

### Printer

Ender 3 v2

### Reproduction steps

I kept trying to slice, then I tried deleting and re entering it into the slicer.

### Actual results

keeps saying the same error

### Expected results

idk maybe it should have been working

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![Screenshot 2023-04-02 185102](https://user-images.githubusercontent.com/129699974/229385683-834e7cb6-9ede-45f4-8672-7771d1478207.png)

**Comment by MariMakes** [comment]
Hey @Cormac-Anglade,

Welcome to the UltiMaker Cura Github 🚀 
Thanks for your report 👍

The new Cura 5.3 Stable contains the fix for this for a number of slicing crashes. 
Could you test if that's the case for your model as well? 
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
