### ISSUE TITLE
Mid-Air Tree Support

### ISSUE THREAD

**Issue by Ppieter21** [Ultimaker/Cura#15134]
### Application Version

5.3.0

### Platform

Windows10

### Printer

Creality Ender3 Pro

### Reproduction steps

It occurs quite often that when I slice an object with tree support that some of the supports are in mid-air.
My branch angle was 40 and the rest of the settings I did not change. 

### Actual results

![image](https://user-images.githubusercontent.com/48323059/229607942-178f5b0f-d5cb-49fb-a045-53791fadf030.png)
![image](https://user-images.githubusercontent.com/48323059/229608027-c2d5d524-d887-4cd0-802b-44084966467f.png)
It does look like the branch starts at the floor, but then only continues higher up.
This only causes some extra pieces of plastic here and there, and slightly weaker support, but I thought it's good to let you know.
I have reported this on a previous update, but I just wanted to let you know on this update as well with the new tree supports.
Feel free to contact me if you have any questions, Conrad Krüger, 0785924652

### Expected results

It would be nice if there are no supports in mid-air.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[Shower Drain Left.zip](https://github.com/Ultimaker/Cura/files/11141811/Shower.Drain.Left.zip)

**Comment by rburema** [comment]
> but I just wanted to let you know on this update as well with the new tree supports.

I'm sorry, but the 'alpha xmas' trees are not in the 5.3 final. We hope to make it before 5.4

**Comment by MariMakes** [comment]
Hey @Ppieter21,

Thanks for your report 👍

We put some effort in preventing support to be printed mid-air here: https://github.com/Ultimaker/Cura/pull/15357
I took a look and your model will look like this in Cura 5.4, no floating islands anymore 😊 
![no floating](https://user-images.githubusercontent.com/40423138/236232665-3f6c72b5-375e-42bd-8f0e-a56568f22fb6.PNG)

To me, it doesn't seem like a bug in Ultimaker Cura, since we have a solution in place. 
Would you still like to keep this issue open or do you agree that we can close it?
