### ISSUE TITLE
Error with slicing

### ISSUE THREAD

**Issue by stew73** [Ultimaker/Cura#15147]
### Application Version

5.1.0

### Platform

Windows 10

### Printer

Ender 3 V2

### Reproduction steps

Tried to slice a file and it came up with an error saying: Slicing failed with an unexpected error

### Actual results

Bug report suggested

### Expected results

File should slice
[CE3_Small-House-upper.zip](https://github.com/Ultimaker/Cura/files/11158392/CE3_Small-House-upper.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

Cant locate log file

**Comment by MariMakes** [comment]
Hey @stew73,

Welcome to the UltiMaker Cura Github 🚀 
Thanks for your report 👍

The new Cura 5.3 contains the fix for this for a number of slicing crashes. 
Could you test if that's the case for you as well? 
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0

If you still run into a crash, please double-check if you shared the correct file and let us know.
I'll take another look at what is going wrong. 👍
