### ISSUE TITLE
Slicing Issue

### ISSUE THREAD

**Issue by BlueMaul** [Ultimaker/Cura#15145]
### Application Version

5.3.0

### Platform

Windows 10

### Printer

Ender 3 Pro

### Reproduction steps

I am creating a d20 model which I am adding all the pokemon type symbols to decorate it. I added the 8th symbol (to a total of 10 symbols on the die, including the 1 and 20),and went to slice it to make sure that my settings were correct.
<img width="348" alt="Capture" src="https://user-images.githubusercontent.com/129918441/229965095-4fccf54a-8bf8-482c-aa33-bce54c25b049.PNG">

### Actual results

When I went to slice the model, it loaded about halfway, and then it crashed. This occurred for a total of 10 times. 
<img width="716" alt="Capture2" src="https://user-images.githubusercontent.com/129918441/229965283-7470f776-6c51-4926-9f40-bd1cf84f722a.PNG">

### Expected results

The model would slice, and I would be able to preview the model. I would then move on to the next symbol.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[CE3PRO_Pokemon Die 1 error.zip](https://github.com/Ultimaker/Cura/files/11154660/CE3PRO_Pokemon.Die.1.error.zip)
Here is the saved project and the symbol I used.

**Comment by MariMakes** [comment]
Hey @BlueMaul,

Welcome to the UltiMaker Cura Github 🚀 
Thanks for your report 👍

This mesh seems faulty. 
What software did you use to make it and can you doublecheck if it's exported correctly? 

If that doesn't fix it you can try a more elaborate mesh fixer like https://myminifactory.github.io/Fast-Quadric-Mesh-Simplification/, or https://www.nanodlp.com/repair-3d-stl-file/.
Or you can use the "Make Solid" feature in AutoDesk MeshMixer. https://meshmixer.com/download.html

To me, it doesn't seem like a bug in Ultimaker Cura, since the mesh is faulty and Cura is not built to alter meshes in this way, that's what CAD software is for.
