### ISSUE TITLE
Crash when trying to slice a model

### ISSUE THREAD

**Issue by EricPeladeau** [Ultimaker/Cura#15148]
### Application Version

5.2.2

### Platform

Windows 10 Home - 22H2

### Printer

Creality Ender 3 pro

### Reproduction steps

1- Opened the MAKIES_Microphone_Mic_Head.STL found in this model (https://www.thingiverse.com/thing:178667)
2 - resize the model to 200%
3 - Printer settings to "Standard Quality" - 0,2mm
4 - Infill 15%, No Support, No Plate Adhesion
5 - Click on "Slice"

### Actual results

Getting error : Slicing Failed, Slicing failed with an unexpected error.  Please consider reporting a bug on our issue tracker.

### Expected results

I would be able to save my model as an gcode file

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/11158626/cura.log)
![Screenshot 2023-04-05 081647](https://user-images.githubusercontent.com/38506313/230078284-56a3c9fd-92fb-4081-b55f-bee6905c7bf7.jpg)
[CE3PRO_MAKIES_Microphone_Mic_Head.zip](https://github.com/Ultimaker/Cura/files/11158629/CE3PRO_MAKIES_Microphone_Mic_Head.zip)

**Comment by MariMakes** [comment]
Hey @EricPeladeau,

Welcome to the UltiMaker Cura Github 🚀 
Thanks for your report 👍

The new Cura 5.3 contains the fix for this for a number of slicing crashes. 
Could you test if that's the case for you as well? 
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0

If you still run into a crash, please double-check if you shared the correct file and let us know.
I'll take another look at what is going wrong. 👍
