### ISSUE TITLE
Slicing failed due to unexpected error - I found a fix!

### ISSUE THREAD

**Issue by snoopios** [Ultimaker/Cura#15155]
### Application Version

5.2.2

### Platform

Windows 11

### Printer

Ultimaker S3

### Reproduction steps

1. Placed my .stl files into Cura (3 x different parts)
2. Oriented the files (rotationally) how I wanted them
3. Duplicated each of the files (2 x of each of the 3 x parts; 6 x parts in total)
4. Positioned the files (linearly) how I wanted them
5. Rounded up the linear positions of each part to get consistent spacing (see screenshots)
6. Tried slicing - this is when it failed
7. Tried moving my prime tower away from the parts (edited the standard position)
8. Tried slicing - this failed again
9. Edited the x position of my three parts on the left side of the build plate by an arbitrary amount (edited the x position by adding a .0xxxxx decimal place after it, maxing out the number of decimal places)
10. Tried slicing - this worked

![Screenshot 2023-04-06 074524 - Fixed](https://user-images.githubusercontent.com/21006663/230294469-cfb968b8-b987-4bbb-a47b-31d3a6c8728b.png)
![Screenshot 2023-04-06 074524 - Failed](https://user-images.githubusercontent.com/21006663/230294472-d3b1ec35-5a5b-40fe-8e82-c96f6ced51df.png)

### Actual results

Until I did the arbitrary move of the parts on the left of my build plate, the slicing kept failing.

Once I moved the parts on the left of my build plate by an arbitrary amount in the x direction starting with .0, slicing worked with this being my only change.

It appears that Cura doesn't like to work with a full set of whole numbers for linear positios

### Expected results

It should slice and then be able to print but it doesn't - until I edit the x position.

I haven't tried the Y position but I got it to slice - maybe you guys can replicate this and try different positional movements to see what impact they have.

Screenshots attached of my "Failed" slice and my "Fixed" slice

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

I found 1 fix that works for this issue on my machine

**Comment by MariMakes** [comment]
Hey @snoopios,

Welcome to the UltiMaker Cura Github 🚀 
Thanks for your report 👍

The new Cura 5.3 Stable contains the fix for this for a number of slicing crashes. 
Could you test if that's the case for your model as well? 
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
