### ISSUE TITLE
I can't slice

### ISSUE THREAD

**Issue by Henryfu999** [Ultimaker/Cura#15156]
### Application Version

I don't know

### Platform

Mac air

### Printer

Ultimaker 2+

### Reproduction steps

I am changing the settings and it just show there were a bug

### Actual results

I reach this

### Expected results

You should maybe help me to fix it?

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

I want this t be print fast

**Comment by MariMakes** [comment]
Hey @Henryfu999,

Welcome to the UltiMaker Cura Github 🚀 
Thanks for your report 👍

The new Cura 5.3 Stable contains the fix for this for a number of slicing crashes. 
Could you test if that's the case for your model as well? 
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0

Have you tried reverting to the default settings?
Have you tried moving the model away from the center of the buildplate and rotating by 90 degrees?
Can you check if your mesh is faulty with the Meshtools Plugin? You can get it here: https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/MeshTools

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
