### ISSUE TITLE
Cura 5.3.0 engine segfaults on MacOS when loading a particular .3mf file

### ISSUE THREAD

**Issue by ahernsean** [Ultimaker/Cura#15171]
### Application Version

5.3.0

### Platform

MacOS Ventura 13.3

### Printer

Creality CR-10S Pro V2

### Reproduction steps

1. Opened the attached .3mf file
2. Slice

### Actual results

After slicing for a few seconds, the slicing engine fails with this SEGV error:
<img width="1265" alt="image" src="https://user-images.githubusercontent.com/1649300/230652408-22c9efc6-9c5b-4964-b015-dcec679b227c.png">

### Expected results

Slicing should complete

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[brain.3mf.gz](https://github.com/Ultimaker/Cura/files/11180498/brain.3mf.gz)

**Comment by MariMakes** [comment]
Hey @ahernsean,

Thanks for your report 👍
I took a look at your project file, are you sure that this model is made for 3D printing?

![image](https://user-images.githubusercontent.com/40423138/236257874-627d0c0e-add2-4dff-b011-9f96c8c9aa05.png)

This mesh seems faulty
Have you tried doing a quick mesh fix with the Meshtools Plugin? 
You can get it here: https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/MeshTools

If that doesn't fix it you can try a more elaborate mesh fixer like https://myminifactory.github.io/Fast-Quadric-Mesh-Simplification/, or https://www.nanodlp.com/repair-3d-stl-file/.
Or you can use the "Make Solid" feature in AutoDesk MeshMixer. https://meshmixer.com/download.html

To me, it doesn't seem like a bug in Ultimaker Cura, since the mesh is faulty and Cura is not built to alter meshes in this way, that's what CAD software is for.
