### ISSUE TITLE
Cura 5.3 fails to slice a file

### ISSUE THREAD

**Issue by pinski1** [Ultimaker/Cura#15173]
### Application Version

5.3.0

### Platform

Win 10

### Printer

Ultimaker 2+

### Reproduction steps

1. Load model from https://www.printables.com/model/362768-angle-mount-for-tapo-c200-dekco-dc2l-cameras
2. Orientate so it's flat to the bed
3. Slice

### Actual results

Hits an error and gives up on slicing
No further information is provided

### Expected results

It ought to complete slicing

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

This file has worked on 5.2.1
This is the 2nd file I've sliced on 5.3.0, the first threw a warning my minimum fan speed was too slow at 15% even though I've never changed that setting.
[cura.log](https://github.com/Ultimaker/Cura/files/11181799/cura.log)
[UM2_Tapo C200 Angle Mount v6.zip](https://github.com/Ultimaker/Cura/files/11181800/UM2_Tapo.C200.Angle.Mount.v6.zip)

**Comment by pinski1** [comment]
Never mind, had tree supports turned on

**Comment by MariMakes** [comment]
Hey @pinski1,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

I'm glad your issue was resolved, but it shouldn't have crashed, even with the tree supports turned on 😅 
I took a look at your project file and it seems like a common workaround, moving the object on the buildplate, seems to work in your model.
![Screenshot 2023-05-04 175614](https://user-images.githubusercontent.com/40423138/236419977-90a4be3d-4249-4050-82ef-2a3bb7369ce8.jpg)

I won't close the issue yet, so one of the developers can take a look at your crash. 
Thanks for your report 👍

**Comment by jellespijker** [comment]
Thank you for your report. It seems that your uploaded project file slices correct on our latest unreleased 5.7.0-alpha.0+3abb5 which indicates that the issue you're experiencing seems to be fixed for the upcoming 5.7.0 release.
I'm closing this issue as fixed for the 5.7.0 release

![image](https://github.com/Ultimaker/Cura/assets/8535734/5a9c2433-06cb-435b-b08c-9c99e6d9af1f)
