### ISSUE TITLE
Can't change the nozzle size of Longer lk5 pro printer

### ISSUE THREAD

**Issue by PunchyNeo** [Ultimaker/Cura#15190]
### Application Version

5.3.0

### Platform

win 11

### Printer

Longer LK5 pro

### Reproduction steps

1.tried to change the nozzle size on the top[ bar, doesn't have any other option other than 0.4
2. tried printer settings, nozzle setting doesn't have a nozzle size settings

### Actual results

doesn't have any option to change the nozzle size

### Expected results

should have a list of nozzle sizes to choose

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

uhh, idk what to put here

**Comment by GregValiant** [comment]
Thanks for the report.
This is a Longer problem as they didn't include any additional nozzles when they submitted the definition files for that printer.  Maybe their site has some additional files you can download.
An alternative is to go into the "variants" folder in the Cura installation folder and find "longer_lk5pro_0.4.inst.cfg".  Open it with any text editor.  Do a "Save As" using the same file naming convention but with your new nozzle size in the name rather than "0.4".  Inside the file are two lines indicating the nozzle size.  Change those two lines to your new nozzle size.  Save the file.  You can do that for any size you want, as many as you want, and then when you restart Cura they should be available.
This is the entire contents of the file:
[general]
definition = longer_lk5pro
name = **0.4**mm Nozzle  <<<<change this line
version = 4

[metadata]
hardware_type = nozzle
setting_version = 21
type = variant

[values]
machine_nozzle_size = **0.4** <<<<change this line

I'll remove the bug label and close this as it is a Longer issue rather than a Cura issue.  I hope you understand.
