### ISSUE TITLE
fehler beim slicen

### ISSUE THREAD

**Issue by Danuell9090** [Ultimaker/Cura#15314]
### Application Version

5.3.0

### Platform

windows 10

### Printer

anycubic mega s

### Reproduction steps

ich wollte eine datei vergrössern und slicen .
das slicen hat nicht funkioniert wenn ich die datei grösser gemacht habe 

### Actual results

hallo
sobald ich eine datei vergrössere und slicen möchte , kommt nach den slicen immer " UNERWARTETER FEHLER"

bitte helfen sie mir 
mein drucker : Anycubic Mega S

### Expected results

das er fertig slicen tut 

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

![WhatsApp Image 2023-04-21 at 17 14 14](https://user-images.githubusercontent.com/131470187/233673579-6215843a-cc04-4234-811b-0cf3c4df7baf.jpeg)

**Comment by Danuell9090** [comment]
[AI3MSPRO_Hex3D_Skull2_Bowl.zip](https://github.com/Ultimaker/Cura/files/11312885/AI3MSPRO_Hex3D_Skull2_Bowl.zip)

**Comment by Danuell9090** [comment]
Hallo
Ich habe ihnen eine ZIP DATEI geschickt

Von meinem iPhone gesendet

Am 24.04.2023 um 16:42 schrieb Casper Lamboo ***@***.***>:

﻿

Hi @Danuell9090<https://github.com/Danuell9090>

thank you for opening the issue. My German is not so good so excuse me for replying in English.

Without a project file we are unable to help you. You can share a project file by saving the project (ctrl+s) and creating a zip of the exported 3mf file. The zip can then be uploaded to this issue on github.

The error looks a bit like a known issue where certain orientations of the model result in a slicing error. We are actively working on resolving this issue but there is a workaround. By slightly rotation and/or moving the model Cura can often still slice the model.

Hope this helps!

**Comment by MariMakes** [comment]
Hey @Danuell9090,

Thanks for the Project File 👍 It seems to be different from the screenshot you shared. But I'm also getting a crash. 
I took a look at it in Cura 5.3.1 and it seems to be related to your layer height. 
When I reset that value from 0.4 to 0.2 I can successfully slice your model: 

![image](https://user-images.githubusercontent.com/40423138/236839562-39a05c60-655a-44c5-8736-2b6d24fe638a.png)


To me, it doesn't seem like a bug in Ultimaker Cura anymore since you changed the setting value into a warning zone. 
Would you still like to keep this issue open or do you agree that we can close it?
