### ISSUE TITLE
A bug with chosing printer

### ISSUE THREAD

**Issue by MrSuiting** [Ultimaker/Cura#15312]
### Application Version

5.3.0

### Platform

Windows 10

### Printer

Elegoo Neptune 2s

### Reproduction steps

Case 1:
1. Open software
2. Software asks for printer (what for!?)
3. Adding generic
4. Open Settings
5. Adding Elegoo Neptune 2S
6. Delete generic you don't need
7. Now you have a "shadow"  printer (which was deleted) and Elegoo Neptune also
8. You can't print becasue software doesn't see a printer connected

Case 2:
1. Create a material
2. Setup 235 for extruder and 90 as a bed temperature
3. Slice and go to printing
4. Now temperature is 210 and 80 (have no idea where from it was coppied, it was a fresh installation)

### Actual results

Every step (changing material, extruder or bed parameter, etc...) Cura is slicing. What for!?

Changed the temperatures manually on a printer during heating

### Expected results

That worked as usual without any slicing every time or save at least parameters then send to a printer as it were given in parameters

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Nothing specific, just a screenshot

![hjdfh](https://user-images.githubusercontent.com/115040260/233615804-a702063c-05bd-437f-add2-33a1032d63e6.png)

**Comment by nallath** [comment]
Could you for the next time you report an issue make a separate ticket for each issue? That will make it a bit easier for us to handle things! Thanks!

But onto the actual issues.

**Case 1**
I've been able to reproduce this. It seems to only happen for printers that are connected via the network. I don't know how you managed to get a generic printer connected in such a way though. You could have also added the Elegoo Neptune 2S right away from the menu where you selected the generic printer. 
The reason the menu is there is because Cura simply expects that there is a printer and that menu is there to ensure that. 
Restarting Cura also cleared the issue for me, but I will make a ticket for this on the backlog as it might cause other issues.

Case 2:
I'm not able to reproduce this. I've done the following:
1. Add Elegoo Neptune 2S
2. Go to material menu
3. Duplicate a material
4. Set the "Default print temperature" to 235
5. Close the material preferences
6. Checkt he print settings menu ("printing temperature" is 235, as expected)

> Every step (changing material, extruder or bed parameter, etc...) Cura is slicing. What for!?

That is because you probably have "auto slicing" enabled. You can change that in the preferences
