### ISSUE TITLE
Special Modes - Print Sequence problem when Printing 2 copies of dual material on IDEX printer

### ISSUE THREAD

**Issue by Doxieserf** [Ultimaker/Cura#15337]
### Application Version

5.3

### Platform

Windows 11

### Printer

Tenlog TL-D3 Pro (IDEX printer)

### Reproduction steps

1)  Previously printed multiple objects in one project
       - 2nd extruder material disabled
       - Special Modes --> Print Sequence set to 'One at a time'
 
2) New project started with two objects (different materials)
      - 2nd extruder material enabled
      - Object #1 - extruder material #1 selected
      - Object #2 - extruder material #2 selected
      - Objects merged
      - Enabled prime tower

3) Need two of these items, so opened a second set of objects into same project; merged and sliced.
      - Problem 1:  Extruder outline was visible on bed for both merged object sets (ie.  as if Print sequence 'one at a time' was on)
      - Problem 2:  After slicing, the preview shows printing one merged object set with prime tower complete, then starts on
                            second set with no second prime tower.  This means either extruders will collide with prime tower (as  it tries to
                            create a 2nd prime tower in same location, or 2nd merged object set will not have a prime tower
      - Problem 3:  The Special Modes --> Print Sequence setting visibility is turned off, because 2nd extruder material is enabled.
                            I had to disable the 2nd extruder material, which turns on the print sequence visibility, change to 'All at once'
                            Then re-enable the 2nd extruder material, then unmerge all objects, reassign extruder materials and remerge.
                            This then results in 2 sets of object printed simultaneously with the prime tower.

This is not really a bug.  But I think this is an odd situation that the software is not able to handle in an ideal manner.

Also, the Tenlog TL-D3 pro printer is missing from the 3rd party printer list and makes it difficult to have to resetup 
for this printer, everytime an update occurs.  

Thank you.

### Actual results

User gets very frustrated.

### Expected results

I believe this should be easily reproduced... please try it out.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

[Thanks.txt](https://github.com/Ultimaker/Cura/files/11306759/Thanks.txt)

**Comment by GregValiant** [comment]
Thanks for the report.
The UltiMaker Company doesn't make any IDEX printers and so they aren't going to pay their people on the Cura Team to develop software that supports someone else's IDEX printers.  That would be a waste of money and resources.  The coding effort would have to come from the community via pull requests.
I've read that "Cura doesn't support IDEX" and in a general sense that is true.  There is no direct support for "U, V, W" axes.
Some printers (i.e.: Raise3D IDEX printers) handle the additional axes within their processors and so can be made to work with Cura, but the owner/operator has to jump through some hoops to get Cura set up correctly.

The printer definition files for 3rd party printers come from the community (or occasionally a manufacturer).  There is no way that UltiMaker can go out and buy one of every printer model on the planet and then put effort ($$$) into figuring them out in order to write the definition files.

Please understand that I don't have anything to do with UltiMaker and I don't own one.  I can understand the "Business" perspective and I sympathize with it.

I'll go ahead and close this as it is expected behavior.  I don't know how much traction it would get but you could make this a Feature Request.
