### ISSUE TITLE
Wont slice

### ISSUE THREAD

**Issue by tje2236** [Ultimaker/Cura#15341]
### Application Version

5.3

### Platform

window 10

### Printer

Ender 5 plus

### Reproduction steps

created object on fusion 360, exported as .stl, loaded to cura, scaled to fit print bed, pushed slice, it took forever and then failed.

### Actual results

Error says "Slicing failed with an unexpected error. Please consider reporting a bug on our issue tracker."

### Expected results

Should have sliced so that i could export to the 3d printer and print.

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[CE5P_Beds.zip](https://github.com/Ultimaker/Cura/files/11310384/CE5P_Beds.zip)
[cura.log](https://github.com/Ultimaker/Cura/files/11310421/cura.log)

**Comment by MariMakes** [comment]
Hey @tje2236,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

That's a pretty cool model 🤩
Your crash seems to be related to tree support. I can slice your model is you select normal support instead: 
![image](https://user-images.githubusercontent.com/40423138/236824986-824d2d86-b799-44d3-b056-4e9bc432ab07.png)

We are working hard to improve the tree support for the 5.4 release so I took a look at one of our internal builds where we have a number of fixes for the crashes and I can see it slices: 
![image](https://user-images.githubusercontent.com/40423138/236825613-76547b3d-b0b5-43ce-84e7-680f715d1996.png)
This is the GCode in case you are curious here is the Gcode: 
[Mari_CE5P_Bed.zip](https://github.com/Ultimaker/Cura/files/11421254/Mari_CE5P_Bed.zip)

To me, it doesn't seem like a bug in Ultimaker Cura anymore, since there is a solution in place. 
Would you still like to keep this issue open or do you agree that we can close it?
