### ISSUE TITLE
Supports touching build plate starting on layer #2

### ISSUE THREAD

**Issue by Pro4791** [Ultimaker/Cura#15388]
### Application Version

5.3.1

### Platform

Windows 10

### Printer

Creality Ender-3 V2

### Reproduction steps

Turn off build plate adhesion with supports enabled.

### Actual results

No brim, skirt, or raft present on the model or supports causing them to start printing on the second layer and not adhering to the build plate.
![bpa off](https://user-images.githubusercontent.com/77859351/235314662-6c718aa4-2cb0-4f05-8028-26d6ea1ec67e.png)
![bpa off layer 2](https://user-images.githubusercontent.com/77859351/235314663-6187163f-60c6-42a0-881c-da343a67f8bb.png)

### Expected results

No brim, skirt, or raft present on the model with supports having a base on the first layer. Should be like the photos below but with no skirt around the model, only the base on the supports.
![bpa on](https://user-images.githubusercontent.com/77859351/235314681-3c87cc26-ab9a-4376-b44d-e3f171f2bfe3.png)
![bpa on layer 2](https://user-images.githubusercontent.com/77859351/235314683-ed6124ee-0de8-4701-8033-6fcad0a7f645.png)
Works as intended in Cura 4.13.1
![4 13 1](https://user-images.githubusercontent.com/77859351/235315538-c9c63368-3ddc-4b66-a862-c8309bec5be0.png)

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[Support CURA.zip](https://github.com/Ultimaker/Cura/files/11359704/Support.CURA.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
This is duplicate and a lot of people are noticing this bug.  The workaround is to enable either the skirt or brim.  When Bed Adhesion is set to "None" then the support brim gets disabled and the support doesn't show up until the second layer.

**Comment by Asterchades** [comment]
I think I may have some insight into this one.

![image](https://user-images.githubusercontent.com/29810435/235337815-9071c89c-58aa-4545-be70-4d2a5ed74098.png)

This is the first layer of supports on my test model using Brim adhesion, so everything is working as expected. Note specifically where the Support is being printed as regular Support, rather than as the Support Brim.

![image](https://user-images.githubusercontent.com/29810435/235337867-9a95d1ad-f712-41f2-80d9-9a3760719655.png)

This is the same model, same settings, but now with None adhesion. The Brim part of the Supports is gone, but the regular Support part is still present.

![image](https://user-images.githubusercontent.com/29810435/235338090-94a1f93a-1465-4ad1-9c83-ee49645427a7.png)

All I have done here is disable the Support Brim setting. It would appear that the presence of _any_ Build Plate Adhesion is being adjusted by the more global setting at the detriment of the Support-specific setting, which is arguably a regression on previous functionality (that grid really doesn't seem like it's going to stay put).

**Comment by GregValiant** [comment]
@Pro4791  I believe this problem has been addressed in 5.7 versions.  Can this be closed now?
