### ISSUE TITLE
slicing failed

### ISSUE THREAD

**Issue by mecha1982** [Ultimaker/Cura#15425]
### Application Version

5.2.1

### Platform

Windows 10

### Printer

Anycubic Vyper

### Reproduction steps

Loaded a 148.5x158.5x13.7mm file, that is 16.5MB. No errors in 3d builder or meshmixer detected. No holes. "Slicing failed" almost immediately.

### Actual results

Slicing fails.

### Expected results

The app should do it's job and - I don't know. Slice the file.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

I'm not the first person this has happened to since 5x. Fix your crap.

**Comment by MariMakes** [comment]
Hey @mecha1982,

Welcome to the UltiMaker Cura Github 🚀 
Thanks for your report 👍

The new Cura 5.3 contains the fix for this for a number of slicing crashes. 
Could you test if that's the case for you as well? 
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.1

Have you tried reverting to the default settings?
Have you tried slicing with Support disabled? 
Have you tried moving the model away from the center of the buildplate and rotating by 90 degrees?
Can you check if your mesh is faulty with the Meshtools Plugin? You can get it here: https://marketplace.ultimaker.com/app/cura/plugins/fieldofview/MeshTools

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
