### ISSUE TITLE
Stopped slicing the file

### ISSUE THREAD

**Issue by TravisFF7** [Ultimaker/Cura#15448]
### Application Version

5.2.1

### Platform

Windows 11

### Printer

Ender 3 Pro

### Reproduction steps

Tried slicing the file again

### Actual results

Same thing, it failed to slice the file

### Expected results

It should slice the file

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

I was trying to slice the file on for an Ender-3, but I used a profile that had been previously set up for a CR-10s. I was also trying to tell the slicer that I was using an Ender 3 Pro, to try to get rid of the soft endstops on the y axis. So I was actually using a standard Ender 3, but telling the slicer it was an Ender 3 Pro, and using a profile that I had set up for the CR-10s. So who knows.

**Comment by MariMakes** [comment]
Hey @TravisFF7,

Welcome to the UltiMaker Cura Github 🚀 
Thanks for your report 👍

The new Cura 5.3 contains the fix for this for a number of slicing crashes. 
I was able to slice your model successfully in 5.3 Stable.
Could you test if that's the case for you as well? 
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.

**Comment by TravisFF7** [comment]
So I actually just closed out the application and restarted it and then it
allowed me to slice the file

**Comment by MariMakes** [comment]
Hey @TravisFF7,

Thanks for the update. 
I'll close the issue since it's resolved.

Happy Printing 👍
