### ISSUE TITLE
Doing the settings on overlap has a bug where if you set something to 0 it doesnt apply

### ISSUE THREAD

**Issue by ToyPower** [Ultimaker/Cura#15467]
### Application Version

5.3.0

### Platform

Windows 10

### Printer

Flsun Super Racer

### Reproduction steps

1. Posted my Model in this case a vace,
2. I had default settings of 4 layers of bottom and top layers applied
3. i added a support blocker and placed on top of the vace where it would overlap where the top layer would be
4. went and selected Modify settings for overlap
5. selected top layer and bottom layer and set to 0

### Actual results

it didnt remove the top or bottom layer, also if i tried doing infill to 0 it will still have infill, seems like the bug is if you set anything to 0

### Expected results

The resulting code i expected there to not be a top or bottom layer where i put the support blocker but didnt remove any of it

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

Just thought i would report this bug im sure others had already reported it

**Comment by GregValiant** [comment]
Thanks for the report.  We'll need a project file to do an investigation as I am unable to duplicate this problem.
When using the blocks as Infill Mesh or Cutting Mesh for Overlaps; the settings affect the block at the overlap.  If you want different settings for the model you have to change the main settings.
Here is a Cutting Mesh set to 0 top and 0 bottom layers, and 0% infill.  There is no top surface at the overlap, but the model still has a top surface just below the cutting mesh because the model is set to have top surfaces.  You can see that there is no infill within the overlap.
![image](https://user-images.githubusercontent.com/64202104/236842016-2c2501b3-f5fd-4f7a-a857-c210b6223f00.png)

It's also possible that I simply misunderstood your post.
Load the model and get Cura ready to slice.  Use the "File | Save Project" command to create a 3mf project file.  In Windows Explorer - right-click on the file and select "Send To..." / "Compressed (zipped) Folder" and post the zip folder here.
