### ISSUE TITLE
When Cura is launched, the USBPrinting plugin causes the printer to reset.

### ISSUE THREAD

**Issue by eAtmApp** [Ultimaker/Cura#15473]
### Application Version

5.3

### Platform

windows 10

### Printer

蓝模(Marlin)

### Reproduction steps

When the USBPrinting plugin is enabled and the printer is in a connected state, starting Cura can cause the printer to automatically restart.

### Actual results

...

### Expected results

USBPrinting plugin, can it support manually connecting the printer? 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

...

**Comment by GregValiant** [comment]
Thanks for the report.
This is likely controlled by the firmware and is a response to the port being opened and a connection being initiated.  You can disable the "USB Printing" plugin in the MarketPlace.  USB printing doesn't have any controls.

You will also notice that if the printer is turned on and THEN the USB cable is connected, that the printer will re-boot when it sees the 5volt signal.  That is also a function of the firmware and is an "external reset" in case the printer processor had locked up for some reason.

There are a lot of good reasons not to use USB printing and very few (if any) reasons to actually use it.  Since no UltiMaker printers use it the UltiMaker company isn't going to pay their people to work on it.  That leaves it up to contributors to fix it but there are so many different hardware configurations out there that it would be a loosing battle.

**Comment by GregValiant** [comment]
I'll close this today.
