### ISSUE TITLE
will not slice 

### ISSUE THREAD

**Issue by spirit-one** [Ultimaker/Cura#15480]
### Application Version

5.2.1

### Platform

windows 11

### Printer

ultimaker ender 3

### Reproduction steps

1. selected 3d model
2. resized model
3. sliced

### Actual results

slicing failed multiple times

### Expected results

slice should complete with no issues whatsoever

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

please fix

**Comment by MariMakes** [comment]
Hey @spirit-one,

Welcome to the UltiMaker Cura Github 🚀 

The new Cura 5.3 contains the fix for this for a number of slicing crashes. 
Could you test if that's the case for you as well? 
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.3.0

If that's not it, I'll need a little bit more information from you.
Do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
