### ISSUE TITLE
Crazy Brim

### ISSUE THREAD

**Issue by MagicMilamber** [Ultimaker/Cura#15486]
### Application Version

5.3.1

### Platform

Windows 11

### Printer

Anycubic Kobra Plus

### Reproduction steps

Slice attached Project

### Actual results

See Screenshot

### Expected results

Brim does not cross the Object base

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[AV_ProfilSystem-Oberteil 90Grad.zip](https://github.com/Ultimaker/Cura/files/11434346/AV_ProfilSystem-Oberteil.90Grad.zip)
![Screenshot 2023-05-09 193322](https://github.com/Ultimaker/Cura/assets/101792312/33a09f80-d027-4c39-ab8c-3e32089cd1d3)

**Comment by GregValiant** [comment]
Thanks for the report and the file.
The brim is going underneath the model because the bottom of the model is a line of points rather than a surface.  Computers are dumb but they are also accurate to a lot of decimal places.  The problem stems from the fact that the portion of your model that must contact the build plate is what I refer to as a "feather edge" or "knife edge".  It has a width of 0.00 at the build plate.  That's why your first layer is empty.
Go to Preferences / Configure Cura and in the Viewport Settings make sure "Automatically drop models to the build plate" is turned off.
Back in the main window set your model to Z = --0.10 .  That will move the line of points into the build plate and the bottom of the model will be a narrow flat surface rather that a feather edge and it will be wide enough to slice at your 0.6 line width.  Dropping the model into the build plate is the only change I made and this is the result.
![image](https://github.com/Ultimaker/Cura/assets/64202104/02011db0-f253-41aa-a9d5-9ce2d6ea50cb)

I think this is more of a "gotcha" math thing than a bug.  The problem is really that although the bottom of the model is resting on the build plate, it isn't sliceable because the contact patch is infinitely narrow.

Here is another screenshot.  I've turned off the brim and you can see that the first layer is missing.  If there is a bug here it might be that although "Remove Empty First Layers" is enabled, that empty layer is not being removed.  That might be because of the feather edge.  Things get dicey when you are dealing with "Infinity and Beyond".
At any rate, I'm inclined to remove the bug label from this as it is more of a model geometry problem than a software issue.  Let me know what you think.
![image](https://github.com/Ultimaker/Cura/assets/64202104/58b5e768-e4e4-4251-a8b5-ebc8c4aff988)
