### ISSUE TITLE
Will not slice

### ISSUE THREAD

**Issue by KDPrints** [Ultimaker/Cura#15586]
### Application Version

5.3.0

### Platform

Windows 10

### Printer

Ender 3

### Reproduction steps

1. You try to slice the print. (Doesn't matter what settings.)
It might be over loading because I'm printing multiple pieces at the same time. 

### Actual results

The print gets about halfway through and stops loading. 

### Expected results

It should be able to slice it and download it as usually.

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

![2023-05-22](https://github.com/Ultimaker/Cura/assets/132709955/02b988c1-507d-44bb-a5d6-b7b017fd1886)
[front chest2.zip](https://github.com/Ultimaker/Cura/files/11537438/front.chest2.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
Using my printer and settings I didn't have any trouble slicing this so I'm unable to duplicate the problem.
![image](https://github.com/Ultimaker/Cura/assets/64202104/0587ab9f-cbdd-4097-92f4-5c09126900e8)

There might be a bug involved but we need a Project File and Cura.log file in order to properly troubleshoot what might be going on.
