### ISSUE TITLE
hole filing error

### ISSUE THREAD

**Issue by Andreipoe1** [Ultimaker/Cura#15628]
### Cura Version

5.3.1

### Operating System

Windows 10*

### Printer

Custom*

### Name abnormal settings

none, just default

### Describe model location

Yes

### Describe your model

Yes, on other pc of other discord members, they sliced my model without issues *

### Add your .zip here ⬇️

[Brat masina rc v2.zip](https://github.com/Ultimaker/Cura/files/11598123/Brat.masina.rc.v2.zip)

when i try to slice it it filing my holes 

![Screenshot 2023-05-30 120045](https://github.com/Ultimaker/Cura/assets/122009385/5d8da815-2418-4150-ba48-ddb0f51c82f8)
![Screenshot 2023-05-30 120007](https://github.com/Ultimaker/Cura/assets/122009385/a026a857-a02f-4c50-9501-9e1b4a6ebfc6)

and its not the first time

**Comment by GregValiant** [comment]
Thanks for the report.
The problem usually occurs when the Mesh Fixes setting "Remove all Holes" is turned on.
In the Experimental section "Make Overhangs Printable" can also cause something like this.
Make sure those two settings are turned off.  They are for special situations and are not often used.

But Remove All Holes should not leave those two vertical holes that are left in your first picture.  The second image does look like you have Remove all Holes turned on.

The zip file contains only the model so I can't check your settings.  Use the "File | Save Project" command and then zip and post the 3mf project file.  With a project file your settings and printer definition can be checked as well.

This is with "Remove all Holes" turned on.  You can see that ALL vertical holes are filled rather than leaving just two of them.
![image](https://github.com/Ultimaker/Cura/assets/64202104/90346b3f-a753-4416-b542-fac81f90341f)

**Comment by Andreipoe1** [comment]
[CFFFP_sdaD.zip](https://github.com/Ultimaker/Cura/files/11599768/CFFFP_sdaD.zip)


I tried in different positions but when a hole is looking up it fills it, and I got both settings tuned off

![Screenshot 2023-05-30 150448](https://github.com/Ultimaker/Cura/assets/122009385/26378b76-55cf-4215-b295-1759d979a507)
![Screenshot 2023-05-30 150642](https://github.com/Ultimaker/Cura/assets/122009385/63febd6b-8e33-4297-961a-bf444d68bdc8)
![Screenshot 2023-05-30 150752](https://github.com/Ultimaker/Cura/assets/122009385/7ac96d4c-81f2-47f4-9ea5-dc68957519e9)
The last one I managed to not let it fill my holes

**Comment by Andreipoe1** [comment]
..

**Comment by GregValiant** [comment]
Thank you.
This is the top view in Cura.  Red areas that face upward are "inverted normals".  They are surfaces where the inside is facing outward.
![image](https://github.com/Ultimaker/Cura/assets/64202104/768cf177-ea4a-4ffd-aeb1-4c170ec2746d)

I used formware.co/OnLineSTLRepair to check the model and here is the report:
-> Analysed your file:
--> 0 Naked edges (?)
--> 0 Planar holes (?)
--> 0 Non-planar holes (?)
--> 0 Non-manifold edges (?)
**--> 1713 Inverted faces (?)**
--> 0 Degenerate faces (?)
--> 0 Duplicate faces (?)
--> 0 Disjoint shells (?)
Back in Cura I've imported the repaired model.  You can see that it looks different than the model you provided.  Notice that two of the holes on the left are showing no overhang on the tops of the holes, but they should.
_What software did you design the model in?_
![image](https://github.com/Ultimaker/Cura/assets/64202104/145da706-e15e-44fb-aad4-892ec42b4270)

Here it is sliced and your model shows that hole being filled.  The repaired model looks fine.  This is in 5.3.1.
![image](https://github.com/Ultimaker/Cura/assets/64202104/52c217ed-64eb-4616-b3f8-7d299fc7a539)

I'm attaching the repaired model.  Try slicing this and let us know if there is a difference.

[GV CFFFP_sdaD_fixed.zip](https://github.com/Ultimaker/Cura/files/11600244/GV.CFFFP_sdaD_fixed.zip)
