### ISSUE TITLE
Slicing failed when I tried to use tree support with a wider branch distance

### ISSUE THREAD

**Issue by softegg** [Ultimaker/Cura#15626]
### Cura Version

5.1.1

### Operating System

Windows 10

### Printer

Craftbot 2 Pro

### Name abnormal settings

Support Structure: Tree; Tree Support Branch Distance: 3.0mm

### Describe model location

Center

### Describe your model

Yes, with zig zag support

### Add your .zip here ⬇️

[CFFFP_Stylish Belt Synth V4 Bottom ABS tree.zip](https://github.com/Ultimaker/Cura/files/11595027/CFFFP_Stylish.Belt.Synth.V4.Bottom.ABS.tree.zip)

**Comment by GregValiant** [comment]
Thanks for the report and and the file.
I moved the model away from the mid-point of the Cura build plate and the model sliced.  
![image](https://github.com/Ultimaker/Cura/assets/64202104/700f808f-c3c2-4d65-bdaa-68adfad58c9c)

This bug has been reported numerous times.  I'll mark this as a duplicate and go ahead and close this as the Cura team is aware of this bug.  I hope you understand.

Hopefully this will be fixed in 5.4.
