### ISSUE TITLE
Failed to slice

### ISSUE THREAD

**Issue by OptikCrash** [Ultimaker/Cura#15630]
### Cura Version

5.3.1

### Operating System

MacOS Ventura 13.3.1

### Printer

Anycubic Kobra Max

### Describe your model

2 parts of a Dome for starwars droid (Chopper)

### Add your .zip here ⬇️

[AKMAX_LowerMainDomeE.3mf.zip](https://github.com/Ultimaker/Cura/files/11601476/AKMAX_LowerMainDomeE.3mf.zip)

**Comment by GregValiant** [comment]
Thanks for the report and the file.
I couldn't get the project to slice either.  Removing one of the pieces and then rotating the remaining part allowed it to slice.
I'll mark this as a duplicate as this behavior has been reported numerous times.  Hopefully it will be fixed in 5.4.
I'm going to go ahead and close this as well as the Cura team has a lot of examples of this behavior.  I hope you understand.

At almost 19 hours for one piece I think I'd print these separately.
