### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by GooeyGoodra4** [Ultimaker/Cura#15656]
### Cura Version

5.3.1

### Operating System

Windows 10

### Printer

Neptune 3

### Name abnormal settings

No

### Describe model location

Center of build plate

### Describe your model

Has printed and sliced before perfectly, not slicing anymore.

### Add your .zip here ⬇️

It gets Half-way done slicing, then stops and gives error.

**Comment by GregValiant** [comment]
Thanks for the report.
Without a project file it's impossible to tell what might be going on.
There is a bug (hopefully it will be fixed in 5.4) that can keep a model from slicing when it is in certain positions on the Cura build plate.  Try moving and/or rotating the model on the build plate.  Sometimes changing the initial layer height by a little bit will also fool the bug.
Let us know if any of that works for you.  The Cura team is aware of the problem that I described but your problem might be different.  A Project File would tell.
