### ISSUE TITLE
Failed slicing of Dragonlock tiles

### ISSUE THREAD

**Issue by daveh0805** [Ultimaker/Cura#15670]
### Cura Version

5.3.1

### Operating System

Windows 11

### Printer

Ender-3/Ender-3Pro/Ender-3-3S

### Describe model location

Tried rotating the models 90 degrees and 180 degrees. Neither worked

### Describe your model

Dragonlock Dungeon tiles from Fat Dragon Games

### Add your .zip here ⬇️

Here is the link to download the zipped project file:

https://we.tl/t-Vf4a0mQ0ZR

**Comment by GregValiant** [comment]
Thanks for the report.
It took a while but it did slice for me on the first try.
Have you tried slicing one or two at a time instead of filling the build plate?
On this I've noticed about this bug is that it really doesn't like stone floors.  When there are a lot of fine differences that will occur on single layers (a lot of islands develop) then the bug is a real problem rather than being somewhat annoying.

I'll mark this as a duplicate as this behavior has been noted many times in 5.3.1.  I'll go ahead and close this as the Cura team is aware and this should be fixed in 5.4.
