### ISSUE TITLE
Unable to use "Per model settings" with a multibody *.3MF file

### ISSUE THREAD

**Issue by DamienCM** [Ultimaker/Cura#15683]
### Application Version

5.3.1

### Operating System

Windows 10

### Printer

Ender 3 

### Reproduction steps

1. Imported my multibody part
![image](https://github.com/Ultimaker/Cura/assets/45606435/ed56d9cc-3bd7-420b-95d6-5fd8da48eef2) 
2. Imported my one-body part and centered both
![image](https://github.com/Ultimaker/Cura/assets/45606435/5d0c9aff-caac-429a-adbd-00bb2dc5652f)

### Actual results

3. Unable to use "Per model settings" (greyed out) for the multi-body one. Here I want to set different print parameters for the multibody part to reinforce the printed part. 
 ![image](https://github.com/Ultimaker/Cura/assets/45606435/5d0c9aff-caac-429a-adbd-00bb2dc5652f)

### Expected results

It should let me access to the "Per model settings" menu or give an explanation.

It works just fine replacing the multibody 3MF file by a regular STL
![image](https://github.com/Ultimaker/Cura/assets/45606435/9e459344-b0bf-49c0-a629-4013c50ca194)

Producing the following reinforcement : 
![image](https://github.com/Ultimaker/Cura/assets/45606435/101c13d3-cb03-4975-a108-eb23c292e49e)
VS the standard slicing without reinforcement
![image](https://github.com/Ultimaker/Cura/assets/45606435/bb6f454c-0da1-4627-bd7b-f5693cad216d)

### Checklist of files to include

- [X] Log file
- [X] Project file

### Additional information & file uploads

[came.zip](https://github.com/Ultimaker/Cura/files/11664460/came.zip)
[cura.log](https://github.com/Ultimaker/Cura/files/11664470/cura.log)

**Comment by GregValiant** [comment]
Thanks for the report.
It would appear that you can't use "Per Model" settings on a "Group".  I have to guess here and my guess would be that Cura knows the group is made of "individual meshes" but has no way to tell which one you are referring to.  When you UnGroup the models and select an individual instance then it's clear what you want and so Per Model is available.
When you bring in a model file that has all your little pieces together then Cura considers it as a single-model and Per Model settings is available.

Although they look the same - the "Group" on the left does not allow per model settings.  The "Model" on the right does allow it BUT not on an individual piece because there are no individual pieces, just a single mesh that happens to look like a bunch of pieces.
![image](https://github.com/Ultimaker/Cura/assets/64202104/5a4e1526-ed66-4d94-90b9-850c14ed5280)

So this would appear to be "Expected Behavior" rather than a bug.  I'll leave the bug label on for now and leave this open so you can respond.
