### ISSUE TITLE
Settings Not Visible in Compare & Save Dialog

### ISSUE THREAD

**Issue by njsokalski** [Ultimaker/Cura#15700]
### Application Version

5.3.1

### Operating System

Windows 10

### Printer

Creality Ender 3 S1 Plus

### Reproduction steps

1. Open a project
2. Change a setting
3. Click Compare & Save

### Actual results

In the dialog box that appears, the table of settings is of 0 height (except for the headers)

### Expected results

In the dialog box that appears, I expect to see a list of settings

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

![CuraBug](https://github.com/Ultimaker/Cura/assets/6307655/a4beb054-9743-4f30-ae9f-0daeedc30dd4)

**Comment by MariMakes** [comment]
Hey @njsokalski,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

That window definitely looks strange 🤔 
It's supposed to look like this:
![image](https://github.com/Ultimaker/Cura/assets/40423138/f23e6ae9-cbb6-4de0-ba9a-fca07b95c616)

I can't reproduce it on my side with Cura 5.4.
Can you doublecheck for us if the issue is present in the latest version of Cura?
Or provide more comprehensive reproduction steps? 
If we cannot reproduce it, we also cannot see how to solve the issue. 

Thank you 🙏
