### ISSUE TITLE
it doesnt slice

### ISSUE THREAD

**Issue by Dlecom** [Ultimaker/Cura#15727]
### Cura Version

5.3.1

### Operating System

Mac os 

### Printer

Ender 3

### Name abnormal settings

no

### Describe model location

sometimes

### Describe your model

is a moon lamp

**Comment by MariMakes** [comment]
Hey @Dlecom,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

We are working hard on reducing the amount of reports of slicing crashes.
We would like to add your example to test our solutions. 
You shared the incorrect file, also one something that contained your contact info, so I removed it. 

Instead of an STL do you have a project file for us? It contains the printer and settings we need for troubleshooting. 
To save a project file go to File -> Save project. Please make sure to .zip your project file. For big files, you may need to use WeTransfer or similar file-sharing sites.

You'll need to open Github in your browser to attach any files to your ticket
You can click the **view it on GitHub** link at the bottom of your email to open GitHub in the browser.
