### ISSUE TITLE
slicing failed

### ISSUE THREAD

**Issue by karsiwek** [Ultimaker/Cura#15726]
### Cura Version

5.3.1

### Operating System

MacOD Montenerey

### Printer

Ender 3 S1 Pro

### Name abnormal settings

broke after i've rotated print by 45 deg

### Describe model location

center

### Describe your model

litophane

### Add your .zip here ⬇️

[CE3S1PRO_window-projekt.3mf.zip](https://github.com/Ultimaker/Cura/files/11720809/CE3S1PRO_window-projekt.3mf.zip)

**Comment by MariMakes** [comment]
Hey @karsiwek,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 
Thanks for your report 👍

![image](https://github.com/Ultimaker/Cura/assets/40423138/b8958a0b-8afb-438b-9f01-485d29c78947)

The new Cura 5.4 contains the fix for this for a number of slicing crashes. 
I was able to slice your model successfully in 5.4 Stable.
Could you test if that's the case for you as well? 
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.4.0

If you still run into a crash, please double-check if you shared the correct file and let us know.
I'll take another look at what is going wrong. 👍
