### ISSUE TITLE
Slicing failure

### ISSUE THREAD

**Issue by hneiva** [Ultimaker/Cura#15723]
### Cura Version

5.3.1

### Operating System

Windows 10

### Printer

Ender 3 V2 Neo

### Describe model location

Rotating it slices fine

### Describe your model

Half of a handle

### Add your .zip here ⬇️

[slice-fail.3mf.gz](https://github.com/Ultimaker/Cura/files/11716044/slice-fail.3mf.gz)

I have sliced it before, but I think it's something to do with the position? It seems like it should slice, rotated it a bit and it slices fine

**Comment by GregValiant** [comment]
Thanks for the report.
Rotating, sometimes sliding it around, sometimes changing the Initial Layer Height can all work to fool this bug.
This behavior has been reported many times and the Cura team is aware of it.  Hopefully it will be fixed in 5.4.
I'll mark this as a duplicate and go ahead and close it as the Cura team has lots of examples of this bug.  I hope you understand.
