### ISSUE TITLE
Slicing Failed

### ISSUE THREAD

**Issue by javiermoraloj** [Ultimaker/Cura#15720]
### Cura Version

5.3.1

### Operating System

Windows 11

### Printer

Ender 3

### Describe your model

He trabajado con el modelo en Fusion 360

### Add your .zip here ⬇️

[CE3E3V2_pendiente ganesha v3.zip](https://github.com/Ultimaker/Cura/files/11715622/CE3E3V2_pendiente.ganesha.v3.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
Try moving it or rotating it in Cura.  This sliced very quickly for me.
This is an often reported bug.  I'll mark this as a duplicate and go ahead and close this as the Cura Team has lots of examples.  This should be fixed in 5.4.
![image](https://github.com/Ultimaker/Cura/assets/64202104/8ea15bd0-10e3-4dee-96b6-ab089a43494c)
