### ISSUE TITLE
Unable to set Monero (XMR) as currency in cura

### ISSUE THREAD

**Issue by Kreyren** [Ultimaker/Cura#15779]
The cost of fillament in local makerspace is 5 CZK/m which converts to `0.00034 XMR` as of 17/06/2023.

The issue is that Cura 5.3.1 only allows numbers up to `0,00` so i am unable to input the cost there:

![image](https://github.com/Ultimaker/Cura/assets/11302521/796ec2f4-9512-4599-9eed-066eb3ada21c)

Proposing to increase the amount of zeros that the `Fillament Cost` parameter can have

### Rationale

I am working on a payment gate that would accept crypto for the fillament and this is complicating implementation.

**Comment by GregValiant** [comment]
Thanks for the report.
I don't see a bug here.  You enter the cost and you enter the weight and the other boxes are calculated values to 2 decimal places.  That's how it works so what you are getting is "expected behavior".
Cura is open source so if you require a custom version then you would need to create it yourself.

I'll remove the bug label from this and go ahead and close it.  I hope you understand.
