### ISSUE TITLE
driver ch340 , service brltty abort access to printer 

### ISSUE THREAD

**Issue by philivy** [Ultimaker/Cura#15821]
### Application Version

5.3.1

### Operating System

ubuntu 22.04 

### Printer

ender3

### Reproduction steps

1 install cura and try to connect to printer 3D , ender3
2 no printer was detected 
3 remove brltty services : sudo apt-get autoremove brltty

### Actual results

success : cura detected the printer 

### Expected results

I can use cura to print via usb 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

https://askubuntu.com/questions/1321442/how-to-look-for-ch340-usb-drivers
please , indicate this procedure , to success installing Cura for ubuntu.

**Comment by MariMakes** [comment]
Hey @philivy,

Quick update from our side 👋
I brought your issue up to the team, but they mentioned that there is not a lot that we can do with the cura team.

We are constantly working on making Ultimaker Cura better. Our community is a big part of that by requesting new features and reporting bugs. To be able to focus on the most requested and needed features and bug fixes from our community and from Ultimaker defer this issue.

Since Cura is open source, you or anyone else is more than welcome to work on this issue and create a pull request yourself.
