### ISSUE TITLE
5.4.0b1 - No brim if supports turned on

### ISSUE THREAD

**Issue by tlhintoq** [Ultimaker/Cura#15848]
### Application Version

5.4.0b1

### Operating System

Win10x64pro

### Printer

Any

### Reproduction steps

In my case happens on CR10s5, Ender3, KobraMax...
Place model
Tick on supports
Use brim
![image](https://github.com/Ultimaker/Cura/assets/11351506/e71048da-3046-441c-b2c0-029c78fc6e45)

### Actual results

With Supports on, no brim
With supports off, yes brim

### Expected results

Brim should not be affected by whether or not supports are turned on.

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[Guard_A_v2.zip](https://github.com/Ultimaker/Cura/files/11826859/Guard_A_v2.zip)

**Comment by GregValiant** [comment]
Thanks for the report and the file.
Your models are 0.3mm above the build plate.  It's expected behavior that there is no brim if the model is floating.  The model isn't high enough off the build plate to develop support but if it was then the support brim would be apparent.
I'll go ahead and close this (it is a function of the way you have set the slice up) and remove the bug label.  I hope you understand but let us know if you feel that is premature.
Here I have moved the left model onto the build plate and there is no problem with the skirt.
![image](https://github.com/Ultimaker/Cura/assets/64202104/49cbcc56-0361-4401-af3e-ed1495220169)
