### ISSUE TITLE
Tree supports somehow not generating correctly

### ISSUE THREAD

**Issue by RodoxDE** [Ultimaker/Cura#15861]
### Application Version

5.4.0-beta.1

### Operating System

Windows 10

### Printer

Elegoo Neptune 3 pro

### Reproduction steps

Copied in the object,

used default values

slice

weird supports

help

### Actual results

![grafik](https://github.com/Ultimaker/Cura/assets/69358187/8f6345f1-30f4-45dd-bb57-fef4e21a3cb8)
Beta version

### Expected results

![grafik](https://github.com/Ultimaker/Cura/assets/69358187/5b792ba3-46f7-49e7-b573-10c64ac27e1a)
Xmas version

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[EN3PRO_Linosch.zip](https://github.com/Ultimaker/Cura/files/11834901/EN3PRO_Linosch.zip)
I just left the settings at the default value, changing any settings didn't improve anything really...

**Comment by GregValiant** [comment]
Thanks for the report and the file.
There are 73 support settings and they need to be adjusted in order to get the support you require.

This is the project with your printer and your settings in 5.4.1:
![image](https://github.com/Ultimaker/Cura/assets/64202104/7037d2b5-5776-4346-afe7-63f7860356b4)

This is my printer with my normal "untweaked" support settings.  With some adjusting I know I could do better.  This is also with 5.4.1:
![image](https://github.com/Ultimaker/Cura/assets/64202104/f5c49ff8-3037-489b-866c-d1b57fa58fe6)

I'll remove the bug label from this as it certainly appears to be a settings issue and I'll go ahead and close this.  I hope you understand.
