### ISSUE TITLE
08 Head

### ISSUE THREAD

**Issue by onkelmasca** [Ultimaker/Cura#15894]
### Cura Version

5.3.1

### Operating System

Windows 11

### Printer

Aquila X2

### Describe your model

yes

### Add your .zip here ⬇️

[08head.zip](https://github.com/Ultimaker/Cura/files/11855812/08head.zip)
[CFFFP_08head.zip](https://github.com/Ultimaker/Cura/files/11855813/CFFFP_08head.zip)

**Comment by MariMakes** [comment]
Hi @onkelmasca,

Welcome to the UltiMaker Cura Github 🚀 
Sorry, it took us a while to get back to you 😞 

The new Cura 5.4 contains the fix for this for a number of slicing crashes. 
I was able to slice your model successfully in 5.4 Stable.
![image](https://github.com/Ultimaker/Cura/assets/40423138/7b24eaa7-72d5-4cd7-8388-cc60b787e750)

Could you test if that's the case for you as well? 
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.4.0

If you still run into a crash, please double-check if you shared the correct file and let us know.
I'll take another look at what is going wrong. 👍
