### ISSUE TITLE
Unexpected behaviour for adaptive layers

### ISSUE THREAD

**Issue by rcpoison** [Ultimaker/Cura#15903]
### Application Version

5.3.1

### Operating System

Linux

### Printer

Flsun Q5

### Reproduction steps

First time I've ever seen this, usually works like a charm.
Sliced model with vertical curves. 

### Actual results

Sections without any vertical details do not get sliced at max layer height.

### Expected results

As expected, the layers with more vertical curvature result in smaller layer height.
But below/above the cutout, it doesn't slice at max layer height

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Additional information & file uploads

[adaptiveLayers.zip](https://github.com/Ultimaker/Cura/files/11858009/adaptiveLayers.zip)
<img width="1280" alt="adaptiveLayers" src="https://github.com/Ultimaker/Cura/assets/281286/38256203-697d-46d4-a3ee-c252ec44a19a">

**Comment by GregValiant** [comment]
Thanks for the report.
I don't understand either.  This slice is with the model buried into the build plate.  It would seem that if a feature was causing Cura to keep the layer height at default that this slice should be at the default.  Instead, it's at Max layer height.
![image](https://github.com/Ultimaker/Cura/assets/64202104/be3c022f-2441-4e3a-8a96-4617b03ba3d7)

Someone from the Cura team will take a look.

**Comment by MariMakes** [comment]
Hey @rcpoison,

I brought your issue up with the team. 
They mentioned that it might be a compounding rounding issue. 
If you increase Adaptive Topography Size, than you see that it's showing more the behavior that you described. 

![image](https://github.com/Ultimaker/Cura/assets/40423138/1f65768c-d0a7-481a-8c81-3073a62cc6d6)

We believe we will not work on this anytime soon and will therefore defer this issue.
Since Cura is open source, you or anyone else is more than welcome to work on this issue and create a pull request yourself.
