### ISSUE TITLE
ERERE

### ISSUE THREAD

**Issue by tongilli77** [Ultimaker/Cura#15911]
### Cura Version

4

### Operating System

3

### Printer

0

### Name abnormal settings

D

### Describe model location

SD

### Describe your model

34

### Add your .zip here ⬇️

SU PROGRAMA ES MUY MALO, SON PESIMOS CON SU PROGRAMA, LAS VERSIONES ANTERIORES FUNCIONABAN MEJOR, NO SABEN UNA MIERDA

**Comment by MariMakes** [comment]
Lo siento, no puedo hablar español.

Please change the tone a bit, we are trying to help you 🥺
I understand that you're frustrated, but we need to work together to get to the bottom of this.
And we cannot do that if you don't fill in the template correctly. 

Since I don't have enough information to troubleshoot, I'll close this ticket.
