### ISSUE TITLE
Cura 5.4 beta 1 won't launch gui

### ISSUE THREAD

**Issue by N6REJ** [Ultimaker/Cura#15981]
### Application Version

5.4 beta 1

### Operating System

window 10 x64 pro

### Printer

Voxelab Aquila S2

### Reproduction steps

install then launch

### Actual results

![image](https://github.com/Ultimaker/Cura/assets/1850089/2a60904d-c63f-4562-816f-40c5a8bb233b)

### Expected results

works just fine.

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[5.4_20230702_062105.zip](https://github.com/Ultimaker/Cura/files/11931618/5.4_20230702_062105.zip)

**Comment by MariMakes** [comment]
Hey @N6REJ,

Thanks for your report 👍

I believe that this is resolved in the 5.4 stable release, you can download the Cura version with the fix here: https://github.com/Ultimaker/Cura/releases/tag/5.4.0
I'll close this issue since it's a duplicate and resolved. 

Thanks again, and please let us know if you run into any other issues 💪
If it's not resolved, let us know and I'll take another look.
