### ISSUE TITLE
Error when opening Cura 5.4.0 - ModuleNotFoundError: No module named 'PyQt6.QtNetwork'

### ISSUE THREAD

**Issue by mzac** [Ultimaker/Cura#16000]
### Application Version

5.4.0

### Operating System

Windows 10

### Printer

Ender 3 Pro

### Reproduction steps

1. Installed Cura 5.4.0
2. Got error
3. Removed Cura 5.4.0
4. Re-downloaded the installer
5. Tried again, got same error

### Actual results

Traceback (most recent call last):
  File "cura_app.py", line 23, in <module>
ModuleNotFoundError: No module named 'PyQt6.QtNetwork'

![image](https://github.com/Ultimaker/Cura/assets/10270879/5675c597-10e8-4b7b-bfda-eaa35d2adb60)

### Expected results

Should not get an error

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

My old Cura 5.3.1 on this same computer still works.

**Comment by MariMakes** [comment]
Hi @mzac,

Thanks for your report 👍
That does not look good 😨 
I'm not getting this error, but it looks serious.

Would you mind sharing your log files. You can find your log file here:
Windows: %APPDATA%\cura\5.4\cura.log

I raised it with the team, hopefully we can prevent more people from running into this error. 
Fingers crossed 🤞

**Comment by mzac** [comment]
> Hi @mzac,
> 
> Thanks for your report 👍 That does not look good 😨 I'm not getting this error, maybe because I've already had Cura 5.4 beta installed, but it looks serious.
> 
> Would you mind sharing your log files. You can find your log file here: Windows: %APPDATA%\cura\5.4\cura.log
> 
> I raised it with the team, hopefully we can prevent more people from running into this error. Fingers crossed 🤞

Hm, this sucks, it didn't create a log file and nothing about 5.4 in the stderr.log  Anything else I can check?

![image](https://github.com/Ultimaker/Cura/assets/10270879/05d79702-d7ba-4666-a045-81c8baedf84f)

**Comment by Hedan-13** [comment]
Hi!!! GM
I'm having the same problem. Just about 10 minutes download from the official site of Ultimaker, install Cura 5.4.0 and get this error. My Cura 5.3.1 still works. 
Also, didn't create any log file for 5.4
TX!!!
![image](https://github.com/Ultimaker/Cura/assets/107428041/a06d8252-eee2-45e4-a8c1-f8c1cd79132c)

**Comment by janderek** [comment]
Getting the same fail, just tried to install at a win10 machine, and then it dosnt fail, but on my win11 machine it wont work, 

as the others, the 5.3.1 i still working

**Comment by leftoverjacksons** [comment]
Having the exact same issue, windows 11

**Comment by Nasersanji** [comment]
I have exact the same! :(

**Comment by MariMakes** [comment]
Hey all,

We discussed this issue with the team.
We are a bit at a loss what is happening here 😖 

Can you try the following things?
- Can you try to install the MSI instead of the .EXE? You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.4.0
- Can you try to run the program as an administrator?  
![image](https://github.com/Ultimaker/Cura/assets/40423138/8b3da03b-702f-4b58-a715-c848606f0a18)

Please let us know if these options do or do not work for you, then we'll try to have another look.

**Comment by Hedan-13** [comment]
Good news!!! After unistalling the version 5.3.1, and deleting all the files related to older versions. Run the MSI as administrator and now is working.  
![image](https://github.com/Ultimaker/Cura/assets/107428041/79ebaa28-27c4-47d4-83e9-83e36cde52b0)

**Comment by mzac** [comment]
I also tried the MSI vs the EXE and it worked.  Didn't have to remove 5.3.1 or run as administrator, it just works.  Thanks for looking into this but it would still be nice to understand what went wrong here.

**Comment by MariMakes** [comment]
Hey all,

Thanks for reporting back!
I'm glad we found a workaround. 😊 

I would also like to understand what was going wrong here. I believe it's related to the updated PyQT library we introduced to fix a host of issues. You can read more about it here: https://github.com/Ultimaker/Cura/discussions/15098

To me, it doesn't seem like a bug in Ultimaker Cura, since we have a solution in place. 
I'll be closing this issue. I hope you understand.
