### ISSUE TITLE
File overwrite dialog buttons are in Dutch but English is selected

### ISSUE THREAD

**Issue by rondlh** [Ultimaker/Cura#16014]
### Cura Version

5.4.0

### Operating System

Windows 10 x64

### Printer

Custom, Marlin

### Reproduction steps

The file overwrite dialog buttons are in Dutch. Just write a gcode file to a file that already exists.
![File Overwrite Dialog](https://github.com/Ultimaker/Cura/assets/77279634/33def03c-be03-4a91-b435-a1506484ae7a)
Note that the title of the dialog is in English. Cura is set to English.

### Actual results

Wrong language in file overwrite dialog buttons.

### Expected results

The dialog buttons should be according to the set language, English in my case.

### Add your .zip and screenshots here ⬇️

![File Overwrite Dialog](https://github.com/Ultimaker/Cura/assets/77279634/43882a9c-9281-4e10-92cf-5f92eefb78cd)

**Comment by MariMakes** [comment]
Hey @rondlh,

Thanks for your report 👍
I believe I've seen this before. If I remember correctly Cura takes the defaults of your computer for these buttons, but I'll have to doublecheck.

I'll bring it up to the team to see what they can do to improve it. But I expect that if it's not a quick fix that it will not get a high priority to implement. Fingers crossed 🤞

**Comment by MariMakes** [comment]
Hey @rondlh,

I've discussed this with the team. 
We believe we will not work on this anytime soon and will therefore defer this issue.
Since Cura is open source, you or anyone else is more than welcome to work on this issue and create a pull request yourself.

P.S. Unfortunately, non-planar slicing is such a fundamental change in Cura, that I don't expect that any time soon.
