### ISSUE TITLE
hole horizontal expansion ERROR

### ISSUE THREAD

**Issue by MBogballe** [Ultimaker/Cura#16037]
### Cura Version

5.3.0 /5.3.1 / 5.4.0

### Operating System

windows 11

### Printer

ender 5 plus / anet a8 plus / DIY

### Reproduction steps

I use your function to adjust holes in the blanks (hole horizontal expansion) but as soon as I fix it it starts making holes in my blanks where there are no holes at all, it worked really well up to V5.2.2 but there after that it starts to make holes in the subjects

### Actual results

I use your function to adjust holes in the blanks (hole horizontal expansion) but as soon as I fix it it starts making holes in my blanks where there are no holes at all, it worked really well up to V5.2.2 but there after that it starts to make holes in the subjects

### Expected results

I use your function to adjust holes in the blanks (hole horizontal expansion) but as soon as I fix it it starts making holes in my blanks where there are no holes at all, it worked really well up to V5.2.2 but there after that it starts to make holes in the subjects

### Add your .zip and screenshots here ⬇️

![5 2 0](https://github.com/Ultimaker/Cura/assets/93795426/f94f9f04-e4d3-4317-be47-c74b71bc077f)
![5 3 1](https://github.com/Ultimaker/Cura/assets/93795426/08cbeb86-7acc-4d31-a80a-70edea21dbb9)
![5,2,2](https://github.com/Ultimaker/Cura/assets/93795426/90f91604-31c2-4580-ba71-6e23fb7d011a)
![5 4 0](https://github.com/Ultimaker/Cura/assets/93795426/578985e1-7879-4e1f-a161-db861e12ed45)
[toyota logo-GG001.zip](https://github.com/Ultimaker/Cura/files/11971349/toyota.logo-GG001.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
That is pretty bizarre and I can confirm the problem when using your model.
The real problem appears to be the model file.  The STL file has 3 separate meshes in it rather than a single mesh.
After using MS 3D Builder to merge the meshes there is no problem.
This is with the Hole Horizontal Expansion at 0.20 on the repaired file.
![image](https://github.com/Ultimaker/Cura/assets/64202104/ec56d851-c0da-4f38-a942-100d1041c983)

I'll go ahead and remove the bug label and close this as it is a model problem.  Let me know if you feel that is premature.
