### ISSUE TITLE
USB online connection to print

### ISSUE THREAD

**Issue by alimi67** [Ultimaker/Cura#16042]
### Cura Version

5.3

### Operating System

windows 11

### Printer

custom printer(marlin)

### Reproduction steps

1.the printer connected to cura and active "monitor" tab
2.usb print pluggin is active
3.the hotend temperature is show 0 in monitor tab and it dose not preheat or print
![1](https://github.com/Ultimaker/Cura/assets/132000582/ac6a0502-8adb-42d1-9e01-048a89a8dd20)
![2](https://github.com/Ultimaker/Cura/assets/132000582/9a08c5a3-1a1d-4bb8-9e5c-49e4c22f4483)

### Actual results

nothing

### Expected results

nothing

### Add your .zip and screenshots here ⬇️

[CFFFP_one_line_Fahrrad_v1.zip](https://github.com/Ultimaker/Cura/files/11977386/CFFFP_one_line_Fahrrad_v1.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
USB Printing is a legacy feature that has been left in Cura since some people like to use it.  It has not been maintained in a few years.  Since Cura is open source anyone could try to fix it, but no one has tried.  There are some many hardware and software configurations out there that it is really impossible to get it to work with every combination.
In addition, no UltiMaker printers use USB Printing and so the UltiMaker Company will not put their time and money into updating USB Printing.
I'll go ahead and close this.  It's one of those things where it either works or it doesn't.

If you have a good connection to the printer then sending G28 should auto-home.  If that doesn't work then my guess would be that it's a baud rate issue.
