### ISSUE TITLE
Standard Supports Have Strange Patterns Cut Out

### ISSUE THREAD

**Issue by AlexCStem** [Ultimaker/Cura#16041]
### Cura Version

5.4.0

### Operating System

Windows 11

### Printer

CR-10 Smart Pro

### Reproduction steps

1. Slice an STL with a horizontal overhang using standard Normal support settings for Everywhere.
2. Look at the Preview of the suports.

### Actual results

The supports have a strange pattern cut out of them that seem to change with part orientation
![Screenshot 2023-07-06 193241](https://github.com/Ultimaker/Cura/assets/50191171/b59a75c8-98b3-4857-97f5-89bb72bc8873)

### Expected results

The supports on this part should look like the attached image of the same part sliced using the same settings on Cura 5.3.1
![Screenshot 2023-07-06 193305](https://github.com/Ultimaker/Cura/assets/50191171/b92b3597-4f51-46b5-977b-ea7d8bf9c9ed)

### Add your .zip and screenshots here ⬇️

[Cura 5.4.0 Supports Issue.zip](https://github.com/Ultimaker/Cura/files/11973770/Cura.5.4.0.Supports.Issue.zip)

**Comment by GregValiant** [comment]
Thanks for the report and the file.
I get this when I slice your project.  "Support Wall Line Count" set to 1.
![image](https://github.com/Ultimaker/Cura/assets/64202104/7da102e6-4ae0-411e-806d-cfa3561286bf)

This is the result of having "Support Wall Line Count" set to 0 and "Connect Support Lines" enabled.
The orientation of the support infill lines is governed by the Support Infill Line Directions setting.  The directions have no relation to the part orientation.
![image](https://github.com/Ultimaker/Cura/assets/64202104/5a8785a8-5f36-4553-8eb2-62583287d075)

So this is expected behavior given the settings you are using.  I'll go ahead and remove the bug label and close this.  I hope you understand.
