### ISSUE TITLE
Weight of filament used calculated incorrectly for small amounts

### ISSUE THREAD

**Issue by gbarbehenn** [Ultimaker/Cura#16150]
### Cura Version

5.3.1

### Operating System

windows 10

### Printer

Monoprice Maker Select v2

### Reproduction steps

Slice something that uses less than 1m of filament, in my case, it was 0.12m of PLA+.  The 1.75mm PLA+ filament has a density of ≈ 3.05g/m, so 0.12m should be 0.366g.

### Actual results

Cura reported 0.12m and *0g* of filament used.

### Expected results

0.12m and 3.7g of filament used.

### Add your .zip and screenshots here ⬇️

[H-B fix.zip](https://github.com/Ultimaker/Cura/files/12053309/H-B.fix.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
The stats above the slice button are rounded to the nearest Gram so 0.366 = 0.
There is an "i" in a circle to the right of that.  If you hover the mouse you will see the number rounded to 1/10 of a Gram which in this case means that 0.366 is rounded to 0.4g.

I'll go ahead and remove the bug label and close this as it is the way the numbers are displayed rather than an error.
![image](https://github.com/Ultimaker/Cura/assets/64202104/c6ed5459-58bb-4591-bdd5-955bd2f43313)
