### ISSUE TITLE
Inadequate tree supports

### ISSUE THREAD

**Issue by wzydhek** [Ultimaker/Cura#16208]
### Cura Version

5.4.0

### Operating System

Windows 10

### Printer

Ender 5 Plus

### Reproduction steps

Attempting to slice and print Chucky (https://www.thingiverse.com/thing:4101482) scaled to 800%.

- Tree Supports
- Minimum Branch Angle: 45 to 70 degrees
- Support Placement: Buildplate only
- Support Overhang Model: 20 to 60 degrees
- Support Z Distance 0 and 0.2
- Limit Branch Reach: disabled
- Tried Support blocker and per model settings with no effect

### Actual results

Tree supports only generated for tip of knife, which were not strong/sturdy enough to support the knife all the way up. Knife always breaks off supports. Unable to create supports further along knife edge using tree supports. Per Model Settings ignored modified support overhang angle setting.

### Expected results

Expected Per Model Setting for Support Overhang Angle to force overhangs to be supported a shallower angle than rest of model.

### Add your .zip and screenshots here ⬇️

[Medieval_Chucky.zip](https://github.com/Ultimaker/Cura/files/12083736/Medieval_Chucky.zip)
![Screenshot 2023-07-18 093845](https://github.com/Ultimaker/Cura/assets/12603409/7c8df93d-7b00-41c9-b1ba-70738638be07)
![Screenshot 2023-07-18 093845_missing_support](https://github.com/Ultimaker/Cura/assets/12603409/5d38913a-2d27-4c89-bd2e-da75f2491af4)

**Comment by GregValiant** [comment]
Thanks for the report and the file.
There are 73 support settings and a lot of them affect other support settings.  There are some contradictions in your settings like the Minimum Support Area set to 2.0 but the Minimum Support Interface Area set to 10.

I re-selected the "Standard" profile and discarded all your changes.  I enabled Tree supports and Touching Buildplate.
This is with the Overhang Support Angle at the standard 45°.  I would say it needs further tweaking, but the knife blade gets supported.
![image](https://github.com/Ultimaker/Cura/assets/64202104/94279b0a-ccb2-4751-a64b-f6f0d709a88d)

I'll leave this open so you can respond, but this appears to be a setting issue rather than a bug so I'll remove the bug label.  I hope you understand.
