### ISSUE TITLE
Missing Translations in Beta

### ISSUE THREAD

**Issue by TomEmmelot** [Ultimaker/Cura#16242]
### Cura Version

5.4.0 beta 1

### Operating System

Windows 11

### Printer

Vertex delta K8800

### Reproduction steps

There are a lot of English text in the Dutch version also not translated explanations.  
On this point i wish to make a statement that someone of Ultimaker must take over the work of Ghostkeeper to keep "Settings guide" up to date for more extensive explanations. I as the translator of the Dutch version of the Guide, think it is your duty!

### Actual results

It is a mesh now

### Expected results

Making mistakes

### Add your .zip and screenshots here ⬇️

![2023-07-20 13_42_56-Cura Settings Guide (2 9 2)](https://github.com/Ultimaker/Cura/assets/47352581/0623966d-6761-4ce3-9936-db8effe1391e)

**Comment by MariMakes** [comment]
Hey @TomEmmelot,

Thanks for your report 👍

I see you are reporting this issue on the 5.4 Beta release. We use the Beta period to collect translations. It's a moment in time where we have finished all the features we want to release and there are no new settings introduced. What you are highlighting here are all new or updated settings in 5.4 that have been sent to the translators. 

The correct translations are available in Cura 5.4 stable, if you are in doubt, you can double check them here: https://github.com/Ultimaker/Cura/blob/3d289d75f97810955aa8402f53e4f8c716d6a654/resources/i18n/nl_NL/fdmprinter.def.json.po#L295-L297

You can download the Cura version with the updated translations here: https://github.com/Ultimaker/Cura/releases/tag/5.4.0
I'll close this issue since it's resolved I hope you understand. 

If you run into any incorrect Dutch translations we would love to learn about them in a new issue. 
I can even teach you how to submit a pull request to request them to be fixed.
