### ISSUE TITLE
Scaled model with tree support and adaptive layer height fails to slice

### ISSUE THREAD

**Issue by torndar** [Ultimaker/Cura#16272]
### Cura Version

5.4.0

### Operating System

Windows 10

### Printer

Creality Ender-3 V2

### Name abnormal settings

Adapative layer height, model scaling, tree support, brim

### Describe model location

Regular orientation, centered on build plate

### Describe your model

It works with default standard quality. A winged panther with wings that need a lot of support. The uploaded project settings work when the model is scaled to 200% but fails at 250%. Also works at 300%

### Add your .zip here ⬇️

[CE3E3V2_dragon_panther.zip](https://github.com/Ultimaker/Cura/files/12163286/CE3E3V2_dragon_panther.zip)

**Comment by torndar** [comment]
If there is a log or a command line parameter I can use to have it create a log or crash dump I'm happy to grab/create it and add it to this bug.

**Comment by GregValiant** [comment]
There are a lot of error-free models that 5.4.0 refuses to slice.
If you go to the MarketPlace you can load "Extensive Support Logging" plugin.  It will add more info to the log file.
The log file can be located using the "Help | Show Configuration Folder" command.  It's the Cura.log file.

**Comment by torndar** [comment]
It seems like just moving the model around on the bed will change success/failure of slicing. I've added a different model also failing to slice and the Cura log with "Extensive Support Logging" installed for a failed slice.
[cura.log](https://github.com/Ultimaker/Cura/files/12209484/cura.log)
[Fridge 400mm can tray.zip](https://github.com/Ultimaker/Cura/files/12209491/Fridge.400mm.can.tray.zip)

**Comment by GregValiant** [comment]
I think that moving or rotating the model changes the way Cura "sees" the model.  Changing the "Initial Layer Height" moves the slice slightly up or down within the model and so that also gives a different "view" of the model.

It obviously should not be necessary to go through such gyrations with the model to get it to slice.  Models that have errors are a different story.  Some errors are significant enough that the model might slice, but can you trust the slice?  Other models just don't slice because the errors are too severe.  The Cura "Mesh Tools" plugin is a very nice utility, but it is limited in what it can repair so having a more capable repair utility to go to (I like MS 3D Builder) is necessary.

And there is this error from your log file:
**"Backend exited abnormally with return code 3221225477!"**
My understanding is that is a code for a memory error.  I'm not savvy enough to know what error it is or why it occurs.  This is the first report of it happening in 5.4.0 but there were a lot of reports for 5.3.1.

The Cura team will take a look.

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
