### ISSUE TITLE
Support interface function supports properly Extruder1 only

### ISSUE THREAD

**Issue by zolee1209** [Ultimaker/Cura#16317]
### Cura Version

5.4.0

### Operating System

Windows 10 64bit

### Printer

Custom FFF

### Reproduction steps

Slicer does not create support interface layer when the support interface extruder is Extruder2. Or at least, not Extruder1.
It does not matter, what are the other extruder settings in this Support class.
As far as i tested, this function works fine in the Cura 4.13.1 and not from 5.x 

### Actual results

There is no possibility to print the model and support with Extruder1 and the support interface with Extruder2.

### Expected results

As above in the actual results.

### Add your .zip and screenshots here ⬇️

[_support_interface_test.zip](https://github.com/Ultimaker/Cura/files/12207323/_support_interface_test.zip)
![If_SI1_used](https://github.com/Ultimaker/Cura/assets/140896949/843f652a-3b40-4493-a4fc-fad61c0aea58)
![M1_S1_SI2_line](https://github.com/Ultimaker/Cura/assets/140896949/85636668-76e5-41ee-9b42-143c1838a21a)
![M1_S1_SI2_material](https://github.com/Ultimaker/Cura/assets/140896949/020962cd-2497-4c60-88c7-0c5c59b88a38)
![M1_S1_SI1](https://github.com/Ultimaker/Cura/assets/140896949/816ee097-5876-4bff-aaee-c687d78c801f)
![M1_S2_SI1](https://github.com/Ultimaker/Cura/assets/140896949/73fba2a2-2799-41c1-9a68-b03c2fe69491)
![M2_S2_SI1](https://github.com/Ultimaker/Cura/assets/140896949/0c0fb745-227f-446f-959e-54a9b967dd63)

**Comment by GregValiant** [comment]
Thanks for the report.
It doesn't work for your JG Artist printer because the "Enable Support Interface" checkbox is grayed out and can't be enabled. 
 It does work for other dual extruder printers.
This is in 5.4.0 with a dual extruder Ender.
![image](https://github.com/Ultimaker/Cura/assets/64202104/f4e1ac55-88a9-4200-9fea-168deb3921c8)

This is with a Sovol SV02
![image](https://github.com/Ultimaker/Cura/assets/64202104/cc217c17-f3c5-49b5-b564-16c4a3c41646)

This is with your printer.  Notice that the Enable Support Interface is grayed out and not available.
![image](https://github.com/Ultimaker/Cura/assets/64202104/715a1abe-2c0a-4c68-bf4d-24513095f890)

If you used a Custom FFF printer the fdmprinter.def.json file says this about "support_interface_enable":
"enabled": "support_enable or support_meshes_present"
Both of those are true in your project so the setting should be enabled.  Which extruder is assigned to Support Interface isn't involved.

Is there some printer definition file or other file that might have overridden that setting?

**Comment by zolee1209** [comment]
> Thanks for the report. It doesn't work for your JG Artist printer because the "Enable Support Interface" checkbox is grayed out and can't be enabled. It does work for other dual extruder printers. This is in 5.4.0 with a dual extruder Ender. ![image](https://user-images.githubusercontent.com/64202104/257003912-f4e1ac55-88a9-4200-9fea-168deb3921c8.png)
> 
> This is with a Sovol SV02 ![image](https://user-images.githubusercontent.com/64202104/257004042-cc217c17-f3c5-49b5-b564-16c4a3c41646.png)
> 
> This is with your printer. Notice that the Enable Support Interface is grayed out and not available. ![image](https://user-images.githubusercontent.com/64202104/257005562-715a1abe-2c0a-4c68-bf4d-24513095f890.png)
> 
> If you used a Custom FFF printer the fdmprinter.def.json file says this about "support_interface_enable": "enabled": "support_enable or support_meshes_present" Both of those are true in your project so the setting should be enabled. Which extruder is assigned to Support Interface isn't involved.
> 
> Is there some printer definition file or other file that might have overridden that setting?

Thanks for the reply and sorry for the late response from my side.

The Enable Support Interface checkbox was always inactive on my side, even in the 4.x versions, but worked fine.
I do not have any additional printer definition file or some like this or at least i do not know about it.
I made this printer configuration in an earlier version of Cura and i just imported it with a *.3mf file.
I will try to create a new printer in the current version and see if it behaves differently.

**Comment by GregValiant** [comment]
I still haven't figured out why this happened but the two children settings "Enable Support Roof" and "Enable Support Floor" have come un-linked from the parent setting.  It seems to have happened because of manual changes to the "Fine" profile.

To the right of "Fine" in the profile selection box is a circle with an arrow on it.  It's the reset button.  Click on that and "Enable Support Interface" will work as it should.
You will have to go back and make manual changes to the profile (enable the interface, set the interface to Extruder 2, etc) but it worked for me.

**Comment by zolee1209** [comment]
I made some tests...
At first, i made a new printer with the same settings, but that didn't solve the problem. The "Enable Support Interface" checkbox remained unactivated.
My next step was that i resetted the Print settings profile, and after that, the checkbox can be activated.
I copied manually all settings of both extruder from the "bad" settings, but the checkbox remained activateable.
I also noticed that although the checkbox is inactive, when displaying the other parameters, the system takes it as activated in the "wrong" configuration.

I'm just guessing that some imported settings are corrupting it, because after I reset the profile and set the old parameters, it works properly.

**Comment by zolee1209** [comment]
> I still haven't figured out why this happened but the two children settings "Enable Support Roof" and "Enable Support Floor" have come un-linked from the parent setting. It seems to have happened because of manual changes to the "Fine" profile.
> 
> To the right of "Fine" in the profile selection box is a circle with an arrow on it. It's the reset button. Click on that and "Enable Support Interface" will work as it should. You will have to go back and make manual changes to the profile (enable the interface, set the interface to Extruder 2, etc) but it worked for me.

Yes, that's exactly what I did and it solved the problem. ;)
Thanks for the help!
