### ISSUE TITLE
Small Top/Bottom Width Setting Not Showing Up

### ISSUE THREAD

**Issue by kaitrek** [Ultimaker/Cura#16356]
### Cura Version

5.4.0

### Operating System

MacOS Monterey

### Printer

CUSTOM FFF

### Reproduction steps

In Settings->Configure setting visibility... under Top/Bottom, the "Small Top/Bottom Width" is check marked.
Then look at the Print Settings under Top/Bottom for "Small Top/Bottom Width" but it does not appear.

### Actual results

Search does not show "Small Top/Bottom Width" and it's missing inbetween 2 settings where it's supposed to be.

### Expected results

Expecting the "Small Top/Bottom Width" to appear in Print Settings.

### Add your .zip and screenshots here ⬇️

<img width="1108" alt="image" src="https://github.com/Ultimaker/Cura/assets/24997534/c89f7f22-297f-495c-b93f-2a6e048a164c">

**Comment by GregValiant** [comment]
Thanks for the report.
Some of the settings are not visible for certain machines or extruder counts or other reasons.  In the case of this setting:
From the fdmprinter.def.json file...

"label": "Small Top/Bottom Width",
"comment": "**Disabled for 5.4.x**, as we're worried about micro-segments in the infill. Also disabled in the engine, so forcing this > 0 will not do anything at the moment."

So this is not a bug but expected behavior.  I hope you understand.
