### ISSUE TITLE
Slice Failed

### ISSUE THREAD

**Issue by jerry110** [Ultimaker/Cura#16380]
### Cura Version

5.4.0

### Operating System

Windows 11

### Printer

ender 3 custom

### Describe your model

boot drier

### Add your .zip here ⬇️

[CE3PRO_Dryer.zip](https://github.com/Ultimaker/Cura/files/12258647/CE3PRO_Dryer.zip)

**Comment by GregValiant** [comment]
Thanks for the report and the file.
This sliced for me on the first try.
There is a persistent bug in 5.4 that can keep a model from slicing.  There are 3 workarounds that alone or in combination can often fool the bug.

- Move the model to a different point on the Cura build plate.
- Rotate the model in Cura
- Make a small change to the Initial Layer Height (like from .20 to .23).

I'll mark this as a duplicate.  Let us know if those will allow this to slice for you.
![image](https://github.com/Ultimaker/Cura/assets/64202104/2740b2c6-87a8-40bb-9886-b70142e7164a)

**Comment by jerry110** [comment]
> Thanks for the report and the file. This sliced for me on the first try. There is a persistent bug in 5.4 that can keep a model from slicing. There are 3 workarounds that alone or in combination can often fool the bug.
> 
> * Move the model to a different point on the Cura build plate.
> * Rotate the model in Cura
> * Make a small change to the Initial Layer Height (like from .20 to .23).
> 
> I'll mark this as a duplicate. Let us know if those will allow this to slice for you. ![image](https://user-images.githubusercontent.com/64202104/258409930-2740b2c6-87a8-40bb-9886-b70142e7164a.png)

Did all three also it gives the error once and if you slice it again it locks the computer up hard
it works fine on my laptop slices just fine. same profile same settings ........

**Comment by GregValiant** [comment]
_"it works fine on my laptop..."_
Can you tell us more about the computer that is having the problem?  You can post a screenshot of the Windows "Settings - System - About" dialog.
What version of Windows does the laptop run?

**Comment by jerry110** [comment]
Yep now i'm not able to slice anything......The laptop runs the same exact version of windows as my desktop
![Screenshot 2023-08-04 181433](https://github.com/Ultimaker/Cura/assets/6697716/747ea3d6-cde8-42f8-95bb-aac8fecf8d36)

**Comment by jerry110** [comment]
i tried downgrading to 5.3.1 same issue

**Comment by jerry110** [comment]
Just an update i fixed the slicing issue. In the bios i changed SVID Behavior from Best Case to Trained and cura now slices no problem.......

**Comment by GregValiant** [comment]
Thanks for getting back with that.  I don't know if that is something that @rburema might be aware of?  (Windows 11 has had a couple of issues.)
I'll leave this open for the Cura team.

**Comment by jerry110** [comment]
Cool.... that's the only change i made in a controlled test. error reboot change reboot it slices

**Comment by rburema** [comment]
Well, that's a new one.

From reading up on it, it shouldn't influence behaviour like that at all, so there's probably something that 'goes right on accident' on our side, or some sort of bug with that BIOS setting.

I have no idea how to even begin testing for this (especially since we don't have that hardware), but I'll ask my colleagues.

**Comment by jerry110** [comment]
Well i can give you detailed specs on my machine if that helps ? but yeah weird thing

**Comment by rburema** [comment]
Thanks, yes. To be honest I don't give it much chance, but that _is_ indeed the sort of info we would need we do decide to get to the bottom of this.

**Comment by rburema** [comment]
Did some more research on this. SVID, especially the 'Best Case' option, seems to be related to overclocking (which some vendors out of the box, so it's not necessarily something you have to set up yourself).

For example, I was able to find this discussion: https://forums.tomshardware.com/threads/svid-best-case-scenario-give-me-bsod.3635099/

As such, we think it's highly likely that the problem here is not on our side, and regardless, there'll be very little we can do.
