### ISSUE TITLE
Last command disables Z stepper.

### ISSUE THREAD

**Issue by mattiasthalen** [Ultimaker/Cura#16403]
### Cura Version

5.4.0

### Operating System

macOS Ventura

### Printer

Creality Ender-3 v2 Neo

### Reproduction steps

Slice any print.
Print it.

### Actual results

Watch how Z comes falling down, sometimes hitting the print.

### Expected results

Z stays in its place.

### Add your .zip and screenshots here ⬇️

End G-code:
```
G91 ;Relative positioning
G1 E-2 F2700 ;Retract a bit
G1 E-2 Z0.2 F2400 ;Retract and raise Z
G1 X5 Y5 F3000 ;Wipe out
G1 Z10 ;Raise Z more
G90 ;Absolute positioning

G1 X0 Y{machine_depth} ;Present print
M106 S0 ;Turn-off fan
M104 S0 ;Turn-off hotend
M140 S0 ;Turn-off bed

M84 X Y E ;Disable all steppers but Z
```

**Comment by GregValiant** [comment]
Thanks for the report.
The definition files come from members of the community, or from the printer manufacturer.  Ultimaker has no way to check the definitions for all those other printers so I'll remove the bug label from this and go ahead and close it.  Let me know if you feel that is premature.

That is the same Ending Gcode as my Ender 3 Pro and it works correctly for me.  It says right there "M84 X Y E ;Disable all steppers but Z" so that's what the printer should do.
The default stepper time-out for the Ender's is 2 minutes.  If it takes you longer than that to get to the printer, and you have a loose Z axis, then the stepper will disable automatically 2 minutes after the print ends and the Z could slide down.  You would need to add "M84 S3600" just ahead of the existing M84 line.  That will give you 1 hour to get to the printer (instead of the 2 minutes).  M84/M18 will automatically reset to 2 minutes if and when the steppers disable.  
The line "G1 X0 Y{machine_depth} ;Present print" sends the print head to the back left corner of the build surface.  99.9% of the time that should be well out of the way.

I'm curious as to why you think this is a bug in Cura.  The command is there so if the printer is not following the command or you are slow to get to the printer when it finishes, the problem would seem to lie elsewhere.
