### ISSUE TITLE
Fan Speed Overide does not work with walls 

### ISSUE THREAD

**Issue by uoutac** [Ultimaker/Cura#16409]
### Cura Version

5.4.0

### Operating System

Windows 11

### Printer

Anycubic Kobra 

### Reproduction steps

1. Check box for "Fan Speed Override" 
2. Select a high number of wall lines

### Actual results

No gcode generated to change fan speed (M106 command is not given at the layer above support)

### Expected results

Gcode is generated to ramp fan to selected speed

### Add your .zip and screenshots here ⬇️

This bug is similar to #13457, however, the support interface setting had no effect on whether fan speed override work or not. 
[AK_half_bridge_test.zip](https://github.com/Ultimaker/Cura/files/12270496/AK_half_bridge_test.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
You are correct, the override does not work for walls.  As it states in the help balloon _"When enabled, the print cooling fan speed is altered **for the skin regions** immediately above the support."_ so this is expected behavior.

I'll remove the bug  label from this and close it.  If you need this functionality you could put in a feature request.  I hope you understand.
