### ISSUE TITLE
Tasa Ford Antiguo

### ISSUE THREAD

**Issue by rpmentz** [Ultimaker/Cura#16424]
### Cura Version

5.4.0

### Operating System

Windows 11 pro

### Printer

Ultimaker S5 pro

### Describe model location

Model is circular

### Describe your model

Have sliced it before, only once could do it.

### Add your .zip here ⬇️

[UMS5_tasa 9a2 corregida.zip](https://github.com/Ultimaker/Cura/files/12291185/UMS5_tasa.9a2.corregida.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
I managed to get this to slice by changing the Initial Layer Height to 0.23 and rotating the model 90°ccw.

This is a known bug so I'll mark this as a duplicate.  I'll go ahead and close this as well since the Cura Team has a lot of examples of this behavior.  I hope you understand.
![image](https://github.com/Ultimaker/Cura/assets/64202104/919a4d40-ceff-43da-94ce-70415514b281)
