### ISSUE TITLE
Large figure won't slice until well below the size I need

### ISSUE THREAD

**Issue by f4r4m** [Ultimaker/Cura#16457]
### Cura Version

5.4.0

### Operating System

Windows 10

### Printer

AnyCubic Mega X

### Name abnormal settings

Changed the size. 

### Describe model location

In the center, tried moving and rotating, didn't work

### Describe your model

Was able to slice it at 125mm tall, but not taller.

### Add your .zip here ⬇️

Trying to print the model 200mm tall, but experience unable to crash at 150mm. I was able to slice it at 125mm with Draft settings, but it won't slice for anything finer.

The file size is too large for me to submit in this form.

**Comment by GregValiant** [comment]
Thanks for the report.
It's tough without the file but one of the workarounds for the bug is to change the Initial Layer Height by a small amount (like 0.20 to 0.23).
There can be issues with scaling a model up.  If there are tiny errors in the model those errors also scale up,  What might have fallen below Cura's notice has been scaled up enough to be a problem.  If you scale the model up the way you want to print it and then export the model you may find a utility that can check and hopefully (if this is the problem) repair it.
You are on Windows and MS 3D Builder is pretty good at fixing models.

Back to the bug...this sounds like it involves the same bug that has been reported numerous times.  I'll mark this as a duplicate and go ahead and close this one as the Cura team has a lot of examples of the behavior.  I hope you understand.
