### ISSUE TITLE
Not Making Copies

### ISSUE THREAD

**Issue by CODYP68** [Ultimaker/Cura#16519]
### Cura Version

3.6.0

### Operating System

Windows 10

### Printer

CrealityBelt Cr-30

### Reproduction steps

Setup slicer profile
Selected 2 copies in crealitybelt setting
Slice project

### Actual results

Copies and all corresponding crealitybelt setting return to default setting, and printer only made one copy of the print.

### Expected results

The setting should have remained and the printer should have printed 2 parts

### Add your .zip and screenshots here ⬇️

![before](https://github.com/Ultimaker/Cura/assets/142686346/5bdd02b9-9a26-4592-acf5-6875697e8f6b)
![After](https://github.com/Ultimaker/Cura/assets/142686346/519f85ed-08c8-4bac-87a9-b8697e70e140)
[CODYP68_crealitybelt Profile.zip](https://github.com/Ultimaker/Cura/files/12386431/CODYP68_crealitybelt.Profile.zip)

**Comment by fieldOfView** [comment]
This is not Ultimaker Cura. It looks like a version that has been heavily modified from a version of Blackbelt Cura, which by itself is a heavy modification of an old, no longer supported version of Ultimaker Cura. You are going to have to ask the people who modified it to support it.

I will close this issue because the people here don't know what has been modified, and will not be able to apply fixes to that version of Cura.
