### ISSUE TITLE
Brim Replaces Support Fails to Generate Correctly and Consistently

### ISSUE THREAD

**Issue by kaitrek** [Ultimaker/Cura#16544]
### Cura Version

5.4.0

### Operating System

MacOS Monterey

### Printer

Custom FFF

### Reproduction steps

1. Use Auto Tower generator for a temperature tower
2. Add Anti-Warping Tabs (addon) to the corners of the tower
3. Enable Brim Support
4. Enable Brim Replaces Support

### Actual results

On the right side, brim generates underneath the tabs.
On the left side, brim goes around the support tabs and with weird inconsistent shapes.
<img width="973" alt="image" src="https://github.com/Ultimaker/Cura/assets/24997534/76c519d7-bc7f-4cce-b7ab-59448587c42a">

<img width="474" alt="image" src="https://github.com/Ultimaker/Cura/assets/24997534/45e3af11-957b-4edf-bced-f69f9550f520">
vs
<img width="629" alt="image" src="https://github.com/Ultimaker/Cura/assets/24997534/2d7a4e9e-56f8-4d0d-90b1-61677e814e51">

### Expected results

Expect when Brim Replaces Support option to be enabled that brim generates underneath support elements like mouse ears/anti-warping tabs, etc.

### Add your .zip and screenshots here ⬇️

[Custom Temp Tower - 270.0-240.0x-5.0.3mf.zip](https://github.com/Ultimaker/Cura/files/12423137/Custom.Temp.Tower.-.270.0-240.0x-5.0.3mf.zip)

**Comment by MariMakes** [comment]
Hey @kaitrek,

Thanks for your report 👍

I took a look, and I noticed that if you move the tabs only a little bit you see the expected behavior show up:
![image](https://github.com/Ultimaker/Cura/assets/40423138/b404abb5-1721-41c7-8e79-cb2ff6c423f6)
I hope that helps you get unstuck for now✌️

I'll bring it up to the team to see what they can do to improve it. But I expect that if it's not a quick fix that it will not get a high priority to implement. Fingers crossed 🤞
