### ISSUE TITLE
Skirt height setting doesn't work with support enabled

### ISSUE THREAD

**Issue by TomN7** [Ultimaker/Cura#16552]
### Cura Version

5.4.0

### Operating System

Windows 11

### Printer

Flashforge Adventurer 4

### Reproduction steps

1. Imported a model into Cura.
2. Enable skirt with height set to 3 layers
3. Enable supports
4. Slice Model

### Actual results

The skirt does not have additional layers printed, and remains one layer high.
The first section of support printed has an extra outline printed instead.

### Expected results

The skirt should have additional layers printed, and the supports should print as normal.

### Add your .zip and screenshots here ⬇️

![image](https://github.com/Ultimaker/Cura/assets/6779044/cd16ed51-1d56-41d3-ba52-7a68e7a6032c)

**Comment by MariMakes** [comment]
Hi @TomN7,

Welcome to the UltiMaker Cura Github 🚀 
Thanks for your report 👍

[We've already seen the report on our community](https://community.ultimaker.com/topic/43823-ultimaker-cura-54-stable-released/?do=findComment&comment=325036) so I discussed it with the team last week. They agreed that it is a bug, especially since the layers seem to be printed twice. 

![ezgif-5-9c25eec678](https://github.com/Ultimaker/Cura/assets/40423138/1dfd0783-8ce8-438e-b643-f6ae0109ffe6)

We've added a ticket to the backlog with the intent to improve this. 
For internal reference CURA-10968

Thanks for the report! 👍

**Comment by MariMakes** [comment]
👋 Quick update on our side. 

This is resolved in the 5.5 Beta release 🎉 , you can download the Cura version with the fix here: [https://github.com/Ultimaker/Cura/releases/tag/5.5.0-beta.1](https://github.com/Ultimaker/Cura/releases/tag/5.5.0-beta.1)
I'll close this issue since it's resolved. 

Thanks again, and please let us know if you run into any other issues 💪
