### ISSUE TITLE
chassis_scaled

### ISSUE THREAD

**Issue by REDTRUK** [Ultimaker/Cura#16602]
### Cura Version

5.3.0

### Operating System

Windows 11

### Printer

TENLOG

### Describe your model

No - No - No

### Add your .zip here ⬇️

[LAV_25_1960505.zip](https://github.com/Ultimaker/Cura/files/12458781/LAV_25_1960505.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
That model won't slice correctly without repair.  A lot of areas are simply missing because of errors in the model.
This is an analysis of the model:
--> 218 Naked edges (?)
--> 6 Planar holes (?)
--> 1 Non-planar holes (?)
--> 3700 Non-manifold edges (?)
--> 2278 Inverted faces (?)
--> 238 Degenerate faces (?)
--> 4446 Duplicate faces (?)
--> 0 Disjoint shells (?)
![image](https://github.com/Ultimaker/Cura/assets/64202104/57e3126c-94dd-4839-b236-579aff77e01b)

Here is the model in Mesh Mixer.  The balls and arrows indicate errors.
![image](https://github.com/Ultimaker/Cura/assets/64202104/61717a6c-852f-424f-b3c1-cac910296218)

I'll remove the bug label and close this.  There isn't any way to tell if a bug is affecting the slice, or if it's because the model is so bad.  I hope you understand.

**Comment by REDTRUK** [comment]
Thanks for the helpOn Aug 28, 2023, at 10:51 PM, GregValiant ***@***.***> wrote:﻿
Closed #16602 as completed.
