### ISSUE TITLE
V_DRIPTIP_810_SPIRALE_JAN

### ISSUE THREAD

**Issue by alamonda** [Ultimaker/Cura#16649]
### Cura Version

5.3.0

### Operating System

Linux

### Printer

Anycubic Pro and Anycubic Vyper

### Name abnormal settings

no

### Describe model location

It starts slicing when I rotate it for 90° but the progress bar freezes at about 10% forever without an error message. 

### Describe your model

I have sliced it successfully in Cura 5.13.0. It is not watertight and cannot be fixed with mesh tools.  

### Add your .zip here ⬇️

[V_DRIPTIP_810_SPIRALE_JAN.zip](https://github.com/Ultimaker/Cura/files/12505531/V_DRIPTIP_810_SPIRALE_JAN.zip)

I understand that the problem lies at the model rather than at the software for it is not watertight. But it worked with Cura 4.13.0 very well so maybe you can make it work with the newer versions. Thanks.

**Comment by GregValiant** [comment]
Thanks for the report and the file.
You can see errors here.  Cura will paint things with a polka-dot pattern when there are bad surfaces.  Another problem is when upward-facing surfaces are colored red.  That means the surface is inside-out.
There are free on-line STL repair services.  This report is from [Formware.co/OnLineSTLRepair](https://formware.co/OnlineStlRepair)
-> Analysed your file:
--> **14 Naked edges** (?)
--> 0 Planar holes (?)
--> 0 Non-planar holes (?)
--> **22 Non-manifold edges** (?)
--> **24 Inverted faces** (?)
--> 0 Degenerate faces (?)
--> **2 Duplicate faces** (?)
--> 0 Disjoint shells (?)
-> Vertex count changed from 127358 to 56675 **(-70683)**
-> Triangle count changed from 254726 to 113384 **(-141342)**
I was able to slice it in 4.13.1 but a lot of parts don't look like they are connected and I wouldn't trust it to print correctly.
This is the repaired model in 5.4.0 and it looks good.
![image](https://github.com/Ultimaker/Cura/assets/64202104/6f7f18c6-8694-471d-be4f-1697463d4a20)

I'm going to remove the bug label and close this as it is a problem with the model.  The 4.x version of Cura were more forgiving of model errors than the new versions, but you can't let the errors slide just because a model sliced because as in this case, although 4.13.1 could slice it - the slice was wrong.
I'll attach the repaired file.
[V_DRIPTIP_810_SPIRALE_JAN_fixed.zip](https://github.com/Ultimaker/Cura/files/12506791/V_DRIPTIP_810_SPIRALE_JAN_fixed.zip)
