### ISSUE TITLE
Slicing the Moon doesn't work

### ISSUE THREAD

**Issue by ofSalty** [Ultimaker/Cura#16670]
### Cura Version

5.4.0

### Operating System

Windows 10

### Printer

My Selfmade Printer

### Name abnormal settings

All like i normally print

### Describe model location

Its in the Center of the Buildplate Turning doesnt help either

### Describe your model

Never sliced succesful, it is watertight and Mesh Tools checked it

### Add your .zip here ⬇️

[CFFFP_moon.zip](https://github.com/Ultimaker/Cura/files/12527698/CFFFP_moon.zip)

**Comment by GregValiant** [comment]
Thanks for the report and the file.
This wouldn't slice for me either.  I changed the "Initial Layer Height" to 0.27 and it sliced.
I'll mark this as a duplicate and go ahead and close this as the Cura team has a lot of examples of this behavior.  Hopefully this will be fixed in the next release.

You can see that "islands" are starting for form over air.  This print will fail without support.
![image](https://github.com/Ultimaker/Cura/assets/64202104/aa698931-6d65-43d1-91f1-bfe2b7c6a438)

This is with your settings and with Tree Support enabled.  You can see that it's a 49 hour print.
![image](https://github.com/Ultimaker/Cura/assets/64202104/f993000b-7535-4c8f-9ae0-aa60f86f8827)
