### ISSUE TITLE
Walls not sliced correcty. The wall is plain but cura addes random more lines.

### ISSUE THREAD

**Issue by Tux12Fun** [Ultimaker/Cura#16697]
### Cura Version

5.4.0

### Operating System

Windows 10

### Printer

Ankermake M5

### Reproduction steps

1. Load the 3D Model.
2. Delete everything without the big container for ESP32
3. Press Slice 
4. Review the Layers in Cura of the Walls somtimes it is 2 up to 4

### Actual results

Walls not plain

### Expected results

Plain steady Wall from Bottom to Top. 

Anker Make Slicer doesn't do this and Prusa doesn't do this.

### Add your .zip and screenshots here ⬇️

See the Uploaded Files (3MF Model and Screenshot)

[Part1.zip](https://github.com/Ultimaker/Cura/files/12560424/Part1.zip)
![Screenshot 2023-09-08 154124](https://github.com/Ultimaker/Cura/assets/4000788/d29700ae-2be6-42cc-8eb5-32c271afacfb)

**Comment by GregValiant** [comment]
Thanks for the report and the file.
When  you have "Hole Horizontal Expansion" set to a non-zero number it gets applied to _any_ hole and the big rectangle qualifies as a "hole".
There is a new setting called "Hole Horizontal Expansion Max Diameter" that was created for just this situation.  If you set Hole Horizontal Expansion to a non-zero number the new setting will be available.

Your project file doesn't have HHE enabled but looking at your screenshot you did have it enabled for that slice.  If you spin the model around so you can see the cross-holes you will see what happens.
Cross-holes cause the big rectangular feature to "not be a hole anymore" so HHE is turning itself on and off depending on the cross-holes.

I'll go ahead and remove the bug label from this as it is expected behavior and there is a setting in place to mitigate this.  I hope you understand.

Here I've set the HHE to 1.0 and "HHE max hole diameter" to 0.0 and you can see the effect and how it relates to the small rectangular hole in the side and the round holes in the end.
![image](https://github.com/Ultimaker/Cura/assets/64202104/8afa9fb1-6198-4b76-8872-1c7d2ded77b6)

This is the same but I've set HHE max hole diameter to 10 and the effect has gone away.
![image](https://github.com/Ultimaker/Cura/assets/64202104/da303202-c1c4-4c4e-9ebe-5e2a3b28e6d6)
