### ISSUE TITLE
Slicing Failed for PETG Print with PLA Supports 0.4mm/0.25mm Nozzle Combo

### ISSUE THREAD

**Issue by Jonboy123123** [Ultimaker/Cura#16723]
### Cura Version

5.4.0

### Operating System

Windows 10

### Printer

Ultimaker S5 Bundle

### Name abnormal settings

PETG Model with PLA Supports 0.4mm/0.25mm Nozzle Combo

### Describe model location

No

### Describe your model

Support Test

### Add your .zip here ⬇️

[UMREDPLA_support_test_piece_0h00m.zip](https://github.com/Ultimaker/Cura/files/12597695/UMREDPLA_support_test_piece_0h00m.zip)

**Comment by GregValiant** [comment]
Thanks for the report and the file.
I had to rotate them.
I had to move them.
I had to change the Initial Layer Height to 0.17mm but it finally sliced.
![image](https://github.com/Ultimaker/Cura/assets/64202104/a9b60911-c8b2-4fd5-8101-717d78ca11bc)

I'll mark this as a duplicate as this bug has been reported many times.  Hopefully it will be fixed in the next release.
I'll go ahead and close this as well.  The Cura team has _LOTS_ of examples of this behavior.  I hope you understand.
