### ISSUE TITLE
Problems with Y driver for Creality Ender-5 Pro

### ISSUE THREAD

**Issue by jkabe11** [Ultimaker/Cura#16732]
### Cura Version

4.13.2 and 5.4.0

### Operating System

Ubuntu Linux

### Printer

Creality Ender-5 Pro

### Reproduction steps

I have printed several items sliced with Cura always with the same result, a skew in the Y direction as if each layer is moved in the -Y direction by about 2mm over 10mm thickness.  1. Creality recommended checking Vref voltages on the board and I found and adjusted X and Z up by about .2 volts but the others Y and Extruder were correct to spec.
2. I printed two Benchy tugboats with the gcode files created other than with Cura and those printed perfectly dimensionally with no skew in the Y direction.
3. My models had required me to rotate the STL files prior to slicing, so I did an experiment rotating the STL prior to opening in Cura so I could print directly and that one also had the Y-axis skew.
4. I also adjusted print speeds by small amounts, didn't record how much, but that also resulted in a skewed part.
5. I downloaded PrusaSlicer and set printer as Ender-5 and used that to slice and create the gcode file and that print came out perfectly with no skew.

### Actual results

As mentioned above, anything using Ultimaker Cura has had a skews in the Y-direction.  This has not always been the case.  I suspect your software had an update which introduced the wrong drivers for the Y-axis.  This would have happened about 1 to 2 months ago, July-August-September 2023.

### Expected results

I expected one of my changes would have corrected the error.  None did, other than changing my slicer software.  PrusaSlicer does not end up with a part which has easy to remove supports and needs a lot more hand polishing so I would like to be able to use Ultimaker Cura, but at the moment that does not appear to be an option. 

### Add your .zip and screenshots here ⬇️

[CE5_LHSide.zip](https://github.com/Ultimaker/Cura/files/12614003/CE5_LHSide.zip)
![IMG_20230805_162241873_HDR~2](https://github.com/Ultimaker/Cura/assets/145068489/98f6cc6b-065c-4cd1-9a65-38bc4799fb3c)

**Comment by GregValiant** [comment]
Thanks for the report.
There are no "Y Drivers" or any other kind of "drivers" in Cura.  It just creates gcode files that tell the printer where to go.
My printer is an Ender 3 Pro and I've never had an issue with whatever you are trying to describe.  Every other month or so I go over the printer with a steel straightedge and a carpenters square to make sure the frame is straight.  It was not assembled correctly from the factory and things can and will come loose over time.  Along with "squareness" you should check all the wheels for wobble.  The bearings are not the best.

I don't believe this could be a software problem or people wouldn't be using Cura.  If you would post a gcode file that shows what you think is the problem I can analyze it.  You would need to zip the file to post it here.

In the mean time I'll remove the bug label because as I said, I also have an Ender and I've never seen this problem.  In addition you say this has happened with 4.13 and 5.4 so it is happening with Cura versions that are different on a very basic level.  My prints have been, and continue to be, amazingly accurate.

Post the gcode file and if it looks like there might be an issue I can always put the label back on.
