### ISSUE TITLE
slicing with experimental break support into chunks

### ISSUE THREAD

**Issue by colemi4117** [Ultimaker/Cura#16730]
### Cura Version

5.4

### Operating System

windows 11

### Printer

ender 3 pro

### Name abnormal settings

break up support in chunks

### Describe model location

center

### Describe your model

moose 

### Add your .zip here ⬇️

[CE3PRO_moosetana 036.zip](https://github.com/Ultimaker/Cura/files/12610323/CE3PRO_moosetana.036.zip)

**Comment by GregValiant** [comment]
Thanks for the report and the file.
When Cura paints part of a model with a polka-dot pattern it means there are errors in the model.
![image](https://github.com/Ultimaker/Cura/assets/64202104/79624074-763a-409f-b13e-133310b6ebc2)

The errors need to be fixed or you can get bad slices (when it does slice).

This is the repaired model.  I had to remove the support blockers in order to export the file.
![image](https://github.com/Ultimaker/Cura/assets/64202104/7de2c9d3-a608-4c4f-a218-071cbea6854e)

As you see it's a 50+ hour print.

I'll mark this as a duplicate error and the Cura team will take a look.

**Comment by colemi4117** [comment]
Thank you for your time on this.  Please tell me, how did you repair the
model?  Did you do it in Cura or in another application?
