### ISSUE TITLE
Failed to slice after scaling

### ISSUE THREAD

**Issue by CertNZone** [Ultimaker/Cura#16743]
### Cura Version

5.4

### Operating System

Windows 10

### Printer

Creality Ender 5

### Name abnormal settings

Sliced when everything was default. Failed after I scaled up the model 5%

### Describe model location

Failed to slice in default location. Sliced after rotating 90 degree.

### Describe your model

Model is a end piece for a clamp for a phone mount.

### Add your .zip here ⬇️

When I drop the model straight into Cura 5.4 it slices fine. I need it to be scaled up slightly and scaling up the model caused it to error. Rotating the model allowed it to slice even after scaling up.
[phone_clamp_project_file.zip](https://github.com/Ultimaker/Cura/files/12631369/phone_clamp_project_file.zip)

**Comment by GregValiant** [comment]
Thanks for the report and the file.
This looks to be a slicing bug in 5.4.0 that has been reported numerous times.  I'll mark this as a duplicate and go ahead and close this one as the Cura team has a lot of examples of models that this occurs with.

There are three workarounds that can fool the bug.   Sometimes it takes a combination.

- Rotate the model in Cura.
- Move the model away from the midpoint of the Cura buildplate.
- Change the Initial Layer Height by a little bit (like from 0.20 to 0.23).

Moving the model didn't work so then I rotated it 90° CCW and the bug was fooled.  This is the "phone clamp scaled" project.
![image](https://github.com/Ultimaker/Cura/assets/64202104/ea1d95b6-1d61-43b6-a964-54704f7062e6)
