### ISSUE TITLE
Bug Nozzle

### ISSUE THREAD

**Issue by AleuDatsi** [Ultimaker/Cura#16751]
### Cura Version

5.4.0

### Operating System

W11

### Printer

Cr10S pro v2

### Reproduction steps

https://community.ultimaker.com/topic/44191-bug-nozzle-size/

### Actual results

https://community.ultimaker.com/topic/44191-bug-nozzle-size/

### Expected results

https://community.ultimaker.com/topic/44191-bug-nozzle-size/

### Add your .zip and screenshots here ⬇️

https://community.ultimaker.com/topic/44191-bug-nozzle-size/

**Comment by GregValiant** [comment]
Thanks for the report.
I saw this on the UM Forum.  Since you have re-installed Cura I don't really think this is a bug per se.
This screenshot highlights the nozzle files of the CR10S Pro.  This is my installation of course, but they are all there.  If you check the "C:\Program Files\UltiMaker Cura 5.4.0\share\cura\resources\variants\creality" folder you should see the full set of nozzle files.  Take a look in there and get back and let me know.
![image](https://github.com/Ultimaker/Cura/assets/64202104/901d9693-b24d-4656-bc30-b4015f8f7034)

One of the big secrets is that the "nozzle size" isn't really used for anything except to define some default line widths and layer heights.  You can install a 1.0 nozzle in the printer and declare a 0.2 nozzle in Cura and run Cura at .6 layer height and 1.0 line width.  You would probably have a lot of orange colored input boxes, but all the calculations are based on the settings values rather than the "nozzle size" setting.
