### ISSUE TITLE
Pattern/ underextrusion after seam with outer walls first and walls > 2

### ISSUE THREAD

**Issue by boehser-enkel** [Ultimaker/Cura#16760]
### Cura Version

Any 5. at least

### Operating System

Windows 10

### Printer

Elegoo Neptune 3 Pro

### Reproduction steps

Set outer walls first
Set walls > 2

### Actual results

Pattern/ looks like under extrusion after sharp corner z seam.
This is not with round shapes

### Expected results

No pattern like with 2 walls or inner walls first

### Add your .zip and screenshots here ⬇️

[Downloads.zip](https://github.com/Ultimaker/Cura/files/12660846/Downloads.zip)

**Comment by boehser-enkel** [comment]
> Thanks for the report. It's not easy in that image but looking at the top of the block I can almost convince myself that there is under-extrusion. If you have a magnifying glass take a look at the top surface. All the extrusions of the skin and walls should be flat and welded together. There should not be any gaps between the skin extrusions.
> 
> All the flows in your project are at 90% so it looks like you have built in the under-extrusion. Did you happen to use some sort of "single wall calibration cube" to calibrate your E-steps? You are also printing at 190 which can be alright as all thermocouples are different, but at first glance it is certainly on the cool side.

Thanky for the message.
In this project i missed to set it back to 95. This was calibrated with single wall cube, yes. With 95 alls lines are connected properly.
This "underextrusion" only happens after the seam. All other lines look good 
I also tested with 100 and also at 200°C+

**Comment by GregValiant** [comment]
A single wall calibration cube is only a good idea if all you print are single wall models that need an exact wall width.  For every other type of print you will have a built-in under-extrusion factor.  Just calibrate the E-steps and then do a regular print with all default settings (the "Draft" profile is a good place to start) and let the the print show you how you're doing.  From there you can adjust the flow numbers to fine tune the prints.  I found a microscope at a garage sale but a decent magnifying glass will work for inspecting a print.  Top skins are good for checking flow.  Ridges and gaps are bad.
There have been previous reports like this.  I investigate them all and I know that if I slice the model that it will print perfectly on my Ender 3 Pro with the 8 bit board _PROVIDED_ I use my default settings and not your "Quality .12..." profile.

These are settings you have that can effect the initial extrusion:

- You have the nozzle size at 0.4 and your line width at 0.3.  If you truly have a 0.4 nozzle installed in the printer, then you aren't getting any proper "squish" of the extruded material.  You can cheat the line width down to about 0.35 (~88%) but going below that makes for inconsistent forming of the extrusion.
- "Minimum wall line width" of 0.3.  The default for a 0.4 nozzle is 0.34 minimum and there is a reason for that.
- My printer doesn't like "Retract at Layer Change" or "Retract before Outer Wall".  Try a test with those disabled.  Right now with your "Wall Ordering" set "Outside to Inside" and with the "Infill Layer Height" at 0.40, on two out of three layers the Outer Wall is being printed first (0.12 layer height) and right after a retraction/prime event.  Looking at your cube again, this might well be an "Every third layer" problem.  For most printers "Outer Wall First" is a bad idea.  It might be necessary for some models, but not as a matter-of-course.
- Your printer definition file (elegoo_base.def.json) says that Acceleration is to be enabled by default at 500 print, and 1000 travel.  You don't have acceleration control enabled in Cura.  That doesn't mean acceleration control is turned off, it means the printer is to use whatever it has as a "maximum accel" in it's M201 register.  It may well be 3000.  That will effect what happens at the start of extrusions.

So you have some setting issues.  Go back to square one, check your E-steps again (no single wall calibration cube please), and use a magnifying glass to inspect the top skin of a print.  The print will let you know what changes would be advisable.

I'm going to remove the bug label from this and close it because it appears that your settings are inducing under-extrusion.  Let me know if you feel that is premature.

**Comment by boehser-enkel** [comment]
> A single wall calibration cube is only a good idea if all you print are single wall models that need an exact wall width. For every other type of print you will have a built-in under-extrusion factor. Just calibrate the E-steps and then do a regular print with all default settings (the "Draft" profile is a good place to start) and let the the print show you how you're doing. From there you can adjust the flow numbers to fine tune the prints. I found a microscope at a garage sale but a decent magnifying glass will work for inspecting a print. Top skins are good for checking flow. Ridges and gaps are bad. There have been previous reports like this. I investigate them all and I know that if I slice the model that it will print perfectly on my Ender 3 Pro with the 8 bit board _PROVIDED_ I use my default settings and not your "Quality .12..." profile.
> 
> These are settings you have that can effect the initial extrusion:
> 
> * You have the nozzle size at 0.4 and your line width at 0.3.  If you truly have a 0.4 nozzle installed in the printer, then you aren't getting any proper "squish" of the extruded material.  You can cheat the line width down to about 0.35 (~88%) but going below that makes for inconsistent forming of the extrusion.
> * "Minimum wall line width" of 0.3.  The default for a 0.4 nozzle is 0.34 minimum and there is a reason for that.
> * My printer doesn't like "Retract at Layer Change" or "Retract before Outer Wall".  Try a test with those disabled.  Right now with your "Wall Ordering" set "Outside to Inside" and with the "Infill Layer Height" at 0.40, on two out of three layers the Outer Wall is being printed first (0.12 layer height) and right after a retraction/prime event.  Looking at your cube again, this might well be an "Every third layer" problem.  For most printers "Outer Wall First" is a bad idea.  It might be necessary for some models, but not as a matter-of-course.
> * Your printer definition file (elegoo_base.def.json) says that Acceleration is to be enabled by default at 500 print, and 1000 travel.  You don't have acceleration control enabled in Cura.  That doesn't mean acceleration control is turned off, it means the printer is to use whatever it has as a "maximum accel" in it's M201 register.  It may well be 3000.  That will effect what happens at the start of extrusions.
> 
> So you have some setting issues. Go back to square one, check your E-steps again (no single wall calibration cube please), and use a magnifying glass to inspect the top skin of a print. The print will let you know what changes would be advisable.
> 
> I'm going to remove the bug label from this and close it because it appears that your settings are inducing under-extrusion. Let me know if you feel that is premature.

Thanks for that massive input. After several test prints i can say that the amount of zigzag infill (15) and 2 walls was the cause. Changing it to 20% or infill to grid for example or walls to 3 the pattern is gone

**Comment by boehser-enkel** [comment]
No No. This just compensated for the infill: zigzag. Normal Grid infill also looks good even with 2 walls
