### ISSUE TITLE
Failed Bracelet

### ISSUE THREAD

**Issue by Engrmpw1** [Ultimaker/Cura#16799]
### Cura Version

5.4

### Operating System

Windows 10

### Printer

Ender 5 S1

### Describe your model

Bracelet

### Add your .zip here ⬇️

[CFFFP_Celtic_Knot_Bracelet_Medium.zip](https://github.com/Ultimaker/Cura/files/12707144/CFFFP_Celtic_Knot_Bracelet_Medium.zip)

**Comment by Engrmpw1** [comment]
![image](https://github.com/Ultimaker/Cura/assets/145869158/7f632248-b4c1-4f9f-aa5f-94455b356876)

**Comment by GregValiant** [comment]
Thanks for the report and the file.
I moved and rotated the model and it sliced.  Sometimes changing the Initial Layer Height can fool this bug as well.
![image](https://github.com/Ultimaker/Cura/assets/64202104/bc4f8bc3-cd22-4847-948c-a2f49ed06380)

I'll mark this as a duplicate and go ahead and close this as it is an often reported bug and the Cura team has lots of examples to work with.  Hopefully it will be fixed in the next release.  I hope you understand.
