### ISSUE TITLE
Parasite gcode automatically generated

### ISSUE THREAD

**Issue by Jaggana69** [Ultimaker/Cura#16828]
### Cura Version

5.4.0

### Operating System

Windows 10

### Printer

Wahnao D12 300 MAX

### Describe your model

35x35_0.4mm_nozzle_flowrate_calibration.stl

### Add your .zip here ⬇️

[project.zip](https://github.com/Ultimaker/Cura/files/12731338/project.zip)

Hello,
In the generated gcode, a parasite line is been generated at the end of the print (line 5314): G1 F1800 E643.56981 ; Modi
This block the printer and extrude 643.56981mm
I can send you the generated gcode file and my Cura settings if I can send you attachments.
BR, Sam

**Comment by GregValiant** [comment]
Thanks for the report.
You had at least one post processor running and it appears to be the WIFI plugin from the Marketplace.
"; Postprocessed by "MKS WiFi plugin"(https://github.com/Jeredian/mks-wifi-plugin)"
Did you have any other post processors running?  They would be the first suspect.
(It is highly unlikely that the problem was caused by the plugin noted above.)

G1 F1995 X133.642 Y133.395 E645.56981 >>>>The last extrusion
G0 F7200 X133.815 Y133.296 >>>>>>>>>>>Wipe move
;TIME_ELAPSED:758.907139
**G1 F1800 E643.56981 ; Modi**  >>>>> This is the final retraction of the print.  Where " ; Modi" comes from must be a post processor.  Cura does not add that.
M140 S0
M107
M104 T0 S0 >>>This is the start of your Ending Gcode
M140 S0
G92 E1
**G1 F300 E643.56981 ; Modi** >>>>>>Not added by Cura.  The "F" number is not your retraction speed and Cura would have used the retraction speed.  The "E" number is correct as it is the same as that last retraction line.
;G28 X0 Y0
G1 X0 Y300 ;Present print
M84
M82 ;absolute extrusion mode
M104 S0
;End of Gcode

I can't tell exactly what could have caused that line to be inserted there but it definitely wasn't Cura (or no one would use it).
The most likely cause would be that it happened in post process.

If you have more information please post it.  I just don't see this as a "Cura bug" but something copied the E value for that line, changed the "F" speed, and inserted the line right after the E had just been set to zero.
