### ISSUE TITLE
Failed Slicing of Flex Facemask

### ISSUE THREAD

**Issue by gvsu4msu** [Ultimaker/Cura#16847]
### Cura Version

5.3.0

### Operating System

Windows 10

### Printer

Ender 3 pro

### Name abnormal settings

no

### Describe model location

center

### Describe your model

Yes other files slice fine too. 

### Add your .zip here ⬇️

[FlexFacemaskLeeAndyTabs.zip](https://github.com/Ultimaker/Cura/files/12766461/FlexFacemaskLeeAndyTabs.zip)

**Comment by GregValiant** [comment]
Thanks for the report and the file.
The project wouldn't slice for me either.  I rotated the model and changed the "Initial Layer Height" to 0.23 and it sliced.

I'll mark this as a duplicate report.  This bug has been reported numerous times and hopefully will be fixed in the next release.
I'll go ahead and close this as well.  I hope you understand.
