### ISSUE TITLE
It chashes the CURA 

### ISSUE THREAD

**Issue by oteropedro** [Ultimaker/Cura#16855]
### Cura Version

5.4.0

### Operating System

Windows 11

### Printer

Ender 3 v2 NEO

### Describe your model

Anchor

### Add your .zip here ⬇️

I cant open this model, while is slicing for the first time it crashes, When I used the version 5.3.1 it works fine but now it doesnt
[anchor.zip](https://github.com/Ultimaker/Cura/files/12775730/anchor.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
Cura 5.4.0 has a bug that can keep models from slicing.  The bug seems to be more prevalent on Windows 11 computers.
Try moving, rotating the model in Cura.  Sometimes changing the Initial Layer Height by a little bit can also help fool this bug.

I'll mark this as a duplicate and go ahead and close it as many people have reported this bug.  I hope you understand.
![image](https://github.com/Ultimaker/Cura/assets/64202104/8ca1c323-e948-47b7-ad89-ee52a306c0bf)
