### ISSUE TITLE
BMW Car

### ISSUE THREAD

**Issue by menuka1** [Ultimaker/Cura#16858]
### Cura Version

5.3.1

### Operating System

Win

### Printer

ender 3 s1

### Name abnormal settings

Super quilty

### Describe your model

BMW car model

### Add your .zip here ⬇️

[CE5P_lambo[1].zip](https://github.com/Ultimaker/Cura/files/12776263/CE5P_lambo.1.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
That model is loaded with errors...
![image](https://github.com/Ultimaker/Cura/assets/64202104/93584afb-b90b-4700-a88b-41da337f8c98)
From formware.co/onLineSTLRepair:
--> 21132 Naked edges (?)
--> 23 Planar holes (?)
--> 3735 Non-planar holes (?)
--> 12 Non-manifold edges (?)
--> 16 Inverted faces (?)
--> 1918 Degenerate faces (?)
--> 0 Duplicate faces (?)
--> 0 Disjoint shells (?)
-> Repairing: 100.00%
----- Repair completed in 128069ms ------
-> Vertex count changed from 120931 to 116392 (-4539)
-> Triangle count changed from 229676 to 234912 (+5236)

This is the model (with errors) sliced in 4.13.1.  This is not printable.
![image](https://github.com/Ultimaker/Cura/assets/64202104/c166e242-f285-4b46-ac0c-09e0fc3276ac)

Here is the repaired model sliced in 5.4.0.
![image](https://github.com/Ultimaker/Cura/assets/64202104/155c0467-0fa1-4702-9891-c086a3dc0d27)

Since the repaired model slices with no problem I'm going to remove the bug label from this and close it.  I hope you understand.  If you have a problem after repairing the model this can be revisited.
