### ISSUE TITLE
Error 'time'

### ISSUE THREAD

**Issue by Da6oN** [Ultimaker/Cura#16862]
### Cura Version

5.4.0

### Operating System

Windows 11

### Printer

Ultimaker3

### Reproduction steps

Error 'time' when send gcode to the printer
same error when i save gcode to disk
only with UM3, not other printer Alfawise U20 Plus

### Actual results

Error 'time' when send gcode to the printer
same error when i save gcode to disk
only with UM3, not other printer Alfawise U20 Plus

### Expected results

Error 'time' when send gcode to the printer
same error when i save gcode to disk
only with UM3, not other printer Alfawise U20 Plus

### Add your .zip and screenshots here ⬇️

![Capture d'écran 2023-10-01 144750](https://github.com/Ultimaker/Cura/assets/61240167/8e4bea44-ee32-48eb-9560-491bbf31e10c)

**Comment by GregValiant** [comment]
Thanks for the report.
Please provide a project file ("File | Save Project") and a Cura log file (cura.log is in the configuration folder at "Help | Show Configuration Folder") and put them in a zip folder and post the zip folder here so that this can be investigated.

@fieldOfView It's a UM3 and I haven't seen this.  It seems to have sliced (my French is as bad as my Swahili) so maybe a Network problem???

**Comment by Da6oN** [comment]
Thanks for your response, I've been working on this for hours and finally fixed the issue.
I had installed the elegoo_neptune_thumbnails plugin and it caused this error with the UM3 even if it was not active.
I deleted it and it works now.

**Comment by GregValiant** [comment]
I filled out a bug report on the authors Git page.  It's [HERE](https://github.com/Molodos/ElegooNeptuneThumbnails/issues).  The author may require further information.

**Comment by Molodos** [comment]
Hi, the Bug in my ElegooNeptuneThumbnails plugin was fixed in Version 3.0.0. Please consider updating the plugin :)
Current plugin versions are 3.0.1 on Marketplace and 3.2.4 on GitHub (unfortunately Ultimaker will take more than a month for review, which makes updating the plugin kind of a pain for me)

**Comment by GregValiant** [comment]
@Da6oN There is the word.  I'll leave this open as I'm not sure of the mechanism for the Cura Team to review updates to plugins.

**Comment by Da6oN** [comment]
> Hi, the Bug in my ElegooNeptuneThumbnails plugin was fixed in Version 3.0.0. Please consider updating the plugin :) Current plugin versions are 3.0.1 on Marketplace and 3.2.4 on GitHub (unfortunately Ultimaker will take more than a month to approve Marketplace updates, which makes updating the plugin kind of a pain for me)

Ok thanks

**Comment by Da6oN** [comment]
@Molodos Ok thanks you
