### ISSUE TITLE
Model does not print if left in center

### ISSUE THREAD

**Issue by Trevor-y** [Ultimaker/Cura#16907]
### Cura Version

5.4.0

### Operating System

Windows 10

### Printer

Anycubic Kobra

### Name abnormal settings

Nothing was changed. Model does not slice on default settings

### Describe model location

The model does slice when moved from the center of the buildplate

### Describe your model

Multiple Models

### Add your .zip here ⬇️

This was happening with multiple models. If you move them from the center it works just fine after
[RL Car.zip](https://github.com/Ultimaker/Cura/files/12838403/RL.Car.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
As with many models like it, this one has errors.
This is in Mesh Mixer.  The balls and lines indicate errors in the model.
![image](https://github.com/Ultimaker/Cura/assets/64202104/d2860c0b-f46d-45f1-9352-6b6ce686e66b)

Here is a report on the model errors.
-> Reading file and indexing vertices
-> Analysed your file:
--> 0 Naked edges (?)
--> 0 Planar holes (?)
--> 0 Non-planar holes (?)
**--> 5687 Non-manifold edges (?)
--> 7806 Inverted faces (?)
--> 646 Degenerate faces (?)
--> 387 Duplicate faces (?)**
--> 0 Disjoint shells (?)

You need to fix the model or you would not be able to trust that it slices accurately.
There is a bug in 5.4.0 and as you noted, one of the ways to fool the bug is to move the model in Cura.  I'm going to close this as there are a lot of reports of the problem occurring with good models and this particular model would not make a good investigating tool due to the errors.  I hope you understand.
