### ISSUE TITLE
Endless slicing or error on specific model with default normal settings (0.15mm)

### ISSUE THREAD

**Issue by Bearzerg** [Ultimaker/Cura#16904]
### Cura Version

5.4.0

### Operating System

Windows 10

### Printer

Ultimaker 3 Extended

### Name abnormal settings

none

### Describe model location

two models at the center of build-plate

### Describe your model

model sliced successfully with adaptive layers on, but with bad results on middle to top layers.
sliced successfully with default setting, with the model slightly pushed trough the build-plate

### Add your .zip here ⬇️

[UM3E_viking-pallisade-Sx2.zip](https://github.com/Ultimaker/Cura/files/12837156/UM3E_viking-pallisade-Sx2.zip)

**Comment by GregValiant** [comment]
Thanks for the report and the file.
I had to move the models around in Cura but after moving them the project sliced.
This appears to be the standard slicing bug in 5.4.0 that has been reported numerous times.  Along with moving a model you could try rotating the models or changing the Initial Layer Height by a little bit.
I'll mark this as a duplicate and close it as this behavior is well documented.  Hopefully it will be fixed in 5.5.  I hope you understand.
