### ISSUE TITLE
Helmet won't slice.

### ISSUE THREAD

**Issue by wicker4143** [Ultimaker/Cura#16922]
### Cura Version

5.4

### Operating System

Windows 10 unactivated

### Printer

Cr-10 Smart (It's actually a Cr-10 Smart Pro, but that isn't an option).

### Name abnormal settings

I can only not slice this model, which has been the biggest one yet. It tries and fails.

### Describe model location

No

### Describe your model

I have never sliced this successfully. It is not watertight, I have not.

### Add your .zip here ⬇️

[CCR10S_HELMET.zip](https://github.com/Ultimaker/Cura/files/12849771/CCR10S_HELMET.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
I didn't have any trouble slicing it but I couldn't import your project because of a Material Conflict.  I think that's another bug.
The model has some errors and should be fixed, but if you move it, rotate it, or change the Initial Layer Height by a little bit it should slice.
![image](https://github.com/Ultimaker/Cura/assets/64202104/9c3b6b55-7f9d-4729-bf5d-acc209bab98c)

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well? Feel free to reopen the issue if it is not resolved.
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
