### ISSUE TITLE
Missing printer model - Ping3dp

### ISSUE THREAD

**Issue by tsh1975** [Ultimaker/Cura#16956]
### Is your feature request related to a problem?

https://ping3dp.com/
I can't find the model number of this manufacturer's printer

### Describe the solution you'd like

Please add model

### Describe alternatives you've considered

NO

### Affected users and/or printers

Please add model

### Additional information & file uploads

https://ping3dp.com/

**Comment by MariMakes** [comment]
Welcome to the UltiMaker Cura Github 🚀 

Since Cura is open source, you or anyone else is more than welcome to work on adding this 3d printer and create a pull request yourself. You can find instructions on how to add a new 3D printer definition here: https://github.com/Ultimaker/Cura/wiki/Adding-new-machine-profiles-to-Cura 
If you are stuck in any way, please reach out! I'll be happy to help out.
