### ISSUE TITLE
2 plugins causing cura to crash.

### ISSUE THREAD

**Issue by NokEternal** [Ultimaker/Cura#16965]
### Cura Version

5.5.0-beta.1

### Operating System

Windows 11

### Printer

Creality Ender 3 S1 Pro

### Reproduction steps

Tried to install the plugin's ( Tabbed Settings 1.0.2 ) as well as ( Sidebar GUI 4.6.2) via the marketplace.

### Actual results

Plugin's ask for agreement, and prompt for a Cura Restart, When Restart occurs, The titled plugins, fail...

### Expected results

Plugins should normally install, but have been on a loop of errors, trying to load them and restart with cura.

### Add your .zip and screenshots here ⬇️

![Screenshot (43)](https://github.com/Ultimaker/Cura/assets/147628077/fe698e64-65c0-4197-ba20-24a42b1e76ea)
![Screenshot (44)](https://github.com/Ultimaker/Cura/assets/147628077/c0de16c4-7812-4847-86ac-6a8788db7144)
![Screenshot (45)](https://github.com/Ultimaker/Cura/assets/147628077/d0a67285-a113-42d9-ab24-c2fd49583ff6)
![Screenshot (46)](https://github.com/Ultimaker/Cura/assets/147628077/68c67d32-c125-42cf-9296-56b06a5d41aa)

**Comment by fieldOfView** [comment]
This is decidedly not a crash; this is a warning that the plugins fail to load. In fact, it is to prevent potential crashes.

In order for these plugins to work, they do quite a bit of "nasty" patching of the original interface. These patches may break the interface when the original interface is changed. So, as a security measure, the plugin checks to see if it has been "approved" for the version of Cura you are using it with. 

When a new release of Cura is available, both these specific plugins always needs to be updated by the author (me). I normally work hard to have an updated version of the plugins ready during the beta period, so when a new stable release of Cura is available, the plugin update is available in the Marketplace. However I can't really finish these updates until I have access to the beta myself, and even after I update the plugins, they need to be tested/reviewed by the Ultimaker Cura team.

It just so happens that I have minutes ago released new versions of both plugins to the Marketplace. 

I admit that the wording in the warning message could be less dramatic. I will work on replacing that dialog with a message of my own design, but it may take an update or two before that new message materializes.

I am closing this issue, because this is not a crash, nor is it a bug, but I will take this feedback in mind and will try to add a more helpful message.
