### ISSUE TITLE
Articulated Dragon 5.4.0

### ISSUE THREAD

**Issue by GigisZombie** [Ultimaker/Cura#17106]
### Cura Version

5.4.0

### Operating System

Windows 10

### Printer

Ender 2 Pro

### Name abnormal settings

only changed quality .2/walls 4/inflill 10/speed 30

### Describe model location

i've tried rotating and moving will not slice

### Describe your model

i can slice with older versions of cura just not with 5.4.0

### Add your .zip here ⬇️

[Articulated Dragon Eryone PLA lw 0.4mm lh 0.2mm if 10% ext1 190C bed 60C.zip](https://github.com/Ultimaker/Cura/files/13169091/Articulated.Dragon.Eryone.PLA.lw.0.4mm.lh.0.2mm.if.10.ext1.190C.bed.60C.zip)

**Comment by GregValiant** [comment]
Thanks for the report and the file.
Every dragon that comes through here is full of errors.  
5.4.0 does have a bug that can keep models from slicing.  You can try moving the model in Cura, rotate the model, or change the initial layer height.  Sometimes a combination is needed to fool the bug.  Because of all the errors you may not be able to trust the gcode if it does slice.
I'll mark this as a duplicate bug for now and go ahead and close this since 5.5 has been released as an update.  I hope you understand.

This sliced after I rotated the model 90°CCW.
![image](https://github.com/Ultimaker/Cura/assets/64202104/3bb56972-b915-4119-8b33-1542e19d23c7)
