### ISSUE TITLE
Slicing creates hole in the objects

### ISSUE THREAD

**Issue by DracieVajko** [Ultimaker/Cura#17134]
### Cura Version

5.5.0

### Operating System

Windows 11

### Printer

Artilerry Sideinder X2

### Reproduction steps

It happens 70% of the time when I try to print anything. Mostly complete reinstall helps but then it comes back after while

It doesnt matter if I change settings or not

I will send the config file with project file aswell so probably you can see it

### Actual results

It does a line through the objects where outer wall is missing

### Expected results

The line with missing outer walls on the object

### Add your .zip and screenshots here ⬇️

![Screenshot (99)](https://github.com/Ultimaker/Cura/assets/119598488/8b5f4acb-cd59-4c74-819c-c139375a0d61)
![Screenshot (102)](https://github.com/Ultimaker/Cura/assets/119598488/2129c304-0ad0-461b-8f9b-e23907564de6)
![Screenshot (101)](https://github.com/Ultimaker/Cura/assets/119598488/243e3698-7e18-4f06-83ad-48704e57054b)
![Screenshot (100)](https://github.com/Ultimaker/Cura/assets/119598488/164b5c74-6a2a-49d6-bf81-c1f24ce7a3e0)
[ASX1_3d_skuska_.zip](https://github.com/Ultimaker/Cura/files/13195018/ASX1_3d_skuska_.zip)
[5.5.zip](https://github.com/Ultimaker/Cura/files/13195019/5.5.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
You have "Coasting" enabled".
The Cura preview only shows movements with extrusions.  During the "Coast" part of a move there is no extrusion.  The length of the gap reflects the distance traveled as a function of the "Coasting Volume".
This is with Coasting turned off.
![image](https://github.com/Ultimaker/Cura/assets/64202104/90175b2f-a81e-409c-adb6-330b33d88628)

I'll remove the bug label and close this as it is expected behavior given your settings.
