### ISSUE TITLE
échec de la découpe 

### ISSUE THREAD

**Issue by epokrso** [Ultimaker/Cura#17291]
### Cura Version

5.5.0

### Operating System

macOS Monterey 

### Printer

Creality Ender-3 pro V2

### Reproduction steps

https://github.com/Ultimaker/Cura/assets/130596806/530aad21-5c1d-4734-aac2-1ae06a6bfbe0

### Actual results

un message s'affiche "échec de la découpe"

### Expected results

la découpe devait réussir 

### Add your .zip and screenshots here ⬇️

[teste logo.stl.zip](https://github.com/Ultimaker/Cura/files/13326100/teste.logo.stl.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
If you load the Mesh Tools plugin from the Market Place you will see this:
![image](https://github.com/Ultimaker/Cura/assets/64202104/b1292772-f2f3-454f-9899-e54fb75c13fe)

All the letters are in polka-dots indicating errors in the model.  The magenta is also in error.
This report is from an on-line utility
**--> 59168 Naked edges (?)
--> 2139 Planar holes (?)
--> 550 Non-planar holes (?)**

That model is pretty bad and likely is not repairable.  It's possible you could get it to slice if you move it, rotate it, or change the initial layer height by a little bit.
I'll close this as there is no way to tell if it won't slice because of a model error, or a bug in Cura.  I hope you understand.

I did get it to slice in 5.5.0, but I wouldn't trust it to print correctly.
![image](https://github.com/Ultimaker/Cura/assets/64202104/7caa6419-5b43-4bdb-948a-6d1b0c1d7eb9)
