### ISSUE TITLE
Error Slicing

### ISSUE THREAD

**Issue by sopa0405** [Ultimaker/Cura#17299]
### Cura Version

5.5.0

### Operating System

Windows 10

### Printer

Two Trees Bluer

### Reproduction steps

I tried to slice a 3d file. I used the default settings

### Actual results

Parts where there should be a gap got combined.

### Expected results

There should be a gap for the parts to move freely. 

### Add your .zip and screenshots here ⬇️

![how-it-slices](https://github.com/Ultimaker/Cura/assets/142125941/055e8da0-6d65-4040-b9f7-ce9f0244311e)
![how-it-is-supposed-to-slice](https://github.com/Ultimaker/Cura/assets/142125941/871e58d9-6a07-45e8-83cb-f7d7c50a79ae)
![what-i-want-to-slice](https://github.com/Ultimaker/Cura/assets/142125941/9f2b470f-4061-4835-a876-17349625a96e)
[cura.log](https://github.com/Ultimaker/Cura/files/13329129/cura.log)

**Comment by GregValiant** [comment]
Thanks for the report.
Use the "File | Save Project" command and then zip the 3mf file and post the zip folder here.  Without the project there is no way to tell what might be going on.  Because it did slice successfully - the info will not be in the log file.
The settings "Outer Wall Inset", "Horizontal Expansion" and a couple of others can come into play.  This behavior has been noted in a couple of previous bug reports regarding models that test for "clearance".
