### ISSUE TITLE
opengl 2.0 or higer requiere on intel grafics 3000

### ISSUE THREAD

**Issue by danilopmaciel** [Ultimaker/Cura#17306]
### Cura Version

5.5

### Operating System

windows 10

### Printer

ender 3

### Reproduction steps

On laptop lenovo x220 using windows 10, intelgrafics 3000 the error appers on intaling.
![image](https://github.com/Ultimaker/Cura/assets/30030866/c9e907dd-ea2d-46f7-9dc1-99c5aa20a7c3)

### Actual results

error opengl 2.0

### Expected results

intall

### Add your .zip and screenshots here ⬇️

not avaliable

**Comment by snydeja** [comment]
I have the same error trying to launch any version of 5 including latest 5.6.0 in Windows 10; however the OpenGL Extension Viewer says that my hardware is running OpenGL 3.1 so I expect that would exceed the minimum requirement, but the stdout file only reports a check for OpenGL 2 or 4 then exits because it says the OpenGL context is too low at 1.1 so I'm at a complete loss here.

**Actual results** 
application fails to launch

**Expected results**
launch application

![image](https://github.com/Ultimaker/Cura/assets/162149761/26486947-b5c4-45e9-8ac7-fec27add6464)
![image](https://github.com/Ultimaker/Cura/assets/162149761/79f10af1-5a4a-4366-898e-fe3131cc95c9)
[stdout.log](https://github.com/Ultimaker/Cura/files/14483601/stdout.log)

**Comment by snydeja** [comment]
Update this [solution ](https://github.com/Ultimaker/Cura/issues/12359#issuecomment-1380799603) worked!

https://gist.github.com/rb-dahlb/26f316c5b6089807a139fc44ee69f0d1
to install the fix named curafix.sdb copy to c:\ and run from an admin cmd prompt
sdbinst.exe -q c:\curafix.sdb
