### ISSUE TITLE
Error when slicing my dragon

### ISSUE THREAD

**Issue by TimyIsCool** [Ultimaker/Cura#17354]
### Cura Version

5.3.1

### Operating System

Windows 11

### Printer

Ultimaker S5 / Ender 3 v2

### Describe your model

I have not been able to slice this model

### Add your .zip here ⬇️

https://wetransfer.com/downloads/05884ff9d3b79963bd8d3d39724bc92e20231117173513/0b98b7e902dfd4dee6b99e3b5c11e23220231117173543/2791ab?trk=TRN_TDL_01&utm_campaign=TRN_TDL_01&utm_medium=email&utm_source=sendgrid

**Comment by GregValiant** [comment]
If you repair that model in something like MS3D Builder it will have a chance to slice.  It has a lot of errors.

It has so many errors that it isn't possible to tell if it won't slice because of a bug, or because of the errors.  The Crystal Dragon was pretty bad but you may have set a new record for problems in 1 model.

I'll leave the bug label on this but I'll close it because of the uncertainties.  I hope you understand.
