### ISSUE TITLE
fallo en la visualizacion de capas y por lo tanto tb falla en la impresion 3d

### ISSUE THREAD

**Issue by lmiguelspcoruna** [Ultimaker/Cura#1735]
Buenas tardes al intentar laminar este archivo falla en la visualización de las capas y hace exactamente lo mismo en los gcodes en la impresora
pongo los 3 archivos el archivo el archivo de Freecad con el que genero el stl que tb pongo el enlace yel gcode generado con la versión 2.4.0 de cura.
https://drive.google.com/file/d/0B4AxlEj10DxkTnlPd20yMFFfWWc/view?usp=sharing
https://drive.google.com/file/d/0B4AxlEj10DxkUm1YU1F0Q3l4WE0/view?usp=sharing
https://drive.google.com/file/d/0B4AxlEj10DxkWmYzU1RmMk9FalU/view?usp=sharing

**Comment by nallath** [comment]
I'm sorry. We don't speak spanish.

**Comment by Ghostkeeper** [comment]
Something about getting 3 times the same g-code despite having different files, and something about layer view being empty?

**Comment by lmiguelspcoruna** [comment]
You can see the file of freecad? That file is the support for the coil, in the file of freecad it is seen that there is a hole that is to pass the axis that supports the filament coil, And in the original without seeing the layers also you see the hole

**Comment by lmiguelspcoruna** [comment]
And have you noticed that if you tilt the figure if you can see the hole?

**Comment by Ghostkeeper** [comment]
For me it just laminates the file and then shows a hole in the layer view in between the normal model. What was exactly your problem? Do you have steps to reproduce it?

**Comment by Ghostkeeper** [comment]
After rotating that model 90 degrees so that it's upright, I think I see what you mean:

![littledent](https://cloud.githubusercontent.com/assets/2448634/25607569/6b1b57a2-2f17-11e7-9811-71ed084d00fa.png)

The cause seems to be that your model has 3 surfaces overlapping each other on the top side. You can see the z-fighting here, due to one of them being marked as overhang by the shader:

![zfighting](https://cloud.githubusercontent.com/assets/2448634/25607644/d074d4c0-2f17-11e7-9f76-e37420451e54.png)

I suspect that some of that noise drops down enough that it intersects with the layer below.
