### ISSUE TITLE
Wrong X and Y zero position

### ISSUE THREAD

**Issue by blithe74** [Ultimaker/Cura#17364]
### Cura Version

5.5.0

### Operating System

Windows 10 Professional

### Printer

Marlin

### Reproduction steps

In the printer settings, the origin of the X and Y axes on the desktop is set in the lower left corner.

### Actual results

However, the program counts coordinates from the middle of the table:
when the model moves to the left of the center, the X coordinates become negative, when moving to the right of the X center positive. The same is true when you move along the Y axis.

### Expected results

The zero value of the X axis must be on the left and increase when you move the model to the right.
The zero value of the Y axis must be at the bottom and increase as the model moves up.

### Add your .zip and screenshots here ⬇️

![Cura_error-1](https://github.com/Ultimaker/Cura/assets/6023788/4aff00cc-ff30-4e50-b5a5-fea5a2160217)

**Comment by GregValiant** [comment]
Yes.  You got it exactly right.  That's how it works.
When you bring in a model - Cura uses the "bounding box" of the model to locate it in space.  You will also notice that if you rotate a model that it looks like the size changes.  A 100mm cube will show 141mm in the setting box.  It's because the bounding box doesn't rotate with the model and always reflects the orthogonal X and Y extents of the model, rather than a models actual size.
Another thing to consider is that not all printers have the origin at the left front.  Most delta printers are "Origin at Center" machines.
I'll remove the bug label from this as it is the way it works.  I'll go ahead and close this as well.  I hope you understand.
