### ISSUE TITLE
Profile for Creality Ender 3 V3 KE

### ISSUE THREAD

**Issue by SGT-276** [Ultimaker/Cura#17420]
### Is your feature request related to a problem?

There is no profile for the Creality Ender 3 V3 KE. 

### Describe the solution you'd like

A Cura profile for the Ender 3 V3 KE to utilize all the features.

### Describe alternatives you've considered

The Ender 3 V2 profiles were not made for the Ender 3 V3 KE, which is a faster and fancier printer than the V2 and it does not use marlin.

### Affected users and/or printers

I should imagine many people would benefit from this!

**Comment by Asterchades** [comment]
All definitions for non-Ultimaker printers are provided by community submissions. The Cura staff simply don't have the time or the hardware to properly create such definitions.

If you would like to create your own definition or modify one of the existing ones (either for private use or submission) you can find more detail here: https://github.com/Ultimaker/Cura/wiki/Definition-Files-Explained

In the meantime the existing Ender-3 definitions do work - though I would recommend not using the standard one due to the exclusion zones. Speed can be adjusted manually in the print settings, bed levelling statements can be added to the Start GCode, and there is currently no dedicated Klipper GCode flavour. Additional Klipper support is planned in future but isn't currently implemented.
