### ISSUE TITLE
Creality Ender 3 V3 KE Profile Missing

### ISSUE THREAD

**Issue by jonesnoh** [Ultimaker/Cura#17431]
### Is your feature request related to a problem?

The printer profile for the new Ender 3 V3 KE is missing in the Cura slicer.

### Describe the solution you'd like

Adding a print profile to match the Ender 3 V3 KE specifications will solve the problem.

### Describe alternatives you've considered

The alternative would be to manually add the profile but I cannot find specific information about the KE to transfer over manually.

### Affected users and/or printers

Creality Ender 3 V3 KE users

**Comment by Asterchades** [comment]
All definitions for non-Ultimaker printers are provided by community submissions. The Cura staff simply don't have the time or the hardware to properly create such definitions.

If you would like to create your own definition or modify one of the existing ones (either for private use or submission) you can find more detail here: https://github.com/Ultimaker/Cura/wiki/Definition-Files-Explained

In the meantime the existing Ender-3 definitions do work - though I would recommend not using the standard one due to the exclusion zones. Speed can be adjusted manually in the print settings, bed levelling statements can be added to the Start GCode, and there is currently no dedicated Klipper GCode flavour. Additional Klipper support is planned in future but isn't currently implemented.
