### ISSUE TITLE
Filament change

### ISSUE THREAD

**Issue by SQ4096** [Ultimaker/Cura#17453]
### Cura Version

5.4.0

### Operating System

Windows 10

### Printer

Longer LK5 Pro

### Reproduction steps

Started a slice, 
went into extensions
went into post processing
selected filament change
established layer to change over
selected z retract of 10mm
selected use filmware on printer, I just updated it last week with the latest version for that printer
 received my red icon on left side of slice saying I had a special process
started slice

did not interrupt for a filament change.

I do have the software using the correct drivers as they are identified as Longer LK5pro, with generic .4 nozzle, printing standard pla

![Screenshot (1)](https://github.com/Ultimaker/Cura/assets/152211569/d5e81d1a-801b-493a-8908-7fb0a34aaefa)
![Screenshot (2)](https://github.com/Ultimaker/Cura/assets/152211569/e9f208d1-787e-4865-ad27-5d83c85039fb)
![Screenshot (3)](https://github.com/Ultimaker/Cura/assets/152211569/080c6216-2798-4def-b613-4a9ab176e9df)
 

### Actual results

nothing, machine continues to print without stopping for filament change

### Expected results

machine should pause, head should jog to 0,0,10mm for filament change

### Add your .zip and screenshots here ⬇️

[LLK5PRO_Oval_soap_dish_bottom.zip](https://github.com/Ultimaker/Cura/files/13478986/LLK5PRO_Oval_soap_dish_bottom.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
This is from your gcode file and M600 is in line #175761.
;BEGIN FilamentChange plugin
M600
;END FilamentChange plugin
;LAYER:37

You can see how minimalist it is when it is depending on the current set up in the printer.  When the printer is not set up beyond having M600 enabled then the line might look like this:
;  Start of Filament Change
M600 E30.00 U300.00 X12.00 Y14.00 Z10.00
;  End of Filament Change
;TYPE:WALL-INNER
That indicates and initial retraction of 30mm, an unload distance of 300mm, and park the head at X12 Y14 Z10.
If M600 is not enabled (it is not on my Ender) then the printer simply won't respond.
If M600 is set up in the firmware, but the additional parameters are not set up then the printer might pause and do nothing.  It is possible that your printer would require M603 to run first to set up the printer for the following M600.

Since your Gcode is only showing the simple "M600" with no parameters then as your screenshot shows - "Use Firmware Configuration" was checked.  If you uncheck that and try a test you might get a positive response from the printer.

You could also try using Pause At Height.  It's the same sort of thing and M0 or M25 must be enabled in the firmware to use it.

I'll remove the bug label from this and close it as the M600 was properly placed into the gcode (and I assume in the correct layer) so there is no bug here.  Your printer certainly saw the command and it either didn't understand it, or it needs the additional parameters.  I hope you understand.
M600 and M603 are explained on the [MarlinFW.org](https://marlinfw.org/docs/gcode/M600.html) site.
