### ISSUE TITLE
still many problems

### ISSUE THREAD

**Issue by DavideMarchi92** [Ultimaker/Cura#17472]
### Cura Version

5.6

### Operating System

Windows 10 Pro

### Printer

flsun sr and qqs pro

### Name abnormal settings

more

### Describe model location

center to the bed

### Describe your model

bike structural piece

### Add your .zip here ⬇️

there are still many problems with this slicer. including not reading ipt files. now it turns out that it is unable to process a piece due to the resolution, with 0.2 yes and with 0.12 no. then there is the fact that it is complicated to bin the supports manually. it also has inconsistent bugs on my printer, every now and then it doesn't turn on the fans and I have to turn them on manually, it doesn't respect the set temperature and sets one at random.

**Comment by GregValiant** [comment]
Thanks for the report.
_"there are still many problems with this slicer. including not reading ipt files."_
What is an ipt file?  I'm not familiar with that one.

_"now it turns out that it is unable to process a piece due to the resolution, with 0.2 yes and with 0.12 no."_
That is a known bug and so far it has not been fixed but it is being worked on.  For many problem models, making a change in the Initial Layer Height will allow it to slice.  That way you don't have to change the layer height.  Rotating the model on the build plate, turning off Print Thin Walls and Optimize wall printing order can also free up the slicing.

 _"then there is the fact that it is complicated to bin the supports manually."_ 
There are over 70 support settings so yes, it takes a bit of thought to get them right for a particular model.  It's what people have asked for.

_"it also has inconsistent bugs on my printer, every now and then it doesn't turn on the fans and I have to turn them on manually, it doesn't respect the set temperature and sets one at random."_
Those are both unlikely to be a Cura problem.  I have inspected a **_LOT_** of gcode files that Cura generated and there have been almost no errors.  Dual extrusion printers have had one or two problems but single extruder printers haven't had any problems within the gcode itself.  No missing commands, no random temperatures, none of that.
If you post a file that you believe to be in error I'll take a look.  Without supporting material I'm inclined to close this as it isn't pointing to anything in particular.  Without that it's really impossible to chase down a bug.
