### ISSUE TITLE
Slicing very unneficient.

### ISSUE THREAD

**Issue by alnavasa** [Ultimaker/Cura#17517]
### Cura Version

5.6.0

### Operating System

MAC OS 13.6.1 (22G313)

### Printer

Ultimaker s5

### Name abnormal settings

Unefficient first layer fill

### Describe model location

flat against buldplate

### Describe your model

Never tried before

### Add your .zip here ⬇️

[Archivo comprimido.zip](https://github.com/Ultimaker/Cura/files/13545653/Archivo.comprimido.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
You didn't provide a project file so I'm not sure of your settings.  It appears you may have combing mode set to "Not in Skin".  For that model with all the radii it would be much better to set combing to "All" or "Not on Outer Surface".  That way it would not travel all around the walls every time it needs to make a move.
This looks like a setting issue rather than a bug.  If you would switch to the default "Fast" profile you will see that the behavior is different.
I'm inclined to remove the bug label from this but post a project file.  It will show your Cura settings.

**Comment by alnavasa** [comment]
ill post the settings, though, it is better to do all the infill rather than jump some sections having to comb all the way around to re do them ,ad them comb all the way around, I get what that setting is meant for, and I want it, though, I think that with that setting it can be more efficient, rather to go around the entire stick 3 times during the process, algorithm could be optimize to move only on the sides the required times instead of going all the way to the other side so many times, 
Though I am sure that if you see it and mention it is meant to be like that, I might be wrong since I have little to none experience compared to you. 
[UMS5_UMS3S5_Calibration stick 8mm.3mf.zip](https://github.com/Ultimaker/Cura/files/13550434/UMS5_UMS3S5_Calibration.stick.8mm.3mf.zip)

**Comment by GregValiant** [comment]
When the combing is set to "Not in Skin" and with "Monotonic" turned on then that will be the movement you get.  That model is a severe case because of all the bumps that need to be gone around to avoid the skin area.  The problem you are seeing is exxagerated because of the geometry of the model.
If the nozzle was to cut through the skin and leave a trail of ooze it would mar the surface so the movement is there whether or not the skin has gone down yet.
I don't agree that this is a bug as the program is doing what it is designed to do.  I will agree it could be done better.  (This is why I never use monotonic on anything small or fussy).
I'll leave the bug label on this and I'll leave the report open for the Cura team to see.  Maybe it's something they've thought about already.

**Comment by alnavasa** [comment]
I get what you mean, 
Definitely not a bug, but could be improved, so feel free to change the status if you consider. 

It's not something that needs urgent fix for me, I just like to leave my User experience around for developers, sometimes they might appreciate, sometimes it's too much feedback.


I am more concerned with the other report I made which it's actually a bug and nobody looked at it :(.
