### ISSUE TITLE
Slicing error, never seen before

### ISSUE THREAD

**Issue by CaptScott331** [Ultimaker/Cura#17529]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

CR10-S

### Name abnormal settings

no

### Describe model location

no

### Describe your model

not this specific model, but previous models with exact same settings have sliced succesfully

### Add your .zip here ⬇️

[CCR10S_Manual_gearbox_axel_small_parts.zip](https://github.com/Ultimaker/Cura/files/13563437/CCR10S_Manual_gearbox_axel_small_parts.zip)

**Comment by 5axes** [comment]
Interesting case . The models are simple, but this model has a problem. It needs support and you've defined tree supports. But there's no room to create the support because of the other parts.

![image](https://github.com/Ultimaker/Cura/assets/11015345/5889e6e9-ddda-44c7-b8dc-720ab3c1e7dc)

Changing the position of the model or removing the support solves the issue.

![image](https://github.com/Ultimaker/Cura/assets/11015345/f156b8cb-c1d2-40f8-98e2-e1d65dbce9f3)

**Comment by Vandresc** [comment]
👋 Quick update on our side.
Your issue seems to have been resolved with this fix from our wonderful community member ThomasRahm!
(https://github.com/Ultimaker/CuraEngine/pull/2002)

I'll close this issue since it's resolved, a fix should be available with the upcoming release.

Thanks again, and please let us know if you run into any other issues 💪
