### ISSUE TITLE
Failed Slice only when Support Touching Build Plate

### ISSUE THREAD

**Issue by bigo93** [Ultimaker/Cura#17521]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Creality CR-10S Pro v1

### Name abnormal settings

Only when Support touching Buildplate

### Describe model location

Front centre

### Describe your model

Lens mount for Quest 2

### Add your .zip here ⬇️

[Lenses.zip](https://github.com/Ultimaker/Cura/files/13550435/Lenses.zip)

Will slice when Support Placement is set to Everywhere

**Comment by Vandresc** [comment]
👋 Quick update on our side.
Your issue seems to have been resolved with this fix from our wonderful community member ThomasRahm!
(https://github.com/Ultimaker/CuraEngine/pull/2002)

I'll close this issue since it's resolved, a fix should be available with the upcoming release.

Thanks again, and please let us know if you run into any other issues 💪
