### ISSUE TITLE
drop down model always reset to checked even if project is saved with unchecked objects

### ISSUE THREAD

**Issue by StmLord** [Ultimaker/Cura#17553]
### Cura Version

5.5

### Operating System

Mac OS Monterey

### Printer

Custom FFF

### Reproduction steps

1) place 1st object into bed 
2) place second object above (or inside) first by unchecking drop down model 
3) save project
4) quit and relaunch Cura and load saved project

### Actual results

all objects that was above zero on Z axis are reseted to Zero Z and Drop down model is again checked.

### Expected results

Z height should be saved with the project and all settings like Drop down model should be respected.

### Add your .zip and screenshots here ⬇️

[test.3mf.zip](https://github.com/Ultimaker/Cura/files/13606296/test.3mf.zip)

**Comment by Asterchades** [comment]
The only way I'm able to reproduce the issue as described is by enabling the global Cura setting "Automatically drop models to the build plate." This setting is a program-level setting and cannot be individually adjusted per model, but it's doing exactly what it says it's going to do - your file has six separate models in it, and it's dropping all six of them to the plate on load (while also enabling the "Drop Down Model" setting by default).

Since you did not provide a log file to verify it I can only assume that this setting is enabled in your client. Disable it, and the models will load with their respective Z values.

**Comment by StmLord** [comment]
Sorry for  that, Yes the option "automatically drop model to the built plate" was checked in the program settings, disabling it and it keeps the Z height of the object.

**Comment by themobydisk** [comment]
There really is a bug here, maybe 2:
1. When a user saves a 3MF file, then loads a 3MF file, they should have the same model in the same positions as when they saved.  Otherwise they cannot continue their work.  The setting "Automatically drop models to the build plate" makes sense when importing an STL with an unspecified coordinate system, but not a Cura-created 3MF where each object has explicit transforms in the 3dmodel.model file.  Cura should respect those transformations.
2. The setting "Automatically drop models to build plate" applies randomly to some of the "normal model" objects in the file.  See attached 3MF file for an example.  (Perhaps this is a separate bug?)

### Reproduction steps
1. Set "Automatically drop models to build plate" to true.
2. Load the attached file with Cura 5.6 or 5.7.  

### Expected result
The attached file was created in Cura 5.6 and has:
- 2 STL files that are merged named "MergedMesh"
- A cutting mesh named "Eraser(1)"
- 2 support blockers named "Eraser(7) and Eraser(8)"
- 6 normal models named: Eraser, Eraser(2), Eraser(3), Eraser(4), Eraser(5), and Eraser(6).
At the time they were saved, all of these objects had "Drop Down Model" unchecked.

Upon load, all of the objects should be in the positions saved in the 3MF file.  Only "MergedMesh" should be on the build plate.

### Actual result
The models are randomly dropped onto the build plate without regard to the configuration at the time of save:
- Good: 2 STL files that are merged named "MergedMesh" were already on the build plate.
- Good: The cutting mesh named "Eraser(1)" is not dropped onto the build plate.
- Bad: The 2 support blockers named "Eraser(7) and Eraser(8)" are dropped onto the build plate.
- Bad: **5 of the 6** normal models are dropped onto the build plate.  Eraser(2) is not, but the others are.

[UMS3_Waterbender_Ring - two colors, adaptive, ironing - one white layer almost at top -- lateral support.3mf.zip](https://github.com/Ultimaker/Cura/files/15052523/UMS3_Waterbender_Ring.-.two.colors.adaptive.ironing.-.one.white.layer.almost.at.top.--.lateral.support.3mf.zip)

**Comment by themobydisk** [comment]
> Sorry for that, Yes the option "automatically drop model to the built plate" was checked in the program settings, disabling it and it keeps the Z height of the object.

That isn't a solution, it's just a workaround.  Cura is overriding a local setting with a global setting.  That's backwards.  

To make this 3MF file, you unchecked the "Drop Down Model" setting on object then moved it to a position.  Cura then saved a transformation matrix for that object into the 3MF file.  Cura is not respecting that setting or that transformation.  As a result, users are forced to uncheck the "Drop Down Model" whenever loading a 3MF, then re-check it when loading an STL.  That's not right.

**Comment by themobydisk** [comment]
> The only way I'm able to reproduce the issue as described is by enabling the global Cura setting "Automatically drop models to the build plate." This setting is a program-level setting and cannot be individually adjusted per model

It can be individually adjusted per model.  Cura is just not respecting that setting.  The user unchecked "Drop down model" on the individual object and assigned it a Z coordinate.  That was saved into the 3MF as a transform matrix in the 3dmodel.model file.  Cura does not save "drop down model" check box state to the 3MF, which it could do.  But it can be inferred by the fact that there is a transform in the 3dmodel.model file.  Cura **does** respect this setting if the object is configured as a "cutting mesh" but it does not respect it on "normal model" or "support blocker."
