### ISSUE TITLE
Ult2+ Extruder temp not correct

### ISSUE THREAD

**Issue by BobFre** [Ultimaker/Cura#1755]
I have stringing and I have lowered the extruder temperature in the settings.  Nothing has seemed to work.  When I was printing I checked the temperature with Tune and instead of the 190 I set it too, it is 240.  I have tried all the PLA selections in the Materials selections and still get the same problem.  Any suggestions?

**Comment by Ghostkeeper** [comment]
For the Ultimaker 2+ you can't set the temperature via Cura. I don't know how you lowered the temperature in the settings, because the temperature should not be displayed in those settings if you have the Ultimaker 2+ selected.

The only thing that controls the temperature is the printer itself. There you can adjust the temperature on the display on the printer.
