### ISSUE TITLE
Ad Printer for Flasforge brand

### ISSUE THREAD

**Issue by CarloSpecchio** [Ultimaker/Cura#17574]
### Is your feature request related to a problem?

Dear developer, 
Recently I bought a Flashforge Printer (Adventurer 5M Pro). Unfortunately this printer is not available in Cura.

### Describe the solution you'd like

Would it be possible to add this printer to the printer database of Cura? (Maybe for the next update release).
In advance accept my best regards and thank's for your great work.
Stay healthy and always happy.
Carlo Specchio
(from the Grand Duchy of Luxembourg)

### Describe alternatives you've considered

I have no alternative as using another slicer software. 

### Affected users and/or printers

I suppose all users who posses the same printer as I do.

**Comment by Asterchades** [comment]
Unfortunately the Cura team only has the time and appropriate hardware to add and maintain Ultimaker printer definitions. This now includes MakerBot printers since the companies merged, for obvious reasons, but cannot reasonably extend to outside manufacturers.

All other printer definitions are provided by the community through pull requests here on GitHub. These can come from individuals or from the manufacturers themselves. If you'd like to learn more about creating your own definition, either for personal use or to submit for others, you can find more details here: https://github.com/Ultimaker/Cura/wiki/Adding-new-machine-profiles-to-Cura
