### ISSUE TITLE
An old machine but well known.

### ISSUE THREAD

**Issue by XChrisylX-maker** [Ultimaker/Cura#17584]
### Is your feature request related to a problem?

Not able to add a Flashforge Creator Pro I use for several years, this printer is not included on Cura's settings. The Flashforge software, Flashprint, is not able on my OS (Apple Sonoma, ARM M2).  Cura's so much better but old items are rarely integrated with new tech. Thanks a lot for your understanding. best regards.
Christian

### Describe the solution you'd like

Integration of the old Creator Pro on Cura.

### Describe alternatives you've considered

None.

### Affected users and/or printers

Flashforge Creator Pro.

**Comment by Asterchades** [comment]
Unfortunately the Cura team only has the time and appropriate hardware to add and maintain Ultimaker printer definitions. This now includes MakerBot printers since the companies merged, for obvious reasons, but cannot reasonably extend to outside manufacturers.

All other printer definitions are provided by the community through pull requests here on GitHub. These can come from individuals or from the manufacturers themselves. If you'd like to learn more about creating your own definition, either for personal use or to submit for others, you can find more details here: https://github.com/Ultimaker/Cura/wiki/Adding-new-machine-profiles-to-Cura
