### ISSUE TITLE
Profile for Ender 3 V2 Neo

### ISSUE THREAD

**Issue by igorluppi** [Ultimaker/Cura#17614]
### Is your feature request related to a problem?

I have not found a profile for Ender 3 V2 Neo

### Describe the solution you'd like

I would like a file to import for Cura or an official alternative from Cura devs for this profile.

### Describe alternatives you've considered

File or step by step settings.

### Affected users and/or printers

Ender 3 V2 Neo users.

### Additional information & file uploads

Beginner in Cura here, please be kind. My first time with this slicer, looks pretty good.

**Comment by Asterchades** [comment]
Unfortunately the Cura team only has the time and appropriate hardware to add and maintain Ultimaker printer definitions. This now includes MakerBot printers since the companies merged, for obvious reasons, but cannot reasonably extend to outside manufacturers.

All other printer definitions are provided by the community through pull requests here on GitHub. There is currently a pull request active for this printer and its immediate predecessor (#13580). However it still appears to be waiting on the original author to update the files as requested (print head dimensions), then request a review.

NB The Ender-3 v2 Neo is functionally identical to the original Ender-3 Pro, save the inclusion of the ABL probe. As such the included Ender-3 Pro definition should work just fine, though you will need to manually perform your own ABL operations or edit the Start GCode to include a `G29` (to create a new mesh) or `M420 S1` (to activate an existing mesh) following the existing `G28` command.
