### ISSUE TITLE
Slicing Skadi cover failed

### ISSUE THREAD

**Issue by PeterAlcivar** [Ultimaker/Cura#17688]
### Cura Version

5.5.0

### Operating System

Windows 11

### Printer

Creality Ender-3 Max

### Describe model location

No

### Describe your model

This is a cup cover with name. I have printed the same thing before, the only difference being I increased the disk thickness from 2mm to 3mm.

### Add your .zip here ⬇️

[CE3MAX_Cup_Cover_Large_3_Skadi.zip](https://github.com/Ultimaker/Cura/files/13697095/CE3MAX_Cup_Cover_Large_3_Skadi.zip)

**Comment by 5axes** [comment]
You don't need Support for this part. And certainly not a Tree Support.

![image](https://github.com/Ultimaker/Cura/assets/11015345/3084231e-cd49-4b27-9f95-a922e890009d)


An other Tree Support issue : https://github.com/Ultimaker/Cura/discussions/16440#discussioncomment-7790452

Slice Failed due to **Tree Support** 

https://github.com/Ultimaker/Cura/issues/17688
https://github.com/Ultimaker/Cura/issues/17670
https://github.com/Ultimaker/Cura/issues/17655
https://github.com/Ultimaker/Cura/issues/17591
https://github.com/Ultimaker/Cura/issues/17597
https://github.com/Ultimaker/Cura/issues/17582
https://github.com/Ultimaker/Cura/issues/17578
https://github.com/Ultimaker/Cura/issues/17575
https://github.com/Ultimaker/Cura/issues/17549
https://github.com/Ultimaker/Cura/issues/17529
https://github.com/Ultimaker/Cura/issues/17521
https://github.com/Ultimaker/Cura/issues/17520
https://github.com/Ultimaker/Cura/issues/17479
https://github.com/Ultimaker/Cura/issues/17412
https://github.com/Ultimaker/Cura/issues/17351
https://github.com/Ultimaker/Cura/issues/17331

**Comment by Vandresc** [comment]
👋 Quick update on our side.
Your issue seems to have been resolved with this fix from our wonderful community member ThomasRahm/
(https://github.com/Ultimaker/CuraEngine/pull/2002)
 

I'll close this issue since it's resolved, a fix should be available with the upcoming release. 

Thanks again, and please let us know if you run into any other issues 💪

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
