### ISSUE TITLE
Imported profiles issue (Cura 2.5.0)

### ISSUE THREAD

**Issue by kr15uk** [Ultimaker/Cura#1768]
Ladies and gents,

I've found a bug with imported profiles. (profile imported from Cura 2.4)

Imported profile doesn't auto update automatically calculated fields, specifically temperature.
<img width="357" alt="screen shot 2017-05-01 at 12 35 19" src="https://cloud.githubusercontent.com/assets/5671041/25578962/5d5167bc-2e6b-11e7-8c81-9d3507b3e26f.png">

2nd glitch is that imported profile "takes over" profile view in settings.
I have active newly created profile in v2.5.0 but it shows partial data fields of imported profile instead of active/created one... Quite weird.
<img width="1920" alt="screen shot 2017-05-01 at 12 29 22" src="https://cloud.githubusercontent.com/assets/5671041/25579008/dcb83b0c-2e6b-11e7-8285-6b042ab80b1f.png">

Thanks.

**Comment by Ghostkeeper** [comment]
The profile you imported overrides the printing temperature, sets it to a fixed value. It doesn't scale along with the default printing temperature because the profile says it should be 195. You can click on the *i* to revert it to scale along with the default printing temperature.

The second glitch seems to be a bug indeed. I'll report that one in our internal tracker so we can plan it.

**Comment by BagelOrb** [comment]
Is that second bug fixed now?

**Comment by Ghostkeeper** [comment]
Nope, still in the backlog: CURA-3764

**Comment by Ghostkeeper** [comment]
Well not any more. Our project manager just removed this from our planning because it's older than 12 weeks.

**Comment by digitalfrost** [comment]
Stale ticket.
Refers to Cura 2.5
Was removed from backlog in 2017.
Can be closed?
