### ISSUE TITLE
Slicing Failed

### ISSUE THREAD

**Issue by bfrensley** [Ultimaker/Cura#17725]
### Cura Version

5.6.0

### Operating System

MacOS Catalina

### Printer

Anycubic Vyper

### Describe your model

MeshFix was performed and still failed.

### Add your .zip here ⬇️

[AV_DT - Wild West - Water Tower - Top.3mf.zip](https://github.com/Ultimaker/Cura/files/13744858/AV_DT.-.Wild.West.-.Water.Tower.-.Top.3mf.zip)

**Comment by 5axes** [comment]
An other "**Print Thin Walls**" issue : https://github.com/Ultimaker/Cura/discussions/16440#discussioncomment-7790452

![image](https://github.com/Ultimaker/Cura/assets/11015345/6a2afaba-6874-4b13-9f6c-29f67ec97363)


Duplicate Slice Failed due to **Print Thin Walls**

https://github.com/Ultimaker/Cura/issues/17725
https://github.com/Ultimaker/Cura/issues/17698
https://github.com/Ultimaker/Cura/issues/17679
https://github.com/Ultimaker/Cura/issues/17676
https://github.com/Ultimaker/Cura/issues/17671
https://github.com/Ultimaker/Cura/issues/17606
https://github.com/Ultimaker/Cura/issues/17560
https://github.com/Ultimaker/Cura/issues/17528
https://github.com/Ultimaker/Cura/issues/17503
https://github.com/Ultimaker/Cura/issues/17499
https://github.com/Ultimaker/Cura/issues/17470
https://github.com/Ultimaker/Cura/issues/17467
https://github.com/Ultimaker/Cura/issues/17457
https://github.com/Ultimaker/Cura/issues/17456
https://github.com/Ultimaker/Cura/issues/17496
https://github.com/Ultimaker/Cura/issues/17478
https://github.com/Ultimaker/Cura/issues/17439
https://github.com/Ultimaker/Cura/issues/17438
https://github.com/Ultimaker/Cura/issues/17410
https://github.com/Ultimaker/Cura/issues/17367
https://github.com/Ultimaker/Cura/issues/17344
https://github.com/Ultimaker/Cura/issues/17177
https://github.com/Ultimaker/Cura/issues/16688
https://github.com/Ultimaker/Cura/issues/16515
https://github.com/Ultimaker/Cura/issues/16417

**Comment by MariMakes** [comment]
Hi @rbenites,

Quick update from our side 👋
We are introducing a new tool to analyze slicing crashes like the one you reported. 💪

Even with the changes we made in the latest versions of Cura we still see that your model crashes. 🫤 But we have added your project file to our analyzing tool to start finding crashes that are similar to yours, which helps us to narrow down what the cause is of your crash so we can resolve this for you and others.

Hopefully, we can find a solution soon 🤞

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
