### ISSUE TITLE
Guide the user for getting the full build size

### ISSUE THREAD

**Issue by Dim3nsioneer** [Ultimaker/Cura#1773]
Official build size of the UM3 is 215x215x200mm (single extrusion) and 197x215x200mm (dual extrusion with support), respectively. Cura 2.5.0 allows for 214x215x200mm and 196x215x200mm (build plate adhesion off). So it's 1mm less in x direction, maybe this one can be added?
Anyway, those maximum sizes are hard to get; only by manipulating multiple options. Not every user will be able to find and change all those settings, and they can only be accessed in custom mode. So maybe a button in the recommended mode for getting maximum build size wouldn't be a bad idea?

**Comment by nallath** [comment]
You always have max build volume. But having a max build volume does not mean that you are able to get the maximum model volume. 

Getting the max model volume will have a big impact on model quality. You will need to change a whole bunch of settings that can mess up your prints big time, unless you know what you are doing. Adding an option for it suggests that it's something that is safe to do, which it isn't. 

As for the missing mm, this can be caused by rounding. There is a bit of that going on in a few places. The end result can then be that you "loose" a milimeter. To be honest, i think we have more important issues to fix then getting an extra mm of build space. Especially as it's not an easy fix.

**Comment by Dim3nsioneer** [comment]
Thanks for your reply. As from a technical point of view, the issue can be closed then.
