### ISSUE TITLE
the supports protrude beyond the outline

### ISSUE THREAD

**Issue by Marek3d** [Ultimaker/Cura#17788]
### Cura Version

5.5.0

### Operating System

Windows11

### Printer

Ender 3

### Reproduction steps

I'm trying to turn on the supports in the case where the supports do not touch the table.

### Actual results

Supports are generated outside the outline of the layers below, so they are printed in the air.
In the attached example, the problem is clearly visible for the large round support whose printing starts from the outer circle that does not touch anything at all.

### Expected results

The support should not protrude beyond the outline 
or be printed with additional support.

### Add your .zip and screenshots here ⬇️

[CE3E3V2_ball_chain_pulley_3.zip](https://github.com/Ultimaker/Cura/files/13773787/CE3E3V2_ball_chain_pulley_3.zip)
![Zrzut ekranu 2023-12-26 223331](https://github.com/Ultimaker/Cura/assets/60315406/c87a5619-af31-4764-832c-9958f3a36b3d)

**Comment by Asterchades** [comment]
The default settings have included a small amount of `Support Horizontal Expansion` since Cura 5.3 (March 8, 2023). The exact value is your `Support Line Width` plus 0.4mm when using regular-type Supports - Tree-type supports get no expansion. The design intent is to make the generated structures more reliable, and changes were also made to the default `Support Join Distance` and `Minimum Support Area` settings at the same time.

The project file you have provided does indeed have the `Support Horizontal Expansion` set to 0.8mm as expected, though it would appear that attempting to maintain the Zig Zag pattern is allowing it to push slightly further out than that. Reducing the expansion to 0mm makes _most_ of the Supports conform exactly - the one remaining Support that does not is being affected by the Use Towers` option due to how small the supported area is, and disabling that makes it conform as well.
