### ISSUE TITLE
Profile for Raise3D Pro3 Hyper speed

### ISSUE THREAD

**Issue by perhusaas** [Ultimaker/Cura#17784]
### Is your feature request related to a problem?

Slicer following these printers is just not good enough..

### Describe the solution you'd like

Profile for Raise3d Pro3 and Pro3 plus with the Hyper speed upgrade

### Describe alternatives you've considered

Learning Ideamaker, but it would still not give me the tree supports.. 

### Affected users and/or printers

Raise3d Pro3 and Pro3 plus with the Hyper speed upgrade

### Additional information & file uploads

I've tested this: [https://github.com/thijse/Raise3DPro3PlusforCura/tree/Pre-release](https://github.com/thijse/Raise3DPro3PlusforCura/tree/Pre-release), but it doesnt support the Hyper speed option (and still has some bugs)

**Comment by Asterchades** [comment]
Unfortunately the Cura team only has the time and appropriate hardware to add and maintain Ultimaker printer definitions. This now includes MakerBot printers since the companies merged, for obvious reasons, but cannot reasonably extend to outside manufacturers.

All other printer definitions are provided by the community through pull requests here on GitHub. These can come from individuals or from the manufacturers themselves. If you'd like to learn more about creating your own definition, either for personal use or to submit for others, you can find more details here: https://github.com/Ultimaker/Cura/wiki/Adding-new-machine-profiles-to-Cura
