### ISSUE TITLE
[5.6.0] Slicing incorrect -> closes some holes randomly (Remove holes is not activ!; Prucaslicer works)

### ISSUE THREAD

**Issue by tispokes** [Ultimaker/Cura#17797]
### Cura Version

5.6.0

### Operating System

W11

### Printer

SWX1

### Reproduction steps

Import file to Cura (first 5.3.0, then installed 5.6.0). 
Testet different profiles (custom, orgin one etc)

### Actual results

Not sliced correctly, see pics

### Expected results

Should slice part as reviewed (Prepare View)

### Add your .zip and screenshots here ⬇️

[Lichtfallep1.zip](https://github.com/Ultimaker/Cura/files/13779276/Lichtfallep1.zip)
3mf, log file and screenshots again

![image](https://github.com/Ultimaker/Cura/assets/45465820/c11e97c1-3e9b-4095-ae24-4a657817dc02)
![image](https://github.com/Ultimaker/Cura/assets/45465820/1efdad14-17ed-435b-8e66-7854f13c1e56)
![image](https://github.com/Ultimaker/Cura/assets/45465820/de20d98d-4205-4c50-b3fc-5081e6031898)

**Comment by Asterchades** [comment]
This model is broken. Each of those "vents" aside from the two at the top against the front has been made of three inverted surfaces - and those two still have two inverted surfaces each. Further to this the connections made to the Y-axis beams on the left-hand side of each of the vents, top and bottom, are being ambiguously defined by attempting to make a connection to a mid-point of a line rather than connecting to another vertex.

![image](https://github.com/Ultimaker/Cura/assets/29810435/69453595-99f5-42de-8740-e9a0bbc2b59f)

_Each of those red surfaces is a back face which should (as the name suggests) only ever be pointed inwards. The invalid lines are visible on the right-hand side of the Y-axis beam on the very left and centre._

Once the model is repaired it slices perfectly.

![image](https://github.com/Ultimaker/Cura/assets/29810435/a217d3d5-3078-4b04-9a0f-3c2ac32717e5)

Different slicers are going to have different repair facilities built in. It seems that PrusaSlicer's facilities are just handling _this_ model better than Cura's. Ultimately, however, it's always going to be pot luck as to whether a faulty model is going to work in _any_ slicer.
