### ISSUE TITLE
Slice error if tree support enabled

### ISSUE THREAD

**Issue by JustDimcore** [Ultimaker/Cura#17807]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Elegoo Neptune 3 pro

### Describe your model

Sliced ok if don't use tree support

### Add your .zip here ⬇️

[EN3PRO_Raspberry_cap.zip](https://github.com/Ultimaker/Cura/files/13782913/EN3PRO_Raspberry_cap.zip)

**Comment by Vandresc** [comment]
👋 Quick update on our side.
Your issue seems to have been resolved with this fix from our wonderful community member ThomasRahm!
(https://github.com/Ultimaker/CuraEngine/pull/2002)
 

I'll close this issue since it's resolved, a fix should be available with the upcoming release. 

Thanks again, and please let us know if you run into any other issues 💪

**Comment by HellAholic** [comment]
We made some improvements to prevent slicing fails in Cura 5.7.0 available to download now. I was able to slice your model successfully in 5.7.0. Could you test if that's the case for you as well?
You can download it here: https://github.com/Ultimaker/Cura/releases/tag/5.7.0
