### ISSUE TITLE
Voxelab aquila X2 Can you add this 3D printer to the software

### ISSUE THREAD

**Issue by cgriffin5021** [Ultimaker/Cura#17849]
### Is your feature request related to a problem?

Can you add the Voxelab Aquila X2 to your 3D slicer software.

### Describe the solution you'd like

Add the Voxelab Aquila X2 software to Cora

### Describe alternatives you've considered

Add the Voxelab Aquila X2 software to Cora

### Affected users and/or printers

Voxelab Aquila X2

**Comment by Asterchades** [comment]
Unfortunately the Cura team only has the time and appropriate hardware to add and maintain Ultimaker printer definitions. This now includes MakerBot printers since the companies merged, for obvious reasons, but cannot reasonably extend to outside manufacturers.

All other printer definitions are provided by the community through pull requests here on GitHub. These can come from individuals or from the manufacturers themselves. If you'd like to learn more about creating your own definition, either for personal use or to submit for others, you can find more details here: https://github.com/Ultimaker/Cura/wiki/Adding-new-machine-profiles-to-Cura

In the interim, just about any printer can be used with the Custom FFF Printer definition that's already provided. The Machine Settings may need to be altered, particularly Build Volume, Material Diameter, and perhaps the Start GCode (such as to include ABL commands), but so long as it understands regular GCode it will be functional.
