### ISSUE TITLE
Add A Ender 3 V3 KE Profile

### ISSUE THREAD

**Issue by maverickmoore63** [Ultimaker/Cura#17985]
### Is your feature request related to a problem?

I can never find the right things to enter a costom printer, and when i use another profile it always limits my speed so there is no time difference between 60mms and 300mms

### Describe the solution you'd like

I would like to see a KE profile added

### Describe alternatives you've considered

an explanation with an alternative

### Affected users and/or printers

V3 KE users

**Comment by Asterchades** [comment]
Unfortunately the Cura team only has the time and appropriate hardware to add and maintain Ultimaker printer definitions. This now includes MakerBot printers since the companies merged, for obvious reasons, but cannot reasonably extend to outside manufacturers.

All other printer definitions are provided by the community through pull requests here on GitHub. These can come from individuals or from the manufacturers themselves. If you'd like to learn more about creating your own definition, either for personal use or to submit for others, you can find more details here: https://github.com/Ultimaker/Cura/wiki/Adding-new-machine-profiles-to-Cura

In the interim, just about any printer can be used with the Custom FFF Printer definition that's already provided. The Machine Settings may need to be altered, particularly Build Volume, Material Diameter, and perhaps the Start GCode (such as to include ABL commands), but so long as it understands regular GCode it will be functional.

Note that there is currently an open pull request for the V3 KE [here](https://github.com/Ultimaker/Cura/pull/17519).
