### ISSUE TITLE
Incorrect object slicing, deep square open container

### ISSUE THREAD

**Issue by goofyseeker311** [Ultimaker/Cura#18003]
### Cura Version

5.6.0

### Operating System

Win11 RTX3080

### Printer

elegoo neptune 3 pro

### Reproduction steps

slicing a square open top container

### Actual results

slicing output is whole inside filled with grid support even if its empty and no top

### Expected results

should be bottom and four walls, no supports, only adhesion

### Add your .zip and screenshots here ⬇️

![akkuprojektituloste](https://github.com/Ultimaker/Cura/assets/19920254/0f6b6308-6bf1-455e-9bb1-5617ca3ce64e)
![akkuprojektituloste2](https://github.com/Ultimaker/Cura/assets/19920254/cb2f5929-523b-4847-817a-e2832191c171)
[EN3PRO_akkuprojekti12a.zip](https://github.com/Ultimaker/Cura/files/13927783/EN3PRO_akkuprojekti12a.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
When I open the 3mf file I get this model.  The red surfaces facing upward are inverted surfaces.  They are a problem because a slicer can't tell the inside from the outside.  The model needs to be repaired.
![image](https://github.com/Ultimaker/Cura/assets/64202104/c616d94d-1e23-4ed9-a311-f8ef3f3900b2)

That 3mf file is not a project file so I have to guess, and I'm guessing you might have "Remove all Holes" turned on.  The model errors can also cause a model to have false walls and/or tops/bottoms but the main culprit is usually "Remove all Holes".

I'll take the bug label off this for now.  Let us know if turning off "Remove all Holes" or repairing the model makes this problem go away.
It didn't show up when I sliced the model.
![image](https://github.com/Ultimaker/Cura/assets/64202104/211d7507-4fef-438d-8552-85b9cade8f77)

**Comment by goofyseeker311** [comment]
so i just need to make sure the surface normals are correct. hmm.
