### ISSUE TITLE
[3.2.1] Conical support hangs in mid-air

### ISSUE THREAD

**Issue by 651851996** [Ultimaker/Cura#1804]
cura2.3 Also have this problem，and 30° have this problem，20°have not

**Comment by Ghostkeeper** [comment]
Funnel support... You mean conical support?

Seems to work here.
![image](https://cloud.githubusercontent.com/assets/2448634/25940694/40d04396-3637-11e7-9c77-ad95b7ad5134.png)

**Comment by BagelOrb** [comment]
Could you please explain the problem a bit more?
I currently don't understand what the problem is.

**Comment by 651851996** [comment]
emm,use 30°,Wide range of support，Sometimes slashes are lost。Generally occurs in the oblique line and support the same---using Google Translate

**Comment by BagelOrb** [comment]
Could you attach screenshots?

Which language do you speak? Perhaps we can understand that better than Google translate can translate it ;)

**Comment by 651851996** [comment]
有道理。就是用30°Funnel support，当Funnel的方向和support的走向平行，可能会出现部分support丢失并产生问题

**Comment by BagelOrb** [comment]
Please include pictures of the layer view.

Please include the ".curaproject.3mf" file.

**Comment by 651851996** [comment]
now without pc，wait some day┐(´д｀)┌

**Comment by BagelOrb** [comment]
Ah ok.

**Comment by 651851996** [comment]
looklike that
![qq 20170724041009](https://user-images.githubusercontent.com/28496904/28502534-ded2f966-7026-11e7-906d-1baebb8a5a99.png)
![qq 20170724041110](https://user-images.githubusercontent.com/28496904/28502535-df0cf4a4-7026-11e7-8e9b-d72dfcbe9da7.png)
![qq 20170724041220](https://user-images.githubusercontent.com/28496904/28502536-df43420c-7026-11e7-914d-0482c4672904.png)

**Comment by Ghostkeeper** [comment]
I could reproduce this. It only seems to happen with zigzag support. What happens is well visible in 651851996's last screenshot: That stray line that's encircled **almost** hits the normal zig-line to the left of it, but not quite. On the layer below, the conical support pushes the line more to the left and as a result the line is now part of the normal border of the support area and because this line is on the opposite side of the zag, the line is not drawn any more.

I wonder what causes the loose lines like this though.
![image](https://user-images.githubusercontent.com/2448634/28828877-5fad4bc0-76d2-11e7-8cd8-0af92a5310cd.png)

**Comment by 651851996** [comment]
Is this model

**Comment by 651851996** [comment]
Is this model
![20170813134611](https://user-images.githubusercontent.com/28496904/29246490-8bec0b4e-802e-11e7-9ee1-7422c2cdb4ce.png)

**Comment by Ghostkeeper** [comment]
Our project manager just removed this from our planning because it's 12 weeks old.

**Comment by Ghostkeeper** [comment]
Yes, it still occurs. Nothing has changed in this regard.

![screenshot from 2018-03-13 11-06-11](https://user-images.githubusercontent.com/2448634/37335362-9b2ad564-26ae-11e8-9f76-8afc00badb50.png)
