### ISSUE TITLE
Failed to slice a dragon model

### ISSUE THREAD

**Issue by DaWhiteXD** [Ultimaker/Cura#18040]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Ultimaker S3

### Describe model location

Center

### Describe your model

An epic dragon model that failed to slice

### Add your .zip here ⬇️

[File link!](https://drive.google.com/file/d/1xrI1dyBIZgajbt21AeLyaxrtqr8ctwjS/view?usp=sharing)

**Comment by GregValiant** [comment]
Thanks for the report.
There are almost 10 million vertices in that model and most of them are wrong.  I could not get Cura to slice this even after trying to repair the model.
Here is what PrusaSlicer came up with.
![image](https://github.com/Ultimaker/Cura/assets/64202104/4fba3041-8bfb-414e-9898-55082e72c350)

There are so many errors in the model that it is impossible to tell if there is actually a Cura bug here.  Even after attempting to repair the model there are missing layers.  I don't believe it's possible to print this unless it is extensively re-worked.
PrusaSlicer reported that it is a 590 hour print and the gcode is over 16,000,000 lines long.  The print would likely fail due to missing layers.

I'll leave the bug label on this, but I'm going to close it as there is no way to tell where a problem might be.  I hope you understand.
