### ISSUE TITLE
Combine everything missing

### ISSUE THREAD

**Issue by cody42** [Ultimaker/Cura#182]
In cura 15.06 and later the "combine everything" option(s) is/are missing.

**Comment by BagelOrb** [comment]
meshfix_union_all
"Union Overlapping Volumes"
Settings > Preferences > Fixes

**Comment by cody42** [comment]
It is missing, see:
![missing](https://cloud.githubusercontent.com/assets/1199044/8904531/853b76de-3460-11e5-90c7-e24113beb409.JPG)
There is no fixes page in the settings and it is not listed in the fixes section of the macine section.

Version: Cura 15.06.02, prebuilt from ultimaker.com
OS: Windows 7 x64

**Comment by BagelOrb** [comment]
I'm sorry. I should have said it is fixed in the master branch, so the next major release has them.

Due to the fact that we cannot make new translations of the settings, we cannot introduce new settings in the current release.

Note that there is no fixes tab because you have no settings from that tab visible.

**Comment by tzminversion** [comment]
Im using Cura 15.06.03 an I still can choose "Combine everything".

I am constantly going back to 15.02.1 because features have been ripped out in the new version unfortunately :( shame really.

**Comment by BagelOrb** [comment]
Why don't you go back to 15.04 ?

The feature is in the current beta release.

**Comment by tzminversion** [comment]
Probably because I didn't know there was a 15.04 ;) Tnx!
