### ISSUE TITLE
Slicing Failed

### ISSUE THREAD

**Issue by zelk12** [Ultimaker/Cura#18251]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Anycubic Kobra 2 PRO

### Name abnormal settings

Supports

### Describe model location

No, no. Rotate XYZ Euler X-45 Y45

### Describe your model

Colibtaion cube

### Add your .zip here ⬇️

[Untitled.zip](https://github.com/Ultimaker/Cura/files/14179286/Untitled.zip)

**Comment by zelk12** [comment]
It works in the alpha build.
![изображение](https://github.com/Ultimaker/Cura/assets/42270055/7d0fda56-2ec8-4948-aec3-a94cb61d70af)

**Comment by HellAholic** [comment]
Thanks for checking on the alpha build. And also glad to hear the the problem has been resolved for the next build.
I'll close this ticket for now since there is nothing more we can do.
But please also participate in the beta period for the next release and provide your feedback then. It helps narrow things down and address issues as soon as possible.

Cheers!
Have a nice weekend.

**Comment by zelk12** [comment]
Ok.

**Comment by zelk12** [comment]
@HellAholic 
Also, can I ask a quick question about the alpha version here?

**Comment by zelk12** [comment]
And it's okay that the interface language in the alpha version is standard.

**Comment by zelk12** [comment]
Ok, thanks.
