### ISSUE TITLE
Enabling Tree supports causes some models to fail

### ISSUE THREAD

**Issue by Sciencesold** [Ultimaker/Cura#18272]
### Cura Version

5.6.0

### Operating System

Windows 10

### Printer

Sovol SV01PRO

### Name abnormal settings

Generate Supports: Enabled, Support Structure: Tree

### Describe model location

Center of build plate, sitting on the largest flat surface available

### Describe your model

I am able to successfully slice the file with Support Structure set to "Normal"

### Add your .zip here ⬇️

[File Unable to be sliced.zip](https://github.com/Ultimaker/Cura/files/14215491/File.Unable.to.be.sliced.zip)

**Comment by HellAholic** [comment]
We have a ticket with the aim to resolve/improve the behavior. It will be included in the next cura release.
For internal references CURA-11603

Could you try with this build: https://github.com/Ultimaker/Cura/discussions/18080

I expect that it will still crash, but we've added extra logging so that we can (hopefully) find what is causing this.
