### ISSUE TITLE
Slicing failed

### ISSUE THREAD

**Issue by crowley285** [Ultimaker/Cura#18270]
### Cura Version

5.6.0

### Operating System

windows 11

### Printer

Ender 3 pro

### Name abnormal settings

tree support

### Describe model location

middle

### Describe your model

clip for guitar cable

### Add your .zip here ⬇️

[files.zip](https://github.com/Ultimaker/Cura/files/14214928/files.zip)

**Comment by HellAholic** [comment]
We have a ticket with the aim to resolve/improve the behavior. It will be included in the next cura release.
For internal references CURA-11603

Could you try with this build: https://github.com/Ultimaker/Cura/discussions/18080

I expect that it will still crash, but we've added extra logging so that we can (hopefully) find what is causing this.
