### ISSUE TITLE
slicing Moana Glowing Heart of Te Fiti

### ISSUE THREAD

**Issue by nvaline** [Ultimaker/Cura#18275]
### Cura Version

5.6.0

### Operating System

windows 11

### Printer

sovol sv06

### Name abnormal settings

switched from normal supports to tree

### Describe model location

2 items center build plate

### Describe your model

2 roughly half dome shapes with opening on the bottom

### Add your .zip here ⬇️

[Moana Glowing Heart of Te Fiti.zip](https://github.com/Ultimaker/Cura/files/14217820/Moana.Glowing.Heart.of.Te.Fiti.zip)

**Comment by HellAholic** [comment]
Hey @nvaline,
We have a ticket with the aim to resolve/improve the behavior. It will be included in the next cura release.
For internal references CURA-11603

Could you try with this build: https://github.com/Ultimaker/Cura/discussions/18080

I expect that it will still crash, but we've added extra logging so that we can (hopefully) find what is causing this.
