### ISSUE TITLE
Odd/Even Slice Mode, Cura feature request

### ISSUE THREAD

**Issue by mscir** [Ultimaker/Cura#18311]
### Is your feature request related to a problem?

I'm researching printing a drone or RC plane, and just found there's something called light PLA which reduces weight about 40-50%. I was told that printing it is a bit tricky since it foams, so to look for models that can be printed in Vase mode, and to slice using the Even/Odd Slice mode. I had never heard of that so I searched and Prusa offers that, but I can't find the equivalent in my Cura 5.6.0 settings. Am I missing it in Cura? Is this something Cura doesn't currently support, that I should suggest to them? 

### Describe the solution you'd like

I'd like Cura to provide an option to enable Even/Odd Slice Mode as Prusa does. 

### Describe alternatives you've considered

I will use Prusa if you are not able to provide this feature.

### Affected users and/or printers

Anyone working with light weight PLA will be able to benefit from this.

**Comment by GregValiant** [comment]
The PrusaSlicer "Even-Odd" appears to have been developed specifically for models created by "3DLabPrint" which in turn were specifically designed to be sliced with Simplify3D.
Airplane parts and some sailboat hulls, are weight sensitive.  Whether they are printed in Vase mode or in Surface mode or with EvenOdd, or just regular, depends on how the specific model was designed.  Many airplane models are not valid for FDM printing because they are not true "solids" but rather collections of single-sided surfaces, so there must be workarounds either in the slicer, or in the settings.  You will find models that will slice better in Cura than Prusa, but other models will slice better in PrusaSlicer.
You won't know which is true until you settle on the model you want to print.

**Comment by mscir** [comment]
Thanks GregValiant, that's interesting and good to know. I guess that settles the issue. Cheers.
