### ISSUE TITLE
Top Surface Skin Layer Incorrect/Missing

### ISSUE THREAD

**Issue by SALXAPHONE** [Ultimaker/Cura#18472]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Creality Ender-5

### Reproduction steps

1. Load Test Cube Model
2. Slice with 0 Top Skin Layers and 4 Top Layers at 0.8 Thickness.
3. Compare to same model sliced with 3 Top Skin Layers at 0.4 Thickness and 4 Top Layers at 0.8 Thickness.
4. Slice again with 0 Top Skin Layers and 8 Top Layers at 0.4 Thickness.
5. Compare to same model sliced with 3 Top Skin Layers at 0.8 Thickness and 8 Top Layers at 0.4 Thickness.

### Actual results

The Top Skin Layers are missing from the model. The Top Skin Layers merged with the Top Layers. The total number of top layers should be equal to Top Layers plus Top Skin Layers, but it is only equal to Top Layers. This has caused pillowing with different prints.

### Expected results

The total number of top layers should be equal to Top Layers plus Top Skin Layers, which would allow the print to avoid pillowing.

### Add your .zip and screenshots here ⬇️

I have tried with multiple models, but has

**Comment by Asterchades** [comment]
This is by design. Top Surface Skin Layers _replace_ Top Layers - they don't add to them. They're intended for changing the properties of the existing layers, such as using a different pattern, a lower speed, a different extrusion width, or even a different extruder. It's how the feature has functioned since its inception back in Cura 2.7.0 (released August 30, 2017).

https://github.com/Ultimaker/Cura/releases/tag/2.7.0
> **Top surface skin**
> 
> Specify print settings of the top-most layers separately in order to improve print duration and achieve higher quality top surfaces.

If you want more total Top Layers, use more Top Layers.
