### ISSUE TITLE
List Index out of Range

### ISSUE THREAD

**Issue by RobinGosse2** [Ultimaker/Cura#18481]
### Cura Version

5.6.0

### Operating System

Win dnows 11 x 64

### Printer

Kobra Neo

### Reproduction steps

I created a reasonably simple shape, no truly complex geometry. I successfully printed more complicated stuff yesterday.

### Actual results

Error code: "List Index out of Range"

### Expected results

A successful print

### Add your .zip and screenshots here ⬇️

![Screenshot 2024-03-01 193900](https://github.com/Ultimaker/Cura/assets/93091153/5c0e0699-a9da-41f4-b9c4-570d75db540f)
[Hermann - Astrophotography Cradle - 004 (8)_PLA_2h55m.zip](https://github.com/Ultimaker/Cura/files/14466804/Hermann.-.Astrophotography.Cradle.-.004.8._PLA_2h55m.zip)

**Comment by GregValiant** [comment]
Thanks for the report.  It isn't clear what you were doing when the warning came up.
Can I assume that you successfully sliced a model and created a gcode file?
Can I also assume that you then opened the gcode in Cura 5.6.0 and attempted to print via the USB port?

USB printing is a legacy function in Cura and is included because some early UltiMaker printers require it.  It is no longer supported or updated as it has always been iffy.

Try printing from the SD card and see if the issue persists.
