### ISSUE TITLE
Slicing failed - War horse

### ISSUE THREAD

**Issue by VinnyAmbesek** [Ultimaker/Cura#18491]
### Cura Version

5.6.0

### Operating System

Windows 10

### Printer

Creality Ender-3 Pro

### Describe model location

No

### Describe your model

War horse rpg miniature

### Add your .zip here ⬇️

[HorseWar.zip](https://github.com/Ultimaker/Cura/files/14469883/HorseWar.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
If you load the Mesh Tools plugin from the Cura Marketplace you will see this and get a warning that the model is not watertight.
Your model is on the left and the model on the right has been repaired with MS3D Builder.  You can see that they are quite a bit different.
![image](https://github.com/Ultimaker/Cura/assets/64202104/adfd4977-d1c7-45d3-97e0-14775811b2e9)

If the original model was to slice you wouldn't be able to trust the gcode because of all the model errors.

I'm going to remove the bug label and close this.  After repairing the model - if you still have trouble slicing we can always re-open this.  I hope you understand.
