### ISSUE TITLE
No support when surface mode = surface

### ISSUE THREAD

**Issue by titatovenaar1** [Ultimaker/Cura#1852]
When setting the surface mode to surface (within special modes) no support is generated. My printer is an UM3.

greets,

**Comment by BagelOrb** [comment]
Why would you want support and surface mode? The surface will then probably stick more to sort than to other surface lines.

**Comment by titatovenaar1** [comment]
I want to print an automotive bumper part in scale 1/10. These parts are real CAD data for new projects The walls are very thin and only show in surface mode

**Comment by BagelOrb** [comment]
I suggest you set the Horizontal Expansion to something like 0.2mm instead.

Op 22 mei 2017 17:17 schreef "titatovenaar1" <notifications@github.com>:

I want to print an automotive bumper part in scale 1/10. These parts are
real CAD data for new projects The walls are very thin and only show in
surface mode

—
You are receiving this because you were assigned.

Reply to this email directly, view it on GitHub
<https://github.com/Ultimaker/Cura/issues/1852#issuecomment-303131178>, or mute
the thread

**Comment by titatovenaar1** [comment]
I tried the site MakePrintable. This seems to work pretty good.

Thanks, I will try the horizontal expansion

**Comment by titatovenaar1** [comment]
Hi I tried the horizontal expansion, but the support disappeared same as with the surface mode.

**Comment by BagelOrb** [comment]
That sounds odd. Are you sure you hadn't left the surface mode on by
accident? Are you sure the model even needs support?

Op 22 mei 2017 21:30 schreef "titatovenaar1" <notifications@github.com>:

**Comment by titatovenaar1** [comment]
Ok, problem is solved with the horizontal expesion set to .2

**Comment by titatovenaar1** [comment]
Expansion
