### ISSUE TITLE
Cura is handling device departure/arrival notifications from Windows poorly.

### ISSUE THREAD

**Issue by gbarbehenn** [Ultimaker/Cura#18528]
### Cura Version

5.6.0

### Operating System

Windows 10

### Printer

Elegoo Neptune 3 Pro

### Reproduction steps

Print a job to USB.  Turn off the printer when done.  Turn printer back on, and reload model.  Reslice and attempt to print to USB, it won't be one of the options.  It is necessary to uplug the USB from the printer for a few seconds, then replug it in, then the "print to USB" will be available again.
Often this will happen on the first print job, but I haven't been able to isolate the combination of actions that causes the to happen on the first print job.

### Actual results

"Print to USB" isn't available after slicing.

### Expected results

If the printer is on and connected, "Print to USB" should be available.

### Add your .zip and screenshots here ⬇️

No further information is required to duplicate the problem.

**Comment by GregValiant** [comment]
Thanks for the report.
USB Printing is a legacy function that is included with Cura because some early Ultimaker printers require it.  It is not supported or updated.  Consequently...it either works or it doesn't.
The reason it was abandoned by UltiMaker was that it is glitchy and is dependent on the computer and printer hardware to function.  The software has no control over what particular USB hardware is installed in the devices.
Printing via the SD card is the preferred method.  Using something like Octoprint works well.
I'll leave the bug label on but I'll go ahead and close this.  I hope you understand.
