### ISSUE TITLE
Cura USB print random stopp

### ISSUE THREAD

**Issue by GameFromWood** [Ultimaker/Cura#18542]
### Cura Version

5.6.0

### Operating System

Windows 10

### Printer

Elegoo Neptune 3

### Reproduction steps

I started printing with the Print via USB function and after 1:40 hours the printer simply stopped and no longer moved.
This happened to me twice today out of 8 prints

### Actual results

printer stopped at half print

### Expected results

printer should move

### Add your .zip and screenshots here ⬇️

[cura.txt](https://github.com/Ultimaker/Cura/files/14528274/cura.txt)

**Comment by GregValiant** [comment]
Thanks for the report.
USB printing is included as a legacy feature of Cura because some older Ultimaker printers require it.  It is no longer supported or updated.  You can move to something like Octoprint or use the SD card.
I'll leave the bug label on this but I'll close it.  There are so many different combinations of hardware, software, port drivers, and firmware out there that it isn't really possible to maintain it.  It either works or it doesn't.  Sorry.
