### ISSUE TITLE
Don't have access to support settings....

### ISSUE THREAD

**Issue by demetan71** [Ultimaker/Cura#18621]
### Cura Version

5.6

### Operating System

windows 11

### Printer

Anycubic Chiron wiht skr board

### Reproduction steps

I want to change support settings because I'm unable to remove it without damage the part.....  I'm always have to change for another slicer for support.  Try many version of Cura, the 5.6, today I switched to 5.4, same thing, no access to support settings
![Capture d’écran 2024-03-15 102323](https://github.com/Ultimaker/Cura/assets/50704727/634004f6-77c4-4b36-adc3-d2072163266f)

### Actual results

I want to change support settings because I'm unable to remove it without damage the part.....  I'm always have to change for another slicer for support.  Try many version of Cura, the 5.6, today I switched to 5.4, same thing, no access to support settings
![Capture d’écran 2024-03-15 102323](https://github.com/Ultimaker/Cura/assets/50704727/634004f6-77c4-4b36-adc3-d2072163266f)

### Expected results

I want to change support settings because I'm unable to remove it without damage the part.....  I'm always have to change for another slicer for support.  Try many version of Cura, the 5.6, today I switched to 5.4, same thing, no access to support settings
![Capture d’écran 2024-03-15 102323](https://github.com/Ultimaker/Cura/assets/50704727/634004f6-77c4-4b36-adc3-d2072163266f)

### Add your .zip and screenshots here ⬇️

![Capture d’écran 2024-03-15 102323](https://github.com/Ultimaker/Cura/assets/50704727/b6ca535e-0b8d-4671-b4cd-6e031e2cd4b6)

**Comment by demetan71** [comment]
Sorry, it work with version 5.4, but I don't know how to delete this tread!!!

**Comment by HellAholic** [comment]
Hey @demetan71 
When support is disabled, all the settings regarding the support are hidden/not displayed. Additionally, you can change the view to show you all of the settings instead of the basic view from the burger menu on top right of the settings view.

![image](https://github.com/Ultimaker/Cura/assets/28710690/ccbd631d-071c-44f0-aa93-6f68f2e107f9)
![image](https://github.com/Ultimaker/Cura/assets/28710690/b13c7198-c25c-4a6e-8203-9d810fa3becd)
![image](https://github.com/Ultimaker/Cura/assets/28710690/513e876f-60a8-43ff-a463-29ca95566966)

Glad you found a workaround, will close this issue.
