### ISSUE TITLE
baby groot won't slice

### ISSUE THREAD

**Issue by OdinsonEntertainment** [Ultimaker/Cura#18634]
### Cura Version

5.6.0

### Operating System

windows 11

### Printer

elegoo neptune 3 pro

### Name abnormal settings

no

### Describe model location

no

### Describe your model

baby groot planter

### Add your .zip here ⬇️

[Baby Groot Planter No Eyes - 6495902.zip](https://github.com/Ultimaker/Cura/files/14624344/Baby.Groot.Planter.No.Eyes.-.6495902.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
There have been numerous reports of slicing failing on Windows 11 systems.  Hopefully this will be fixed in 5.7.0.
I'll mark this as a duplicate report and go ahead and close this.  I hope you understand.

This is your model in Cura 5.6.0 but on a Win10 computer.
![image](https://github.com/Ultimaker/Cura/assets/64202104/bb2a54c6-f686-4232-af8e-817807f3005b)
