### ISSUE TITLE
Error de corte

### ISSUE THREAD

**Issue by fanloeb** [Ultimaker/Cura#18638]
### Cura Version

5.6.0

### Operating System

Windows 10

### Printer

Hellbot Magna SE 32bits

### Name abnormal settings

Error de corte

### Describe model location

Continúa el error también a 90°

### Describe your model

Es la primera vez que lo intento.

### Add your .zip here ⬇️

[HMSE_messi.zip](https://github.com/Ultimaker/Cura/files/14625612/HMSE_messi.zip)

**Comment by MariMakes** [comment]
Hi @fanloeb,

Welcome to the UltiMaker Cura Github 🚀 

Several slicing crashes have been resolved with the 5.7 Beta release.
It also fixed your issue since I was able to slice your file:
![image](https://github.com/Ultimaker/Cura/assets/40423138/a23a1e0a-0845-4182-98cd-d55a23cb7b3d)

You can download the Cura version here: [https://github.com/Ultimaker/Cura/releases/tag/5.7.0-beta.1](https://github.com/Ultimaker/Cura/releases/tag/5.7.0-beta.1)

I'll close this issue since it's resolved.
Thanks again, and please let us know if you run into any other issues 💪
