### ISSUE TITLE
cant see normal preview only a slice of it 

### ISSUE THREAD

**Issue by Sjawel123** [Ultimaker/Cura#18650]
### Cura Version

5.6

### Operating System

windows11

### Printer

bibo2

### Reproduction steps

upgraded cura   now the preview looks odd and incomplete

### Actual results

nothing

### Expected results

how to  change it back to normal preview  a full preview with all the layers in yellow

### Add your .zip and screenshots here ⬇️

![image](https://github.com/Ultimaker/Cura/assets/122851876/2a6463f6-87dc-4ad6-822c-c318d1b401ed)

**Comment by HellAholic** [comment]
@Sjawel123 You're running the preview in compatibility mode. If you did not intend this behavior you can revert it by unchecking the "Force layer view compatibility mode" in Preferences > General. Note a restart of the application will be required for the changes to take effect.
Alternatively, if you only wish to see all the layers in compatibility mode rather than just the top layers you can uncheck "Only Show Top Layers" in the drop down for Color scheme.
![image](https://github.com/Ultimaker/Cura/assets/28710690/a838e83a-9668-4af4-8890-d840da50860d)

I don't see a bug here so I'm closing this issue.
