### ISSUE TITLE
o cura não está aparecendo o percurso de camada

### ISSUE THREAD

**Issue by Edsonvh1976** [Ultimaker/Cura#18702]
### Cura Version

5.7.1

### Operating System

Windows 11

### Printer

Ender 3

### Name abnormal settings

não foi feito nenhuma alteração

### Describe model location

ele corta quando coloco varios objetos na mesa

### Describe your model

sim

### Add your .zip here ⬇️

não aparece o percurso de camada

**Comment by HellAholic** [comment]
Hey @Edsonvh1976 ,
There is currently an issue where the layers that do not contain any paths - empty gaps in model - cause a visual glitch in the preview (CURA-11695). However, without a project files or screenshots or some sort of clarification about the issue we cannot proceed any further or attempt to find the root cause. Please include either clear steps to reproduce the issue in combination with screenshots or a project file that highlights the issue you're experiencing.
