### ISSUE TITLE
Unexpected error when slicing

### ISSUE THREAD

**Issue by Lookitdisguy** [Ultimaker/Cura#18725]
### Cura Version

5.6.0

### Operating System

Windows 10

### Printer

Sovol SV03

### Name abnormal settings

Tried the Spiralize Outer Countour feature, tried default profile and it still crashes

### Describe model location

no it does not slice

### Describe your model

Its a vase and its my first time trying to print it, it is not watertight and I did try the mesh fix

### Add your .zip here ⬇️

[SS_[shelled]An-Over-Engineered-Vase.zip](https://github.com/Ultimaker/Cura/files/14751589/SS_.shelled.An-Over-Engineered-Vase.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
5.6 struggled with certain organic shapes.  The bugs were worked on and so far 5.7beta seems to be much improved and although this would not slice in 5.6.0 it does slice in 5.7beta.
MS 3d Builder has a more capable repair tool than the one provided by Mesh Tools.  It's available in the Microsoft store.

I'll mark this as a duplicate and close it since the fix seems to have been made.
This model develops a lot of individual "islands" as it is printing so it isn't a candidate for Spiralize.
![image](https://github.com/Ultimaker/Cura/assets/64202104/c9d725b7-1c2a-47c9-b14e-38ac32f83e26)
