### ISSUE TITLE
Slicing failed while trying to cut a hole in bottom layers

### ISSUE THREAD

**Issue by PythonesqueSpam** [Ultimaker/Cura#18736]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Custom

### Describe model location

No

### Describe your model

Yes before trying cutting

### Add your .zip here ⬇️

[AA8_Engine Mount Shell.zip](https://github.com/Ultimaker/Cura/files/14763610/AA8_Engine.Mount.Shell.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
The bullet shaped piece is full of errors and the pieces haven't been merged properly.  That will always cause problems.
This is your model sliced in PrusaSlicer.
![image](https://github.com/Ultimaker/Cura/assets/64202104/a203b303-1d3b-423f-b2be-b7a7516ac561)

Using Cura's Mesh Tools I split the model. 
![image](https://github.com/Ultimaker/Cura/assets/64202104/2a1d35ee-502a-495d-90c0-fcf641ecb5b0)

So there isn't any way to say if there is a bug causing the problem because the model is a mess.
I'll go ahead and remove the bug label and close this.  I hope you understand.
