### ISSUE TITLE
scaling problems

### ISSUE THREAD

**Issue by noahcentineo03** [Ultimaker/Cura#18759]
### Cura Version

5.6.0

### Operating System

windows 11

### Printer

Creality ender 3 v2

### Reproduction steps

1.when i scaled above 400% it's unable to slice

### Actual results

![image](https://github.com/Ultimaker/Cura/assets/165359669/2fb02c13-ede1-4b96-beea-1798c8ced81e)

### Expected results

sliced file with the gcode

### Add your .zip and screenshots here ⬇️

![image](https://github.com/Ultimaker/Cura/assets/165359669/a63fec4d-835d-46fa-ab09-a555d3255b61)

**Comment by Asterchades** [comment]
I'm honestly not surprised that the slicing failed here - that model has been made extremely poorly. The red surfaces indicate overhang and should never appear _on top_ of a model, and the polkadot patterns indicate disconnected, volume-less, or otherwise faulty geometry that similarly cannot slice. Each of these issues is going to be made more significant when scaling it as they represent a larger amount of the model's surface. Given the amount of errors, even if this did finish slicing it would probably have looked very little like the model itself save maybe the desk.

It needs to be repaired. It's entirely possible that's all it needs to slice correctly. Given you appear to be using Windows you can try using MS 3D Builder to repair it automatically, though do verify how it looks coming out the other side as that many faults could easily lead to problems that require manual intervention.

That said, without a project file - as was requested when submitting this report - it's impossible to perform any diagnostics on this specific issue. It would also be worth trying Cura 5.7 ([currently in beta](https://github.com/Ultimaker/Cura/releases/tag/5.7.0-beta.1)) as it incorporates both additional fixes for such issues and better reporting facilities for engine crashes.
