### ISSUE TITLE
Cura keeps calling a fatal error whenever I upload an stl

### ISSUE THREAD

**Issue by AyyoGithub** [Ultimaker/Cura#18778]
### Cura Version

5.6.0, 5.7.0 Beta 1

### Operating System

MacOs Montery

### Printer

Anycubic Kobra

### Reproduction steps

Nothing, just tried to upload a file and 2 error messages were shown

### Actual results

2 error messages show up saying fatal error 

### Expected results

You should be able to continue slicing

### Add your .zip and screenshots here ⬇️

<img width="638" alt="Screen Shot 2024-03-31 at 8 37 56 AM" src="https://github.com/Ultimaker/Cura/assets/163337873/0477ffa1-c6cd-4481-b616-2df451c52b10">

**Comment by HellAholic** [comment]
Hey @AyyoGithub ,
Could you please elaborate on the issue you're experiencing? Are you using a plugin? Does the issue happen after slicing? Did you change specific settings? Do you have any plugins installed?
Also it's unclear to us what you mean by "Upload". Officially we only have upload to Digital factory, so if the issue is tied to a plugin, then reporting it on the repository of the plugin would be best to address it.
