### ISSUE TITLE
Error al trasladas la figura en vista previa

### ISSUE THREAD

**Issue by Francisco-Javier-Carreon-Duran** [Ultimaker/Cura#18801]
### Cura Version

5.4.0

### Operating System

Windows 11

### Printer

kingroon kps3

### Name abnormal settings

no

### Describe model location

no

### Describe your model

si

### Add your .zip here ⬇️

<img width="413" alt="Captura de pantalla 2024-04-02 234148" src="https://github.com/Ultimaker/Cura/assets/148082405/296e2ea0-e7c2-40f7-9f79-5e95ef276d71">

**Comment by HellAholic** [comment]
Hey @Francisco-Javier-Carreon-Duran , 
Can you provide some information here? We can't help you with your issue at the moment.
Please use the fields to describe your issue rather than answering Yes/No to the example questions there.
Add steps to reproduce or a model. And lastly let us know what is the expected behavior and what is the actual results that is causing the issue for you.

**Comment by rburema** [comment]
Could you try using the new 5.7.0? Does the issue still happen in that version. As I recall, there might have been some changes to how we handle the tool-affordances since 5.4.0
