### ISSUE TITLE
Very small font in the menu

### ISSUE THREAD

**Issue by rom119** [Ultimaker/Cura#18805]
### Cura Version

5.7.0 beta1

### Operating System

Win 11

### Printer

Anycubic Vyper

### Reproduction steps

Very small font in the menu

### Actual results

Very small font in the menu

### Expected results

![Small font in menu](https://github.com/Ultimaker/Cura/assets/96545004/db73458b-2558-4dfc-8099-489e417c42f2)

### Add your .zip and screenshots here ⬇️

[Small font in menu.zip](https://github.com/Ultimaker/Cura/files/14853184/Small.font.in.menu.zip)

**Comment by HellAholic** [comment]
Hey @rom119 ,
Can you point out the section that has a very small font?
From the picture I do not see any text with very small font.

**Comment by HellAholic** [comment]
![image](https://github.com/Ultimaker/Cura/assets/28710690/1a85ee59-9e50-41fc-bfb9-98ef6351aef5)
Here is the top bar text across different versions of Cura.
The font size has been consistent since 4.13.1
If you wish to have larger font size then that would be a feature request rather than a bug.

A bug indicates a behavior outside of the expected parameters.
I am closing this report as I do not see an issue here.
