### ISSUE TITLE
Slicing error 

### ISSUE THREAD

**Issue by Dr-pollo12** [Ultimaker/Cura#18830]
### Cura Version

5.6

### Operating System

Windows 10

### Printer

Creality Ender 3 Neo Max

### Name abnormal settings

first time 

### Describe model location

living room ambient, No A/C

### Describe your model

I cant even slice the model 

### Add your .zip here ⬇️

Im new in this 3D printing thing and when im slicing the model it just dropout a slice error and cant preview the project. Havent print anything, yet. This is a project for medical school.

https://we.tl/t-kTQpfJCwLB

**Comment by GregValiant** [comment]
Thanks for the report.
Cura 5.6.0 had some problems when trying to slice "organic" models.  Cura 5.7.0 is out and is much improved.
This sliced for me in 5.7.0.
![image](https://github.com/Ultimaker/Cura/assets/64202104/86d42914-dbac-4449-ac2e-b2ed45a50a34)

I'll mark this as a duplicate and go ahead and close it since the problem seems to be fixed.

I turned off supports for this as the pelvic model has floating pieces and they would generate a lot of support (it took a LONG time to slice without supports).  Even without support this is a 120 hour print.  Printing both models at the same time limits the amount of floorspace for supports to grow for each model, and is inordinately complex with a high chance of failure.
