### ISSUE TITLE
Cura 2.6 Beta - z hop no longer functions

### ISSUE THREAD

**Issue by notnyt** [Ultimaker/Cura#1883]
z hop is no longer working since 2.6 beta

**Comment by BagelOrb** [comment]
Do you have Z hop Only Over Printed Parts enabled?

**Comment by notnyt** [comment]
Yes, and when it moves over printed parts, it still does not Z hop.  This was working normally in 2.5

**Comment by notnyt** [comment]
Nevermind, this looks like it's in the g-code just not displayed in the layers view

**Comment by BagelOrb** [comment]
Non retracted moves are dark blue. Moves which are retracted or z hopped
are displayed in light blue.

Op 26 mei 2017 10:18 schreef "Rob Mosher" <notifications@github.com>:

Nevermind, this looks like it's in the g-code just not displayed in the
layers view

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/Ultimaker/Cura/issues/1883#issuecomment-304221690>, or mute
the thread

**Comment by notnyt** [comment]
was working in s3d a bit where the retract/hop moves show the vertical lift, didn't realize when I was in Cura that they weren't shown
