### ISSUE TITLE
Slicing not loading at all

### ISSUE THREAD

**Issue by ThatOtherNateGuyOnYouTube** [Ultimaker/Cura#18847]
### Cura Version

5.4.0

### Operating System

Windows11

### Printer

Elegoo Neptune 3 max

### Reproduction steps

Used meshmixer to fix “model not manifold” error and exported file as STL binary. Dropped STL file on the workspace. Resized x to 200mm. Used suggested slicer settings. Slicer processed but doesn’t load at all. 

### Actual results

Slicer processed but then doesn’t load at all, the bar does not fill with any color, and I receive no error codes. 

### Expected results

Model should slice properly to prepare for printing 

### Add your .zip and screenshots here ⬇️

I will add the files soon. Currently, cura wont even let me save the file, it freezes.

**Comment by GregValiant** [comment]
Thanks for the report.
Cura versions 5.3 thru 5.6 had problems slicing.  Cura 5.7.0 looks to be much better.
Install 5.7.0 and see if the problem has been addressed.
I'll mark this as a duplicate slicing error and go ahead and close it as the problem was worked on extensively.  I hope you understand.
