### ISSUE TITLE
Slicing Failed same issue different versions 5.6.0 -> 5.7.0

### ISSUE THREAD

**Issue by zIlgar** [Ultimaker/Cura#18848]
### Cura Version

5.7.0

### Operating System

Windows 11 Pro

### Printer

Creality Ender 3v2

### Name abnormal settings

tree support

### Describe your model

xbox phone stand

### Add your .zip here ⬇️

[CE3E3V2_M5_Nut.zip](https://github.com/Ultimaker/Cura/files/14902269/CE3E3V2_M5_Nut.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
This sliced for me in both 5.6.0 and 5.7.0.
Use the "Help | Show Configuration Folder" command to find the CUra.log file.  Zip it and post the zip folder here.  Maybe something in there will point to what is going on with your system.
As a quick check - right click on the Cura icon on your desktop and select "Run as Administrator".  There is some evidence that it might be where the problem is.
