### ISSUE TITLE
Slicing Failed, don't know why. Suddenly stopped working with 5.6 and 5.7 didnt fix it

### ISSUE THREAD

**Issue by mortyfire** [Ultimaker/Cura#18856]
### Cura Version

5.7.0

### Operating System

Win 11 Home

### Printer

Anycubic Mega X

### Describe your model

its watertight, meshfix does nothing, I have sliced this successfully before

### Add your .zip here ⬇️

[Body13.zip](https://github.com/Ultimaker/Cura/files/14921107/Body13.zip)

**Comment by HellAholic** [comment]
@mortyfire if it suddenly stopped working please go through the changes you made before/after.
Any sort of project files that you've opened recently or profiles that you've imported.

If you don't have any custom settings/profiles, then I recommend clearing the configuration folder and checking to see if you can add the same printer and slice again.
Model you included slices with tree support and normal support in 5.7.0

This is more of a discussion and request for help imo rather than a bug.
