### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by Krizlon** [Ultimaker/Cura#18865]
### Cura Version

5.6

### Operating System

Windows 11

### Printer

Every

### Reproduction steps

the application freezes for no reason and keeps throwing it out of the application.

### Actual results

BUG

### Expected results

BUG

### Add your .zip and screenshots here ⬇️

.

**Comment by HellAholic** [comment]
This repository is for topics related to the application Cura, while a frozen application would qualify as a topic, this seems to be more of an IT issue with your device rather than something we can tackle in the application based on the information you've provided.

If you do not have the decline to provide clear information, we cannot provide any help.
I am closing this issue since the Expected results is matching the Actual results, and yes that is sarcasm.
