### ISSUE TITLE
Missing pyDulcificum when I added the makerbotwriter plugin

### ISSUE THREAD

**Issue by charely6** [Ultimaker/Cura#18904]
### Cura Version

5.2

### Operating System

Windows 10

### Printer

Marketbot replicator+

### Reproduction steps

Copy the makerbotwriter folder from plugins folder here in the repo into the plugins folder for my cura install.

Restart cura

### Actual results

Get message saying it didn't load correctly would you like to remove it.

Checked the cura.log and found an entry saying it was missing pyDulcificum

### Expected results

Cura not throw an error message and when adding makerbot replicator+ as a printer be able to export a makerbot file

### Add your .zip and screenshots here ⬇️

None

**Comment by HellAholic** [comment]
Hey @charely6 ,
the makerbot writer plugin currently only supports Method X and Method XL so I do not know what the effect/result would be for the replicator+ since this is not tested nor intended use by Cura.
Outside of that, you're trying to copy modules developed based on dependencies that are not present in the 5.2 version, hence the error.
