### ISSUE TITLE
slicing failed on articulated baby basilisc link here https://www.thingiverse.com/thing:6524052

### ISSUE THREAD

**Issue by Psybr0** [Ultimaker/Cura#18911]
### Cura Version

5.6.0

### Operating System

windows 11

### Printer

neptune 4 pro

### Name abnormal settings

none

### Describe model location

center

### Describe your model

snake basilisk

### Add your .zip here ⬇️

https://www.thingiverse.com/thing:6524052

**Comment by GregValiant** [comment]
Thanks for the report.
I didn't have any trouble slicing this in Cura 5.7.0.  A lot of the slicing errors that occur with 5.6 were fixed in the new version.
I suggest you install 5.7 (you don't have to uninstall 5.6 if you don't want to).
I'll mark this as a duplicate and go ahead and close it.  I hope you understand.

Cura Mesh Tools says that model is water-tight but it has a lot of other errors.  It also has 2,000,000 surfaces.  The eyes in particular are an extremely dense mesh and there is no way that an FDM printer can keep up with that sort of resolution.
Here you can see that the mesh in the area around the eye is so dense it's almost black.  Each surface is 0.02mm on a side.
![image](https://github.com/Ultimaker/Cura/assets/64202104/2babd294-828e-46f2-8984-f5845d10210d)

This is a 16+ hour print at 75mm/sec.
![image](https://github.com/Ultimaker/Cura/assets/64202104/795fceeb-622c-4a3b-9ae7-4b1d8e8804d0)
