### ISSUE TITLE
Cura2.6 Beta - Fan speed not set correctly

### ISSUE THREAD

**Issue by jaybaugh** [Ultimaker/Cura#1892]
Fan speed always set to 50% speed.

Look at gCode, notice LAYER:0 speed set to 50%.
;LAYER:0
M106 S127.5

Steps to replicate:
Set "Initial Fan Speed" to 25
Set "Fan Speed" to 100
Set "Regular Fan Speed at Layer" to 2

Notice the gcode is missing any other fan speed. No fan speed is set for layer 2.

No other fan speed is set until the ending gcode.

**Comment by Ghostkeeper** [comment]
Not seeing this. I did exactly as you said, using an UM2E+ and a small-ish model. It produced this:

    ;LAYER:0
    M106 S63.8

Note that `255 * 0.25 == 63.75`, so this seems to be correct.

Then it also produces this:

    ;LAYER:1
    M106 S255

While it says `;LAYER:1`, this is because the layer numbers in the g-code count from 0 instead of 1, and Cura prefers to show layer numbers counting from 1 to the user.

**Comment by jaybaugh** [comment]
Since you were not able to replicate this, I tried clearing my existing profiles and settings and tried this again and was not able to replicate it. So this is closed.
