### ISSUE TITLE
Elegoo Cura 5.6.0 Slicing failed

### ISSUE THREAD

**Issue by zanyzella** [Ultimaker/Cura#18948]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Elegoo Neptune 4 Pro

### Name abnormal settings

There are no abnormal settings

### Describe model location

Is in the centre of the buildplate

### Describe your model

It is the top of a Lithophane light box

### Add your .zip here ⬇️

[GOTHIC_LITO_TOP.zip](https://github.com/Ultimaker/Cura/files/15092768/GOTHIC_LITO_TOP.zip)

I have had this problem with slicing things, many times with Elegoo Cura 5.6.0. Haven't a clue why though. Usually if i alter the settings or move the item on the buildplate it then slices fine.

**Comment by GregValiant** [comment]
Thanks for the report.
5.6.0 struggled with models that devolve into numerous "islands".  The problem was worked on and 5.7.0 doesn't show anywhere near the number of problems that 5.6 had.
Install Cura [5.7.0](https://github.com/Ultimaker/Cura/releases/tag/5.7.0) and see if it fixes the problem.  I didn't have any trouble slicing the model in 5.7.0.
I'll mark this as a duplicate report and go ahead and close it.  I hope you understand.

This is in 5.7.0.
![image](https://github.com/Ultimaker/Cura/assets/64202104/28921e7a-4b8a-4a06-89bf-c701e9587f07)
