### ISSUE TITLE
Short slice failed

### ISSUE THREAD

**Issue by Jeff705** [Ultimaker/Cura#18965]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Taz Workhorse

### Describe your model

New model, not sliced before

### Add your .zip here ⬇️

[CFFFP_Hero of the Federation - Sizing Slice - Head Opening.zip](https://github.com/Ultimaker/Cura/files/15134812/CFFFP_Hero.of.the.Federation.-.Sizing.Slice.-.Head.Opening.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
A lot of the "Won't slice" errors have been fixed in 5.7.0 and further work was done for 5.7.1 which was released last week.  I suggest you install 5.7.1 and see if the problem has been fixed.

I'll mark this as a duplicate and go ahead and close it.
This is in 5.7.1
![image](https://github.com/Ultimaker/Cura/assets/64202104/6e6e58d9-f6bc-4d4f-a09d-4dbb15259369)
