### ISSUE TITLE
Error al cortar

### ISSUE THREAD

**Issue by Leirbag777** [Ultimaker/Cura#18973]
### Cura Version

5.6

### Operating System

Windows 10 home

### Printer

creality ender 3

### Describe your model

Logré cortarlo antes

### Add your .zip here ⬇️

No me deja segmentar ningún archivo

**Comment by HellAholic** [comment]
@Leirbag777 There is a step by step description how to make a project file in the slicing fail report. Please follow the instructions and at the very least include a project file of a model that you cannot slice.
Your issue is local to your computer, settings you've changed, plugins installed, etc.
If you cannot share a project file, the quickest fix would be to remove all the configurations and start fresh:
- In the %appdata%\Roaming\cura\
This will remove all your printer definitions, profiles, plugins, etc.
