### ISSUE TITLE
3DBenchy.stl スライス結果が？

### ISSUE THREAD

**Issue by KouMRT** [Ultimaker/Cura#18975]
### Cura Version

4.8.0   5.7.0

### Operating System

windows11

### Printer

X5SA 

### Reproduction steps

3DBenchy.stl をDraft 0.2mmでスライス　

### Actual results

天井が逆ピラミッド状になり、船底の文字が消える

### Expected results

スライス結果が変

### Add your .zip and screenshots here ⬇️

![スクリーンショット 2024-04-28 135622](https://github.com/Ultimaker/Cura/assets/168323381/296c54dd-a612-44a4-b34d-8f2666cb601f)

**Comment by HellAholic** [comment]
@KouMRT Please include a project file, the issue is most likely from the settings you have selected/modified on your printer. 
Image below is from X5SA sliced with 0.2mm Normal quality (printer does not have a 0.2mm Draft quality)
![image](https://github.com/Ultimaker/Cura/assets/28710690/09f48cd2-1f4f-4a27-a61a-ef694b9f52ce)

**Comment by GregValiant** [comment]
@KouMRT - see if "Experimental / Make Overhang Printable" is enabled.  It is a seldom used option that will add chamfers to overhangs to "make them printable".
