### ISSUE TITLE
Pointless slicing with brim bed adhesion options

### ISSUE THREAD

**Issue by JHale716** [Ultimaker/Cura#18974]
### Cura Version

5.50

### Operating System

Mac OS Sonoma 14.4.1

### Printer

Creality Ender 3 Pro

### Reproduction steps

Select bed adhesion brim, slice

Typically using PETg and ABS type filaments that are poor in the bed adhesion department.

### Actual results

The brim is printed, and then the slicer has the printer start printing in the object's centre. You select brim as the bed adhesion option because adhesion is a problem, and then it tries to print the smallest things without the support of the brim! 

And unsurprisingly the print fails.

### Expected results

When selecting brim as the bed adhesion option, the brim is printed first as it is (nice and large & stuck), and then the printer works from the brim into the centre of the object.

### Add your .zip and screenshots here ⬇️

Change the way the slicer lays down the first layer when you know that adhesion is a problem with the print setting being brim. Where you have no bed adhesion on, or it's skirt, then start int he middle it's prettier, but when you have bed adhesion flagged as an issue pretty is a long way down the list against the print failing.

**Comment by GregValiant** [comment]
Thanks for the report.
The print order is:

1. Bed Adhesion
2. Support
3. Support-Interface
4. After those the order is dependent on your settings like "Wall Ordering" and maybe "Infill before Walls".

If you are having problems with the initial layer not sticking then it sounds like you have other problems.  Warping doesn't occur on initial layers as the bed temperature should be close to the glass temperature of the material (the material is soft enough not to shrink).
If you feel that a different "order" would be better for the Initial Layer then a "Feature Request" wherein you describe what you feel the order should be might be better.  At some point, and depending on the model geometry and what is on the first layer, you are going to have islands printed.

I'm going to remove the bug label from this and close it as the order you are getting is the expected behavior.  If you feel that is premature let me know.

This is a 3dbenchy with a Brim.  The lettering on the bottom prints before the hull is attached to the brim.  
![image](https://github.com/Ultimaker/Cura/assets/64202104/b3c8540f-287a-4c1b-b858-bf5314beb2dc)
