### ISSUE TITLE
Christmas Village, Slicing Failed

### ISSUE THREAD

**Issue by HertleinE** [Ultimaker/Cura#18995]
### Cura Version

5.5.0

### Operating System

Windows10

### Printer

Sovol01

### Name abnormal settings

Nothing

### Describe your model

Yes

### Add your .zip here ⬇️

Need help
[ChristmasTown.zip](https://github.com/Ultimaker/Cura/files/15180161/ChristmasTown.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
That model has showed up here numerous times.
Cura 5.5 and 5.6 really struggled when trying to slice certain shapes, and "organic" shapes were among the ones they struggled with.

Install [Cura 5.7.1](https://github.com/Ultimaker/Cura/releases) and see if the problem goes away.  5.7.0 and 5.7.1 are a lot better and the slicing errors have fallen down to almost none.

I'll mark this as a duplicate and since that problem was worked on and appears to be fixed, I'll go ahead and close this.  I hope you understand.
This is in 5.7.1.
![image](https://github.com/Ultimaker/Cura/assets/64202104/eb1e2e88-f4b3-4ccd-a4cb-80e7b4220340)

**Comment by HertleinE** [comment]
Thanks for Information
