### ISSUE TITLE
15.06.2: Combing moves crossing Perimeters

### ISSUE THREAD

**Issue by CCS86** [Ultimaker/Cura#190]
Hi guys, I love Cura's ability to avoid retracts with combing moves, but noticed tonight that some of them are treading right on / crossing external perimeters. This is definitely affecting the surface quality:

![image](https://cloud.githubusercontent.com/assets/12439543/8897181/006552f2-33d6-11e5-99ed-f9b4aeb02936.png)

**Comment by nallath** [comment]
@BagelOrb This sounds like an engine issue.

**Comment by BagelOrb** [comment]
Can you provide me with an stl which suffers from such problems under standard settings?

It's hard for me to see from your screen shot what is wrong here. Are the infill lines I am seeing on the top layer? Are you printing a cylinder with 5 outer walls and no infill, or a hollow cylinder?

Perhaps the gcode viewer of the old Cura is better.

Please provide with with an STL.

**Comment by CCS86** [comment]
This is a part set to 3 perimeter shells, so in this section, we are seeing 6 shells. It is a hollow cylinder, so the inner and outer shell are outer surfaces.

It might be a little more clear in this picture:

![image](https://cloud.githubusercontent.com/assets/12439543/8907789/e4479932-343d-11e5-8d2b-432c46338040.png)

**Comment by CCS86** [comment]
Here is the STL file: https://dl.dropboxusercontent.com/u/60958586/Body.stl

**Comment by BagelOrb** [comment]
I can see clearly now the view is closer. 

It seems the distance by which to stay within the perimeters of the current part is not configurable, while it should be.

This should be easily fixed, but because a new settings needs to be translated in all languages you should would have to wait a couple of months.

**Comment by CCS86** [comment]
Thanks bagel, glad I could help. Hope we see it soon.

**Comment by BagelOrb** [comment]
Looking at it again it looks like it's not crossing the boundary, but it's getting really close to the edge. This is also what I see when I look at the gcode produced by 15.06.

Instead of making it configurable, I've made it default that the combing boundary is on the second perimeter. This saves the time of making an extra offset, which would be the case when the distance would be configurable.

During combing, the nozzle now stays around the second perimeter.

**Comment by CCS86** [comment]
Cool, thanks!
