### ISSUE TITLE
Bad slicing result, unexpected gaps

### ISSUE THREAD

**Issue by stefanino-ch** [Ultimaker/Cura#19002]
### Cura Version

5.7.0

### Operating System

Windows 11

### Printer

Sovol SV04

### Reproduction steps

Add part to cura. 
Part files are attached. 

Slice it. 

### Actual results

Result in v5.4
![slicing-v5_4](https://github.com/Ultimaker/Cura/assets/56797041/52bfcedb-a305-4b73-88e4-5284b6e5a9eb)

Result in v5.7
![slicing-v5_7](https://github.com/Ultimaker/Cura/assets/56797041/7cef36b4-0b80-471e-86bf-f75e22b6ef9e)

Happens with .stl and with .3mf file. 
The .stl file I have checked with Blender, perfect display, no errors in model reported. 

I have not even tried to print, as the gaps displayed are so big. 

### Expected results

At least the same result as in previous versions. 

### Add your .zip and screenshots here ⬇️

Part files
[gear-wheel-big.zip](https://github.com/Ultimaker/Cura/files/15189675/gear-wheel-big.zip)

Universal project file
[UCP_gear-wheel-big.zip](https://github.com/Ultimaker/Cura/files/15189704/UCP_gear-wheel-big.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
Neither 3mf file opened as a project for me, but what I see in your image is exactly the preview to expect when "Coasting" is enabled.
The preview only shows moves with extrusions.  Because "Coasting" moves aren't extrusion moves, they aren't shown and so you see the characteristic gap.  The nozzle moves across as if it was still an extrusion, but the extruder doesn't turn and the pressure within the nozzle is allowed to bleed off.

I'll go ahead and remove the bug label and close this.  Let me know if you feel that is premature.

**Comment by stefanino-ch** [comment]
Hey Greg
You're right. I've disabled coasting and get the expected result. 
![no-coasting](https://github.com/Ultimaker/Cura/assets/56797041/da71f2da-4f00-4756-b597-3548d3e6bda1)

PIBCAK: Problem Is Between Chair And Keyboard. :-(

Thank you for your support.

**Comment by GregValiant** [comment]
Coasting works as it should.  Just remember that the preview will look a little odd.
