### ISSUE TITLE
The workpiece is brittle, but the settings are correct.

### ISSUE THREAD

**Issue by TonHuijs** [Ultimaker/Cura#19006]
### Cura Version

5.7.1

### Operating System

Windows 10

### Printer

Ultimaker S5

### Reproduction steps

after updating from cura 5.0.0. to 5.7.1 Beta to 5.7.1
5.7.1 Beta was ok. printed mass of products .
After updating to 5.7.1 the products aren't fulfilled.
Settings are 100% filling
Tried several changes in settings but not becoming better results.
Strange : the BCN3D printer has the same behavior.
So not a nozzle problem.

### Actual results

outsite wall loses from product.
Strange : the BCN3D printer has the same behavior.
So not a nozzle problem!!
So Ultimaker and BCN3D printer same result.
Companion has also this problem on other BCN3D

### Expected results

Full filled product.

### Add your .zip and screenshots here ⬇️

[UMS5_wagenplaat 2024-02-05.zip](https://github.com/Ultimaker/Cura/files/15193777/UMS5_wagenplaat.2024-02-05.zip)
![20240502_224743](https://github.com/Ultimaker/Cura/assets/76877589/416e2b69-924f-4244-8bca-2f3365c859c2)

**Comment by GregValiant** [comment]
Thanks for the report.
I'm not bad with a lot of the printers, but UM printers are different and you will need a UM person to respond to this.  Have you posted this over on the [UM Forum](https://community.ultimaker.com/discover/)?  The "inner-walls detaching" problem may be related to the filament (excessive shrinkage) or the printing temperature,  I've certainly seen this problem before.  I have not experienced this with my own projects (on a Creality machine) and I've been using 5.7.0 and now 5.7.1 since they were released.

I sliced your project.  Reading the gcode into Excel - the lower flat (in that image) shows that the line widths are all 0.41.  That's right on the money for a 0.40 line width at 102% flow.
So it doesn't look like the problem is in the gcode.  I know you are having the problem on multiple printers - are you using filament from the same manufacturer's batch on all of them?
