### ISSUE TITLE
Strange Slicer decisions leads to inefficient moves..

### ISSUE THREAD

**Issue by ArcAIN6** [Ultimaker/Cura#19044]
### Cura Version

5.5.0

### Operating System

Windows 10

### Printer

Anet ET4X

### Reproduction steps

Loaded model
Sliced

### Actual results

Once sliced, i previewed the print in cura, because when printing, there are quite a few superfluous movements, where the printhead jumps around, doesn't print anything, then resumes printing like nothing ever happened.

Video of behavior has been added at the end, can confirm this happens in print as well (which is why i re-sliced it to make this video)
Project File has been zipped and added at the end

### Expected results

One would expect the slicer to try to minimize the amount of travel between printing. Even if any sort of "avoid" setting is in effect, completely routing around several potential avoid locations isn't streamlined, when faster, shorter routs are available. 

### Add your .zip and screenshots here ⬇️

https://github.com/Ultimaker/Cura/assets/418929/22734568-53d3-4e79-b983-af860e0dcdd5
[Truss_Issues.zip](https://github.com/Ultimaker/Cura/files/15250362/Truss_Issues.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
I sliced your project with 5.5.0 and I get the same movement.  Slicing it with 5.7.1 there is no problem.
So I would suggest you upgrade to 5.7.1.  In addition to this problem being fixed It's much better in regards to slicing time and the number of slicing crashes is down dramatically.

I'll go ahead and close this as it appears to be fixed in the current version of Cura.
