### ISSUE TITLE
[5.7.0] unusual speeds

### ISSUE THREAD

**Issue by Dumpflam** [Ultimaker/Cura#19052]
### Cura Version

5.7.0

### Operating System

Windows 10

### Printer

Ender-3 S1 PRO

### Reproduction steps

[Blind-Spot mirror attachment - Kopya.md](https://github.com/Ultimaker/Cura/files/15278460/Blind-Spot.mirror.attachment.-.Kopya.md)

!!!CHANGE .md TO .stl!!!
[profile.md](https://github.com/Ultimaker/Cura/files/15278475/profile.md)
!!!CHANGE .md TO .curaprofile!!!

hi when slicing this model with these settings the speed stays at 13mm after the short pillar is printed. dunno why.

### Actual results

low speed for no reason.

### Expected results

normal speeds.

### Add your .zip and screenshots here ⬇️

![image](https://github.com/Ultimaker/Cura/assets/141259221/4ecd45cf-3528-4ac5-b6a0-20fc7f6d61cf)

**Comment by Dumpflam** [comment]
> Minimum layer time?

YUB!
do you think i should just make it 0 cuz i have a double 5015 fan setup?

**Comment by GregValiant** [comment]
The slow down occurs right where the print becomes a single "island" and the layer time is just about cut in half.
If you are confident in your layer cooling setup you can drop the minimum layer time.  It may need some experimentation.  Fortunately, it's a small print.

What is going on appears to be expected behavior rather than a bug.  I'll remove the bug label but I'll leave this open for a bit so you can respond.

**Comment by Dumpflam** [comment]
Thank you! Very informative. I think ill lower it a bit. Alright, cya!

12 May 2024 Pzr 05:15 tarihinde GregValiant ***@***.***> şunu
yazdı:

**Comment by GregValiant** [comment]
I'll close this then.  Good luck.
