### ISSUE TITLE
Brims being added, even though "none" is selected

### ISSUE THREAD

**Issue by ArcAIN6** [Ultimaker/Cura#19064]
### Cura Version

5.5.0 - 5.7.1

### Operating System

Windows 10

### Printer

Anet ET4X

### Reproduction steps

Import model, slice.

### Actual results

notice that for some reason cura is adding brims, even though "none" is selected. 

### Expected results

one would expect there to be NO brims at all when selecting "none", or "Skirt" or literally anything OTHER than brims. 

### Add your .zip and screenshots here ⬇️

![image](https://github.com/Ultimaker/Cura/assets/418929/6c197a27-587b-483c-8c37-8d53f51306a3)
![image](https://github.com/Ultimaker/Cura/assets/418929/063f7b1a-b076-4cf8-bd41-8c6f83793163)
[Odd_Brims.zip](https://github.com/Ultimaker/Cura/files/15285289/Odd_Brims.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
That isn't a brim.  It is a support structure being generated for the 45° chamfer on the bottom of those flat models.

This is in 5.7.1 with "Support Overhang Angle" at 40° (which is less than the angle of the chamfer) and the "Support Horizontal Expansion" at 0.8.
![image](https://github.com/Ultimaker/Cura/assets/64202104/8bc7ae80-a808-4f5e-9683-4cf50f8d082c)

This is your project in 5.5.0.
![image](https://github.com/Ultimaker/Cura/assets/64202104/e581bb60-17d6-46c7-ab59-029fb4d4aff7)

In both versions - changing either the "Support Overhang Angle" to 50° (greater than the chamfer angle and less than the approximate max of 63°) or the "Support Horizontal Expansion" to 0.0 will cause that first layer support structure to go away.

This happens to be in 5.7.1 with Support Horizontal Expansion at 0, and 5.5.0 reacts the same way.
![image](https://github.com/Ultimaker/Cura/assets/64202104/b3b94747-21c4-4886-90b1-b7559b1cc955)

So this is a settings issue rather than a bug.  I'll remove the bug label and go ahead and close this.  I hope you understand.

**Comment by ArcAIN6** [comment]
Thanks, i was really losing my mind trying to figure why it was printing those
