### ISSUE TITLE
Slicing Failed with an unexpected error

### ISSUE THREAD

**Issue by getglenn** [Ultimaker/Cura#19071]
### Cura Version

5.6.0

### Operating System

Linux Mint 21.3

### Printer

Creality Ender 3 V3 SE

### Reproduction steps

1. imported .stl
2. duplicated it x3
3. tried to slice

### Actual results

**Slicing failed** Slicing failed with an unexpected error

### Expected results

the model should have been sliced in preparation for saving to print
![SlicingFailed](https://github.com/Ultimaker/Cura/assets/46698756/e0a3411b-68f7-4d2d-9ba7-85bef9b11dc9)

### Add your .zip and screenshots here ⬇️

I am using an AppImage of Cura and I cannot find the log using the above location or the Help setting folder
regards Glenn O

**Comment by GregValiant** [comment]
Thanks for the report.
Cura 5.5 and 5.6 suffered from these slicing failures.  The problem seems to be solved in 5.7.0 and now 5.7.1.
I suggest you move to Cura 5.7.1 and see if the problem goes away.

I'll mark this as a duplicate and go ahead and close this as the problem appears to have been fixed.
