### ISSUE TITLE
Optimize Wall Printing Order forgets outer walls for holes

### ISSUE THREAD

**Issue by Block137** [Ultimaker/Cura#19085]
### Cura Version

5.7.1

### Operating System

Windows 11

### Printer

Custom

### Reproduction steps

1. Slice models with internal geometries
2. Enable Optimize Wall Printing Order
3. Slice

### Actual results

(Wall Ordering set to Inside to Outside)
G-code prints inner walls (green) but skip outer wall before moving to inner walls of other holes, then comes back to print outer wall (red) of each geometry individually.

Works properly for non-hole geometries.

Possibly related to #19056

### Expected results

Prints inner walls and outer wall of the same geometry in 1 go

### Add your .zip and screenshots here ⬇️

[OptmzWallOrdr.zip](https://github.com/Ultimaker/Cura/files/15339681/OptmzWallOrdr.zip)
![Screenshot 2024-05-17 014124](https://github.com/Ultimaker/Cura/assets/23495338/27aad991-db81-45e8-ad00-e54f6219cd04)
![Screenshot 2024-05-17 014809](https://github.com/Ultimaker/Cura/assets/23495338/1d67bee5-4980-44b0-809f-c6322837ccf9)

**Comment by GregValiant** [comment]
Thanks for the report.
I get the same results as you in that project.
Go to "Experimental" settings and disable "Group Outer Walls".  It looks to me like I'm getting the ordering you want with that setting disabled and Optimize Wall Printing Order enabled.

That was the only change I made and you can see below that each hole is completing before the print head moves on to another.
Let us know if it works for you.
![image](https://github.com/Ultimaker/Cura/assets/64202104/de733a1a-1ca7-4509-ab2a-a8b197c90774)

**Comment by Block137** [comment]
Looks like Group Outer Walls is the cause.
That said, the actual bug is that Group Outer Walls doesn't work with non-hole walls? (screenshot2)
Also why was it decided to be enabled by default?

**Comment by GregValiant** [comment]
_"That said, the actual bug is that Group Outer Walls doesn't work with non-hole walls?"_
Sure it does.
Look at the image below and you will see that the preview slider isn't at the end of the layer.
![Untitled](https://github.com/Ultimaker/Cura/assets/64202104/cf12b798-5b76-447a-93cf-72249360ae66)

When I slice the file with "Group Outer Walls" disabled it looks like exactly what you wanted and that final outer wall is in place.
This appears to be a settings issue so I'll go ahead and remove the bug label and close this.  Let me know if you feel that is premature.
