### ISSUE TITLE
[BUG] [5.7.1] Artefact on horizontal surface

### ISSUE THREAD

**Issue by yet-another-average-joe** [Ultimaker/Cura#19091]
### Cura Version

5.7.1

### Operating System

Windows 10

### Printer

Voron 2.4

### Reproduction steps

Slice the provided STL

### Actual results

Cura 5.7.1 produces a artefact ; see images
Cura 5.7.0 and Orca don't

Appears with 0.2 mm layer height ; Cura 5.7.1 behaves as expected with 0.16 and 0.24 

### Expected results

a smooth horizontal plane

### Add your .zip and screenshots here ⬇️

![Cura Bug 1](https://github.com/Ultimaker/Cura/assets/43514870/00ea376a-7056-43c3-939a-9cf6110d5753)

![Cura Bug 2](https://github.com/Ultimaker/Cura/assets/43514870/0e0001a7-736e-45a2-8a15-9258d945a81f)

![Cura Bug 3](https://github.com/Ultimaker/Cura/assets/43514870/60cd2546-849c-49f4-96d5-948cc3939238)

[Pièce1 v6.zip](https://github.com/Ultimaker/Cura/files/15349275/Piece1.v6.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
I've seen that before and it's always been because of a slight angle on a surface, or the model isn't quite flat on the build plate.
I sliced that project file and cannot duplicate the problem.
I checked the model using MS3D Builder and the model looks good and that surface does look planar-parallel to the base surface.
The image below is at the project layer height of 0.20.  I also sliced it with layer heights of 0.30 down to 0.05 and couldn't duplicate the problem.
I see in the preview that Cura is putting an outer wall and the correct count of inner walls around that triangle.  Somehow Cura is seeing that triangle as being taller than the rest of that surface.  Since the surface looks good my best guess is that somehow a very small angle was introduced into the Cura setup causing that aberration.  I'm confident there is no problem with the model itself.
![image](https://github.com/Ultimaker/Cura/assets/64202104/7aea0639-5571-4d75-ac25-406c015307cd)

The Cura team will take a look.

**Comment by yet-another-average-joe** [comment]
Really weird. Now unable to reproduce the issue.
Been thinking of some rounding errors piling up after rotating the model in various positions before repositioning it : nada !
Weirdest thing is it appeared only there. Given the length of the model (355 mm), we could expect such artefacts at others places if it was at an angle, or amplifying it with tinier layer heights.
Even weirder : just opened the attached project file : nothing !

Apart from this tiny artefact, the part came out just perfect.

Closing the bug report.

**Comment by GregValiant** [comment]
I tried to duplicate this by starting out with the model as it would be when you imported it.  I flipped it all over and then tried angles as low as 0.08° I couldn't get only that corner to show.

If this comes up again let us know and this can be re-opened.  I'll leave the bug label on this but go ahead and close it.

**Comment by OsmosisD** [comment]
Happening to me too, in 5.7.2. Seems to be some sort of weird rounding error. May be hard to pin down. Only happens extremely close to 60% scale at 0.12mm layer height with a 3DBenchy.

![image](https://github.com/user-attachments/assets/5d29472d-1991-4554-94d0-b13604781e99)

Weirdly, I was printing this model with the same version, scale, and layer height a few weeks ago and this wasn't happening. Tested slicing with the stock profile and printer settings and it's still doing it, also for 0.2mm layer height too now. I'll just scale to 59.999% for my prints to fix it, but still weird. One of those things maybe?

[CCR100_3DBenchy.zip](https://github.com/user-attachments/files/16190154/CCR100_3DBenchy.zip) if anyone wants to take a look.
