### ISSUE TITLE
 cura stopped detecting my creality cr-10s (non-pro) printer through usb

### ISSUE THREAD

**Issue by 1043613lcpsorg** [Ultimaker/Cura#19148]
### Cura Version

5.7.1

### Operating System

Windows 11

### Printer

Creality 3d CR-10s

### Reproduction steps

plug it in

### Actual results

cura stopped detecting my creality cr-10s (non-pro) printer through usb after i took my laptop downstairs then brought it back and plugged it in and it stopped detecting it.

### Expected results

dosent work

### Add your .zip and screenshots here ⬇️

![Screenshot 2024-05-27 183132](https://github.com/Ultimaker/Cura/assets/153699099/6a5c689c-52eb-4f44-b65b-ee611be5d338)

**Comment by GregValiant** [comment]
The "USB Printing" plugin is a legacy feature included with Cura because older UltiMaker printers must use it.  For other machines - USB Printing has a variety of problems and is not recommended for printing.

Occasionally, Windows will assign the Serial Port Driver to a specific USB port (rather than allowing it be be available to all USB ports).  Have you plugged the printer into the same port that you used before moving the computer?
