### ISSUE TITLE
Error slicing with tree supports

### ISSUE THREAD

**Issue by lobero21** [Ultimaker/Cura#19168]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Geeetech I3ProW

### Describe your model

I have this problem with all model

### Add your .zip here ⬇️

I have now this problem with this model
[Cabel_Holder.zip](https://github.com/user-attachments/files/15516641/Cabel_Holder.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
We ask for project files so we can see how you have Cura set up, your printer, the material, and the model placed.
I didn't have any trouble slicing this in either 5.6.0 or 5.7.1.

Cura 5.7.1 is out and many of the slicing failures that occurred with 5.6.0 have been fixed.  I advise to upgrading to Cura 5.7.1.

I'll mark this as a duplicate report and go ahead and close this as slicing problems were very apparent in 5.6.0 and they seem to be fixed in 5.7.1.
