### ISSUE TITLE
Printsettings on extruder 1 get over written by extruder 2.

### ISSUE THREAD

**Issue by LStapp** [Ultimaker/Cura#19166]
### Cura Version

5.6.0

### Operating System

Windows 10

### Printer

Ultimaker 3

### Reproduction steps

1. Set extruder 1 to PLA
2. Set extruder 2 to PC
3. Slice a model using extruder 1

### Actual results

1. Print model, print fails
2. Check Gcode, see that temperatures are to high (inc. buildplate) matching un used PC

**3. Problem is solved when setting both extruders to PLA.**

### Expected results

1. Correct temperatures and succesfull print

### Add your .zip and screenshots here ⬇️

[PLA PC problem.zip](https://github.com/Ultimaker/Cura/files/15503785/PLA.PC.problem.zip)

Added both the PLA and PC senario (printing model in PLA) and PLA PLA.
Senario PLA and PC has wrong temperatures in Gcode.

Thanks in advance.

**Comment by GregValiant** [comment]
Thanks for the report.
Use the "File | Save Project" command and zip the 3mf file and post the zip folder here.  We will need to see how you have the printer and Cura set up.

Both extruders are active throughout the "PC PLA" file and there are ~562 tool changes.  This is not a "print with extruder 1" gcode file and in fact it starts out with Extruder 2 as the active tool.  The support is all from Extruder 2.
Tracking the temperature changes throughout the gcode; each tool is printing at the correct temperature.

There is only one bed temperature.  It will be the highest bed temperature of all active extruders.  Since Extruder 2 is in use throughout the print, and PC has the highest bed temperature, that's the temperature used and the bed is at 107.

When you sliced the model did you disable Extruder 2 and set the "Bed Adhesion Extruder" to Extruder 1 and the "Support Extruder" to Extruder 1?  That's what I'll look for in the project file.
