### ISSUE TITLE
project wouldnt slice

### ISSUE THREAD

**Issue by mikthemadman000** [Ultimaker/Cura#19171]
### Cura Version

5.6.0

### Operating System

windows 11

### Printer

custom FFF printer (Ender 3)

### Name abnormal settings

no

### Describe model location

no

### Describe your model

the model is an articulated dragon

### Add your .zip here ⬇️

[articulated-dragon-model_files.zip](https://github.com/user-attachments/files/15519764/articulated-dragon-model_files.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
When a model is made up of numerous copies of the same part, and that part has errors in it, you end up with a LOT of errors in the assembled model.
Cura 5.6.0 did have trouble with some organic shapes and moving up the 5.7.1 is a good idea.  This particular model needs repair or I wouldn't trust the slice.  I did get it to slice in 5.7.1 despite the errors.
Go to the Cura MarketPlace and load the Mesh Tools plugin.  It will show a warning when you import models that have extra surfaces or inverted surfaces.
![image](https://github.com/Ultimaker/Cura/assets/64202104/27253014-5ef5-4293-b0e1-251fcca4f4c7)

I'll mark this as a duplicate report as this was a well known bug in 5.5.0 and 5.6.0.  I'll close this as the bug seems to have been fixed in the later versions.
