### ISSUE TITLE
SLICING FAILED POST SCALING

### ISSUE THREAD

**Issue by CurtisDay77** [Ultimaker/Cura#19202]
### Cura Version

5.6.0

### Operating System

macOS Monterey 12.7.2

### Printer

CREALITY CR10

### Name abnormal settings

No abnormal settings in my opinion

### Describe model location

Model is exactly where CURA imported it to

### Describe your model

The model is a simple female sculpture that sliced perfectly at original size. Then again scaled up to 100mm on the Z using uniform scaling. Then again up to 150mm & 200mm. Then failed scaling it up to 250mm & 300mm

### Add your .zip here ⬇️

<img width="2048" alt="Screen Shot 2024-06-08 at 9 17 05 am" src="https://github.com/Ultimaker/Cura/assets/165210584/98ebf2fa-c854-47af-a445-f15f03942efd">

**Comment by GregValiant** [comment]
Thanks for the report.
5.5 and 5.6 had problems with certain "organically shaped" models.  5.7.0 and now 5.7.1 are greatly improved and I suggest you upgrade.
If there are any errors in a model, and you scale the model up, the errors scale up as well.  An open seam that might fall below the "noticeable" threshold at 100% might be above the threshold at 200%.  Make sure the model is error-free.

I'll go ahead and mark this as a duplicate as it was a known bug in previous versions.  I'll close this as it appears to have been fixed in more recent versions.  I hope you understand.
