### ISSUE TITLE
Screen tearing and crashing 

### ISSUE THREAD

**Issue by KennethMcNutt** [Ultimaker/Cura#19209]
### Cura Version

5.7.2

### Operating System

win 11

### Printer

X-one2

### Reproduction steps

I added  QIDi printer files into the share /cura folder of 5.7.2  I copied only the files that did not exist in the 5.7.2 folder already  the files came from the QIDI print app folders " Plugins and Resouces"  It works fine in Cura 5.6.0 but make 5.7.2 unstable 

### Actual results

![UltiMaker Cura 6_9_2024 6_00_08 PM](https://github.com/Ultimaker/Cura/assets/25518303/1f771f6c-0546-416f-8d0d-355c05683887)
![UltiMaker Cura 6_9_2024 6_00_42 PM](https://github.com/Ultimaker/Cura/assets/25518303/cede2c62-0238-4e6e-aa83-b5a81a9ef756)
![UltiMaker Cura 6_9_2024 6_02_00 PM](https://github.com/Ultimaker/Cura/assets/25518303/451a8e3f-044d-422f-b1a1-c0090d3bfcbb)
![XO_Groot_v1_1M_Merged - UltiMaker Cura 6_5_2024 8_19_04 PM](https://github.com/Ultimaker/Cura/assets/25518303/cd796b7c-1f64-4ad1-a103-07ce171850d0)

### Expected results

Printers and related info is added into Curas' data and functions accordingly (at least in previous versions of Cura)

### Add your .zip and screenshots here ⬇️

[cura.log](https://github.com/user-attachments/files/15755420/cura.log)

https://github.com/Ultimaker/Cura/assets/25518303/0c487604-8d62-4385-a5df-471906cdb478
![UltiMaker Cura 6_9_2024 6_00_42 PM](https://github.com/Ultimaker/Cura/assets/25518303/cabc851b-8408-4f75-b3b0-5d13f58fabfa)
![UltiMaker Cura 6_9_2024 6_02_00 PM](https://github.com/Ultimaker/Cura/assets/25518303/5800415e-8049-4203-a3df-b36e6e3210af)
![XO_Groot_v1_1M_Merged - UltiMaker Cura 6_5_2024 8_19_04 PM](https://github.com/Ultimaker/Cura/assets/25518303/28bc630a-f6d8-47a7-8609-3b1d99033648)
![UltiMaker Cura 6_9_2024 5_59_39 PM](https://github.com/Ultimaker/Cura/assets/25518303/0af8377a-15c0-4da0-bddc-298b51178d3a)
![UltiMaker Cura 6_9_2024 6_00_08 PM](https://github.com/Ultimaker/Cura/assets/25518303/e0aafafa-da5c-4d6f-b6c6-77721401e9a1)

[cura.log](https://github.com/user-attachments/files/15755422/cura.log)

both 5.7.2 l 5.6.0 logs are  are here along with some Miscellaneous capters of what have in 5.7.2 

I know the isn't something PPL normally do  But I would like to keeping using My QiDI printers in Cura 5.7.2 Thanks Ken

**Comment by GregValiant** [comment]
Thanks for the report.
If I understand, you are adding files to Cura that were written for another application in order to add your printers?  There is an article [HERE ](https://github.com/Ultimaker/Cura/wiki/Adding-new-machine-profiles-to-Cura) regarding adding machine profiles and support files.

I'll remove the bug label from this as it seems you are trying to patch in code from another app.  This simply isn't a Cura problem. 

I think you will need to go through all the files and check them to make sure they are compatible with the Cura Python and JSON standards.  If there are unsupported calls in the files (importing files that don't exist or that have different names) then there will be issues.  I'm surprised this worked in any fashion.
