### ISSUE TITLE
Slicing failed

### ISSUE THREAD

**Issue by mokind** [Ultimaker/Cura#19237]
### Cura Version

5.6.0

### Operating System

Windows 10

### Printer

Tronxy XY-2 Pro

### Name abnormal settings

see project file

### Describe model location

center

### Describe your model

Never successful

### Add your .zip here ⬇️

[TXY2PROPRO2EXY3SE_Rialto_Bridge_Venice_IEC3D.zip](https://github.com/user-attachments/files/15846479/TXY2PROPRO2EXY3SE_Rialto_Bridge_Venice_IEC3D.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
5.5 and 5.6 suffered from a lot of slicing problems.  I suggest you move up to 5.7.2.
![image](https://github.com/Ultimaker/Cura/assets/64202104/5d35ff8b-b87e-47e1-bd5d-2d88456cb7f2)

I'll mark this as a duplicate and close it as the problem was well known and appears to have been fixed.
