### ISSUE TITLE
velocidad limitada - ender 3 V3 SE

### ISSUE THREAD

**Issue by jeromarq** [Ultimaker/Cura#19297]
### Cura Version

5.7.1

### Operating System

Windows 11 / Mac os

### Printer

creality ender 3 V3 SE

### Reproduction steps

quiero imprimir una pieza de una sola pared, sin relleno y sin capa superior e inferior.
agregue la opcion "espiralizar el contorno exterior"

### Actual results

la velocidad maxima es muy baja, no llega a los niveles que permite la impresora. 
imprime mas lento que una ender 3 V2 

### Expected results

deberia imprimir minimo a 90mm/s y esta imprimiendo a 20mm/s aprox. 

![Screenshot_1](https://github.com/Ultimaker/Cura/assets/174021542/5598d446-e0c1-4020-9b90-e7caf396338a)

### Add your .zip and screenshots here ⬇️

![Screenshot_1](https://github.com/Ultimaker/Cura/assets/174021542/993a57a1-8560-440d-b38a-edb7d17e0fa2)

**Comment by GregValiant** [comment]
Thanks for the report.
You did not include a project file so I can't really investigate.  This is often a settings issue so I'll remove the bug label and close this.
Go to the "Cooling" settings.  You will find "Minimum Layer Time" and "Minimum Speed".  You can decrease the "Minimum Layer Time" and the speeds will no longer be calculated to provide the 10 second minimum.  You can increase the "Minimum Speed" as well.
Your layer cooling fan must be capable of rapidly cooling the extrusion or your print will be a mess.  That's why the setting is there in the Cooling section.

**Comment by jeromarq** [comment]
muchas gracias era eso!! desactive el "tiempo mínimo de capa" y ahora está
a la velocidad que necesitaba. muchas gracias !!
____________________
Arq. Jerónimo Marquez
1122524130
