### ISSUE TITLE
speed settings do not match real printing speeds.

### ISSUE THREAD

**Issue by packjosh24** [Ultimaker/Cura#19338]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Creality Ender-3 v2

### Reproduction steps

I am calibrating my machine after some time and i noticed the print speeds in the slice do not reflect real speed. I have the following settings for speed. 
Print speed, infill speed, and wall speed at "200 mm/s"
top/bottom speed"150 mm/s"
travel speed "300 mm/s"
initial layer speed "30 mm's"
all material flow is set to 100% except for initial layer flow is 90%. 

### Actual results

in reality, the bottom 4-5 layers are verry fast even the initial layer is about 200 mm/s. then after that, the infil and walls slow down to about 50 mm/s. 

### Expected results

The real print speed should match the settings i have set. Slow first few layers then fast printing the whole way up.

### Add your .zip and screenshots here ⬇️

[CE3E3V2_xyzCalibration_cube.zip](https://github.com/user-attachments/files/16119918/CE3E3V2_xyzCalibration_cube.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
The first 5 layers have bottom "skins" and so they take longer and the top 5 layers have "skins" and so they take longer.  Within the Infill area the Layer Time dramatically decreases.

Your "Minimum Layer Time" is 10 seconds and your "Minimum Speed" is 10mm/sec.  You are bumping up against those limits and so Cura is dropping the speeds so the "10 seconds/layer" limit is not exceeded.

I'll go ahead and remove the bug label and close this as it is expected behavior given your settings.
