### ISSUE TITLE
vertical printing

### ISSUE THREAD

**Issue by SamWiseLouis** [Ultimaker/Cura#19348]
### Cura Version

5.4.0

### Operating System

linux

### Printer

Elagoo Neptune 3 plus

### Reproduction steps

took a model part for a star wars interdictor and instead of printing flat turned it so it was vertical pointing so i would use less supports and such. IT may be the angle of the parts but i am unsure

### Actual results

Got an error slicing

### Expected results

it to print quicker with less filament

### Add your .zip and screenshots here ⬇️

![Screenshot from 2024-07-09 12-48-31](https://github.com/Ultimaker/Cura/assets/35609869/3340ae64-0a67-4a15-87c2-51181c3ca76d)

**Comment by GregValiant** [comment]
Thanks for the report.
If you look closely at the models in the Prepare screen you will see "polka-dot" patterns.  Cura uses that pattern to indicate surfaces that are configured incorrectly.  All three parts need repair.  Even if you got those models to slice when laying down you could not trust the slice.
Cura 5.7.1 is much improved over 5.5 and 5.6 so I suggest you upgrade.  5.7.2 is good but it requires a post processing patch because of a problem with it adding temperatures before the StartUp Gcode on ABL equipped machines.

I'm going to go ahead and remove the bug label and close this as it is a model problem and your Cura version is 6 releases behind.  I hope you understand.

**Comment by SamWiseLouis** [comment]
Thanks i missed that! Much appreciatedSent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: GregValiant ***@***.***> Date: 7/9/24  1:14 PM  (GMT-05:00) To: Ultimaker/Cura ***@***.***> Cc: SamWiseLouis ***@***.***>, Author ***@***.***> Subject: Re: [Ultimaker/Cura] vertical printing (Issue #19348) 
Thanks for the report.
If you look closely at the models in the Prepare screen you will see "polka-dot" patterns.  Cura uses that pattern to indicate surfaces that are configured incorrectly.  All three parts need repair.  Even if you got those models to slice when laying down you could not trust the slice.
Cura 5.7.1 is much improved over 5.5 and 5.6 so I suggest you upgrade.  5.7.2 is good but it requires a post processing patch because of a problem with it adding temperatures before the StartUp Gcode on ABL equipped machines.
I'm going to go ahead and remove the bug label and close this as it is a model problem and your Cura version is 6 releases behind.  I hope you understand.
