### ISSUE TITLE
Printer attempts to print in mid air

### ISSUE THREAD

**Issue by MJeffares** [Ultimaker/Cura#19410]
### Cura Version

5.4.0

### Operating System

Windows 10

### Printer

CR10

### Reproduction steps

1. Slice the model with less than 5 wall lines and due to the model geometry and settings the sliced model has extrusions in mid air during layer 5
2. Enable infill before walls and the result does not change (As it doesn't effect top/bottom layers)

### Actual results

The printer attempts to print mid air at the start of layer 5

### Expected results

The printer doesn't print in mid air

### Add your .zip and screenshots here ⬇️

[CCR10_Test_Lid_V3.zip](https://github.com/user-attachments/files/16322995/CCR10_Test_Lid_V3.zip)
![2024-07-21 15_33_58-Window](https://github.com/user-attachments/assets/7024aca2-e84b-413d-afe8-75ec6940e2f2)

**Comment by GregValiant** [comment]
Thanks for the report.
This is all about your settings.
Your support "XY distance" is 4.0mm.  The holes just aren't big enough for that and so no support is being generated.  In addition, your "Support Z Distance" is 0.56mm (2 layer heights) and that's usually too much for circular features.
This model doesn't have any areas that require "bridges" and you need to turn that off.

This is with "XY distance" at 0.40, "Support Top Distance" at 0.28, and the Top Interface Density at 60%.  This will work.
![image](https://github.com/user-attachments/assets/1b8fc2a1-dfcc-4a24-b6fa-f1f0a4e5de3c)

I'll remove the bug label since it is all about the settings.  I'll go ahead and close this as well as 5.4 is 6 versions behind.  I hope you understand.
