### ISSUE TITLE
Raft Extended over Build Plate

### ISSUE THREAD

**Issue by Medbrane** [Ultimaker/Cura#19436]
### Cura Version

5.7.0

### Operating System

macOS Sonoma

### Printer

Anet Et4

### Reproduction steps

I imported several larger models. I turned on the raft and tree support settings and kept all items within the boundary. I then sliced the model.

### Actual results

After slicing, I noticed some of the reacts generated beyond the build plate. At first I assumed it was just a visual glitch, but after loading the g-code onto my printer, it tried to print outside some boundaries of the build plate.

### Expected results

I would expect the raft to stop at the end of the build plate or at least not show up in the g-code when I go to print.

### Add your .zip and screenshots here ⬇️

<img width="1440" alt="Screenshot 2024-07-26 at 4 06 07 PM" src="https://github.com/user-attachments/assets/d250fac3-a44e-4548-9692-b8d2dd7d072c">

**Comment by GregValiant** [comment]
Thanks for the report.
I recall seeing bug reports about this and it may have been fixed in more recent versions.  I can't duplicate the problem in 5.8beta or 5.7.2.  The model I used in 5.7.0 wouldn't generate the problem either.

Recreate the problem and then use the "File | Save Project" command and zip and post the project file here.
