### ISSUE TITLE
Cura appears to hang when generating custom Tower

### ISSUE THREAD

**Issue by Beep6581** [Ultimaker/Cura#19467]
### Cura Version

5.8.0

### Operating System

Manjaro

### Printer

Creality Ender-3 V3 KE

### Reproduction steps

1. Extensions > Auto Towers > Custom Speed Tower

### Actual results

A popup appears, but the content is just a corrupt (cropped and non-interactive) copy of the custom settings. See screenshot.

![screenshot_20240802_175511](https://github.com/user-attachments/assets/07c65b11-fc16-42f5-abaa-f7ab0b0423ee)

I killed Cura thinking it was frozen, but after several attempts I found that it takes 30-120 seconds to generate the tower.

```htop``` shows that openscad is running, see screenshot later on.

Note that if you use a non-custom tower, e.g. Extensions > Auto Towers > Speed Tower - Print Speed 100-200, the model appears instantly.

### Expected results

If generating a custom tower is not instant, I would expect there to be a progress bar or spinner or something that tells me to wait 30-120 seconds, and not a corrupt popup.

### Add your .zip and screenshots here ⬇️

This appears in the console:
```
QQmlExpression: Expression file:///home/morgan/.local/share/cura/5.8/plugins/AutoTowersGenerator/AutoTowersGenerator/Resources/QML/QT6/SpeedTowerDialog.qml:69:17 depends on non-NOTIFYable properties:
    SpeedTowerController::towerTypesModel
```

![screenshot_20240802_180027](https://github.com/user-attachments/assets/f28d6850-bf04-4e5b-ab17-7aef0212713e)

**Comment by gh13** [comment]
Also OpenSCAD hasn't had an official release since 2021, however there are regular development releases, [https://openscad.org/downloads.html#snapshots ](https://openscad.org/downloads.html#snapshots )
which I've found to speed things up on the processing side & It might also be worth trying one of those.
As the dev releases can run in parallel with the official release & install to a (nightly) folder you'll have to updated the auto towers plugin setting so that it points to the path for the dev exe file rather than the exe from the official release.
