### ISSUE TITLE
Slicing Failed

### ISSUE THREAD

**Issue by AJames141** [Ultimaker/Cura#19497]
### Cura Version

5.8.0

### Operating System

Windows 11

### Printer

Sovol svo1

### Name abnormal settings

None, I literally just sliced a file 20 seconds prior. I have also sliced this current file in the past with 0 issues. 

### Describe model location

No, i rotated it 90 degrees and it will not slice.

### Describe your model

I have sliced this model before.

### Add your .zip here ⬇️

What zip file?

**Comment by GregValiant** [comment]
Thanks for the report.
We need something to work with in order to investigate.  Set Cura up to slice and use the "File | Save Project" command to create a project file.  Use the "Help | Show Configuration Folder" command to locate the Cura.log file.
Zip the 3mf file and the log file and post the zip folder here.
If you right-click on a file in Explorer you will see the "Send To..." command.  One of the options will be "Compressed (Zip) Folder".  You can zip one and then drag the other one into the zip folder to add it to the archive.
