### ISSUE TITLE
As with almost Every cura slicer version before this new one simply doesn't slice at all so how are people even using it

### ISSUE THREAD

**Issue by cnccarvey** [Ultimaker/Cura#19540]
### Cura Version

5.7.1

### Operating System

windows 10

### Printer

Creality CR10 S5

### Describe your model

Hub for quad bike

### Add your .zip here ⬇️

1040

**Comment by GregValiant** [comment]
There are hundreds of thousands of Cura users and 99.99999% don't have a problem.  That would seem to indicate that the problem is local to your computer.  My printer is a Creality Ender 3 Pro and I'm running Cura under Windows 10.  I've never had a problem with it.
I'm going to remove the "Slicing Error" tag because this problem is likely something else.  If you don't post a log file we really can't help.
