### ISSUE TITLE
Print Setup Disabled

### ISSUE THREAD

**Issue by scubabyrt** [Ultimaker/Cura#19588]
### Cura Version

5.8.0

### Operating System

Windows 11

### Printer

Anet et4 

### Reproduction steps

started with 5.4.0 and when downloaded some new files or tried to reopen saved designs only stl file. updated utilimaker and still cant open saved file to change some values. I get print set up disabled. g code cannot be modified. There are designs that my kids want to reprint and we cant

### Actual results

.

### Expected results

.

### Add your .zip and screenshots here ⬇️

![Screenshot 2024-08-26 184301](https://github.com/user-attachments/assets/bba9e885-2469-4919-8b83-a68d809ee986)

**Comment by GregValiant** [comment]
Thanks for the report.
If you want to re-slice a file then you need to load the model file (STL, 3mf, OBJ, etc.).
If you open a gcode file in Cura you can "preview" the file and you can print it via USB (maybe) but you cannot alter a gcode file in Cura because there is no model information in the file.  It's just a simple text file.

To actually edit a gcode file you would need to open the file in a text editor like Notepad and manually make changes.

I don't see a bug here so I'll remove the label and close this.  If you have questions post them and I'll try to answer.
