### ISSUE TITLE
5.8.0 Print one at a time

### ISSUE THREAD

**Issue by middlechamber** [Ultimaker/Cura#19623]
### Cura Version

5.8.0

### Operating System

Win11

### Printer

Creality Ender3 Pro

### Reproduction steps

Small Items I print 1 at a time when I upgraded to 5.8.0 the setting was already selected I hit print & it started printing all at once. I stopped Looked at the settings which was correct, so I switched it resliced then switched it back to 1 at a time & sliced it to print & it still printed all at once

### Actual results

Same thing

### Expected results

print 1 at a time

### Add your .zip and screenshots here ⬇️

No screen shot needed

**Comment by GregValiant** [comment]
Thanks for the report.
We ask for a project file because without one we have nothing to look at or compare to.
My printer is an Ender 3 Pro and I just finished a 4 model "One-at-a-Time" print.  It was perfect.  So on my own I am unable to duplicate this.
Are you running stock firmware or is something between the gcode and the printer (Sonic Pad, Raspberry PI, Klipper, etc.).
