### ISSUE TITLE
Bridging Orientation Problems

### ISSUE THREAD

**Issue by Andreuha** [Ultimaker/Cura#19659]
### Cura Version

5.8.0

### Operating System

Windows 10

### Printer

Snapmaker J1

### Reproduction steps

This seems to overlap with [10372](https://github.com/Ultimaker/Cura/issues/10372), which is a very old entry now and lacking the example of reproduction attached below.

This is triggered by adjusting the wall settings to completely fill in the volume in the sections of the part that bridges are supposed to be connecting. 

### Actual results

After increasing wall count, cura orients bridges along the long axis of the gap, with one end of the bridge being suspended in air. 

I have found no way to get Cura to orient the bridges correctly without reducing wall count or switching to a stock profile (that is not dialed in for this combination of filament and printer)

![Capture](https://github.com/user-attachments/assets/eb9b22d9-b503-4933-a1b2-a53558369ced)

### Expected results

Bridges should always go along the shortest direction of the gap. Bridges should generally avoid having one end be touching any unsupported material. 

Additionally, it would help a lot if there were a simple setting to just override the algorithm and force a specific direction for any bridges over a certain length layers across the part.

### Add your .zip and screenshots here ⬇️

[examples of same model with bridges in wrong and right orientation.zip](https://github.com/user-attachments/files/17017728/examples.of.same.model.with.bridges.in.wrong.and.right.orientation.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
When I open your "wrong orientation" file and slice it, I get this:
![image](https://github.com/user-attachments/assets/ae0efc12-4196-403f-8c5b-e648a06a2ae8)

I think the settings are different as you have a lot more walls in your preview.  Here I have set it to 5 walls and it still looks OK.
![image](https://github.com/user-attachments/assets/4ac0c327-62da-4b21-ab70-0158a036b78e)

If I make the wall count 5 it still doesn't match what you show in your screenshot.
![image](https://github.com/user-attachments/assets/e52171ef-9bdd-4d52-9a25-93497f92738a)

Load the model and set Cura up.  Use the regular "File | Save Project" command and post the new 3mf file.

**Comment by tremitry-darkstar** [comment]
I've experienced something similar. Community thread here (which includes my project file and a moderator comment that attempts to troubleshoot the issue: https://community.ultimaker.com/topic/44977-enable-bridge-settings/?do=findComment&comment=337582

In short, I have an Ender 3 that I'm trying to print some rail covers for. When I enable bridging mode, Cura attempts to print the first layer of the bridge along the long axis of the rails, which itself are just bridges over thin air. It seems to ignore the sides which a) exist and b) are a shorter distance to bridge.

Apparently, increasing the horizontal expansion to 0.2mm convinces Cura to print the first layer of bridging across the shorter axis (I believe 0.18mm is the point where Cura changes the axis it lays down the first bridging layer, but for my particular models, it did something weird to some of the circular parts of the models because it could not properly print a line around some of the rounded parts.) I'm literally printing these now to try it out.

**Comment by tremitry-darkstar** [comment]
Do I need to recreate this as a new issue now? I'm trying to avoid making duplicate issues....
