### ISSUE TITLE
Cannot change bed size for custom printer Cura 2.6

### ISSUE THREAD

**Issue by gbbickerton** [Ultimaker/Cura#1965]
I Cannot change bed size for custom printer when it is the only one, if I create a duplicate I can change the bed size on the new one .

**Comment by fieldOfView** [comment]
Same issue as https://github.com/Ultimaker/Cura/issues/1902
This can be mitigated by removing the folder named "old" from C:\Users\[yourname]\AppData\Roaming\Cura\2.6\machine_instances (note: Roaming, not Local)

Should be fixed with this PR, which I hope will still be included in 2.6: https://github.com/Ultimaker/Uranium/pull/258

**Comment by Ghostkeeper** [comment]
This seems to be a duplicate then (since duplicating the machine works, this appears to be the same problem).
