### ISSUE TITLE
Area to small for tree support

### ISSUE THREAD

**Issue by Sonnerick** [Ultimaker/Cura#19729]
### Cura Version

5.6.0

### Operating System

Win 11

### Printer

Mega Zero

### Name abnormal settings

Generate Suppor + Support Structure: Tree

### Describe model location

Center

### Describe your model

Button cover

### Add your .zip here ⬇️

[Button.zip](https://github.com/user-attachments/files/17307175/Button.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
Cura 5.5 and 5.6 had trouble slicing certain organic shapes.  Cura 5.6 is 5 versions out of date and the problem was fixed in Cura 5.7.0.
I would suggest updating to the latest stable release (5.8.1) or to 5.9beta which was just released.
I'll mark this as a duplicate and go ahead and close it.  I hope you understand.
