### ISSUE TITLE
Cant slice my print

### ISSUE THREAD

**Issue by Sparechange01** [Ultimaker/Cura#19732]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

ELEGOO NEPTUNE 4 MAX

### Name abnormal settings

just tree support

### Describe model location

centered

### Describe your model

it is a key fob

### Add your .zip here ⬇️

[Honda Key Fob - 3327112.zip](https://github.com/user-attachments/files/17320350/Honda.Key.Fob.-.3327112.zip)

the files i used were Back V2 Front V2 Honda Logo V2 latch V2 and lock screw

**Comment by GregValiant** [comment]
Thanks for the report.
Cura 5.5 and 5.6 had problems slicing certain shapes.  That has been fixed in later versions.  I suggest you update to the latest stable version (5.8.1) or to 5.9beta which has just been released.
I'll mark this as a duplicate and go ahead and close it as the problem seem to have been fixed.  I hope you understand.
