### ISSUE TITLE
Only basic settings visible

### ISSUE THREAD

**Issue by wasikan-git** [Ultimaker/Cura#19744]
### Cura Version

5.8.1

### Operating System

Linux Mint

### Printer

Prusa i3 Mk3S

### Reproduction steps

1. Click Settings/Configure settings visibility
2. Select eg. Advanced

### Actual results

Only basic settings are visible in the settings panel, no matter what was selected (Advanced, Expert, All).

### Expected results

Different sets of settings (according to selection) should be visible in settings panel.

### Add your .zip and screenshots here ⬇️

![Cura 5-8-1 2024-10-13 18-14-39](https://github.com/user-attachments/assets/d1cc82f5-d062-41c0-b0c0-30ae1875f778)

**Comment by Asterchades** [comment]
You need to switch to the Advanced/Custom page in order to view the individual settings, regardless of their visibility state. Simply click the *Show Custom* box at the top of the settings drop-down. A similar button should be present on the Custom page to change back to the Simple/Recommended view.

**Comment by wasikan-git** [comment]
Thank you, everything works. Though, I wouldn't call it intuitive.
