### ISSUE TITLE
Missing the 'CuraEngine Tiled Infill Generation' Plugin

### ISSUE THREAD

**Issue by Bedslinger** [Ultimaker/Cura#19765]
### Cura Version

5.8.1

### Operating System

Windows 11

### Printer

Creality Ender 3/Ender-3 v2

### Reproduction steps

1. Clicked on 'Marketplace'
2. Searched for 'CuraEngine Tiled'

### Actual results

The desired plugin (displayed in this video: https://www.youtube.com/watch?v=IOpm3cJbdHQ ) is not shown

### Expected results

The 'CuraEngine Tiled Infill Generation' plugin is shown as one of the plugins that comes up when its name is searched via the Marketplace

### Add your .zip and screenshots here ⬇️

![Screenshot 2024-10-16 162114](https://github.com/user-attachments/assets/6d078325-bdd0-4321-a7ce-3101fb261ff7)
![Screenshot 2024-10-16 162139](https://github.com/user-attachments/assets/f0b410d4-f822-43da-a065-34c9a8e778ec)

**Comment by GregValiant** [comment]
Thanks for the report.
It may have been removed for some reason.
@HellAholic ?

**Comment by GregValiant** [comment]
@Bedslinger,
There you have it.  I'll remove the bug label and close this as the removal was intentional.

If you have a previous version of Cura that included the plugin, and if it wasn't causing you any trouble (it did not for me) then you can copy the folder from your configuration folder ("Help | Show Configuration Folder") and the "plugins" sub-folder to the same folder in your new version.
![image](https://github.com/user-attachments/assets/d3321b04-e66b-4a7e-8618-971f56ae7b7a)
