### ISSUE TITLE
Using "Spiralize Outer Contour" walls become paper thin

### ISSUE THREAD

**Issue by norventa** [Ultimaker/Cura#19771]
### Cura Version

5.7.0 & 5.8.0

### Operating System

Windows 10 x64

### Printer

Creality SE 3

### Reproduction steps

With model attached I sliced it with Spiralize Outer Contour turned on...

### Actual results

 And Cura output the modified model with paper thin walls. There was also an artifact eminating from the "hinge".

### Expected results

The wall thickness should have remained unmodified, 2mm thick.

### Add your .zip and screenshots here ⬇️

[Cat Feeder Hopper v13.zip](https://github.com/user-attachments/files/17410938/Cat.Feeder.Hopper.v13.zip)

Without "Spiralize Outer Contour":
![image](https://github.com/user-attachments/assets/a843e81c-0ff3-4095-bad1-41e6c39671b9)

With "Spiralize Outer Contour":
![image](https://github.com/user-attachments/assets/eeeb9555-a300-4360-a679-aa1fe9e97bc4)

**Comment by GregValiant** [comment]
Thanks for the report.
The nature of Spiralize is to only print the outer wall.  Among other things that means that top surfaces are not allowed because the line index distance goes to infinity.
"Spiralize" automatically turns on "Remove all Holes" as it is required that a model be solid thru-and-thru.  You cannot spiralize a model with a vertical hole because the hole creates "islands" that require travel to get to.
You can see that the upper portion of the "Spiralized" preview is resting on air.
The arrows indicate the travel moves to and from the "island" that is the upper portion of the print.  Because spiralize is enabled - those travel moves are actually extrusions.
![NotSpiral](https://github.com/user-attachments/assets/0fcddc3b-cfcc-43bd-9c6b-53372a108308)

That model is not suitable for spiralize.  I'll remove the bug label and close this.  I hope you understand.
