### ISSUE TITLE
Error Print Cable Holder

### ISSUE THREAD

**Issue by Elvalio** [Ultimaker/Cura#19829]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Wanhao Duplicator 12 230

### Describe model location

Rotating at 90° work (but far from optimal)

### Describe your model

Never sliced (correctly) before

### Add your .zip here ⬇️

[Cable Holder - 2481258.zip](https://github.com/user-attachments/files/17562284/Cable.Holder.-.2481258.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
The slicing problems that plagued 5.5 and 5.6 have been fixed in later versions.  I suggest upgrading to 5.8.1.
I'll mark this as a duplicate and go ahead and close it as the problem has been fixed.

Here you can see that the Mesh Tools plugin has found errors in the model.
![image](https://github.com/user-attachments/assets/0a5f8986-be9b-42e6-b033-9363a1e0b59d)

This is the STL sliced in 5.8.0.
![image](https://github.com/user-attachments/assets/a0fa9202-9e4b-4a24-ba8f-4d4947fa4d42)
