### ISSUE TITLE
Slicing failed

### ISSUE THREAD

**Issue by andret92** [Ultimaker/Cura#19839]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Elegoo Neptune 3 Rpo

### Reproduction steps

Try to run a slice form a stl but keeps bringing error.

### Actual results

keeps showing the error for a while and then eventually shows me the slice result

### Expected results

That the failing doesn't happen all the time

### Add your .zip and screenshots here ⬇️

![Screenshot 2024-10-31 072617](https://github.com/user-attachments/assets/cdc8ec37-73eb-4b55-b68b-6762fd871677)

**Comment by GregValiant** [comment]
Thanks for the report.
Cura 5.5 and 5.6 had problems slicing certain geometries.  That was fixed in 5.7.0 and the current release is 5.9.0beta.  I would suggest you update to a newer version.  I run 5.8.0 and it's been fine.  An advantage to 5.9.0beta is the logic capability in the StartUp and Ending Gcodes.  If you think that would be of use then try the beta (but stay away from using Scarf Seams as there have been problems but they will definitely be fixed in 5.9.0 stable).
I'll mark this as a duplicate and close it as it was a well known bug in 5.6 but does appear to have been fixed in the more current releases.  I hope you understand.
