### ISSUE TITLE
Problemi nell'apertura dei file STL, senza disattivare l'usb printing. 

### ISSUE THREAD

**Issue by luigiamorfini** [Ultimaker/Cura#19850]
### Cura Version

5.8.1

### Operating System

Ubuntu Linux 24.04.1

### Printer

Anycubic Kobra Plus

### Reproduction steps

Salve, ho creato un video per farvi capire. Per aprire i stl con Ultimaker Cura devo disattivare l'usb printing dalle impostazioni. 
Come mai?.

Ubuntu 24.04.1

Ottengo quello che vi ho mostrato nel video.

Una cosa per non disattivare i plugin etc.. come devo fare?. C'è dare qualche permesso ad flatpak ?

Grazie mille e buon inizio settimana.

### Actual results

dopo aver disattivato l'usb printing si aprono i file stl.

### Expected results

tutto ok dopo disattivazione. 

### Add your .zip and screenshots here ⬇️

https://www.youtube.com/watch?v=PM0jF7VBql8

**Comment by GregValiant** [comment]
Thanks for the report.
The USB Printing plugin will poll the USB ports looking for a printer.  If you have other USB devices plugged in to the computer, and if they are internally configured as serial devices (like some bluetooth headphones and speakers) then Cura will keep trying to connect but cannot because it isn't a printer.  The other device doesn't respond as expected and USB Printing isn't complex enough to know that it cannot connect so it just keeps trying.
There has been discussion and feature requests to disable USB Printing by default.  Some of the original Ultimaker printers require it and that has been a snag.

I'll mark this as a duplicate report and close it.  USB Printing will not be updated by UltiMaker because it was found to be too unwieldly to work properly.
