### ISSUE TITLE
Slicer Issues

### ISSUE THREAD

**Issue by SuppleAubergine** [Ultimaker/Cura#19868]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

UltiMaker S5

### Describe model location

Middle

### Describe your model

Top of a helmet split into two sections one side doesn't slice the other does.

### Add your .zip here ⬇️

![image](https://github.com/user-attachments/assets/33632668-e136-438b-b36f-3740893a5edf)

**Comment by GregValiant** [comment]
Thanks for the report.
Cura versions 5.5 and 5.6 had problems slicing "organically" shaped objects, and objects with a lot of definition within a single layer (cobblestone floors in buildings, rough wood plank floors, etc.).  Those problems were addressed in 5.7.0 and the current stable version is 5.8.1.  I would suggest moving up to a newer version.

I'll mark this as a duplicate report and I'll go ahead and close it since the problem appears to have been fixed in the recent versions.  I hope you understand.
