### ISSUE TITLE
Cannot load STL file into slicer, no error message

### ISSUE THREAD

**Issue by Riptils** [Ultimaker/Cura#19906]
### Cura Version

5.7.1

### Operating System

ArchLinux

### Printer

Tronxy X5SA

### Reproduction steps

1. ➜ QT_QPA_PLATFORM=xcb cura5

2. click on load a file, load a (small) stl file

### Actual results

Nothing append even 5 minutes later

### Expected results

File loaded and appears in the slicer

### Add your .zip and screenshots here ⬇️

I'm on archlinux, I use sway on wayland (with xwayland). I'm using vulkan and all my opengl drivers are installed. I use an  AMD Athlon Silver 3050U with Radeon Graphics.
I'm using opensources drivers mesa - RADV. My system is up to date.

The only logs was : 
➜ QT_QPA_PLATFORM=xcb cura5        
qt.qml.typeresolution.cycle: Cyclic dependency detected between "file:///opt/cura5/share/cura/resources/qml/Actions.qml" and "file:///opt/cura5/share/cura/resources/qml/Actions.qml"

**Comment by GregValiant** [comment]
Thanks for the report.
Do you happen to have any auxiliary USB devices (headphones, earbuds, etc.) plugged in to the computer?  There has been a problem reported when a USB device is internally configured as a serial device, and "USB Printing" keeps trying to connect but cannot.  Disabling "USB Printing" in the Marketplace seems to be the fix for that.
