### ISSUE TITLE
sovol 04

### ISSUE THREAD

**Issue by arnaizluis** [Ultimaker/Cura#19927]
### Cura Version

5.7.1

### Operating System

windows 10

### Printer

sovol 04 idex

### Reproduction steps

con ultimaker cura 5.7.1 intento imprimir una pieza con el extrusor 2 en el perfil de impresora single mode 02
Genero gcode y la impresora intenta imprimir con el extrusor 1 (single mode 01) y no extruye plastico
Uso lo mismo pero con Sovol 3d cura version 1.7.2 y lo hace perfecto con el extrusor 2.
Con cura 5.7.1 siempre usa el extrusor 1 y si está configurado para single mode 2 no lo realiza

### Actual results

no se puede imprimir con extrusor 2

### Expected results

como en sovol 3d cura poder imprimir con el extrusor 2

### Add your .zip and screenshots here ⬇️

[gcode sovol y ultimaker.zip](https://github.com/user-attachments/files/17812812/gcode.sovol.y.ultimaker.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
UM printers always assume that Extruder 2 is the support extruder.  Since UM does most of the work on UM Cura, that's the way it will be for the foreseeable future.
The SOVOL printer definitions in UM Cura come from SOVOL.  They have a couple of problems (my opinion) in the StartUp Gcode.  They do not set the "mode" of the printer and they do not call out the active tool.

I don't have one of those printers, but I have looked at them.  I've written this plugin to (hopefully) fix the problems with the startup gcode.
In Cura, use the "Help | Show Configuration Folder" command to locate your config folder.
Download and unzip the attached file and place "SovolSV04_IDEX_Plugin" into the "plugins" folder within your "Configuration Folder".
[SovolSV04_IDEX_Plugin.zip](https://github.com/user-attachments/files/17815732/SovolSV04_IDEX_Plugin.zip)
Upon re-starting Cura the plugin commands will be available within the "Dual Extrusion" category.
![image](https://github.com/user-attachments/assets/8fff3fc9-a987-4583-b4a4-fe48937248e7)

When "Auto Select Mode" is chosen, the script looks at the printer name to determine the "mode".  That means you will still need the 5 printers installed.
If you specifically select "Dual Mode" then more options are available that can add additional gcode commands for Extruder Start, Extruder End, etc.

Let me know whether or not the plugin fixes your problem.
I'll remove the bug label and close this as it is a Sovol problem with their definition files.  I hope you understand.

**Comment by arnaizluis** [comment]
Muchas gracias, lo voy a probar.
Una gran máquina sovol04 con un malísimo firmware

**Comment by GregValiant** [comment]
The definition files aren't great either.
