### ISSUE TITLE
QIDIPRINT Plugin  crash after version > 5.6

### ISSUE THREAD

**Issue by Martin-By** [Ultimaker/Cura#19950]
### Is your feature request related to a problem?

I use a Qidi Printer X-MAX 1 along with the plugin qidiprint (from Github, [link to QIDIPRINT plugin)](https://github.com/nkuvyrkin/Ultimaker-Cura-v5.x-QIDI-X-CF-Pro-Plugin/releases).
This plugin works fine until Cura version 5.6. For newer versions (5.7, 5.8, 5.9 last nightly build) I can enter the preview tab and when I return to the prepare tab Cura stop working and shutdown.
[Uploading cura.log…]()

### Describe the solution you'd like

That Cura does not crashes.

### Describe alternatives you've considered

I do not know.

### Affected users and/or printers

qidi X-Max use

**Comment by GregValiant** [comment]
Thanks for the request.
You have a third party printer and are using a plugin and definitions from a 4th party.  I have no way to check this because I don't know the printer or what the author of the plugin may have done.

Cura 5.9.0 has 150 more settings than Qidi 5.6 (which is Cura 4.9) and 40 settings have been deleted since 4.9.
This is a prime reason why definitions have to come from the community.
I'm going to close this.  Let me know if you feel that is premature.
