### ISSUE TITLE
Tree Supports Unable to Slice

### ISSUE THREAD

**Issue by blboyd** [Ultimaker/Cura#19975]
### Cura Version

5.6.0

### Operating System

Win10 Pro

### Printer

FLsun V400

### Reproduction steps

I can slice all day long without supports or with normal supports but as soon as I slice with tree supports it stops half way through the slicing process.

### Actual results

Slicing stops half way through with slicing failed

### Expected results

Slicing should complete

### Add your .zip and screenshots here ⬇️

This happens with any file

**Comment by GregValiant** [comment]
Thanks for the report.
This was a known problem with 5.6.0 and was addressed (and seems to be fixed) in later versions.
Try upgrading to [5.8.0](https://github.com/Ultimaker/Cura/releases) scroll down and the installation files will be under "Assets"(5.9.0 has a couple of issues).

I'll mark this as a duplicate and close it as the problem appears to have been fixed in current versions.
