### ISSUE TITLE
This "Bug" Forces Unnecessary User Errors

### ISSUE THREAD

**Issue by TSBrownie** [Ultimaker/Cura#19985]
### Cura Version

5.4.0

### Operating System

Windows 10

### Printer

Ender 3 Pro

### Reproduction steps

1) I prepare a print.
2) Write it to a micro SD card.
3) Print the print, only to find the wrong parameters were executed.

### Actual results

I often get unexpected results when printing. It requires reprints. 
Cura parameters are stored at the app level and not in the .3mf file. 
Therefore, when I switch between project A & B, I often get project A's parameters on project B
and vice versa. It's a huge waste of time and money.

### Expected results

I would expect that the Cura parameters set for a project are saved in the 3mf file for that project (rafts, temperature, speed, support, quality, etc.)
Then, when I have 3, 4, or 5 projects going, I don't end up using the wrong set of parameters for a project.

### Add your .zip and screenshots here ⬇️

None

**Comment by Asterchades** [comment]
Cura does save the parameters to Project files - that's why they're requested for diagnostic purposes, as they contain all of the settings instead of just the ones that the user remembers that they've changed.

Nothing forces you to load them as Projects, though. By default an option is presented when opening a 3MF containing a project as to whether you want to load it as a Project or just the model files contained within. There is also, however, a check-box which can be used to "Remember [my] choice" which will, as the name suggests, open every print from then on using whichever of those two options you select - whether that's what you want to use on a specific later Project or not.

You can change the behaviour through the main Cura Preferences. Towards the bottom, just above the **Profiles** heading, is a drop-down for setting the _Default behaviour when opening a project file_. Just below that same heading is one for the _Default behaviour for changed setting values when switching to a different profile_ - though I will admit the dialogue this presents doesn't draw a lot of attention to any individually changed settings, rather than saved profile settings.

**Comment by GregValiant** [comment]
There is also some confusion because there are 3mf model files that are not project files.  If you saved one as a project using "File | Save Project" then it's definitely a project and contains:  Your model, all the Cura settings, and your machine with it's specific machine settings (custom startup gcode, etc.).  We couldn't do the triage around here if that wasn't true.
If you "Exported" a model as a 3mf file, then just the model is in the file without any settings and without a printer.

UM did not create the 3mf archive standard and it has been around awhile.  All the slicers use it for projects and so it is always an issue when someone opens a simple 3mf model file and expects settings to change but they don't.

I don't see a bug here so I'll remove the label and go ahead and close this.  Let me know if you feel that is premature.
