### ISSUE TITLE
missing build plate temperature option

### ISSUE THREAD

**Issue by Jimmyracle** [Ultimaker/Cura#20029]
### Cura Version

5.9.0

### Operating System

mac os Sonoma Version 14.4.1

### Printer

creality k1 max

### Reproduction steps

i looked for the build plate temperature adjustment option. i focused on the materials pulldown menu to find this option. couldn't locate it. checked other pulldown menus, still could not locate it. went under preferences to see if the build plate temperature setting is selected, it is selected.

### Actual results

cannot change build plate temperature, due to missing option from materials pulldown menu.

### Expected results

with the option present, the temperature of the build plate should be adjustable.

### Add your .zip and screenshots here ⬇️

![Screenshot 2024-12-13 at 9 12 06 AM](https://github.com/user-attachments/assets/70f99b2c-5d5d-43ab-ac01-ba165d6b4326)

**Comment by HellAholic** [comment]
Try the search bar in either the setting visibility or the print setting
![image](https://github.com/user-attachments/assets/0ce1e718-9770-4057-988e-32db7da66516)

**Comment by Jimmyracle** [comment]
![Screenshot 2024-12-13 at 9 15 25 AM](https://github.com/user-attachments/assets/6bce0728-6f13-4431-a61d-bcbeb96c7d4e)
 The first screenshot was a mistake.

**Comment by HellAholic** [comment]
Ok in that case, since you have a little info button next to the build plate temp, I am guessing that in the machine settings the heated bed is unchecked. Which is what the tool-tip is probably say if you mouse over the info button next to the build plate temperature in the setting visibility you shared.
So in the preferences go to the printers, select your K1 Max, select machine setting, and check if the heated bed is checked.
![image](https://github.com/user-attachments/assets/788d35f3-9700-42c5-b52d-f9c31430b029)

If it is checked. select your printer > go to help > export package for technical support, this creates a 3mf file with the machine and your logs, make a zip out of that and drop it in the report here.

**Comment by Jimmyracle** [comment]
You solved my problem, thank you HellAholic.
![Uploading Screenshot 2024-12-14 at 9.16.49 AM.png…]()
