### ISSUE TITLE
Slicing for EX1 only but Cura activates EX0 at the end of Layer:1

### ISSUE THREAD

**Issue by slyari** [Ultimaker/Cura#20021]
### Cura Version

5.6.0

### Operating System

Windows 11

### Printer

Custom bedslinger IDEX

### Reproduction steps

I have two toolheads in Cura. I deactivated EX0 (left toolhead) and activated EX1 (right toolhead). I sliced my part with only EX1.

### Actual results

At the end of layer 1, EX0 activates and starts heating to 200. EX1 parks. EX0 moves towards the part, retracts, then parks. EX1 stays at 200 the entire time. EX1 returns to printing the part. This does not happen when printing with only EX0. 

go to LAYER:1 in the gcode and scroll up a bit. You will see T0 is activated for no reason. 

### Expected results

I expected EX1 to print the entire part without EX0 activating or moving since that extruder is disabled in the slicer.

### Add your .zip and screenshots here ⬇️

[cura bug.zip](https://github.com/user-attachments/files/18083145/cura.bug.zip)

**Comment by GregValiant** [comment]
Thanks for the report.
Without a project file I can't investigate because I can't duplicate this.  When I disable T0, set the model to T1, and slice - only T1 shows up in the gcode file.  I'm using 5.9.0.

I suggest you update Cura to 5.9.0.
I'll go ahead and close this.  After upgrading, if this behavior is still an issue then this bug report can be re-opened and updated to include 5.9.0.
