### ISSUE TITLE
Initial build plate temp&build plate temp..

### ISSUE THREAD

**Issue by muhendis80** [Ultimaker/Cura#2003]
I made
Build plate temperature 0 C
Build plate temperature Initial layer 100 C

it is always working at 100 C, but it did not cold down temperature to zero after initial layer made

**Comment by Ghostkeeper** [comment]
Indeed, this reproduces. I suspect because 0 degrees is treated as a special case where it would simply not be necessary to output any temperatures (until first layer bed temperature was introduced as a feature).

Workaround for now is to put the ordinary bed temperature to 1 degree. I'm filing a bug about this though.

**Comment by Ghostkeeper** [comment]
You're going to have to keep using the workaround. Our project manager just removed this issue from our planning for being older than 12 weeks.

**Comment by Ghostkeeper** [comment]
This one is earlier, but let's treat it as a duplicate of https://github.com/Ultimaker/Cura/issues/2674
