### ISSUE TITLE
[5.9.0] USB Printing plugin causes Cura to freeze or hang when enabled

### ISSUE THREAD

**Issue by JohnVlahidis** [Ultimaker/Cura#20054]
### Cura Version

5.9.0 (Flatpak and AppImage tested)

### Operating System

Pop!_OS 22.04 LTS GPU: Intel Integrated Graphics (Mesa drivers up to date)

### Printer

No printer connected. Using Cura for slicing only.

### Reproduction steps

1. Open Cura (5.9.0).
2. Keep the USB Printing plugin enabled (default state).
3. Attempt to open an STL file (e.g., a simple cylinder or cube).
4. Cura either freezes indefinitely or takes a very long time to load the model.
5. Disable the USB Printing plugin.
6. Open the same STL file again—Cura processes it instantly.

### Actual results

Cura hangs or becomes extremely slow when opening STL files while the USB Printing plugin is enabled, even if no printer is connected. Disabling the plugin resolves the issue completely.

### Expected results

Cura should open STL files promptly, regardless of whether the USB Printing plugin is enabled or disabled, especially when no USB printer is connected.

### Add your .zip and screenshots here ⬇️

![cura_bug_report_converted](https://github.com/user-attachments/assets/4dfad21d-cc3b-4c42-8d69-4fb072267771)
[cura.log](https://github.com/user-attachments/files/18203429/cura.log)

**Comment by GregValiant** [comment]
Thanks for the report.
This is an often reported bug with the USB printing plugin.  If you have USB devices attached to the computer and they are internally configured as "serial devices" then Cura will keep attempting to connect to them thinking that it's a printer.  I know some USB headphones and speakers have the problem.  (See #19633 which is also in regards to FlatPack and feature request #19373).

Just disable USB printing if you aren't using it.  It is a legacy feature kept in Cura because Ultimaker Originals require it.
I'll mark this as a duplicate and close it.  There has been discussion at Ultimaker about this problem but there is no fix in place yet.
