### ISSUE TITLE
RFE: concentric zigzag infill pattern

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [Ultimaker/Cura#2074]
this request is to add concentric zigzag infill pattern, for example:
![image](https://user-images.githubusercontent.com/1622151/27874631-cbe3271e-6175-11e7-98d5-5032d8a58652.png)

**Comment by Andrei-Pozolotin** [comment]
problem with current concentric: it collapses on high print speeds
problem with current zigzag: it is not concentric (works on high speeds)

**Comment by BagelOrb** [comment]
Well, this pattern doesn't allow for high print speeds because the line segments are so short that the actual sped will be limited by your acceleration / jerk settings.

I'm sorry to say that I don't think this is worth investing our precious implementation time.
There are loads of cool features still on our TODO list, and the TODO list keeps overflowing.
