### ISSUE TITLE
Cura 2.6.1: Default Prime tower position invalid

### ISSUE THREAD

**Issue by Dim3nsioneer** [Ultimaker/Cura#2090]
The situation this issue occurs on the UM3 is when you have two materials with very different settings for the brim size, e.g. pp (very large brim) and tpu-95a.
To reproduce the error do this:
- load two objects
- select pp in first printcore, eg. tpu-95a in second printcore
- assign one object to the second extruder
It seems Cura places the prime tower according the settings of printcore 2 which happens to be in the forbidden range of printcore 1.
![cura_261_primetowerpositioninvalid](https://user-images.githubusercontent.com/5468304/27992655-d847900e-6499-11e7-8686-286f7d10d0e5.jpg)

**Comment by Ghostkeeper** [comment]
Yeah, we have a bit of a problem here. We keep moving that prime tower ever so slightly further towards the centre because we keep getting profiles with large brims or rafts.

In this case, the PP profile is the culprit. We'll have to move the prime tower again, but that's no permanent solution. Perhaps we could devise a way to place the prime tower always just inside with an inheritance formula... I might give that a try tomorrow.

**Comment by Dim3nsioneer** [comment]
Cool, thx.

**Comment by Ghostkeeper** [comment]
Fixed this for the Ultimaker 3 here: https://github.com/Ultimaker/Cura/commit/ee52e1b9eaf055433ce5c3367045402c078b50df

**Comment by Dim3nsioneer** [comment]
I guess you are aware that at a certain brim size the x coordinate still can cause the same issue?

**Comment by Ghostkeeper** [comment]
Yeah, I'm aware, because of the bed clip and such. We're not running into the limit right now, so I think I'll leave that for later :)
