### ISSUE TITLE
Brim from model is removed when slicing

### ISSUE THREAD

**Issue by gabfv** [Ultimaker/Cura#2098]
When printing the Hairy Lion with brim model from [Thingiverse](https://www.thingiverse.com/thing:2007221), the brim from the model is removed when it is sliced in Cura 2.6.2 on Win10 x64 Pro. Is that normal? The file used is named **Hairy_Lion_with_brim.STL**. Here's my profile: 
[60mms-20infill-PLA-FanV2.zip](https://github.com/Ultimaker/Cura/files/1135908/60mms-20infill-PLA-FanV2.zip)

Here's what I get in Cura after slicing:
![image](https://user-images.githubusercontent.com/24780542/28023506-175dd254-655c-11e7-8a92-70155e9b7b5a.png)
Here's what I have in Meshmixer:
![image](https://user-images.githubusercontent.com/24780542/28023641-6faee164-655c-11e7-8b6b-c5ec5510fa9f.png)

**Comment by Ghostkeeper** [comment]
Yes, I'm getting the same result. The problem is that the "brim" is slimmer than the initial layer height. Three things you could do:
* Move the model upwards by 0.07mm (z).
* Set the initial layer height to 0.2mm. Reduces bed adhesion though.
* Just enable Cura's brim. This would also produce a brim around the lion, not just around the draft shield though.
