### ISSUE TITLE
Skirt Shrink when Scale Increased

### ISSUE THREAD

**Issue by ocarlier** [Ultimaker/Cura#2175]
In Cura 2.6.2, when uniformly increasing the scale, with skirt build plate adhesion enabled; the skirt prints at a smaller size within the footprint of the object.

**Comment by Ghostkeeper** [comment]
This can happen when you have models with a bottom side that is not flat. When you scale the model up, some of the bottom side gets shifted up towards the second layer rather than the first, leaving only some small bits on the actual first layer.

Was your model flat? It doesn't happen for me when I use a flat object.

**Comment by ocarlier** [comment]
Sounds about right; thanks.
