### ISSUE TITLE
custom printer in latest version

### ISSUE THREAD

**Issue by giliammc** [Ultimaker/Cura#223]
why did you remove the custom printers from the latest version of cura (15.6)

**Comment by awhiemstra** [comment]
Custom printers were removed due to a complete rework of the settings structure. Specifically, the ability to create a custom printer from within the UI was removed, you can still add custom printers but the steps have changed slightly. See https://github.com/Ultimaker/Cura#making-profiles-for-other-printers

**Comment by giliammc** [comment]
it would be nice if there was a gui for this

**Comment by nallath** [comment]
There is a generator out there that someone made. We're also looking into something.
