### ISSUE TITLE
Feature request : Infill "shift"

### ISSUE THREAD

**Issue by darkdvd** [Ultimaker/Cura#2412]
For a specific project, I need to print an object that fits in a volume of 210.8 x 200.2 x 195.5 mm.
For this project, I use an infill of 3% (triangles)
I need to position the fill on the axis of the object to reinforce some parts.
Problem: I can't move the object sideways to make it coincide with the infill.
Can you introduce the possibility of moving the X/Y origin of the infill?
![px_infill_p1](https://user-images.githubusercontent.com/16816760/30282961-161a5164-9717-11e7-98d0-0604d36d0f7a.jpg)

**Comment by darkdvd** [comment]
To begin, please excuse my English (I use GG translate)

In most cases, Infill is used only as an internal support for an object.

In my case, the Infill is an important mechanical element playing an essential role in the construction of an object.

With CURA, the Infill is positioned in the center of the buildplate, which is not a problem for most objects. : To adjust the position of the Infill, simply move the object on the board.

I am currently working on a project where the filling has to be done in the longitudinal axis of the object.

This object is inclined by 42 ° on the plate and it is 195.5 mm high.
I used the "Infill Line Directions" function to orient the Infill in the axis of my object using the values ​​[47,107,167] for an Infill in triangles.

Problem: I can not move my object to align the Infill longitudinally.

Could you add an option "Infill Origin" with two options in the parameters:
- Buildplate Origin
- Object Origin

Another parameter "Infill Origin Directions" would allow this position to be adjusted. Ex. [-5,15] to move the Infill from -5mm to X and 15mm to Y

Merci !

David.

**Comment by smartavionics** [comment]
Err, it might be easier if you got yourself a bigger printer (just kidding).

**Comment by amagr0** [comment]
That's a very important future feature in order to guarantee similar mechanical properties in the same models that are placed in different positions on the print bed.
Like the zscar that now have the option to "Z Seam Relative", a similar approch could be implemented to the infill.

![screenshot_1](https://user-images.githubusercontent.com/12901952/30372819-fe678db4-9876-11e7-8f0f-94624b725c7c.jpg)

**Comment by smartavionics** [comment]
I agree, having the ability to move the infill origin so as to achieve uniform mechanical properties across multiple parts would be very good. I'm not familiar with the Cura infill code but I when I have some time I will look into how that could be achieved.

**Comment by darkdvd** [comment]
Daid, Jun 4, 2014 - 12:17 PM
http://ultimaker.com/en/community/6937-ability-to-shift-infill-pattern-in-cura#reply-55665

**Comment by darkdvd** [comment]
note : concentric infill is centered to the object.
https://github.com/Ultimaker/CuraEngine/blob/master/src/infill.cpp LINE 114

**Comment by DDDirk** [comment]
I agree, I also once spent some time shifting a model around until I finally got the infill-walls where I wanted them. But I also had to play with the infill percentage to get something that seemed good. And it was actually rather a coincidence that I got the infill walls exactly where I wanted them, in different parts of the model (what worked in one location also worked in another).

Another way to achieve this is by incorporating the internal supporting structures in the model. That way you can make less homogeneous supporting structures, exactly where you want them. This is an as yet little used advantage of 3D printing, the ability to make internal structures just as easily as the visible external parts.
One way to do this is to make big holes in the model (where you don't want or need any material) and use 100% infill. Another is to place very thin bars (where you want the supporting structures) with 0% infill. (Or any percentage you like of course.) Both work with the boolean subtract of a CAD program. And in Cura, make sure 'mesh fixes > union overlapping volumes' is enabled.
The second method is a bit more complicated because the thin bars have to be sufficiently close to the shell, so they touch (which depends on the shell width). What happens is that Cura will create a shell around those thin bars, which then becomes the supporting structure. That's why they can be very thin (although they don't have to be).
Of course the bars have to be placed such that they don't need any support (eg not horizontal). Or with the second method you could use infill anyway, which then acts as a support structure (just like when the model has a horizontal top). And then it would be nice if you could get that where you want it, as requested above.
Note that if you use infill, those internal shells will be printed at shell speed, which will likely be lower than infill speed. And thus possibly stronger.

However, this is more work, possibly too much if you want to do a single print. And for smaller models it might not work well. So I am still in favour of the proposition.

**Comment by smartavionics** [comment]
Hi Folks, I've done a bit of work on this and have basic "infill origin" support working. Have a look at this image, there's two parts, the infill is identical for the two parts and has been offset  by 1mm to the right and 4mm upwards so that one of the infill "nodes" coincides with the hole on the bottom left of each part. If you look at the settings you can see new Infill X Offset and Infill Y Offset fields. The infill does not shift when the part it shifted on the build plate.
![screenshot_2017-09-17_23-00-13](https://user-images.githubusercontent.com/585618/30525351-dfcac7fc-9bfc-11e7-8e2b-c8f41202f068.png)
Is this the sort of capability you are looking for?

**Comment by darkdvd** [comment]
Yes ! 
And if you change the infill direction to "[30,90,150]" the Infill for the holes on the bottom will be aligned too.
Just play with the infill % and tada !

**Comment by darkdvd** [comment]
The infill shift is more useful when you cannot move the piece on the buildplate because it is too large.

**Comment by darkdvd** [comment]
smartavionics : is the infill a per model setting too ?

**Comment by smartavionics** [comment]
> And if you change the infill direction to "[30,90,150]" the Infill for the holes on the bottom will be aligned too.
Just play with the infill % and tada !

Like this?
![screenshot_2017-09-18_06-59-41](https://user-images.githubusercontent.com/585618/30530495-0d7bf026-9c3f-11e7-9561-da86dcb07cc1.png)

**Comment by smartavionics** [comment]
Yes, the offsets are settable per-model.

**Comment by darkdvd** [comment]
Definitely to put in the next version of CURA !

**Comment by Labern2** [comment]
+1 this will be very handy.

**Comment by Ghostkeeper** [comment]
This was implemented now. I'm not sure if this got in time for 3.0, but it's in 3.1 anyhow.
