### ISSUE TITLE
Changing printer settings requires too many clicks

### ISSUE THREAD

**Issue by yourhead** [Ultimaker/Cura#2490]
In order to change the nozzle size of my printers I have to:

1. Choose Settings
2. Printer
3. Manage Printers
4. Click Machine Settings
5. Change the nozzle size.

If there are machine settings available it seems like they should appear in Settings menu. That would save at least 1 click.

Even better -- put the nozzle size (and other often adjusted features of the machine) in the main window instead of buried.

**Comment by nallath** [comment]
The issue here is that your printer was not setup with the correct profiles; If you have a look at a UM2+ (which has an ollson block), you will have such a configuration; There you can select a nozzle size by means of a drop down next to your profile. Good third party profiles need to be provided by others. As you might imagine, we (Ultimaker) won't spend time on creating these.

If you want an easier way of doing this / don't feel like creating all the profiles it need; just change the line width. That's the actual setting that is used by the engine. The line width is calculated from the nozzle size, but the engine only uses "leaf" settings.
