### ISSUE TITLE
Cura 2.7: Missing option Print Sequence

### ISSUE THREAD

**Issue by tthurow** [Ultimaker/Cura#2497]
There is no option to set the print sequence by more as on model.

![error cura](https://user-images.githubusercontent.com/6584969/30909912-0f773f34-a383-11e7-9be7-006120799f49.png)

![models](https://user-images.githubusercontent.com/6584969/30909997-67ea19ac-a383-11e7-9851-f37f5a72aac1.png)

**Comment by nallath** [comment]
This has never been possible on the UM3 (or any dual extrusion machine)

**Comment by tthurow** [comment]
Then the error message is misleading. I also do not understand this limitation, especially in the industrial environment, this is an extremely important function to be able to print parts sequentially onto the printing plate, unattended over hours. In my view there is no technical reason against the function, only the restricted areas are larger.

**Comment by fieldOfView** [comment]
You can in fact go to Preferences -> Printers -> Machine Settings, and set the number of extruders to 1. Then you can print One at a Time, though only with the first extruder.

**Comment by Ghostkeeper** [comment]
The limitation is a technical one that could in theory be resolved in Cura but we haven't yet. There's two things preventing us from allowing One-at-a-Time printing with multi-extrusion right now:
* When moving to a wipe brush or switching bay, you might hit previously printed objects.
* You need multiple prime towers.

The error message is a bit unclear because it's automatically generated, but it's the number of extruders that you have that prevents this setting from being visible, so the message by itself is correct.

**Comment by ianpaschal** [comment]
One at a time mode is now working thanks to disabled extruders.

**Comment by Ghostkeeper** [comment]
To be clear, you can now disable extruders so that there is only one extruder left. Then you'll be able to select one-at-a-time mode again.

However dual extrusion one-at-a-time printing still doesn't work. We have an issue open for 3+-extruder prime towers.
