### ISSUE TITLE
Support density field generating insufficient support for BB .8, Extruder 2

### ISSUE THREAD

**Issue by lgreenlee** [Ultimaker/Cura#2606]
I am using a BB .8 extruder with Ultimaker Natural PVA. 

When selecting "Support Density %" the field generates insufficient support material in some cases. This can be traced back to an insufficient Support Line Distance value of 3 * [Nozzle Diameter] @ 100%. 

This setting appears to generate sufficient support with the BB .4 nozzle with a minimum value of 1.2 mm. The minimum value of 2.4mm for the BB .8 however is too small, especially for large support scaffolds that have some height they eventually cool and separate.

I would suggest just using the base nozzle diameter as 100% to make the scale more meaningful.

**Comment by Ghostkeeper** [comment]
The support line distance is 3 times the nozzle diameter at 100% because the support pattern is triangles. So there is 3 times the distance between parallel lines but it draws 3 times as many parallel lines. In other words, that behaviour is expected. That doesn't mean that it couldn't be made more clear how it got to that line width. The setting description says nothing about this so maybe that needs some improvement.

These lines overlap at the intersection points, which prevents the material from extruding. This is why you actually get less than 100% infill in that case. In reality what happens is that you get lots of tiny little pillars of material because it's just blobs upon blobs piling up at the intersections.

Might I suggest using support interface instead at a 100% infill density? You could give it a pattern then that's more suitable for 100% infill, such as lines or concentric. And your normal gradual support would still work for the rest.
