### ISSUE TITLE
error in slice

### ISSUE THREAD

**Issue by lamerhouse** [Ultimaker/Cura#2641]
as you can see from the picture that there are inconsistencies and this is reflected on the printed object
![2017-10-20](https://user-images.githubusercontent.com/11464372/31816283-fb42cc8a-b58f-11e7-8b3f-ce98524cc7ff.png)

**Comment by ChrisTerBeke** [comment]
Can you attach a project file so we can debug this?

**Comment by lamerhouse** [comment]
[bocchettone giusto.zip](https://github.com/Ultimaker/Cura/files/1408791/bocchettone.giusto.zip)

**Comment by Ghostkeeper** [comment]
Yup, reproduces for me too (using UM3 default profiles AA0.4/PLA/Fine).

It's the overlap compensation kicking in. The hollow cone has a shell that's approximately 0.6mm thick. It wants to place two walls there (one for the inner border and one for the outer border). But two lines of 0.35mm aren't going to fit, so it makes one line of 0.35mm and another of 0.25mm.

The problem is that sometimes it decides that the inside border needs to be 0.35mm and the outer 0.25mm, and sometimes the other way around. Since the overlap compensation only adjusts flow and not the positions of the lines and you only see the outside line, you will see the 0.35mm lines as protruding farther than the 0.25mm lines.

When printing this effect will be lesser, since the material overflows where the line doesn't fit, but since the printer is imperfect you will still see the effect a bit on the actual surface.

To solve this we'd need to find a way to canonicalise which of the two overlapping lines gets reduced. I don't see a way to do that directly though...

**Comment by BagelOrb** [comment]
The second printed line is always the one being compensated.

It seems that it's not always printing the outer outline first.

I think it would be a good idea to always print the most outside outer wall first.

**Comment by jackha** [comment]
As of Cura 3.4.1, this seems to be fixed.

![gh2641](https://user-images.githubusercontent.com/1016604/44398415-0aa8e480-a544-11e8-8e39-21447856aa34.png)

**Comment by lamerhouse** [comment]
perfect

Il giorno mar 21 ago 2018 alle ore 13:14 jack <notifications@github.com> ha
scritto:
