### ISSUE TITLE
Cura 3.0.3 under extrusion on layer change

### ISSUE THREAD

**Issue by Inglebard** [Ultimaker/Cura#2672]
Hi,

I just notice under extrusion on Cura 3.0.3. It's visible after travel before layer change. I try to enable/disable retractation, the issue is the same. The problem was not present in Cura 2.7.

I use a Prusa MK2s with default profile "Draft Quality".

I attach an image to show the issue. (left cura 3, right cura 2).
![curatest](https://user-images.githubusercontent.com/8203903/31966019-95e45516-b909-11e7-9467-77ee56a6204d.jpg)

I also join gcode generated by cura 2 and cura 3 and the STL used in the zip file. (just need to print some layers to see the problem)
[test-cura.zip](https://github.com/Ultimaker/Cura/files/1412392/test-cura.zip)

**Comment by smartavionics** [comment]
I think the problem you have is caused by the fact that with the default settings, cura 3, does not align the z-seams on the inner and outer layers and also does not optimize the order in which the walls are printed to minimize travel. The underextrusion you are seeing is, I believe, caused by the fact that before that outer wall is printed, there is a long distance travel move and the nozzle is oozing all the while so when it gets to the outer wall, it underextrudes.
I think you can fix this by turning on the experimental wall order optimization and it may pay you to specify the z-seam position also.

**Comment by Inglebard** [comment]
Hi,
Ok, so it's not a bug, it's a feature :-)

> The underextrusion you are seeing is, I believe, caused by the fact that before that outer wall is printed, there is a long distance travel move and the nozzle is oozing all the while so when it gets to the outer wall, it underextrudes.

Well, you are right. The travel move is longer on Cura 3. But does this means there is no retraction above infill ? (if it's the case, combined to non wall order optimization, it's 100% problem on a lot of prints, no ?)

> I think you can fix this by turning on the experimental wall order optimization and it may pay you to specify the z-seam position also.

Ok, I will check this ASAP.

**Comment by smartavionics** [comment]
Hi
> But does this means there is no retraction above infill ?

Yes, when combing is enabled (which I think it is by default), there is no retraction above infill.

**Comment by Inglebard** [comment]
Activate wall order optimization fix the issue.

**Comment by Ghostkeeper** [comment]
In 3.1 we've made the Z seam to be aligned in the inner walls as well.

**Comment by Inglebard** [comment]
Ok, waiting for the next release so.

**Comment by agasevangelos** [comment]
Hi!
I have the same problem on version 2.5, 2.6, 2.7!
The older version 1.5 of Cura don't have this issue.
So why is this happening?

**Comment by agasevangelos** [comment]
I think I have found the solution.

Turning **Combing Mode** **off** on versions after 1.5 seems to solve the problem!
_(Which is quite weird because on version 1.5 with Combing Mode on there is not a problem.)_

**Comment by bwarring24** [comment]
I have this same problem as well. Cura 15 doesn't have an issue. @agasevangelos I will try to turning that off and printing a test cube to see if it fixes it. It has been so annoying because I love having all the features in Cura 3.1 vs Cura 15, but I also want good quality prints. I'll report back tomorrow.

**Comment by bwarring24** [comment]
@agasevangelos I just printed a test cube with combing off and it came out flawless! Thank you so much for figuring it out!

**Comment by agasevangelos** [comment]
Hey hello!
I am glad that you found it useful and you confirmed it too!
Its a really weird problem. It took me so much time to figure it out. because on previous cura I allways had combing mode on.
I would like to hear from the cura development community how is this possible?

**Comment by fyl2xp1** [comment]
I came across this issue while hunting down a slightly different problem, but it also seems to be caused by combing=on as default setting.

Please have a look at https://www.thingiverse.com/groups/prusa-i3/forums/general/topic:28926

Can this be solved by other means than disabling combing? My case is rather standard and I would expect it to work with default settings.

**Comment by Ghostkeeper** [comment]
In that thread the Runtimeerror user mentions this:

> I think I'll have to find a way to tell Cura to wait for the filament coming out after a transport.

I can answer that: Try setting Retraction Extra Prime Amount to a few cubic millimetres. It extrudes a slight bit after each retraction to get the filament flowing more. It won't prevent stringing but it will prevent underextrusion after stringing if tuned correctly. Maybe that makes the lines more sturdy and thus less wobbly?

**Comment by fyl2xp1** [comment]
The problem described in the thread occured due to combing which explicitely doesn't use retraction. So the Prime Amount won't help here.

Maybe faster travel speeds might help to mitigate the problem a bit.

Another compromise might be to use retraction only when crossing other structures. Currently disabling the combing mode results in a retraction hell when printing the infill pattern.

**Comment by LubosD** [comment]
I'm hitting this problem on my Mk3. I've spent quite a while chasing this one down, one of the things that helped a little for the picture in the initial post was disabling "Compensate Wall Overlaps", but as I read this topic, I'm led to believe that was just a partial workaround.

I have the problem already [linked](https://www.thingiverse.com/groups/prusa-i3/forums/general/topic:28926) here. But for me also some parts of the print just don't get printed this way and I don't remember having encountering this in the past.

![See this photo](https://user-images.githubusercontent.com/878801/40389087-b13447b0-5e11-11e8-8dc5-e140437073fd.jpg)

I was watching this print very closely and it seems the filament doesn't get primed in time. I thought something was wrong with my printer, but this issue is non-existent in Slic3r Prusa edition.

**Comment by Ghostkeeper** [comment]
We should probably have a separate ticket for that issue. This one is about layer changes and it was fixed.

**Comment by virdagreat147** [comment]
hey guys, i figured out a solution when i was having this issue, all you have to do is turn on "Max comb distance with no retract" and set it to like 0.001 mm, this makes it so it retracts on combing moves too, it might also help to use "extra prime amount" to compensate for the filament lost due to oozing.

enjoy! and feel free to ask questions
