### ISSUE TITLE
Closed object in spiral vase mode

### ISSUE THREAD

**Issue by cody82** [Ultimaker/Cura#2675]
Right now it does not seam possible to print a closed object in spiral mode.
Cura prints a bottom layer but no top layer.

It should have an option to print a top layer in spiral mode.

**Comment by smartavionics** [comment]
> It should have an option to print a top layer in spiral mode.

And how is it going to be able to do that? What support does the top have? You can't print onto thin air!

**Comment by cody82** [comment]
Of course it would not work on all objects, but in my case it should work.
See here:
![](https://abload.de/img/2017-10-2500_56_23-cucual3.png)
But I see your point that it is not trivial.

**Comment by smartavionics** [comment]
Even in your case it's not guaranteed to work well because, remember, the top layer is a spiral and so the z-height varies around the layer so if it tried to put a roof on that it wouldn't be easy to get a nice looking result.

All, in all, I think that although it would be nice to be able to do this, the effort in making it work would rather outweigh the benefit.

If I was printing the above model, I would just use non-spiral mode, one wall and hide the z-seam on one of the corners.

**Comment by ChrisTerBeke** [comment]
Vase mode is just not designed for situations like these, but rather for vases.. Pretty sure we're not gonna change anything in there.

**Comment by Ghostkeeper** [comment]
Spiralize Outer Contour doesn't mention the word "vase" though.

**Comment by ChrisTerBeke** [comment]
We can change the description maybe? IMO spiralize = vase mode :P
