### ISSUE TITLE
3.0.4. Cura per part settings infill

### ISSUE THREAD

**Issue by sierradays** [Ultimaker/Cura#2722]
Infill settings not working.  100% will fill, but anything less is not correct

**Comment by smartavionics** [comment]
Hi, could you please provide more info - screenshots? model? settings? Without that, it is impossible to understand your problem.

**Comment by sierradays** [comment]
Here is a view from the top, this is between two walls.  You can see the infill pattern doesnt fill the area or bridge to the next wall.  Infill Setting are 20% grid infill.

![image](https://user-images.githubusercontent.com/22430393/32396783-ed5cf07c-c0a3-11e7-9e00-6a0ceab92022.png)

**Comment by smartavionics** [comment]
Yes, that looks weird. Could you please post a link to the model or upload it so I can try slicing it myself.

**Comment by smartavionics** [comment]
Just a thought, make sure that gradual infill steps is set to 0. Maybe that is non-zero and doing something weird?

**Comment by smartavionics** [comment]
Also, in the above image, where is the bottom skin? The skirt is visible so you are displaying all of the layers but there's no skin under the weird infill.  Can you please show a similar image but this time use the layer view so that the various components (skin,  infill, etc.) are colour coded.

**Comment by Ghostkeeper** [comment]
When you set infill to 100% we automatically set the number of bottom skin layers to 999999. This is because it should have the same effect but prints faster, achieves better infill density and better quality wall adhesion. The downside is though that your preferred infill settings won't work any more then. A workaround is to set the infill to 101% (or the bottom layer count back to 5 or so).
