### ISSUE TITLE
3.0.4 adds projects to the existing one

### ISSUE THREAD

**Issue by thesec** [Ultimaker/Cura#2734]
Loading a new project file in 3.0.4, Mac OS, adds it to the current one.
Expected: Replace the current project.

**Comment by Vandrasc** [comment]
Hi @thesec, I am not able to reproduce.

When I load a new project, the open project pops up asking if I want to update the existing file or Create a new one, works as expected for me. Or the project will be updated or a new machine and project file will be created. 
![open project](https://user-images.githubusercontent.com/26549794/32432429-e717b9fa-c2d7-11e7-9335-d757f5330f70.png)

I also have the option to load the file as a project file or as a model
![openproject](https://user-images.githubusercontent.com/26549794/32432524-4229f182-c2d8-11e7-809d-df15968cc0b4.png)
When you choose to import as model, the model will be added to the current project (correct)

Silly question, but did you selected Import as models instead of Open as project?

**Comment by thesec** [comment]
Hmm, those screenshotted dialogs do not show to me ...
The way I open a project is: select "File" menu, "Open File(s)", select the 3mf project file.

**Comment by ChrisTerBeke** [comment]
You might have a preference enabled to automatically choose one of these behaviours. You can also set the preference to always give the dialog so you can choose.

**Comment by thesec** [comment]
Opening and saving files was set to alway import the model - thank you @ChrisTerBeke !
