### ISSUE TITLE
3.0.4 - One at a time and infill mesh

### ISSUE THREAD

**Issue by nicolinux** [Ultimaker/Cura#2736]
When the print mode "one at a time" is enabled, and one wants to define an object as an infill mesh, then Cura should ignore the "bounding box" of that infill mesh. Reason for that is that the bounding box of the infill mesh might be so big as that Cura will refuse to slice if it expands outside of the building plate. But since it is "just" an infill mesh, the bounding box should not be regarded in this case.

On the following screenshot you can see that I wanted to use a small box in order to reinforce one area of a frame temple. This is not possible here if the print mode "one at a time is selected".
![ot](https://user-images.githubusercontent.com/1069286/32414320-54ac896e-c224-11e7-9b47-d81cf45d514c.png)

**Comment by diegopradogesto** [comment]
I have checked and Cura says that is unable to slice because one of the models is outside the buildplate, but it's showing this message because the two models are overlapping, so the message is also incorrect.
![meshinfill](https://user-images.githubusercontent.com/15830521/32597494-3148b450-c537-11e7-977c-7f5cd6c89cd8.PNG)

Yes, this is something we need to take a look at. I wanted to suggest that you can create a group with the two models but I noticed that CuraEngine crashes.

**Comment by diegopradogesto** [comment]
Devs, take a look at CURA-4551
