### ISSUE TITLE
Collecting Data Prompt shown although disabled

### ISSUE THREAD

**Issue by thesec** [Ultimaker/Cura#2840]
I disabled the preference to "Send (anonymous) print information".
Yet I am nagged with the prompt "Collecting Data ... You can disable this ... Dismiss" every single time I start Cura 3.0.4 :/

Is it another setting that I am missing? Please fix, if not.

**Comment by ChrisTerBeke** [comment]
You'll have to click 'dismiss' instead of the 'x' in the top right corner.

**Comment by thesec** [comment]
The legal requirements would need the dialog to be modal then plus they'd require the hint where and how to opt out.

When the according preference is unset the dialog must no longer appear. Or you could rename 'preferences' to 'afterrences'? ;D

Either way ... it is imho a bug.

**Comment by Ghostkeeper** [comment]
I've made a fix that it doesn't display the message when the user disabled the setting without clicking on the message.

**Comment by Black6spdZ** [comment]
This problem STILL plagues 3.6.0! There is NO dismiss button, only "ALLOW".. what kind of trickery is being pulled here?

**Comment by maukcc** [comment]
Still showing up in 4.1

**Comment by Ghostkeeper** [comment]
> This problem STILL plagues 3.6.0! There is NO dismiss button, only "ALLOW".. what kind of trickery is being pulled here?

We've originally put a "no, thanks" message there but had to hide it under an additional click for higher-ups because they seem to think that more data is better and want to include this dark pattern here to stimulate more people to send data.

A couple of things are weird about this message right now:
* The "Allow" button doesn't do anything except prevent the message from appearing again. It doesn't enable the analytics when you've previously disabled it.
* The "X" button only hides the message. It doesn't disallow analytics sending.

For 4.1 we're redesigning the first-use screens so that you don't get a million pop-ups any more about firmware upgrades being available, connecting stuff, change log, etc. but just one wizard. This wizard includes analytics, so hopefully it'll work a lot more nicely in this regard. It's not yet merged into Master though: https://github.com/Ultimaker/Cura/pull/5449
