### ISSUE TITLE
Cura 2.7 and Linux Mint 18.2?

### ISSUE THREAD

**Issue by connmcd** [Ultimaker/Cura#2845]
I'm trying to use Cura 2.7 with Linuxmint 18.2 and the program loads up fine but I cannot get it to connect to the printer (Prusa i3 clone) with usb.  What else do I need on my system to make this happen?  I had been running cura on a older Win7 computer, but now have a faster Linux machine.  Unfortunately, I am new to linux....Any help would be appreciated!

**Comment by Ghostkeeper** [comment]
Something you could try is to start [Printrun](http://www.pronterface.com/), and see if that application can make a connection. If it makes a connection, the problem probably lies with Cura. Don't try to run Printrun at the same time as Cura though, because Cura doesn't check if the device is busy and two applications talking through the same USB connection results in noise.

One thing that I usually try is to open a terminal and type `ls /dev`. This gives a list of all devices in your computer. Then I plug in the USB cable and type `ls /dev` again. If there is now an extra item, it indicates that your computer found the printer.
