### ISSUE TITLE
Re-Slicing with "Open ..." Dialog

### ISSUE THREAD

**Issue by thesec** [Ultimaker/Cura#2899]
Whenever I select file/open... the current model is automatically being sliced again.
Without any setting having changed at that moment that should not happen.

**Comment by ChrisTerBeke** [comment]
Indeed. I think it also happens when you connect to a networked printer.

**Comment by smartavionics** [comment]
Hi @ChrisTerBeke , maybe related to the above issue, updating (aka saving) the current profile also triggers a reslice (well it would do if I had auto-slice enabled, you know what I mean).

**Comment by fieldOfView** [comment]
Add "saving a project" to the list...

**Comment by ChrisTerBeke** [comment]
Sounds like this needs a Jira ticket. My gut says it has to do with one or more of the many signals being thrown around in Python to which re-slice reacts.

**Comment by edugarci** [comment]
hola buenas noches,tengo un grave problema, se me a perdido la comunicación con mi impresora prusa i3
y lo e intentado casi todo sin lograr conectarme, no reconoce el puerto. haber si me podeis ayudar porfa

**Comment by Ghostkeeper** [comment]
I can't reproduce this. I can reproduce the bugs that a reslice happens when you save your profile or save a project file (we already had tickets for those). No reslice happens when you connect to a networked printer though, unless you sync the materials in the subsequent dialogue but then it's necessary. Also no reslice happens when I click on File -> Open File... until I actually load a new model, but then it's also necessary.

**Comment by Ghostkeeper** [comment]
Edugarci, your problem is a different one than what is reported here. I would like you to make a new issue.

Some hints I can give with your connection problem: Try making a connection with Pronterface first to see if it's Cura or your printer itself that is giving the problem.
