### ISSUE TITLE
Bug: Overlapping convex hulls

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Cura#294]
Expected: the shadows of objects signifying their convex hull cannot overlap due to the way collision detection is implemented.
Actual: overlap

![cura_overlapping_hulls](https://cloud.githubusercontent.com/assets/8895761/9488366/da9d67f0-4bd9-11e5-9015-b65d0c0e7fe3.png)

**Comment by nallath** [comment]
Seems to be caused by the bounding box intersection. The bounding box fits snugly over the object, whereas the convex hull is offset with a minkowsky hull (so it's sometimes larger).

**Comment by BagelOrb** [comment]
You're begging the question.
What's the reason the convex hull is offsetted and the bounding box is not?!

**Comment by nallath** [comment]
How is this begging the question?

**Comment by BagelOrb** [comment]
My question is on the convex hulls overlapping; your answer simply restates that the convex hulls are overlapping and gives the cause. You're not giving a reason.

What's the reason the convex hull is offsetted and the bounding box is not?

**Comment by nallath** [comment]
I am giving a reason. The reason is that the bounding boxes are not overlapping (which caused the intersection to be removed from the list to be checked, so it never intersected the hulls). I did not only re-state that they are overlapping. Even if I did, that is not begging the argument. 

To answer your second question; The convex hull states in what area other objects cannot be printed. The bounding box is there so we can see if the object can be printed on the build plate. I'm not 100% sure if that behaviour is correct, but that's how we use it.

**Comment by BagelOrb** [comment]
I still don't totally understand **why**. Many people confuse reasons with causes - no worries.

As I understand it now the convex hulls are supposed to have an overlap because the convex hull ensures non-overlapping models by enforcing that a model doesn't overlap with the convex hull, not by enforcing that the convex hulls of the models are non-overlapping.

**Comment by nallath** [comment]
No, convex hulls should never overlap. They had an overlap because the check never got to the point of checking the convex hulls (as it stopped at checking bounding box A with bounding box B).

**Comment by BagelOrb** [comment]
So this is a bug.
You say convex hulls should never overlap, but here they do.

**Comment by nallath** [comment]
Look at the commit and what i wrote. I explicitly stated that i already fixed this.

**Comment by BagelOrb** [comment]
Ohh ok. I'm sorry.
