### ISSUE TITLE
Missing detail

### ISSUE THREAD

**Issue by NovaDenied** [Ultimaker/Cura#2958]
Some detail in solid view is not showing up in layer mode and thus is not being printed on the model. The detail is there in cura 2.5 but not 3.0 or 3.1. Some detail thats there is thinner than on cura 2.5 as well.
![detail in solid](https://user-images.githubusercontent.com/34422333/33807718-0e8ddf14-dda9-11e7-9120-df2eb84b269f.png)
![missing detail in layers not printed](https://user-images.githubusercontent.com/34422333/33807719-0e9abdce-dda9-11e7-8d8e-44dd9d18ce06.png)

**Comment by NovaDenied** [comment]
The detail is in cura 2.5.
![cura 2 5 detail is there in layer view](https://user-images.githubusercontent.com/34422333/33807749-6372f7f8-dda9-11e7-9033-b85b1d4c97a4.png)

**Comment by Vandrasc** [comment]
Hi @NovaDenied, is the Print Thin Walls setting enabled? You can search for it while in the Custom tab in the search box. Also, it is possible to attach your model so we can have a look? 
Thank you!

**Comment by NovaDenied** [comment]
No it wasn't but it seems to be working now I dont understand what happened but I do know that cura crashed and then reset my settings and it worked since then. Must of been a glitch.

**Comment by ChrisTerBeke** [comment]
Maybe related to our 3.1 beta settings bug. After cleaning the settings folder it should then be solved indeed.

**Comment by NovaDenied** [comment]
how do i do that?

**Comment by Ghostkeeper** [comment]
What he meant is to basically reset Cura to factory defaults, removing all profiles and custom settings and such. You can do that by opening Cura and going to Help -> Show Configuration Folder. Then close Cura. Then delete the parent of that folder it brings you to (called `cura`).

Or less intrusive, delete only the changes that were made while using Cura 3.1 by deleting just the `3.1` folder. The glitch you saw could be caused by using the 3.1 beta that left the configuration in a broken state.
