### ISSUE TITLE
Reduce the shininess in shaders

### ISSUE THREAD

**Issue by dkingsjr** [Ultimaker/Cura#2962]
One thing I've noticed, is that there is a horrible light reflection effect going on in Cura. It is WORSE with the white theme. and gets a little better with the dark theme...however, i think it should be eliminated all together. Or at least we should have the option to turn it on and off as we see fit. I am not entirely sure why there is a need for a light reflection off the model loaded into Cura, but it makes seeing certain details horribly difficult to see, and is a little bit taking on the eyes.

**Comment by alekseisasin** [comment]
Maybe can You please send a print screen (highlight areas) of the area which in your opinion should be customized ?

**Comment by fieldOfView** [comment]
I think the request is to remove (or tone down) the specular highlight

**Comment by Ghostkeeper** [comment]
Sometimes it's just necessary to have a specular reflection in order to make out details on the surface. For instance, here is a wavy sort of surface without specular reflections ([this model](https://www.thingiverse.com/thing:2139138)):
![image](https://user-images.githubusercontent.com/2448634/34456383-bd5fbb98-ed94-11e7-81d9-999d6aa630c1.png)

So I am of the opinion that the specular reflection is useful and important even.

The white theme has the same specular reflection as the dark theme, so that could be placebo or only perceptual.

**Comment by ianpaschal** [comment]
Since this is not hard for the user to edit themselves and not really an issue with the software, I'm closing this.

**Comment by FrozenFold** [comment]
It would still be nice to have a setting within the program for people like me who don't know how they are expected to change it once in the file folder for the shaders.
