### ISSUE TITLE
Slicing simple cone model causes a lot of travels - optimization probably required

### ISSUE THREAD

**Issue by bipsendk** [Ultimaker/Cura#2967]
When slicing the attached model, a lot of travelling between printing is taking places on each layer - instead of just moving in circles towards the top.

Is there a way to optimize the slicing of this model ?

STL and output gcode attached 
[Hoved-2-gcode.zip](https://github.com/Ultimaker/Cura/files/1549098/Hoved-2-gcode.zip)

[Hoved-2.zip](https://github.com/Ultimaker/Cura/files/1549081/Hoved-2.zip)

**Comment by smartavionics** [comment]
Most of those travels are caused by the filling between the walls. Cura doesn't really make a good job of that so, personally, I would disable the filling (set fill gaps between walls to nowhere). The travels can be reduced further by setting a user specified z-seam position so that the seams on both the inner and outer cones are aligned. Finally, do enable optimize wall printing order as the optimizer does try to avoid travels where it can. Hope this helps.

**Comment by smartavionics** [comment]
![screenshot_2017-12-11_20-27-15](https://user-images.githubusercontent.com/585618/33852257-b41984d4-deb1-11e7-8955-efbe7f508141.png)
