### ISSUE TITLE
Coasting does not always replace the end of extrusion path with a travel path.

### ISSUE THREAD

**Issue by ChrisRiddell** [Ultimaker/Cura#2973]
Cura 3.1
Windows 10
Ultimaker2+

Something i noticed while placing with coasting with filament that's a little oozy was that coasting is not always replacing the end of an extrusion path with a travel path.

![coasting_from_outter](https://user-images.githubusercontent.com/2055566/33936078-25c4edce-e04e-11e7-8f60-c1f3c74d2fea.PNG)
1 you can see it's not doing coasting on the outer outline but is for 2 like I'd expect.

![coasting_from_outter_case2](https://user-images.githubusercontent.com/2055566/33936079-25f399da-e04e-11e7-906b-1d0c9b4d7503.PNG)
and this one you can see its not doing coasting at all before it moves off.

**Comment by Ghostkeeper** [comment]
I'm not able to reproduce this. All paths, the long ones and the short ones, seem to have gaps in there that get replaced by travel moves. Only when a line is very short, the Minimum Volume Before Coasting comes into play and prevents the coasting on that perimeter. But in your screenshot it looks like it's the longer path that gets no coasting rather than the shorter path.

Maybe it's specific to certain models? Could you share a model that reproduces this?

Looking closely at your second screenshot, it looks almost like the wall is broken into pieces over there. There seems to be two seams: One where the original "1" is pointing in the first screenshot, and one a little bit lower where you seen the travel moves in the second screenshot. Maybe then the Minimum Volume Before Coasting kicked in and prevented the coasting in that perimeter?

**Comment by ChrisRiddell** [comment]
Had anther play it seems to be related to travel movements that don't have a retraction (something to do with combing maybe?)
