### ISSUE TITLE
Open Cura 3.03 Projects with Cura 3.1 ? 

### ISSUE THREAD

**Issue by filipgoc** [Ultimaker/Cura#2997]
Hi, I know there are some issues related to the having installed 3.1 BETA, which I did, but now I am simply trying to open 3.03 projects with 3.1 and it is not working. No 3.1 BETA involved. Mac OS Sierra. 

Namely, 3.1 does not load/respect the 3.03 project's setting. 

Is there any known workaround/ fix?

It'd be a pain to try and redo all mu projects from scratch not knowing what transferred and what did not...

**Infill in 3.03: cubic**
![image](https://user-images.githubusercontent.com/16858474/34079187-b640abc2-e328-11e7-85f3-e17687a885ce.png)

And **infill in 3.1, same project: zig zag, different density...**
![image](https://user-images.githubusercontent.com/16858474/34079171-5337f3be-e328-11e7-81f5-3cc412f80324.png)

**Comment by Thisismydigitalself** [comment]
Consider yourself lucky. After i installed 3.1 beta my Cura is a complete mess.  i don't know what broke down but i do know i am in pain. I will not stop using Cura because I love it and the good guys are doing their utmost but I am counting the hours and minutes for next release as the only version i can run now is 3.1beta (no other 3.x version will run anymore) and all my projects needed to be redone and I don't want to think what if i could not reuse these with 3.2..

**Comment by filipgoc** [comment]
@Thisismydigitalself uff. sorry to hear that. I'm sure we'll get to the bottom of it sooner or later.

**Comment by Ghostkeeper** [comment]
I can't reproduce this. I created 2 projects using 3.0.4, one with the Ultimaker 2+ and one with the Ultimaker 3. Both set the Infill Pattern to Cubic. Then I closed 3.0.4, cleared my settings and loaded 3.1. I could open both projects and both of them would set the Infill Pattern properly to Cubic.

Maybe it would help to try your project file if you are at liberty to share it?

**Comment by filipgoc** [comment]
@Ghostkeeper thanks for checking. I'm attaching a project file made for IMADE3D JellyBOX and I have verified the issue does show up on my computer using this specific project file. 

- Sidenote, is the only difference between 3.03 and 3.04 the name (Cura vs Ultimaker Cura)? I created the projects with 3.03. 
- You also made me think about the printer definitions. Maybe the issue is the printer definitions do not match - if a project file is opened with a different printer (like custom), it does all sorts of unpredictable things.  Even though I did no change them in months...

[door handle.3mf.zip](https://github.com/Ultimaker/Cura/files/1603450/door.handle.3mf.zip)

![image](https://user-images.githubusercontent.com/16858474/34565633-dc67871c-f15b-11e7-8a4e-5603771998bd.png)
![image](https://user-images.githubusercontent.com/16858474/34565693-1bcb17f2-f15c-11e7-841d-fbdc364a92e0.png)

**Comment by Ghostkeeper** [comment]
I think I remember 3.0.4 had a fix for the signing of the MacOS build as well. But that's not relevant for Windows users.

Indeed your project file specifies that it should be cubic, but loading it into version 3.2 causes the zigzag pattern to be selected. Looks like a version upgrade problem between 3.0 and 3.1 due to that extruder train for single extrusion machines refactor we did. That should really have been tested better.

**Comment by filipgoc** [comment]
Thanks for looking into this @Ghostkeeper.

**Comment by fieldOfView** [comment]
snazzy logos you have there, @filipgoc

**Comment by filipgoc** [comment]
> snazzy logos

:-) Haha. It was the fastest and least cognitively taxing way to make sure I am actually opening the project files in the correct Cura versions as I was trying to prove that one of them has issues.

**Comment by Ghostkeeper** [comment]
Our testers report that it's fixed for 3.2 stable.
