### ISSUE TITLE
Print time estimate with .25 nozzle

### ISSUE THREAD

**Issue by tclancey** [Ultimaker/Cura#3007]
Print time estimates do not change with changes of print speed.
This may be the same/similar with different nozzles, I haven't tested.

**Comment by Ghostkeeper** [comment]
Can't reproduce this. I loaded an Ultimaker 3 with a 0.25mm nozzle with a 4cm cube.

Speed 30mm/s: 8h 32m time estimate.
Speed 55mm/s: 6h 42m time estimate.

Keep in mind that if you have a very small and detailed model, changing the print speed might have very little effect because it never reaches that speed due to the acceleration limits.
