### ISSUE TITLE
Print one at a time not possible with two extruders - UM3

### ISSUE THREAD

**Issue by nicolinux** [Ultimaker/Cura#3121]
One can not enable the setting Special Model -> Print on at a time. The setting tooltip informs the user that it is not compatible with two extruders. But it does not tell the user that it is overly cumbersome to go and edit the machine and set the extruder number to 1. This should be easier...

**Application Version**
Cura 3.1.0

**Platform**
Mac

**Steps to Reproduce**
Try to slice two objects on a UM3 and have them print one at a time.

**Actual Results**
Not possible.

**Expected results**
Possible... Cura should let me temporary set the number of extruders to 1 and then activate the print one at a time feature.

![screen shot 2018-01-11 at 16 02 29](https://user-images.githubusercontent.com/1069286/34832337-ee3b07e6-f6e9-11e7-8a44-6eff4cd69c4c.png)

**Comment by fieldOfView** [comment]
"It is not a bug, it is a feature"

This was done because Cura (generally speaking) has no idea what happens when the printer switches tools. For example in the case of the UM3 you are using, the printhead moves to a pre-defined position to switch extruders. There could be a previously printed model in the way, which could cause a collision between that print and the printhead.

That's why One at a time printing had to be disabled for multi-extrusion printers.

**Comment by nicolinux** [comment]
Ok, I understand. I am not arguing about that, but I think it should be easier for the user to perform "one at a time prints" with a dual extrusion printer even if that means that the printer has to be set to one extruder.

**Comment by ChrisTerBeke** [comment]
We're working on a "single extrusion mode for UM3" feature (or generally: disable extruders), which should make it easier to enable this feature from the UI.

**Comment by ChrisTerBeke** [comment]
Related: https://github.com/Ultimaker/Cura/issues/1671.

**Comment by yankee14** [comment]
What is the status of this? I think it was solved in #1671.

**Comment by ChrisTerBeke** [comment]
It was indeed
