### ISSUE TITLE
rotate option

### ISSUE THREAD

**Issue by espadan3d** [Ultimaker/Cura#3272]
Hi
Thanks a lot for provide Cura.
I use of Cura 2.6(64bit) in Windows 10, when I install 3 version or higher don’t show rotation icon. 
Please help me
Regards
![1](https://user-images.githubusercontent.com/36302436/36032570-ad00d6d4-0dc3-11e8-9f37-73833476f102.png)

**Comment by ianpaschal** [comment]
Can you post some log information? My guess is that the Rotation Tool, which is a plugin, is not being correctly loaded. This will throw some errors in the log file.

**Comment by espadan3d** [comment]
Hi
Thanks 
I check it not active in plugin
I active it and close, open program solved.
In Cura One can print a piece with several layers of thickness(for example 0-5 mm height by 0.3mm and 5-10 mm by 0.3mm layer?
![2](https://user-images.githubusercontent.com/36302436/36034881-b5283a3a-0dca-11e8-9920-b7cba4f99a89.png)

**Comment by ianpaschal** [comment]
Great! Glad that solved it!

> In Cura One can print a piece with several layers of thickness(for example 0-5 mm height by 0.3mm and 5-10 mm by 0.3mm layer?

In general, please open separate tickets for separate questions, but since it's a short one:

Yes. There is an experimental feature called adaptive layer height. If you are using version 3.2, open preferences, go to settings, and scroll all the way down. There you can check the adaptive layer height boxes and you'll see those options in the sidebar.

**Comment by espadan3d** [comment]
Thanks a lot
