### ISSUE TITLE
master: Option missing to install plugins manually

### ISSUE THREAD

**Issue by thopiekar** [Ultimaker/Cura#3282]
Just wanted to install a plugin manually via preferences, but found this:

![image](https://user-images.githubusercontent.com/1847437/36065189-953a0212-0e97-11e8-9402-e092b7983bc7.png)

Not only that the text is not readable, when the system theme is black, there is also no possibility to add plugins manually anymore. Seriously, how do you think should it be possible to distribute testing builds of plugins in the future like this?

![image](https://user-images.githubusercontent.com/1847437/36065184-7835ca48-0e97-11e8-9b4b-d97a3477c42c.png)

Or has the decision really been made to prevent users to install plugins from 3rd-party locations?

**Comment by fieldOfView** [comment]
See the discussion here; https://github.com/Ultimaker/Cura/pull/3203#issuecomment-363185975

@ianpaschal: The text color in the first screenshot is because of the use of Text instead of Label. Label is defined as Text with a preset color (and some other properties) that defaults to the system text:
https://github.com/pyqt/python-qt5/blob/master/PyQt5/qml/QtQuick/Controls/Label.qml#L79

**Comment by thopiekar** [comment]
@fieldOfView Thank you for pointing out this discussion :+1:

**Comment by Vandrasc** [comment]
Fix included in the next release.
