### ISSUE TITLE
Cura generates useless support

### ISSUE THREAD

**Issue by JulienDevillers** [Ultimaker/Cura#3308]
**Application Version**
3.1

**Platform**
WIN7 SP1

**Qt**
 using the version from Ultimaker's website

**PyQt**
 using the version from Ultimaker's website

**Display Driver**

**Steps to Reproduce**
import this file : 
[CC_porte_tringle - 2.L.curaproject.3mf.zip](https://github.com/Ultimaker/Cura/files/1723134/CC_porte_tringle.-.2.L.curaproject.3mf.zip)

**Actual Results**
Cura generates useless support like here:

![cura](https://user-images.githubusercontent.com/11025667/36193689-247fb7e2-1167-11e8-82e7-73e8bb9673cc.png)

**Expected results**

**Additional Information**

**Comment by ianpaschal** [comment]
Can you provide more information about how you're getting this to generate? Are you using PVA?

**Comment by smartavionics** [comment]
It's related to the support towers setting. Turn off the towers and they should go away.

**Comment by JulienDevillers** [comment]
@ianpaschal :
- To get this:  import the 3mf file. What other info do you need?
- What is PVA?

@smartavionics : you're right.

**Comment by ChrisRiddell** [comment]
Yeah its related to support towers like @smartavionics said,

To be honest this has come up a number of times now here and on the forums maybe it should not be on by default.

**Comment by ianpaschal** [comment]
@JulienDevillers Yes, it's the support towers. PVA is a kind of filament.

@ChrisRiddell I'm not a big fan of them either but I believe they're on by default because the materials department at Ultimaker says they produce better prints when using PVA, which is why I asked @JulienDevillers if he was using PVA which would change this from unexpected to expected behavior.
