### ISSUE TITLE
[3.2.0] Z-Hop not working

### ISSUE THREAD

**Issue by Thisismydigitalself** [Ultimaker/Cura#3329]
My Cura 3.2 doesn't perform Z-Hop. 
How can I check what can cause this?

**Comment by ChrisTerBeke** [comment]
My z-hops work fine...

Please share your user settings, without that there's no way to debug for the developers.

**Comment by Thisismydigitalself** [comment]
Here you go (change .txt to .3mf)
[L_TOOTH v5.curaproject.txt](https://github.com/Ultimaker/Cura/files/1729735/L_TOOTH.v5.curaproject.txt)

**Comment by smartavionics** [comment]
Turn off "z hop only over printed parts".

**Comment by smartavionics** [comment]
BTW, when I have a model like yours with horizontal holes, I put a thin web across the hole so that the regions either side of the hole are always connected by outer walls. Here's a grotty image that shows where the webs are positioned. Once the print is finished you have to drill out the holes but that only takes a few moments. I find that the wall quality is improved by doing this.
![screenshot_2018-02-18_17-36-28-webs](https://user-images.githubusercontent.com/585618/36354921-51dfcc4e-14d3-11e8-88b8-4b9274fc1349.png)

**Comment by Thisismydigitalself** [comment]
Turn off "z hop only over printed parts" ?  
This is counter intuitive. I left this feature checked few weeks back (and forgot about it) thinking no need to hop outside the part, what am i missing?.. :)

Can you please explain what do you mean by "thin web" across the holes?


Thx.

**Comment by smartavionics** [comment]
The webs are simply a vertical wall that completely blanks the hole. I normally position them on the centre line of the holes (the orange lines in the image above) but sometimes I position the web flush with one of the part's side walls. I normally make the web 2 x the outer wall line width thick so that it is printed as part of the outer wall. The point is that the outer wall of the hole part is printed in one with no retracts/travels.

**Comment by Thisismydigitalself** [comment]
> The point is that the outer wall of the hole part is printed in one with no retracts/travels.
Understood, good idea.

**Comment by smartavionics** [comment]
Here's an example, there are 4 horizontal holes and each has a web on its centreline:

![screenshot_2018-02-18_20-12-12](https://user-images.githubusercontent.com/585618/36356294-1df02004-14e8-11e8-95a2-f50633d62b96.png)

See how the outer wall for the whole part is printed in one.

**Comment by Thisismydigitalself** [comment]
Yes, perfectly understood.

**Comment by Thisismydigitalself** [comment]
After unchecking "Z hop only over printed parts" Zhop works again.
Please explain the reasoning behind the description as it is counterintuitive for me.

Thx.

**Comment by smartavionics** [comment]
>  Please explain the reasoning behind the description as it is counterintuitive for me.

It's not my work, I don't know what they intended to achieve with that, sorry.

**Comment by Thisismydigitalself** [comment]
![tooth v8](https://user-images.githubusercontent.com/30949968/36425412-5f7ce2e2-164f-11e8-8118-0f034e2b78d1.png)

**Comment by smartavionics** [comment]
Looking good although are the webs too thin? They have to be 2 outer wall thicknesses wide.

**Comment by Thisismydigitalself** [comment]
![ice_screenshot_20180220-153907](https://user-images.githubusercontent.com/30949968/36426898-3e51cd94-1654-11e8-975d-5e0a3bf59581.png)

**Comment by smartavionics** [comment]
That's looks good. Have you tried printing it?

**Comment by Thisismydigitalself** [comment]
will print it later today. i placed the web closer to one end for either closer drill, or for using the longer side for making sure the drill bit will have more bore to straiten itself before it hits the web. we'll see.

**Comment by ianpaschal** [comment]
@Thisismydigitalself Any luck? Can we close this?

**Comment by Thisismydigitalself** [comment]
You can close this issue on one condition:  Please tell me why one needs to uncheck "Z hop only over printed parts" for things to work as expected. this somewhat counterintuitive description was what got me me confused in the first place. please consider better description :)

**Comment by ianpaschal** [comment]
I can't really defend this kind of thing as I've only been working at Ultimaker 10 weeks. I could dig out the commit and figure out who named the setting but I think a better option is to tag @LukeChen-Ultimaker. Luke and I both did the same UX masters program but he's been at Ultimaker far longer than I have so he may know better about why it is the way it is. He might also feel like investigating the issue from a UX perspective. Not sure. I am going to go ahead and close the issue because we will consider it, but I have to defer to my seniors regarding what we do about it.

**Comment by Ghostkeeper** [comment]
> After unchecking "Z hop only over printed parts" Zhop works again. Please explain the reasoning behind the description as it is counterintuitive for me.

As it seems nobody was able to explain this so far, I think we need to clarify this a lot better then!

The point of this setting is that if you're performing a z-hop from A to B but the path between A and B is completely devoid of any obstacles, then the hop is useless. You wouldn't hit anything in the path to B anyway. So if you're ending at A in an outer wall and starting at B in an outer wall, then you might as well not perform a Z hop and save some time and wear on the Z axis.
