### ISSUE TITLE
Individual mesh settings + adaptive layer heights = sad cura

### ISSUE THREAD

**Issue by JJJpnt** [Ultimaker/Cura#3401]
**Application Version**
3.2.1

**Platform**
Windows

**Display Driver**
NVidia's latest on a Gtx970

**Steps to Reproduce**
Slice with two meshes, one main and another inside of with mesh settings it to define a stronger infill zone. Add smooth layer height, press slice. 

**Actual Results**
Curaengine's stomach seems not to handle that mix and does an indigestion. Apparently tries to makes walls from the origin seeing the layer view, got a normal 1st layer, the second one is showing red wall lines from the origin to various places, noteworthy to say that the mesh that does change the infill isn't even contained in that layer. 

**Expected results**
Get a good slice of it ;)

**Additional Information**
Ok this is new and experimental, I just hope this information can help you :)
![screenshot20180226_080233](https://user-images.githubusercontent.com/30186166/36657813-4cae5a50-1ace-11e8-8bbe-aa80b8788db2.jpg)

**Comment by ianpaschal** [comment]
Thanks for reporting the bug!

Adaptive layers (that's what you mean right?) has a lot of limitations still. One of these is that it doesn't handle multiple objects very well, especially not using per-object settings.

This is something we're currently discussing, but it may involve saying for the time being that adaptive layers should just be used one object at a time.

We'll keep you posted.

**Comment by ChrisRiddell** [comment]
I understand the Adaptive layers not supporting multi models because each model would not really want the same layer heights. 

But I hope Ultimaker will keep the mesh type models in mind as its good for doing custom infill and etc.

**Comment by ianpaschal** [comment]
Ideally yes, this would be possible, but we've recently put another issue related to adaptive layers on the back-burner for similar reasons: it would require re-writing a _big_ part of Cura Engine. Since it's kind of an edge case using an experimental feature I don't imagine we'll get around to it any time soon.

I will discuss it with the Cura product owner and let you know if this is something we will put into the planning or leave for the time being.

**Comment by BagelOrb** [comment]
For finding this issue later: "adaptive layers" "variable layer height"

**Comment by Ghostkeeper** [comment]
I can't reproduce this issue. It seems to work fine.
![screenshot from 2018-03-16 12-41-28](https://user-images.githubusercontent.com/2448634/37518896-65cb7b10-2917-11e8-8c02-b8bcbba00117.png)

As far as I'm concerned, adaptive layers should just work with multiple models since it's required for dual extrusion and because it should also work with a single model that has multiple parts.

**Comment by ianpaschal** [comment]
Needs info for 2+ months and but went cold.
