### ISSUE TITLE
How to go back to 2.7 from 3.2

### ISSUE THREAD

**Issue by JJ460** [Ultimaker/Cura#3433]
**Application Version**

**Platform**

**Qt**

**PyQt**

**Display Driver**

**Steps to Reproduce**

**Actual Results**

**Expected results**

**Additional Information**

**Comment by JJ460** [comment]
2.7 is working ok but I would like to try the new 3.+ features, However, I want to be able to go back to 2.7 if needed.  There are numerous discussions about the issues in the new releases, but no discussion on returning to the earlier version.  Is it possible to make a clean return after files are deleted.  Is this process documented somewhere?
tx

**Comment by ianpaschal** [comment]
It's totally possible and pretty easy but we need more info from you (I see you ignored the template). Please fill that out if you'd like your question answered.

**Comment by JJ460** [comment]
OK, where is the template. when I sign in there is a "profile" but no "template" option.

Tx   JJ


________________________________

**Comment by ianpaschal** [comment]
The template is the first post in this thread with bold text. When you make a new issue that text comes pre-loaded so you can write in under the headings what's going wrong, how to recreate the problem, etc.

As far as your question though you can just install 3.2 from [the Ultimaker website](https://ultimaker.com/en/products/cura-software/list). For version 3.x, each version gets its own folder in your applications data (location depends on what operating system you use). Since you're coming from 2.7 though it will be a totally different folder within Program Files (or whatever) because we renamed it from "Cura" to "Ultimaker Cura". So you can just install 3.2.1 and then uninstall it later and your installation of Cura 2.7 won't be changed.
