### ISSUE TITLE
[3.2.1]  skirt line count not the same on small models than on bigger models

### ISSUE THREAD

**Issue by vernieg** [Ultimaker/Cura#3473]
[3.2.1]  skirt line count not the same on small models than on bigger models

**Application Version**
3.2.1

**Platform**
Linuxmint 8.3

**Printer**
Anycubic i3 Mega

**Steps to Reproduce**
Load the model, smaller than 20mm square. Enable skirt, line count 1.

**Actual Results**
Five lines is shown undler Layer view.

**Expected results**
One line should be shown like when loading larger models.

**Additional Information**
Link is provided for the sample model file and screenshot is attached.

https://drive.google.com/open?id=1QN26XuPJfZyofhxn0TstrwMuW_dyH5q_

![skirt](https://user-images.githubusercontent.com/37242799/37253637-672ca9c6-256f-11e8-9c4a-8d7b30953c0b.png)

**Comment by fieldOfView** [comment]
This is by design. A skirt is mainly intended to make sure the nozzle is primed. With a small object, it could be that not enough material is extruded and the extruder does not get primed sufficiently.

See the setting “Skirt/brim minimal length” to adjust the minimal amount of material that is extruded for the skirt.

**Comment by vernieg** [comment]
Thank you.
