### ISSUE TITLE
[3.2.1] Bigger layer height spent more filament (!)

### ISSUE THREAD

**Issue by mtmello2003** [Ultimaker/Cura#3475]
Win10 x64

It doesn´t make sense for me:  When I set layer height to 0.2 (for example), I gave xx meters and xx grammar of filament needed to print but if I increase the layer to 0.3, the ammount will increase too...

Bigger layer will generate less total layer needed to print the item then, will consume less filament.

![lay030](https://user-images.githubusercontent.com/15361590/37256420-3e19bed8-2539-11e8-9ca0-6ee53269679c.png)

![lzy020](https://user-images.githubusercontent.com/15361590/37256421-3e3c6e9c-2539-11e8-9658-51f79d4f4b46.png)

**Comment by fieldOfView** [comment]
> Bigger layer will generate less total layer needed to print the item then, will consume less filament.

No, because each of the thicker layers will extrude more material than the thinner layers. With all other parameters (such as line width) set to the same value, the total amount of material for the print should be in the same ballpark. The brim is going to take more material to print with a bigger layer height though.

**Comment by ianpaschal** [comment]
Yup, thanks @fieldOfView. @mtmello2003: It may seem strange but is expected.

**Comment by ChrisTerBeke** [comment]
Doesn't seem like a bug, closing.
