### ISSUE TITLE
font problems on Mac OS High Sierra 10.13.3

### ISSUE THREAD

**Issue by aupilot** [Ultimaker/Cura#3495]
![screen shot 2018-03-14 at 18 58 18](https://user-images.githubusercontent.com/13015685/37449276-633efa0e-2875-11e8-958c-37841d2d6955.png)

**Comment by fieldOfView** [comment]
See #3277

**Comment by aupilot** [comment]
thanks. Is there a binary with these fixes available?

**Comment by ianpaschal** [comment]
There's not. The download links in those threads were mainly just meant for testing. We didn't really want to distribute that because it makes a headache down the road when we say, "What version are you running," and a user says, "Uh, something I downloaded from a GitHub issue thread."

But since we know @fieldOfView's fixes work and they're incorporated into our development versions, they'll be in 3.3 Beta in about 2 weeks.
