### ISSUE TITLE
change nozzle diameter does not change profiles

### ISSUE THREAD

**Issue by GentleRV** [Ultimaker/Cura#3511]
**Application Version**
3.2.1

**Platform**

**Qt**

**PyQt**

**Display Driver**

**Printer**
Prusa I3MK2

**Steps to Reproduce**
change nozzle diameter in machine setting

**Actual Results**
nothing

**Expected results**
minimum layer and all wall thicknesses must be adjusted to a multiple of the nozzle diameter above a minimum thickness

**Additional Information**

**Comment by diegopradogesto** [comment]
I have checked and you are right, I could reproduce it. However I also checked in the master version and it works, so it is fixed in the next version. You can see it in the snapshot:
![image](https://user-images.githubusercontent.com/15830521/37643429-cbf75a1a-2c20-11e8-8b4b-16b8472f55e9.png)

Next week we are releasing a new beta version, so please check again then.
