### ISSUE TITLE
Prime tower infill percentage

### ISSUE THREAD

**Issue by mtmello2003** [Ultimaker/Cura#3550]
Hello,

There is the condition that layer after layer, wont be exxtruder change but CURA still filling the prime tower with the same extruder (filament color) using the "prime tower minimum volume" (normally set to full - solid tower).

In that case, the better way is cura use a new parameter like: "prime tower infill %"

Will save a lot of filament and time because if do not have extruder change, do not need to fullfill the tower using the minimum volume...

thanks

**Comment by Ghostkeeper** [comment]
It's probably fine to use the normal infill density of the appropriate extruder for this.

**Comment by sjoerdtimmer** [comment]
I would love this too as my 2-in-1-out setup requires a large prime tower it would soothe the pain a little if the prime tower layers that don't actually change color would be printed like infill.
@Ghostkeeper, are you working on this?
If not I will try to implement this myself.

**Comment by ianpaschal** [comment]
For reference: JIRA CURA-5248

**Comment by Ghostkeeper** [comment]
I'm currently working on a new strategy for the prime tower that doesn't alternate the layers any more but prints one of the extruders inside the other, and causes the outer extruder to always print. This sort of invalidates this issue since the prime tower can be made much thinner because the adhesion is better.

I think it will be unnecessary.

For a demo you can try out the feature_prime_tower_shells branch on CuraEngine.

**Comment by Ghostkeeper** [comment]
It is no longer necessary because the prime tower circles are now printed next to each other, so they can have different thicknesses. They no longer need to have the same thickness because they are not stacked on top of each other. So instead of adjusting the infill rate, you can simply adjust the thickness.
