### ISSUE TITLE
Cura 3.3B- First impressions

### ISSUE THREAD

**Issue by Thisismydigitalself** [Ultimaker/Cura#3577]
3.3B First Impressions:

(-) Only Half of my profiles were copied to 3.3.
(-) Printer's start/end codes are completely different
(-) Printer's settings are different.
(-) LineType view much more "noisy" than in 3.2.1 (EDIT: Just noticed this is a BUG - when setting 0.1 layer and slicing - it reverts back to 0.2 - and that's probably why i see as bad / noisy outcome.

(+) Printer remembers 0.4 nozzle.

**Comment by ianpaschal** [comment]
We really appreciate your feedback, especially since you're an active member around here.

But, that being said, could you please open actual issues about these things with examples and detailed info? Otherwise there's not really anything we can do with the information.

I'm going to close this because it's too hard to use the issue system when it's several different topics/issues all mashed into one.

**Comment by Thisismydigitalself** [comment]
sure thing. its just too many issues surfaced wth 3.3b including crash which i havnt included so i just dumpped my first impressions. as i am on the road i will try to manage issues the proper way soon.
