### ISSUE TITLE
Combing in any mode will create travel move over holes in parts

### ISSUE THREAD

**Issue by Miranio** [Ultimaker/Cura#3645]
**Application Version**
3.2.1

**Platform**
Windows 7

**Printer**
Anet A8 highly modified

**Steps to Reproduce**
Use part with hole in it, multiply it and prepare the print. You'll notice travel move over those holes as if cura consider them as printed area. They were printed area before right, but on the current layer they aren't so travel move should avoid them.

**Actual Results**
![image](https://user-images.githubusercontent.com/18230982/38557519-4560fa48-3c9b-11e8-9aa1-18a7b10021d1.png)

![image](https://user-images.githubusercontent.com/18230982/38557504-3788b5c8-3c9b-11e8-92d7-ef79a68f5933.png)

**Expected results**
The nozzle should stay over printed area of the actual layer being printed and not over printed area 100 layers before. The layer should avoid part also once it exited one part and enter the next one right where print should begin. Right now it's travelling in a straight line not avoiding part at all.

**Comment by BagelOrb** [comment]
These prints look rather thin. Maybe they are too thin to comb on the inside.

However they should avoid the parts in any case, so that could be a bug.

So you have the Hop settings enabled?

**Comment by Miranio** [comment]
Actually they are 1mm thick walls at the top section and I print with a 0.4mm nozzle, so there is enough room to comb inside

That was a behavior I noticed on other prints but those one create some issue with inside travels.

Yes z-hop is enabled.

**Comment by BagelOrb** [comment]
Yeah. Sounds reasonable.

Now that I think about it I don't really see why we automatically disabled
combing for z hops.

This should be an easy fix. It's just removing an artificial restriction,
if I remember correctly.

**Comment by BagelOrb** [comment]
Come to think of it it might be not that easy.

Changing this might change the Z hop behavior when the nozzle has to print some material which is totally surrounded by material of the other extruder. The functionality of Only Z Hop When Stuck would become different.

**Comment by Ghostkeeper** [comment]
We've recently made some adjustments to combing for Cura 3.4 that could make it successfully comb in thin objects like these.

> Now that I think about it I don't really see why we automatically disabled combing for z hops.

The idea was that it would no longer be necessary to z-hop if you don't cross the walls. We didn't think of the problem where a nozzle would scrape a small object off the build plate by going over infill without hop.

A second argument still holds though: If you z-hop, combing should no longer be necessary. If you're in mid-air it doesn't make sense to walk through a maze of walls which are way below your nozzle. I still hold by that. After the z-hop it should land inside your model (infill if possible), so there should be no stringing going inside either. So I hope that, since stringing going in is not a problem, a solution to your issue would be to only use z-hop.

Does it properly land in the middle of your model? Maybe if you increase the z-hop height a bit? We use 2mm by default in Ultimaker's profiles iirc.

**Comment by nallath** [comment]
Since there hasn't been any response for the pas 10 months or so, I'm going to assume that the fixes in 3.4 resolved it.
