### ISSUE TITLE
cura won't slice

### ISSUE THREAD

**Issue by seralkis** [Ultimaker/Cura#3678]
hello, I need help cura won't slice even when switched off antivirus and firewall
[stderr.log](https://github.com/Ultimaker/Cura/files/1916697/stderr.log)

[edit]
it seems that it is not able to prepare any project that does not completely touching the build plate
for example:

[1.zip](https://github.com/Ultimaker/Cura/files/1917351/1.zip)

**Comment by seralkis** [comment]
[curaproject.zip](https://github.com/Ultimaker/Cura/files/1920827/curaproject.zip)

**Comment by diegopradogesto** [comment]
It slices fine in Cura 3.2 and Cura 3.3. I didn't check any other versions. 
![image](https://user-images.githubusercontent.com/15830521/38917208-50b702f2-42ea-11e8-9ddf-186d9e4eea4b.png)
Maybe try to start with a clean install by removing the configuration folder located in:
- C:\Users\\<your username>\AppData\Roaming\cura\<Cura version> (Windows)
- $USER/Library/Application Support/cura/<Cura version> (OSX)
- $USER/.local/share/cura/<Cura version> (Ubuntu/Linux)
NOTE: Removing this will delete your printers and custom profiles. You can backup your data first.

**Comment by seralkis** [comment]
unfortunately it will not help, I've already done it (repeatedly) before writing on this forum

**Comment by ianpaschal** [comment]
Please fill out the issue template, especially including, based on Diego's experiments, your Cura version. Might be that we already fixed the issue if you are running a version older than 3.2.

**Comment by ianpaschal** [comment]
Closing because author has not filled out the template with info required to debug.

**Comment by Ghostkeeper** [comment]
Reading the log indicates that the user is getting an encoding error when CuraEngine outputs a weird character byte to the log (`\xC0`). This indicates that we may be outputting CuraEngine's log in a different encoding than how it's interpreted on the front-end's side. Only we currently don't specify `-fexec_charset` so it should default to UTF-8, which is how it's interpreted in the front-end. So that seems to be working fine.

For now I've made the front-end more robust against these faulty encodings from the back-end: https://github.com/Ultimaker/Uranium/commit/340c586dd67328e1560a261a96fdbf6acfc27866

It should not break on this anyway.
