### ISSUE TITLE
[3.3.1] Cannot add custom material

### ISSUE THREAD

**Issue by modem7** [Ultimaker/Cura#3766]
Version 3.3.1

Windows 7 x64

Wanhao i3 2.1

When trying to add custom materials, an error occurs when changing diameter, regardless what the custom printer is set as.

![1 75](https://user-images.githubusercontent.com/4349962/39539267-14df470a-4e37-11e8-90e1-3ca998226dfe.JPG)

![1](https://user-images.githubusercontent.com/4349962/39539274-1904acf8-4e37-11e8-821a-0c9568c8943f.JPG)
![2](https://user-images.githubusercontent.com/4349962/39539275-1925bcb8-4e37-11e8-9947-d162ca853946.JPG)

Also, unable to import materials, which means I cannot follow recommendations by @ChrisTerBeke on #3734 

![3](https://user-images.githubusercontent.com/4349962/39539388-5e51cd72-4e37-11e8-98b8-4a07457bb646.JPG)
![4](https://user-images.githubusercontent.com/4349962/39539389-5e801bbe-4e37-11e8-97e5-f92d47339e07.JPG)

**Comment by diegopradogesto** [comment]
If you create a material with 1.75mm diameter but the selected printer is configured to use 2.85mm filament, then the material is filtered out, that's why we show the message. If you switch to a printer that uses 1.75mm filament, then your material will be there.
Be sure your printer has the same setting in Settings>Printers>Machine Settings and then in the Extruder tab, take a look at the compatible material diameter.

**Comment by modem7** [comment]
Please see the screenshots in the original post.

It shows the printer extruder size set to 1.75.

**Comment by diegopradogesto** [comment]
Mmmmm, ok sorry. I will try to reproduce it.

**Comment by modem7** [comment]
Just in case it was values in custom printer:

200x200x180 w/ heated bed. No further changes at this time

**Comment by diegopradogesto** [comment]
I used your user data (the one that you posted on the other thread) and I'm able to create new materials and duplicate them.
Can you please try to do it with a clean install (removing your data folder - make a backup just in case). If it still doesn't work, can you please save a project file (File>Save as project) (even without any model in the buildplate) that allow us to get your current configuration.

**Comment by modem7** [comment]
Clean install resolved. 

Where would previous printer settings from old versions be stored? I can't seem to find them!

Tried machine_instances but nothing in there for full printer settings

**Comment by Ghostkeeper** [comment]
The old versions are in a folder next to it. For you on Windows that would be:

    C:\Users\modem7\AppData\cura
    | - <some log files are here>
    |-3.2
    |  |- <your configuration from the last time you used 3.2>
    |-3.3
    |  |- <your current configuration in 3.3>

**Comment by RichyT** [comment]
Have the same issue, Curea 3.6.0 with a custom printer. I would suggest that reinstalling the software is not a sufficient fix (only a work-around) considering this occurred with a clean install.

**Comment by ttait-vantim** [comment]
Fresh install on 3.6.0 on new PC and couldn't see any imports either... then I checked the extruder and it was set to 2.85mm for 1.75mm machine. Stranges as this was the same custom JSON for the Craftbot+ I've been using since 3.2.  I changed the extruder daimeter in the GUI and now all is good, but I can't find where that change was stored...
