### ISSUE TITLE
[3.3.1] Can't change infill %

### ISSUE THREAD

**Issue by fernx** [Ultimaker/Cura#3771]
**Application Version**
3.3.1

**Platform**
MAC OS

**Printer**
Anet

**Steps to Reproduce**
since install

**Actual Results**
Infill lock at 20%
![screen shot 2018-05-03 at 2 55 05 pm](https://user-images.githubusercontent.com/20249399/39596993-0beb7726-4ee2-11e8-99c2-4763b657a0bd.png)

**Expected results**

**Additional Information**

**Comment by Vandrasc** [comment]
Hi @fernx, it is intended behavior that when the children settings have been customized than the parent is affected and becomes "disabled", greyed out. I agree that it is not very clear, we are working at that :) 
You can first reset the Infill Line Distance and adjust the Infill density to the desired value and then adjust the Infill Line Distance.
It is also possible to change the infill from the Recommended tab but we currently have a bug in there where the Infill slider has no effect if infill line distance is overridden, Devs CURA-5324

**Comment by Vandrasc** [comment]
See #1034

**Comment by Ghostkeeper** [comment]
The bug with the Recommended tab is different. I've made a fix for that just now.

This is expected behaviour so it's a UX issue. Previously I had proposed a solution for this sort of case where you could select the unit for the setting to use. You would then just have one setting, Infill Density, and you'd have the option of filling this in as percentage or as distance between the lines. Or, a better example, the Brim Width setting as mm or in number of lines. This suggestion was denied though.

Maybe our UX people can take a look at it.
