### ISSUE TITLE
Cura adds M82 to the end of my gcode files.

### ISSUE THREAD

**Issue by amedsoprano** [Ultimaker/Cura#3822]
at the en of my endscript cura always adds an `M82` to set the E to absolute extrusion, so when i go and print the next file it does crazy stuff. (yes, i print in relative)

**Comment by smartavionics** [comment]
Yes, the Cura devs demanded that at the end of the print, it resets the absolute/relative extrusion mode back to "normal". They considered all gcode flavours except RepRap to normally use absolute extrusion. I said at the time that this was a mistake but they had their way. Sorry, it's a feature (intended bug). So the only way around this bug is to choose RepRap flavour gcode but that may not be compatible with your firmware.

**Comment by fieldOfView** [comment]
If the only (?) problem is that the next print "does crazy stuff", couldn't you add M83 to the start gcode as a workaround?

**Comment by smartavionics** [comment]
But what happens when the OP is also using gcode produced by other slicers that don't have this bizarre behaviour?

**Comment by fieldOfView** [comment]
OP could also add the M83 there. I said its a workaround, not a fix.

**Comment by fieldOfView** [comment]
A postprocessing script to remove the offending M82 could also work (could be as simple as using the built-in search/replace to replace any ```M82``` with ```;M82```). Still a workaround, not a fix, but at least postprocessing scripts now persist between sessions.

**Comment by smartavionics** [comment]
Good thinking, that could be a usable workaround.

**Comment by amedsoprano** [comment]
Yep I added M83 to the start script, but it sure is a workarround

**Comment by jackha** [comment]
Depending on the setting "relative_extrusion" in the printer definition, Cura will put either M82 or M83 in the gcode. Hope this helps.
