### ISSUE TITLE
[3.3.1] Cura Connect Monitor does not refresh on Chrome

### ISSUE THREAD

**Issue by StilTeg** [Ultimaker/Cura#3879]
**Application Version** 3.3.1

**Platform** Windows 10 - Chrome Version 66.0.3359.181 (Build officiel) (64 bits)

**Printer** Ultimaker 3 Extended

**Steps to Reproduce**

**Actual Results**

**Expected results** Current print displayed

**Additional Information**

Whatever I print, before the print start, I have it in the queue, nor problem, but it never moves to the print in progress. The camera still shows real time.
I tried removing cookies from the local site, without success. It still displays that it wants me to remove that old print
[
![curabug](https://user-images.githubusercontent.com/39877228/40886129-15579704-6733-11e8-926b-cdd8e900e024.JPG)
](url)

**Comment by ChrisTerBeke** [comment]
Unfortunately we don't give support for Cura Connect via this repository. Please check the Ultimaker forum.

That being said, I'm familiar with this bug and it will be fixed in the next release. Until then, the only thing that can fix it is resetting Cura Connect from the printer display (under the maintenance menu).
