### ISSUE TITLE
[3.4 Beta] Infill Support Not Working

### ISSUE THREAD

**Issue by RedRightArm** [Ultimaker/Cura#3906]
I downloaded Cura's new 3.4 beta version. Infill looks exactly the same wether I have Infill Support checked on or off.

**3.4**

**macOS 10.13.4**

**Deltaprintr Delta Go**

**I loaded a model. I clicked Infill Support on and off.**

**I see no difference between it being on or off.**

**I'd expect to se a difference in the infill.**

****

**Comment by ChrisTerBeke** [comment]
Please provide a project fie with the models and settings so we can have a look.

**Comment by diegopradogesto** [comment]
I was checking the feature and it works for me, maybe is model dependent. @RedRightArm , did you figure out what happened? Is your issue solved?
I will close this ticket since we didn't receive any info from you. If it is still happening, send us the project file (File > Save Project...) and reopen the issue.

**Comment by Dukegriff** [comment]
I am having the same problem when I turn on infill support it starts to slice but then stops part way through.

**Comment by diegopradogesto** [comment]
Please, provide project file.
