### ISSUE TITLE
Combing Mode does not work anymore

### ISSUE THREAD

**Issue by Taiko1976** [Ultimaker/Cura#3942]
**Application Version**
3.3.1

**Platform**
Windows 7

**Printer**
RepRap selfmade

**Steps to Reproduce**
Try to slice a part with a hole and compare slice results when Combing Mode is set to All, No Skin, and None. My part has a dimension of 14x4x15 mm with a 2.8 mm hole in the middle.

**Actual Results**
The slicer does not recognize the hole as skin or "outside wall" and moves straight across without retracting or deviating its movement path to prevent crossing perimeters. Since the slicer will not retract before moving across the hole (or move around it), oozing from the extruder will fill the hole.

**Expected results**
The slicer should make sure to move around printed outer walls to keep part integrity on the outside intact. The hole should be considered as "outside wall" or perimeter. The hole should be kept intact and not crossed.

**Additional Information**
![combine mode all](https://user-images.githubusercontent.com/18835558/41505064-72fb0936-7200-11e8-9afb-819bdfd2f64b.png)
![combine mode no skin](https://user-images.githubusercontent.com/18835558/41505066-77ab5c38-7200-11e8-9049-fc23d1b208c8.png)
![combine mode off](https://user-images.githubusercontent.com/18835558/41505067-7b61b48a-7200-11e8-8064-6a4b6604f9e5.png)

**Comment by jackha** [comment]
Hi @Taiko1976 . Thanks for your report.
Can you try the new version 3.4? I can see that your model has very thin sides next to the hole, so it probably considers moving from one side to another impossible using combing. So it goes "outside", which is also the inner hole. In Cura 3.4 that should be improved.
To check if this is actually the problem, you could scale up the model (500%?) and see if it still happens.

btw. I see you use the "legacy" layer view. Is that intentional? Or if you have a relatively new computer, do you have recent graphics drivers? The current "3D" layer view looks so much nicer IMO...
