### ISSUE TITLE
[3.2.1] Keyboard menu controls do not work properly

### ISSUE THREAD

**Issue by herrdeh** [Ultimaker/Cura#3971]
**Application Version**
3.2.1 PPA
**Platform**
ubuntu 18.04 GNOME

**Steps to Reproduce**
hit alt-d or alt-b or alt-a (I'm at the German version)
**Actual Results**
nothing
**Expected results**
The "Datei" / "Bearbeiten" / "Ansicht" menu should pop up.

**Comment by alekseisasin** [comment]
@herrdeh , I think the issue is related to this discussion: 
https://github.com/Ultimaker/Cura/issues/2964#issuecomment-352139776

**Comment by Ghostkeeper** [comment]
It's not the keyboard layout thing or specific to Linux. It's the language. Switching to German reproduces this problem for me too.

**Comment by Ghostkeeper** [comment]
I get a warning in the log when these buttons are pressed:

    QQuickAction::event: Ambiguous shortcut overload: Alt+B

**Comment by DDDirk** [comment]
I have a similar problem using Cura 3.0 AppImage (also on Linux).
Alt - F, E, V, X and H work (File, Edit, View, Extensions, Help), but nog Alt - S, L and R (Settings, Plugins and Preferences). I also get the 'Ambiguous shortcut overload' messages in the terminal for those shortcuts.

Also (possibly related?), moving between the menus with the arrow keys doesn't work everywhere. Using those I can get to Settings, with Alt-V and then right arrow. Another right arrow opens the Printer submenu (because the top item gets preselected), yet another closes the menus and and yet another one starts rotating the build plate. If I do Alt-X for Extensions and then right arrow repeatedly, nothing happens at all. Maybe this has something to do with that the top item (Changelog) does not get preselected? This only happens in Extensions. In all the other menus, the top item gets preselected (if not greyed out).
Going left (from Help) works ok all the way.

**Comment by diegopradogesto** [comment]
For Devs.: CURA-5642

**Comment by diegopradogesto** [comment]
It happens also in Windows and also in English.

**Comment by Ghostkeeper** [comment]
We fixed this in version 3.5. Thanks for the report!
