### ISSUE TITLE
Slicing crashes specific to orientation and model

### ISSUE THREAD

**Issue by davebelleville** [Ultimaker/Cura#3983]
**Application Version** 3.4.0

**Platform** Win7-64

**Printer** Custom (Ender4-0.5 nozzle)

[BKCTester_P2302.curaproject.3mf.curaproject.3mf.curaproject.zip](https://github.com/Ultimaker/Cura/files/2138951/BKCTester_P2302.curaproject.3mf.curaproject.3mf.curaproject.zip)

**Steps to Reproduce** Try to slice this specific model in the specific orientation

**Actual Results** Partial slicing then crash "Slicing engine for Cura has stopped working"

![3 4 0 crash on rot](https://user-images.githubusercontent.com/20446262/41939018-7a8d1f86-7949-11e8-8ccc-2b94f3ef2264.png)

**Expected results** Sliced output

**Additional Information** Works fine in 3.3.1 There are other issues about the slicing engine but none specific to 3.4.0 that I found.

**Comment by smartavionics** [comment]
Hi, a workaround is to turn off the wall print order optimization. This is causing the crash due to a poor bit of coding on my part which I will fix. However, the bug is being triggered by your model which I think is broken in some way.

Firstly look at the solid view, it looks OK:

![screenshot_2018-06-26_23-13-49](https://user-images.githubusercontent.com/585618/41942266-bda05a98-7996-11e8-9002-5178c9d2f345.png)

Then look at the x-ray view, those red areas are bad:

![screenshot_2018-06-26_23-14-07](https://user-images.githubusercontent.com/585618/41942283-d1a238c2-7996-11e8-8bfb-c155b454efed.png)

Finally, look at the sliced layer view, quite a lot of walls/roofs are missing:

![screenshot_2018-06-26_23-14-26](https://user-images.githubusercontent.com/585618/41942299-e3e5429a-7996-11e8-9c21-55b53460f1e6.png)

So, I think the model has some problems which you need to fix.

Hope this helps.

**Comment by davebelleville** [comment]
I will fix my model, thank you. I just printed it. Not good.  I will remember to check the model next time.

**Comment by smartavionics** [comment]
I have submitted the fix for this crash. Thanks again for making the effort to report it.

**Comment by LipuFei** [comment]
@davebelleville @smartavionics The fix has been merged. It will be included in the next release.
