### ISSUE TITLE
Create option for Gyroid infill

### ISSUE THREAD

**Issue by probonopd** [Ultimaker/Cura#4004]
Please create gyroid infill that is the shape as graphene. This shape has been shown to be very strong as a 3D printed object and if used as an infill would presumably create very strong 3D prints

http://itsybitsymag.com/2017/01/11/mit-research-ten-times-strong-lightweight-graphene/

Reference:
https://github.com/prusa3d/Slic3r/issues/92

**Comment by ianpaschal** [comment]
FYI the link doesn't work.

**Comment by Kriechi** [comment]
It was working a few days ago...
Anyway: https://www.reddit.com/r/3Dprinting/comments/81b39y/new_infill_pattern_gyroid_looks_amazing/

**Comment by filipgoc** [comment]
Nice.

**Comment by Theagainmen** [comment]
Any news on this? Will Cura add this? :)

**Comment by ianpaschal** [comment]
For now I don't think so, but we will continue to discuss as a team. We would probably be open to adding it via a pull request if someone writes the engine code for it.

**Comment by Theagainmen** [comment]
Thanks, keep it up, love Cura!

**Comment by probonopd** [comment]
Here is a semi-scientific on-camera comparison:
https://www.youtube.com/watch?v=upELI0HmzHc

**Comment by tmbdev** [comment]
Gyroid infill is very useful not just because of its mechanical properties, but also because the interior of the part is fully connected; this is true for no other infill pattern AFAIK. Fully connected interior infill space allows the part to be filled easily with epoxy, and on the other hand lets liquid/air escape through a single hole.

**Comment by fieldOfView** [comment]
Thanks for providing a usecase other than "I want it".

**Comment by tmbdev** [comment]
Let me summarize also the "traiditional" justifications for gyroid: gyroid is one of the strongest infills for a given weight, it is fairly isotropic (=works about the same in all directions), doesn't require strong accelerations, and prints fairly fast. I don't have much hands-on experience with it yet (since Cura is my primary slicer), but I think it may make a good default just based on its mechanical properties alone.

**Comment by Snypes88** [comment]
Missing this feature is absolutely the only reason I use slicer PE!! It is a must if you would like to print PETG infill at any decent speeds as... Come on dev team, this is a chance to make Cura the greatest slicer again 👍

**Comment by smartavionics** [comment]
> It is a must if you would like to print PETG infill at any decent speeds as...

As what?

**Comment by Snypes88** [comment]
@smartavionics you left out the remainder of the sentence. Sharp changes in direction for line infill result in more blobbing and thus poor print quality. Besides, everyone loves Gyroid, so it should just be implemented 😄

**Comment by smartavionics** [comment]
> @smartavionics you left out the remainder of the sentence. 

LOL, you added the remainder of the sentence after I made my comment!

**Comment by ianpaschal** [comment]
Cura has some big stuff in the works so unfortunately for now, no. This issue is marked as "Deferred" because we do not plan to devote any time to it in the foreseeable future, but would like it implemented eventually. Pull requests are very welcome.

**Comment by smartavionics** [comment]
OK, I'll have a go at implementing it.

**Comment by smartavionics** [comment]
Could some kind person attach a simple model and also the gcode that has been created from that model using gyroid infill so I can compare it with I will be producing. Cheers.

**Comment by agibson2** [comment]
I will when I get home tonight.  A simple cube with walls and top bottom layers?  How big do you want it?

**Comment by Snypes88** [comment]
Here's a simple 25x25x25mm cube using gyroid infill 👍 

[Cube.zip](https://github.com/Ultimaker/Cura/files/2373010/Cube.zip)

**Comment by Snypes88** [comment]
Here's the same cube but only with infill... in case its easier for you to check that way @smartavionics 

[CubeInfillOnly.zip](https://github.com/Ultimaker/Cura/files/2373047/CubeInfillOnly.zip)

**Comment by agibson2** [comment]
You might want to mention what infill percentage you used.

**Comment by Snypes88** [comment]
an STL of a 25mm cube..... 🤔😉 The infill is at 17% for reference

**Comment by agibson2** [comment]
This is a 25x25 cube also with a bunch of different infills with and without walls/top/bottom.  I also scaled it by 1200% and did a 300x300 cube with a 2% infill.  I couldn't include it as it is bigger than 10MB.  I included that in the pic because I printed a 300x300 2% infill for fun... well I aborted it after about 36mm.  The 2% 300x300 actually printed which I was surprised by.

The link for the 300x300 is below if you are curious.
https://drive.google.com/file/d/1OB2GbjhJTXPmezXLHlKC8ajgqa7sbjWD/view

![gyroid_infill_25x25cube_300x300x36](https://user-images.githubusercontent.com/6733850/45396669-bb1d7c00-b60a-11e8-96c9-cd3b2b915022.jpg)
[cube_25x25.zip](https://github.com/Ultimaker/Cura/files/2373244/cube_25x25.zip)

**Comment by smartavionics** [comment]
Thanks for the files, they helped a lot.

I am happy to report that after bashing my head against sufficient walls, progress has been made.

As the following pics show, the basic functionality is now working. Needs to be tidied up and performance could be a problem. With high density infill, the slice time goes up hugely. Does Slic3r also slow down a lot for dense gyroid infill?

![screenshot_2018-09-12_21-55-41](https://user-images.githubusercontent.com/585618/45452847-fe452100-b6d6-11e8-90a7-b88f1984c3cb.png)

![screenshot_2018-09-12_21-55-27](https://user-images.githubusercontent.com/585618/45452848-fe452100-b6d6-11e8-8758-53a4fcf4113b.png)

![screenshot_2018-09-12_21-55-13](https://user-images.githubusercontent.com/585618/45452849-fe452100-b6d6-11e8-88a9-a504e74b7462.png)

**Comment by fieldOfView** [comment]
Awesome!

We could implement a warning for the infill density setting in the frontend if the infill pattern is set to gyroid.

**Comment by smartavionics** [comment]
Hi Aldo. That could be a good idea but it's early days yet so I want to find out where the time is going and get it as fast as possible first.

Do people actually use this infill very dense? I just printed that little cube and it seems very sturdy.

Later tonight I will upload a new Linux dev archive so that if anyone is using Linux they could try out the current state of the art.

**Comment by smartavionics** [comment]
How strong would you like your infill, Sir?

Gyroid with infill multiplier set to 3...

![screenshot_2018-09-12_23-10-35](https://user-images.githubusercontent.com/585618/45456046-32254400-b6e1-11e8-8b48-2df274cffea3.png)

**Comment by smartavionics** [comment]
I have uploaded a new Linux archive that includes this feature in its current early state. If anyone tries it out, please provide feedback.

The archive can be found at https://www.dropbox.com/sh/s43vqzmi4d2bqe2/AAADdYdSu9iwcKa0Knqgurm4a?dl=0

**Comment by agibson2** [comment]
I can't test the Linux build unfortunately but as for speed, Yea it does get slower on another slicer.  This with testing with cubes.  I assume more complex stuff will take longer.

Testing on the other slicer software...
100x100x100 mm cube using different infill
20% 1 to 2 seconds
40% 3 seconds
60% 4 seconds
70% 5 seconds
80% 6 seconds
90% 8 seconds
95% 9 seconds
99% 9.5 seconds
100% Gui popup... The Gyroid infill pattern is not supposed to work at 100% density  Shall I switch to rectilinear fill pattern?

**Comment by agibson2** [comment]
I got my CentOS 7 system up and running again.  I tried to run the Linux archive you provided on CentOS 7 but I get an error about  libssl.

File "/home/user1/Downloads/cura/lib/python3.5/ssl.py", line 98, in <module>
  import _ssl                        # if we can't import it, let the error propagate
ImportError: libssl.so.1.0.0: cannot open shared object file: No such file or directory

CentOS 7 has libssl.so.1.0.2k   (openssl-1.0.2k-12.el7.x86_64)

Closest thing I could find which is a recent thing...
https://github.com/Ultimaker/Cura/issues/4061

If I shouldn't post that info in this thread as it is unrelated to gyroid, let me know and I will remove it.

**Comment by smartavionics** [comment]
Sorry, the archive didn't work for you, it was created on a Ubuntu 16.04.5 system.

With regard to the infill density could you please create a 50% infill cube using another slicer and attach the gcode so I can compare densities.

Cura does have a performance problem when the infill has many lines so some work is needed there.

Another issue at the moment is that gyroid infill doesn't work with the connect infill lines option and it would be nice to get that working.

**Comment by agibson2** [comment]
My first print.  It is pretty strong.  The thickness of the lines are thinner but that is likely some setting differences between slicers.  I am completely new at the other slicer.

Some things that are noticeable...  In Cura it stops extruding when it moves over to the next line.  With the other slicer, it just continues to extrude when it moves to the next line which gives it a little more rigidity and looks cleaner (no stringing at top speeds as it never stops extruding when doing infill) but wastes more filament of course.  I actually like Cura's way because I want to print some things without top bottom and walls and the extra filament messes up the pretty structure on the sides :).  It would be better to have an option though so we could decide if we should just keep extruding or stop during the movement to the next line.  With the Cura version, the cube *looks* kind of not so perfect though because of the stringing as that is most visible when you look at it but that might be my settings and it is only visual.  If you look at the inside though, It looks nice.  I have never cared about infill looks until this version of infill so that just might be me :).

I am liking it.  It is a very good start for this.  Thanks for putting the time into it.  I am going to keep using this version for Gyroid infill even though I have to go through hoops to get the files to my desktop to print them :).

[image-3 2](https://user-images.githubusercontent.com/6733850/45521721-4161cb80-b78d-11e8-96b5-4115a4d85727.jpg)
[image-2 9](https://user-images.githubusercontent.com/6733850/45521722-4161cb80-b78d-11e8-9700-8d996b1c27aa.jpg)
[image-1 26](https://user-images.githubusercontent.com/6733850/45521723-41fa6200-b78d-11e8-8247-d96069c23eb1.jpg)

**Comment by agibson2** [comment]
I forgot to mention that the 7.6% in the other slicer is about the same as 10% in Cura going by the pattern size.  Not that any one is right or wrong, just an observation.

**Comment by agibson2** [comment]
The other slicer seems to be overextruding which is why it is thicker and stronger.  Cura is right at 0.4mm (my nozzle width) but slic3r is making the lines from 0.52 to 0.56.  I think I have slic3r configured properly but I can't be 100% sure.  Maybe they are overextruding on purpose with a default setting somewhere or maybe just this infill or maybe something else entirely :).

**Comment by agibson2** [comment]
Increasing the Infill Line Width to 0.5mm (0.4mm nozzle) in Cura makes a 10% infill match the 10% infill pattern of slic3r.  That seems to indicate they are overextruding.  I have never used the infill line width before so that is new to me.

**Comment by agibson2** [comment]
300x300x36.2 2% infill 0.54 Infill Line Width (0.4mm nozzle).  Assuming 0.54 does anything with a 0.4mm nozzle.  The print turned out nice except it started to have some lifting issues as the line ends are not connected as mentioned above.  I used some blue tape on one small section to keep it going and it recovered.  It looks nice and pretty strong considering it is only 2% infill.  I doubt 2% infill will be the norm though as it doesn't have enough coverage for a good top layer of course.  It looks nice though :).
[img_1385](https://user-images.githubusercontent.com/6733850/45547771-f0cf8a00-b7ef-11e8-9560-ee61ac28449e.jpg)

**Comment by probonopd** [comment]
Thanks for your testing and comparison. This is very helpful @agibson2

**Comment by smartavionics** [comment]
Yes, I was just about to comment, thanks for the testing.

I have been busy again today and apart from a slew of bug fixes and performance improvements, have also implemented the connect lines feature for the gyroid infill as you can see here:

![screenshot_2018-09-14_18-33-32](https://user-images.githubusercontent.com/585618/45565804-b3e5b080-b84c-11e8-872f-8f88acd16952.png)

I found it quite challenging to implement but it appears to work OK on the few examples I have tried. Further testing and feedback would be most welcome.

**Comment by smartavionics** [comment]
In about 20mins or so, a new archive should appear on my Dropbox which contains the day's release.

**Comment by fieldOfView** [comment]
https://www.youtube.com/watch?v=E-WHW-QNswE

**Comment by Theagainmen** [comment]
@smartavionics legend man! Can't wait to see this. (Lines in layer view look pretty trippy but that's just the way it is) thanks! :)

**Comment by smartavionics** [comment]
That's what we want, trippy prints!

I think the infill line connections are not yet perfect as sometimes it connects lines that don't have to be connected but, overall, it's working pretty well as you can see...

![screenshot_2018-09-14_18-53-56](https://user-images.githubusercontent.com/585618/45566781-936b2580-b84f-11e8-8ccd-8455601360ff.png)

**Comment by smartavionics** [comment]
Hi Adam, thanks again for the super testing and feedback. Those pics are looking good.

With regard to the density, what I have done is adjust the pitch of the gyroid lines based on the infill line distance scaled by some factor. The infill line distance is related to density and line width. For example, if you are using simple "lines" pattern then 50% density would use a line spacing equal to the line width. 25% density would use a line spacing 3 times the line width. The gyroid pitch is calculated so that the total length of filament required for the infill is close to the length required for the lines pattern with the same infill density. The idea here is that changing the infill pattern from lines to gyroid should result in parts with similar weight.

I think that the layer start point is fixed so it won't start the next layer from where the current layer finishes. I can see the benefit of doing less travel but the downside would be that it would immediately reverse and extrude on top of the still molten layer below so it could give quality issues?

**Comment by agibson2** [comment]
Thanks for taking the time for the explanation.  It is interesting to hear the reasons for things.  It sounds very logical.

For the start point, I looked at the gcode from slic3r and it does start right back over top of where it finished the last layer.  Maybe that isn't always the case... I certainly don't know.  I just thought it was interesting as it was faster and didn't have as much stringing on my printer but stringing can be compensated for mostly.  Maybe a Cura dev already investigated that at some point and determined it is bad.  I am sure you Cura devs are doing what is best for Cura.

I printed another object "Save pangolins" but with outer layers you can't see anything inside so no since in showing a pic of it.  It turned out to be an excellent print.
https://www.thingiverse.com/thing:2064359/

I think people are going to be very happy with what you have done when this eventually gets approved.  It is working well for me as it is now.  I think it is going to be a popular feature when it eventually gets released.

**Comment by agibson2** [comment]
You have been very busy lately according to the pull request commits today.  Will another build be up today?  If so I will wait for my next print.

**Comment by smartavionics** [comment]
OK, I've fixed the issue but the build won't be uploaded for a couple of hours as our internet is tied up for a while.

**Comment by Snypes88** [comment]
Amazing progress 😍 Never thought things would go so fast! @smartavionics When can we expect to try out your progress under Windows? Or is the Alpha channel only for Linux?

**Comment by smartavionics** [comment]
Sorry, @Snypes88 , I can only create Linux versions of my Cura as I don't use Windows here. All of the source is available on github so someone who can build Windows releases could build it but I'm afraid I don't know anyone who does build for Windows from source.

I don't know if it would work but if you have sufficient free disk and memory you could install a small Linux system using Virtualbox and try running my releases using that.

**Comment by agibson2** [comment]
Another print using Gyroid.  I like the pattern.  It is a consistent pattern from the side compared to the triangles that I always used before.  This is a pencil holder.

[image-2 12](https://user-images.githubusercontent.com/6733850/45603335-3c08b900-b9f9-11e8-8126-a7e851b8d41d.jpg)
[image-1 30](https://user-images.githubusercontent.com/6733850/45603336-3ca14f80-b9f9-11e8-897f-27ceac4ba201.jpg)

**Comment by smartavionics** [comment]
Hi Adam, thanks for all the feedback, I'm glad you're happy with the results.

> One thing I noticed when increasing Infill Line Width (from a previous print) from 0.4 mm to 0.6 mm for a 0.4 mm nozzlie is that it shows as 2 lines when really it is just a thicker single line. I tried triangle infill and it showed the same thing so I guess that is expected?

Hmm, I don't see that can you provide some screenshots of the layer view?

**Comment by agibson2** [comment]
I think it is just a rendering/view thing with Cura on Ubuntu inside a HyperV (Windows 10).  Regular Cura on Windows doesn't exhibit this weird looking rendering.

[screenshot](https://user-images.githubusercontent.com/6733850/45640309-4752f780-ba80-11e8-9a82-3e1adc926a73.png)

**Comment by smartavionics** [comment]
Ah, that screenshot is showing the layer view to be using compatibility mode. The OpenGL in the VM must have a low version. I don't think there really are two lines there.

**Comment by agibson2** [comment]
I agree.  It is just using whatever defaults HyperV and Ubuntu use.  I am not worried about it.

Here is another print using transparent PLA.  Really liking the pattern.
[img_1413](https://user-images.githubusercontent.com/6733850/45653905-92343580-baa7-11e8-86e4-4ec6a0401857.jpg)
[img_1412](https://user-images.githubusercontent.com/6733850/45653906-92343580-baa7-11e8-9e28-db16ec2f3771.jpg)

**Comment by agibson2** [comment]
> Cura has some big stuff in the works so unfortunately for now, no. This issue is marked as "Deferred" because we do not plan to devote any time to it in the foreseeable future, but would like it implemented eventually. Pull requests are very welcome.

@ianpaschal Any chance of this getting out of deferred status with the work and the pull request that has been done on it by smartavionics?

**Comment by probonopd** [comment]
He says

> Pull requests are very welcome.

👍

**Comment by fieldOfView** [comment]
Note that the "deferred" status is only meant to show that UM devs won't spent time developing this. Fortunately for us, @smartavionics is not an UM dev.

**Comment by ianpaschal** [comment]
Yup! "Deferred" means we want it (or in the case of a bug, it _should_ be fixed) but that we don't have the time/dev power to make it happen for the foreseeable future.

When Mr. Avionics has made a PR for us to review, we'll slap an "In Progress" label on the PR. 😉

**Comment by smartavionics** [comment]
> When Mr. Avionics has made a PR for us to review, we'll slap an "In Progress" label on the PR. wink

https://github.com/Ultimaker/Cura/pull/4365

https://github.com/Ultimaker/CuraEngine/pull/850

Over to you...!

**Comment by ianpaschal** [comment]
Aha oops! I'm actually now officially working only the UM3 Networking Plugin, so I can't speak to whether or not anyone in Cura team has picked it up but I imagine @Appesteijn will put it in a sprint soon in the near future.

**Comment by smartavionics** [comment]
> Isn't Open Source great?

Sure is. It makes a lot stuff possible that otherwise would be very difficult to achieve.

**Comment by smartavionics** [comment]
I can now build on Linux and OS X but cannot build Windows releases. I have posted a request for help on the forum but nobody has replied.

**Comment by fieldOfView** [comment]
It has been merged! 🍾 🍰 🍺 🎈

**Comment by filipgoc** [comment]
Whoa. What an amazing pace of development here. Congrats!

**Comment by probonopd** [comment]
Thank you everyone involved 💯

**Comment by Theagainmen** [comment]
It has been merged! 🍾 🍰 🍺 🎈
What does this mean? Will it be in the next Cura version?

**Comment by ChrisTerBeke** [comment]
It's not in time for 3.5, but 3.6 will have it (right @nallath ?)

**Comment by Appesteijn** [comment]
Yes it will be in 3.6

**Comment by agibson2** [comment]
I suspect someone will end up getting an alpha build with it compiled in that people will use unofficially...  I think people are really excited for it.  Ideally it would be 3.5 final code with only Gyroid infill compile in but I would settle for a mainly stable alpha master build too.  As I mentioned... I am working on getting a Windows environment going but having a lot of setbacks that really has me puzzled.  At the rate I am going though 3.8 will likely be released by that time :).

**Comment by smartavionics** [comment]
Just letting you know that I have now posted a Windows version of my development release which includes the gyroid infill. You can find it at https://www.dropbox.com/sh/s43vqzmi4d2bqe2/AAADdYdSu9iwcKa0Knqgurm4a?dl=0

**Comment by agibson2** [comment]
Excellent!  Get testing everyone with Windows that is interested! :)  Thank you for this.

**Comment by supermerill** [comment]
Congrats!

**Comment by jcobreros** [comment]
Hey @smartavionics, first: thank you for this build. It works great and I'm loving the infill. However, the fine resolution of the generated gcode chockes my serial bandwidth (and sd-card's), it creates micro motor stalls while the buffer refills, and it forces me to reduce the printing speed.

I've tried changing Cura's maximum resolution from 10um to 20um, but gyroid infill doesn't seem to listen to that variable, as the generated files are exactly the same size.

What would be the easiest way to change the resolution?

Thanks!

**Comment by probonopd** [comment]
So happy to see this :+1: in the Cura 3.6.0-BETA AppImage on Linux:

![peek 2018-11-11 21-50](https://user-images.githubusercontent.com/2480569/48318674-f5e86400-e5fb-11e8-88df-aad5efc53ae7.gif)

**Comment by smartavionics** [comment]
Hi @jcobreros , I'm sorry to hear that the line density in the gyroid infill exceeds your printer's capabilities but I don't think there's much I can do about that because the gyroid pattern is already being generated quite coarsely. Each wave cycle uses a max of 16 line segments. When the pitch (distance between waves) is small it will use even fewer line segments but I do feel that reducing the number of segments further will severely impact the quality of the wave shape.

**Comment by jcobreros** [comment]
Cool! I'm glad to see it's already well optimized. I'll look into my printer's bottleneck.

**Comment by ChrisTerBeke** [comment]
Using this as my go-to infill now :)

**Comment by smartavionics** [comment]
Sorry, the gyroid infill ignores the infill line direction setting.
