### ISSUE TITLE
15.09.82 G Code generation for UMO

### ISSUE THREAD

**Issue by Xisle** [Ultimaker/Cura#401]
Application Version: 15.09.82
Platform: OS X 10.9.5

Steps to Reproduce:
Slice a Tri-force .stl model

Actual Results:
1) After homing the bed, a move to the center of the platform occurs before the part is printed.

2) Multiple passes are made over the same section for all of the bottom layers before beginning the hollow portion of the part.

3) 30 mm/s was chosen in Cura, but the G Code shows otherwise

4) There is at least one F270000 command in the G Code

5) At the end of the print, X/Y axes and the bed were homed.

Expected results:
None of the above.

**Comment by Xisle** [comment]
![screen shot 2015-09-18 at 10 33 26 am](https://cloud.githubusercontent.com/assets/12257213/9967826/7262afea-5df1-11e5-878c-8c831ea824d3.png)

**Comment by Xisle** [comment]
https://github.com/Xisle/Cura/blob/master/tri-force_newCura.gcode

**Comment by Xisle** [comment]
https://www.youtube.com/watch?v=vrrswd7CW7E

The first 3 seconds is all you need to watch

**Comment by Xisle** [comment]
Just noticed the back right of the pyramid does not look right. It printed fine in 15.04.2.

![6ak0mzl](https://cloud.githubusercontent.com/assets/12257213/9968206/9f79e5d2-5df3-11e5-9fe3-db9a9d9715b5.jpg)

**Comment by Ghostkeeper** [comment]
UMO is obviously a newfag. And I keep being amazed by the amount of effort you put in bug reports. Thanks!

**Comment by Xisle** [comment]
.83 appears to have fixed 1, 2 and 3.

4) I show many matches for "F270000" still in the .gcode

5) The end of the .gcode is a mess now...

![screen shot 2015-09-21 at 8 48 52 am 2](https://cloud.githubusercontent.com/assets/12257213/9998535/07879506-603e-11e5-8689-7cac4b8364b4.png)

**Comment by awhiemstra** [comment]
The end GCode was already a mess, it is just a bit more of a mess now. ;)

One reason it looks so messy is that all the settings are exported, including machine settings like start/end GCode. This causes the duplicated start/end GCode at the end of the file.

**Comment by mikenew12** [comment]
I'm on 15.09.83 and the multiple-passes issue is still very much a problem. When I go to slice this model:

![screenshot 2015-09-23 21 56 29](https://cloud.githubusercontent.com/assets/522101/10065653/180966fa-623e-11e5-8471-54b1b18b51a8.png)

parts of the bottom layers are doubled. You can see it in this visualization. Notice the top left, bottom left, and middle parts of the layer are darker because the lines have been drawn twice, however the right side of the layer is fine. Actually trying to print this causes the plastic to build up after a few layers and crash the print head. This is layer 4(ish):
![screenshot 2015-09-23 21 48 21](https://cloud.githubusercontent.com/assets/522101/10065613/5af8d3ac-623d-11e5-8ec8-808e66c35d75.png)

The same thing happens towards the end of the print as it's printing top layers of the inset lettering (sorry that's hard to phrase correctly). This is around 10 layers before the end. Note that I turned infill to 0 just to make the visualization clearer; obviously this wouldn't actually print.
![screenshot 2015-09-23 22 03 01](https://cloud.githubusercontent.com/assets/522101/10065742/2a91c6f4-623f-11e5-82fc-16041c7e9d54.png)

This is with almost completely default, "normal" settings. I adjusted the filament size, print temps, and start/end gcode, but other than that nothing special.

Here's the stl file: https://dl.dropboxusercontent.com/u/1667048/d6.stl

**Comment by nallath** [comment]
Thats a nice visualisation. What tool do you use for that?

**Comment by mikenew12** [comment]
@nallath https://github.com/hudbrog/gCodeViewer. This is with "emulate extrusion width" and "render lines slightly transparent" turned on.

**Comment by mikenew12** [comment]
Just a quick update to this: as of 15.09.85 the multiple-passes issue is considerably worse. Parts of the print are being laid down at least 3 or 4 times (I can't tell for sure, because the visualization is just a black mass).

![screenshot 2015-09-29 17 07 31](https://cloud.githubusercontent.com/assets/522101/10181470/5add53a4-66cd-11e5-9bcc-49d747cecaf3.png)

**Comment by BagelOrb** [comment]
1) seems to already be solved.

2) There was a bug with duplicated skin parts for which I am quite ashamed. For every new skin part, all previous skin parts were reprinted.
It's solved in the next (pre-)release now.

Nice gcode viewer ^^

3) seems to already have been fixed.

4) Coasting is performed at a speed just under the speed with which it has just been printing. However, the percentage was taken to be a proportion, so the coasting speeds were 100 times too high. This has just been fixed.

5) The Cura profile string seems to be executed on an UMO. The M25 command is ignored by an UMO. After conversing with my colleagues, I've decided the current Cura profile string must be removed altogether. The frontend team will be working on reintroducing something similar to the profile string used to retrieve a profile from a gcode.

**Comment by BagelOrb** [comment]
@Xisle What is the youtube video supposed to show? (https://www.youtube.com/watch?v=vrrswd7CW7E)

Are you trying to show the double skin parts bug (problem 2)?

If you can provide me with the tri-force model I will verify that it will be printed correctly.
