### ISSUE TITLE
[3.4.1] Support mesh and modify settings mesh interfere with object

### ISSUE THREAD

**Issue by herrdeh** [Ultimaker/Cura#4051]
**Application Version**
3.4.1
**Platform**
ubuntu 18.04

**Steps to Reproduce**
1. import a flat box, mark as "print as support structure", place it underneath/into your target object
2. import a cylinder, mark as "overlap with other models", set infill density very high, place into the target object - same place as support object
3. slice
4. remove support object
5. slice again

**Actual Results**
The overlap object will print to the very bottom of the build plate.

**Expected results**
The overlap object should only print where intersecting with the target object.

**Additional Information**

As it should be (no support object in place):
![bildschirmfoto von 2018-07-10 17-52-30](https://user-images.githubusercontent.com/7152847/42522919-9bd5fa68-846c-11e8-8cbd-b573dc9ed256.png)
![bildschirmfoto von 2018-07-10 17-52-23](https://user-images.githubusercontent.com/7152847/42522920-9bfaf91c-846c-11e8-8ce9-0980fdc6e529.png)
![bildschirmfoto von 2018-07-10 17-52-08](https://user-images.githubusercontent.com/7152847/42522921-9c21fddc-846c-11e8-8057-7c330d487163.png)

As it comes out with additional support object:
![bildschirmfoto von 2018-07-10 17-51-33](https://user-images.githubusercontent.com/7152847/42522922-9c52bc74-846c-11e8-9727-c510390b4826.png)
![bildschirmfoto von 2018-07-10 18-12-12](https://user-images.githubusercontent.com/7152847/42522990-cf09a100-846c-11e8-9d32-83df99f7c940.png)

Example file:
https://www.dropbox.com/s/h63mp6wz18mlkn6/PI3_PLA-GH-unten-36-10-3-m-Verst.curaproject.3mf?dl=0

**Comment by herrdeh** [comment]
The problem does not occur with support in general activated.

**Comment by diegopradogesto** [comment]
Indeed, this is a bug. Thanks for providing all the information.

As a tip for this model, I would use better "Modify settings for infill of other models" for the cylinders instead of "Modify settings for overlap with other models". In this case, the outer surface of your main model doesn't get affected by the cylinders. See attached picture:
Left cylinder was choose to "Modify settings for overlap with other models" (blue areas shows some artifacts in the model surface)
Right cylinder was choose to "Modify settings for infill of other models" (nor artifacts in the surface)
![image](https://user-images.githubusercontent.com/15830521/42698710-fde55ce0-86be-11e8-8cb6-116a4981a45b.png)

Curiously this will serve as a workaround for your problem. Give it a try!

**Comment by diegopradogesto** [comment]
For devs.: CURA-5579

**Comment by diegopradogesto** [comment]
This is now fixed on master branch. It will be available in next release.

**Comment by herrdeh** [comment]
Thank you very much for taking care for this issue.
Actually, I saw the artifacts mentioned in #3 - good to have a solution for it!

Cheers,
Wolf
