### ISSUE TITLE
Set nozzle temp for first layer after support

### ISSUE THREAD

**Issue by farsidecura** [Ultimaker/Cura#4096]
Would it be possible to add a new property to set the nozzle temperature for the first layer after support?

**Application Version**
CURA 3.4.1

**Platform**
WINDOWS 10 PRO-64bit

**Expected results**
This would be used in an effort to provide less adhesion between the support material and the printed object, while also leaving the gap between layers small enough to keep a decent print quality.

**Comment by smartavionics** [comment]
Hi, you may be interested to learn that a new feature to allow the fan speed to be modified for the skin above support has been added to Cura. See https://github.com/Ultimaker/CuraEngine/pull/748 if you're interested. It works very well for PETG. I'm getting extremely easy release with PETG breakaway support when I use 100% fan.

**Comment by Ghostkeeper** [comment]
Setting the temperature for the layer above support is infeasible, since this will quite often just be a very short strip and you can't adjust the temperature of the nozzle very fast.

What's more, if you adjust the target temperature too often in a short amount of time, PID controllers tend to freak out and the temperature fluctuates wildly. For Ultimaker printers for instance we hold that if we need to adjust the temperature for less than 50 seconds we're better off not adjusting it at all. This bit above the support layer will probably take less than 50 seconds to print.

**Comment by GregValiant** [comment]
Is this still an issue or can this be closed?
