### ISSUE TITLE
15.09.83: Crash on reslice.

### ISSUE THREAD

**Issue by CCS86** [Ultimaker/Cura#413]
Not sure if there is a way to get more data on this crash. Looks like possibly an engine issue, since the last entry is sending data to slicing engine. Not sure if the other warnings are important. This crash showed up as a windows "Cura experienced and error and must close".

![cura log](https://cloud.githubusercontent.com/assets/12439543/9994014/c89f412e-6040-11e5-9277-ce845bbc37e7.jpg)

Save this file and remove the jpg extension

**Comment by CCS86** [comment]
Might have been triggered by setting shell thickness to .4mm while wall line count was set to 5.

**Comment by Ghostkeeper** [comment]
Definitely looks like an engine issue since the engine crashes, but that shouldn't mean that the front-end crashes too...

**Comment by nallath** [comment]
Does the GUI crash? It does seem to go wrong on the engine side.

**Comment by CCS86** [comment]
Yup, the GUI crashed with a windows prompt.

**Comment by BagelOrb** [comment]
The end of the log says:

============================================

2015-09-21 09:03:22,628 - INFO - Backend crashed or closed. Restarting...
2015-09-21 09:03:22,935 - INFO - Started engine process: C:\Program Files (x86)\Cura_15.09.83\CuraEngine.exe
2015-09-21 09:03:22,977 - DEBUG - Backend connected on port 49674
2015-09-21 09:03:23,479 - DEBUG - Preparing to send slice data to engine.
2015-09-21 09:03:23,494 - DEBUG - Sending data to engine for slicing.

=====================================================

I don't think this bug is solvable with the limited information we have.

**Comment by Ghostkeeper** [comment]
Since this all happened 10 days ago, it's too late to direct CCS86 to the engine log now, but the engine log might shed some light on this. If it ever happens again, we'll have to find that log.
