### ISSUE TITLE
Cura TAGs

### ISSUE THREAD

**Issue by mtmello2003** [Ultimaker/Cura#4158]
Hi,

Where can I find the complete list of cura tags (variable) that we can use in gcode scripts? 

like this for example:
{material_print_temperature_layer_0} 

Thanks

**Comment by BagelOrb** [comment]
Cura/resources/definitions/fdmprinter.def.json 
There are also maybe two settings defined in fdmextruder.def.json

**Comment by ChrisTerBeke** [comment]
This question keeps coming back though, maybe we should add a section to the Wiki.

**Comment by fieldOfView** [comment]
Since this keeps coming back every so often, I made a quick and dirty html page that parses fdmprinter.def.json and fdmextruder.def.json and spits out a list:

http://files.fieldofview.com/cura/Replacement_Patterns.html

https://gist.github.com/fieldOfView/03636e14a1889d73b331cab2c3e06040#file-replacement_patterns-html

**Comment by Ghostkeeper** [comment]
Apart from all the settings, we also expose the `{date}` and `{time}` and also some old names of settings. See https://github.com/Ultimaker/Cura/blob/6a053a9f46c56a94cfaf611cb55376b4d0ad09d1/plugins/CuraEngineBackend/StartSliceJob.py#L275 for the implementation.

**Comment by fieldOfView** [comment]
I had already added those to the top of the document linked above.
