### ISSUE TITLE
Build hollow towers in a single direction 

### ISSUE THREAD

**Issue by adiastra** [Ultimaker/Cura#4211]
**Application Version**
3.4.1

**Platform**
WIndows
**Printer**
MP Mini Delta

**Steps to Reproduce**
Build a hollow tower with infilled walls 

**Actual Results**
Print head changes direction 
**Expected results**
Print head should cintinue in either a clockwise or counterclockwise direction for the entire print

**Additional Information**
When printing any tower (tall walls, hollow inside) that includes an infill, the print head changes directions form clockwise to counterclockwise depending on what it is doing (walls or infill) I would like the print head to continue in one direction to allow proper cooling and have less abrupt direction changes. The current options (expert and experimental) do not allow for this.

**Comment by Ghostkeeper** [comment]
We optimise the path, including the direction in which infill lines are printed, based on what the quickest path would be. This has a weighting to keep the directions the same to reduce accelerations, so that is already implemented. Only Cura considers the change of direction not as bad as the extra travel length, in your case.

The difference in direction between the two outer walls (on the outside and on the hollow inside) is a known problem, but it usually isn't a problem; only if you have no infill and no skin, just pure walls on a layer in a hollow part.
