### ISSUE TITLE
Cura slicing missing layers

### ISSUE THREAD

**Issue by EliasDebaveye** [Ultimaker/Cura#4247]
**Application Version**
3.4.1

**Platform**
Windows 10

**Printer**
Ender 3
![cura](https://user-images.githubusercontent.com/42442650/44213219-79192b80-a16d-11e8-8993-64ddde69d490.PNG)

**Comment by smartavionics** [comment]
Well, it could be the model or all sorts of things. Tell  you what, if you attach the project file, someone could possibly find out what's going on.

**Comment by EliasDebaveye** [comment]
[Picachu_Remix_Low_poly.zip](https://github.com/Ultimaker/Cura/files/2295407/Picachu_Remix_Low_poly.zip)

**Comment by smartavionics** [comment]
Thanks for the model file. The model has flaws, that's the problem. This is what Freecad says about it:

![screenshot_2018-08-17_07-09-08](https://user-images.githubusercontent.com/585618/44250522-8fb29780-a1ec-11e8-8f2d-7c63b450d0b0.png)

**Comment by Ghostkeeper** [comment]
Yes, it seems that the nose was pasted on afterwards using loose polygons rather than a closed volume. This causes it to become ambiguous which parts of the model are inside the model and which parts are outside. In your case, it decides that most of the head is outside the polygon there.

You can see this in X-ray view pretty easily.
![screenshot from 2018-10-16 11-25-20](https://user-images.githubusercontent.com/2448634/47006452-36a4a880-d136-11e8-92ca-15386003775c.png)
