### ISSUE TITLE
section of part missing. changes with rotating part

### ISSUE THREAD

**Issue by supersoulman** [Ultimaker/Cura#4258]
**Application Version**
3.4.1
**Platform**
Mac OS 10.13.6

**Printer**
PRUSA i3 MK3

**Steps to Reproduce**

ADD PART TO BUILD PLATE. SECTION OF PART IS MISSING. 

**Actual Results**
THE SECTION THAT IS MISSING CHANGES IF YOU ROTATE THE PART

**Expected results**
THE FULL PART SHOULD BE THERE

**Additional Information**
NONE
![screen shot 2018-08-19 at 12 23 15 am](https://user-images.githubusercontent.com/29802201/44305491-85a4ac00-a346-11e8-96ad-3f18ae743625.jpg)
![screen shot 2018-08-19 at 12 22 27 am](https://user-images.githubusercontent.com/29802201/44305492-85a4ac00-a346-11e8-8f25-2f7b476ccd47.jpg)

**Comment by smartavionics** [comment]
Please provide the model file. Even better, please zip the cura project file and attach that to this issue. Thanks.

**Comment by fieldOfView** [comment]
This is 90% certain caused by a "non manifold" model. Check the model in X-ray view, and you should see red parts. Best thing is to repair the model before printing. 

You may try if it slices better with the setting "Union Overlapping Volumes" turned off (use the search on top of the Custom settings).

**Comment by BagelOrb** [comment]
I would wager it is 99% certain.
