### ISSUE TITLE
[3.4.1] Estimated time off by about 33% when printing via USB

### ISSUE THREAD

**Issue by hawkerm** [Ultimaker/Cura#4373]
**Application Version**
3.4.1

**Platform**
Windows 10

**Printer**
Prusa I3 (Anycubic I3 Mega)

**Steps to Reproduce**
1. Open Cura
2. Setup Print
3. Print via USB
4. Wait

**Actual Results**
Estimated 9 hour print took 12 hours instead.

**Expected results**
Estimated time should have been 12 hours...

**Additional Information**
Seems to be constantly about 33% more time for print time vs. estimate I've been given.

**Comment by nallath** [comment]
This is an issue with the machine definition. Since this was contributed by a third party, it's likely that the machine settings for jerk & acceleration are wrong. Cura does use those to estimate the time it will take to print, but if the machine then uses different ones, the estimations will be off.
