### ISSUE TITLE
Strange crash of Cura within JGCreat

### ISSUE THREAD

**Issue by hlwalg** [Ultimaker/Cura#4413]
![image](https://user-images.githubusercontent.com/43514253/45926923-cb96f600-bf2a-11e8-8213-d735926c8c45.png)

Ladies/Gentlemen:
After succesfully starting JGCreat once, reopening the program every next time gives the included error message. After deinstalling/reinstalling it's the same: one time it opens; after that first time we get the error message again.
Regards

Hugo Walg

**Comment by ChrisTerBeke** [comment]
JGCreat seems to be a modified version of Cura. We don't support those here, please contact JSAurora directly.

**Comment by hlwalg** [comment]
This might be true, but i.m.h.o. is this the result of the use of different versions of the Visual ++ dll's. Is this true? Without also installing the latest Cura, the JGCreate program keeps on working.

**Comment by Ghostkeeper** [comment]
The issue seems to be with access rights to a folder that creates settings. I don't know why Cura doesn't have these access rights, but then again, the normal Cura installation doesn't generate a configuration folder there either, so this really is something that you would have to take up with the authors of your Cura version.
