### ISSUE TITLE
[3.5] Ender 3 Profile not correct

### ISSUE THREAD

**Issue by tauceti82** [Ultimaker/Cura#4468]
Hi,

the new Ender 3 Profile in Cura 3.5 has a wrong fine profile.
It has the same layer height as normal 1.5 whereas CR10 have 1mm
Fine also has a lower wall thickness as normal profile.
Please recheck. I haven'T compared all values. 
It would be nice to have the same CR10 fine profile in the Ender 3 printer too

**Comment by ChrisTerBeke** [comment]
It's up to community/Creality to provide the correct values for 3rd party machines.

**Comment by stelgenhof** [comment]
This is because Cura 3.5 includes an incorrect version of the Ender-3 machine definition. The incorrect version was corrected and committed but apparently didn't make it in the 3.5 release.

You can see in the master branch (https://github.com/Ultimaker/Cura/tree/master/resources) that the correct profile and extruder train definition are present.
