### ISSUE TITLE
[3.5]machine extruder trains  not specified in Creality ender 3 definition file

### ISSUE THREAD

**Issue by ilporcupine** [Ultimaker/Cura#4474]
Seems to default to some Ultimaker profile, as the filament size reverts to 2.85mm. May explain horrible underextrusion problem I had. On inspecting the .json files, the CR10 series all define the extruder, as do the other machines I inspected. Only the Ender seems to be missing an extruder definition.

**Comment by SaskiFX** [comment]
Looks like the extruder is listed in the extruders folder, just didn't get mentioned in the definition for the printer.

**Comment by stelgenhof** [comment]
This is because Cura 3.5 includes an incorrect version of the Ender-3 machine definition. The incorrect version was corrected and committed but apparently didn't make it in the 3.5 release.

You can see in the master branch (https://github.com/Ultimaker/Cura/tree/master/resources) that the correct profile and extruder train definition are present.

**Comment by BagelOrb** [comment]
So this is fixed already for the next release - if I understand correctly.

I can reopen if need be.

**Comment by stelgenhof** [comment]
@BagelOrb Thanks for the quick response!
