### ISSUE TITLE
Dual Extrusion Build Plate Volume

### ISSUE THREAD

**Issue by Leifcald** [Ultimaker/Cura#4544]
I Cant print this sprocket with support layer using dual extruders although the second extruder is no way near the boundries for the second extruder.

Shouldnt the diffrent extruders slice diffrently to allow maximum build volume.?

**Application Version**
3.5.0

**Platform**
Windows 7 X64

**Printer**
Ultimaker 3 Extended

![image](https://user-images.githubusercontent.com/44057993/46801256-6cbee280-cd5a-11e8-9e51-3a0f3e5ef11e.png)

![image](https://user-images.githubusercontent.com/44057993/46801289-8e1fce80-cd5a-11e8-8129-505cc7dbf878.png)

**Comment by diegopradogesto** [comment]
In a Ultimaker 3 there is no room to move the right extruder all the way to the left of the buildplate, or the left one all the way to the right. The new Ultimaker S5 already solves that.

We cannot fix this in Cura, it's hardware dependent.

**Comment by Ghostkeeper** [comment]
The report was about the right extruder not needing to go all the way to the left of the build plate, since the part that was printed by that extruder doesn't go that far towards the edge. In the picture it's only the support that's being printed by the other extruder, which is more towards the centre of the build plate.
