### ISSUE TITLE
[3.5.0] Supports are generated beneath the model under the "real" support structure

### ISSUE THREAD

**Issue by printingotb** [Ultimaker/Cura#4583]
**Application Version**
3.5.0

**Printer**
Custom FDM

**Steps to Reproduce**
See attached project and pictures

**Actual Results**
Supports are generated beneath the model under the "real" support structure

**Expected results**
Same file and settings did not do this in 3.4.1

**Additional Information**
Cura 3.5.0:
![1](https://user-images.githubusercontent.com/32172100/46972763-9875fb80-d0bf-11e8-99a4-7e93a6e458ec.PNG)
Cura 3.4.1:
![2](https://user-images.githubusercontent.com/32172100/46972770-9d3aaf80-d0bf-11e8-97b1-ee4ec2c790d8.PNG)

[supportbug.zip](https://github.com/Ultimaker/Cura/files/2480196/supportbug.zip)

**Comment by diegopradogesto** [comment]
This seems to be a bug. The support is being generated from the top part and dropping down till the BP. I even tried to put a support blocker in the bottom part and the support is generated anyway.

![image](https://user-images.githubusercontent.com/15830521/47014268-06670500-d14a-11e8-9413-fb32fc0d0543.png)

**Comment by gravesfamily** [comment]
Just to add on, I'm seeing the same thing in a different model that sliced fine in 3.4.1, and because of it, I cannot actually print the item I need because the support inside the tunnel fills it up, making the tunnel useless. :-)

Using this object: https://www.thingiverse.com/thing:2783459

The tunnel in the object ends up with a support in 3.5:
![4](https://user-images.githubusercontent.com/44204236/47025785-fedb3800-d118-11e8-838d-a9a009f8e960.JPG)

While 3.4.1 does NOT have the same support generated:
![7](https://user-images.githubusercontent.com/44204236/47025845-174b5280-d119-11e8-9094-fa154d5e2dc3.JPG)

Note that there is actual model above the tunnel that will have support on top of it as necessary.
![2](https://user-images.githubusercontent.com/44204236/47025906-3649e480-d119-11e8-9160-63bb03f55886.jpg)
![3](https://user-images.githubusercontent.com/44204236/47025916-3a760200-d119-11e8-9e7f-9d82b09c07b8.JPG)

**Comment by b14ckyy** [comment]
Confirmed. Recognized yesterday on my first slice on 3.5.1 too. 

If Printbed only, cura will generate printbed support for overhangs, even if parts of the model are underneath:

![image](https://user-images.githubusercontent.com/33039058/47575071-7d1db280-d941-11e8-9f66-947b66f9269c.png)

The big overhang on the back is ignored, this has a 45° angle. 

![image](https://user-images.githubusercontent.com/33039058/47575157-b22a0500-d941-11e8-8c59-2f20e5cfdfbf.png)

if support activated anywhere it looks like this:

![image](https://user-images.githubusercontent.com/33039058/47575227-dab1ff00-d941-11e8-8b33-5db516e4a7f4.png)

if support blocker is used in the top part, the support beneath will disappear on that line:

![image](https://user-images.githubusercontent.com/33039058/47575351-34b2c480-d942-11e8-9c2c-e7157a356528.png)

**Comment by dragoon88** [comment]
This bug has continued into version 3.6. It does not matter if there is support blocker on a lower overhang, or if the lower overhang is at a printable angle. The lower overhang angle in this picture is 33°. The other lower overhang has a support blocker.
![support](https://user-images.githubusercontent.com/4960379/48499259-e0865c00-e7ec-11e8-9829-1926878f5b49.png)

**Comment by Ghostkeeper** [comment]
It doesn't reproduce in Cura 4.0 any more:

![screenshot from 2019-01-15 11-44-24](https://user-images.githubusercontent.com/2448634/51175572-faaaec00-18ba-11e9-8bf2-9b0b1c48feb5.png)

This same model did exhibit the bug in 3.6.

**Comment by Ghostkeeper** [comment]
Ah, yes, it looks like our internal ticket (CURA-5833) was already marked by our QA as fixed.
