### ISSUE TITLE
Suport on top surfaces an

### ISSUE THREAD

**Issue by tebz** [Ultimaker/Cura#4606]
Cura 3.5.1
Rhino3D  5 SR14 32-bit (5.14.522.8390, 2017-05-22)

**Application Version**
Cura 3.5.1
Rhino3D  5 SR14 32-bit (5.14.522.8390, 2017-05-22)

**Platform**
Windows 10 -64, version 1709

**Printer**
Ultimaker 3 

**Steps to Reproduce**
Enable support & use Extruder 2 as support material (PVA)

**Actual Results**
There are excessive support printed that are not supporting

 anything.
More on 0.1 mm layer height
Even more with 0.06 mm layer height

**Expected results**
Use support only when needed

![image](https://user-images.githubusercontent.com/9913364/47152146-28908c80-d2dc-11e8-9519-61b73af779cd.png)
![image](https://user-images.githubusercontent.com/9913364/47152155-334b2180-d2dc-11e8-8669-b91bd06e93eb.png)
![image](https://user-images.githubusercontent.com/9913364/47152171-4100a700-d2dc-11e8-8f6c-9452314580df.png)

[UM3_MTME400_assy_20180928 lucka.zip](https://github.com/Ultimaker/Cura/files/2491741/UM3_MTME400_assy_20180928.lucka.zip)

**Comment by rburema** [comment]
Hi @tebz, I'm not sure what you're trying to say here? Please finish the title, fill out the form, and possibly attach a model and/or screenshots. cheers, Remco.

**Comment by rburema** [comment]
Hm, apearantly github doesn't notify a commenter when a report is edited only. Anyway, we're getting similar reports (see also #4658 and #4653 ), so we'll probably have a look at it.

**Comment by rburema** [comment]
Possible relation to #4583 as well?

**Comment by Ghostkeeper** [comment]
It's generating this support because your model is not watertight:

![screenshot from 2018-10-29 10-27-36](https://user-images.githubusercontent.com/2448634/47641052-56d85c80-db65-11e8-9c28-c7f429f21db3.png)

This introduces tiny (~20μm) pieces of overhang which are expanded by 3mm due to the Support Horizontal Expansion setting.

**Comment by alekseisasin** [comment]
Devs, see CURA-5868.

**Comment by tebz** [comment]
Would it not be logical to ignore overhang smaller than, maybe, upp to half the printing width ?

**Comment by rburema** [comment]
Hi @tebz,
We enforce water-tightness in order to do these sorts of calculations (overhang-angle, etc.) in a timely manner, so slicing time (not to be confused with printing time) does not become prohibitive. Also it isn't really well defined what the 'outside' and 'inside' of an object is if water-tightness is violated. That means that all bets are off if a model doesn't conform.
You could argue that we should just disable all support smaller than a certain size, but then things that (locally) look like, say, an iverted pyramid woudn't have support printed any more.
cheers, Remco.

**Comment by Ghostkeeper** [comment]
Removing all small areas would invalidate our option for support towers. Plenty of prints need to support things that are very slim: Pins pointing downwards, wings with wingtips, clips with sharp edges, etc.

You can set the Support Minimum Area setting higher in your case, which would fix the issue. I think that is a good workaround, and more or less what you were looking for anyway, but it's optional.
