### ISSUE TITLE
[3.5.1] Mesh Type "Modify settings for overlap with other model" produces Unable to slice

### ISSUE THREAD

**Issue by sneaky-tricky** [Ultimaker/Cura#4640]
Simple overlap of model with "Modify settings for overlap with other model" mesh can not be sliced. Same profile and project works fine in 3.4.1.

[CFFFP_Better_Temperature_Tower_v5_240-160.zip](https://github.com/Ultimaker/Cura/files/2504531/CFFFP_Better_Temperature_Tower_v5_240-160.zip)
![cura_2018-10-23_00-32-09](https://user-images.githubusercontent.com/4428861/47336156-8f0b0700-d65c-11e8-9165-aae0e2bf453d.png)

**Comment by Vandrasc** [comment]
Hi @sneaky-tricky , the problem lays at the print sequence - one at a time- , so in this case, it is expected behavior that the slicing is not being triggered, because the disallowed areas are overlapping. 'The one at a time is only possible if all models are separated in such a way that the whole print head can move between the models.'

Can you please confirm if Cura triggers a slice when Print sequence is set to 'All at Once'? 

Thanks!

**Comment by sneaky-tricky** [comment]
Oh, you're right. I didn't realize that "Modify settings for overlap with other model" mesh doesn't work in "One at a Time" mode. Everything's fine in "All at Once" mode.

**Comment by Ghostkeeper** [comment]
See also #4193.
