### ISSUE TITLE
[3.5.1] Extruder 2 not wiping on prime tower on 1st layer

### ISSUE THREAD

**Issue by Braccoz** [Ultimaker/Cura#4643]
**Application Version**
3.5.1

**Platform**
Windows 7 X64

**Printer**
Custom Printer

**Steps to Reproduce**
Just have a model that uses both extruders on layer 1. The first extruder will print the base of the prime tower and the model, then when switching to extruder 2, it will not wipe on prime tower but instead go directly to the model.

**Actual Results**
extruder 2 does not wipe

**Expected results**
extruder 2 should wipe on prime tower before going to the model
[CFFFP_dualTest3a.zip](https://github.com/Ultimaker/Cura/files/2510278/CFFFP_dualTest3a.zip)

**Comment by alekseisasin** [comment]
Hi @Braccoz , I have followed your steps as explained and I see the extruder 2 prints brim around the model. Can you check all the settings which you are using? For test add Iltimaker 3. load the models and slice with two extruders with an enabled prime tower. You should see the normal behaviour.

**Comment by Braccoz** [comment]
hi @alekseisasin , if you disable the brim (which i don't intend to use) you can see the issue:

extruder 1 is primed on the first layer of prime tower, and that's ok, but extruder 2 is not. starting from layer 2 extruder 2 gets properly primed.

https://guides.github.com/features/mastering-markdown/
![cura](https://user-images.githubusercontent.com/3883377/47743917-6bf5de00-dc80-11e8-90d4-46578cd1fbd1.png)

**Comment by alekseisasin** [comment]
Can you select the Build Plate Adhesion Type: "Skirt"

**Comment by Braccoz** [comment]
yes i can, and it will print a skirt with both extruders. but i don't want a skirt, on the part at least.

**Comment by alekseisasin** [comment]
Then it is intended behaviour. If you still want to have some extra extrusion you can add a small ("dummy") model which will be printed before the model. (In this case, you might need to change the Layer Start X and Layer Start Y.)

**Comment by Braccoz** [comment]
i wouldn't call this intented behaviour. the option "wipe inactive nozzle on prime tower" suggests the inactive nozzle will be primed before printing which isn't the case. if brim or skirt is mandatory, then it should be put automatically on prime tower, but still respect the setting for the actual part

**Comment by alekseisasin** [comment]
Under "intended" I meant, it works as expected. You also right, if no brim, then the extra lines still might appear on the prime tower.

**Comment by Ghostkeeper** [comment]
Skirt or brim is not mandatory, but if your firmware doesn't automatically prime it's highly advisable to enable skirt, brim, raft or Prime Blob for every extruder that you're using, otherwise it will indeed not prime. If you can't do that because you don't have space on your build plate or something, you can still disable it at risk of not being primed properly.

Wipe inactive nozzle on prime tower doesn't mention or seem to imply that the nozzle must be primed first.

And of course it's not wiping if it hasn't printed yet.

**Comment by marcottt** [comment]
i have same problem on my anycubic kossel with Y bowden splitter. I do not undestand solution. 
I tried with skirt but when 2nd extruder start make only 1 skirt (when i ask for 3 for example and 1st material effectly made 3). 
I can make a dummy object to print with 1 layer high, but how a can tell to cura to print it before primary object and not after ? or there is a real solution ?

**Comment by Ghostkeeper** [comment]
> I tried with skirt but when 2nd extruder start make only 1 skirt (when i ask for 3 for example and 1st material effectly made 3).

Keep in mind that this is a per-extruder setting so if you want the other extruder to also make 3 lines, you need to modify the setting in that extruder's tab.

> but how a can tell to cura to print it before primary object and not after ?

The extruder's planning will start with the object that is closest to the "Layer Start X" and "Layer Start Y" coordinates. The printer will always start with the first extruder though, there is no configurability there.

**Comment by BitHappy** [comment]
I'm having the same issue with my prints. It appears to work fine and does deposit material into the prime tower if you have brim enabled, but in all other cases it goes directly from extruder 1 to extruder 2 on the first layer. Normally I would just use brim and it would be fine, but for a print I'm doing today I'm having serious bed adhesion issues and need to use a raft. If you use a raft, you can't include a brim on the prime tower and then it doesn't work.


![CuraIssue](https://user-images.githubusercontent.com/7006359/62642162-fc410d80-b8f9-11e9-9e5e-05ec20645e34.png)

As you can see in the above issue, on the first layer of the print after the raft the layer is complete but the prime tower only has blue in it. (And it began with blue) Maybe it would work if they just made the first layer of the prime tower the other color and did it in between instead of at the beginning?

**Comment by Ghostkeeper** [comment]
Making one layer of the prime tower another colour is not an option since it causes the tower to topple over if the two materials don't stick well together (such as with PLA+TPU, or breakaway materials).

**Comment by BitHappy** [comment]
Oh ok that makes sense, it was just an idea I thought up as I wrote haha. Well the best option then would be to just treat it like the rest of the tower and deposit the second material in the inner area right?

**Comment by palo0406** [comment]
Basicaly there is one way- for the skirt print select second extruder means  you will start with nozzle 2  print  skirt and than with nozzle 1 print  first layer of prime tower - should  prime  enough material from first extruder  (is printeed before model and  depends on  prime tower size should  clean nozzle )  than from the second layer there is no issue wiping works good
