### ISSUE TITLE
Cura 3.5.1 don't fill gaps between walls

### ISSUE THREAD

**Issue by Predator75** [Ultimaker/Cura#4684]
**Application Version**
3.5.1

**Platform**
Windows 64

**Printer**
custom

**Steps to Reproduce**
Slice the file with 0.4 nozzle and 5 wall count

[RightAnt blu.zip](https://github.com/Ultimaker/Cura/files/2526145/RightAnt.blu.zip)

**Actual Results**
the  gaps between walls are not filled, the problem is visible in cura preview before the print

**Expected results**
Fill gaps between walls

**Additional Information**
![index](https://user-images.githubusercontent.com/1283811/47665242-ef400280-dba0-11e8-9864-28fea9503dc8.jpg)

**Comment by smartavionics** [comment]
Try turning off the overlap compensation for the inner walls.

**Comment by Predator75** [comment]
> 
> 
> Try turning off the overlap compensation for the inner walls.
unfortunately the result does not change

**Comment by Predator75** [comment]
No way to fill these gaps? :-(

**Comment by smartavionics** [comment]
Have you tried using thinner wall lines?

**Comment by Predator75** [comment]
Yes smartavionics, thanks, if I print with a thinner line or I print only 3 walls count the sharp angles are not created.
But why do not it fill them?

**Comment by Ghostkeeper** [comment]
In the "Shell" category right under "Fill Gaps Between Walls", make sure that the "Filter Out Tiny Gaps" setting is not checked.

It's checked by default because for many of the smallest gaps, moving the nozzle there and trying to extrude won't have much of an effect since the delay between the extruder and the flow through the nozzle basically prevents any material from being extruded in that tiny amount of time that the nozzle is over the correct spot.
