### ISSUE TITLE
Incorrect "Check compatibility" error with extruder empty and using BB printcore

### ISSUE THREAD

**Issue by ack000** [Ultimaker/Cura#4706]
**Application Version**
3.5.1

**Platform**
MacOS 10.13.6

**Printer**
Ultimaker 3+

**Steps to Reproduce**
- Set the printer up with a BB print core in slot 2, but do not load any material (this is common, since I put the PVA away in a drybox when not using it).
- in cura, use any project that uses only material 1
- select the actual printer's configuration

**Actual Results**
Cura warns "check compatibility" and sets the profile to "Not supported".
The problem seems to be that Cura ignores the fact that material 2 is actually "empty" in the printer,  and instead sets it to "PLA" (which you can see if you click on the "Extruder 2" button at the top right).  And of course, PLA *is* incompatible with a BB printcore -- but
(a) material 2 is actually "empty", not PLA
(b) material 2 is not even *used* in the print job at all
The error message can very confusing, because if you click on the "Extruder 1" button, it shows the material loaded for extruder 1 in bright orange, suggesting that *it* is responsible for the incompatibility.

**Expected results**
There should be no error message, for the  two cases below.
(a) material 2 is actually "empty" --- or
(b) material 2 is not actually used in the print job

**Additional Information**
The workaround is to click on the "Extruder 2" button and pretend it has PVA loaded.  Thankfully, even though this is not the actual physical configuration of the printer, Cura allows me to print.  But that is pretty bogus.

[project.3mf.zip](https://github.com/Ultimaker/Cura/files/2539068/project.3mf.zip)

**Comment by diegopradogesto** [comment]
You mean using the sync button (right side of the printer name)? Yes we know about that. The thing is that what we can do is maybe disable this extruder when a material is empty in the printer. However how to handle it when there are no materials in the printer (both extruders), we can't disable all the extruders.

It needs to be analysed. Probably we will find out a solution for the next version. I mark it as a bug. Thanks for sharing.

**Comment by ack000** [comment]
How about treating “empty" as a (pseudo-)material that is compatible with any print core?

	Alex

**Comment by diegopradogesto** [comment]
Yes, that's the other possibility, but currently we don't have a material that is compatible with all the print cores, so we have the same problem. In the next months we are preparing some changes in the UI workflow and maybe we can fix this corner case.

FYI @LukeChen-Ultimaker

**Comment by ethanpil** [comment]
I have the same problem as well on 3.6

I leave Extruder 2 empty (with BB core), and when I select to show the configuration, it correctly shows empty.

![image](https://user-images.githubusercontent.com/254784/53215382-35fcb100-3605-11e9-9d93-878473d621b5.png)

After I select the printer and connect, it will load Extruder 1 settings correctly but highlighted in orange, and Extruder 2 material will always need to be changed to PVA even though its empty, or nothing will print. This has been happening since the 2.x releases and I have never been able to get it to work without this intervention.

![image](https://user-images.githubusercontent.com/254784/53215431-79571f80-3605-11e9-8a38-a1e735186d9a.png)

I need to change to:

![image](https://user-images.githubusercontent.com/254784/53215468-a0155600-3605-11e9-9d17-42cc62bac8ed.png)

It's really frustrating and time consuming and confuses students when they change materials or printers...

**Comment by Ghostkeeper** [comment]
The UI changes we've made in 4.0 make it easier to disable an extruder so that this problem doesn't occur any more, but it's still manual. We're toying with the idea to disable an extruder automatically when syncing with a printer that has no material in one of the extruders.

**Comment by Ghostkeeper** [comment]
Oh, I understand that we already implemented that. I think that makes the workflow sufficiently clear then.

When you sync with a printer that doesn't have a material in one of the extruders, that extruder gets disabled in Cura. This means that
* the available quality levels will only depend on the material that was present,
* you can use one-at-a-time mode, and
* no more orange material drop-downs after syncing.
