### ISSUE TITLE
[3.5] Hair tip starts in hair and there isn't a support

### ISSUE THREAD

**Issue by Liger0** [Ultimaker/Cura#4723]
**Application Version**
3.5.0

**Platform**
Windows 10 x64

**Printer**
Cr-10S

**Steps to Reproduce**
Use supports (normal or tree) on a model with little hair tips starting in hair.

**Actual Results**
Some of the parts starting in hair won't be supported, the others will have support too much distant that will be useless

**Expected results**
There should be a support

**Additional Information**
![hair tip not supported 2](https://user-images.githubusercontent.com/20385116/47957537-dc219e00-dfb7-11e8-8c10-f9112337c776.png)
![hair tip not supported](https://user-images.githubusercontent.com/20385116/47957538-dc219e00-dfb7-11e8-9fef-7f8e520d339f.png)

**Comment by diegopradogesto** [comment]
Can you please provide the STL or (even better) the project file?

**Comment by Liger0** [comment]
> 
> 
> Can you please provide the STL or (even better) the project file?

[CCR10S_tree support.zip](https://github.com/Ultimaker/Cura/files/2563522/CCR10S_tree.support.zip)

**Comment by diegopradogesto** [comment]
I was taking a look, it seems that this tiny part is skipped by the algorithm because is very small and very close to the main body. Using normal supports with default parameters would also skip this part for the same reason. You can maybe try reducing the X/Y distance, increasing the support horizontal expansion, ... But I don't know if it will be an easy fix for that. We appreciate you post the issue, since the Tree Support is experimental we want to keep improving it.

BTW, I checked the model and I saw some weird parts, such as the hair is a different part than the rest of the body and some other surfaces crossing each other. See pictures:

Artifacts in the model due to connected submeshes:
![image](https://user-images.githubusercontent.com/15830521/48304626-cb73a980-e51c-11e8-95e5-052b0c2897ca.png)

Information from the Mesh Tools plugin:
![image](https://user-images.githubusercontent.com/15830521/48304636-ee9e5900-e51c-11e8-8dec-cf5630ca5edd.png)

Where the two parts cross each other:
![image](https://user-images.githubusercontent.com/15830521/48304648-345b2180-e51d-11e8-98a2-54766578b5a4.png)

**Comment by alekseisasin** [comment]
Hi @Liger0 , 
To solve this case you can try to change the setting: Support X/Y Distance. From 0.7 to 0.1, Then extra support will be generated. As well the change increases the printing time and material usage as well.
The second option you can try to add a small block with and set Per Model Setting "Print as support" and place next to the place where you need extra support. 
I hope it will help you to improve the quality of the printed model.

**Comment by Liger0** [comment]
Anothere edge-case similar to the already mentioned one but regarding the Z distance instead of the X/Y is  the behaviour you can see when the Z distance is very low (1 layer as an example), in which case using the tree supports won't touch it.
I guess it is so because the option to make the supports also on the model and not only on the build plate doesn't apply to the tree supports so the needed supports can't go over the hidden parts. 

If it is how I think, I see the only solution would be an intelligent support function which would detect any unsopported point and tell you the tree support is not suited for the model.

Here I'll attach an example.
![tree](https://user-images.githubusercontent.com/20385116/49177480-a91bc180-f34d-11e8-8849-f63f85be49c3.png)

[support tree layer.zip](https://github.com/Ultimaker/Cura/files/2626341/support.tree.layer.zip)

**Comment by GregValiant** [comment]
Is this still an issue with current Cura versions (5.8.0 and up).  Can this be closed?
