### ISSUE TITLE
Cura 3.5.0/3.6.0 beta stops printing too soon

### ISSUE THREAD

**Issue by Predator75** [Ultimaker/Cura#4726]
**Application Version**
3.6.0 beta

**Platform**
win x64

**Printer**
cfff

**Steps to Reproduce**
1.75 filament diameter, 0.4 nozzle, 3 wall, 0.2 layer height

**Actual Results**
the print stop before the real end, it always happens when the last layer is to be filled

**Expected results**
print ok

**Additional Information**
![20181104_142650](https://user-images.githubusercontent.com/1283811/47964712-fd2cd200-e03d-11e8-996d-7ab15a97c1bc.jpg)

**Comment by Predator75** [comment]
Sorry error in my firmware

**Comment by Ghostkeeper** [comment]
In the UM2 firmware this issue also existed for a while. It happened when the end of the file was being reached in the firmware, which was triggering the printer to stop printing. The printer was done reading the file but there were still a few commands left in the command buffer that would then get cut off.

So maybe a workaround is to add a few comment lines to the bottom of your g-code file so that the firmware can continue reading.

**Comment by ZhenhuaMao** [comment]
I found all the ER17 and ER18 errors come from the impact. If you print with 2 type material, the Printcore AA and BB might be printed at the same space. I did the correction for the Ultimaker and it is okay, it looks okay for the first few levels. So, it should be the Cura issue.

**Comment by ZhenhuaMao** [comment]
I found all the ER17 and ER18 errors come from the impact. If you print with 2 type material, the Printcore AA and BB might be printed at the same space. I did the correction for the Ultimaker and it is okay, it looks okay for the first few levels. So, it should be the Cura issue.

**Comment by Predator75** [comment]
> 
> 
> Maybe it helps to post the g-code that Cura generates for this cube, then.
I have attached it
[cubo2.zip](https://github.com/Ultimaker/Cura/files/2821387/cubo2.zip)

**Comment by Ghostkeeper** [comment]
In your g-code, it specifies that it should draw the last few lines correctly. I see nothing wrong with the g-code.

![screenshot from 2019-02-01 12-48-07](https://user-images.githubusercontent.com/2448634/52121391-c73cc100-261f-11e9-9ecd-aca8b8c6fa5b.png)

What should the g-code specify differently in order to make your printer finish the last few lines of g-code?

**Comment by ZhenhuaMao** [comment]
I connected one for the clamps on the connector cable to the AA tubing (should be the BB tubing), might cause the clamp to pull the connector every time the Printcore moving!

**Comment by ZhenhuaMao** [comment]
reset the clamp and connector and it is okay now, continuously monitor...
