### ISSUE TITLE
[3.6.0] slicer does not add layer to touch the bed

### ISSUE THREAD

**Issue by momala454** [Ultimaker/Cura#4791]
**Application Version**3.6.0

**Platform**
windows 10

**Printer**
creality ender 3

**Steps to Reproduce**

**Actual Results**

**Expected results**

i'm using the support and adherence, but using the attached  stl file, it looks like some of the model does not touch the bed, and even with support and adherence, cura does nothing to make it touch the bed, so when i try to print, when it arrives at the second layer to the point where it tries to print the element that does not touch to bed, it print in the air and does not stick at all to the bed.

**Additional Information**

![bug1](https://user-images.githubusercontent.com/83005/48435449-d62c7980-e77c-11e8-98fc-3bb09f055ebb.png)
![bug2](https://user-images.githubusercontent.com/83005/48435450-d62c7980-e77c-11e8-8369-e1bac8db67ca.png)

[o_Door_Side_Top.zip](https://github.com/Ultimaker/Cura/files/2577599/o_Door_Side_Top.zip)

**Comment by momala454** [comment]
yes that's what i understood, but generating "support" or "adherence", should make something to fix this, no ?

**Comment by smartavionics** [comment]
Yes, in general, it does. But in this case the gap is smaller than the layer height so it won't possibly put support in there.

**Comment by momala454** [comment]
my layer height is 0.1

**Comment by smartavionics** [comment]
OK, but, remember, you also need at least one layer of air above the support otherwise it will never separate from the part being supported. If you really want support under that model you need to raise it sufficiently. Here I raised it to 0.5mm and it put support under the whole model...

![screenshot_2018-11-13_22-41-01](https://user-images.githubusercontent.com/585618/48447921-4e069e00-e795-11e8-9310-b02f258a9a57.png)

**Comment by momala454** [comment]
so no "automatic" solution in cura, i have to manually verify that the object is not floating and if it does, put it underground or above ?

**Comment by smartavionics** [comment]
Correct. Goodbye.

**Comment by momala454** [comment]
can you consider adding a feature that detect this kind of problem and warn or automatically find solutions ?

**Comment by alekseisasin** [comment]
Hi @momala454 , I think it is out of the Cura scope. It is normal practice before sending Gcode to a printer user needs to ensure that it model is correctly prepared. "Detect this kind of problem" - this is a feature request. If you have a clear idea of how it should work, you can always make a pull request and even propose your solution.
If you do not mind to close the issue, because @smartavionics answered your question.

**Comment by momala454** [comment]
thank you
