### ISSUE TITLE
[3.6.0] Mesh problem dialog disappears

### ISSUE THREAD

**Issue by resnbl** [Ultimaker/Cura#4808]
**Application Version**
3.6.0

**Platform**
Mac OS 10.14.1

**Printer**
Creality CR-10

**Steps to Reproduce**
Open Cura, drag/drop (bad) .stl file into Cura.

**Actual Results**
A dialog box flashes by at the bottom of the screen too fast to be read. No model is displayed on screen. Log contains "Mesh has overlapping faces!".

**Expected results**
If Cura cannot process the input .stl, the dialog box should stay on the screen until it is dismissed by the user. (So I believe this is more of a UX issue than an actual processing bug.)

**Additional Information**
See log line number 229.
[cura3.6.log.zip](https://github.com/Ultimaker/Cura/files/2586911/cura3.6.log.zip)

Here is the "bad .stl" in question
[wrapping_paper_cutter.stl.zip](https://github.com/Ultimaker/Cura/files/2586919/wrapping_paper_cutter.stl.zip)

Update: After completely clearing out Cura and reinstalling, the log message goes away.  However, a dialog still flashes by, but may be the "item too small" message (model does not properly indicate mm instead of inches).

**Comment by diegopradogesto** [comment]
I can correctly load the STL. the dialog box flashing is probably the "Loading gcode" and it does it really quickly because it's a very light file.

The problem is that CuraEngine is not able to provide any layer data because it's too small. Maybe try changing the size of the model or the settings.

Please attach a project file instead of only the STL to better analyze your case.
