### ISSUE TITLE
Feature request: Layer Thickness

### ISSUE THREAD

**Issue by pixxmedia** [Ultimaker/Cura#4840]
Why is it not possible to print the outer walls in a different thickness than the inner walls? I can control the printing speed separately, so why not also the wall thickness? 
It would save a lot of time in printing and make a lot of things easier. 
Please add this feature to your next update.

**Comment by Ghostkeeper** [comment]
You can control the thickness of the outer wall separately, yes. Search for the setting "Outer Wall Line Width" to control how wide the outer wall should be. Note that, by mathematics, there can be only one outer wall, so that width is only for the single line of outer wall. The rest of the wall thickness will be filled with inner walls.

If you meant to increase the layer thickness (in Z direction) of some wall lines, that is infeasible since these outlines will often not be directly on top of each other. Even when the user thinks that his surfaces are completely vertical, they will often not be 100% precisely above each other or just have different vertices for the same outline due to triangulation.

**Comment by pixxmedia** [comment]
That's not exactly what I meant. Maybe a little mispronounced.
