### ISSUE TITLE
[3.6.0] "Post stretch script" removes "G92 E0" from 

### ISSUE THREAD

**Issue by lekv** [Ultimaker/Cura#4878]
**Application Version**

3.6.0

**Platform**

MacOS Mojave

**Printer**

Creality CR-10 with default settings, but the printer doesn't seem to matter (also happens with Ender 3 Pro).

**Steps to Reproduce**

Add the "Post stretch script" in the post processing plugin with defaults and slice a model.

**Actual Results**

The plugin removed the "G92 E0" commands from the start G-code. This causes the extruder to retract all the way back to before the purge lines, and the normal print then doesn't extrude filament for a while.

Here's the start code when using this step:
```
;FLAVOR:Marlin
;TIME:271
;Filament used: 0.0823987m
;Layer height: 0.2
;POSTPROCESSED
;Generated with Cura_SteamEngine 3.6.0
M140 S60
M105
M190 S60
M104 S200
M105
M109 S200
M82 ;absolute extrusion mode
G28 ;Home
G1 F6000 X0 Y0 Z15
;Prime the extruder

G1 F200 E3


G1 F2400 E-5
;LAYER_COUNT:41
;LAYER:0
```

**Expected results**

Don't drop the "G92 E0" commands. Here's the start code without the stretch plugin:
```
;FLAVOR:Marlin
;TIME:271
;Filament used: 0.0823987m
;Layer height: 0.2
;Generated with Cura_SteamEngine 3.6.0
M140 S60
M105
M190 S60
M104 S200
M105
M109 S200
M82 ;absolute extrusion mode
G28 ;Home
G1 Z15.0 F6000 ;Move the platform down 15mm
;Prime the extruder
G92 E0
G1 F200 E3
G92 E0
G92 E0
G1 F2400 E-5
;LAYER_COUNT:41
;LAYER:0
```

**Additional Information**

**Comment by diegopradogesto** [comment]
AFAIK this was already fixed in master (here https://github.com/Ultimaker/CuraEngine/pull/909) and it will be available in the next release.

**Comment by sgtnoodle** [comment]
I just tried the post stretch script and got the same bad behavior where all `G92 E0` statements were gone from the post-processed gcode. It's 2019 and I installed from the master maybe a month ago, so I don't think that referenced PR fixed it.

Since the G92's were gone, my printer firmware error'ed out on the script due to an excessively large extruder movement.

Reading through that PR referenced when closing this issue, it doesn't seem like it has anything to do with the post-stretch script. Reading through the post stretch script, it looks like the parser special cases G92. I'm guessing that it is just baking in all offsets into the post-processed gcode. It doesn't seem so good that it's mucking with the printer's start and end scripts though. Also, that referenced CuraEngine PR has a comment claiming that some firmwares suffer from quantization errors when operating on large-in-magnitude extruder positions.

I'm not familiar with the intricacies of the post stretch math. Does the extruder motion need to be mucked with, or could the slicer's extruder commands be better preserved in the post-processed output?

**Comment by Ghostkeeper** [comment]
Indeed that PR is only on CuraEngine so it couldn't have fixed anything in the post-stretch script. I don't think this issue is solved.

> I'm not familiar with the intricacies of the post stretch math. Does the extruder motion need to be mucked with, or could the slicer's extruder commands be better preserved in the post-processed output?

The post-stretch script is intended to change the locations where the nozzle is moving, but retaining the E-values as they are so that you're technically underextruding (iirc). I don't see why it needs to do anything with `G92` other than reading it to detect travel moves properly. I think the special handling in the code is for that.

**Comment by Ghostkeeper** [comment]
I made a fix for this that solves the issue. It doesn't seem to give any problems with the models that I tried.

If you want a preview, you can download the new version of this script here: https://raw.githubusercontent.com/Ultimaker/Cura/master/plugins/PostProcessingPlugin/scripts/Stretch.py

If you're on Windows you can install that script by putting the .py file in `C:\Program Files\Ultimaker Cura 4.1\plugins\PostProcessingPlugin\scripts`, overwriting the old file.

**Comment by sgtnoodle** [comment]
Printing with it now. So far so good! Thanks for fixing the script so quickly. I'm really excited about the potential improvements this script will have on my prints' dimensional accuracy.

Re: retained E-values and underextrusion, I think the idea is that, after properly tuned post-processing, the extruded plastic ends up where the slicer originally intended it to go. Therefore, the original extrusion amount should be just right.

**Comment by sgtnoodle** [comment]
Well, my test print error'ed out halfway through due to a failed sanity check in my firmware (klipper). The post-processed script commanded a move in X-Y during an un-retract extruder motion. The firmware figured it wasn't a retraction move and didn't like the high rate of extrusion relative to the X-Y motion.

Vanilla cura gcode:
```
G1 F2400 X127.825 Y128.429 E1607.20441
G1 X127.755 Y128.499
G0 F9600 X127.755 Y129.19
G1 F1800 E1606.60441
;MESH:NONMESH
G0 F9600 X91 Y129
;TIME_ELAPSED:943.928928
;LAYER:50
;MESH:10-20-40-CalibrationObject.stl
G0 X91 Y129 Z10.2
;TYPE:WALL-INNER
G1 F1800 E1607.20441     ; This seems to make sense
G1 F4800 X91 Y111 E1607.82416
G1 X109 Y111 E1608.44391
```

Post-processed version:
```
G1 F2400 X127.825 Y128.429 E1607.20441
G1 X127.755 Y128.499
G0 F9600 X127.755 Y129.19
G1 F1800 E1606.60441
;MESH:NONMESH
G0 F9600 X91 Y129
;TIME_ELAPSED:943.928928
;LAYER:50
;MESH:10-20-40-CalibrationObject.stl
G0 X90.929 Y129.071 Z10.2
;TYPE:WALL-INNER
G1 F1800 X91 Y129 E1607.20441     ; This seems a little off
G1 F4800 X90.929 Y110.929 E1607.82416
G1 X109.071 Y110.929 E1608.44391
```

My guess is that this is a bug unrelated to the G92 fix. One could argue this is a klipper issue, but on the other hand the little X-Y shimmy on the Z movement doesn't seem to be helping anything either, and didn't seem to occur on the previous 50 layers. Should I make a new issue for it?

**Comment by Ghostkeeper** [comment]
You could make a ticket out of that, yes. I don't think I could fix the issue with that information though. It's all pretty vague and detailed, and one specific case out of 50 layers where there is 0.6mm extra filament movement is not going to make it to our priority list.
