### ISSUE TITLE
Cura expert config window clipped

### ISSUE THREAD

**Issue by chrisspen** [Ultimaker/Cura#491]
For any screen size less than or equal to about 1280x800, the "Expert config" window accessed from Expert->Open expert settings is nearly unusuable because much of the dialog extends beyond the lower part of the screen, including the ok/cancel buttons.

Ideally, there'd be a scroll bar to access all parts of the dialog.

**Comment by TMHogenhout** [comment]
This issue is regarding legacy Cura. You can post your issue here: https://github.com/daid/Cura

But as I said this is legacy, so this issue will probably not be fixed. I would advice waiting for the next major release of Cura, planned for december. In the meantime you can ofcourse always try the beta version of the new Cura: http://software.ultimaker.com/Cura_closed_beta/
