### ISSUE TITLE
Z Hop should work at travel speed!

### ISSUE THREAD

**Issue by sozkani** [Ultimaker/Cura#4944]
[CFFFP_testslice.zip](https://github.com/Ultimaker/Cura/files/2653681/CFFFP_testslice.zip)

**Application Version**
version 3.6 and all other older versions too.

**Platform**
windows

**Printer**
FLSUNQQ

**Steps to Reproduce**

**Actual Results**
Z Hope during the printing  lift up with printing speed and leaves out a lot of material. It may be not retracting correct way.

**Expected results**
Travel speed Z hope.

**Additional Information**
does not import all Profiles settings from previous versions.

**Comment by pediegoivan** [comment]
I agree or at least a speed control for hop speed should be added!

**Comment by smartavionics** [comment]
It does, my travel speed is 300 mm/S and that's the speed it hops at. 

![Screenshot_2019-05-15_08-57-27](https://user-images.githubusercontent.com/585618/57758442-9cb6d580-76ef-11e9-8715-507f4ef8b0a6.png)

You need to turn off "Z Hop Only Over Printed Parts".

**Comment by Ghostkeeper** [comment]
The horizontal movement of the Z hop is performed at the travel move. The vertical movement is performed at the "Maximum Z Speed". This is a separate setting. You want this to be a separate setting because the Z axis is typically a lot slower than the other axes to move, and causes ringing if there are too many vibrations on it.
