### ISSUE TITLE
Layerview: different extruder => different color

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Cura#504]
Make it so that different extruder trains are visualized differently.

Make sendPolygons of CuraEngine also send extruder_nr.

**Comment by Ghostkeeper** [comment]
Requires some thought on how to differentiate the colours between multiple nozzles, while keeping the associations of colours with walls, support, etc. consistent. Perhaps we should vary the saturation? Pastel vs. deep colours?

For one thing, I think it'd be good to select two colours and vary linearly between them, since that will generalise well to more than two nozzles.

**Comment by BagelOrb** [comment]
That or make it togglable for what you use different colors: either visualize as it is now, or color the segments based solely on extruder_nr and switch between these two with a button.

**Comment by fieldOfView** [comment]
Layers are now shown in a darker color if they are printed with an "inactive" extruder. The "active" extruder is determined by the currently selected extruder-tab.

Issue can be closed
