### ISSUE TITLE
[Request] Settings visibility export

### ISSUE THREAD

**Issue by Liger0** [Ultimaker/Cura#5047]
Hi there.
There are much profile settings option so it requires much times to setup the visibility of the ones you need everytime, and then after resetting them for any reasons it a loss of time.
Would it be possible to implement an option to export the visibility settings in a file?
Thanks.

**Comment by Ellecross** [comment]
Sounds like a nice idea. Thanks @Liger0, I'm going to raise this idea to the Cura team. If a ticket gets created as a new feature, I'll update you. ;)

**Comment by Ellecross** [comment]
Ticket for a new feature created. 
Devs see CURA-6071

**Comment by fvrmr** [comment]
We are constantly working on making Ultimaker Cura better. Our community is a big part of that by requesting new features and reporting bugs. 

To be able to focus on the most requested and needed features from our community and from Ultimaker, we have decided to remove this feature request from our backlog. We believe we will not work on this anytime soon and will therefore defer this issue.

Since Cura is open source, you or anyone else is more than welcome to work on this issue and create a pull request yourself.
