### ISSUE TITLE
[3.6.0] Brim underextrudes when only edge of part touches build plate

### ISSUE THREAD

**Issue by PsyonicOne** [Ultimaker/Cura#5080]
**Application Version**
3.6.0

**Platform**
Linux

**Printer**
Custom FFF

**Steps to Reproduce**
Add part to GUI, make sure "brim" is ON, slice, print, observe results

**Actual Results**
The first layer, the brim, has severely under-extruded lines

**Expected results**
Properly extruded lines

**Additional Information**
I have observed this with any part where only a single edge touched the build plate. The simplest way to recreate it is to drop in a cube, rotate it 45deg so that only a single edge is touching the plate and slice with a brim, then print.
To make the part work, one only needs to drop the model into the build plate a small amount and re-slice.
I've attached two .3mf files for you to look at as well as the STL used.
Hope this helps in some way! 

[BrimIssue.zip](https://github.com/Ultimaker/Cura/files/2716354/BrimIssue.zip)

**Comment by Vandrasc** [comment]
Hi @PsyonicOne , I know we weren't very prompt with our reply, but thank you for your feedback. 

I tried to reproduce using the project files you attached but the brim is correctly generated for me.

Does the issue also occur in the latest 4.1 version of Cura?  If still an issue for you, please re-open the ticket and we will see what could have gone wrong but I expect this to be already fixed in 4.1.

Thank you!
