### ISSUE TITLE
[3.6.0] Internal overhangs printed in mid air

### ISSUE THREAD

**Issue by AndreKR** [Ultimaker/Cura#5143]
I'm printing [this file](https://www.thingiverse.com/download:2772014) with a layer height of 0.3 mm and a 5% grid infill. ([Cura project](https://github.com/Ultimaker/Cura/files/2742379/AI3M_Sides.3mf.zip))

The model contains some holes:

![image](https://user-images.githubusercontent.com/1188538/50924994-5d326100-1451-11e9-9ca1-a27bccf677f9.png)

The problem is that Cura prints two layers of infill and then tries to put the bottom of the hole on top of thin air:

![image](https://user-images.githubusercontent.com/1188538/50925294-39234f80-1452-11e9-847d-6cd7d92b2c95.png)

I kind of expected it to print (more dense) infill as some kind of internal support.

**Comment by smartavionics** [comment]
> I kind of expected it to print (more dense) infill as some kind of internal support.

It doesn't treat the bottom of holes any different to any other skin region. As far as the slicer is concerned, below that hole is a solid region (after all, the model is solid there, isn't it?) The fact that you have chosen to make the solid region very porous is not taken into consideration.

**Comment by AndreKR** [comment]
Sure, it is a skin region, but a very small one, smaller than the infill grid... shouldn't it print additional infill there? Aren't small skin pieces a common enough use case?

**Comment by smartavionics** [comment]
You can use the expand skin setting to expand those skin regions under the holes so that they span more infill lines. That was the primary reason that setting was created (I know cos I added it to Cura). But, really you have got to expect problems when using 5% infill. BTW, you will get better support if you use gyroid infill.

**Comment by AndreKR** [comment]
While the feature I was looking for (print more infill to support disconnected skin) doesn't exist, your answer kind of solves my problem, so I'm going to close this issue.

**Comment by tablatronix** [comment]
Is there a better solution to this now? Infill supports or something?

**Comment by Ghostkeeper** [comment]
Infill Support will support the top side just as well as the small feature a bit lower. The only thing it really does is to not support top sides that are steeper than the overhang angle.

Cura has no real method to "aim" infill at protruding pieces except Gradual Infill and the Cubic Subdivision pattern. Gradual Infill also supports the top side just as much as the rest but will make the denser infill a bit lower for your internal cavity. Cubic Subdivision places denser infill all around the protrusion but in this case will have very little effect since the object itself is fairly thin already.

**Comment by tablatronix** [comment]
I still have yet to find a good solution to allow holes, bosses and features to be excluded from infill, or have a denser infill, so they are not using the top skin for strength.

Could I use mesh overlap overrides?


![Screen Shot 2020-09-01 at 9 39 03 PM](https://user-images.githubusercontent.com/807787/91926125-294a2600-ec9c-11ea-93f2-58aaf8c3b1bb.png)


interestingly enough, I have managed the opposite, no infill... useless but interesting. ( this is infill support <90º)
![Screen Shot 2020-09-01 at 9 48 53 PM](https://user-images.githubusercontent.com/807787/91926487-fc4a4300-ec9c-11ea-8aaa-957af71957c2.png)

**Comment by Ghostkeeper** [comment]
Did you try the (relatively) new Skin Edge Support Thickness setting?

**Comment by tablatronix** [comment]
I will try it, I think I have not installed the update yet

**Comment by printingotb** [comment]
You can use a denser infill with a couple of "gradual infill steps" enabled. That way it will halve the density for each step you add. So if you set it 20% and two steps, it will print it at 20% only near the top layers and then reduce it first to 10% and then to 5%. Use the  "Gradual infill step height" setting to determine how far below the supported layers it does it.

**Comment by tablatronix** [comment]
Just an update I have been using Skin Edge Support constantly now, Good tip for the infil steps, I tried it previously but could not get the gradation right, but did not really understand it at the time.
