### ISSUE TITLE
Nozzle / Filament clean button on printer monitor

### ISSUE THREAD

**Issue by jgwinner** [Ultimaker/Cura#5146]
**Application Version**
3.6.0

**Platform**
Windows 64 (10)

**Printer**
Creality CR-10 (Probably printer independent)

**Steps to Reproduce**
When I need to change filaments or debug a problem, I frequently have to do the following:

1. Preheat the nozzle, possibly the bed
2. Raise the Z axis by a large amount
3. Possibly turn off the motors (I think this gets done for us)
4. Go to the printer menu
5. Navigate to Prepare->Move axis->1mm->Extruder
6. Watch the fiber, see how it's going
7. Menu times out, so again go to Prepare->Move axis->1mm->Extruder
8. Sit back down at PC, home the Z

**Enhancement**
It would be great if there were a button on the Printer control to do all of this in one step. I could paste in G code.

**Additional Information**
An even better, more general suggestion would be a way to paste in buttons that would call arbitrary G code as desired; although this might conflict with other operations. Maybe the button could be marked as "during pause only" or something in the setup. As is, the gcode line is deleted every invocation.

Just an idea. I'm still a n00b with all of this, and I made a mess out of working with ABS and had to do the above steps a LOT. Anytime I do something repetitive a lot, I stare at the automation and think "Hmmm"

On the other hand, maybe you pro's never have to do this :)

**Comment by nallath** [comment]
Well, the issue, in this case, is that Ultimaker printers tend to have controllers on them which have the procedure that you describe ingrained (thus there being no need for Cura to re-implement that).

Since most of the developers that work on Cura are paid for Ultimaker, we primarily focus on functions that benefit those machines (and if they happen to also improve other printers is a secondary benefit, but not the reason why we make those changes). This does mean that there is little chance of us actually building the feature (and we also don't actually have all the printers that this should work on, which further complicates matters)

**Comment by jgwinner** [comment]
Ah, understood. Your printers are fantastic (as is the software), just a little out of my reach :)

Thanks for listening.

It's open source, right? Can I take a look? I'd branch it, I wouldn't go playing in your repository, I realize you don't know me. OTOH I haven't done QT in a long time, so it would probably take me a while. My current printer issue's over, it's not as huge of a deal, I just thought it was odd you couldn't extrude from the monitor page.

I think the Macro capability on the device monitor page would be a fantastic thing - could make implementing new features a snap.

Anyway, thanks for the response, and thanks again for the software.
