### ISSUE TITLE
Changing Print Paths

### ISSUE THREAD

**Issue by smithr355** [Ultimaker/Cura#5195]
I have 3 of the same models load for example model 1, model 2 and model 3. Cura is set to print all at once and starts at 1 then to 2 and then 3. Once it is done with 3 it moves back to 1. Is it possible for it to start the next layer at the one it is finishing since it is already there instead of going back to the firat one?

**Comment by smartavionics** [comment]
If my memory is trustworthy, I think this was once possible. But since Cura became multi-threaded to take advantage of multiple CPUs it cannot do that anymore as it computes all the print moves for each layer independently of the other layers. Because of that it doesn't know where the previous layer finished when computing the moves for the next layer.
