### ISSUE TITLE
THE JOB ENDS BUT THE PRINTER DOES NOT RETRACT Z AXIS

### ISSUE THREAD

**Issue by danylipsker** [Ultimaker/Cura#5266]
**Application Version**

**Platform**

**Printer**

**Steps to Reproduce**

**Actual Results**

**Expected results**

**Additional Information**

**Comment by Ghostkeeper** [comment]
NOTHING CAN RETRACT THE Z AXIS
Z AXIS ONLY ROTATE

**Comment by Ghostkeeper** [comment]
In all seriousness though.

The retraction missing at the end of the print is a known issue in the UM2+ firmware, originating from here: https://github.com/Ultimaker/Ultimaker2Marlin/commit/aa89f34a056a5192923e06842e4919ceedc933fd#commitcomment-23464254

It has since been fixed in that firmware but the fix was not published via Cura because it was not properly tested.
A workaround was to put some comments at the end of the g-code. Cura 3.6 should do this. Can we see your g-code?

**Comment by Enverex** [comment]
I've noticed the same thing: Is the printer responsible for the Z axis retraction at the end, or should that be handled by Cura adding something to the generated GCode?

My Duplicator 6 doesn't move the Z axis at the end either, it just homes the head (incredibly slowly, directly over the print I may add, which doesn't seem ideal considering it's still hot and may still have slight extrusion) and leaves the Z axis where it was. Moving the Z axis back at least slightly before homing the head seems like a more sensible choice.

**Comment by fieldOfView** [comment]
What is your end-gcode, as configured in the machine settings? This is where you define what happens at the end of a print.
