### ISSUE TITLE
Fuzzy Skin not working with Support blocker

### ISSUE THREAD

**Issue by presto87** [Ultimaker/Cura#5276]
**Application Version**
3.6.0

**Platform**
Windows 10 Pro

**Printer**
Ultimaker 3

**Steps to Reproduce**
Create a support blocker that covers a section of a part. 
Select the support block
Go to "Per Model Settings"
Select Mesh Type: "Modify Settings for infill of other models"
Under "Select Settings" add "Fuzzy Skin" (for the support block mesh)
Ensure the "Fuzzy Skin" check box under per model settings (with support block selected) is checked.

**Actual Results 1**
No change to the model

**Expected results 1**
Fuzzy skin should be applied only to parts of the model which overlap with the support blocker.

**Steps to Reproduce 2 (Reverse of above)**
If "fuzzy skin" is selected under the main print setup section and setting is shown, but un-checked on the per model settings for the support blocker, THEN it should do the opposite of what is stated above... 

**Actual Results 2**
Fuzzy skin remains applied to the entire model.

**Expected Results 2** 
fuzzy skin should be applied on everything that doesn't overlap with the support blocker.... 

[UM3_ElevatorPad_R1-ISSUE SAMPLE FILE.zip](https://github.com/Ultimaker/Cura/files/2834088/UM3_ElevatorPad_R1-ISSUE.SAMPLE.FILE.zip)

**Comment by Ghostkeeper** [comment]
You selected the wrong mesh type. "Modify settings for infill of other models" only modifies the infill. Since fuzzy skin only applies to the walls, you're not seeing anything different.

Select "Modify settings for overlap with other models" instead. That gives the result that you expect:
![screenshot from 2019-02-06 08-57-30](https://user-images.githubusercontent.com/2448634/52327697-4994fe80-29ed-11e9-9db4-7e08f49410db.png)
