### ISSUE TITLE
[3.6.0] Filament change retraction is backwards

### ISSUE THREAD

**Issue by Kinlateral** [Ultimaker/Cura#5313]
**Application Version**

3.6.0

**Platform**

Windows 10

**Printer**

Ender 3

**Steps to Reproduce**

Enable filament change in post processing

**Results**

When enabling "Filament Change" in post processing, it defaults to an Initial Retraction value of 30.0mm and a Later Retraction Distance of 300.0mm. However, these values actually result in extrusion rather than retraction. The values need to be set to negative to make it actually retract.

**Comment by Ghostkeeper** [comment]
That seems to be printer-dependent then, because we originally had it backwards and then got the same bug report. The filament change is implemented with the M-code `M600`, so it could be that different firmwares are interpreting it differently. The [RepRap Wiki](https://reprap.org/wiki/G-code#M600:_Filament_change_pause) seems to say that it should be a positive number, because it says "Retract Distance" rather than something like "Delta E".

**Comment by fiddlekrazy** [comment]
I the Ender 3 and had the same problem. 'Ghostkeeper is right, you have to make it a negative to work.

**Comment by IvenBach** [comment]
Application Version: 4.6.1
Platfrorm: Windows 10
Printe: Ender 3 Pro

Just bit by this issue.
Here to confirm the `Initial Retraction` is backwards and extrudes filament. Submitting a value of `50` and saving the gcode emits `E50.00`. Changing it to `-50` does **NOT** emit any command.

**Comment by GregValiant** [comment]
Can this be closed or is it still an issue?
