### ISSUE TITLE
Allow changing retraction speed/length/prime speed in ChangeAtZ

### ISSUE THREAD

**Issue by Yannik** [Ultimaker/Cura#5321]
This would be very helpful for retraction calibration towers like this:

![image](https://user-images.githubusercontent.com/801996/52910199-5f7bac80-3294-11e9-83f2-bb4c13bc4084.png)
These can currently only be sliced with simplify3d :-(

**Comment by Ghostkeeper** [comment]
We find ChangeAtZ's current implementation to be hard to maintain. So we don't, or hardly, change it. I wouldn't put your hopes up. But if someone does want to tackle this, please make sure that this works together with other features of ChangeAtZ, such as changing the flow (which shouldn't affect the retraction distance).

**Comment by Venoryk** [comment]
I second this. I was just attempting to configure a retraction test to get my printer dialed in only to find that I would have to use S3D in order to do it. As i'm somewhat new to 3D Printing Cura has been the only slicer that I've had any experience with. Would love to see this feature added to Cura.

**Comment by Ghostkeeper** [comment]
This got implemented. It'll be in the upcoming version!

**Comment by Yannik** [comment]
@Ghostkeeper Which version will this be in? 4.5?

**Comment by Ghostkeeper** [comment]
No, the upcoming version would be 4.7.
