### ISSUE TITLE
Top/Bottom Thickness changes not visually represented in Layer View/Layer Thickness view

### ISSUE THREAD

**Issue by Delaser** [Ultimaker/Cura#5355]
When setting Top/Bottom thickness, and top or bottom thickness, it is not visually represented in the layer view and the layer thickness view does not adjust the colour to match.

The layer count also does not change (Eg, Less top layers should mean lower layer count overall)

Pictured:
https://imgur.com/a/0xeToNM
Top layer is set to 0.6mm
layer count is 3
0.6/3 = 0.2
The top layers on the model should be visibly thicker, and yellow coloured.

**Application Version**
3.6.0

**Platform**
Win10

**Printer**
Using Ender3, but seems to be printer agnostic.

**Steps to Reproduce**
Change Top/Bottom layer thickness

**Actual Results**
Layer thickness view does not accurately reflect shell settings.

**Expected results**
Layer thickness view should show colour/thickness difference on top/bottom layers.

**Additional Information**
Chances seem to be applying to the model as the print duration estimate updates after layer thickness changes.

**Comment by Ghostkeeper** [comment]
I think you're having a misunderstanding here. The top thickness indicates the total thickness of the top. Divide that by the layer height and you'll arrive at the number of top layers. All layers still have the same height, apart from the initial layer resting on the build plate. And so you'll still have the same number of layers in total.

If you set the top thickness higher, that just eats away at the infill below it. You'll have less infill and more top skin.

We need every layer to be completely planar (i.e. the same thickness and height) because otherwise preventing collisions between the nozzle and the previously printed parts, as well as preventing big flow changes, becomes a nightmare. Especially in a multi-threaded context where every layer is processed in a separate thread.
