### ISSUE TITLE
No support brim without buildplate adhesion turned on

### ISSUE THREAD

**Issue by Athrabeth1** [Ultimaker/Cura#5508]
**Application Version**
Cura 4.0.0

**Platform**
Windows 10

**Printer**
Creality Ender 3
[CE3_Fan Body Endoscope V4.zip]
(https://github.com/Ultimaker/Cura/files/3005851/CE3_Fan.Body.Endoscope.V4.zip)

**Steps to Reproduce**
Add a brim for support, without buildplate adhesion turned on.

**Actual Results**
No brim inside of the support without turning on other build plate adhesion.
For example a brim, with a width of 0mm, works.

**Expected results**
Support brim controlled separately from buildplate adhesion 

**Additional Information**

**Comment by rburema** [comment]
Hi @Athrabeth1, We know about this issue and even fixed it, but the fix was only applied to the master branch, since it was too close to 4.0 release. The master branch will be the base for the (yet to be made) 4.1 branch, so it'll definitely be in there. (See also #4829 of which it is the easier sub-issue).
