### ISSUE TITLE
Verbose GCode

### ISSUE THREAD

**Issue by CCS86** [Ultimaker/Cura#551]
Is there a reason that Cura isn't posting out GCode which includes all settings? It seems like such a small physical size, for so much valuable diagnostic information. I appreciate that feature even for personal use, but especially in a beta development cycle, I can't imagine it being omitted!

**Comment by Ghostkeeper** [comment]
There was talk of this a while ago. Also in relation to the 3MF file format which allows some settings to go along with the 3D model.

**Comment by BagelOrb** [comment]
I still think it would be nice to include all flattened settings in the gcode.
Could be nice to identify problems in gcode, whether it's a user setting problem, a setting calculation error or a slicing error.

**Comment by Ghostkeeper** [comment]
I made a ticket to do that (save all settings instead of just the ones that are not saved to a profile). But it got rejected by our project manager for being older than 12 weeks.

**Comment by ianpaschal** [comment]
The reason for this is because we find it vastly more useful to see which settings have been changed when analyzing print quality. Including all settings would actually make this more difficult so we’ve decided that we will not take time to fix it, and are marking it as `Status: Won’t Fix/Do` and closing the issue.
