### ISSUE TITLE
Top/Bottom thickness (mm) entirly broken

### ISSUE THREAD

**Issue by dgrat** [Ultimaker/Cura#5540]
Still ignoring the values, when previsouly the number of layers was set. 
The layer number must be updated if the value is changed,

![grafik](https://user-images.githubusercontent.com/4668178/55288794-0c316980-53bd-11e9-844c-30472782fc53.png)

**Comment by smartavionics** [comment]
For me, using my master branch based Cura, changing either the Layer Height or the Top/Bottom Thickness settings changes the values of Top Layers and Bottom Layers. I can also set the number of layers explicitly but don't need to when those other settings are changed. Of course, if you do set the value of Top Layers or Bottom Layers explicitly, then you would not expect changes to Layer Height or Top/Bottom Thickness to have any effect.

**Comment by Ghostkeeper** [comment]
Going to assume your reproduce steps here because you didn't write them down. I'm assuming that you changed the Bottom Layers setting, then changed the Top/Bottom Thickness setting and expect the Bottom Layers setting to change.

That's the wrong expectation. Bottom Layers overrides Top/Bottom Thickness.
