### ISSUE TITLE
[4.0.0] Arrange all models CTRL+R

### ISSUE THREAD

**Issue by Martin-S-2019** [Ultimaker/Cura#5555]
**Application Version**
4.0.0

**Platform**
Win 7 Pro

**Printer**
Ultimaker 3

**Steps to Reproduce**
Arrange all models CTRL+R

**Actual Results**
Wrong postions

**Expected results**
A better arrangement

**Additional Information**

![C1](https://user-images.githubusercontent.com/49182629/55387391-a9151380-5531-11e9-9a95-171b6c80abf1.JPG)

![C2](https://user-images.githubusercontent.com/49182629/55387422-b9c58980-5531-11e9-8443-cb965174b2d2.JPG)

![C3](https://user-images.githubusercontent.com/49182629/55387538-e24d8380-5531-11e9-88c3-998c24c9b6a4.JPG)

![C4](https://user-images.githubusercontent.com/49182629/55387549-e7123780-5531-11e9-93a5-6b43026ff678.JPG)

[Cura.zip](https://github.com/Ultimaker/Cura/files/3033024/Cura.zip)

**Comment by nallath** [comment]
This is because the arrangement algorithm is pretty damn naive. It currently tries to put the largest object in the middle and then put all the other objects around it. That logic tends to work okayish if you have one large model and a bunch of smaller ones but it tends to break down fast if that's not the case.

We still have a ticket on the backlog to spend time on it and it's also one of the areas where I still want to get some (master) graduate(s) for to do some more research on, but I don't think this will be fixed any time soon.

**Comment by supernovae** [comment]
Just confirming i'm seeing this same behavior. It did work for the most part in cura 3.x but i also noticed when i import a couple of models in cura 4 that the models import off the virtual build plate after the first one is imported. Have to change my view and drag them back into build plate.
