### ISSUE TITLE
Extruder 1 Start G-Code does not get called at first layer

### ISSUE THREAD

**Issue by tarchive** [Ultimaker/Cura#5629]
**Application Version** 4.0.0

**Platform** Windows 10 x64

**Printer** Custom Delta build with Smoothieboard

**Steps to Reproduce** 
1. Create machine profile with two extruders. 
2. Assign different startup G-code for each extruder.
3. Slice a multi extruder print.
4. Examine G-code 

**Actual Results** Generated G-Code skips/does not include extruder 1 startup-G-Code for first layer. 
For Example this is the current order of operations in the G-Code:
1. Printer Startup G-Code              
2. Layer 1, Extruder 1, Main G-code
3. Layer 1, Extruder 2, Start G-code   
4. Layer 1, Extruder 2, Main G-code
5. Layer 2, Extruder 1, Start G-code
6. Layer 2, Extruder 1, Main G-code
7. Layer 2, Extruder 2, Start G-code   
8. Layer 2, Extruder 2, Main G-code

**Expected results**
Extruder specific G-Code should run before the its main layer G-Code
For Example:
1. Printer Startup G-Code       
**2. Layer 1, Extruder 1, Start G-code**
3. Layer 1, Extruder 1, Main G-code
4. Layer 1, Extruder 2, Start G-code   
5. Layer 1, Extruder 2, Main G-code
6. Layer 2, Extruder 1, Start G-code
7. Layer 2, Extruder 1, Main G-code
8. Layer 2, Extruder 2, Start G-code   
9. Layer 2, Extruder 2, Main G-code

**Additional Information**
If i was to wager a guess, its because the first line of actual G-Code calls T0 (extruder 1) active  then starts the heating process. From that point the routine that checks whether the extruder specific G-Code should run determines the extruder did not change and does not call the start G-Code.
Only when the extruder switches to T1 (extruder 2) or back to T0 from T1 does it determine the Start G-Code should run.

In my case this is not major because i was only relying on the the extruder specific G-Code for a wiping sequence with offsets matching the corresponding extruder.  Luckily having enough clearance space, i just increase the wipe distance to catch both nozzles. No an efficient path but still works.

**Comment by Ghostkeeper** [comment]
This is intentional. It gives a greater control. The extruder start and end g-codes should only get executed upon an extruder switch. If you want it to get executed at the beginning as well, you can still put it in your start g-code. It requires some copy-paste work, but it's not all too much work.

On the other hand, some printers want to execute their extruder switching code only when actually switching and not on the first layer. Like, you might need to do some print head movement for the tool swap, or a certain method of priming that is different from what's being done on the first layer because you can't wipe it on the build plate any more. For those printers, it's good that the switching code is not executed on the first layer.
