### ISSUE TITLE
It uses a very long time when slicing tall models with some support blockers. Hardly any cpu usage

### ISSUE THREAD

**Issue by Silithas** [Ultimaker/Cura#5642]
https://i.imgur.com/PpNwFJS.png

Cura hardly uses any cpu when slicing. and it doesn't even show up in programs running when i'm sorting by cpu usage.

Using latest 4.0

**Comment by smartavionics** [comment]
Hi @Silithas , please save the project file, zip it and attach to this issue so we can investigate your issue. Thanks.

**Comment by Ghostkeeper** [comment]
Not able to reproduce. Here is the model that I sliced: [tall_support_blocker.zip](https://github.com/Ultimaker/Cura/files/3110820/tall_support_blocker.zip)

Without support blocker this took 17.76860499382019s. Single sample.
With a support blocker this took 18.53211522102356s. Single sample.
It would stay at about 350% CPU usage throughout the slicing process on my computer, except that it dipped to about 25% halfway through support generation for a second, for both slices.

**Comment by Silithas** [comment]
> Hi @Silithas , please save the project file, zip it and attach to this issue so we can investigate your issue. Thanks.

https://www.dropbox.com/s/idrmtshhnxgwswj/CE3_Gears1_V8E_PrintInPlace_BasicSupports.rar?dl=0

**Comment by Ghostkeeper** [comment]
That RAR archive seems to be corrupt. My Archive Manager application can't open it, anyway. Is it a RAR or did you rename it?

**Comment by Silithas** [comment]
Extracted fine here. Used winrar. Will zip it then instead of rar.

**Comment by Silithas** [comment]
Also yes, it was a rar.

**Comment by diegopradogesto** [comment]
The project file that you attached is only one object, and no support blockers are added. Do you mean "Tree supports" (because I saw you have that option enabled)? Actually when trying to slice it, it takes very long time, but when I disable tree supports, it's much faster. Checking the CPU usage, it's using almost 100%.

![Screenshot 2019-06-20 at 12 15 52](https://user-images.githubusercontent.com/15830521/59843710-65c08900-9359-11e9-8f36-9a5795ed405f.png)
