### ISSUE TITLE
Bottom Hole filled only on multi-model

### ISSUE THREAD

**Issue by FHSES** [Ultimaker/Cura#5670]
**Application Version**
 4.0.0

**Platform**
Win10

**Printer**
BQ Witbox2
[BQW2_4x_Custom_EmptyD6.zip](https://github.com/Ultimaker/Cura/files/3121588/BQW2_4x_Custom_EmptyD6.zip)
[BQW2_1x_Custom_EmptyD6.zip](https://github.com/Ultimaker/Cura/files/3121589/BQW2_1x_Custom_EmptyD6.zip)

**Steps to Reproduce**

When i slice 1 model the bottom hole is supported
If I multiply the model the bottom holes are filled!

**Actual Results**

The parts to print is wrong

**Expected results**

The parts to print should good

**Additional Information**

Even with 1 part it is hard to find the parameters to not have the bottom hole filled

**Comment by smartavionics** [comment]
Hello @FHSES , I think the problem is with the model as the Cura meshtools finds problems...

![Screenshot_2019-04-26_15-19-48](https://user-images.githubusercontent.com/585618/56814313-d3a77300-6836-11e9-948d-747904c54ac5.png)

BTW, you can probably save a little time when printing by using an Infill Layer Height of 0.2 (or maybe even 0.3).

**Comment by FHSES** [comment]
Hello,
If i put only one model, there is no problem with the bottom holes!
![1x_Cust](https://user-images.githubusercontent.com/50021647/56884717-f02bf100-6a6a-11e9-852b-8cb0f2904c6b.PNG)

But if i only multiply the model... no more hole at the bottom! 
![2x_Cust](https://user-images.githubusercontent.com/50021647/56884747-03d75780-6a6b-11e9-8928-efd3be3ba2ef.PNG)

and not depending of witch face is down (Customizable Dice)
![Dice](https://user-images.githubusercontent.com/50021647/56884949-89f39e00-6a6b-11e9-9876-96c17e450433.PNG)

**Comment by smartavionics** [comment]
All true, but that doesn't get away from the fact that the model itself has issues. Fix the model first and then the slicer's performance can be evaluated.

**Comment by FHSES** [comment]
> BTW, you can probably save a little time when printing by using an Infill Layer Height of 0.2 (or maybe even 0.3).

Yes Sure! Depending of the quality expected!

**Comment by FHSES** [comment]
> the fact that the model itself

You right! they were issues in the model (flipped faces)
But I don't understand why the problem was solved with 1 model and not with multiples.

Thank You

**Comment by Ghostkeeper** [comment]
Indeed, you can also see that it's not watertight in X-ray view:
![Screenshot from 2019-04-29 11-41-09](https://user-images.githubusercontent.com/2448634/56888222-c9be8380-6a73-11e9-8511-8d37c533d7a0.png)

If the model is not watertight, then technically there is no inside to your model. A human can understand that the volume that is 99% surrounded by triangles is probably meant to be filled with plastic, but a computer doesn't. Cura tries to close such small gaps at a best-effort attempt, but it is not reliable because there is no real solution to this.

The reason why it suddenly stops working with multiple meshes is because then there are multiple outlines on one layer and the whole problem of closing every single outline separately becomes more complex.
