### ISSUE TITLE
[cura 4.0] Missing floor over irregular cavities

### ISSUE THREAD

**Issue by archer183** [Ultimaker/Cura#5676]
**Application Version**

4.0
**Platform**

Win10x64
**Printer**

Custom
**Steps to Reproduce**

Slice (see attached 4.0 file
**Actual Results**

certain /floor regions are missing, see pictures and attached 4.0 file

![Cura 4](https://user-images.githubusercontent.com/11451382/56943843-2a7ea800-6ad6-11e9-81f4-a5be01efdddf.JPG)

[Cura4badfloor.zip](https://github.com/Ultimaker/Cura/files/3130112/Cura4badfloor.zip)

**Expected results**
Should be a floor as shown in cura 2.5 file and image

![Cura2 5_](https://user-images.githubusercontent.com/11451382/56943860-35393d00-6ad6-11e9-9a2b-b57cbf9b5a4b.JPG)

[Cura2.5proj.curaproject.3mf.zip](https://github.com/Ultimaker/Cura/files/3130110/Cura2.5proj.curaproject.3mf.zip)

**Additional Information**

**Comment by Ghostkeeper** [comment]
I could reproduce this, but it's expected behaviour.

You need to reduce the Skin Removal Width (and probably also Skin Expand Distance) in order to have that bit of skin. This feature is meant to reduce printing time in almost vertical walls by removing thin parts of skin alongside the walls. In your case, it is tuned a bit aggressively I'm afraid.
