### ISSUE TITLE
Select Extruder for Ooze Shield

### ISSUE THREAD

**Issue by theOehrly** [Ultimaker/Cura#5693]
Feature Request:

It would be helpful if one could select the ooze shield to be printed with one extruder only instead of alternating the extruders.

I have run into issues with the ooze shield, for example when printing with flexible filament. The single line wall didn't print very well with it and started to fall apart in places.
Also it is an issue when printing with two filaments that don't stick together very well, making printing the ooze shield more difficult then necessary.

For those reasons I'd prefer an option to select which extruder the ooze shield should be printed with.

**Comment by Ghostkeeper** [comment]
It needs to print the ooze shield first on a layer, because if it doesn't then it won't protect your print against travel moves with oozing at first, until it has been printed. To that end, it needs to always use the first extruder of the layer to print the ooze shield.

Sorry, other constraints are stronger here. I know of the issue with the layer adhesion with some material combinations, but I don't think there is a good fix here.
