### ISSUE TITLE
Temperature

### ISSUE THREAD

**Issue by shape667** [Ultimaker/Cura#5737]
**Application Version**
4.0.0.0

**Platform**
Windows 7

**Printer**
Builder Premium Large

**Steps to Reproduce**
Set print temp to 215 degrees

**Actual Results**
Gcode slices as M104 S220 and M109 S220

**Expected results**
M104 S215 and M109 S215
![2019-05-13 17_22_14-Ultimaker Cura](https://user-images.githubusercontent.com/6159729/57635770-1d6aba00-75a8-11e9-84a2-fbc036e5a999.jpg)
[BPL_Flexi-Dragon_Body.txt](https://github.com/Ultimaker/Cura/files/3173753/BPL_Flexi-Dragon_Body.txt)

**Additional Information**

**Comment by Ghostkeeper** [comment]
Yeah, it's getting warmer isn't it? I'm looking forward to summer as well.

I don't see that as an issue though.

**Comment by Ghostkeeper** [comment]
Oh, sorry. I see that you filled in the form in the comment `<!-- ... -->` tags, which is why it's not showing up here. I'll edit the post to make it visible.

**Comment by Ghostkeeper** [comment]
It's saying `M104 S220` because that's the value for the "Printing Temperature Initial Layer" setting. The authors of your printer's definition wanted the initial layer printing temperature to be 5 degrees higher than the rest.

You'll find that later in the g-code it sets the temperature to 215 and uses that for the majority of the print.
