### ISSUE TITLE
Filament Color change and stepper motors

### ISSUE THREAD

**Issue by fiddlekrazy** [Ultimaker/Cura#5833]
**Application Version**
Cura 4.0/4.1

**Platform**Windows 10

**Printer**
Ender 3

**Actual Results**
Stepper motors are not locked during filament change(s)

**Expected results**
Stepper motors should be locked

**Additional Information**
I never had a problem when I was using the PTFE system on my printer because I didn't have to touch the print head to change the filament so I don't know if the problem existed before I change the printer to direct drive. It took me a while but I finally figured out that the stepper motors (all of them) are not locked during filament change thus the head moves (both Z and X axis) and as I discovered recently so does the bed.

**Comment by smartavionics** [comment]
Hello @fiddlekrazy , please zip up an example of gcode that has this problem and attach to this issue. Thanks.

**Comment by fiddlekrazy** [comment]
The problem is not in the gcode but must be in the post processing plug-in. As you can see, in the gcode attached, there is nothing that either enables or disables the stepper motors. 

[Eye.zip](https://github.com/Ultimaker/Cura/files/3245668/Eye.zip)

**Comment by smartavionics** [comment]
I wonder if your controller has an idle timeout and if you delay when changing the filament, the timeout cuts the power to the steppers?

**Comment by Ghostkeeper** [comment]
Cura tends to assume that the motors remain powered throughout the whole print unless Cura commands it so. For instance, it commands it explicitly to disable power to the motors during a pause for Repetier (and then homes the print head when restarting).

What extra g-code does your printer need to prevent it from disabling power?

**Comment by fiddlekrazy** [comment]
Cura must be commanding the stepper motors to disable. Ender 3 uses Marlin. M600 is the only code that Cura sends to the machine so the disable code must be embedded in the M600 command in Marlin. Does this make sense??

**Comment by Ghostkeeper** [comment]
`M600` by itself doesn't have such an option according to [this documentation](https://reprap.org/wiki/G-code#M600:_Filament_change_pause). There are commands to [enable/disable power](https://reprap.org/wiki/G-code#M17:_Enable.2FPower_all_stepper_motors) to the motors but since it appears that `M600` in itself disables it and doesn't execute any further g-code until the user resumes, it is impossible to add a command in between to re-enable power or something.

If there is nothing that Cura can send to prevent this for your printer, you're really going to have to look towards the firmware developers of that printer. `M600` appears to have some flaws in their implementation.

**Comment by fiddlekrazy** [comment]
I can understand that it disables the extruder motor but I do not understand why it disables the other motors. I guess I will have to try and write a workaround in gcode.
