### ISSUE TITLE
Cura 4.1.0 UI issue, build plate hidden after starting a USB print. 

### ISSUE THREAD

**Issue by krak1369** [Ultimaker/Cura#5834]
Cura 4.1.0
**Application Version**

Windows 7 pro 64
Dell Latitude D630
Mobile Intel 965 Express Chipset

**Platform**

Ender 3
**Printer**

The UI does not refresh correctly after running a USB print. Can not see the build plate. 
**Actual Results**

After closing menu pop up the build plate should be visible again.
**Expected results**

This may have nothing to do with USB printing, but I have seen it twice in a row. after printing via USB. It appears as though the menu is leaving behind the artifact that prevents the build plate from being visible. 
Quiting and restarting is the only work around I have found so far. 
![cura4-1-0-ui-issue](https://user-images.githubusercontent.com/51299699/58766846-8787d680-8538-11e9-8774-8feff8c2f1e3.jpg)
 
**Additional Information**

**Comment by Ghostkeeper** [comment]
I think the actual problem is that your entire top bar is transparent. This gives you a glimpse at the build plate behind the big white screen of the Monitor stage.

Here's how it should look (minus the Profile Assistant stage which is something for developers only):
![Screenshot from 2019-06-03 15-14-24](https://user-images.githubusercontent.com/2448634/58804524-58459800-8612-11e9-96ad-438d5f2a30a7.png)

The big white background is a limitation of the current set-up, because the print monitor does need to have a white background for some connectivity modes (such as wifi with Ultimaker printers) but not necessarily for others, like USB printing.

**Comment by GregValiant** [comment]
I'm cleaning house.
Is this still a problem with current Cura versions (5.8.0 and up)?  Can I close this?
