### ISSUE TITLE
[Question] Can I create a chrome extension to send an STL to Cura?

### ISSUE THREAD

**Issue by mbartlett21** [Ultimaker/Cura#5844]
**Platform**
Windows 10

**Details**
I would like to be able to export straight to Cura from the CAD application that I use ( [Onshape](https://www.onshape.com) ).
Is there any way that I could write a chrome extension to send an exported STL to Cura, or will I just have to download then import?

**Comment by Ghostkeeper** [comment]
There's three methods I can think of that you could approach this, but with various degrees of plausability. For one:

> Is there any way that I could write a chrome extension to send an exported STL to Cura

Chrome extensions can't *start* Cura. At least, I hope not, though I'm no expert with Chrome extensions (I've only ever worked with Firefox). I assume they can't just launch a binary executable since they are sandboxed in Chrome.

A third method, a little better, is to have the Chrome extension talk to Cura via a local socket. Cura uses this technique right now when you log in using an Ultimaker account. The login page is on a web page which refers to localhost:port to send an HTTP request. Cura meanwhile has opened up a web service that listens to HTTP requests on that port.

A third method, probably the easiest: Applications can register themselves to be opened with certain URI schemas. For instance the game store Steam has links like `steam://store/292030` which when clicked would open my favourite game in the Steam application. To implement this they have to register this URI schema at the operating system somehow. How that works is [different for every platform](https://support.shotgunsoftware.com/hc/en-us/articles/219031308-Launching-applications-using-custom-browser-protocols) but certainly doable for the three platforms that Cura supports. This way the user won't even need to install a Cura-side plug-in as long as the Chrome extension delivers the model on a local file (in a file format that Cura can read) in Chrome's temp or download folder and then calls Cura with that file as first parameter.
