### ISSUE TITLE
Automatic brim relative to model shape and size, PLUS skirt.

### ISSUE THREAD

**Issue by ephestione** [Ultimaker/Cura#5874]
**Is your feature request related to a problem? Please describe.**
I like brim in general, it gives the priming function of the skirt, plus it's useful for adhesion.
For larger models though, where the bed adhesion would be sufficient in and by itself, brim is not really determining for adhesion, but rather a hassle to remove afterwards, and in this case a lone N mm long skirt would be helpful to prime the nozzle.
Whereas, for smaller models with small contact area with the bed, for example "pikachu standing on all fours", there should be a N mm long skirt for priming PLUS a generous brim (line-count-wise), otherwise sooner or later I will hear screeching noises where the nozzle is hit by a partially detached and slanted structure that protrudes above the current layer, and I know the print has been f-up because the left front leg of Pikachu has been lost before it fused with the rest of the body (please excuse me for the frequent references to Pikachu, this is the first frivolous print I'm doing in ages, it's for my little son and I've already thrown away 3 times the first few mm's worth of print, yet this reminded me of a problem I've already encountered in the past with other prints all serious and stuff, for replacement parts or prototypes or whatever).

I could just manually change the settings before slicing, but, you know, there's already code to detect automagically where support is best placed, why not letting the code itself also deal with the best strategy for adhesion, and leave the user to only change those parameters like walls count, infill type and density, and other things very specific to the object and its intended use?

**Describe the solution you'd like**
Detect each contiguous contact area of the object with the bed, and apply a different brim size (0-N lines count) relative to it, so for example if the model is of a sitting dog, the front legs will get 10 lines of brim, while the butt+hind legs will probably get 0 lines of brim.
There will be an additional option to have a skirt as well together with the brim (instead of just either of them), so the nozzle priming won't affect the brim extension.

**Affected users and/or printers**
I suppose everyone who happens to print both large and small models, and won't have to change between adhesion settings depending on which of the two he's printing.

**Comment by Ghostkeeper** [comment]
We have this feature, though it works slightly differently. Try setting the Brim/Skirt Minimum Length to be considerably bigger, something like 5000mm or 10000mm.

The solution here works different from what you describe because brims can intersect with each other. If they intersect with each other and some brims need to have more lines than other brims, then the brim lines are going to need to have endpoints, instead of being closed loops. When these endpoints are on the inside brim it doesn't matter much, but on the outside brim they tend to make the brim's adhesion weaker rather than stronger because it provides a spot where the brim starts to peel off due to the shrinking tension provided by the model.

For inside brims, we'd like to implement cutting off the brim at some point in order to fix the bug where "Brim on Outside Only" produces inside brims if there is some other shape inside the hole. That is a different issue though.
