### ISSUE TITLE
Change local profile path from command line? [linux]

### ISSUE THREAD

**Issue by paukstelis** [Ultimaker/Cura#5875]
Is it currently possible to set the path of the local profile overrides, etc. from the command line or as  an environmental variable? In a multiuser environment having each user default to $USER/.local/share/cura adds some difficulty when wanting to define custom printers/profiles/materials.

**Comment by Ghostkeeper** [comment]
It would help to fill in the issue template. What is the problem that this solution is supposed to help with?

I wouldn't expect any difficulties in defining custom profiles when there are multiple users on the computer. My computer has some extra users (like `tor` and `root`) but that doesn't bother Cura one bit because it's stored in my own home directory.
