### ISSUE TITLE
Strange Slicing Result

### ISSUE THREAD

**Issue by RocketNut** [Ultimaker/Cura#5919]
**Application version**

**Platform**

**Printer**

**Reproduction steps**

**Actual results**

**Expected results**

**Additional information**

**Comment by RocketNut** [comment]
I am getting some strange slicing result. The first screenshot shows what I am getting instead what it should look like (second screenshot).

The STL file is too large to attach here so here is a DropBox link::
[https://www.dropbox.com/s/wvijx0ikqe9e2qf/My%20Complete_Disk.stl?dl=0](url)


![image](https://user-images.githubusercontent.com/49567121/59878428-8098fa80-9365-11e9-9939-a05c24d1830f.png)

![image](https://user-images.githubusercontent.com/49567121/59878490-ac1be500-9365-11e9-9a36-1d1ff6a76903.png)

**Comment by RocketNut** [comment]
I forgot to include a screenshot from my CAD that shows the disk as designed.
For some reason I can not pasted here!!!!!

**Comment by smartavionics** [comment]
Now that's what I call a big model (note tiny build plate at the bottom)!

![Screenshot_2019-06-20_21-39-00](https://user-images.githubusercontent.com/585618/59880022-f6bc5200-93a3-11e9-8ff9-b6517a570a52.png)

However, it has problems as loading it causes the Cura Mesh Tools plugin to say...

![Screenshot_2019-06-20_21-38-18](https://user-images.githubusercontent.com/585618/59880037-fb810600-93a3-11e9-9c80-16cfd092f0a0.png)

Fix the model and Cura should be able to slice it.

**Comment by RocketNut** [comment]
Yes, it is very large. When I loaded it I scaled it down to 15%,  then rotated 90 deg to lay it flat. If it's not laid down flat you will have to use support. I design, (with 3D printing in mind) it with X-axis pointing upwards so no supports are needed.  

OH, maybe I should mention I am using 3,4,1, I have too many problems with 4.1.0.
Here is a screenshot of X-Ray view. I never used this features so I do not understand what it is telling me. 

    On Thursday, June 20, 2019, 2:41:16 PM MDT, Mark Burton <notifications@github.com> wrote:  
 
 
Now that's what I call a big model (note tiny build plate at the bottom)!



However, it has problems as loading it causes the Cura Mesh Tools plugin to say...



Fix the model and Cura should be able to slice it.

**Comment by smartavionics** [comment]
I loaded your model into FreeCAD and got it to analyze it. Loads of problems as you can see. You need to fix your model before it can be sliced....

![Screenshot_2019-06-20_22-10-04](https://user-images.githubusercontent.com/585618/59881784-53ba0700-93a8-11e9-9195-7ae0ea8c7c44.png)

**Comment by RocketNut** [comment]
OKI will turn over to CAD support to see what they say.
It's just really strange that it is ONLY this model that has problems.

    On Thursday, June 20, 2019, 3:11:41 PM MDT, Mark Burton <notifications@github.com> wrote:  
 
 
I loaded your model into FreeCAD and got it to analyze it. Loads of problems as you can see. You need to fix your model before it can be sliced....

**Comment by Ghostkeeper** [comment]
Because RocketNut's screenshot didn't work (e-mail attachments to replies to Github don't automatically get posted), here's a screenshot of X-Ray View of your model in Cura:
![Screenshot from 2019-06-21 10-56-35](https://user-images.githubusercontent.com/2448634/59911116-7fbea200-9413-11e9-90bc-325eeead2f43.png)

Initially it showed nothing special but rotating the camera towards the side reveals a bunch of red areas.

> I never used this features so I do not understand what it is telling me.

X-Ray View will show the insides of your model. If there is extra geometry inside, or the walls are not watertight, then it will show red areas. This means that it is ambiguous what the inside of your model is.

Since your model has this extra geometry or missing geometry inside (depending how you look at it), it is ambiguous where the insides of your mesh are going to be. This is why Cura can't figure out what spaces to fill with skin, and why this specific model prints so strangely.

It is not something that we can really fix in Cura realistically. There are tools out there to repair your mesh that go by heuristics, like that the surface that has the fewest sharp corners is the one that you probably intended as the outside of your model. Some suggestions:

* FreeCAD (like SmartAvionics suggested)
* MeshLab
* Blender
* Netfabb

All of these work with heuristics, some better than others. I'd advise you to stay away from the voxel-based ones though, like MakePrintable. They tend to make your print very blocky which is disturbing when actually printed.

I'm closing it because it's not something we can realistically fix.

**Comment by RocketNut** [comment]
OK
I can understand why there might be excess material in the model. It appears the functions I used to draw the part and followed this response to cad support.
Please close this support ticket.

Thanks for the great support. 

 

    On Friday, June 21, 2019, 3:13:22 AM MDT, Ghostkeeper <notifications@github.com> wrote:  
 
 
Because RocketNut's screenshot didn't work (e-mail attachments to replies to Github don't automatically get posted), here's a screenshot of X-Ray View of your model in Cura:


Initially it showed nothing special but rotating the camera towards the side reveals a bunch of red areas.


I never used this features so I do not understand what it is telling me.


X-Ray View will show the insides of your model. If there is extra geometry inside, or the walls are not watertight, then it will show red areas. This means that it is ambiguous what the inside of your model is.

Since your model has this extra geometry or missing geometry inside (depending how you look at it), it is ambiguous where the insides of your mesh are going to be. This is why Cura can't figure out what spaces to fill with skin, and why this specific model prints so strangely.

It is not something that we can really fix in Cura realistically. There are tools out there to repair your mesh that go by heuristics, like that the surface that has the fewest sharp corners is the one that you probably intended as the outside of your model. Some suggestions:
   
   - FreeCAD (like SmartAvionics suggested)
   - MeshLab
   - Blender
   - Netfabb

All of these work with heuristics, some better than others. I'd advise you to stay away from the voxel-based ones though, like MakePrintable. They tend to make your print very blocky which is disturbing when actually printed.

I'm closing it because it's not something we can realistically fix.

**Comment by RocketNut** [comment]
Bingo
I sent the message about excess material to my cad support. I did not do a drawing function correctly causing the excess material. When I redid the function everything fell into place and now slice up correctly, 

Thanks for the great help... Please close this support ticket. Have a great day. 

    On Friday, June 21, 2019, 3:13:25 AM MDT, Ghostkeeper <notifications@github.com> wrote:  
 
 
Closed #5919.
