### ISSUE TITLE
Thin models : sanity check

### ISSUE THREAD

**Issue by yet-another-average-joe** [Ultimaker/Cura#5931]
**Application version**
4.1

**Platform**
Win10

**Printer**
not relevant

**Reproduction steps**

create a thin model (0.2mm thick, 1 layer, draft profile : 0.2mm, 1st layer = 0.3mm)

**Actual results**

the sliced model will be printed with 1 layer, but the thickness is based on the 1st layer parameter ; see generated gcode

**Expected results**

the 1st layer and the layer height should be limited to the model height.

**Additional information**

I imagine that most users will not print such models. But they are usefull for testing purpose (calibration), for spacers, and for TPU gaskets for those who print functionnal parts ; can be really accurate, +-2 or 3 hundredths of mm, measured with a micrometer (no chinese crappy calipers) : such prints are not silly, they are really usefull. I am 100% sure that such a sanity check is easy to implement (2 min() macros)

**Comment by Ghostkeeper** [comment]
> the 1st layer and the layer height should be limited to the model height.

This is not the result I'd expect. Cura takes a sample cross section at Z=0.15mm (with your 0.3mm initial layer height) and anything that crosses that plane gets to be in that one layer. If the model happens to end 0.05mm higher, Cura won't know because it didn't slice at that height. In order to know, Cura would have to slice at Z=0.2mm as well.

For instance, if you have a cuboid that is 0.2mm high but one of the corners is heightened to 0.25mm, would you expect the entire model to print at 0.25mm height? If you have a shape that is 10.2mm high and due to the initial layer height it slices at Z=10.1mm and Z=10.3mm, would you then expect the last layer to have half extrusion?

I think that the experts who do have a use case for single-layer prints and need it to have the same height as the original model (and have the build plate calibrated well enough for it) can just adjust the initial layer height as they see fit. We're not going to implement this.
