### ISSUE TITLE
GCODE Meta features

### ISSUE THREAD

**Issue by aryez91** [Ultimaker/Cura#5962]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I have tons of unusable gcodes accumulating after few months/years.
They are unusable professionally because I don't remember what settings are in those files. Physical size of model, estimated filament, time, quality settings...

**Describe the solution you'd like**
It would be great if cura could write meta data to the gcode.
This could include basic print settings (quality, build plate adhesion, supports),
 non default applied settings, and the model physical properties (size, number of models etc)...

Secondly, it would be nice if cura asked on next launch or something if the printing ended successfully, and  include this new meta information on the source gcode.

**Describe alternatives you've considered**

Today I manually include some settings in the filename: filament required and printing time,
And it's ok but limited.

It would also frequently happen that I'll reslice the original, but that is sometimes a time consuming task.

Another partial alternative is to preview the gcode, but that usually takes a long time and doesn't recompute filament required and time.

Lastly I could save all cura project files and see what the settings were, though this means having duplicate files, occupying hard disk space.

**Affected users and/or printers**
 
People who have clients that ask for reprints of old model.
Anyone who wants to quickly reprint an older file, but want to double check the settings, differentiate variations.
![cura meta features](https://user-images.githubusercontent.com/16970046/60542809-50a60b80-9d04-11e9-8371-dc38e72eb131.png)
 

**Additional context**

**Comment by Ghostkeeper** [comment]
The settings you've changed already get appended to the g-code. It's at the very bottom of the g-code. The model dimensions also get written to the g-code header (in 4.1 only in the Griffin flavour, but since 4.2 with every flavour). However there is no shell integration as you've shown in that screenshot. Cura can import the g-code as a profile I believe though.

**Comment by Ghostkeeper** [comment]
Getting feedback on how good the print went is a separate issue. I once made a prototype that did this here: https://github.com/Ghostkeeper/R2D2 This added a new stage after Monitor where you could fill in how good the print went and it would store this in Cura's configuration folder (rather than in the g-code because the g-code file might not exist at all since we sent the print via USB or wifi, or maybe the file moved, etc.) In my case that feedback was used to tweak your settings better but it could also just be used as reference. In any case, it didn't come through. I don't think we'll implement that feedback tracking unless we find a stronger need for it.

**Comment by GregValiant** [comment]
See PR #15854 It's in line for review.
Can this be closed?
