### ISSUE TITLE
buf is 0

### ISSUE THREAD

**Issue by amparodiazvera** [Ultimaker/Cura#5994]
When I save the Gcode to the SD card, and start to print in the printer, de BUF rapidly goes to 0 instead of 16. why?

**Application version**

**Platform**

**Printer**

**Reproduction steps**

**Actual results**

**Expected results**

**Additional information**

**Comment by smartavionics** [comment]
Hello @amparodiazvera , I think you're going to have to provide more information than that if there is any chance that the issue will be investigated. How about some details of what went wrong?

**Comment by amparodiazvera** [comment]
Hi! I have an Anet A8. And cura 3.6. Every time i try to print with the SD card, the print starts, butthe “buf” on the lcd screen starts from 16 to 0 and the movements of the printer starts to stop. The quality prints are turning horrible because of this. 
I later install the cura 14.07 and printed the same stl file and everything goes great!
I tried with cura 4.1.0 and the same, i tried with another sd car and the same. 
It appears to be a problem with saving de gcode!
Do you know how can i fix this???

Amparo Diaz

**Comment by Ghostkeeper** [comment]
I edited the original post. The stuff between the \<!-- and --\> is invisible to us so your original sentence was hidden.

I don't know your printer's firmware, but it sounds a bit like the motion buffer is running out. The motion buffer is a place in the printer's memory where it stores pre-computed moves that are to be executed by the motors. If the motors go through the moves too fast (because all of the moves are really short) the CPU cannot keep up pre-computing those moves.

You can fix that problem by increasing the setting value for Maximum Resolution (or from 4.0 onwards Maximum Deviation as well). The g-code will be lower resolution, allowing your printer's CPU to keep up. As a result the surface will be slightly rougher for round objects, but not as rough as what you're seeing if the motion buffer is running out; no more blips.

**Comment by Ghostkeeper** [comment]
I'm going to assume that was the problem. If that doesn't fix it, let us know and we'll open the ticket back up to see if there's anything Cura can do.
