### ISSUE TITLE
[4.1.0] Weird, inefficient and useless travel moves

### ISSUE THREAD

**Issue by theWaldschrat** [Ultimaker/Cura#6059]
**Application version**
4.1.0

**Platform**
Windows 10

**Printer**
Creality Ender 3

**Reproduction steps**
Open attached project file:
[Glashalter.zip](https://github.com/Ultimaker/Cura/files/3432140/Glashalter.zip)
Slice, then preview, move down to first layer and replay the last about 20 %.

**Actual results**
Watch the print head bounce back and forth instead of a smooth print movement.
Also note the unretracted travel which leaves a nice, solid string on the print bed:
![Unretracted_Travel](https://user-images.githubusercontent.com/38852807/61885524-3d025500-aefe-11e9-800d-276c5fb0b877.png)

**Expected results**
Smooth, efficient printing without bouncing back and forth and no unretracted travels outside of the model.

**Additional information**
Not much more to say.

**Comment by smartavionics** [comment]
Hello @theWaldschrat , I have sliced your project using my cura build and it doesn't have the problems you mention. That could be because my cura build has fixes for various defficiences in the combing and other features. If you want to try it out, you can find my builds at https://www.dropbox.com/sh/s43vqzmi4d2bqe2/AAADdYdSu9iwcKa0Knqgurm4a?dl=0. They can be installed alongside the Ultimaker buids.

![Screenshot_2019-07-25_16-28-32](https://user-images.githubusercontent.com/585618/61887504-acc21100-aef9-11e9-8965-c9a347401fef.png)

**Comment by Ghostkeeper** [comment]
This is fixed in Cura 4.2 along with the fixes we made for gap filling. Please try the beta!
