### ISSUE TITLE
4.2 upgrade deletes Monoprice Ultimate printer

### ISSUE THREAD

**Issue by donaldnaegele** [Ultimaker/Cura#6104]
4.2 upgrade deletes Monoprice Ultimate printer.

Can you add it back?

Don

**Comment by smartavionics** [comment]
It's caused by a bug in the new way of presenting the printers by manufacturer. Unfortunately, the manufacturer string in the definition for the Ultimate is "monoprice" but the other monoprice printers use "Monoprice". As a workaround, if you can find the file called monoprice_ultimate.def.json in the files installed with Cura, edit it and change the manufacturer name. Hope this helps until the devs can fix the bug.

**Comment by donaldnaegele** [comment]
I can't find that file on my Mac.

Don

**Comment by smartavionics** [comment]
Sorry, I don't have a working Mac installation to look at so I can't help.

Here's an idea, try unziping the attached project file and opening it with Cura and it should install the printer.

In fact, loading any previous project that uses the same printer type should create the printer.

[empty.zip](https://github.com/Ultimaker/Cura/files/3453784/empty.zip)

**Comment by donaldnaegele** [comment]
That worked! Thank you so much.

Don

**Comment by Deneteus** [comment]
I just use the Wanhao D6 profile since its the same printer. I also have the Ultimate.

**Comment by Ghostkeeper** [comment]
I fixed the manufacturer of this printer. Not sure why the lowercase `monoprice` section would disappear. The only place there where we use case-insensitivity is in the sorting key...
