### ISSUE TITLE
4.1.2 Pointless moves 

### ISSUE THREAD

**Issue by Arthzil** [Ultimaker/Cura#6207]
**Application version**
4.1.2

**Platform**
Windows 10

**Printer**
Ender 3
[CE3_FanCover_LevelIndicator.zip](https://github.com/Ultimaker/Cura/files/3505857/CE3_FanCover_LevelIndicator.zip)

**Reproduction steps**
Example - layer 10, around 5th second of playing preview.

**Actual results**
 The head is making pointless zig-zag moves, no extrusion there. The moves are very rapid and are creating artifacts and stringing.

**Expected results**
The move shouldn't even happen.

**Additional information**

**Comment by smartavionics** [comment]
Turning off the Avoid Printed Parts When Travelling reduces the travels somewhat.

**Comment by Ghostkeeper** [comment]
Indeed this is a bug. It should shortcut the combing move there as long as there is nothing in the way. We'll investigate.

**Comment by dferrier1** [comment]
fyi...

I am seeing this same behavior in version 4.4.1 running windows 8.1

**Comment by dferrier1** [comment]
Version 4.4.1 running windows 8.1.

In my gcode file, the behavior starts immediately from the second layer on. 

[CCR10MAX_CR 10 S5 four Trays With Divider v3.zip](https://github.com/Ultimaker/Cura/files/4236816/CCR10MAX_CR.10.S5.four.Trays.With.Divider.v3.zip)

**Comment by smartavionics** [comment]
Please save the project file and then either rename the .3mf file to zip or zip it and attach to this issue. Without that it's hard to help. Thanks.

**Comment by dferrier1** [comment]
My apologies.

Here is the .3mf file. I did not save the original as .3mf so this one is actually simpler but still shows the same behavior. I noticed that I had selected a different profile and it did *not* show the behavior. But with this profile selected (the same as the original) I do see the behavior. I have scoured the settings but do not see anything that could explain this though. 


[CCR10MAX_CR 10 S5 Tray With Divider v3.zip](https://github.com/Ultimaker/Cura/files/4236915/CCR10MAX_CR.10.S5.Tray.With.Divider.v3.zip)

**Comment by smartavionics** [comment]
You have the wipe nozzle thing enabled, turn that off and the wacky moves go away.

![Screenshot_2020-02-21_16-18-06](https://user-images.githubusercontent.com/585618/75051441-ce9e6900-54c5-11ea-847b-6761b6171abd.png)

**Comment by dferrier1** [comment]
Ah yes, I just found that. I had to enable all options visibility to see it though. 

Thanks.

**Comment by Ghostkeeper** [comment]
The original issue is still on our backlog (developers, ticket number is CURA-6725).

**Comment by OutsourcedGuru** [comment]
For what it's worth, I was just scratching my head over this one. There are many sections (large and small) of seemingly-pointless `G0` moves. The sheer number makes me think that this must be a bug. I've tried different infill types and percentages.

Versions: **Cura 4.5.0** and 3.6 on macOS 64-bit
Wipe Nozzle Between Layers: OFF

[5milCamRing_Gyr45.gcode.zip](https://github.com/Ultimaker/Cura/files/4452755/5milCamRing_Gyr45.gcode.zip)

**Comment by Ghostkeeper** [comment]
In your case the travel moves that I consider "pointless" are most likely solved by setting the Z Seam Position to "Shortest".

**Comment by OutsourcedGuru** [comment]
I changed to Shortest as seen here.
![Screen Shot 2020-04-14 at 9 02 31 AM](https://user-images.githubusercontent.com/15971213/79247391-500fd900-7e2f-11ea-992a-3b6f5f013ce0.png)

Nine or ten `G0`s in a row:
```
G1 X54.356 Y54.203 E0.02864
G0 F1800 X57.277 Y52.44
G0 X58.79 Y51.714
G0 X60.386 Y51.197
G0 X62.036 Y50.893
G0 X63.709 Y50.811
G0 X65.38 Y50.949
G0 X67.02 Y51.307
G0 X68.598 Y51.878
G0 X69.803 Y52.504
G0 X73.274 Y54.607
G1 F600 X75.612 Y56.944 E0.10995
```

Is there some reason for this? Is it trying to wipe off excess extrusion in some way?

**Comment by Ghostkeeper** [comment]
It makes multiple travel moves after one another usually because it's trying to avoid hitting a wall, i.e. combing. It will also travel to the inside if it was on a wall while the travel move happens, and will travel through the inside of the object to the closest place of another object if it travels from one object to another. See [this documentation](https://github.com/Ultimaker/CuraEngine/blob/master/docs/generating_paths.md#travelling) for details.

There are also more cases where it might make multiple travel moves after one another, e.g. for an extruder switch with wipe or wiping off the prime tower, but those are pretty easy to recognise in the g-code. Yours just seems to be moving towards the right somewhere while avoiding something with a slightly round edge in the middle.

**Comment by Ghostkeeper** [comment]
This issue was taken off of our backlog, when the quality engineers reassessed priorities. Because the travel moves are usually a tiny fraction of the print time and this issue is really uncommon, we'll have to defer this. That means we're not expecting to fix this issue any time soon (unless more critical cases are discovered).
