### ISSUE TITLE
Loading project ignores profile

### ISSUE THREAD

**Issue by burgi400** [Ultimaker/Cura#6221]
**Application version**
4.2.1

**Platform**
Win 10

**Printer**
CR-10

**Reproduction steps**
Change print settings to own profile
save as project
close cura
open cura
load project 

**Actual results**
standard profile 0.2 in use

**Expected results**
own profile iin use

**Additional information**

**Comment by LipuFei** [comment]
Hi @burgi400 , I can confirm on the issue. The problem is that in Cura 4.1, the default quality profile for CR-10 is `draft`. But in Cura 4.2.1, `draft` is not available for all materials. For example, PLA doesn't have a draft profile.

I think the issues you reported in https://github.com/Ultimaker/Cura/issues/6222 and https://github.com/Ultimaker/Cura/issues/6223 are more or less the same issue.

When you import the custom quality profile you attached in https://github.com/Ultimaker/Cura/issues/6223, you will see and be able to select that custom profile, but after you close and open Cura again, it will be reset to "Standard". This is because that custom profile is based on the `draft` quality. In Cura 4.2.1, certain materials such as PLA do not have a `draft` profile. From the screenshot below, you can see that:

 - There's no draft in the quality profile drop down list with PLA
 - The material PLA control has an orange color, indicating that you currently have a quality profile that's not supported.

![image](https://user-images.githubusercontent.com/2630468/63253751-b2014a00-c272-11e9-9bdc-b66ea112d05a.png)
