### ISSUE TITLE
4.2.1 single pass round features split into multiple passes

### ISSUE THREAD

**Issue by Wdfitzpat007** [Ultimaker/Cura#6230]
**Application version** 4.2.1

**Platform**
Windows 10 pro 64x latest at time of post

**Printer**
Tevo Tarantula, but this should not matter? Guessing it is a logic bug. I like making my own supports since cuts supports are so difficult to get exactly the way I want on mass production runs. And will undoubtedly change between cura versions eventually. I have had no problem with straight single passes.

**Reproduction steps**
Made my own round supports 0.1mm or so wider than the nozzle.

**Actual results**
Divides the circular supports with travels, between 1 and 8 travels seemingly randomly. This is a problem because sometimes the nozzle will leave an ooze blob that is difficult to prevent with Bowden + E3D volcano. The print head collides with these blobs.

**Expected results**

Each single pass support is made in a single pass.

**Additional information**
This is likely due to the slicer not having logic for specifically round single pass-able geometry.
https://drive.google.com/file/d/1-vuMYafWGO7-_0DWk_nRwPp9xIWwLqoG/view?usp=drivesdk

**Comment by smartavionics** [comment]
Hi, I don't really understand what the problem is from what you have written above but if you could save the project file (File -> Save) and then either zip or rename the .3mf to .zip and attach to this issue then I can take a look and maybe help. Thanks.

**Comment by Ghostkeeper** [comment]
I'd not expect a contour to be broken off halfway and continued later. Is that what you meant?

As for the order in which the rings are printed, it could well look very arbitrary because it's trying to minimise travel moves with Nearest Neighbour. It's not in the same organised way that a human would order these parts because a computer is not able to understand that concentric rings belong to each other. It just looks at travel distances.
