### ISSUE TITLE
Setting corner speed (slowdown) 

### ISSUE THREAD

**Issue by kyjak** [Ultimaker/Cura#6237]
Using larger nozzles with higher printing speeds destroys the quality
of sharp corners (90 degree is a common one for example). The filament has no time
to stick in the sharp corner very well.

I would suggest a parameter to slow down print on angles sharper than a value.
So 2 values - angle threshold and a percentage of downspeed

The only fix now is to set a small speed to outer wall, however, having few corners
makes printing any straights equally slow, thus delaying the print unnecessary.

All printers are affected (I own a prusa mk3)
Everybody would benefit, any advanced user.

**Comment by smartavionics** [comment]
Have you tried using lower acceleration values for the walls?

**Comment by Ghostkeeper** [comment]
There is a setting for this: Jerk. Jerk is the speed that the nozzle is allowed to run through corners. Sharp corners get slowed down more than obtuse corners. I advise that you lower the jerk setting considerably. For example, Ultimaker 3 uses an outer wall jerk of 5mm/s.

For the Prusa i3 you first need to check the Enable Jerk Control setting so that Cura takes over control of how much jerk to use during your print. Otherwise it lets the firmware decide.

**Comment by kyjak** [comment]
Thank you, acceleration did the trick. Sorry for the ticket.
