### ISSUE TITLE
[4.3 beta] Coasting on first layer has a bigger gap

### ISSUE THREAD

**Issue by Liger0** [Ultimaker/Cura#6342]
**Application version**
4.3

**Platform**
Win10 x64

**Printer**
Cr10S

**Reproduction steps**
Enable coasting.

**Actual results**
The line gap on the first layer is a lot larger than the one on other layers

**Expected results**
Same gap

**Additional information**
Flow is 95% for both first layer and all other layers.
Layer height is the same for first layer and other layers.
[CCR10S_Coasting.zip](https://github.com/Ultimaker/Cura/files/3606051/CCR10S_Coasting.zip)

**Comment by rburema** [comment]
Hi @Liger0 Thanks for trying the beta yet again! :-)

When I load the project in both 4.3-BETA and 4.2.1 I'm seeing some differences: The line-width is 0.44 (4.2.1) instead of 0.4 (4.3-BETA), and the coasting happens in a different place in the model. If I set the line-width to the same values, and compensate the line direction to get roughly the same image, it seems that the behaviour, when it comes to the gap-size, isn't different in 4.2.1.

The question still remains however, since the gap is bigger in 4.2.1. as well (just not as noticeable on first inspection). However:
There are quite a few settings which might have an effect on the first layer, and if you check the feed-rate (in preview, select the 'Feedrate' colour scheme), you can see that the first layer has a way lower feedrate (in both versions), which in turn affects the coasting-gap length.

The 'flow %' is only the modifier applied at the end, on top of the other effects.

**Comment by Liger0** [comment]
Yes, there have been some changes since 4.2.1 with profile machine values. Also, some other unaffected settings have been reset in my profile for some reasons.
In fact I didn't try coasting on earlier versions, I gave it a try in cura 4.3 beta because the bulge drop issue coasting always had has been just solved in this version.

**Comment by Liger0** [comment]
I think what I'm pointing out is  more visible here. I am unsure if it's intended, so I'll go ahead just in case. The larger the section, the larger the coasting.
[coasting.zip](https://github.com/Ultimaker/Cura/files/3618366/coasting.zip)
![coasting](https://user-images.githubusercontent.com/20385116/64996295-d7b75880-d8dd-11e9-85eb-7724540c1030.png)

**Comment by Ghostkeeper** [comment]
The coasting gap can be different on the initial layer because the line width, layer height and flow rates can be different. Typically I'd expect the coasted distance to be smaller than on the rest of the layers, but if e.g. the layer height is lower than on the rest of the layers it will be longer. This is also what I'm seeing in your project file.

The things you're seeing in that screenshot is the effect of the Minimum Volume Before Coasting setting, which is also intended behaviour.

**Comment by Liger0** [comment]
But on the first example, the shape is the same on all the layers, same for layer height, line width and flow, still on first layer the coast lenght is 2x the one on other layers.

**Comment by Ghostkeeper** [comment]
No, it's not. Your profile sets the layer height to 0.24mm but the initial layer height is 0.12mm.
![Screenshot from 2019-09-18 11-40-31](https://user-images.githubusercontent.com/2448634/65137177-63bda300-d9f8-11e9-84e0-4c31c645c321.png)

**Comment by Liger0** [comment]
That's strange really. I am sure I saved it with both values being the same.
