### ISSUE TITLE
[2.1] Legacy dialog used for "Save as file"

### ISSUE THREAD

**Issue by thopiekar** [Ultimaker/Cura#635]
This is what I currently see on KDE:
![bildschirmfoto3](https://cloud.githubusercontent.com/assets/1847437/12873009/47e9f78c-cdb3-11e5-8907-080da696bf79.png)

And what I expect like we have as "open file" dialog:
![bildschirmfoto5](https://cloud.githubusercontent.com/assets/1847437/12873010/4e2e4918-cdb3-11e5-83f5-44de08687191.png)

**Comment by awhiemstra** [comment]
This is intentional due to a bug in the KDE file dialog that I still need to properly report. The KDE dialog converts the Qt file type filters into something the KDE dialog expects. However, unfortunately it only looks at file extensions. Since we have two file types with the same extension, the file dialog does not restore to the right extension. Now, to be fair, the issue arises because of having save support for both ascii and binary STL and there is little reason to save to ascii, but the issue remains that if anything we save to has the same extension as something else, the KDE dialog gets confused.

**Comment by awhiemstra** [comment]
And upstream bug filed: https://bugs.kde.org/show_bug.cgi?id=359528

**Comment by thopiekar** [comment]
Thanks :+1:

**Comment by nallath** [comment]
This can be closed. This is either fixed or out of our hands.
