### ISSUE TITLE
Filter Ironing by aspect ratio

### ISSUE THREAD

**Issue by Firedrops** [Ultimaker/Cura#6374]
**Is your feature request related to a problem? Please describe.**
Ironing sometimes wastes time on long strips which functionally do not benefit from it.

**Describe the solution you'd like**
An aspect ratio or minimum width filter for ironing. For example,
1. ignore faces with aspect ratios more than 5:1, OR 
2. ignore faces with the shorter dimension below 3mm.

**Describe alternatives you've considered**
There's currently an ironing setting for only the highest layer, but this is not granular enough for some prints.

I have no idea how non-rectangular surfaces can be detected by this filter, but 1 step at a time.

**Comment by Ghostkeeper** [comment]
Why does the aspect ratio of a shape (a shape's bounding box?) matter for whether you want to iron or not?

**Comment by Firedrops** [comment]
because if it's a long thin ledge, then it's pointless to do ironing on that part.

**Comment by Ghostkeeper** [comment]
Hmm. Well, I think an [opening operation](https://scikit-image.org/docs/dev/auto_examples/applications/plot_morphology.html#opening) would be more fitting then, because it won't depend on the direction of the thin ledge.

**Comment by Ghostkeeper** [comment]
Perhaps it's good to realise why it's pointless to do ironing on a thin part. Because perhaps the real reason is that it's pointless to perform ironing on the walls, and the Ironing Inset is just a complete and correct solution then.

**Comment by fvrmr** [comment]
We are constantly working on making Ultimaker Cura better. Our community is a big part of that by requesting new features and reporting bugs. 

To be able to focus on the most requested and needed features from our community and from Ultimaker, we have decided to remove this feature request from our backlog. We believe we will not work on this anytime soon and will therefore defer this issue.

Since Cura is open source, you or anyone else is more than welcome to work on this issue and create a pull request yourself.

**Comment by Firedrops** [comment]
I think the general improvements to print quality has somewhat obsoleted the need for ironing, and the offset mentioned above should be able to catch most cases.
