### ISSUE TITLE
Set priorities between avoiding parts and avoiding supports

### ISSUE THREAD

**Issue by jokamikaze** [Ultimaker/Cura#6376]
Prioritize (or put an select box) the "avoid printed parts" over the "avoid supports", if both are enable Cura prefer avoid supports.

![image](https://user-images.githubusercontent.com/24738622/65173985-620ad400-da26-11e9-9b34-b23b61418b33.png)

**Comment by Ghostkeeper** [comment]
It's currently avoiding all of them at the same time. This cuts the computation time for calculating combing down a lot.

**Comment by adamsiem** [comment]
@Ghostkeeper Is this expected behavior in my screenshot for Travel Avoid? I have Combing Mode: All, but it does not comb for the few supports created in the slot at the nearest end of the fins of the model.
![Combing Mode ALL Fails to Comb for Supports](https://user-images.githubusercontent.com/1068543/78208971-c4339f80-7473-11ea-89c1-a6914c6b9a5b.png)

**Comment by Ghostkeeper** [comment]
I'll refer to my answer here then: https://github.com/Ultimaker/Cura/issues/2401#issuecomment-609764762

Your comment is off-topic for this issue thread. This issue thread is about prioritising which parts of the print it hits if collisions are inevitable and combing is impossible.

This would mean that CuraEngine would first need to calculate if there is a valid path without hitting any walls or support, and if there is no such valid path it should calculate again to see if there is a valid path that doesn't hit any walls but may hit some support. We don't think this case occurs very often and it would mean a significant slowdown for slicing for everyone, so we've chosen to defer it until we have a better system to compute combing paths with priorities.
