### ISSUE TITLE
Cura 4.3 connect infill lines reduces infill area

### ISSUE THREAD

**Issue by ungutknut** [Ultimaker/Cura#6419]
**Application version**
Cura 4.3

**Platform**
Win10 64bit

**Printer**
custom printer (FunmatHT) with 0,4mm nozzle

**Actual results**
When selecting "connect infill lines", small areas (e.g. small feature on bottom right is just 1mm wide) dont get infilled.
https://imgur.com/a/J3JGMeq

**Expected results**
Small areas should get infilled, like they used before selecting "connect infill lines".
https://imgur.com/RXshTze

**Additional information**
This behaviour was already apparent on Cura 3.6. 

"Fill gaps between walls" and "filter out tiny gaps" has no effect. I'm not sure if it's a bug, but it's something that other slicers can handle gracefully ( https://imgur.com/LlYjah1 ).

What also kind of works, is setting the wall line count from 1 to 2. Then the gaps strangely get filled with top/bottom (which is actually set to 0) as you can see here: https://imgur.com/rYzzZPb
Unfortunately this doesn't work out for me because top/bottom areas have no setting like "print top/bottom before wall" (that's gonne be my next feature request BTW) - so it disarranges the print order (infill before walls) which is crucial for this print.

Unfortunately I'm not allowed to upload this current project but I could create a similar geometry if that would help.

**Comment by Ghostkeeper** [comment]
I see what you mean. The reason why this happens is that Connect Infill Lines makes the infill lines stop half a line width before the edge so that the connecting line lies adjacent to the wall rather than half on top of it.

When you have more walls it will get filled because the gaps that are too small to be filled with walls are closed separately. Not so for infill though, because infill tends to have lower density anyway so they have gaps regardless.

I agree that this behaviour is undesirable though. I'll think if there is anything we can do...

**Comment by ungutknut** [comment]
Thanks for the explanation and looking into it.

**Comment by GregValiant** [comment]
I'm cleaning house.
Is this still a problem with current Cura versions (5.8.0 and up)?  Can I close this?

**Comment by ungutknut** [comment]
I haven't encountered this issue for a long time now. You can close it, yes. Thanks!

**Comment by GregValiant** [comment]
Thanks.
