### ISSUE TITLE
Cura 4.2.1 & 4.3 have HUGE gcode files of same STL then older versions (v4.0 & v4.1).

### ISSUE THREAD

**Issue by Roboman10** [Ultimaker/Cura#6463]
**Application version**
All Versions

**Platform**
Windows 10 64Bit v1903

**Printer**
Creality CR-10 S4

**Reproduction steps**
When printing the same STL file with the exact same settings (Layer height, Infill, etc...) Cura v4.2.1 and Cura 4.3.0 creates a HUGE gcode file for sending to your 3D printer.  Unfortunately mine or any other CR-10, CR-10 S4, CR-10 S5, etc... doesn't have a big enough buffer to receive the huge gcode commands fast enough, and it causes micro pauses. The pauses will create small blobs all over the place on the print. With Cura v4.0 and v4.1 the gcode is more then twice as SMALL and prints just fine without any pauses happening.

[Cura Versions Gcode File Size.pdf](https://github.com/Ultimaker/Cura/files/3679212/Cura.Versions.Gcode.File.Size.pdf)

**Actual results**

**Expected results**

**Additional information**
Not sure what was changed in v4.2.1 and v4.3.0 but possibly the creawsome mod added to these Creality printers may be causing the HUGE gcode files.

**Comment by Ghostkeeper** [comment]
> Not sure what was changed in v4.2.1 and v4.3.0 but possibly the creawsome mod added to these Creality printers may be causing the HUGE gcode files.

Could be. I don't see any obvious changes in the profiles that could cause this. Could you try setting Maximum Resolution significantly higher, maybe? Something like 0.2mm might be more appropriate.

We're not able to help you with this issue, really, because we can't tune the profiles for printers without testing the profiles. And to test the profiles we'd need a printer. Cura currently has 180 different printers; you can understand that this is not viable.

If you know of improvements to be made to the profiles and people agree with these changes, then we can merge them into the default profiles for a next Cura release. We accept those via pull requests.
