### ISSUE TITLE
Updated to 4.3 and no third option for align to build plate.

### ISSUE THREAD

**Issue by MrJabu** [Ultimaker/Cura#6482]
I am not seeing the third option add to Cura 4.3

![cura](https://user-images.githubusercontent.com/21026988/66238331-5b868880-e6c5-11e9-88f0-d7906549be15.png)

**Comment by smartavionics** [comment]
The availability of this feature depends on the level of OpenGL support your computer provides. If the preview screen uses the old "compatibility mode" with a single slider on the right to select the layer of interest rather than 2 sliders (one on the right and one on the bottom) which you get with the full layer view, then it indicates the OpenGL support is not sufficient to give you the align to build plate feature.

**Comment by rburema** [comment]
In the case you _do_ have a graphics card that's capable of OpenGL 4.1 (or higher):
 - (often the case on laptops) check if you're not accidentally rendering with the Intel chip on the main board
 - (might help) update your drivers
