### ISSUE TITLE
values in the printer profile are not saved

### ISSUE THREAD

**Issue by ssavickiy** [Ultimaker/Cura#6505]
when you change the extruder settings in the printer profile, the values are displayed through the dot, if you drive the values through the dot, these values are not saved. eslire to drive values through to sing, for example, a nozzle size of 0.4 that remain. cura 4.3

при изменении параметров эструдера в профиле принтера, значения отображаются через точку, если вбивать значения через точку, то эти значения не сохраняются. еслиже вбивать занчения через запетую, например размер сопла 0,4 то сохранится. cura 4.3

**Comment by Ghostkeeper** [comment]
The automated translation of your Russian mangles the report. Sorry. It's hard to understand.

As I understand, you're trying to change the nozzle size by typing `0.4` instead of `0,4`, or `0.4` instead of `0,4`. And it's not retaining the changed setting?

I'd expect that text box to accept both `0.4` and `0,4` but change the `0,4` into `0.4` as soon as you change focus. The rest of Cura also works in this way.

**Comment by ssavickiy** [comment]
Yes, that's right. the entered value is not saved if used there .""to separate the nozzle or filament size value.

да, правильно. не сохраняется введеное значение, если там используется "."  для разделения значения размера сопла или филамента.

**Comment by Ghostkeeper** [comment]
Thanks for your help with the analysis! Since https://github.com/Ultimaker/Cura/issues/6546 contains more information and discussion, I'll close this one as a duplicate.
