### ISSUE TITLE
[4.3] Support geometry becomes smaller 

### ISSUE THREAD

**Issue by Liger0** [Ultimaker/Cura#6554]
**Application version**
4.3

**Platform**
Win10 x64

**Printer**
Cr10S

**Reproduction steps**
Open the project file

**Actual results**
On the back, the supports get smaller until it disappears for some layers.

**Expected results**
Do not skip layers

**Additional information**
I tried to change xy distance and minimum polygon surface to 0, but it didn't make a difference.
I don't understand why it wants to become smaller.
[Back supports.zip](https://github.com/Ultimaker/Cura/files/3746554/Back.supports.zip)
![back supports](https://user-images.githubusercontent.com/20385116/67143670-0ecab200-f26e-11e9-8ddb-b6f48d35c8c4.png)

**Comment by Ghostkeeper** [comment]
It wants to become smaller because the model is getting too close. It's hard to see in the screenshot, but Majin Buu's spine is getting closer to the support there. It's the same ridge as what the seam is placed on in the layers just below.

We have two solutions to this: Reducing the minimum support X/Y distance, or enabling tree support. Given the type of model involved here and your very tall, thin pillars, I think it's wise to give tree support a try.

I see only intended behaviour here. The support is supposed to be able to rest on the surface, but due to the large horizontal distance it'll probably end up as blobs on the surface instead which don't provide any meaningful strength.
