### ISSUE TITLE
Feature Request: cover the whole layer with skin even if part of it will be printed on.

### ISSUE THREAD

**Issue by Cyberman-tM** [Ultimaker/Cura#6555]
**Is your feature request related to a problem? Please describe.**
When Cura knows that a higher layer will be smaller, it will create an outline of the higher layer, leaving part of the current layer "open", to be covered with additional infill.

Normally this is no problem, but in some cases (small items) it's a waste of time - and with ironing it even creates a section where the raw infill is visible instead of a nice skin.
(That last part may be solvable through settings, I'm not sure.)

**Describe the solution you'd like**
Add an option to create "top skin" for the whole layer whenever Cura sees that a layer is at least partially open.
I.e. instead of creating the outline, just go across it all, and then print on top of that nice skin.
Unless that is actually a problem with layer bonding?

[edit] I've also created a forum thread, I've posted a picture there to demonstrate what I mean:
https://community.ultimaker.com/topic/29874-feature-request-cover-the-whole-layer-with-skin-even-if-part-of-it-will-be-printed-on/

**Comment by Ghostkeeper** [comment]
You should be able to upload images here on Github too, by the way. Github uses Amazon AWS though so if you have a browser plug-in that blocks 3rd party requests or scripts you'd need to unblock that.

I see you describe two problems that can both be fixed with settings:
* [Minimum Infill Area](https://github.com/Ghostkeeper/SettingsGuide/blob/master/resources/articles/min_infill_area.md) will close small gaps in the top skin. This way, instead of stopping just before the small gap, it'll just continue printing skin over the whole gap. It can save some time at the cost of more material. This answers your main question. It's not as brute force as your proposed solution, but only applies to small gaps in the skin where it's needed. Increase this setting to maybe something like 10mm^2 for your model.
* [Ironing Inset](https://github.com/Ghostkeeper/SettingsGuide/blob/master/resources/articles/ironing_inset.md) is a distance that Cura will keep between the edge of the ironed area and the edge of the top surface. If you reduce that to 0, the influence of those letters will not nearly be as big.

I hope those solutions are sufficient for your case. I think the first solution is a better solution in general than what you've proposed.
