### ISSUE TITLE
Error Cura 4.3.0 Weedo

### ISSUE THREAD

**Issue by ese628** [Ultimaker/Cura#6769]
<!--
Hi. Cura 4.3.0 Weedo does not save file in XG3 format
![Error](https://user-images.githubusercontent.com/58611413/70360503-7b6d3080-185d-11ea-8e11-67220001943d.png)

**Comment by ese628** [comment]
![Error](https://user-images.githubusercontent.com/58611413/70360613-c8510700-185d-11ea-9506-4657d61b3226.png)

**Comment by Ellecross** [comment]
I would really really like it if you: 

Give more description about the issue 
OR fill up the bug template 
OR attach a project file ;) 

This will help us reproduce your issue. 

Can you also try the same in [Cura 4.4](https://ultimaker.com/software/ultimaker-cura) please?

**Comment by ese628** [comment]
Hi. I am trying to use the Ultimaker CURA version for the Weedo F192 printer, but it does not recognize the printer and does not save in X3G format. In version 4.4.0 this printer is not included.

**Comment by ese628** [comment]
![Error CURA](https://user-images.githubusercontent.com/58611413/70433253-f69e3480-1a5f-11ea-960c-2e1548773d00.png)

**Comment by Ghostkeeper** [comment]
We don't publish any Cura version for Weedo F192. It appears that you've either downloaded an alternative version of Cura that we don't maintain, or you've installed a mod that got broken. Either way, there is little that we can do about it.

If you have a log file when trying to save that X3G file, you may report it in the issue list for the X3GWriter: https://github.com/Ghostkeeper/X3GWriter/issues
That is not something that Cura can do anything about either (but it's my own problem since I maintain that X3GWriter plug-in).

**Comment by ese628** [comment]
Okay. Thank you!!

**Comment by Ferjapolis** [comment]
Solo debes iniciar a Cura como administrador.
