### ISSUE TITLE
[Feature Request] Inject all slicer settings into GCODE

### ISSUE THREAD

**Issue by stantond** [Ultimaker/Cura#6799]
**Is your feature request related to a problem? Please describe.**

When you have many GCODE files on the go, managed in one place (in my case, OctoPrint), it can be hard to keep track of which settings you used for a given file.

There are plugins that can pull this data from GCODE to display in a GUI while managing GCODE files, but Cura doesn't provide an option to insert all of this data when slicing. Slic3r and Simplify3D support this. Even without a GUI, it's not hard to dip into the file and take a look.

**Describe the solution you'd like**

An option to add all settings to the start of the GCODE file when slicing, similar to the output of https://github.com/tjjfvi/CuraSettingsInjector.

**Describe alternatives you've considered**

A workaround is to use this custom GCODE, https://github.com/tjjfvi/CuraSettingsInjector, but it's an elaborate way to solve a simple problem, and it needs to be manually updated in Cura settings every time there's new setting added to Cura or the reference to an existing setting is changed in a Cura update.

**Affected users and/or printers**

Anyone who has a need to review settings they used to slice a particular GCODE file.

**Comment by Ghostkeeper** [comment]
Cura already does this. It's put at the end of the file though, not the beginning. It looks like this:

```
;SETTING_3 {"global_quality": "[general]\\nversion = 4\\nname = Fine #2\\ndefini
;SETTING_3 tion = ultimaker3\\n\\n[metadata]\\ntype = quality_changes\\nquality_
;SETTING_3 type = normal\\n\\n[values]\\n\\n", "extruder_quality": ["[general]\\
;SETTING_3 nversion = 4\\nname = Fine #2\\ndefinition = ultimaker3\\n\\n[metadat
;SETTING_3 a]\\ntype = quality_changes\\nquality_type = normal\\nposition = 0\\n
;SETTING_3 \\n[values]\\ninfill_sparse_density = 30\\nspeed_print = 55\\n\\n", "
;SETTING_3 [general]\\nversion = 4\\nname = Fine #2\\ndefinition = ultimaker3\\n
;SETTING_3 \\n[metadata]\\ntype = quality_changes\\nquality_type = normal\\nposi
;SETTING_3 tion = 1\\n\\n[values]\\ninfill_sparse_density = 30\\n\\n"]}
```

In that example I changed the infill density and printing speed. It will only show the changes from the defaults. At one point it was showing all settings there (even the ones that weren't changed) but we had to revert that change because it became impossible to see which settings were adjusted by the user.

When importing profiles with Cura's profile manager, you can import a .gcode file and it will create a profile with the settings that were used for that g-code. This way you can also find out all of the defaults combined with the changes made for that particular print.
