### ISSUE TITLE
[2.1] Can't reset maximal fan speed

### ISSUE THREAD

**Issue by thopiekar** [Ultimaker/Cura#681]
What I get here is a loop of resetting the value and repairing it (exclamation mark).
The console output doesn't tell anything interessant, just that it restarted CuraEngine.

See:
![cura1](https://cloud.githubusercontent.com/assets/1847437/14099430/b5a5358a-f585-11e5-9990-cbec8aadf02d.png)
![cura2](https://cloud.githubusercontent.com/assets/1847437/14099436/bb37c742-f585-11e5-92ec-31f3092d0126.png)

**Comment by fieldOfView** [comment]
Not sure if I agree with the qualification "bug"; the behavior is correct (though slightly confusing).

Apparently the profile defines an absolute value for Maximum Fan Speed, and Cura rightly shows a notice that the normal calculated value is overridden. After restoring the setting to its calculated value, Cura rightly shows you that the setting has been changed from the absolute value stored in the profile. The confusion here is that the absolute value is the same number as the value that is calculated from the Fan Speed value.

The "bug" is not so much in Cura's logic, but in the profile. Specifically, the Maximum Fan Speed being overridden to 100 in the PLA material profile. However, removing that value from that profile causes the Maximum Fan Speed not to be reset when switching back from ABS as a material.

(Note: this does not happend on UM2 or UM2+ machines because they don't use the generic material profiles; use UMO to reproduce)

**Comment by Ghostkeeper** [comment]
I'd still categorise this as a bug though, even if it is a bug that will likely only be solved with the design refactoring we're doing for 2.2!

**Comment by thopiekar** [comment]
Doesn't happen anymore.
