### ISSUE TITLE
Cubic Subdivision Shell Options for Wall, Top, and Bottom Boundaries

### ISSUE THREAD

**Issue by mallstar2** [Ultimaker/Cura#6889]
**Proposed Feature**
Include options to turn _Cubic Subdivision Shell_ on/off for wall, top, and bottom boundaries.

**Reason for Request**
I want to use Cubic Subdivision infill to save time and material on models that need high infill percentage only for top layer quality, but these savings are negated by the extra material that Cubic Subdivision adds near wall and bottom boundaries.

**Comment by Ghostkeeper** [comment]
This is what Gradual Infill was made for. Did you try that? Does that not work for you?

**Comment by mallstar2** [comment]
I have tried Gradual Infill but I had the same problem that was reported in issue #6001 
Cubic Subdivision doesn't have that problem because every infill line is inherently supported.

**Comment by Ghostkeeper** [comment]
We've discussed this with the team, and while the feature is an improvement, we won't give it any priority now. Reasons:
* Gradual infill generally gives enough layers to bridge properly, given enough step height.
* Gradual infill will be faster to print.
* Gradual infill will work better with top surfaces with a lot of detail, since it doesn't work via cube subdivision.

This alternative isn't so bad, really. Try it!

It's not to say that this will never get built, but it's not something we'll look at now.
