### ISSUE TITLE
Wrong Slicing on Cura 4.4.0/.1

### ISSUE THREAD

**Issue by Eagle71** [Ultimaker/Cura#6896]
**Application version**
Cura 4.4.0 4.4.1

**Platform**
Win7 64Bit

**Printer**
Creality Ender 3

**Reproduction steps**
1. Lode Model
2. Rotate Vertical
3. Slice

**Screenshot(s)**
Cura4.4.x 
Blue Ground over Support not flat, makes a V.
Red Wrong Form
![1-C44x](https://user-images.githubusercontent.com/30080520/71641732-cfbed100-2ca0-11ea-9916-ea4cbf044ef4.JPG)

Correct in Cura 4.0.0
![1-C400](https://user-images.githubusercontent.com/30080520/71641804-e6b1f300-2ca1-11ea-8641-0075aa105f98.JPG)

Wrong, building a wall, no Air goes out of the jet
![2-C44x](https://user-images.githubusercontent.com/30080520/71641890-0ac20400-2ca3-11ea-8dc3-f16a04131d6c.JPG)

**Actual results**
Wrong printing  ;-)

**Expected results**
Use older Cura

**Project file**
[HM_Volcano_Single_5015_Duct_Gen2e.zip](https://github.com/Ultimaker/Cura/files/4014093/HM_Volcano_Single_5015_Duct_Gen2e.zip)

**Log file**
[cura.zip](https://github.com/Ultimaker/Cura/files/4014125/cura.zip)

**Additional information**
Sorry, no more Info

**Comment by smartavionics** [comment]
The model isn't perfect as you can see here...

![Screenshot_2020-01-01_16-53-32](https://user-images.githubusercontent.com/585618/71643927-03f1bc00-2cb8-11ea-811a-a0e3334840c7.png)

However, when I slice it using my Cura build it doesn't appear to have any obvious problems...

![Screenshot_2020-01-01_16-58-34](https://user-images.githubusercontent.com/585618/71643935-2552a800-2cb8-11ea-96bd-e28e6c3e1ff0.png)

**Comment by Eagle71** [comment]
I added a printer: Ultimaker 2+
There all is fine.
Switched back to Creality Ender 3 (pro) and it is bad. So there musst be the fault!
Added a second Ender 3 
There is all fine.
I tested.......It is my faster Profile. Can you find the reason why this happens?

My Profile
[PETG-Faster-Std-FAULT.zip](https://github.com/Ultimaker/Cura/files/4014426/PETG-Faster-Std-FAULT.zip)

**Comment by Ghostkeeper** [comment]
The model is indeed not watertight:
![Untitled-1](https://user-images.githubusercontent.com/2448634/71646096-ac1c7a80-2ce2-11ea-8fe6-28f70886d97b.png)
However that doesn't seem to be the problem. It slices fine.

The problem is that [Make Overhang Printable](https://github.com/Ghostkeeper/SettingsGuide/blob/master/resources/articles/experimental/conical_overhang_enabled.md) is enabled in your profile. This model is hollow and at the top side of the cavity there is a lot of overhang. That setting adjusts your model so that there is no more overhang. Probably not what you want, but expected behaviour. Solution: Uncheck that setting.

**Comment by Eagle71** [comment]
Thanks for the help to solve the problem.
It's not a problem, it's a feature

The model is not the problem! I printed it with Cura 4.0.0. 
It look not easy, but it spend some  support blocker, that it keept hollow.
And the printer bridges the overhang.
It's only the PETG little bad, so the beginning layers over the support was bad.

![3-C44x](https://user-images.githubusercontent.com/30080520/71646456-41bb0880-2ce9-11ea-921c-f5a2af96227f.JPG)
