### ISSUE TITLE
[4.4.1] Straight line curving at 90° intersection

### ISSUE THREAD

**Issue by Liger0** [Ultimaker/Cura#7025]
**Application version**
4.4.1

**Platform**
Win10 x64

**Printer**
Cr10s

**Reproduction steps**
1. Use a model with lines that intersect at 90°

**Screenshot(s)**
![straight line deviation 2](https://user-images.githubusercontent.com/20385116/73127875-4496d980-3fc7-11ea-922d-8445418cd94a.png)
![straight line deviation](https://user-images.githubusercontent.com/20385116/73127876-4496d980-3fc7-11ea-9d6e-24e2b158fb39.png)

**Actual results**
Depending on the intersection feature type, the lines curve at the end

**Expected results**
End the line straight

**Project file**
[straight line deviation.zip](https://github.com/Ultimaker/Cura/files/4112945/straight.line.deviation.zip)

**Comment by smartavionics** [comment]
Use my Cura, it does thin walls differently to UM Cura...

![Screenshot_2020-01-25_22-17-07](https://user-images.githubusercontent.com/585618/73127996-840df780-3fc0-11ea-856a-5ee4d8a45f5f.png)
![Screenshot_2020-01-25_22-16-41](https://user-images.githubusercontent.com/585618/73127997-84a68e00-3fc0-11ea-9eb1-7d482fd37cc4.png)

**Comment by Ghostkeeper** [comment]
You can try shifting or rotating the model slightly as well. This is the result of the technique used to fill small gaps and print walls thinner than the line width. It fills the thin space with tiny lines and then combines those lines together. The line segment at the end has an endpoint that's not connected to anything else and then doesn't get "straightened" to another line segment, so it gets a little lip there. I think something similar happens at the intersection since there is a bit more space there. By shifting or rotating the model slightly, the lines are generated relatively at a different offset and it could combine differently.

Ultimately the thin wall printing algorithm is something we need to look at (mostly because of the bug that it doesn't combine the lines well sometimes).

**Comment by mahtDFR** [comment]
Thanks for the report, this is an issue we're aware of. It's a sub issue to a larger issue to do with a library and it's being looked into. We'll create a ticket in our internal system for this.

**Comment by GregValiant** [comment]
I'm cleaning house.
Is this still an issue in current Cura versions (5.8.0 and up)?  Can this be closed?
