### ISSUE TITLE
bug; configuration overrule from "monitor"  does not work Cura 4.4.0

### ISSUE THREAD

**Issue by UltiArjan** [Ultimaker/Cura#7047]
Summary, the option to overrule the configuration error (wrong material type/color in Cura vs Ultimaker3) is not working. Looks like it's caused because the "manage in browser"link on the monitor tab in cura is pointing at "cloud". The overrule is working from the "local-ip/print_jobs" page.

See enclosed screen shots

**Application version**
4.4.0.

**Platform**
Window 10

**Printer**
Ultimaker3

**Reproduction steps**
see screenshots enclosed, tried it a few times

**Screenshot(s)**
see pdf

**Actual results**
overrule button does not work, just does nothing

**Expected results**
overrule accepted and printer starts printing even though cura is loaded with "black pla"and the printer with "generic pla"

[printjob-override-error.docx](https://github.com/Ultimaker/Cura/files/4135254/printjob-override-error.docx)
[configOverrideBug.pdf](https://github.com/Ultimaker/Cura/files/4135279/configOverrideBug.pdf)
[configOverrideBug.pdf](https://github.com/Ultimaker/Cura/files/4135281/configOverrideBug.pdf)

**Comment by mahtDFR** [comment]
Hi UltiArjan, thanks for the detailed report. I reproduced the issue.

This is not so much a Cura issue, but a Cloud issue, so there's not much we can do from our side except report it to the cloud team (which I have already).
This is down to the feature on the UM3 not being available in the firmware, but the override button is still being shown. It's on the backlog to be fixed by the cloud team in upcoming releases, but it's unclear when the next release for the UM3 is going to be...

As it's not a Cura issue, I will close this.
