### ISSUE TITLE
Not correct slice model

### ISSUE THREAD

**Issue by userosos** [Ultimaker/Cura#7110]
Cura 4.5 beta. See pic. Gcode doesn't look like the model.
![cura_bad](https://user-images.githubusercontent.com/22872748/74602446-8a702a80-50b9-11ea-9cfc-85666120c7a6.jpg)
[CFFFP_Retraction.zip](https://github.com/Ultimaker/Cura/files/4209596/CFFFP_Retraction.zip)

**Comment by Ghostkeeper** [comment]
That's because the model is too thin to print there:

![image](https://user-images.githubusercontent.com/2448634/75237390-8c27a580-57bf-11ea-8f5e-a5bbeca50529.png)

It's never going to be able to print an infinitesimally thin wall. However you can try to get it to print by reducing the wall line width and enabling "Print Thin Walls". I don't think the result will be nice. Most likely you'll just have to fix the model because I don't think you intended this.
