### ISSUE TITLE
[4.5 Beta] Per Model Settings menu covers Object List

### ISSUE THREAD

**Issue by valeria-gomez** [Ultimaker/Cura#7117]
**Application version**
4.5 Beta

**Platform**
Windows

**Printer**
Ultimaker 3

**Reproduction steps**
1. Select part on bed
2. Select Per Model Settings
3. Select and make visible many per model settings

**Screenshot(s)**
![image](https://user-images.githubusercontent.com/60856983/74613678-a652eb00-5110-11ea-8a19-6c355ee9ab2b.png)

**Actual results**
Object list is being overlapped, cannot see anymore 

**Expected results**
Object list should not be visible.

**Comment by Ghostkeeper** [comment]
Not sure what we should do about this. Moving the toolbar higher may not look as nice since it's no longer centred, and may cause it to intersect with the printer list. Though the printer list is perhaps less crucial since it doesn't stay open after the focus is lost.

I also don't think that changing the Z order is a good idea logically. The panel should feel as if it's floating on top.

**Comment by GregValiant** [comment]
I'm cleaning house.
Is this still an issue in current Cura versions (5.8.0 and up)?  Can this be closed?
