### ISSUE TITLE
Use multiple cores

### ISSUE THREAD

**Issue by controlflow** [Ultimaker/Cura#7173]
Cura is a quite resource-insensitive app when slicing in terms of CPU usage... but it basically do not uses multiple cores at all :\ This is 16-core Ryzen CPU doing simple slicing for 30+ minutes (this is single thread working, jumping back and forth between cores + SMT):

![cura](https://user-images.githubusercontent.com/194765/75483161-4f260380-59b7-11ea-81e3-9264f6ba0ab1.png)

While I understand that slicing in kinda sequential process (next layer entry point is kinda dependent on previous layer), but it seems that it can be easily done in parallel layer-by-layer (even with possible quality degradation/more stringing/non-optimal seam location), maybe even with supports generation.

It seems that since #876 from year 2016 nothing has changed much...

**Comment by smartavionics** [comment]
The part of Cura that does the actual slicing, CuraEngine, does indeed use multiple cores for a large proportion of the work it does. Some of the work has to be done serially but a lot can, and is, parallelised. Your above graphic does not reflect reality.

**Comment by smartavionics** [comment]
I only have 4 cores but notice here how CuraEngine is using 357% of CPU while slicing...

![Screenshot_2020-02-27_21-40-58](https://user-images.githubusercontent.com/585618/75489294-e3896980-59a9-11ea-8c32-7fa8bd74ecb5.png)

**Comment by mahtDFR** [comment]
I just sliced a cube at 0.002 layer height but I cant reproduce it because it's using all my cores here.
![image](https://user-images.githubusercontent.com/17821912/75537743-d7d48c00-5a17-11ea-93d4-192c96164e56.png)

Can you share a log? That may give some clues.

**Comment by controlflow** [comment]
To reproduce, slice the biggest 300x300 model from: https://www.thingiverse.com/thing:2916907
Disabling support/tree support generation speeds up things 10x times, but still takes a 5+ minutes to complete with most of the cores doing nothing.

**Comment by smartavionics** [comment]
I sliced one of those chains and for most of the time, all 4 cores were busy.

**Comment by Ghostkeeper** [comment]
Could you go into your task manager while Cura is running, then right-click on Cura.exe, and check "affinity"? Are all cores checked there? And the same while it's slicing and for CuraEngine.exe?

**Comment by v1n2e7t** [comment]
Could this be a Ryzen AMD issue? I’m seeing the same thing on my Ryzen 7 3800X

**Comment by Ghostkeeper** [comment]
We have two known/reproducible bugs regarding this, mind you: There is no multithreading on MacOS at all. And with Tree Support there is multi-threading but it's largely defeated by a caching system.

I don't think it's an issue with Ryzen since I'm using a Ryzen 9 3950X myself. I also logically wouldn't think this depends on the processor; more on the operating system.

**Comment by v1n2e7t** [comment]
Thank you, I am on windows but was using tree supports.

**Comment by Fuzzypyro** [comment]
Can 100% confirm its not an issue between Intel/AMD. Found it's just how it processes tree supports.I ran a test between two systems just to make sure it wasn't an issue with poor optimization with infinity which in hindsight doesn't make sense anyway since it's only processing on 1 core and not say half. Hopefully they are able to find a way to split the load of tree support generation among multiple cores in the near future.

Tested on Manjaro using appimage 4.7.1

**Comment by robherc** [comment]
I'm running Lubuntu on a laptop with a Ryzen7 cpu. Cura has recently (within the past week) started showing this problem (could possibly be an incompatibility with a recent OS update?).

The past 8 slices have all taken multiple minutes (possibly because of running postprocessing scripts?), and used only 13% cpu (4-core, 8-thread architecture).

**Comment by fieldOfView** [comment]
Postprocessing scripts do not run until just before the gcode is saved or printed, so they do not affect slicing/previewing.

**Comment by Smarti0101** [comment]
Same here on a Ryzen9 5950X (16c/32t). Max usage 5%.....

**Comment by TheRealKasumi** [comment]
Exactly the same "issue" here on a Windows system with a 7950X and 128GB RAM. It seems that only 4 cores are used. Could explain why it can't be seen in the screenshot above where the CPU only has 4 cores.

**Comment by eazrael** [comment]
Ryzen 7700X, Win10,, no problems, large parts use all 16 virtual cores. It really depends on the amount of parallelizable and serial work. If the parallelizable work is done fast as all cores are used, you may not even see the spike. 

Is there any debug mode or so where the slicing times are logged?
