### ISSUE TITLE
Supports are floating in the air when influenced by X/Y/Z distance

### ISSUE THREAD

**Issue by alkhimey** [Ultimaker/Cura#7191]
**Application version**
4.5

**Platform**
Ubuntu

**Printer**
Creality-Ender-3, 0.4mm nozzle, generic PLA.

**Reproduction steps**
1. Download the following model: https://www.thingiverse.com/thing:929504
2. Slice with supports.

**Screenshot(s)**
![Screenshot from 2020-02-29 14-42-43](https://user-images.githubusercontent.com/652603/75607673-3aa25200-5b02-11ea-81de-bebde2a5329b.png)

**Actual results**
Supports are floating in the air. Can't print like this.

**Expected results**
There is a connection between the supports and the bed.

**Project file**
(Change extension to 3mf)
[CE3_fidget_star_standing_30_2_50.zip](https://github.com/Ultimaker/Cura/files/4270299/CE3_fidget_star_standing_30_2_50.zip)

**Comment by mahtDFR** [comment]
Thanks for the report. I was able to reproduce it. 
We thought it might be a result of stair stepping issues (see 6379 for more discussion on this). Even when stair stepping was set to 0 the issue persisted.

![image](https://user-images.githubusercontent.com/17821912/75663934-f7ff8780-5c71-11ea-9ea3-c17235af79a4.png)

**Comment by BagelOrb** [comment]
This is due to the Support XY distance.

It would be nice if Cura checked for something like this happening and always generates support which is supported, but that's quite a difficult thing to implement.

**Comment by Ghostkeeper** [comment]
Workaround for now is to use Tree Supports or Enable Conical Supports with a slight negative conical support angle. Solving the issue where the support is removed by a protrusion in the X/Y plane is a pretty hairy problem that Tree Support has a solution for.

I expect that in practice, this support will probably repair itself at some point though. It will leave a slight scar.

**Comment by alkhimey** [comment]
@Ghostkeeper It seems that the conical option prints the model engulfed inside a conical support structure. Are you sure it is possible to remove the supports afterwards?

**Comment by BagelOrb** [comment]
I think you should lower the angl setting of the conical or tree support then.

**Comment by Ghostkeeper** [comment]
I think you should increase the normal Support Overhang Angle since I'm not seeing the angles at the top being supported if I only add conical support to your previously submitted project file:
![image](https://user-images.githubusercontent.com/2448634/76204394-9d79a480-61f8-11ea-8e69-6e2ee4146b1e.png)

Though in actuality if you really want to print this object in this orientation, you'll probably need to print it like this or it will become very unstable towards the top.

**Comment by StarNamer** [comment]
I'm not sure this is that same issue, but I've had an instance of Tree Supports being generated floating in mid-air in 4.6 Beta. So the recommendation to use Tree Supports to avoid the issue won't necessarily fix it.

Here's a couple of images of Cura showing the floating support, plus a photo taken while it was being printed with the c(almost) corresponding view in CURA. Fortunanlely, the print succeeded anyway; unfortunately, re-slicing did not produce the same support structure - presumably because tree supports have some randomness - so I can't provide a model which reproduces the issue.


![image](https://user-images.githubusercontent.com/1997874/79232385-5c138f00-7e5f-11ea-84a2-675fb79639f9.png)
![image](https://user-images.githubusercontent.com/1997874/79232422-62097000-7e5f-11ea-8313-1421dbb30702.png)
![image](https://user-images.githubusercontent.com/1997874/79232448-69307e00-7e5f-11ea-9f67-84b219fbf8ee.png)
![image](https://user-images.githubusercontent.com/1997874/79232467-6fbef580-7e5f-11ea-972a-c89247154dc4.png)

**Comment by StarNamer** [comment]
It seems that Tree Support is often "optimistic" about print supports in mid-air.
![image](https://user-images.githubusercontent.com/1997874/81971137-856b3a80-9618-11ea-9685-87fbb29e0c1b.png)
![image](https://user-images.githubusercontent.com/1997874/81971161-8f8d3900-9618-11ea-9f9a-9eb928091684.png)

**Comment by Ghostkeeper** [comment]
The second and third images, no there isn't. Usually it corrects itself fairly quickly. The issue is unrelated to this issue though. Please refer to [this issue](https://github.com/Ultimaker/Cura/issues/4342).

**Comment by spiritedfang** [comment]
I found the same issue in version 4.5.0. It leaves floating support structures in every support type under the head and wings in this model at 200% scale for the Ender 3: https://www.thingiverse.com/thing:3931684

**Comment by alkhimey** [comment]
Yep, I have this issue again in 4.6.1.
I am not sure, but it looks like the conical supports experimental option is not doing anything, the supports look suspiciously similar to the zig zag supports:
![Screen Shot 2020-07-04 at 10 20 36](https://user-images.githubusercontent.com/652603/86507343-4075b000-bde0-11ea-915e-cd9cfda65ba4.png)
This one without conical box ticked:
![Screen Shot 2020-07-04 at 10 19 05](https://user-images.githubusercontent.com/652603/86507345-44093700-bde0-11ea-8e6d-bbc4588a0d51.png)

Project:
[CE3_Lejon.3mf.zip](https://github.com/Ultimaker/Cura/files/4872238/CE3_Lejon.3mf.zip)

**Comment by BagelOrb** [comment]
That's a wholly unrelated issue. Could you please make a separate ticket for that?

**Comment by CiriousJoker** [comment]
<img width="600" alt="Floating supports" src="https://user-images.githubusercontent.com/16866223/103160349-212a6f00-47d4-11eb-908e-1d019214d746.png">

Using Cura 4.8 on Big Sur.

**Comment by GregValiant** [comment]
I'm cleaning house.
Is this still an issue in current Cura versions (5.8.0 and up)?  Can this be closed?

**Comment by StarNamer** [comment]
I haven't noticed this in recent versions so I'd not object to closing it.

**Comment by GregValiant** [comment]
Thanks.
