### ISSUE TITLE
[4.5.0] Segmentation fault on exit

### ISSUE THREAD

**Issue by Perlovka** [Ultimaker/Cura#7208]
**Application version**
4.5.0 (possibly all 4.x)

**Platform**
Gentoo
Qt-5.14
Python-3.6

**Printer**
Any

**Reproduction steps**
Exit cura, either by close button or File->Quit menu

**Actual results**
Exit with segfault

**Expected results**
Clean exit

**Log file**
[cura-exit.log](https://github.com/Ultimaker/Cura/files/4275076/cura-exit.log)

**Comment by Ghostkeeper** [comment]
We only maintain Cura for Qt 5.10 at the moment, though I know it works properly with 5.13 as well (as this is on my development laptop too). We can't switch to a newer version at the moment because that would drop support for older versions of Windows and MacOS that still have too many users, although declining slowly. We also can't work with supporting multiple versions since we don't have the manpower for it. Our only Linux distribution is the AppImage that you can find in Github's releases page, so if the problem occurs there Ultimaker can solve it.

I've seen this issue myself on one of my development environments too. I'm not sure what causes it. It doesn't seem to do much harm now since it happens after all of the configuration has been saved. Still a bit annoying.
