### ISSUE TITLE
Enlarge Machine Settings Dialog

### ISSUE THREAD

**Issue by thesec** [Ultimaker/Cura#7224]
With version 4.5 the start and end gcode's text fields became veeeeery small - see attached screenshot.
Please enlarge / allow scrolling / allow to enlarge the dialog itself ...

![Screenshot 2020-03-04 at 12 14 47](https://user-images.githubusercontent.com/91770/75874542-3633ad00-5e12-11ea-8b06-a479fdb8b4a2.jpg)

**Comment by tech2077** [comment]
This is also the case in 4.5 on MacOS. The window is too small and cannot be resized.


<img width="853" alt="image" src="https://user-images.githubusercontent.com/528634/75908788-7003b400-5e10-11ea-99dc-d24c652f238e.png">

**Comment by mahtDFR** [comment]
Thanks for the report.
@thesec which OS are you running here? MacOS as well?

**Comment by smartavionics** [comment]
I agree the initial size of those gcode boxes is way too small. However, on Linux, it is possible to resize the whole dialog like any other window.

**Comment by thesec** [comment]
@mahtDFR - yes, am running OS X, too.

**Comment by fieldOfView** [comment]
I propose that instead of enlarging the window (which is a sliding slope), the gcode snippets are moved to a different tab, or they are edited using a widget that pops up a dialog.

**Comment by thesec** [comment]
@fieldOfView - please keep the extruder's gcodes on mind when you decide to take it that way to keep it consistent.

**Comment by nallath** [comment]
The issue was that the dialog still had hardcoded values in them (instead of using the dynamic sizing used by the rest of the code).
It also had it's min & max size set to be the same, which linux and windows interpreted as "Resize it to whatever you want" and osx as "No resize allowed". 
I've fixed both, so it shouldn't be needed to move the gcode to a different tab (anyway, I hope it won't be needed, because that's a lot more work)
