### ISSUE TITLE
[4.5] Max temperatur only 365°C

### ISSUE THREAD

**Issue by Prio94** [Ultimaker/Cura#7255]
**Platform**
Windows10
**Printer**
Creatbot F430 (for PEEK)

**Reproduction steps**

    Load Stl
    Try to slice

**Actual results**
Not slicing...
Field for the temperatur becomes red (not orange).
This didn´t happen in [4.4] (only orange).

**Expected results**
I want to print with high temperatures, above 400°C.

**Comment by Goodfeat** [comment]
If you want to print at higher temperatures, you need to edit the file fdmprinter.def.json or add your own configuration for your printer, where this restriction will be removed

![image](https://user-images.githubusercontent.com/44455128/76391118-78cd2a80-63ba-11ea-9682-881c471a37e7.png)

This workaround will work on all current versions of the program.

**Comment by fieldOfView** [comment]
> or add your own configuration for your printer

This is the best option. Don't edit fdmprinter.def.json.

**Comment by fieldOfView** [comment]
It is a good question why there is an arbitrary maximum value for temperatures. In other places (temperatures, dimensions), Cura makes a point of not placing a hard limit on values other than limits of physics such as the speed of light.

**Comment by nallath** [comment]
For quite a few materials, it can get dangerous (and even lethal) if you heat them higher. So that's why these do have a max temp.
Furthermore, marlin also has these values as the max per default (and the vast majority of printers that are based on fdm_printer.def.json use that). 

The best solution, in this case, is to add a custom definition for your printer that increases the max temperature.
