### ISSUE TITLE
[Question] Is it normal custom supports uses hidden params?

### ISSUE THREAD

**Issue by GMagician** [Ultimaker/Cura#7259]
**Application version**
4.5

**Platform**
Win10

**Printer**
Custom

**Reproduction steps**
1 Import stl
2 add custom supports

**Actual results**
It seems that custom supports added to object changes behaviours depending on "support from bed" or "support everywhere" option (not sure about translation). But usually supports may be disabled when custom support are added and above parameter is hidden.
Is this an expected behaviours?

[test.zip](https://github.com/Ultimaker/Cura/files/4314678/test.zip)

![img1](https://user-images.githubusercontent.com/3684609/76357206-90070c00-6317-11ea-92bc-680e99386258.png)
![img2](https://user-images.githubusercontent.com/3684609/76357219-95fced00-6317-11ea-8e5f-dc43a661279b.png)

**Comment by Ghostkeeper** [comment]
It's currently expected that per-object settings (such as being a support mesh or not) may enable features that use settings that are hidden from the normal settings list. Not really desired, I'd say, but the 3D scene is currently unable to affect the settings list at all. This is not just for performance reasons (but scanning the 3D scene to evaluate every property of every setting would indeed kill performance). It's also to prevent fairly complex infinite loops, where settings depend on the scene and the scene depends on the settings.

I'll go out on a limb here and outright close this since I don't think we really want to tackle this issue. A colleague can correct me if they feel strongly about it though.
