### ISSUE TITLE
Slicing unoptimized : A lot of unnecessary movements

### ISSUE THREAD

**Issue by bvalat** [Ultimaker/Cura#7260]
**Application version**
Cura 4.5.0

**Platform**
Win10
**Printer**
Ender 3

**Reproduction steps**
1. Slice https://www.thingiverse.com/download:883343 with 0.28 ender 3 settings.
2. Look at the first layer movements.

**Actual results**
The print head after each segment between skin wall (in the red circle) on the bottom right generating a lot of travel movements following the skin
![Slicing](https://user-images.githubusercontent.com/45319952/76368952-29dbb280-6332-11ea-9313-a25e89e7ef9f.jpg)

**Expected results**
The print head fills the gap between walls without unnecessary movements.

**Project file**
https://www.thingiverse.com/download:883343
Generated gcode : 
[CE3_La_linea_di_Cavandoli_Happy_20mm.zip](https://github.com/Ultimaker/Cura/files/4315337/CE3_La_linea_di_Cavandoli_Happy_20mm.zip)

**Comment by Ghostkeeper** [comment]
That's because the Ender 3 profile specifies that Combing Mode is set to "Not in Skin". That means that it'll avoid going over the skin. Indeed there is a way to avoid the skin in this case: Go all the way around along the walls.

Changing the combing mode to "All" allows the travel move to go through the skin as well. In your case it shaves off more than an hour off your printing time!

As far as I can see everything is working correctly here, except the defaults for your printer.
