### ISSUE TITLE
[2.1 Beta] Print temperature isn't read from profile

### ISSUE THREAD

**Issue by Raniz85** [Ultimaker/Cura#732]
When saving a profile the print temperature as set is shown in the profile manager but in the GUI it's always set to the default when switching profiles - regardless of what it's set to in that profile.

**Comment by AmedeeBulle** [comment]
This is because temperature is defined in the Material and the Material priority is higher than the Profile priority so the Material overrides.

I am struggling with that as well, but it is by design: the idea is to be able to use the same Profile with different Materials, where the Material properties override the Profile ones.

Note that if you don't like it this way, you can always create Materials without temperature, that way Profiles will stay untouched.

**Comment by nallath** [comment]
We aren't very happy with how profiles work at the moment either. This is why we're reworking it as we speak.

The only reason why we did go forward with releasing it as it is, is because you have to make a release at some point. If you wait for everything to be perfect, you will never release anything.
