### ISSUE TITLE
extruder to high temperture gives not the normal temparature that must print with.

### ISSUE THREAD

**Issue by khan04what** [Ultimaker/Cura#7322]
when I put the gcode on the sdcard and start the print, my profile starts 205 degrees, but I looked at my screen and it shows 213 degrees which is way too high. Normally this is 205 degrees and then the temperature drops to 200 degrees print temperature now its hopping 209-206 degrees its take to long to go 200 temp printing temp. my prints and the first layer was better in cura 4.3.
so something in the g-code is processed incorrectly in cura 4.5 what i don't know. I must say that my printer has stood still for some time, maybe that has something to do with it.

**Application version**
4.5 cura

**Platform**
Win 10, card Asus strix gtx 960

**Printer**
Anycubic I3 Mega

**Reproduction steps**
1. (Something you did.)
2. (Something you did next.)

**Screenshot(s)**
(Image showing the problem, perhaps before/after images.) 

**Actual results**
extruder to hot profile is normal 205 degrees and not 213 degrees for first initial layer and hops also print temp normal temp is 200 degrees now its hopping 209-206 degrees its take to long to go 200 temp printing temp.
**Expected results**
first initial layer is normal 205 degrees then drops to 200 degrees print temperature  

**Project file**
(For slicing bugs, provide a project which clearly shows the bug, by going to File->Save. For big files you may need to use WeTransfer or similar file sharing sites.)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
printing with eryone marble filament
had no issues in cura 4.3

**Comment by Ghostkeeper** [comment]
Are you able to point out a problem in your g-code then?

Here's a bit of g-code sliced in Cura 4.5 for Anycubic i3 Mega: [test.zip](https://github.com/Ultimaker/Cura/files/4375721/test.zip)

Looking in that file you'll find all of the heating commands at `M104` and `M109`. For me, Cura only produces one M104 and one M109 at the start, both heating up to 200 degrees. It then cools down to 0 degrees at the end of the print (twice, due to the end g-code configured in the profile).

I'm thinking that it's just bad calibration of the heater in your printer.
