### ISSUE TITLE
Add a special mode to print first layer(s) all at once and the rest one at a time

### ISSUE THREAD

**Issue by moham96** [Ultimaker/Cura#7440]
**Is your feature request related to a problem? Please describe.**

When printing with print sequence (one at a time) you get a bit of speed because the head doesn't have to travel between the models each layer but you risk failure of some models due to first layers not sticking well, and you can't walk away from the printer after the first layer(s) of the first model.

**Describe the solution you'd like**

The solution in my mind would be to add a new print sequence that combines the advantages of both sequences (the speed of "one at a time" and the lower risk of non-sticking first layers of "all at once").
this new mode will print the first layer(or first layers whose number can be configure) all at once and then goes to print the rest layers of the objects one at a time.

**Affected users and/or printers**

This is most useful when printing multiple models(especially miniatures) and you need to print them one by one for speed or so you can use [M486 G-code](https://reprap.org/wiki/G-code#M486:_Cancel_Object) to cancel a failing object and move to the next object

**Comment by Ghostkeeper** [comment]
Took a while to respond here. We saw the potential of this pretty easily and then today went over how it would be implemented. In this architectural discussion we realised that it would be quite a refactor to implement this.

The "easy" solution of a post-processing step won't do due to the complexity of dealing with initial layer settings like initial layer fan speed, initial layer temperature, etc. It wouldn't be maintainable. The best solution we came up with is to add single-layer "meshes" to the first mesh group just after the slicing stage, and then remove the first layer from the rest of the mesh groups. Due to the complexity of this though we can't fit that in our planning so we've opted to defer this feature, put it on our long list of desires.
