### ISSUE TITLE
[4.6.0 Beta] Most Z Moves Missing

### ISSUE THREAD

**Issue by CCS86** [Ultimaker/Cura#7458]
4.6.0 Beta / Win 10

Well, this beta version just tore my print head up. After starting the initial layer at 0.2mm, there are no Z moves until like Z11.xx . So, the printer just kept printing at Z.2 until bad things happened :(

It was actually the PP script "retract continue", recently updated, which stripped out the Z coordinates, not Cura Engine.

[4.6.0.gcode.txt](https://github.com/Ultimaker/Cura/files/4459365/4.6.0.gcode.txt)

**Comment by smartavionics** [comment]
That gcode has been post-processed so maybe that's what zapped z? What does the post-processing script do?

**Comment by CCS86** [comment]
@smartavionics I think you are right. I had the "retract continue" PP script on, which I didn't connect to Z move modifications, since it should explicitly be creating E moves, not modifying any other axis. Removing that script appears to fix the issue.

I'll link to this issue in the script update issue.

**Comment by rburema** [comment]
The fix linked in that ticket was not the only one, did the updated script you donwloaded contain all three fixes? 

(https://github.com/Ultimaker/Cura/commit/d5166030d76838e4aa52c25338081468c2535195, https://github.com/Ultimaker/Cura/commit/9b997d421b25c1bfc56be7c68ba75fd8f6902653 and https://github.com/Ultimaker/Cura/commit/d9649dc3ddd7e055bc936030ae5f9ddc4b20bc7b)

For others following along: Those where added to the 4.6 branch _after_ the beta came out, so the issues are still in 4.6-beta, but _should_ be fixed in 4.6

**Comment by CCS86** [comment]
Maybe not. I downloaded a copy of the script linked by ghostkeeper.

**Comment by rburema** [comment]
> Maybe not. I downloaded a copy of the script linked by ghostkeeper.

If you mean the one in the issue, then that's the file with only one or two of the fixes applied, not all three.

**Comment by Ghostkeeper** [comment]
I don't think the other two fixes would make any difference in this regard. one is a transparent change to reduce indentation. The other is to counter rounding errors that would cause the script to have a false positive (it thinks there is a retraction but actually there isn't).

I could reproduce your issue after a few educated guesses. The culprit is that "Retract on Layer Change" is enabled. The script doesn't deal with that correctly. It also needs to start tracking Z moves to correct this.

**Comment by Ghostkeeper** [comment]
Fixed for 4.6 stable.
