### ISSUE TITLE
Resizing/scaling of model leads to corrupted slicing gcode

### ISSUE THREAD

**Issue by cyberrbob** [Ultimaker/Cura#7491]
**Application version**
4.5.0

**Platform**
Windows 10.0.18363
Intel HD 530 / Nvidia Quadro M1000M (two GPU's)

**Printer**
Sovol SV01 ( similar to Creality CR-10)

**Reproduction steps**
1. Opened the [model](https://drive.google.com/file/d/1RS-smsuv1VGXzCiDTIxCCShZ-EBQAiym/view?usp=sharing) and resized/scaled it ![scaled](https://user-images.githubusercontent.com/4995211/79115117-52b5f400-7d85-11ea-91a1-55d184471d3e.PNG)

 from 53mm to 100mm it in Cura.
2. Pushed the 'slice' button in checked the result: ![result](https://user-images.githubusercontent.com/4995211/79115053-24381900-7d85-11ea-9ccc-224937996696.PNG)

**Actual results**
Please see step 2. This is not a gcode-visualization issue, problem exists in actual printed model (I saw this bug too late, only after print is done).

**Expected results**
No gaps in the sliced result are expected.

**Project file**
[here](https://drive.google.com/file/d/14UZ13t4KIX6z3QBya30ONr_VjILrwk7m/view?usp=sharing) it is.

**Log file**
[cura.LOG](https://github.com/Ultimaker/Cura/files/4469240/cura.LOG)

**Additional information**
If I resize the model in Microsoft 3D builder and slice it - there is no problem.

**Comment by smartavionics** [comment]
The problem is that the model is not valid, it has errors....

![Screenshot_2020-04-13_13-36-01](https://user-images.githubusercontent.com/585618/79120860-d7a40c00-7d8b-11ea-9d0e-6048c2578a85.png)

The error regions are highlighted with that weird blue/purple pattern (that's a new cura feature that isn't in a release yet) but you can also see the warning shown by the cura mesh tools plugin (which is available now from the marketplace). Fix your model!

**Comment by cyberrbob** [comment]
Hm, okay I see it now. Model is not mine (I have very limited knowledge of 3d modelling). But anyway, thanks for quick reply.
