### ISSUE TITLE
Layer start

### ISSUE THREAD

**Issue by maukcc** [Ultimaker/Cura#7507]
**Is your feature request related to a problem? Please describe.**
in "travel" there is the option "layer start x" and "layer start y". These coordinates can result in a long travel move.

**Describe the solution you'd like**
We would like a "shortest" option, like in "Z seam alignment"

**Affected users and/or printers**
All

**Comment by Ghostkeeper** [comment]
This in fact used to exist, until [we implemented multi-threaded slicing](https://github.com/Ultimaker/CuraEngine/pull/472). Since we compute the mesh order in a separate thread for each layer now, the last mesh of the previous layer, or indeed the final position, may not be known yet when it computes the next layer. So it couldn't start computing the next layer because it doesn't know where to start the path optimisation from.

We consider this feature infeasible now. Sorry.
