### ISSUE TITLE
2.2.1: Z Shift in Model Footprint

### ISSUE THREAD

**Issue by CCS86** [Ultimaker/Cura#756]
I'm not sure if this is just a graphical glitch, or more serious issue. After importing this model I see:

![image](https://cloud.githubusercontent.com/assets/12439543/15613564/a95538b4-23f9-11e6-8710-a805b3133fb8.png)

[Cover.stl.txt](https://github.com/Ultimaker/Cura/files/286898/Cover.stl.txt)

**Comment by fieldOfView** [comment]
Have you dragged to object around at all? It is possible to push an object into the buildplate to cut off a portion of the bottom. If you drag an object up, it should fall back onto the buildplate again.

**Comment by CCS86** [comment]
That is, as-loaded. Dragging doesn't change it, nor does "lay flat". The model's frame is coincident with the XY plane.

**Comment by fieldOfView** [comment]
I see, it is an extremely small object, so you are zoomed in quite a bit.
I am 98% sure this is a graphics glitch. The "shadow" is drawn slightly above the buildplate to prevent graphic artefacts due to "depth fighting" (https://upload.wikimedia.org/wikipedia/commons/b/bb/Z_buffer-Z_fighting.png). Normally you don't see that, but when you are looking from very close-by it may become visible.

**Comment by Ghostkeeper** [comment]
The shadow is 0.1mm above the build plate to reduce z-fighting. Ideally we'd incorporate the shadow in the texture of the build plate but that has all sorts of difficulties.

If you zoom out all the way, you can still see the z-fighting, by the way. At some point the floating point precision in the depth image becomes too coarse.
