### ISSUE TITLE
CreatBot F430

### ISSUE THREAD

**Issue by Polax76** [Ultimaker/Cura#7573]
Hello, I installed the latest version of Cura 4.6 and did not find the CreatBot F430 printer there, can you send me the settings for the 3D printer.

**Comment by mahtDFR** [comment]
There's an issue template, please fill it out otherwise we need to exchange more messages to get the information needed to help you.

We don't maintain third party profiles and I can't see it merged in master, so you probably added it manually in your old installation. If you want it merged in future releases, someone will have to contribute a tested definition for it.
