### ISSUE TITLE
Layer Height & Skirt Bug

### ISSUE THREAD

**Issue by marco-117** [Ultimaker/Cura#7595]
**Application version**
4.6.0

**Platform**
Windows 10

**Printer**
Ender 3

**Reproduction steps**
1. Slice a Benchy Model with Layer height  of 0.2mm
2. Set a Skirt with one Line

**Actual results**
The printed heigth steps are 0.16mm
Printed skirt lines are >1

**Comment by rburema** [comment]
Can you attach a project file to the issue? (Save, don't export. Rename or zip to appease github.)

**Comment by Ghostkeeper** [comment]
I'm not able to reproduce this issue so far. Here is a snippet of g-code from the start of the print, where you can see it move to Z0.2 which is the initial layer height:

```
;LAYER_COUNT:50
;LAYER:0
M107
G0 F6000 X122.637 Y102.311 Z0.2
;TYPE:SKIRT
G1 F2700 E0
```

The second bug you're reporting is probably due to the [Skirt/Brim Minimum Length](https://github.com/Ghostkeeper/SettingsGuide/blob/master/resources/articles/platform_adhesion/skirt_brim_minimal_length.md) setting. Reduce that to 0 if you always want it to have the Skirt Line Count setting regardless of how small the skirt is then.

**Comment by marco-117** [comment]
![Unbenannt](https://user-images.githubusercontent.com/56135788/80525670-1f788500-8981-11ea-8660-962e1fdae400.PNG)

At first a screenshot. As you can see, the model has a heigt of 48mm and it is sliced into 275 layers. So one layer has a height of 0.17mm and NOT 0.2mm as in the configuration.

I added the project as you want, i hope it will help
[CE3_3DBenchy.zip](https://github.com/Ultimaker/Cura/files/4547900/CE3_3DBenchy.zip)

The explanation with the skirt should be the solution. The model is small and therefore one skirt line would be to short. Thank you for that.

**Comment by marco-117** [comment]
Here the same Model and same configuration in Cura 4.5.0. The amount of layers fits to the layer hight in the configuration.

![Unbenannt](https://user-images.githubusercontent.com/56135788/80526707-b265ef00-8982-11ea-8e9f-c56a105b5b47.PNG)

**Comment by nallath** [comment]
You seem to be using the dynamic profile. That has variable layer height enabled. The second profile doesn't use that. So you are simply comparing things that aren't the same.

**Comment by Ghostkeeper** [comment]
Disable Adaptive Layers or reduce the Adaptive Layers Maximum Variation setting to get a layer thickness closer to the median Layer Height setting.
