### ISSUE TITLE
[4.6.0] Layer Skipped 

### ISSUE THREAD

**Issue by Doriangaensslen** [Ultimaker/Cura#7618]
**Application version**
4.6.0

**Platform**
![image](https://user-images.githubusercontent.com/12153042/80510885-a0348280-897b-11ea-984c-0ffd2c9c05e7.png)

**Printer**
Ender 3

**Reproduction steps**
1. Download https://www.thingiverse.com/thing:790533/zip
2. Select only one CE3_Top_CornerF2 File
3. Print Settings Layer height 0.2 Infill Density 55% Speed 60mm/s
4. Print

**Screenshot(s)**
![IMG_3094](https://user-images.githubusercontent.com/12153042/80512574-fd313800-897d-11ea-976e-b4ce0450ded0.jpg)
![IMG_3095](https://user-images.githubusercontent.com/12153042/80512600-06baa000-897e-11ea-9873-466bd6ed6a7e.jpg)
![IMG_3096](https://user-images.githubusercontent.com/12153042/80513179-f6ef8b80-897e-11ea-8edc-1f9adc9363ed.jpg)

**Actual results**
The printer Prints flawlesly but just "forgets" to print a layer. I've tried again and it stopped ad the exatly same height (Picture 1). Strangely only there the infil skipped also a little which never happened otherwise. When i tried to print the same piece again but with other parts, it printed without a problem (picture 3). Today i printed another piece with complete other settings from thingiverse, and it skipped again a layer on another height (Picture 2). Normally i would suspect the printer but i've double checked everything, z-travels light and without a problem, the extrusion isn't and wasn't a problem. Since its reproducable with a file and the same settings i belive its a problem with the Slicing. 

**Expected results**
Print without problems

**Project file**
See description

**Additional information**
-none-

**Comment by bill-orange** [comment]
If you look in Preview does the preview show the layer missing or with printing accomplished correctly?

**Comment by Doriangaensslen** [comment]
In the preview the layers are perfectly fine

**Comment by bill-orange** [comment]
Thanks. I thought it might be the same problem as #7611

**Comment by Ghostkeeper** [comment]
> 4. Print

This is where I get stuck with the reproduction steps, since I don't have a Creality Ender 3.

From what I can tell from your pictures, comparing them to my own attempt at following your steps, it seems to fail around layer 90, no? I don't really see anything weird around layer 90. The closest thing that could possibly be a mistake is that it resets the E value at layer 119 because it would exceed E5000 and then cause larger and larger rounding errors in some firmware. But maybe the `G92 E0` occurs somewhere else for you. It's hard to tell without a project file or the g-code if the slice is exactly the same for me.

**Comment by Doriangaensslen** [comment]
I will print this piece again and if it fails again il send you the Gcode. right now im waiting for filament, since ive used all.

**Comment by Ghostkeeper** [comment]
Or maybe the Z stage gets stuck? Could use a bit of lubricant?

**Comment by GregValiant** [comment]
Is this still applicable today?  Can this be closed now?
