### ISSUE TITLE
2.1.1 not tagged as release

### ISSUE THREAD

**Issue by thopiekar** [Ultimaker/Cura#763]
When going to https://github.com/Ultimaker/Cura/releases the 2.1.1 codebase is not available to download.

Could you please tag this release?

**Comment by MarcusWolschon** [comment]
2.1.2 isn't tagged as added as a release too.

https://github.com/Ultimaker/Cura/tags

**Comment by thopiekar** [comment]
That's correct 😑

**Comment by nallath** [comment]
We're very good at forgetting things :$

**Comment by CReimer** [comment]
The same goes for CuraEngine, Uranium and libArcus.
Well, for libArcus it's actually worse. There isn't even 2.1.0 tagged.

**Comment by TZanke** [comment]
I think this issue is related to https://github.com/Ultimaker/cura-build

ubuntu-15.04-build-script.sh should have an optional option like "--version 2.2.0".
If argument is set, create tag at the end of script and push tags to github.

Optionally, if version is set, upload created files to download section. (very basic deployment process)

Best regards
Tobias

**Comment by Ghostkeeper** [comment]
2.1.3 is tagged.
