### ISSUE TITLE
Cubic Subdivision pattern slightly rotated by default

### ISSUE THREAD

**Issue by evilC** [Ultimaker/Cura#7635]
This is a follow-up from #7541 

**Application version**
4.5.0

**Platform**
Windows 10 x64  
nVidia Geforce 1080 Ti

**Printer**
Ender 3 Pro

**Reproduction steps**
1. Place a cube on the bed which is aligned with the X/Y axes
2. Slice using Cubic Subdivision

**Screenshot(s)**
![](https://i.imgur.com/CXtYuLz.png)

**Actual results**
The pattern is very subtly rotated by a degree or two

**Expected results**
The horizontal lines are properly horizontal

**Comment by smartavionics** [comment]
Here's something that isn't right, in SubDivCube::precomputeOctree(), the variable infill_angle is given type AngleRadians but initialised with 45 which looks like degrees. Later on, infill_angle is passed to the PointMatrix constructor which looks like it expects a value in degrees. So I would have thought that infill_angle should be of type AngleDegrees rather than AngleRadians. However, with that change, the line orientation is different but still not what I expected. Setting infill_angle to 0, however, has the desired effect.

Using    AngleDegrees infill_angle = 0;

![Screenshot_2020-04-30_17-10-12](https://user-images.githubusercontent.com/585618/80733374-8757d880-8b05-11ea-9f00-aaec4e56b794.png)

Using     AngleDegrees infill_angle = 45;

![Screenshot_2020-04-30_17-11-22](https://user-images.githubusercontent.com/585618/80733530-bbcb9480-8b05-11ea-8282-f116d6fa88db.png)


Using    AngleRadians infill_angle = 45;

![Screenshot_2020-04-30_17-11-54](https://user-images.githubusercontent.com/585618/80733563-c9811a00-8b05-11ea-934f-315a25ee3d60.png)

**Comment by evilC** [comment]
Awesome, thank you @smartavionics

**Comment by widget-** [comment]
> So I would have thought that infill_angle should be of type AngleDegrees rather than AngleRadians. However, with that change, the line orientation is different but still not what I expected.

The 45 degree one? It looks right to me

![image](https://user-images.githubusercontent.com/7691630/80749872-c168b080-8aec-11ea-89a7-2a26000012cb.png)

**Comment by smartavionics** [comment]
By jove, Sir! I think you could  be right, I was looking at the wrong line, methinks.

So, perhaps just changing that one line in the source to declare infill_angle to be of type AngleDegrees will be sufficient to fix the jaunty orientation that it has at the moment. Let's leave that to the UM devs to ponder...

**Comment by evilC** [comment]
In the absence of adding support for allowing us to pick rotation angle via the UI, please could you set `infill_angle` to 0?
Now that #7541 is implemented and the pattern is centered on the mesh, using 45 degrees will still tend to yield a non-symmetrical infill

**Comment by evilC** [comment]
Oh, and @smartavionics, any chance of one of your custom builds set like this while I wait for the proper release? Windows x64

**Comment by smartavionics** [comment]
Sure, I can make a build using:

 AngleDegrees infill_angle = 0;

I'll do it tomorrow, I'm too tired to do it now.

**Comment by evilC** [comment]
Oh and [those two commits that went into master](https://github.com/Ultimaker/CuraEngine/pull/1243/commits) too
Much appreciated

**Comment by Asterchades** [comment]
45 radians ~2,578.31°. If you take out the full loops (7 of) than you're left with ~58.31°. Given the offset angle of the pattern at 60°, that would make for the line going lower-left to upper-right being what has taken that value, indeed putting the entire pattern off by ~1.69°, which matches up with @evilC's rough estimate. So there's almost certainly a superfluous conversion going on there.

Regarding symmetry, rotating by 30° may give the results you're looking for.

**Comment by smartavionics** [comment]
Hi @evilC , a Windows-64 build that features these changes (including rotation) should be available to download in about 30 mins. Have fun!

**Comment by evilC** [comment]
@smartavionics Thank you, I can confirm that in your version, everything works exactly as I desire :)

**Comment by evilC** [comment]
FYI, similar issues with support structures - see #7643

**Comment by evtrados** [comment]
The PR's from @smartavionics regarding this issue have been merged, so this will be resolved in the next Cura release (i.e., v4.7).
