### ISSUE TITLE
Print Sequence - On at a time

### ISSUE THREAD

**Issue by MiguelFigueiredo47** [Ultimaker/Cura#7637]
Hello,
I am Miguel Figueiredo
I just update Cura for 4.6.1 version.
I can NOT print sequence in One at a time. Cura reduce my build volume. its impossible to print. 
This issue was not happening before at old versions. 
How can i solve it?

**Application version**
Cura 4.6.1

**Platform**
Microsoft Surface

**Printer**
Ender 3

**Comment by Vandrasc** [comment]
Hi @MiguelFigueiredo47 , thank you for your feedback. 

Unfortunately, I am not able to reproduce with just the information you provided, can you add a project file, screenshots, and logs? Thank you1

**Comment by MiguelFigueiredo47** [comment]
> Hi @MiguelFigueiredo47 , thank you for your feedback.
> Unfortunately, I am not able to reproduce with just the information you provided, can you add a project file, screenshots, and logs? Thank you1

Hello @Vandrasc,
I am used to print sequecence one at a time. 
with this new version 4.6.1 is not possible.
Cura enable print sequence one at a time just with one object at the build plate. if I multiply my objects cura automaticly reduce my build volume.
- Print Sequence - One at a time.
![Captura de Ecrã (73)](https://user-images.githubusercontent.com/64600588/80807072-1a4f4c00-8bb4-11ea-8886-224146b74b40.png)

-Print Sequence - One at a time (Multiple Objects) (PROBLEM)

![Captura de Ecrã (74)](https://user-images.githubusercontent.com/64600588/80807165-57b3d980-8bb4-11ea-917c-4e3205e9fd28.png)

**Comment by mahtDFR** [comment]
Looks like the build volume height has been reduced. So it's not a problem with the XY plane, but the Z plane. Note the bounding box z limit around your objects - it cuts off at around 30mm.

Here - I reproduced it too. 

![image](https://user-images.githubusercontent.com/17821912/80809021-21308b80-8bc1-11ea-9a9e-e1c55f0675f7.png)

As a workaround you can increase the gantry height in the machine settings. By default it's set to 25 for some reason.

![image](https://user-images.githubusercontent.com/17821912/80809118-4de4a300-8bc1-11ea-8bc8-0092206afa03.png)

I've seen this before and I think it's a problem with the machine definition itself. This is a third-party definition so it's nothing to do with us. We try to avoid changing third party definitions because we can't test them, so the original contributor or somebody else with one of these machines will need to fix it and submit a **fully tested** version to us - then we can pull it into a future release.

**Comment by Ghostkeeper** [comment]
The gantry height for the Ender 3 has been 25mm since forever. We have no reason to believe that to be incorrect. I don't understand why Miguel says this is a regression in 4.6.

**Comment by MiguelFigueiredo47** [comment]
I would like to say was my mistake confirm this problema was a regression in 4.6. 
serious apologies for my mistake. I had print sequence one at the time before, but i have to admit was with lower sice 25mm height.
one more time sorry for create this subject.
