### ISSUE TITLE
[website] Some corrections and improvements

### ISSUE THREAD

**Issue by sk8nfool** [Ultimaker/Cura#7645]
**Application version**
Website instructions for running from source in Ubuntu

**Platform**
Ubuntu 18.04

**Printer**
Does not apply

**Reproduction steps**
1. Visit https://github.com/Ultimaker/Cura/wiki/Running-Cura-from-Source-on-Ubuntu
2. Scroll to "Notes"
3. Attempt to follow instructions

**Screenshot(s)**
N/A

**Actual results**
"... ~/[USERNAME] ..." example

**Expected results**
"... ~/"

**Project file**
N/A

**Log file**
N/A

**Additional information**
N/A

I realize that the page is a work in progress but it really needs to be reviewed/rewritten.

On the page [here](https://github.com/Ultimaker/Cura/wiki/Running-Cura-from-Source-on-Ubuntu) in the **Notes** section the example "\~/\[USERNAME\]" is given. This probably won't produce the desired result if used anywhere. The **~** is converted to the value of "$HOME" automatically by most shells. The example would therefore produce "/home/friend/friend" where -friend- is the user's username.

It should also be noted that the following procedures install software at the system level and therefore require superuser privileges.

On the same page in the **Cura-build CMake workflow** section introductory paragraph you mention that there are 2 choices. Those two choices need to be indicated in some manner. For instance with the insertion of a header **METHOD 1** and **METHOD 2** in the appropriate places. As a suggestion I would change the introductory paragraph to something like

**There are two methods to choose from. The first uses the [cura-build-environment](https://github.com/Ultimaker/cura-build-environment) to download and install all the required components. The second method guides you through the manual installation of the required components and shows how to run Cura from them.**

By the way, the first method doesn't indicate how to run Cura from the resulting installation.

In any case the instructions in the first method say to "Open CMake and ..." in two places. There is no CMake file in either repository however there is a "cmake" directory chock full of *cmake* files. This needs clarification.

**Comment by Ghostkeeper** [comment]
Thanks for the corrections! I've applied them to the wiki. A few remarks:
* I've changed the "[USERNAME]" example to `/home/[USERNAME]/`. Because to remove the `[USERNAME]` example entirely would defeat the purpose of that paragraph.
* I made an introduction header. Good suggestion!
* I'm not sure what you mean with the last point though. There are CMakeLists.txt files in both repositories. With "open CMake" it means to run the application called "cmake" in whatever form you like, be it `cmake-gui`, `ccmake` or just plain old `cmake`. The guide assumes that you know what CMake is and how to use it. That there is a directory with .cmake files is an implementation detail, really.
