### ISSUE TITLE
[Cura 2.1.2] Unable to drag files in

### ISSUE THREAD

**Issue by RhinoAus** [Ultimaker/Cura#776]
Unable to drag files in from desktop; must use Open dialog box. Very, very slow and inefficient

**Comment by fieldOfView** [comment]
Could you see if this also happens if you restart Cura?

What happens on Windows is that the installer must run as "elevated" (admin) user. When it runs Cura after installation, Cura is also ran as elevated user, and that breaks dragging files from the desktop. If you run Cura normally, dropping files should work.

**Comment by Ghostkeeper** [comment]
> ran as elevated user, [...] breaks dragging files from the desktop.
:confused:

**Comment by RhinoAus** [comment]
Okay; so I ran it normally and dragging works again. Very odd bug :(

**Comment by fieldOfView** [comment]
Good to know it is only on the very first run.

**Comment by fieldOfView** [comment]
There's a possible (simple) fix which we will have to include in our installer:
http://stackoverflow.com/questions/16555625/how-to-launch-an-executable-on-the-end-of-installation-correctly
