### ISSUE TITLE
[master] infill mesh hides selected object "glow"

### ISSUE THREAD

**Issue by smartavionics** [Ultimaker/Cura#7765]
**Application version**
master

**Platform**
Linux with Qt 5.13.2

**Printer**
N/A

**Reproduction steps**

Loaded someone's project that has a large infill mesh that smothers most of the other models.

Selected one of the normal models that lie underneath the infill mesh.

View in prepare mode.

**Screenshot(s)**

![Screenshot_2020-05-15_14-51-57](https://user-images.githubusercontent.com/585618/82057915-edbf2800-96bb-11ea-968a-f8f697dd5b17.png)

**Actual results**

The object selection "glow" is not visible through the infill mesh.

**Expected results**

The highlighted outline of the selected object should still be visible through the infill mesh.

**Project file**

**Log file**

**Additional information**

Not really critical but a bit confusing inasmuch that you can select a model but it's not actually highlighted when viewed through the infill mesh.

**Comment by Ghostkeeper** [comment]
Indeed. I guess that's because there is no exception for translucent objects, compared to the normal case where the objects that block the view are actually solid:

![image](https://user-images.githubusercontent.com/2448634/82211902-eabd7500-9911-11ea-8482-bc793dc1cba3.png)

**Comment by fieldOfView** [comment]
Wouldn't it be useful/better to have the selection outline show the full outline of the selected model(s) _regardless_ of what is in front of it?

**Comment by nallath** [comment]
Wouldn't that look really weird if you have multiple objects selected?

**Comment by Ghostkeeper** [comment]
I think it's either this, or as fieldOfView says everywhere.

Everywhere would be fine. It will make prints like this look a lot different:
![image](https://user-images.githubusercontent.com/2448634/82308368-f7010b00-99c1-11ea-9a33-cb0a0e6e2753.png)
However in a way it would make it more clear as well.

To implement that, the best way is to re-render the entire scene in the selection buffer rather than to have that as an additional pass, and then don't render objects that are not selected.

However we decided that this doesn't get enough priority for us over other things. We probably won't get around to implement this any time soon.

**Comment by fieldOfView** [comment]
But if "someone" implements that, it will probably be merged?

**Comment by Ghostkeeper** [comment]
I'd be in for it. What would you say, @Yian-Lai ?

**Comment by Yian-Lai** [comment]
Yes, I agree. It will make it more clear.
