### ISSUE TITLE
Status of Marketplace plugins/materials installed

### ISSUE THREAD

**Issue by marine-3d** [Ultimaker/Cura#7771]
I'm having a bit of a clear out of my Cura setup and starting from fresh.

With a fresh install, Cura is asking to sync with my account. Before allowing this, I want to check which materials and plugins are actually on my account but without clicking into each tile on the website, there is no clear indication which items are already on my account.

Would it be possible to:
1. Have some sort of indication that a plugin is already 'added to Cura' on the tile itself (Image attached).
2. Having a filter near the search bar 'Installed', similar to the 'Materials Station' checkbox.
![Screenshot 2020-05-16 at 08 22 04](https://user-images.githubusercontent.com/53610024/82113649-88b51200-974f-11ea-836f-b5b6a1d5aa6c.JPG)

Many thanks,

**Comment by Ghostkeeper** [comment]
No, I'm afraid this is not possible for us, since we also have the requirement that this needs to work with multiple Cura installations. It's one of the major use cases this was intended for.

If there are multiple Cura installations, there can be some that have the plug-in installed and some that don't. Cura installations are not uniquely identifiable and some might never have logged in.

Or an installation could have logged in with a different account and synced the plug-in from there. Or perhaps the plug-in was installed while you were not logged in.

So I'm afraid that this is impossible with our current requirements. Sorry.
