### ISSUE TITLE
4.6.1 support interface inconsistency

### ISSUE THREAD

**Issue by batesman1** [Ultimaker/Cura#7808]
**Application version**
4.6.1

**Platform**
Win 10

**Printer**
Ender 3 Pro

**Reproduction steps**
Added model and sliced with standard supports and support interface enabled. Additionally there are odd holes in the support that shouldn't be there. If I switch to tree supports, the interface is present.

**Screenshot(s)**
![image](https://user-images.githubusercontent.com/49410803/82722615-5a2ac000-9c96-11ea-9892-34d7e25b39cb.png)

![image](https://user-images.githubusercontent.com/49410803/82722667-c4dbfb80-9c96-11ea-963d-856694c292aa.png)

**Actual results**
Slicer fails to add support interface when it should.

**Expected results**
The support roof and floor should be present where the support touches the model and the base.

**Project file**
[CE3PRO_Cultist_Body_NEW.zip](https://github.com/Ultimaker/Cura/files/4671208/CE3PRO_Cultist_Body_NEW.zip)

**Log file**
[cura.log](https://github.com/Ultimaker/Cura/files/4671212/cura.log)

**Additional information**
(Extra information relevant to the issue.)

**Comment by 64Florian** [comment]
Hello @batesman1 
In my point of view the top and bottom need at least one "gap" to let the user to be able to remove the support without braking the product ..
-> **Your product is very small (height less than 4 cm)**  
In you case, I confirm for your bottom of the support, it's a bit strange:
![Capture d’écran 2020-05-24 à 01 55 22](https://user-images.githubusercontent.com/34726380/82742703-b0186a00-9d61-11ea-8f02-bac75571caa8.png)

But if I revert your setting (by selecting again "Super quality" -> "Discard" ) 
then enable support and line I have a "good" support: 
![Capture d’écran 2020-05-24 à 02 07 08](https://user-images.githubusercontent.com/34726380/82742880-8bbd8d00-9d63-11ea-93a9-12b6be267eba.png)
**Please ! before doing that, save your profile**, otherwise you'll lose all your settings (_ok you have a backup on this forum now in the 3mf file .._ )

For dev and support teams: discard "clean" following settings:
![Capture d’écran 2020-05-24 à 02 10 03](https://user-images.githubusercontent.com/34726380/82742939-582f3280-9d64-11ea-9792-bfbf8c0d4610.png)
![Capture d’écran 2020-05-24 à 02 10 14](https://user-images.githubusercontent.com/34726380/82742940-58c7c900-9d64-11ea-870e-6bcb458971b9.png)

Sorry, for the moment, I was not able to find "why" the bottom of the support doesn't start where it should...

**Comment by rburema** [comment]
@batesman1  Could you try to setting either (or both) 'Support Stair Step Width' or 'Support Stair Step aximum Height' to 0? Just trying to confirm if part of this is related to a known issue (that we maybe finally getting to soon).

**Comment by Ghostkeeper** [comment]
Reduce the Minimum Support Area to 0 to make the support re-appear.

Reduce the Minimum Support Interface Area to 0 to make the support interface re-appear.

Those settings seem to be working as expected, so I'll close this issue.

**Comment by batesman1** [comment]
Confirmed. Resetting the minimum support interface area did the trick. Thanks to you all!
