### ISSUE TITLE
[4.6.1] "Select face to align to the build plate" doesn't quite align

### ISSUE THREAD

**Issue by fleutot** [Ultimaker/Cura#7839]
**Application version**
Cura 4.6.1

**Platform**
OS: Debian GNU/Linux 10 (buster) x86_64 
CPU: Intel i7-7500U (4) @ 3.500GHz 
GPU: Intel HD Graphics 620 

**Printer**
Ultimaker 2+

**Reproduction steps**
"Select face to align to the build plate" doesn't seem to go all the way. I noticed that because the skirt on my print didn't go around the whole part, it went through the middle.

The model directly after opening:
![Screenshot_2020-05-28_075048](https://user-images.githubusercontent.com/178409/83104621-67daae00-a0b9-11ea-946e-b78b3b3b5b04.png)

After "Select face to align to the build plate", seen from below. The face is not completely red, only half of it seems to be touching the build plate:
![Screenshot_2020-05-28_075116](https://user-images.githubusercontent.com/178409/83104659-7a54e780-a0b9-11ea-9076-fb2446a9515f.png)

After "Lay flat":
![Screenshot_2020-05-28_075130](https://user-images.githubusercontent.com/178409/83104671-804ac880-a0b9-11ea-8f4d-1ad79aa7b655.png)

This is how I expected the downward face to look like after "Select face to align to the build plate".

**Comment by fleutot** [comment]
This was a problem between the chair and the keyboard. The thin faces were not really parallel. Still, I don't get that "Lay flat" managed to places all the "not really parallel" faces flat on the build plate anyway.

**Comment by Ghostkeeper** [comment]
The lighter red and darker red happens because of the collision area shadow. That shadow is actually just a 3D plane. It's situated slightly above the build plate in order to prevent Z fighting. That's why faces that are on the build plate appear in a brighter red. This not only happens to faces that are 100% exactly aligned, but also to other faces as long as they fall beneath the 0.1mm Z coordinate or whatever that shadow is at.

The automatic "lay flat" option selects one of the lowest triangles to lay it flat on. It probably selected one that happens to make the rest of the triangles fall beneath the shadow. They are still not quite flat. Of course, the slicing also has a certain resolution due to the Initial Layer Height, so most likely the slice would succeed nonetheless.
