### ISSUE TITLE
Dual extrusion, prime tower

### ISSUE THREAD

**Issue by maaspt** [Ultimaker/Cura#7864]
Hi

I am having this issue since updating from version 3.4.1.
I am using 4.6.1 but when I need dual extrusion on first layer with prime tower, I have to use version 3.4.1

I have dual extrusion with only one nozzle.
Object has two colors on first layer, and prime tower is enable.

The issue is that Cura prints prime tower with first extruder before printing objetc, and does not print prime tower with second extruder after color/extruder change . Second color is printed without nozzle prime, all this in first layer.

When I use version 3.4.1, prime tower first layer is only printed after color/extruder change . Nozzle gets primed ok after first layer extruder/color change, and second color is printed ok.

I have this issue long time, after several cura updates I still have to use two versions to get some objets printed ok.

Is there any setting for this ? Or is it just me ?

Thanks .

**Comment by Ghostkeeper** [comment]
In the first layer it's using the "main" prime tower extruder to print the bed adhesion. This is to make the prime tower more stable. Otherwise it may topple over, because different materials tend to adhere not very well to each other.

But on the first layer it should also prime every nozzle anyway, whether you have a prime tower or not. That's why it's unnecessary to also prime with the prime tower. It will draw additional lines around your skirt or brim with every extruder, so that the nozzle gets primed that way.
