### ISSUE TITLE
Certain models cause planes to form in prepare screen

### ISSUE THREAD

**Issue by ragin76er** [Ultimaker/Cura#7913]
**Application version**
4.6.1

**Platform**
Windows 10 10.0.18362 Build 18362, i5-6600k CPU, Nvidia RTX 2070 GPU

**Printer**
Creality Ender-3

**Reproduction steps**
1. Downloaded this model: https://www.thingiverse.com/thing:2595559
2. Sliced it in Cura with 0.1 mm layer height and 0.2 mm first layer
3. Enable Spaghetti Infill (seems to be a trigger for this)

**Screenshot(s)**
At the top layer
![image](https://user-images.githubusercontent.com/47162371/84275320-89468b80-aaf6-11ea-8f34-dc74a3cee92f.png) 

The first layer issue on the model
![image](https://user-images.githubusercontent.com/47162371/84275510-c6ab1900-aaf6-11ea-815d-30974fb432e9.png)

**Actual results**
Every time there is a full layer break it changes the position of the model, makes prints unusable.

**Expected results**
No strange distortions and a normal print

**Project file**
Available on request, 

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
(Extra information relevant to the issue.)

**Comment by Ghostkeeper** [comment]
This is a visualisation issue. Spaghetti infill causes the infill of a lot of layers to be printed in one layer. Like, 100 layers is no exception. This creates a tiny line with a huge amount of extrusion. The layer view visualises this huge extrusion as if it's a line with a huge width.
What's more, layer view also creates endcaps on both ends of the line, which are as long as the line's width. This makes the surface area you see in layer view many times bigger than the actual extruded material.

The print actually also fails very often. I've never seen spaghetti infill work correctly myself. You need very specific materials to make it effective, apparently. We have a ticket in our backlog to remove this feature, actually, because the original intent of that feature is no longer applicable. Therefore I'm afraid that we won't fix this issue. The setting has a death sentence.
