### ISSUE TITLE
4.6.1 support issues

### ISSUE THREAD

**Issue by realacc** [Ultimaker/Cura#7929]
horizontal angles support doesn’t even touch the print resulting in failed print. Ender 3

**Comment by mahtDFR** [comment]
Well done for posting the issue template. Next step: fill it in so we can try to help you.

**Comment by rburema** [comment]
Found a brief description in the comments of the template. Edited the original to show it. Still not much to go on.

@realacc Have you tried adjusting 'Support Z Distance', 'Support X/Y Distance' and/or 'Minimum Support X/Y Distance'?

Alternatively, you could attach a screenshot or even the project, so we can see what's going on.

Thirdly, we've seen some support issues due to stair stepping not doing what's expected. A bug that we're working on and which will probably be fixed in 4.7. To test if you're affected, set either 'Support Stair Step Height' or 'Support Stair Step Minimum Width' to 0.

**Comment by realacc** [comment]
Hello, thanks for the response back. Yup I did try changing the support x/y
distance from .8 to .3 and it worked. I will also try the stair stepper
height to 0. Thanks again for your help.

**Comment by HeathHicks** [comment]
Is there a list of command line prompts and custom parameters for the silent deployment and configuration for either the exe or the msi?

**Comment by rburema** [comment]
@HeathHicks Is this what you meant? : https://stackoverflow.com/questions/8560166/silent-installation-of-a-msi-package/8560308#:~:text=You%20should%20be%20able%20to,end%20of%20the%20msiexec%20parameters.&text=You%20can%20read%20the%20options,options%20from%20Start%20%2D%3E%20Run.
