### ISSUE TITLE
Show setting changes

### ISSUE THREAD

**Issue by BagelOrb** [Ultimaker/Cura#7966]
**Is your feature request related to a problem? Please describe.**
I want to know which settings I have changed, so I can identify why my print is the way it is.
I would like to see an overview of the changed settings.

**Describe the solution you'd like**
In the profile dropdown there should be an option "Show current setting changes", which then opens a window very similar to the Discard changes dialog:
![image](https://user-images.githubusercontent.com/8895761/85387619-52846280-b545-11ea-814b-4ba8f21c9be1.png)

**Describe alternatives you've considered**
Have the same option in the dropdown, but it changes the setting visibility to show exactly those settings which have changed.

**Affected users and/or printers**
all

**Additional context**
After a couple of prints I forget what settings I am working with.

Current workaround is to change material and back.

**Comment by mahtDFR** [comment]
I've added this to the backlog, CURA-7528

**Comment by mahtDFR** [comment]
(Thanks for the request 😉)

**Comment by fvrmr** [comment]
We are constantly working on making Ultimaker Cura better. Our community is a big part of that by requesting new features and reporting bugs. 

To be able to focus on the most requested and needed features from our community and from Ultimaker, we have decided to remove this feature request from our backlog. We believe we will not work on this anytime soon and will therefore defer this issue.

Since Cura is open source, you or anyone else is more than welcome to work on this issue and create a pull request yourself.

**Comment by tyeth** [comment]
Install the Profile Analyser plugin, actually called Profil Analyser... I'm using the Support Guide plugin too, wonderful, mouse over guide for each setting.
https://marketplace.ultimaker.com/app/cura/plugins/5axes/ProfilAnalyser
