### ISSUE TITLE
[4.6.1] Gaps between wall and top/bottom surfaces

### ISSUE THREAD

**Issue by Fatturret** [Ultimaker/Cura#8009]
**Application version**
4.6.1 and 4.5

**Platform**
Windows 10 Home 64bit (10.0, build 18363)

**Printer**
Wanhao duplicator i3 1st gen (using the Wanhao duplicator i3 machine settings with the addition of a purge line at the start of gcode)
**Reproduction steps**
This has been happening for past few prints. It may have been happening longer that i didn't notice because i recently upgraded my nozzle and only now has it become apparent. but cura seems to be miss slicing the intersection between walls and surfaces. Originally it thought it was my printer but it actually shows up in the slicer.
I've tried messing with the fill tiny gaps etc settings and that doesn't seem to help, I also tried downgrading to cura 4.5 and the problem persists even using the stock settings. This seems to happen regardless of what model i use and seems to mostly affect 90 degree edges that are fairly small ledges.

**Screenshot(s)**
![Raw model](https://user-images.githubusercontent.com/6181568/86208068-ebf5e900-bbc3-11ea-8f39-e309ea9ce14f.PNG)
![Gaps in cura slicing](https://user-images.githubusercontent.com/6181568/86208106-0760f400-bbc4-11ea-8530-172ce0499709.PNG)

**Project file**
https://we.tl/t-aFGEiZYb4C

**Comment by Ghostkeeper** [comment]
Yeah, I see it. You'll need to reduce the Skin Removal Width setting in this case. [Here is a brief explanation of what the setting does.](https://github.com/Ghostkeeper/SettingsGuide/blob/master/resources/articles/infill/skin_preshrink.md) The last sentence mentions precisely your case. Setting it to 0.4mm seems to work better.

The setting removes thin strips of skin, because they often occur in nearly-vertical walls where skin is unnecessary. That saves time. The flip side is that this can also remove thin strips of skin elsewhere, such as when there is a thin ledge.
