### ISSUE TITLE
Add Mendel90 to cura 2.1.2

### ISSUE THREAD

**Issue by boelle** [Ultimaker/Cura#808]
attached is the JSON for the Mendel90

NOTE: rename it from mendel90.PNG to mendel90.JSON

![mendel90](https://cloud.githubusercontent.com/assets/3832239/16110722/71c26708-33af-11e6-8a24-5b97e9bab2f5.PNG)

and the platform stl

NOTE: rename from mendel90_platform.png to mendel90_platform.stl

![mendel90_platform](https://cloud.githubusercontent.com/assets/3832239/16110813/ee277874-33af-11e6-9282-7303b3e69c71.png)

**Comment by Ghostkeeper** [comment]
Added the files. Thanks for your contribution! The JSON required some structural modifications, but the values are still the same. I'm guessing that you meant for the machine head shape the minimum-x and minimum-y to be negative, otherwise you have a collision rectangle that doesn't even enclose the nozzle itself.

**Comment by boelle** [comment]
dooh.. yes

and also not sure if i got all variables in there that describe the hardware

there should be a generator for this :-D or some better documentation for dummies :-P

**Comment by Ghostkeeper** [comment]
There was a generator, but it's outdated. Eventually we'd like to allow people to make new machines "in-game".

**Comment by boelle** [comment]
that would be a good thing... 

i tried to test the JSON... but since i cant select comport and speed i had to stop where i'm now... once the comport selection is added i can test and adjust it.

mostly the start and end Gcode needs some tweaks
