### ISSUE TITLE
Change profile export/import handling

### ISSUE THREAD

**Issue by MisterPrintf** [Ultimaker/Cura#8112]
As I understand it, profile imports are currently handled in this manner:
-Search for listed preset
-IF preset found duplicate preset
-ELSE throw error&abort
-Apply listed changes to preset

The issue with this is that if the name of a preset changes, as occurred with the integration of Creawesome into Cura last year, old profiles can no longer be imported.
So, how it should work is simple.
When a profile is exported, every setting in the profile is saved.
Then, when it is imported, a new profile is created with the listed settings.

**Comment by nallath** [comment]
Some old profiles can indeed not be imported anymore. What you can do is add a custom ff printer and use that for creality. For those printers the update will still work as expected.

Unfortunately, the change that you suggest isn't quite possible, since the changes of a profile are on a profile _type_. Since the creality printer now has specific quality profiles per material, it's simply not possible to copy them (since you would be copying material specific settings with them as well). You can see https://github.com/Ultimaker/Cura/wiki/Profiles-&-Settings for more information.
