### ISSUE TITLE
[4.6.1] Infill mesh gets printed when overlapping cutting mesh

### ISSUE THREAD

**Issue by Block137** [Ultimaker/Cura#8125]
**Application version**
4.6.1

**Platform**
Win10

**Reproduction steps**
1. Add a normal model.
2. Add modifier mesh as "Infill mesh only"
3. Add another modifier mesh as "Cutting mesh"
4. Make the 2 modifier meshes overlap (does not need to overlap with model from step 1)
5. Slice

**Screenshot(s)**
![Screenshot (328)](https://user-images.githubusercontent.com/23495338/88923975-c5979c00-d29c-11ea-818d-608c4338e505.png)
![Screenshot (329)](https://user-images.githubusercontent.com/23495338/88923982-c6c8c900-d29c-11ea-9124-7b29782f4020.png)

**Actual results**
Overlapping region of the 2 modifier meshes gets printed even though it is outside of actual model.

**Expected results**
Modifier meshes don't interact with each other. Only modify meshes that are normal models.

**Project file**
[overlaps.zip](https://github.com/Ultimaker/Cura/files/5001251/overlaps.zip)

**Log file**
None provided

**Additional information**
1. Infill mesh order has no effect.
2. Overlapping region of modifier meshes of the same type (infill only / cutting) does not get printed.

**Comment by nallath** [comment]
We've added this to our backlog: CURA-7636

**Comment by fvrmr** [comment]
We are constantly working on making Ultimaker Cura better. Our community is a big part of that by requesting new features and reporting bugs. 

To be able to focus on the most requested and needed features and bug fixes from our community and from Ultimaker, we have decided to remove this bug from our backlog. We believe we will not work on this anytime soon and will therefore defer this issue.

Since Cura is open source, you or anyone else is more than welcome to work on this issue and create a pull request yourself.

**Comment by Block137** [comment]
Still happening in 5.3.1
![Screenshot (270)](https://github.com/Ultimaker/Cura/assets/23495338/c2b2d465-dc05-4d38-ab5d-00c8f120604f)
![Screenshot (269)](https://github.com/Ultimaker/Cura/assets/23495338/2e6aecfc-35b1-4be2-a896-4d91a17edfdd)

**Comment by MariMakes** [comment]
Hey @Block137,

👋 Fresh eyes reporting for duty. 
Thanks for double-checking this behavior in 5.3.1 and letting us know. 💪 

Can you help me understand, how this bug is limiting how you are working with Cura? 
Do you have an example of a time when you had overlapping meshes that were printed when you did not want them to?

This extra context makes it easier for us to understand the priority of this bug. 
Thank you 🙏
