### ISSUE TITLE
Allow Prime Tower setting height.(use 2-in-1 hotend)

### ISSUE THREAD

**Issue by sw35** [Ultimaker/Cura#8166]
Printer
Custom Printer , 2-in-1 Hothend ,2 extruders with shared heater(mixed nozzle).

**Is your feature request related to a problem? Please describe.**
When I print bigger things, because Prime Tower not be printed to the top, 
there will always be problems,  Ex. material liquefaction, dripping, dyeing

I think it’s because another material has been in the heating zone for too long, causing problems

![2020-08-10_120655](https://user-images.githubusercontent.com/17957752/89751319-25ded700-db02-11ea-8dea-e7412229658a.png)

**Describe the solution you'd like**
(A clear and concise description of what you want to happen. If possible, describe why you think this is a good solution.)

**Describe alternatives you've considered**
I always create a new square and designate it as a support material,
The height is the same as the model, and it is forced to be printed on top.
To solve this problem

But this is a waste of material and time.

Hope to increase the option of setting Prime Tower height

![2020-08-10_120735](https://user-images.githubusercontent.com/17957752/89751338-3000d580-db02-11ea-9929-beab71d2fcec.png)

Sorry I am not aware of how to fill an issue and  English is not my native language

**Comment by Ghostkeeper** [comment]
What happens when you make a single-extrusion print? Does it also cause liquefaction, dripping, discolouration?

The prime tower only lasts until the last extrusion switch, because after that, the print is basically just a single extrusion print. To the nozzle it doesn't matter whether it continues printing on one big layer, or whether it continues with a higher layer. It just keeps on printing.

If your problem is actually that the filament degrades when it's heated for too long, I suggest you lower the printing temperature. All 3D printed filament is designed to be heated while in the Hot Zone of the nozzle of a normal continuous print.
If your problem is that the print is too fast and the previous layer hasn't solidified yet, I suggest you take a look at the [Minimum Layer Time](https://github.com/Ghostkeeper/SettingsGuide/blob/master/resources/articles/cooling/cool_min_layer_time.md). Increasing the minimum layer time will force Cura to slow down so that the layer has enough time to cool down. There are also other settings like fan speed (which should probably always be at 100% for PLA anyway).

**Comment by sw35** [comment]
I use a single nozzle and will not have these problems 

I have this problem with 2-in-1 Hothend(mixed nozzle)

I think it should be the sprinkler, the material will drip out when the sprinkler is retracting, as shown below
![2020-08-20_181554](https://user-images.githubusercontent.com/17957752/90758246-4c2a2100-e311-11ea-99d7-b11dfd3a31de.png)

It is true that lowering the nozzle temperature can improve these problems, but the strength and combination of the printed model will be very poor.

I use two different materials, such as PLA and PVA (for support), because of set a higher material temperature
Will make these problems more frequent

Sometimes, because of these problems, it may lead to model failure or model misalignment

That’s why I hope to have this function to print out liquefied materials in advance

**Comment by Ghostkeeper** [comment]
So if you only use the first extruder in a print it's fine, but if you've used the second extruder for a few layers 12 hours ago, the first extruder will continue to print badly for the rest of the print? I really don't understand. After the second extruder has printed its blue layers, the print is effectively single-extruder from then on. The second extruder is retracted and gone.

It shouldn't need to heat up to the PVA printing temperature any more or anything. If you're printing PLA+PVA but the layers with PVA is done, it should be printing PLA at 190 degrees or something for the rest of the print. It's also printing PLA at 190 degrees if you're printing single extrusion. How could it ooze differently if at some point in archaeological history it switched materials?

**Comment by sw35** [comment]
I'm sorry, I clarify the hotend I use
I use 2-in-1 Hothend, 2 extruders with shared heater (mixed nozzle).
As shown below
![2020-08-25_050042](https://user-images.githubusercontent.com/17957752/91096323-73c21600-e690-11ea-9d08-e7f278127ec8.jpg)

Both materials are heated together, only one temperature can be set
![2020-08-25_050340](https://user-images.githubusercontent.com/17957752/91096346-7ae92400-e690-11ea-90a7-128edfc8c0ae.jpg)

That's why there will be problems when the hotend retracts and moves.

I use this hotend because I need to mix colors in my work
But there is also a need for two-color, two-material applications.

**Comment by Ghostkeeper** [comment]
Yeah so what is the problem with that hot-end then if there used to be a different material in the nozzle chamber at some point several days ago, that would require you to switch back and forth at every layer days later?

**Comment by Ghostkeeper** [comment]
Maybe it just needs a longer Nozzle Switch Retraction Distance, to pull the inactive material out of the hot zone?
