### ISSUE TITLE
[4.6.2-4.7 beta] Possible unneded gap filling

### ISSUE THREAD

**Issue by Liger0** [Ultimaker/Cura#8217]
**Application version**
4.6.2, 4.7 beta

**Platform**
Windows 10 x64

**Printer**
Cr10S

**Reproduction steps**
1. Load my obj model
2. 0.4 nozzle, 0.12mm layer height
3. Slice

**Screenshot(s)**
![gap filling triangle](https://user-images.githubusercontent.com/20385116/90935550-bf13c480-e403-11ea-83dd-dbd3e611a2ad.png)

**Actual results**
Without gap filling, part of the triangle is not printed. With it, those parts are printed as a gap filling

**Expected results**
All the faces of the triangle have the same width of 0.8, I don't see why the external ones are printed correctly while the internal ones can't be. 
So, it may be possible to print it fully without gap filling.

**Project file**
[test triangle gap filling.zip](https://github.com/Ultimaker/Cura/files/5111303/test.triangle.gap.filling.zip)

**Comment by Ghostkeeper** [comment]
It's a faulty model in this case. The two triangles have been pasted on top of the surface here, as you can see with a model editor like Blender:
![image](https://user-images.githubusercontent.com/2448634/91063451-4e042500-e62e-11ea-99ef-9094368da5b8.png)

But those triangles are not attached to the main body everywhere. You can see this happening if you reduce the outer wall line width (e.g. to 0.1mm) and set the outer wall inset to 0mm.
![image](https://user-images.githubusercontent.com/2448634/91063943-e13d5a80-e62e-11ea-90db-dd6dbdc16d20.png)

The triangle is protruding exactly 0.4mm. Since the line width is 0.4mm, you'd be on the edge of having a printable object. However with an additional 0.15mm Outer Wall Inset, you've got nothing left then.
