### ISSUE TITLE
[4.6.1] z seam not placed at sharpest corner

### ISSUE THREAD

**Issue by Triangulix** [Ultimaker/Cura#8220]
**Application version**
Cura 4.6.1

**Platform**
Windows 10

**Printer**
Heavily modified Tevo Tornado

**Reproduction steps**
1. Select "Sharpest Corner" as z seam alignment
2. Print something with corners

**Screenshot(s)**
![20200822_013228](https://user-images.githubusercontent.com/43012099/90943111-ba0d4000-e418-11ea-9fa4-4a5697611b4b.jpg)

**Actual results**
The seam is not placed at the sharpest corner but in a round part.

**Expected results**
The seam should be placed at one of the two 90° corners.

**Project file**
[Bugelhalter 8.zip](https://github.com/Ultimaker/Cura/files/5111663/Bugelhalter.8.zip)

**Comment by Ghostkeeper** [comment]
That's because the Seam Corner Preference is set to "Hide Seam". That means it's going to choose the sharpest *inner* corner to try to hide the seam as best it can. To get a better result for this print, I'd recommend "Smart Hiding", which chooses the sharpest inside corner if there is one, or the sharpest outside corner otherwise. It's made to fix cases like this. Or otherwise choose "Hide or Expose Seam" which works like what you're probably expecting it to do.
