### ISSUE TITLE
Support for Tiertime Printers

### ISSUE THREAD

**Issue by Julzilla** [Ultimaker/Cura#8228]
Looking for Cura support to be added for all Tiertime printers.

Cura supports a lot of 3D printers except for the Tiertime line. I would love to be able to slice my projects with Cura as the Up Studio lacks many parameters to tweek projects.

Printers to support:
- X5, 
- UP300
- Up mini 2 ES
- UP BOX,
- UP BOX Plus
- Up Mini 2
- Cetus3D

Cheers

**Comment by nallath** [comment]
All third party printers (eg; Non-Ultimaker printers) have been added by community members as contributions. Since we don't have (or support) those printers, it's impossible for us to create these profiles.

You can find more information on how to add new machines to cura on https://github.com/Ultimaker/Cura/wiki/Adding-new-machine-profiles-to-Cura
