### ISSUE TITLE
Helper Mesh Icon dispeared in the left toolbar, eraser mesh doesn't work

### ISSUE THREAD

**Issue by soleshoe** [Ultimaker/Cura#8241]
I was using Helper Meshes (2) to prevent support generation at some point in my model, it worked as expected.
I've saved the project then when reloaded, the helper mesh icon disapeared from the left toolbar.
I tried to use eraser meshes (1) instead but it has no effect on support generation.

**Application version**
4.7 beta

**Platform**
MacOS 10.15.6 (19G73)

**Printer**
(Which printer was selected in Cura?)

**Reproduction steps**
1. install fresh cura 4.7 beta version
2. load a model then apply some helper meshes to prevent support generation
3. save the project
4. quit Cura
5. re-launch Cura
6. load the saved project
7. The helper mesh icon (2) dispeared from the left toolbar

**Screenshot(s)**
(Image showing the problem, perhaps before/after images.) 
![image](https://user-images.githubusercontent.com/940041/91267841-7a29be00-e774-11ea-90e0-bc52e195bd4d.png)

**Actual results**
(What happens after the above steps have been followed.)
![image](https://user-images.githubusercontent.com/940041/91267987-c7a62b00-e774-11ea-96c2-f85a7ac80c1f.png)

**Expected results**
(What should happen after the above steps have been followed.)
![image](https://user-images.githubusercontent.com/940041/91268185-25d30e00-e775-11ea-9adb-e4cdc3127ea0.png)

**Project file**
(For slicing bugs, provide a project which clearly shows the bug, by going to File->Save. For big files you may need to use WeTransfer or similar file sharing sites.)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
(Extra information relevant to the issue.)

**Comment by Ghostkeeper** [comment]
There is no "Helper Mesh" tool in Cura's normal distribution. There never has been. Could it be that this was a plug-in you installed? There is also no plug-in in the Marketplace though that adds any "Helper Mesh" tool there, as far as I know.

What you're looking at seems normal to me. No missing tools or anything. Support Blocker and Per-Object Settings are still there. And the screenshots in your expected behaviour and actual behaviour are exactly the same.

Or maybe you just upgraded from a rather old release and are confused because the icons changed? The icon for the per-object settings tool was changed to those four hourglass figures, second from the bottom, a few releases ago.
