### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by Theprogramlouis** [Ultimaker/Cura#8278]
**Application version**
4.7.0

**Platform**
windows 10

**Printer**
dagoma magis

**Reproduction steps**
1. lancer un impression

**Screenshot(s)**
![Bug](https://user-images.githubusercontent.com/70466426/91654404-a0b76400-eaa8-11ea-8308-cec2459778ad.png)

**Comment by Sophist-UK** [comment]
@Theprogramlouis Issue title of "Bug" is extremely unhelpful. Indeed The screen shot leaves us guessing as to what the issue is?

1. Are you using USB Printing or Octoprint? You cant tell from the screen shot and you don't say.

2. You haven't given any information about the object you are trying to print, your Cura settings, whether this is the screen shot immediately after you start printing, and whether the print actually happens or not.
