### ISSUE TITLE
2nd layer issue

### ISSUE THREAD

**Issue by ultravision3d** [Ultimaker/Cura#8307]
**Application version**
4.7.0 and 4.6.2

**Platform**
windows 8.1

**Printer**
creality ender 3 pro

**Reproduction steps**
1. download this item (calibration cube) https://www.thingiverse.com/thing:1278865 or https://www.youmagine.com/designs/10mm-cube
2. use Cura default settings with creality ender 3 selected 
3. open generated gcode with Cura

**Screenshot(s)**
![2ndlayerissue](https://user-images.githubusercontent.com/70686439/92089067-f6a04a80-edcd-11ea-8a59-854958cf9598.png)

**Actual results**
2nd layer is bigger than others, causing elephant foot when printing, tested on 4.7.0 and 4.6.2 with several stl

**Expected results**
equal size layers

**Comment by rburema** [comment]
I can see this as well. I've added it to the list of things to be discussed.

**Comment by Ghostkeeper** [comment]
This does not reflect in the print this way. I believe your elephant's foot is the result from your normal print quality issues, not the result of first reloading the g-code file in Cura.

You can verify this as well by looking at the extrusion amounts. The layer height of this layer is 0.2mm. Here are two lines from the skin of the second layer, which allows us to calculate the length of the second line:

```
G1 F1350 X108.49 Y126.51 E53.8868
G1 X108.49 Y108.49 E54.48615
```

So it's moving from `Y126.51` to `Y108.49`, a length of 18.02mm, and it's extruding from `E53.8868` to `E54.48615`, a length of 0.59935mm. That length of filament has a volume of `0.59935mm * pi * (1.75mm / 2)² = 1.4416mm³`. That volume divided by the line length and the line height results in a line width of `1.4416mm³ / 18.02mm / 0.2mm = 0.4mm`, which is the configured line width for skin. So the line width is correct in the g-code.

This problem comes from faulty assumptions of the layer height. In this case, due to the start g-code of the Creality Ender 3, the layer view assumes that the initial layer height is 0.3mm. It then sees that the second layer starts at 0.4mm and so that layer must be 0.1mm thick. But because it still sees the same amount of extrusion, it assumes that the lines must be twice as wide. It is a problem in layer view only. It will not explicitly print this way. I suggest you look at adjusting your settings to fix the Elephant's Foot.

Because of its low impact we've decided to defer this issue. It will not get any great priority from us over more pressing issues unless the situation changes.
