### ISSUE TITLE
Custom supports to work along with tree supports

### ISSUE THREAD

**Issue by Liger0** [Ultimaker/Cura#8325]
**Is your feature request related to a problem? Please describe.**
Tree supports can be very useful, but some parts may still be no reached.
Using tree supports, custom supports aren't sliced.

**Describe the solution you'd like**
Allow the construction of custom supports along with tree supports

**Affected users and/or printers**
Any

**Comment by Ghostkeeper** [comment]
Since it's expected behaviour that custom support meshes should still be printed even if tree support is used, I'll change this to a bug report.

**Comment by Ghostkeeper** [comment]
However I'm unable to reproduce the issue. For me the custom supports still get printed as they should.
![image](https://user-images.githubusercontent.com/2448634/92398134-46fa0e00-f128-11ea-9fd7-e8a4e146d5b1.png)
![image](https://user-images.githubusercontent.com/2448634/92398147-4f524900-f128-11ea-99e7-549e3c5f5d91.png)

**Comment by Ghostkeeper** [comment]
Keep in mind that if your custom support model has a great wide volume, you might want to increase the Support Infill Density, as it's usually set very low for tree support.

**Comment by Liger0** [comment]
I looked up a bit and it seems this is in fact a feature request. I was wrong thinking they couldn't be printed together.
The reasons they weren't are different and caused by 2 facts:

First, I want tree support to start from the build plate, but I positioned the custom support to start from the model, so it isn't printed. 
The request here is to enable separate positioning options.

Second, when i positioned the custom support, it was on the model, so it wasn't created, but this, over not generating the custom support itself, caused another issue: in the area where it is supposed to be, the tree supports are skipped and the slicing takes an immense amount of time. 
So this would require a special check, so if it finds some intersection between the first layer of the custom support of the model and the tree supports with the supports from the build plate only, it should not considert he custom support but use the tree support instead of deleting it. What happens now is that it literally works as if the custom support was a support blocker instead.

**Comment by Ghostkeeper** [comment]
> First, I want tree support to start from the build plate, but I positioned the custom support to start from the model, so it isn't printed.
The request here is to enable separate positioning options.

Indeed when "Touching Buildplate" is enabled, area support that doesn't touch the build plate is removed right now, including support meshes. It would be more powerful if that didn't happen. This is not specific to tree support; it also happens when you have "normal" support.

> in the area where it is supposed to be, the tree supports are skipped and the slicing takes an immense amount of time.

I'm unable to reproduce this issue. I have a support mesh set up like this:
![image](https://user-images.githubusercontent.com/2448634/92705391-f830bc00-f353-11ea-822c-3589edd1317c.png)
And it ends up like this:
![image](https://user-images.githubusercontent.com/2448634/92705558-18f91180-f354-11ea-911f-c574626c17e1.png)
So the tree support keeps on generating through this custom support mesh. It also didn't take any longer to slice with the support blocker than without.

**Comment by Liger0** [comment]
Maybe because the branches start from the same point? Mine was a single tree branch. Not sure.

**Comment by Ghostkeeper** [comment]
Do you have a project file where support meshes cause tree support to be skipped, then?

**Comment by GregValiant** [comment]
I'm cleaning house.
Is this still an issue in current Cura versions (5.8.0 and up)?  Can this be closed?
