### ISSUE TITLE
Generic PC material does not have supported profiles on Creality

### ISSUE THREAD

**Issue by amantegazzi** [Ultimaker/Cura#8334]
**Application version**
4.7

**Platform**
(Information about the operating system the issue occurs on. Include at least the operating system and maybe GPU.)
Win10 Pro 64bit, Core i7-6700, Radeon R9

**Printer**
Creality CR10S Pro

**Reproduction steps**
1. Select Generic PC as material, result in not supported profile

**Screenshot(s)**
![image](https://user-images.githubusercontent.com/35607226/92334495-c6d39a00-f08e-11ea-9498-53b3fce8d7c1.png)

**Actual results**
Cannot have multiple profiles for standard and low quality.

**Expected results**
(What should happen after the above steps have been followed.)

**Project file**
NA

**Log file**
NA

**Additional information**
(Extra information relevant to the issue.)

**Comment by nallath** [comment]
We rely on community contributions for third party printers. Since no-one contributed these profiles, Cura shows a not supported profile warning.

Do note that you can still manually set the layer height to be something lower. The not supported warning is just there to indicate that Cura fell back to more generic defaults, which may or may not work (aka; A significant amount of tweaking might be needed to get it to work).

If any such profiles for PC are contributed, we would be more than happy to review / merge them.

**Comment by amantegazzi** [comment]
Is there a documented way to contribute?

Best, Andrea
________________________________
