### ISSUE TITLE
Model not sliced

### ISSUE THREAD

**Issue by SaluTony** [Ultimaker/Cura#8376]
**Application version**
V4.7.1

**Platform**
Windows

**Printer**
Creality CR-10

**Reproduction steps**
Load .STL file.   Click Slice. 

**Screenshot(s)**

**Actual results**
The result is 0 minutes, 0 grams, 0 meters. (It did not slice)

**Expected results**
Should have sliced something or given an error message.

**Project file**
[TestPyramid.zip](https://github.com/Ultimaker/Cura/files/5214363/TestPyramid.zip)

**Log file**
[cura.log](https://github.com/Ultimaker/Cura/files/5214397/cura.log)

**Additional information**
the model is an "empty pyramid" with a wall tickness of 0.25. The target is to test a tall print without using too much material.

**Comment by konskarm** [comment]
As far as I see, the model is **extremely thin**, so CuraEngine _doesn't have anything to slice_. I tried increasing the size of the printer to 1000x1000x1000 in the machine settings and then scaling the model to ~160% (to make its walls thicker). Then, using a 0.06mm layer height and a line width of 0.1mm, the slicing process generated a tangible result (after a good 1hour of slicing).

![image](https://user-images.githubusercontent.com/19388042/93075883-bc189680-f686-11ea-85d7-67cfb361eaf3.png)

Ultimately, this is expected behavior so I am closing this issue.
