### ISSUE TITLE
[4.7] Support is printed where it shouldn't

### ISSUE THREAD

**Issue by GMagician** [Ultimaker/Cura#8383]
**Application version**
Cura 4.7

**Platform**
Win10

**Printer**
Ultimaker S5

**Reproduction steps**
1. Open project
2. Slice it

**Screenshot(s)**
![Senza nome](https://user-images.githubusercontent.com/3684609/93118232-42050380-f6c0-11ea-8b47-36423fb57920.png)

**Actual results**
Base support is printer on whole base

**Expected results**
An hole in support should be present

**Project file**
[bug.zip](https://github.com/Ultimaker/Cura/files/5220014/bug.zip)

**Additional info**
Disable option to automatically place items in plate

**Comment by nallath** [comment]
Change the value of "support merge distance" to zero. The round circle is simply too small and it is filled by the merge distance.

**Comment by GMagician** [comment]
@nallath thanks for your answer but I can't find any "support merge distance" option
![Senza nome](https://user-images.githubusercontent.com/3684609/93211404-7bda1680-f761-11ea-9475-235d1a76eb02.png)

**Comment by rburema** [comment]
@GMagician I think it's support _join_ distance.

**Comment by GMagician** [comment]
@nallath & @rburema it doesn't work either
![Senza nome](https://user-images.githubusercontent.com/3684609/93236709-6f64b680-f77f-11ea-8fee-9afabd67c070.png)

**Comment by GMagician** [comment]
@nallath & @rburema I found why it's not working and how to let it works, but it's a bug to me.

Overriding value where you see in picture: **it doesnt' work**.
With such override I enabled supports in print settings and I wrote 0 there in "support join distance": **it doesn't work**
With override 0, print setting->support join distance 0 I re-disabled support enabled: **it works**!

I think that that's definetively a bug, even if not the original posted

**Comment by rburema** [comment]
That is strange indeed. I'll at least reopen it, and then we'll rediscuss how much priority this should get.

**Comment by Ghostkeeper** [comment]
We had an incongruence here in how the setting is displayed in the front-end and how the setting behaves when slicing. Basically, the problem was that the front-end thinks it's a per-object setting but the back-end gets the setting value as a per-extruder setting (from the Support Infill Extruder).

Here's a workaround for you:
1. Enable support.
2. Set Support Join Distance to 0.
3. Disable support again.

It then shows the hole as expected.
![image](https://user-images.githubusercontent.com/2448634/93338896-36821b80-f82b-11ea-8933-31eee5241fda.png)

I've fixed this for 4.8. The changes I made are:
* The setting can no longer be added as a per-object setting.
* The setting will show up now if support is disabled but there are support meshes in the scene (so you don't need to enable-change-disable support any more).

Same goes for Support Horizontal Expansion, which had the same problem.
