### ISSUE TITLE
[4.6 / 4.7]  Issues when an XY parallel face falls between layer heights

### ISSUE THREAD

**Issue by CCS86** [Ultimaker/Cura#8389]
**Application version**
4.6 / 4.7

**Platform**
Win10

**Printer**
Prusa i3

**Reproduction steps**
Open attached project file, look at layer 70 / 71

Cura seems to struggle with planar faces, parallel to the build plane, which fall between layer height increments. The expected behavior is that the entire planar face is included or excluded from a given layer. The actual behavior is that some random chunks are included/excluded.

Bad behavior:
![image](https://user-images.githubusercontent.com/12439543/93269163-193e4600-f774-11ea-9fce-b26830952d55.png)

The only change here is first layer height changing from 0.3mm to 0.29mm:
![image](https://user-images.githubusercontent.com/12439543/93269294-53a7e300-f774-11ea-9843-ab90c4aaf1e9.png)

The layer immediately below:
![image](https://user-images.githubusercontent.com/12439543/93269360-71754800-f774-11ea-907a-5beef05270fe.png)

Project file:
[ColletFixture.3mf.txt](https://github.com/Ultimaker/Cura/files/5228443/ColletFixture.3mf.txt)

**Comment by rburema** [comment]
Doesn't occur in the current main branch. Likely related to #8240 and fixed by https://github.com/Ultimaker/CuraEngine/pull/1313

In other words: _We expect this to be fixed in 4.8_

In the meantime, if the current workaround is not to your liking, you could _maybe_ also adjust the 'Slicing Tolerance' under the 'Experimental' settings.
