### ISSUE TITLE
4.7.1 - Some of the support merges with print

### ISSUE THREAD

**Issue by wyekey** [Ultimaker/Cura#8442]
Application version - 4.7.1
Platform - Windows 10 x64 
Printer - Ender 3

Issue has occurred on every print since I upgraded from 4.7 to 4.7.1. Four models were downloaded from thingiverse and myminifactory, and one was a model I designed and had printed previously with no issues ( prior to Cura version 4.7.1 ). Parts of the support filament merge with the print, both when the support is from the bed upwards and when coming off a part of the print itself. It doesn't happen with all supports though.

**Reproduction steps**
Import into Cura - slice - save file - print.

**Screenshot(s)**
The model that is my design displays in Cura correctly prior to slicing. 

1) The design has a slightly curved base ( it fits over the crossbar of my bicycle ). Support filament is printed from the bed and should just peel off to leave a smooth curved surface. 

![Image 008](https://user-images.githubusercontent.com/70485838/94211620-d7c33e80-fec9-11ea-95dc-471b4195fce4.png)

the model rotated to show the curved surface better

![Image 014](https://user-images.githubusercontent.com/70485838/94211746-46080100-feca-11ea-85c6-bcf23bdee499.png)
  
![Image 015](https://user-images.githubusercontent.com/70485838/94211862-84052500-feca-11ea-991c-002310527538.png)

2) There are two small rectangular holes in the side of the print that go right through and out the other side.  

![Image 010](https://user-images.githubusercontent.com/70485838/94211914-a0a15d00-feca-11ea-9c8e-c3f6147fc78d.png)

**Actual results**

1) The only support you can peel off are four small domes around four holes and two small end parts, so it's very uneven. The rest of the support material is part of the print.

![3 (4)](https://user-images.githubusercontent.com/70485838/94236730-9f415600-ff05-11ea-8fbc-26fdf025fe01.JPG)

2) The holes on the side of the model should have support material that you can drill/pull out, but it's merged with the print completely. 

![3 (3)](https://user-images.githubusercontent.com/70485838/94236691-9486c100-ff05-11ea-9c28-0cbd8f0d2734.JPG)

**Additional information**
These issues can be seen in Cura when it's sliced. 

Attached are a screenshot of the support settings I have changed from the default and the relevant log file.

![Image 007](https://user-images.githubusercontent.com/70485838/94211963-c3cc0c80-feca-11ea-85f1-e42cc24d6852.png)
[cura.log](https://github.com/Ultimaker/Cura/files/5279818/cura.log)

I have the print as an stl file and 3mf file, but your system won't accept them.

As the issue would affect everyone slicing a print that needs support, but no-one else is reporting it, I'm guessing it's just my installation. When I upgraded to 4.7, a 4.7 installation folder was created on the C drive. The previous 4.6 installation folder remained, so I deleted it. My current installation now has a 4.7 installation folder, but no 4.7.1 folder despite upgrading.

**Comment by Asterchades** [comment]
This is a setting issue, though I'm unsure whether it's a default (I suspect not) or something you changed yourself and forgot about (most likely).

In your log is the setting 'conical_overhang_enabled="True"'. Within Cura, this becomes the more human-readable "Make Overhang Printable" experimental setting. And it would appear that it's doing exactly what it's supposed to do, in that the cones its printing are automatically being angled down at 45° (your specified "Support Overhang Angle") to make it so they can print successfully.

This has nothing to do with Supports, which is why you've not seen it mentioned before. It's strictly that experimental setting, and it would have printed identically if you'd not used Supports at all. This same setting would have been affecting all prints you've been doing with overhangs greater than 45° or bridges, though it may not have been quite as noticeable as it was here..

As for the directories, minor builds don't get a new director for either program or setting. As such 4.7.1 goes into the same 4.7 directory, as would 4.7.2 if it ever came into being.

**Comment by wyekey** [comment]
Unticked the "make overhang printable" option and it slices correctly now. Thanks. Love Cura by the way.
