### ISSUE TITLE
Dual layer heights

### ISSUE THREAD

**Issue by 7ucky7uk3** [Ultimaker/Cura#8446]
**Is your feature request related to a problem? Please describe.**
When lowering the layer height from 0.2mm to 0.1mm for a higher resolution the print time doubles.

**Describe the solution you'd like**
When activating the "dual layer heights"-feature cura slices the outside wall with 50% of the set layer height. Inner walls, infill and
supports are sliced with 100% layer height. This would keep the print time low while the outside has a fine layer structure.
For example: 
- selected layer height:       *0.2mm*
- printed layer height outside wall:       *0.1mm*
- printed layer height inner walls, infill & supports:       *0.2mm*

**Describe alternatives you've considered**
haven't found any

**Affected users and/or printers**
Everybody

**Additional context**
![dual_layer_heights](https://user-images.githubusercontent.com/71878565/94257998-7c766800-ff2c-11ea-933d-7ff9a25d6304.JPG)

**Comment by konskarm** [comment]
Hi @7ucky7uk3. While this could save printing time, in practice it's not very feasible. If the entire wall has an angle, the above solution is not possible, since the wall lines of consecutive layers are not aligned on each other. Also, even if they are aligned, the nozzle can bump on the outer wall when trying to print the inner wall or vise-versa (depending on which wall is printed first). 
In general, this whole idea cannot work with our current implementation of CuraEngine, since the slicing is always planar.

**Comment by 7ucky7uk3** [comment]
Hi @konskarm, thanks for your reply. If the entire wall has an angle, which in most cases is very likely, then the slicer would just have to print 2 or more outer walls (where necessary) to adapt.
But since with the current Cura Engine makes this type of print time optimization impossible, I guess this option has to be put on hold.

**Comment by Ghostkeeper** [comment]
See also https://github.com/Ultimaker/Cura/issues/6322 for a different discussion of the same feature.
