### ISSUE TITLE
Shadow of objects is not displayed when viewed from under the platform

### ISSUE THREAD

**Issue by Zogar89** [Ultimaker/Cura#8469]
**Application version**
Cura 4.7

**Platform**
Windows 10 Nvidia Gtx 1070

**Printer**
Custom

**Reproduction steps**
1. Place object on bed
2. Move the camera to a view under the table.
The problem is most evident when the object is cut by the bed.

**Screenshot(s)**
![Cura bug 4 7](https://user-images.githubusercontent.com/11767960/94614794-1c115e80-027d-11eb-9c0f-9dcf7f0338ef.JPG)
![Cura bug 4 6](https://user-images.githubusercontent.com/11767960/94614822-27648a00-027d-11eb-86f4-8ef32e76e3ee.JPG)
**Actual results**
Shadow of objects is not displayed when viewed from under the platform.

**Expected results**
Shadow of objects is displayed when viewed from under the platform.
It is especially necessary to see if the entire model is resting on the platform or has irregularities.

**Comment by nallath** [comment]
This was intentionally changed in 4.7 since the shadow is only intended to show where the object is printed (eg; We simply didn't  know that people were "abusing" this side effect as a feature).

But I do have some good news; In order to facilitate this, we elevated this to a "real" feature and re-color the entire area that is below the build plate (this also has the advantage of being fully correct; the shadow was always drawn a bit above the build plate)

![image](https://user-images.githubusercontent.com/3922611/94693155-a916ef00-0333-11eb-93ec-8d44eeaf06c0.png)
