### ISSUE TITLE
[4.7.1] Single support dot shifting the Z offset

### ISSUE THREAD

**Issue by Liger0** [Ultimaker/Cura#8480]
**Application version**
4.7.1

**Platform**
Windows 10 x64

**Printer**
Cr10S

**Reproduction steps**
1. Tree support
2. No interface layer

**Screenshot(s)**
![dot causing wrong z distance](https://user-images.githubusercontent.com/20385116/94907022-cd8fda00-049f-11eb-92b4-00da26a037be.png)

**Actual results**
A single dot on top of the support causes the entire supports to have a wrong z distance from the model.
That dot is unexpected as the surface is flat.

**Expected results**
The dot should not be there, and the rest should be printed correctly at 1 layer of offset rather than 2.

**Project file**
[CCR10S_Dot causing wrong Z distance.zip](https://github.com/Ultimaker/Cura/files/5316985/CCR10S_Dot.causing.wrong.Z.distance.zip)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
(Extra information relevant to the issue.)

**Comment by Ghostkeeper** [comment]
I don't think that dot can cause other support to have a different distance. Z distance is computed locally, not for the entire part at once.

Because your branch distance is less than your branch diameter, the branches merge very quickly. This causes that particular branch tip to suddenly be wide enough to print, temporarily counteracting [this bug](https://github.com/Ultimaker/Cura/issues/5759). But really you are just experiencing #5759.
