### ISSUE TITLE
Make USB cable printing command text box wider

### ISSUE THREAD

**Issue by eliesand** [Ultimaker/Cura#8481]
Thanks for this great app!
Good job guys.

This is a request for improvement. I don't know where to write it to you because I think that the idea will be **pleasant to all users** and will **multiply the possibilities of the software** which is already one of the best (beginner's opinion)

### My request, if it is possible:
In the _"MONITOR" page_, there is plenty of room to put two text boxes:
1. A real real-time monitor of the information "received" (console)
2. A wide area to send orders
(A bit like in Pronterface)
3. Near the current temperature, the **current layer** printing and **Z absolute position** (I thing X&Y useless).
And, why not log into a text file in case of a problem?

This addition will allow to add many possibilities in the future : 
By ex, via (Post processing -> Modify G-Code) the possibility of sending messages to the console and the possibility of interrupting/posing at certain points, it would than be simple to send unplanned commands in progress printing.

These improvements may make of Cura the best. Next, it would be possible to add mini procedural language usable in the command zone? (Variables, IF, While, ...)

I hope this will make a small contribution to everyone.
In the hope of having been useful
Elie SAND, Brussels, Belgium (French speaking)

**Comment by Ghostkeeper** [comment]
I think a real-time monitor is not something we'd like to add since the information is generally useless to most people. Part of designing a good user experience is to hide information that is irrelevant. If you don't keep doing this, it ends up looking like a cockpit of an aeroplane. Cura is meant to slice and send over the sliced g-code, not to debug your serial port.

As for `2.`, the current layout of the USB cable printing monitor was once designed for a situation where the model was still displayed beside it. This is why the design is so slim and to the side. I would be in favour of giving the design a bit more room.

The current layer and/or Z position could be nice to show. The X/Y position is infeasible since there is a delay (up to like a minute) between when Cura sends the g-code and when the printer executes it.

However for both of these Ultimaker won't spend resources on improving the USB cable printing monitor since it has no printers any more that support the USB cable printing workflow. We'll leave this open for users of USB cable printers to solve, but we can't spend time on it ourselves.

Your issue really is 3 feature requests in one. I'll change the title to one of them to allow people to find that issue. Please create separate issues for each of them next time, so that we may track which features are still open and which aren't.
