### ISSUE TITLE
Bridging line direction

### ISSUE THREAD

**Issue by tomsutton** [Ultimaker/Cura#8485]
v4.6.7
Windows 10
FLSUN QQ-S

![image](https://user-images.githubusercontent.com/21124840/94977097-32cee400-050f-11eb-82e7-a903085db1c3.png)

When bridging, the skin first layer lines go in the wrong direction.

Quite new to this. Is it a bug? Or something I can fix in the settings.

Thanks

**Comment by Ghostkeeper** [comment]
There is no setting to determine the direction in which it bridges. That's meant to be automatically determined from the model.

If the experimental bridge settings are enabled, it chooses the bridging direction based on the longest unsupported edge. If they are disabled, it uses the older routine of taking the direction from the two farthest supporting pillars. In your case, the experimental one is probably going wrong because the long edge (parallel to your bridging lines) overhangs due to the slope of the walls there. The old routine would choose correctly then, so you can try disabling Enable Bridge Settings setting in the Experimental category.

It's hard to give more details on this. Do you have a project file that you could share so that we may reproduce the problem and maybe verify a fix or workaround?

**Comment by ZhuJo** [comment]
I have also noticed this, especially with Line width set above 0.45 mm (with 0.4 mm nozzle). It simply creates bridges that doesn't make any sense from logical point of view.

First image shows bridging at 0.45 line width. It isn't ideal like PrusaSlicer does (90 deg angle from the walls to create shortest path) but at least, somewhat usable (but not at all with PETG)
![045_line](https://user-images.githubusercontent.com/7055428/95710854-dcc21500-0c61-11eb-9197-d620a9a7e02d.jpg)

Here is the same bridge with 0.5 mm line width. That is clearly completely out of touch.
![05_line](https://user-images.githubusercontent.com/7055428/95710860-e0ee3280-0c61-11eb-87a7-99cd06fbd0c1.jpg)

**Comment by dgrat** [comment]
>If the experimental bridge settings are enabled, it chooses the bridging direction based on the longest unsupported edge.
I think this is exactly the opposite of how it should be.

**Comment by Ghostkeeper** [comment]
With "edge", I meant the edges of the polygon encircling the area that gets bridged, not the individual skin lines. This was an external contribution to Cura, but I think the idea behind selecting the longest edge is to ensure that at least the that long edge is printed optimally. In your case, it appears like the left and right sides of that model get wrongly classified as bridging in general. Perhaps that is due to the geometry of the mesh though, which is hard to see. You didn't provide any reproduction steps either (which is why this issue was closed originally).

I think the theoretical "optimal" bridging direction would be the direction that minimises the longest bridging line. This requires generating the line pattern in all possible directions though, so an approximation can be made by finding the minimum bounding rectangle (not axis-aligned) and using the direction of the short side of that. The width of the minimum bounding box is different from taking the orthogonal direction to the length of the longest bounding box.

**Comment by CombatVolcano** [comment]
Also have this problem
![image](https://github.com/user-attachments/assets/464a4a56-b439-4f96-b7c2-6aabc29983b7)
without bridging settings it is much more reasonable
![image](https://github.com/user-attachments/assets/6d65e74f-ce5b-48a0-8ecb-f2bb84e64631)
this isn't really a weird model and I don't know why bridge settings would do this
