### ISSUE TITLE
[4.8.99 master 20201002014518] No default or personal profiles, import fails

### ISSUE THREAD

**Issue by Liger0** [Ultimaker/Cura#8500]
**Application version**
4.8.99 master 20201002014518

**Platform**
Windows 10 x64

**Printer**
Cr10S

**Reproduction steps**
1. Any material
2. 0.4mm nozzle
3. Export Custom profiles from 4.6.2
4. Try to import them in master

**Screenshot(s)**
![profiles](https://user-images.githubusercontent.com/20385116/95130874-7cad0980-075d-11eb-994d-377048d81ed7.png)
![profile import](https://user-images.githubusercontent.com/20385116/95131246-052baa00-075e-11eb-8094-c7cb5c0b1499.png)

**Actual results**
No default nor custom profiles. Profiles fail to import

**Expected results**
Default and custom profiles. Additional profiles should import.

**Project file**
(For slicing bugs, provide a project which clearly shows the bug, by going to File->Save. For big files you may need to use WeTransfer or similar file sharing sites.)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
(Extra information relevant to the issue.)

**Comment by konskarm** [comment]
Hi @Liger0. We recently had a bug that caused the Creality printers to lose all of their profiles. This bug was included in this nightly build but was fixed yesterday with https://github.com/Ultimaker/Cura/commit/a73cd96e1afd7788707e9e573c2dc3f15cb54eee. If you could try running it from source, the problem should not occur anymore.
