### ISSUE TITLE
Custom profiles missing under different nozzle sizes

### ISSUE THREAD

**Issue by TKDesigns** [Ultimaker/Cura#8534]
**Application version**
(Cura 4.7.1)

**Platform**
(Windows 10)

**Printer**
(Creality CR10S Pro)

**Reproduction steps**
1. (Changed Nozzle Size)
2. (Opened Manage Profiles
![Screenshot (2)](https://user-images.githubusercontent.com/58378601/95924003-59491680-0d7c-11eb-9823-8cf083a2f314.png)
![Screenshot (1)](https://user-images.githubusercontent.com/58378601/95924012-5c440700-0d7c-11eb-890e-ad22d67096c2.png)

It seems that when a nozzle size is selected, some or all custom profiles go away, even when looking at the manage profile screen. I understand having specific profiles for a certain nozzle size, but I should at least be able to see all my profiles in the manage screen. Or have it broken down by the profiles for each nozzle size and let you cross over those profiles. Most settings will work between say a .4 and .6 nozzle. Even a .8. But There's no way to copy and paste them, or even see them at all.

**Comment by Ghostkeeper** [comment]
This is expected behaviour.

Your custom profiles are overlaid on the built-in profiles, and these built-in profiles are specific to a certain configuration of your printer (for the Creality CR-10S Pro that you have selected at least; some printers didn't configure this). If your custom profile is based on the Draft quality level and you are currently on the Normal quality, and then switch to your custom profile, it will first switch to Draft quality and then put your custom profile on top.

If you change the nozzle size such that there is no Draft quality profile any more, there is no quality profile to put underneath your custom profile. So you can't switch. You can only switch to custom profiles for which their quality level is available to your current printer configuration.
