### ISSUE TITLE
Problem between two printers

### ISSUE THREAD

**Issue by Fabdu57** [Ultimaker/Cura#8545]
Hello,

I have a problem...
Two profiles, the first created with Ender 3 pro, the second with SOVOl SV02.
Same parameters. Same values. However, support are different, and i have some problem on certain parts...

![image](https://user-images.githubusercontent.com/69864038/96146405-89bcbc00-0f06-11eb-9bd0-cabaee62b5b4.png)

Is somebody can help me, because if it continue, i will sell SV02 to take again a creality ender 3 lol.

Thanks in advance,
Fabrice

[Fichier 3mf.zip](https://github.com/Ultimaker/Cura/files/5385661/Fichier.3mf.zip)

**Comment by eskeyaar** [comment]
These doesnt have project files, so pls upload them as project files.

**Comment by Fabdu57** [comment]
on zip file you have the 3mf file.
You don't arrive to upload it ?

**Comment by eskeyaar** [comment]
yes, those are just 3mf file, it doesnt open as project file.
Save them as project not export them.

**Comment by Fabdu57** [comment]
OK sorry.
I will do it again tomorrow

**Comment by eskeyaar** [comment]
also mention what version of cura you are using.

**Comment by Fabdu57** [comment]
Version is 4.7.1
New files in attachment
[Files.zip](https://github.com/Ultimaker/Cura/files/5395229/Files.zip)

**Comment by Ghostkeeper** [comment]
> and i have some problem on certain parts...

What is the problem you're having? Is it not filling that gap? Could you fill in the issue template, specifically with what your expected behaviour is and what your actual behaviour is?

I'm getting the same result with both project files, visually:
![image](https://user-images.githubusercontent.com/2448634/96428946-a86dcc00-1200-11eb-8a08-fbe571ba4412.png)

Inspecting the g-code there are still slight differences. You say that all of the settings are the same, but there still are differences. Most importantly, the Maximum Resolution and Deviation settings are still very different which has an influence on the thicknesses of all parts and the exact coordinates of your vertices. Try setting those to be equal.
