### ISSUE TITLE
Dual Extrusion with Modified Prime Tower crashes my Printer

### ISSUE THREAD

**Issue by WeMakeThings3D** [Ultimaker/Cura#8554]
Cura 4.7.1, 4.7, 4.6.1

Windows 10, 64 bit, on an Asus G750JX ROG Laptop

Geeetech A30T (modified from A20T)

**Reproduction steps**
Set up: I printed a serpinski triangle STL Wednesday night in a single color. It came out perfect. I wanted to print it again but change to a new color mid way through and then a third color at the end. I ran a mini test print to check my blending settings and EVERYTHING WENT TO HELL.

I have narrowed down the "bug" to be in the dual extrusion tree. I put three boxes on the build plate. 12mmx12mmx.6mm side by side by side. Box one prints with EX0, Box 2 prints with EX1, Box 3 prints with EX2.

But extruder 0 bleeds into box 2, so I enable the prime tower. It goes again, making the trip back to the tower to purge between boxes, but there's not enough material purged so I still have EX0 PLA in Box 2.

HERE IS WHERE THE PROBLEM STARTS AND DOES NOT GO AWAY: I increase volume purged from 6mm^3 to 20mm^3. I know I will also have stringing, so to reduce that I crank up Retraction distance from 16 to 40 and speed from 20 to 45. Slice it, save it, stick it in the printer. Run the next test, home, prime line, home, goes to prime tower. prints the tower, prints layer 1 of box 1 with extruder 0. (HERE) it goes into an endless feedback loop where it re-runs the last 5 diagonal lines over and over, but the start point is at the last loops end point causing a shift, shifting my head and bed to the limits and GRINDS. It will sometimes start the loop in the prime tower so I will get endless semicircles until it crashes. It will sometimes just sprint toward home, crash, and grind the motor.

When I go back into the code to change the values back to default the problem persists.

The only temporary fix I can do is to make a new profile on cura and rerun the same tests where I don't touch the dual extrusion settings at all which I need to change because by default they don't work! I am starting with an A20T profile and changing the bed size, acceleration, speeds, etc.

I have uninstalled Cura 4.7.1 and reinstalled it. And still get the same issue. I have run 17 experimental prints this morning. The only thing that has worked is to download Cura 4.4, but I cannot modify the retraction speed or acceleration, and the prime tower isn't flushing all the material I need before it prints the next box.

**Actual results**
![Bad Print 2](https://user-images.githubusercontent.com/73004160/96323147-8e09d780-0fe1-11eb-8ad4-7750840a84b3.jpg)
![Bad Print Tails](https://user-images.githubusercontent.com/73004160/96323148-8ea26e00-0fe1-11eb-936d-1ce26d2dcb6b.jpg)
![Bad Print](https://user-images.githubusercontent.com/73004160/96323149-8ea26e00-0fe1-11eb-9c78-c6cc8f78bde1.jpg)

**Expected results**
![Desired Bed](https://user-images.githubusercontent.com/73004160/96323161-96621280-0fe1-11eb-9fbf-e3df4b5ed7f5.jpg)

**Project file**
I've uninstalled Cura 4.7.2 so I cannot get a saved project file at the moment

**Log file**
I'm not sure what a log file is, if someone can provide more info I will provide it.

**Additional information**
Creating a new profile resets the issue. Changing the dual extrusion specs causes it to lapse back into the bug. Reverting files back to stock keeps the bug.

**Comment by Ghostkeeper** [comment]
> I've uninstalled Cura 4.7.2 so I cannot get a saved project file at the moment

Cura 4.7.2 doesn't exist. You should still be able to make a project file using Cura 4.7.1 though, or any version that reproduces the problem.

As far as I understood, your issue basically summarises to this:
* Using the default settings you are not getting any layer shift issues.
* You change the Prime Tower Minimum Volume, Retraction Distance and Retraction speed settings, and it starts getting a layer shift because your printer seems to repeat the last few commands causing a relative movement multiple times.
* You reset these 3 settings to their defaults for your printer, and it still gets the same problem.

I tried to reproduce this as far as I could without having any profile for the Geeetech A30T and without having your printer. I used the unmodified A20T instead. However after the 3rd step, the g-code is exactly the same as the 1st step. The printer is then expected to behave the same as in the 1st step.

I have a strong suspicion that you're hitting a firmware bug, because:
* CuraEngine always outputs absolute coordinates for X, Y and Z. If it's making the zig-zaggy movement repeating the last few layers, that would mean that there would be wholly new coordinates in the g-code. If you're not seeing these zigzags in layer view then those coordinates don't exist.
* It repeats a handful of moves that happen to coincide approximately with the size of the Marlin g-code buffer, or at least that order of magnitude.
* The same g-code apparently produces different results.

We don't have access to your printer, your print profile or your printed scene. To begin to debug your issue we'll need to have at least SOME information to go by. Could you give us a project file that reproduces the problem, and also point out where in the output of Cura it goes wrong? You can indicate that with screenshots of layer view that show the issue, or snippets of g-code, and tell us what you'd like Cura to do differently?
