### ISSUE TITLE
[4.7.0] Retraction Extra Prime Amount - Only on First Layer

### ISSUE THREAD

**Issue by jleadbetter** [Ultimaker/Cura#8598]
**Application version**
4.7.0

**Platform**
Dell Precision M6800, Windows 7

**Printer**
CoreXY
Reproducible using Duet and SKR 1.4 Turbo boards
.08 Titan Volcano 
.2 Retraction

**Reproduction steps**
1.	Slice a model and enter a value for Retraction Extra Prime Amount.
2.	Save and print the gcode file.

**Actual results**
Extra Prime amount only happens on the first layer.

**Expected results**
Extra Prime to occur at the start of each layer or after a retraction and/or travel move.

**Project file**
Gcode and file screenshots are attached.

**Log file**
No Logs

**Additional information**
1.	Opened the gcode files in a text editor to investigate the issue.
2.	With how I have my printer configured in Cura, I determined that an Extra Prime value of 1 results in a file of 0.415752.  A value of 2 results in a file value of 0.831504…and so on.
3.	I can see these values at the start of the first layer, but doing the Extruder math between the end of one layer and start of the next, the Extra Prime amount seem to be missing.  The math just doesn’t work out.
4.	I have performed a similar test using Simplify3D and it prints as expected.  Examining the files shows that their version of “Extra Prime” is performed at the start of each layer.

![Extra Prime Bug](https://user-images.githubusercontent.com/2387976/96959193-0af6ee80-14c5-11eb-87e1-58bc77967ee3.png)

[Extra Prime GCode Files.zip](https://github.com/Ultimaker/Cura/files/5427447/Extra.Prime.GCode.Files.zip)

**Comment by Ghostkeeper** [comment]
You need to enable "Retract At Layer Change" for it to retract. The Retraction Extra Prime Amount will only happen when unretracting. It doesn't occur at layer changes unless Retract At Layer Change is enabled.

This seems to work fine. I've tested with a large Retraction Extra Prime Amount of 999mm³ which is about 156mm of filament, and it shows big jumps of E at every layer:

```
G1 F1500 X113.04 Y103.758 E318.73152   ;<-- Last printed move.
M204 S2812
M205 X18 Y18
G1 F1500 E312.23152                    ;<-- Retraction
;MESH:NONMESH
G0 F600 X113.04 Y103.758 Z0.47
G0 F9642.9 X120.7 Y111.7
;TIME_ELAPSED:42.622575
;LAYER:2
M106 S170
M204 S1000
M205 X10 Y10
;TYPE:WALL-INNER
;MESH:cube.stl
G1 F1500 E475.3294                     ;<-- Unretraction, includes Extra Prime Amount (+~156mm)
G1 F1800 X112.3 Y111.7 E475.3689       ;<-- Continue printing as normal.
G1 X112.3 Y103.3 E475.4084
```

Your g-code doesn't show retractions at the layer change, so I'll assume that the setting is disabled. It would be good in the future to add an actual project file to your bug report, so that we can reproduce your bug. You can save a project file in Cura via "File" -> "Save Project...". G-code files are not project files.
