### ISSUE TITLE
[4.8 beta] Slicing STL: Fillets sliced wrong

### ISSUE THREAD

**Issue by GrooverFromHolland** [Ultimaker/Cura#8613]
**Cura 4.8 beta**
**Windows 10 64 bit**
**Ender 5 Plus**

When slicing STL file, some fillets are replaced with a rectangle surface in outer wall.
Version 4.8:
![version4 8](https://user-images.githubusercontent.com/8282778/97106850-3dbb0580-16c4-11eb-8e0c-91fcd470996f.png)

Version 4.6.2:
![Version4-6-2](https://user-images.githubusercontent.com/8282778/97106863-5aefd400-16c4-11eb-9302-e020b4590f9c.png)

STL file:

[ShelfBracket20-24.zip](https://github.com/Ultimaker/Cura/files/5434687/ShelfBracket20-24.zip)

The two versions are using the same settings.
The STL is made with Fusion360 
Format: binary
Nr. of triangles: 53394
Refinement: High

**Comment by nallath** [comment]
Could you also share a project file? I think it might be related to settings that you used.

**Comment by GrooverFromHolland** [comment]
Here is the Cura 4.8 Project file:

[ShelfBracket20-24.zip](https://github.com/Ultimaker/Cura/files/5440618/ShelfBracket20-24.zip)

**Comment by Ghostkeeper** [comment]
This is a problem with your settings, particularly the Hole Horizontal Expansion setting which is set to 1mm.

Hole Horizontal Expansion makes all horizontal holes wider. There is a big hole in the middle of your model, as becomes apparent when you look at a single layer:
![image](https://user-images.githubusercontent.com/2448634/97314008-8a8b1180-1867-11eb-8a0d-7f62e26988e5.png)

Yes, I mean the big rounded triangle in the middle throughout 95% of the layer. That's a hole in the shape, so it gets expanded by 1mm.

A few layers lower however, the shape breaks into pieces due to the vertical holes on the side of the bracket:
![image](https://user-images.githubusercontent.com/2448634/97314132-aee6ee00-1867-11eb-86d8-eaf2c30bdccf.png)

Suddenly there is no more hole, just 4 rather slim parts. And thus no hole gets expanded any more. The result is a shelf of 1mm at the height where the last screw hole closes up.

**Comment by nallath** [comment]
I've also tested this with 4.6; The result is the exact same. So it's also not a regression.
