### ISSUE TITLE
[4.8 beta] Extra Skin wall missing when top surface layers is active 

### ISSUE THREAD

**Issue by printingotb** [Ultimaker/Cura#8625]
**Application version**
4.8 beta

**Platform**
Windows 7, NVIDIA GeForce GT 730. (Using dual monitors).

**Printer**
Custom fff

**Reproduction steps**
1. See attached project, 2 top surface skin layers are enabled with different pattern and line width. Extra skin wall is on.
2. Turning off top surface skin layers restores the extra skin wall.

**Screenshot(s)**
![Missing skin wall](https://user-images.githubusercontent.com/32172100/97286291-9bc22700-1843-11eb-894d-39d6194d42a5.PNG)
![Missing skin wall2](https://user-images.githubusercontent.com/32172100/97286893-37ec2e00-1844-11eb-9d34-c0b73548cdab.PNG)

**Actual results**
Skin wall missing

**Expected results**
Skin wall present

**Project file**
[Missing skin wall.zip](https://github.com/Ultimaker/Cura/files/5444405/Missing.skin.wall.zip)

**Comment by konskarm** [comment]
Indeed, it reproduces. It seems that it only happens if the top surface skin pattern is concentric. When I switch it to lines or zigzag, the skin walls appears as expected.

_Top surface skin pattern = Concentric_
![image](https://user-images.githubusercontent.com/19388042/97411248-48fa7500-1900-11eb-9d5a-1ff294436b25.png)

_Top surface skin pattern = Zig Zag_
![image](https://user-images.githubusercontent.com/19388042/97411267-4e57bf80-1900-11eb-861e-bb3c0c26d78d.png)
