### ISSUE TITLE
[4.8 beta] Infill wall lines overlaps when infill steps is active at the same time 

### ISSUE THREAD

**Issue by printingotb** [Ultimaker/Cura#8628]
**Application version**
4.8 beta

**Platform**
 Windows 7, NVIDIA GeForce GT 730. (Using dual monitors).

**Printer**
Custom fff

**Reproduction steps**
1. See attached project, enable at least 2 infill walls and  enable infill steps at the same time.

**Screenshot(s)**
![Infill wall and steps](https://user-images.githubusercontent.com/32172100/97291073-b7303080-1849-11eb-8c6d-907c8593a589.PNG)

**Actual results**
Infill walls overlaps

**Expected results**
No ovelap

**Project file**
[Infill wall and steps.zip](https://github.com/Ultimaker/Cura/files/5444680/Infill.wall.and.steps.zip)

**Comment by printingotb** [comment]
Submitted before I was done, updating...

**Comment by jellespijker** [comment]
This is occurs because the gradual infill areas don't take into account previous generated area. This is normally not a problem but once _connected lines_ are enabled or _extra infill wall counts_ are set to a number higher then 0.  It will generate an infill area with a denser density with an extra wall around it. Since these denser areas are drawn over the a previous generated infill area this will result in over extrusion. 

We were aware of this problem with _connected lines_ (Cura devs see CURA-7115) but not with _extra infill wall count_. This is fortunately also fixed in branch  [CURA-7115_gradual_infill_overextrusion](https://github.com/Ultimaker/CuraEngine/tree/CURA-7115_gradual_infill_overextrusion).
Were we only generate a wall for the least dense area 
[FffGcodeWriter.cpp#L1708](https://github.com/Ultimaker/CuraEngine/blob/d759e19df7d454032aabe8205bee594e032e39a7/src/FffGcodeWriter.cpp#L1708)
