### ISSUE TITLE
[4.8 Beta] Resize works better but still not fixed

### ISSUE THREAD

**Issue by MrEd88** [Ultimaker/Cura#8646]
**Application version**
4.8 Beta

**Platform**
Linux Mint 20 - GTX 1050Ti

**Printer**
Custom Printer - (It is an Ender3 modified for Direct Drive, BMG extruder and e3dv6 hotend clones, if it matters )

**Reproduction steps**
1. Import model and rotate
2. Resize without uniform scale
3. Rotate the same degrees to return to original position
4. Resize to 100% each axis

**Screenshot(s)**
Two cubes for comparison loaded
![image](https://user-images.githubusercontent.com/19942461/97470141-30488a00-1915-11eb-815f-4d0c9a8d5996.png)

**Actual results**
Trying to get back to original shape is not possible, there are small deformation in the shape.

**Expected results**
Model should keep proportions 

**Project file**
[Resize_test.zip](https://github.com/Ultimaker/Cura/files/5453624/Resize_test.zip)

**Log file**
[cura.log](https://github.com/Ultimaker/Cura/files/5453653/cura.log)

**Additional information**
Quick video showing the issue

https://filebin.net/e1b8z2kfywl7m50k

**Comment by jellespijker** [comment]
Thank you for filling in the bug report. At first thought I was under the impression that it was a bug. But it is correct mathematical behaviour. These sequence of transformations actually result in a shear transformation. This is because the rotational 3D matrix applied to object are not commutative and therefore are depend on the order in which they're applied.
