### ISSUE TITLE
Orientation of FLSUN QQ-S Axes

### ISSUE THREAD

**Issue by LuizPonzini** [Ultimaker/Cura#8663]
The orientation of the axes X and Y (on the table) are rotated 120º in relation of the FLSUN QQ-S Printer spectro.
Thank you.

**Comment by Ghostkeeper** [comment]
In which direction is it rotated?

Are you able to fix the [mesh](https://github.com/Ultimaker/Cura/blob/master/resources/meshes/FLSUN-QQ-S.stl) for this printer yourself?

**Comment by LuizPonzini** [comment]
Hi, thanks for your quick response.
Please see the correct orientation in the attached image.
I reduced the model for easier understanding, but the current Z position and scale are correct.
In fact, the angle difference is 135 ° (counterclockwise), not 120 ° as I said before.
Please contact me again if you want more details.
Thanks.
![FLSUN_QQ-S_CorrectOrientation](https://user-images.githubusercontent.com/73707891/97976062-dc242680-1da8-11eb-98dc-d35e77d3622c.jpg)

**Comment by Ghostkeeper** [comment]
Thanks! I've changed it for version 4.9.

**Comment by pmos69** [comment]
> Thanks! I've changed it for version 4.9.

There's an additional sub-issue related to this: the Printhead settings.
Those are still using the wrong orientation for the x/y axis.

**Comment by Ghostkeeper** [comment]
> The Printhead settings.

If the print head shape needs to be rotated, I can't really help you there. I don't have that printer so I can't measure anything. I could blindly rotate the current rectangle around its coordinate origin but chances are that I'll rotate it the wrong way around or that it's not a rectangle and I'd have no way to know.

> The views selection buttons on the main windows (ex: "Top View")

These are aligned to the g-code coordinates, not necessarily to the front of the printer. Cura doesn't know what the front of the printer is (it just displays that 3D model) so there is no way to really change this to align to an arbitrary direction. We can't begin to try to detect where the LCD display is in a 3D model or anything.

> Also, it's still off by 25º.

You are then disagreeing with @LuizPonzini. Could you come to an agreement with them?

**Comment by pmos69** [comment]
> > The Printhead settings.
> 
> If the print head shape needs to be rotated, I can't really help you there. I don't have that printer so I can't measure anything. I could blindly rotate the current rectangle around its coordinate origin but chances are that I'll rotate it the wrong way around or that it's not a rectangle and I'd have no way to know.
> 
> > The views selection buttons on the main windows (ex: "Top View")
> 
> These are aligned to the g-code coordinates, not necessarily to the front of the printer. Cura doesn't know what the front of the printer is (it just displays that 3D model) so there is no way to really change this to align to an arbitrary direction. We can't begin to try to detect where the LCD display is in a 3D model or anything.
> 
> > Also, it's still off by 25º.
> 
> You are then disagreeing with @LuizPonzini. Could you come to an agreement with them? And are you sure you've tested with version 4.9 or master? It's not been released yet.

Hi @Ghostkeeper,

Sorry for the confusion. I don't think I was clear.
I tested with Arachne engine alpha (99.0.0 I think).

Btw, I perfecly understand that you can't determine what is the "front" side of the printer

Here's the problem: With the rotation I see in Arachne the "problem" is actually worse than before.

This is an example stl in 4.8.0 in top view:
![image](https://user-images.githubusercontent.com/123733/108705108-c9269500-7504-11eb-84de-e15aa64fd947.png)

Sure, the STL is not correctly orientated because the "DOWN" side is not facing the "front" of the printer, but at least it's correctly facing one of the printer sides. And that is how it prints: That side of the printed model is parallel to the printer side because the x axis runs paralel to the printer side panel. (even if it's the wrong side).

It's anoying that it's the wrong side? Yes, but I guess it can be fixed by shifting the connections of the 3 stepper motors to get the orientation right.
I don't even know if it's a general issue or just poor quality control by the manufacturer.

In Arachne, the same model in top view looks like this:
![image](https://user-images.githubusercontent.com/123733/108712004-14917100-750e-11eb-8020-d48d723f7219.png)

It's still not facing the right printer side, but the real problem is, it's now not even paralel to the printer side in the representation.

PS: If you want to know, in my printer the "front" side is this one, but as I said, that a minor issue:
![image](https://user-images.githubusercontent.com/123733/108712932-6d153e00-750f-11eb-9b9d-c83c0e12fdfe.png)

Thanks.
