### ISSUE TITLE
configurable fx/calculated settings

### ISSUE THREAD

**Issue by chepo92** [Ultimaker/Cura#8707]
**Is your feature request related to a problem? Please describe.**
Some times I want some settings to be equal value to others, 

**Describe the solution you'd like**
Ex, using two extruders I would like stand by temp to be equal to printing temp, and every time print temp changes, the stand by also does 

**Describe alternatives you've considered**
manually setting the settings and remembering when and which to change

**Comment by konskarm** [comment]
This is a dublicate of https://github.com/ultimaker/cura/issues/3856. This used to be in our backlog for a long time, but it got archived due to inactivity. We rediscussed it today and we estimated it to be a very large change that we do not expect will be used that often. Therefore, we will defer it due to the amout of work needed to achieve the desired result.
