### ISSUE TITLE
[4.8] infill for walls seems broken

### ISSUE THREAD

**Issue by 7FM** [Ultimaker/Cura#8724]
**Application version**
4.8

**Platform**
Windows 10

**Printer**
Ender 3

**Reproduction steps**
Slice attached STL with 30% Infill and Cubic Pattern, Wall Thickness 0.2, Wall Line Count 2
(feel free to ask for more relevant profile settings, or is there an easy way of exporting?)
Edit: increasing Wall Line Count to 3 results in solid lines(without additional infill) as in Cura 4.6.2 with Wall Line Count set to 2

**Screenshot(s)**
Created Infill: 
![image](https://user-images.githubusercontent.com/41307817/98710748-5d208680-2384-11eb-8215-ed326f25d26c.png)
Same Layer but after printing infill: 
![image](https://user-images.githubusercontent.com/41307817/98710900-89d49e00-2384-11eb-972b-567d2c2a48aa.png)
Same STL & Profile sliced with Cura 4.6.2 looks better: 
![image](https://user-images.githubusercontent.com/41307817/98712124-2ba8ba80-2386-11eb-8e71-05375ba80945.png)

**Actual results**
Inner wall lines are printed with infill as well as solid in a single layer.

**Expected results**
Per layer the walls should either be printed with infill or solid per line.

**Project file**
[project_file.zip](https://github.com/Ultimaker/Cura/files/5519255/project_file.zip)

**Comment by jellespijker** [comment]
I can't reproduce it on master, I suspect it was fixed with ultimaker/curaengine#1353
![image](https://user-images.githubusercontent.com/8535734/98719801-7d564280-2390-11eb-9738-48e9b47b5947.png)

**Comment by shauneccles** [comment]
Confirming this bug in shipped 4.8.

**Comment by konskarm** [comment]
I can reproduce this. What you are seeing here is the gap filling technique overlapping with the infill. 

**Fill Gaps Between Walls: Everywhere**
![image](https://user-images.githubusercontent.com/19388042/99229067-ca517300-27ed-11eb-870a-50102c8a3d4d.png)

**Fill Gaps Between Walls: Nowhere**
![image](https://user-images.githubusercontent.com/19388042/99229106-d89f8f00-27ed-11eb-85a4-b333f96efd04.png)

This is something we also recently discovered. However, we decided we won't fix that in the current master, since it will be fixed by the new [variable-line width, wall-generating technique](https://github.com/Ultimaker/CuraEngine/pull/1210) that we have in the works.

**Comment by konskarm** [comment]
You can work around this issue for the time being by increasing the Wall Line Count by 1 and keeping the Fill Gaps Between Walls as Everywhere. Then the small gap will be filled only by the gap-fillling but not by infill. This happens because CuraEngine tries to add an extra wall to replace the infill, but the wall doesn't fit, so it is then replaced by a gap-filling (yellow) wall with smaller width.

![image](https://user-images.githubusercontent.com/19388042/99231757-53b67480-27f1-11eb-84d6-40b8f55a3343.png)

As a small preview, this is how it will look like using libArachne:
![image](https://user-images.githubusercontent.com/19388042/99231851-76488d80-27f1-11eb-9ec0-3e49f2d6c75a.png)

The middle inner wall, which cannot be as wide as the rest of the inner walls, is properly printed with an adapted line width.

**Comment by 7FM** [comment]
> As a small preview, this is how it will look like using libArachne:
image
The middle inner wall, which cannot be as wide as the rest of the inner walls, is properly printed with an adapted line width.

On the image you have increased the wall count to 3 (see circle) too which is your current suggested workaround, I hope it works with a wall count of one less as well. Else the bug would still be present.

Besides that I am not sure if the suggested workaround will always work, because increasing the wall count might cause new problem regions as previously there was enough free space that wall gab filling wasn't triggered (but is triggered with increased wall count causing the problem). If so you would have to increase the wall count as long as this problem occurs, resulting in longer prints & filament usage (if needed I might be able to create a proof of concept showing this hypothesis). Maybe setting fill gabs between walls to nowhere is a better workaround.

**Comment by konskarm** [comment]
That's true. We haven't implemented the gap-filling technique to work with libArachne yet, so the middle wall at the moment will not be filled at all. Nevertheless, it will look something like the above image, with the difference that the middle wall will be a skin wall (since infill cannot fit in there).

**Comment by Ghostkeeper** [comment]
The original issue here was fixed with Cura 4.12. And then the gap filling is entirely replaced by https://github.com/Ultimaker/CuraEngine/pull/1210 too.
