### ISSUE TITLE
Slicing issue on prime tower when support infill extruder is different than support interface extruder. 

### ISSUE THREAD

**Issue by yves1937** [Ultimaker/Cura#8760]
**Application version**
4.8

**Platform**
windonws 10

**Printer**
Geeetech A20M

**Reproduction steps**
1. Generate Support 
2. Set support infill extruder (E1) different than Support Interface extruder (E2)
3. Slice, and see slide result on the prime tower. 

**Screenshot(s)**
(Image showing the problem, perhaps before/after images.) 
![image](https://user-images.githubusercontent.com/74403346/99049927-bad8ec80-2597-11eb-82af-132e2b99598f.png)

**Actual results**
The dual extrusion prime tower second extruder (E2) is not started until the support interface is interface. This leaves some gap until the E2 starts (ie in the air). 

**Expected results**
The prime tower should be filled with E1 (ie E1+E2 area) till the support interface start then (as done) with E1 + E2.

**Project file**
(For slicing bugs, provide a project which clearly shows the bug, by going to File->Save Project. For big files you may need to use WeTransfer or similar file sharing sites. G-code files are not project files!)
[GA_Carabine_4mm.zip](https://github.com/Ultimaker/Cura/files/5535840/GA_Carabine_4mm.zip)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
(Extra information relevant to the issue.)

**Comment by rburema** [comment]
Sorry, but this is expected behaviour. The prime tower has one primary extruder that always prints (a sort of bucket), and then the others are just dumped in there whenever convenient.

There is little to no benefit from filling the prime tower up all the way, it's not a model, it's a helper structure. All it needs to do is enable priming, maybe wipe of a nozzle, not get any material or stringing over the model and not fall over.
