### ISSUE TITLE
Cura 4.8.0 stabil can not find octoprint instances

### ISSUE THREAD

**Issue by 00monter00** [Ultimaker/Cura#8764]
Thank you for making Cura ;)

**Application version**
4.8.0 stabile

**Platform**
win10 64 pro

**Printer**
ender 3 pro

**Reproduction steps**
1. update all apps also ostoprint connection to 3.5.1.7

**Screenshot(s)**
https://i.postimg.cc/m26wLZKZ/octo.jpg

**Additional information**
I have  issue now also with 4.8.0 beta but not with  4.6.1 (still i have). I'm not only one with this issue. I erase 4.7.1 and 4.8 beta with instalation of 4.8.0. Now i istalled one more time 4.8 beta and also issue exist in 4.8 beta.

**Comment by fieldOfView** [comment]
Issues with the OctoPrint plugin should be reported in the issue queue for that plugin:
https://github.com/fieldofview/cura-octoprintplugin/issues

If you report an issue there, be sure to also include what version of OctoPrint you use.
If you are running OctoPrint 1.5.0 RC1 on Python 2, see this issue for OctoPrint: https://github.com/OctoPrint/OctoPrint/issues/3813

**Comment by jellespijker** [comment]
Thank you for referring him @fieldOfView
I asked if he could report this on FB but I wasn't clear in my communication and forgot to mention that it should be reported in the octoprintplugin issue queue. 

@00monter00 I will close this issue here but thanks for taking the time to provide us developers feedback.
