### ISSUE TITLE
Copy past of models

### ISSUE THREAD

**Issue by chrisje1980** [Ultimaker/Cura#8859]
Hi Cura makers.

Is a Copy/paste option possible? 
That i can select a model and ctrl c ctrl v it :) 
That would be handy

Many thanks
greetings from the netherlands
Chris

**Comment by fieldOfView** [comment]
No, you can not use Ctrl+C/Ctrl.V, but you can use Ctrl+M/Enter.

**Comment by Ghostkeeper** [comment]
This used to be on our backlog (reported internally by myself) but it got removed from our planning as it was not deemed important enough. This was quite a while ago so maybe I'll propose it again then.

**Comment by ragingsonar** [comment]
The multiply model option isn't a replacement for a simple copy paster imo; I never like autoplacement and will place things by hand. But it's most annoying when I'm trying to do an array of parts on "Print one at a time" and I just want to copy and offset a group of parts, but can't. 
Idk if I'm missing something.

**Comment by Gravitate1** [comment]
Not sure if this was previously possible, but Cura 5.1.1 allows you to layout the parts as you wish. Then you can select all the parts, and group them (right click, "Group Models"). Then you can multiply the group, retaining the original layout.

**Comment by MariMakes** [comment]
👋 Quick update on our side. 

This is resolved in the 5.5 Beta release 🎉 , you can download the Cura version with the fix here: [https://github.com/Ultimaker/Cura/releases/tag/5.5.0-beta.1](https://github.com/Ultimaker/Cura/releases/tag/5.5.0-beta.1)
I'll close this issue since it's resolved. 

Thanks again, and please let us know if you run into any other issues 💪
