### ISSUE TITLE
Infil line distance seems to be calculating wrongly in 4.8.0

### ISSUE THREAD

**Issue by gitcnd** [Ultimaker/Cura#8865]
**Application version**
4.8.0

**Platform**
Mac

**Printer**
Anycubic Chiron

**Reproduction steps**
Infill density is 100%
Infill line width is 0.4
Infil line distance computes to 1.2
The description says line distance is a function of density and width, so, at 100%, it doesn't make sense to be 1.2

Leaving it at 1.2 looks wrong in the preview (too much gaps for 100% infil)
Manually overriding it to 0.4 looks wrong in the preview (lines all squished)
Manually selecting 0.8 *looks* right; not sure if the printing is right or wrong though.

**Screenshot(s)**
Attached

Line width is 0.4:
![Screen Shot 2020-12-02 at 12 41 56 am](https://user-images.githubusercontent.com/4301826/100755806-4aa3e500-3438-11eb-9cf5-2db138829d8e.png)

Info says distance is a function of 100% and 0.4mm:
![Screen Shot 2020-12-02 at 12 41 01 am](https://user-images.githubusercontent.com/4301826/100755855-5abbc480-3438-11eb-8cde-db9101b3cd78.png)

But result of 1.2 looks wrong:-
![Screen Shot 2020-12-02 at 12 43 50 am](https://user-images.githubusercontent.com/4301826/100755912-66a78680-3438-11eb-961e-7061eed11356.png)

manual 0.4 also looks wrong:-
![Screen Shot 2020-12-02 at 12 43 23 am](https://user-images.githubusercontent.com/4301826/100755946-6effc180-3438-11eb-86e7-ff94a2bd7e7c.png)

manual 0.8 *looks* right?
![Screen Shot 2020-12-02 at 12 44 18 am](https://user-images.githubusercontent.com/4301826/100756021-85a61880-3438-11eb-803f-29c5be618e1c.png)

**Comment by Ghostkeeper** [comment]
It's actually correct (in theory at least).

The Infill Line Distance is the distance between the centrelines of two adjacent infill lines *in the same direction*.
You are using the Triangles pattern. This prints lines in 3 different directions. Each of these sets of lines will indeed have spacing of 1.2mm and line width of 0.4mm, producing 33.3% density. But since there are 3 of these sets of lines, the total amount of extrusion adds up to 100% density.

However the lines overlap. With Triangles, there's a lot of overlap since 3 lines join together in one spot. Conversely there are also gaps besides these crossings, with an area equal to the superfluous material in the overlaps.

In theory, the amount of material of the lines sums up perfectly to 100% (bar the very sharp corners that are too thin for the infill lines to fit, which are to be filled with gap filling later). This would happen if the material would spill out perfectly from the crossing lines into the adjacent gaps. In practice, the crossings do provide sufficient backpressure that will make your filament slip in your feeder and you won't get 100% density unless printing with a perfect fluid. This is why printing at 100% density is best done with a pattern that doesn't have any crossings, such as Lines or Zigzag.

The formula for Infill Line Distance takes the pattern into account and calculates the distance differently depending on the pattern.
