### ISSUE TITLE
can not edit material options

### ISSUE THREAD

**Issue by davidbogle** [Ultimaker/Cura#8874]
**Application version**
4.8.0

**Platform**
windows 10 Nvidia gpu

**Printer**
Ultimaker 2+ extended

**Reproduction steps**
i have 2 printers, a UM 3 and a 2+ extended
when i switch to th4e 2+ i can not edit or see material options, like temperature, etc.
when i switch back the UM 3, it all shows fine

**Screenshot(s)**
(Image showing the problem, perhaps before/after images.) 
this image is from UM 3
![image](https://user-images.githubusercontent.com/75382029/100896780-9da38980-3484-11eb-9f1b-c72896192497.png)

this image is from UM 2+ (it will not expand)
![image](https://user-images.githubusercontent.com/75382029/100896884-b7dd6780-3484-11eb-812c-36729b523481.png)

**Actual results**
i can only control temps if i go into material properties and edit there not in the settings menu

**Expected results**
i should see temps and stuff (like for other printer)

**Project file**
(For slicing bugs, provide a project which clearly shows the bug, by going to File->Save Project. For big files you may need to use WeTransfer or similar file sharing sites. G-code files are not project files!)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**
(Extra information relevant to the issue.)

**Comment by Ghostkeeper** [comment]
This is expected behaviour. The settings for Material Diameter, Build Plate Temperature, Print Temperature, Flow, Retraction Distance and Retraction Speed are hidden when using the UltiGCode flavour. That g-code flavour (only used by the Ultimaker 2 family) expects those settings to be set with a material profile in the printer firmware. The temperature used for the print depends on the material that is selected in the printer, not on the g-code provided by Cura.

The original idea behind this is that the firmware knows more about the printer hardware and how they work with materials than Cura. Ultimaker has come back on this idea later and allows Cura to set the temperatures etc. again. After all they depend on the application intent and the quality level as well. Cura knows which printer is being used and can play into that, but the firmware doesn't know about the intent and quality level so it control the temperatures.

But the Ultimaker 2 family still has this weirdness, yes. The settings are correctly hidden.
