### ISSUE TITLE
Print Temperature Initial Layer

### ISSUE THREAD

**Issue by asusdk** [Ultimaker/Cura#8895]
**Application version**
4.8 (Same Bug in 4.7)

**Platform**
Windows 10 (Build 19041.630)

**Printer**
Ender 3 Pro

**Reproduction steps**
Set all Print Temperatures to 210, but Initial Layer Temp to 215
Tried the same with other Temperatures

**Screenshot(s)**
![1](https://user-images.githubusercontent.com/54312862/101377012-9c71c280-38b1-11eb-9bde-e7c8eeb244a1.JPG)
![2](https://user-images.githubusercontent.com/54312862/101377017-9d0a5900-38b1-11eb-895c-ce6044c72da1.JPG)

**Actual results**
As to see in Screenshot 2, the Actual GCode, refers to 215 Degrees for the whole Print instead of just the first Layer

**Expected results**
First Layer Temp should be 215, all following layers should have 210

**Project file**
[Biological_Warning_Sign.zip](https://github.com/Ultimaker/Cura/files/5653881/Biological_Warning_Sign.zip)

**Comment by rburema** [comment]
If I slice that project file in 4.8, I get an `M104 S210` on line number 1523 in the gcode, right before (the comment says) layer 1 starts (`;LAYER:1` on line 1548). The only other M109/M104's I can find in the code put everything back to 0 at the end of the print.

In other words: Can you tell me where the problem is?
