### ISSUE TITLE
Top/Bottom layers missing from stepped wall when wall thickness similar to step size.

### ISSUE THREAD

**Issue by curator23** [Ultimaker/Cura#8897]
**Application version**
Cura 4.8.0 (also seen in earlier versions)

**Platform**
Windows 10 x64

**Printer**
Custom (Marlin flavour)

**Reproduction steps**
1) Import a geometry with a stepped wall, where the depth of the step is 1.2mm
2) Slice with wall thickness of 0.8mm
3) Slice again with a wall thickness of 1.0mm
3) Slice again with a wall thickness of 1.2mm
(Note that the number of lines is not important, only the total thickness of all those lines)

**Screenshot(s)**
![Cura Wall Step Bug](https://user-images.githubusercontent.com/18598564/101397983-54f53180-38c5-11eb-9459-1cd74f598d62.png)
![08_L1](https://user-images.githubusercontent.com/18598564/101388101-69323200-38b7-11eb-9c5b-a3d3a49c2f6f.png)
![08_L2](https://user-images.githubusercontent.com/18598564/101388118-6e8f7c80-38b7-11eb-8e88-15bbae5a286f.png)
![10_L1](https://user-images.githubusercontent.com/18598564/101388137-72bb9a00-38b7-11eb-85cd-ccc491ab460a.png)
![10_L2](https://user-images.githubusercontent.com/18598564/101388165-7c450200-38b7-11eb-86d4-5408f5478ab3.png)
![12_L2](https://user-images.githubusercontent.com/18598564/101388188-823ae300-38b7-11eb-8e46-0f95bbf0cad3.png)

**Actual results**
When the step depth is less than the wall thickness - 0.4mm, no connecting top/bottom is added, leaving a gap in the shell.

**Expected results**
Thickness of the shell should be consistent with wall and top/bottom thickness going around the corner of the inset, without any gaps. Ideally, top/bottom lines should fill the area under the inset wall.

**Project file**
[CFFFP_Lower and Upper.zip](https://github.com/Ultimaker/Cura/files/5654522/CFFFP_Lower.and.Upper.zip)

**Log file**
Not a crash.

**Additional information**
None of the line width settings or machine/extruder nozzle settings has any effect on the point at which top/bottom layers go missing.

Edited to clarify expected outcome.

**Comment by Ghostkeeper** [comment]
You need to reduce the Skin Removal Width.

This is expected behaviour. Skin Removal Width removes any skin that is thinner than a certain width, and is by default set to about the total width of the walls. Increasing the Skin Removal Width reduces printing time with models that have sloped walls, but also increases the chance of this sort of gap occurring. See also the Settings Guide article of Skin Removal Width that gives exactly this case as an example: https://github.com/Ghostkeeper/SettingsGuide/blob/master/resources/articles/infill/skin_preshrink.md

The default of Skin Removal Width is chosen such that there should be no gap in theory. In practice, a few tenths of a millimetre of leeway would probably be a good idea I think.
