### ISSUE TITLE
Smarter Skin Edge Support

### ISSUE THREAD

**Issue by gaby64** [Ultimaker/Cura#8926]
![image](https://user-images.githubusercontent.com/2108555/101803531-9f052f80-3ade-11eb-8e9c-472b8b47733e.png)

why not make lines connect to the nearest supported structure, be it infill or a wall?

the Z in the classic calibration cube always ends up sagging at those points where there is an unsupported direction change, all it would take to solve this is to continue the lines into nearest infill or walls.

or another solution is to create the shortest straight lines (to supported points) under unsupported direction changes

![image](https://user-images.githubusercontent.com/2108555/101804637-d0322f80-3adf-11eb-8cfb-ff058f4bdbc9.png)

another quick solution would be to have an option to make the entire layer solid wherever there is skin

**Comment by Ghostkeeper** [comment]
This has the problem that you'd then interrupt the flow and get retractions in the infill, which is going to deteriorate the strength.

The idea behind Skin Edge Support is to prevent the edge of the support from sagging. If you have enough infill lines below the edge of the skin, the first few of these will still sag (just like the skin edge did) but it'll get better every layer and eventually bridge the gaps in your infill. So the primary solution to this problem would be to just make the Skin Edge Support a bit thicker.

> another quick solution would be to have an option to make the entire layer solid wherever there is skin

This is already implemented. You can set the Skin Expand Distance to 9999mm.

I think your real problem is that your infill density is so low that you're going to get a lot of sagging. One of the primary functions of infill is to support the top skin. Even if you don't need your model to be strong, you still need to support the top skin. This is the primary function for Gradual Infill. So here is my alternative suggestion:

* Quadruple your infill density.
* Set Gradual Infill Steps to 2.

As a result most of your infill will still be the low density you've chosen before, but just before the skin starts it'll double the infill density and a few layers later double it again.

I think a combination of these is sufficient to solve this problem, and will have less problems with interrupted flow than the solution you propose.
