### ISSUE TITLE
Print overlap in one at a time mode renders under the plate

### ISSUE THREAD

**Issue by billy1380** [Ultimaker/Cura#8934]
**Application version**
4.8.0
**Platform**
Mac OS X (details in screen shot)
![Screenshot 2020-12-13 at 11 55 22](https://user-images.githubusercontent.com/1329727/102011106-1da9d900-3d3a-11eb-919c-e85a35393db1.png)

**Printer**
Prusa MK3

**Reproduction steps**
- Set print one at a time mode
- Load a model
- add multiples of the model

**Screenshot(s)**
![Screenshot 2020-12-13 at 11 47 45](https://user-images.githubusercontent.com/1329727/102011150-5ea1ed80-3d3a-11eb-8c1e-af608e2c862e.png)

**Actual results**
The print overlap shadow is rendered under the plate

**Expected results**
The print overlap shadow (rectangle) renders under the plat so it is only visible when the object is moved away from the plate

**Comment by billy1380** [comment]
Seems to be a problem when the raft option is enabled. When it is disabled the shadow comes back.

![Screenshot 2020-12-13 at 12 35 15](https://user-images.githubusercontent.com/1329727/102011986-aecf7e80-3d3f-11eb-9b6a-dc901bdec914.png)

**Comment by rburema** [comment]
Thanks for the report. We've created internal ticket CURA-7930 to address this. It might be a while until we get to it (if at all) though!

**Comment by billy1380** [comment]
@rburema I understand... it is not critical.

As a workaround I switch off build plate adhesion until before I generate gcode.

**Comment by fvrmr** [comment]
We are constantly working on making Ultimaker Cura better. Our community is a big part of that by requesting new features and reporting bugs. 

To be able to focus on the most requested and needed features and bug fixes from our community and from Ultimaker, we have decided to remove this bug from our backlog. We believe we will not work on this anytime soon and will therefore defer this issue.

Since Cura is open source, you or anyone else is more than welcome to work on this issue and create a pull request yourself.
