### ISSUE TITLE
[Feature request] Material cost per object

### ISSUE THREAD

**Issue by userosos** [Ultimaker/Cura#8935]
Hi! How i need use manager materials For printing cost calculations. I set diameters and temperatures spools/materials in print settings/profile. In general, I do not understand the logic of the work. If I set a custom material, what are the implications for Print settings/Profile? I would like to be able to display different materials to estimate the cost of printing ONLY.
Also add, please, the ability to view the cost of printing a model separately, if the table there are more than one.

**Comment by userosos** [comment]
If i select an profile after it i select material (spool) Profile drop to default - fine. It is bug?

**Comment by konskarm** [comment]
If you want to add filament cost/weight information, do the following:

1. Open the Materials tab in the preferences (Ctrl+K)
2. Select the material you want (e.g. Generic PLA)
3. Press Duplicate (this will create a duplicate of the material you had selected)
4. In the duplicated material, press the "Unlink Material" button
5. Fill in the Filament Cost and Filament Weight values in your new material

![image](https://user-images.githubusercontent.com/19388042/102463054-df1e6200-404a-11eb-89ec-5c9dcc21c04e.png)

> If I set a custom material, what are the implications for Print settings/Profile?

Using the duplicated material should work exactly like using the original one you duplicated, so it shouldn't affect your print quality at all.

> I would like to be able to display different materials to estimate the cost of printing ONLY.

Once you slice, you can see the cost of each material by hovering over the information icon, down right:
![image](https://user-images.githubusercontent.com/19388042/102463707-c06c9b00-404b-11eb-8516-96e34ab15314.png)

> Also add, please, the ability to view the cost of printing a model separately, if the table there are more than one.

This is a feature request. I'll put it up for discussion.

> If i select an profile after it i select material (spool) Profile drop to default - fine. It is bug?

I don't really understand that. Can you provide detailed reproduction steps?

**Comment by konskarm** [comment]
We discussed the feature request about pre-calculating the cost of each object, and we decided to reject it, considering that it requires quite a lot of work to be done in our engine in order to achieve it. So the work needed doesn't justify the benefit of the feature itself.
As a workaround, you can see a good estimate of the cost simply by slicing the specific model alone on the buildplate.

**Note:** I renamed the feature request title so that other users can find it and refer to it if needed. In case you find another bug, please create a separate ticket for it.
