### ISSUE TITLE
[4.8.0] Gap fill overlapping with infill

### ISSUE THREAD

**Issue by jmding8** [Ultimaker/Cura#8939]
**Application version**
4.8.0

**Platform**
Windows 10

**Printer**
Prusa Research Mk3s

**Reproduction steps**
1. Slice Benchy using Prusa Research's Mk3s profile for 0.2mm+fast (not Cura's default), which has Fill Gaps Between Walls = Everywhere, two wall perimeters at 0.4mm.

**Screenshot(s)**
![image](https://user-images.githubusercontent.com/44815547/102020326-6d35d800-3d2d-11eb-83d6-5c8ee0a7496c.png)

**Actual results**
Gap fill (depicted in yellow) overlaps with infill (depicted in orange), resulting in overextrusion and bulging of the printed part and poor print quality.

**Expected results**
Gap fill should not be used where the gap between perimeters is >1 line width (i.e. where infill is used). The "checkerboard orange/yellow" area should be infill, with no gap fill occuring.

**Project file**
[BenchyBug.zip](https://github.com/Ultimaker/Cura/files/5685172/BenchyBug.zip)

**Log file**
N/A as not a GUI issue I think?

**Additional information**
None

**Comment by rburema** [comment]
While I couldn't find the ticket (or, of there was one, the other github ticket), I remember us fixing something like this recently.

Sure enough, it reproduces (somewhat, I tried it with the Prusa profile that came with Cura rather than going through the 9 step process of adding theirs) in 4.8.0, but the problem is gone in the current main branch (meaning it's fixed for the next release). 

Visual aid:
![overlap_was_fixed](https://user-images.githubusercontent.com/41987080/102323640-09a3e880-3f81-11eb-86dd-bdc9f6c67524.png)
