### ISSUE TITLE
Profile Settings not Properly Saved

### ISSUE THREAD

**Issue by CCS86** [Ultimaker/Cura#895]
Steps to reproduce:

- Select a custom settings profile (#1)
- Make changes to #1 settings
- Select a different profile (#2)
- Choose to update #1 when prompted
- Select profile #1 again

Expected: Profile reflects the updates made and saved.

Observed: Certain settings revert to hard coded values. I have observed this with bed temp and retract distance reverting to 60*C and 6.5mm. Other settings may be affected too.

**Comment by fieldOfView** [comment]
This is a known issue with Cura 2.1. It is fixed in Cura 2.2 which we are still working on.
The "hardcoded values" are taken from the material profiles here:
https://github.com/Ultimaker/Cura/tree/2.1/resources/profiles/materials
If you switch from PLA to ABS, printer temperature and material flow are also affected. No other settings are affected. If it really bothers you, you could try removing the last two lines of lines of the PLA.cfg file as a patch.

Sorry for the inconvenience.

**Comment by CCS86** [comment]
Thanks!
