### ISSUE TITLE
Short lines on wall when gradual infill

### ISSUE THREAD

**Issue by RoyBerntsenDesign** [Ultimaker/Cura#8953]
**Application version**
4.8
**Platform**
Windows 10, GTX 1070
**Printer**
Custom Corexy Printer
**Reproduction steps**
1. Selecting gradual infill
2. Slice

**Screenshot(s)**
![2020-12-16_LI](https://user-images.githubusercontent.com/32734385/102333564-e3387a00-3f8d-11eb-95d4-b6552cf39f47.jpg)

**Actual results**
Short lines being generated on the walls. These create a lot of unnecessary moves and a longer print time than needed
**Expected results**
Infill should gradually decrease and no extra lines generated on the wall
**Project file**
[Bow.zip](https://github.com/Ultimaker/Cura/files/5701864/Bow.zip)

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)

**Additional information**

**Comment by Ghostkeeper** [comment]
This is expected behaviour. It's generating higher infill density there since it's just below the top of the model. The model has a light slope there, which makes the edge of the infill area close to the top of the model. Therefore it's expected to increase the density of the infill towards the edge of the model.

I agree that the lines are in this case pretty useless. The walls by themselves will stand upright fine. There is no way to filter this out as far as I know, at the moment.
