### ISSUE TITLE
4.8.0 - Nozzle size dropdown missing - custom FDM

### ISSUE THREAD

**Issue by Anarasha** [Ultimaker/Cura#8954]
**Application version**
4.8.0

**Platform**
Windows 10, NVidia GTX 970 

**Printer**
Custom FDM 

**Reproduction steps**
1. Add custom FDM printer with all relevant information(bed size, heated bed, start and end gcode and so on) 
2. Attempt to select a nozzle size. Notice that the nozzle size dropdown isn't there 
3. Create a Creality Ender 3 printer as I used to use one of those and it had the dropdown menu. The newly created Ender 3 machine has the dropdown menu but my custom machine still does not 
4. Try to make a new custom machine, it still does not have the dropdown menu 

**Screenshot(s)**
(Image showing the problem, perhaps before/after images.) 
![billede](https://user-images.githubusercontent.com/45836295/102336794-f1889500-3f91-11eb-987a-55cfc0c117a3.png)

**Actual results**
No dropdown menu exists for nozzle size on a custom printer 

**Expected results**
I expected to have a dropdown menu for nozzle size, or at least be able to make one for my custom profile 

**Log file**
(See https://github.com/Ultimaker/Cura#logging-issues to find the log file to upload, or copy a relevant snippet from it.)
Not sure it's relevant, but here is the log file 
[cura.log](https://github.com/Ultimaker/Cura/files/5701982/cura.log)

**Additional information**
I did search the issues on here, and I didn't find one exactly like this one. I found some with empty nozzle size dropdowns but nothing relating to a completely missing dropdown. Apologies if it exists and I simply missed it

**Comment by Ghostkeeper** [comment]
This is behaving as expected.

There are no nozzle profiles for the Custom FFF Printer at all. It wouldn't really make sense since there are no pre-made nozzles to select from. Custom FFF Printer in general is not expected to change anything away from the defaults, so the only thing that these profiles would be allowed to change is the nozzle size. Having a select set of profiles for only the nozzle size would only limit the user to a pre-set selection of nozzles, but this printer in particular is meant to provide workable compatibility for any FFF printer.

Instead, you're expected to simply change the nozzle size in the printer settings dialogue.
![image](https://user-images.githubusercontent.com/2448634/102890098-25fdc480-445c-11eb-951c-21a20b2cbbce.png)
