### ISSUE TITLE
[4.8.0] Skip walls while slice

### ISSUE THREAD

**Issue by axispod** [Ultimaker/Cura#8960]
**Application version**
Cura 4.8.0

**Platform**
Windows 10

**Printer**
Flyingbear Ghost 5

**Reproduction steps**
1. Make a model with wall's width 1.2mm
2. Slice it, nozzle width is 0.4mm

**Screenshot(s)**
(Image showing the problem, perhaps before/after images.) 
![image](https://user-images.githubusercontent.com/5475640/102491204-b1a8d700-4091-11eb-9803-1aa4a30f2055.png)

**Actual results**
It makes only two walls instead of three ones

**Expected results**
It makes three walls

**Project file**
[FBG5_box1.zip](https://github.com/Ultimaker/Cura/files/5709613/FBG5_box1.zip)

**Comment by rburema** [comment]
Due to the way (all the supported) meshes are made up of triangular polygons, a model with, for example, ''exactly'' 1.2mm wall widths, doesn't usually really have those widths due to small rounding errors.

If you make the wall widths of the model a tiny, tiny bit larger or the extrusion width a tiny, tiny bit smaller it will give you 3 walls in your case.

Incidentally, this will be fixed once we finally merge 'Adaptive Line Width' into the engine, slated for somewhere within the next 2 version updates. (See https://github.com/Ultimaker/CuraEngine/pull/1210 )
