### ISSUE TITLE
Add Longer3d machine

### ISSUE THREAD

**Issue by Kim-Fu** [Ultimaker/Cura#9035]
**Is your feature request related to a problem? Please describe.**
(A clear and concise description of what the problem is. Ex. I'm always frustrated when [...])
#Longer machine is aimed at beginners. It is very inconvenient for users to use the software, spend too much time, and may not be able to set proper printing parameters in the end.

**Describe the solution you'd like**
(A clear and concise description of what you want to happen. If possible, describe why you think this is a good solution.)
#Please add Longer LK1, LK4, LK4 Pro, Cube2 models.

**Describe alternatives you've considered**
(A clear and concise description of any alternative solutions or features you've considered. Again, if possible, think about why these alternatives are not working out.)

**Affected users and/or printers**
(Who do you think will benefit from this? Is everyone going to benefit from these changes? Or specific kinds of users?)
#Incomplete statistics, 6,400 users, nearly 50,000 devices

**Additional context**
(Add any other context or screenshots about the feature request here.)
#If you can add Longer machines, what information do you need?

**Comment by Ghostkeeper** [comment]
We can't create profiles for a printer without actually testing profiles on that printer. There is no point in having optimised profiles for the printer if we can't test which settings work best on the printer.
We're not going to test on the Longer3D printers because we don't have this printer ourselves, and because we don't have the time and resources to test all 3D printer models out there. Ultimaker has a team of engineers that optimise print profiles for all sorts of materials, configurations and applications. But it only has an incentive to do that for their own printers.

Other manufacturers or their users may supply us with profiles and we'll gladly add them to Cura to make 3D printing easier for the world at large, and to draw them in to use Cura (and through that perhaps other Ultimaker products too). The development team can't do it, but we accept profiles through [pull requests](https://github.com/Ultimaker/Cura/pulls).
