### ISSUE TITLE
4.8.0 Support in the air

### ISSUE THREAD

**Issue by Marek3d** [Ultimaker/Cura#9050]
**Application version**
4.8.0

**Platform**
Win10

**Printer**
Ender [3]

**Reproduction steps**
Slicing an object with supports generates supports suspended in the air. Visible in the attached screenshot, (I marked one in yellow)

**Screenshot(s)**
![Zrzut ekranu 2020-12-31 195910](https://user-images.githubusercontent.com/60315406/103422829-a41c4280-4ba3-11eb-861c-d35d6188082b.jpg)

**Actual results**
generates supports in the air

**Expected results**
no supports in this place...

**Project file**
[CE3_support_on_air.zip](https://github.com/Ultimaker/Cura/files/5758099/CE3_support_on_air.zip)

**Log file**
n/d

**Additional information**
n/d

**Comment by Ghostkeeper** [comment]
This is expected behaviour.

The problem is that the ring of support is too thin to print. The piece of support is smaller than a single line width. You have an extra support wall and use zig-zag, which both provide an outline that needs to keep 1/2 line width distance from the edge of the support area. If the support is less than 1 line width, this 1/2 line width inset removes the entire ring. The support interface is the same width, but since that doesn't have an outline of any kind, the nozzle path doesn't need to keep 1/2 line width distance from the edge and thus it can still produce those tiny lines.

There are two ways out of this:
* Have the support interface print with similar settings to the normal support. Good advice in any case, but in this case it's more prominent. Setting the Support Interface Pattern to zigzag removes the tiny (useless) lines of support interface. Or removing the extra wall and setting the normal support pattern to grid allows it to print the support infill.
* Use a bit of Support Horizontal Expansion to make the support wider such that it can always be printed. 1 line width (0.4mm) is the safest, always expanding to more than 1 line width even if constrained on one side. In your case 0.21mm is enough since it can expand almost completely to both sides. This is how the problem is tackled in Ultimaker's profiles.
