### ISSUE TITLE
Allow differing settings for dual extruders

### ISSUE THREAD

**Issue by ArtZL** [Ultimaker/Cura#9059]
**Is your feature request related to a problem? Please describe.**

My printer has two extruders, and my project wants to use two different types of filaments with different colors.  The first ~20 layers would use extruder #1 and the rest of the print would use extruder #2.  For this particular project, I'm printing a flat sheet with writing on top of it.  The writing requires a different layer height and speed than the flat sheet.

One problem is that the infill and shell are required to use the same extruder for ALL layers.  If I want the bottom half to be white and the top half to be red...  the colors will be mixed.  Another problem is that the layer height and the infill speed are tied together for ALL layers, regardless of which extruder is printing.

**Describe the solution you'd like**

I would like to be able to specify separate parameters for each extruder (except support, adhesion, and prime tower).

**Describe alternatives you've considered**

It might be possible to manually edit the gcode to give me what I want, but every time I edit the print and re-slice, I'd have to find the location and edit the gcode again - a time-consuming process that can introduce errors.

**Affected users and/or printers**

I believe everyone who uses a second extruder for anything other than supports would be thrilled with removing the required ties between the two extruders.

**Additional context**

There easily could be situations where shifting back and forth between filaments creates some ill-defined choices for the shell and infill.  But it would be up to the user to understand when this would cause a problem and when it would be ok to take advantage of differing parameter values.

Thank you for your considerations.

**Comment by Ghostkeeper** [comment]
You can use different infill speeds for different extruders. Here I have two objects printed with different extruders. I've set each extruder to have a different Infill Speed (70 vs 150):
![image](https://user-images.githubusercontent.com/2448634/104209883-861bd100-5432-11eb-8209-bff8ddb678f5.png)

Not all settings can be different between extruders. All of the settings with the chain link icon (![image](https://user-images.githubusercontent.com/2448634/104210067-b95e6000-5432-11eb-83c8-20a81c19f89c.png)) are global. Layer height is one of them. The reason for Layer Height is technical. It's difficult to prevent collisions with parts on other layers, especially since those other layers are generated asynchronously. Other settings have different reasons to be global settings, sometimes very obvious (Build Plate Temperature, Print Sequence, etc).

Cura can absolutely use different extruders for infill from a certain layer onwards. Only Cura doesn't do per-layer settings. Instead Cura has infill meshes and cutting meshes. These are more powerful than only being able to change settings for the whole layer. They are also less into the 3D printing details (layers) and more towards volumetric design; the 3D model used for the infill mesh is precisely the communication towards Cura as to the volume that should be filled with the other extruder.

I'll close this feature request, since it's already 99% implemented. For the feature request to make the Layer Height per-extruder, see https://github.com/Ultimaker/Cura/issues/3193.
