### ISSUE TITLE
[Help need solution] PROPORTIONNAL LINEAR ADVANCE (Outlines in 0.1mm + infills in 0.4mm = INFILLS bad printed cause linear advance not adapted for 0.4)

### ISSUE THREAD

**Issue by studiodyne** [Ultimaker/Cura#9136]
Linear advance  NEED to be variable
If printing  ' OUTLINES' in 0.1mm , and INFILLS in 0.4mm , ' Cura Option to reduce print time '
Then we have a big problem !
Linear advance is set for 0.1mm , BUT NOT FOR 0.4
Results:
Outlines with 0.1 height are perfect
INFILLS in 0.4  DON'T OVERLAP ' because of the linear advance that reduce the extrusion ' , infills are down

How to solve ?   
Someone here knows Cura and can make this feature add a M900 Gcode command  with the dedicated value for each height'
Someone here can add a Gcode comment to write the ' current actual layer height ' and I will create a pull request on MARLIN to make ' PROPORTIONAL LINEAR ADVANCE

Now it's impossible to make it only in firmware because , the machine doesn't know what is the actuel current height to apply the right linear advance. Only the slicer knows that!

You have created ' Combined Infills ' but forgotten to add ' VARIABLE LINEAR ADVANCE '

Thks

**Comment by fvrmr** [comment]
Can you share your project file? And maybe add some screenshots to clarify this more. 

It helps for us to fill in the form so precise as possible, so we can reproduce and find a solution faster.

**Comment by studiodyne** [comment]
I have remade the topic

**Comment by Ghostkeeper** [comment]
Linear advance doesn't care about line height or line width, only flow rate, right? If it needs to grow to triple the flow rate, it'll provide overpressure during that grow. But that doesn't need to depend on whether it's printing 0.4mm wide lines at 0.3mm layer height, or 1.2mm wide lines at 0.1mm layer height. The result is the same.

> Linear advance is set for 0.1mm

Provably untrue. Linear advance is not in Cura at all at the moment. I think you intended to make a feature request to implement Linear Advance and then a specific variant of it. But if you just want to add an `M900` command to your starting g-code, I think you should just add it there rather than ask us to do it for you. The start g-code field is there specifically to write down all the random stuff your printer needs to properly configure and ready itself before printing. `M900` is a pretty good example of stuff that the start g-code is intended to do.

If you want to change the default start g-code for your current printer, you can. But the developers can't test those things for you, since we don't have your printer unless you have an Ultimaker printer. So we require you to then make those changes yourself, test them, and then create a pull request to merge the correct changes into the default profiles in Cura.
