### ISSUE TITLE
[4.8.0] On macOS Big Sur (11.1) it is not possible to select Models

### ISSUE THREAD

**Issue by Ababuy78** [Ultimaker/Cura#9204]
Application version
4.8.0

Platform
macOS Big Sur (11.1)
Radeon Pro 575X 4 GB

Printer
Indifferent

Reproduction steps

1. Drag and drop a model from Finder to Cura 4.8.0
2. Model cannot be selected or modified

**Comment by fvrmr** [comment]
Hi @Ababuy78 
This is a known issue. With a recent update of the Big Sur OS, and on the new Macbooks containing the M1 processing chips there are Apple has introduced incompatibilities between the OpenGL libraries used, and the latest firmware used by the Macbook.

This means that Ultimaker Cura is currently not supported on new Macbooks containing the M1 chip. Please bear with us while we look into fixing this in an upcoming Ultimaker Cura version.

You can find the original issue here: #8745 
That why I will close this, because it is a duplicate.
