### ISSUE TITLE
Connect enhancement for USB printer

### ISSUE THREAD

**Issue by rgb55** [Ultimaker/Cura#9211]
Hello, this could be a nice enhancement for USB printer.

Whit USB connected printer this take very long to reconnect the printer if Cura is open and the printer vas turned of to avoid printer fan noise and then turned on again.
A good idea would be to have a connect button to reconnect easily the printer without restarting Cura or wait for a long time that the printer is connected back to Cura.

Regards,
Roland

**Comment by fvrmr** [comment]
Hi @rgb55 thank you for your feature request. 
USB connection is not a focus of Ultimaker, because Ultimaker printers uses network connection. That's why we won't look into this and why I will defer this issue. 
But a pull request is always welcome, so you and other users that have USB connection can use it.

**Comment by rgb55** [comment]
Thanks for your feeback,

 

Roland

**Comment by Ghostkeeper** [comment]
A manual connect option is being discussed in this feature request: https://github.com/Ultimaker/Cura/issues/5207
