### ISSUE TITLE
Bridging settings affect overhangs(not bridges)

### ISSUE THREAD

**Issue by Julius971** [Ultimaker/Cura#9224]
**Application version**
4.8

**Platform**
Win 10
specs irrelevant

**Printer**
Ender 5 Pro (customized)

**Reproduction steps**
1. load an overhang testprint
2. enable bridge settings

**Actual results**
If the overhanging parts lines are shorter then the minimum setting for bridges. The overhangs are treated as bridges, not overhangs.

**Expected results**
The bridging settings shouldnt affect overhangs.

**Comment by fvrmr** [comment]
Hi @Julius971 could you share a project file? Because I am not sure if I understand what is happening.

**Comment by Ghostkeeper** [comment]
I'm unable to reproduce this. Here I have a model of a sheared cube which has a rather steep overhang, steep enough for the entire outer wall to hang in the air.
![image](https://user-images.githubusercontent.com/2448634/107350158-5d3a3a80-6ac9-11eb-97dc-e8f94836879f.png)

Regardless of whether lines are shorter than the Minimum Bridge Wall Length or longer, it's not using the bridging routine for these overhangs. It would print those walls at 50% flow then, and it's not doing that.

A project file would allow us to reproduce your case, so that we can see what's going on.

**Comment by Julius971** [comment]
![grafik](https://user-images.githubusercontent.com/27428991/107395185-e028b880-6afc-11eb-8238-f77ce57caa4e.png) - bridging settings enabled


![grafik](https://user-images.githubusercontent.com/27428991/107395277-f33b8880-6afc-11eb-92db-8c717cea9701.png) - bridging settings disabled

**Comment by Ghostkeeper** [comment]
Nice pictures!

**Comment by Julius971** [comment]
Oh damn missed that. Will do👍🏻
