### ISSUE TITLE
Cura turning off extruder halfway a print

### ISSUE THREAD

**Issue by martijnschouten** [Ultimaker/Cura#9268]
**Application version**
Cura 4.8.0 and 4.7.1

**Platform**
Windows 10

**Printer**
Diabase H-series

**Reproduction steps**
1. Make a 3 material print, using extruder 3,4 and 5
2. Click slice
3. Check the code that was produced using notepad++

**Screenshot(s)**
![image](https://user-images.githubusercontent.com/6079002/107693369-57517e80-6cae-11eb-9f21-b9a282d58caa.png)

**Actual results**
There is a M104 T1 S0 at line 2769 cooling down the S0 nozzle in mid-print. Resulting in extra print time.

**Expected results**
M104 T1 S215 at line 2781 Cooling down the printhead to the standby temperature

**Project file**
(For slicing bugs, provide a project which clearly shows the bug, by going to File->Save Project. For big files you may need to use WeTransfer or similar file sharing sites. G-code files are not project files!)
[source files and log.zip](https://github.com/Ultimaker/Cura/files/5968301/source.files.and.log.zip).

**Log file**
See zip above.

**Additional information**
Disabling the first 2 extruders does not stop the slicer from printing with the first nozzle

(#8213), but does solve the issue.
Seemed to be slightly related to #4355, but the solution provided did not solve this issue

**Comment by fvrmr** [comment]
Hi @martijnschouten thank you.

I looked into your files, but I couldn't find the line 2781 with M104 T1 S0. 

But I think what is happening is that the first extruder is used for the `build plate adhesion` and after it is used it will turn off, because it doesn't have to print anymore.
The reason why it is not going on the standby temperature is because this could cause oozing. 

When I disable the first 2 extruders in Cura I can't select them for printing in the printer settings. So `build plate adhesion` goes automatically to extruder 3. 

I don't know if your printer has the option to use shared heater, that could be a solution for the stand by temperature. You can find more about the shared heater here: #8148 

Please let me know if that could be a solution.

**Comment by martijnschouten** [comment]
Hi, thank you very for looking at the gcode, and i'm really sorry the lines weren't there, very sloppy. I changed to cura 4.8 to check if it happened there as well, which didn't have the post-processing script for the diabase (which renames T0 to T1). It is now M104 T0 S0 at line 2649.

The thing is that extruder 0 should not stop extrudering after the first layer, because the extruder is still used in the prime pillar.
![image](https://user-images.githubusercontent.com/6079002/107782373-473aad00-6d49-11eb-82d5-da71bab3a0fa.png)

I checked just changing the build plate adhesion extruder to extruder 3 also solves the issue, so it seems to be something that only happens if there is an not disabled extruder which is not used for any other parts but is used as the build plate extruder and is used for the prime pillar.

My printer does not have the option for a shared heater.

**Comment by Ghostkeeper** [comment]
When running this through an engine compiled in debug mode, you get an assertion failure because one of the extruder plans is created but empty. This is also reflected in the warnings it gives when running in release mode:

```
2021-02-19 13:06:54,114 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [110]: [Backend] [WARNING] Warning: Couldn't find previous extruder plan so as to set the standby temperature. Inserting temp command in earliest available layer.
2021-02-19 13:06:54,115 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [110]: [Backend] [WARNING] Empty extruder plan detected! Discarding extrusion temperature command.
2021-02-19 13:06:54,115 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [110]: [Backend] [WARNING] Warning: Couldn't find previous extruder plan so as to set the standby temperature. Inserting temp command in earliest available layer.
2021-02-19 13:06:54,115 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [110]: [Backend] [WARNING] Empty extruder plan detected! Discarding extrusion temperature command.
2021-02-19 13:06:54,115 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [110]: [Backend] [WARNING] Warning: Couldn't find previous extruder plan so as to set the standby temperature. Inserting temp command in earliest available layer.
2021-02-19 13:06:54,115 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [110]: [Backend] [WARNING] Empty extruder plan detected! Discarding extrusion temperature command.
```

Looking a bit further into the result, searching through the g-code for `T\d`, we find the following sequence:

* The start of the print heats up all nozzles including T0 and starts printing with T0.
* After printing the prime tower, Cura switches to T2 and sets the temperature of T0 to 0.
* In the second layer, T0 gets preheated to 225 degrees. A short while later it switches to T0 again to print the prime tower shell.
* From there on T0 gets switched between 215 degrees (stand-by temperature) and 225 degrees a few times, and cooled down at the end of the print to 0.

So the problem is that at the end of its extruder plan in the first layer, it cools down to 0 rather than the stand-by temperature. In all of the other layers it's working fine. The extruder should be heated for the printing itself (there is an `M109` command).

CuraEngine predicts whether an extruder gets used in a particular layer by looking at whether they are used for support, adhesion, infill, etc. and then looking at whether an area exists for that structure on a particular layer. Sometimes this is problematic if the area exists but is thinner than a line width, but that doesn't seem to be the case here. Perhaps it's just as simple as that we forgot to take the prime tower outer shell into account when testing whether an extruder gets used.

**Comment by fvrmr** [comment]
Hi @martijnschouten we have discussed your issue with the team. 
But we have to defer this issue, because it is not our priority list right now. Most of our users have maximum 2 print cores instead of 5 print cores what you have. 
Hope you understand. If you have more question feel free to reach out.
