### ISSUE TITLE
[4.8] With 1 or 2 Perimeters and 0 infill, Errant Travel Move

### ISSUE THREAD

**Issue by CCS86** [Ultimaker/Cura#9339]
4.8.0 / Win 10 x64

When making a print with 1 or 2 perimeter walls and 0% infill, Cura is inserting a small travel move inwards. With 3 walls, the behavior stops:

![image](https://user-images.githubusercontent.com/12439543/109374937-83f4c100-787e-11eb-9218-db707f9d3ee0.png)

![image](https://user-images.githubusercontent.com/12439543/109374940-88b97500-787e-11eb-8a05-009ae764b65c.png)

![image](https://user-images.githubusercontent.com/12439543/109374942-8d7e2900-787e-11eb-8cdb-a45286db6568.png)

.
.
.

[Coast-bug2.3mf.txt](https://github.com/Ultimaker/Cura/files/6063792/Coast-bug2.3mf.txt)

**Comment by Asterchades** [comment]
Dark blue is a travel without retraction. I would be suspecting that's an Outer Wall Wipe, which would appear to be set to a (in my opinion excessive) level roughly equal to twice the wall width.

The behaviour also isn't stopping with three walls. It's just not moving far enough to cross over the full width of the wall, but it's quite clearly still performing the same movement.

**Comment by CCS86** [comment]
The alternate theory sounds correct. Since outer wall wipe distance was set to zero. 

Here is the behavior with a 1mm wipe which pushes the position of this inwards dive:
![image](https://user-images.githubusercontent.com/12439543/109388560-86cad280-78cd-11eb-9757-942f19d89bf2.png)
![image](https://user-images.githubusercontent.com/12439543/109388564-8c281d00-78cd-11eb-9232-9adbcd6ee116.png)
![image](https://user-images.githubusercontent.com/12439543/109388574-921dfe00-78cd-11eb-9eea-fd0123580296.png)

**Comment by CCS86** [comment]
Finally found a setting that changes the behavior: combing mode

Off: 
![image](https://user-images.githubusercontent.com/12439543/109393594-547a9e80-78e8-11eb-9ef2-92471b394f41.png)

All: 
![image](https://user-images.githubusercontent.com/12439543/109393607-5e040680-78e8-11eb-9674-ab7629ed7cfa.png)

Not in Skin: 
![image](https://user-images.githubusercontent.com/12439543/109393616-665c4180-78e8-11eb-999d-fe4316a80a48.png)

Within infill: 
![image](https://user-images.githubusercontent.com/12439543/109393624-6f4d1300-78e8-11eb-865d-e020713d1f50.png)

**Comment by Asterchades** [comment]
Ah, combing! Would never have even guessed that it could be at fault here, so nicely deduced.

If I'm honest, I've had it turned off for a long time now. PETG in particular (which I almost exclusively print these days) shows noticeable quality loss with it in use - and situations like this could be part of why. But that's starting to get off topic, so I'll leave it there and hope that the devs can get you sorted.

**Comment by CCS86** [comment]
I tried a LOT of settings before that! 

I have gone back and forth on combing. With PLA, using combing can have a pretty dramatic reduction in retracted moves, which on a bowden printer can save you a bunch of time and improve quality. 

Hopefully, the devs can dig in and see why combing is adding these moves. Maybe it will lead to a quality increase when using combing. But, this might just be an edge case, with empty infill.

**Comment by fvrmr** [comment]
Hi @CCS86 could you share your project file? 
So I can see what is happening. Cause I can't see it with your file, because the settings are missing.

**Comment by CCS86** [comment]
> Hi @CCS86 could you share your project file?
> So I can see what is happening. Cause I can't see it with your file, because the settings are missing.


It's at the bottom of the original post.

**Comment by fvrmr** [comment]
> It's at the bottom of the original post.

Yeah, I downloaded that file. But it was just a 3mf file, because dragging it into Cura this didn't pop up and it should do that with a project file. 
![Screenshot (96)](https://user-images.githubusercontent.com/77000924/109529394-fac7cf00-7ab5-11eb-98f1-07d3a7434707.png)

Actual result:
![Screenshot (98)](https://user-images.githubusercontent.com/77000924/109529758-509c7700-7ab6-11eb-8e52-a14ee2c40050.png)

So in this I use my printer and settings. And with a project I have your printer and settings, so it is easier to reproduce.

**Comment by CCS86** [comment]
[Coast-bug2.3mf.txt](https://github.com/Ultimaker/Cura/files/6063792/Coast-bug2.3mf.txt)

**Comment by fvrmr** [comment]
Thanks, I understand and see what is happening. 
It doesn't matter how many wall lines you have it will always move to the 3rd wall/ 2d inner wall.

I will discuss it with the team. Keep you posted.

**Comment by Ghostkeeper** [comment]
To summarise what we've discussed with the Cura team:

* To Cura, 0% infill is still the inside of the model. It doesn't know that for your intent the inside of your walls also need to be pretty.
* It seems to move the nozzle away from the outer wall to prepare for a retraction, perhaps for the layer change. This is allowed to go towards the inside, after all, retracting while on the outer wall is bad. You're better off moving inside. So this would be expected behaviour and not a bug.
* We realise the desire that the inside of the model might need to be made pretty as well, but that's not considered to be worth the development time or the added complexity to the interface or settings.

Loading the project file into Cura myself though I see that it's slightly different. What's happening is that it's travelling to the starting position of the next layer. This travel move is a combing move and happens to be almost to the same spot. Because the combing strategy tries to avoid being on the outer wall at all cost, and being on the first inner wall secondarily, it moves away from the 2 outermost walls here first, then goes as close as it can to its destination, then travels back onto the outer wall to continue printing there.

I think in a perfect world it would see that the path to the destination is shorter than the path away from the outer wall and then make a shortcut to the destination without combing, as the lesser of two evils.

But I also agree with the Cura team that this case is not going to need the priority from us now due to the low impact, so we'll still have to defer it. We can reconsider if it turns out to be very easy to fix or if it turns out to have a bigger impact.
