### ISSUE TITLE
[4.8] Skin Removal Width rounding issue

### ISSUE THREAD

**Issue by Timocop** [Ultimaker/Cura#9385]
### Application Version

4.8.0

### Platform

Windows 10 x64

### Printer

Custom FFF Printer

### Reproduction steps

1) Select "Normal" preset
2) Import CaliCat
3) No skin created at paws and face.

### Actual results

Does not create skin on small skin volumes.

### Expected results

Should create skin at those regions doesnt matter how small the volume is.

[calicat.zip](https://github.com/Ultimaker/Cura/files/6122731/calicat.zip)

Does not create skin at regions when setting is on default.
![2021-03-11_12-46-06](https://user-images.githubusercontent.com/22834512/110783151-576e7b00-8268-11eb-888e-41ffba8a71e2.png)

When the value is slightly lower, it will generate skin in those areas.
![2021-03-11_12-46-54](https://user-images.githubusercontent.com/22834512/110783202-6a814b00-8268-11eb-89e0-f63bb5dc9ad5.png)

**Comment by fvrmr** [comment]
Hi @Timocop thank you for your report.
Could you add a project file? (file - save project) 
That helps me reproduce this issue. Thank you in advance.

**Comment by Timocop** [comment]
This happens on a default profile preset. But here:

[calicat.zip](https://github.com/Ultimaker/Cura/files/6131861/calicat.zip)

**Comment by fvrmr** [comment]
Hi @Timocop this is fixed by our Arachne engine.
Please check that out here: https://github.com/Ultimaker/Cura/releases/tag/Arachne_engine_beta

![Screenshot (118)](https://user-images.githubusercontent.com/77000924/111799695-8b324c00-88cb-11eb-835f-e9f6f2b340fa.png)

Let me know if this works for you to and feel free to reach out for more questions.

**Comment by Timocop** [comment]
Yes this works very well.
