### ISSUE TITLE
Save Active Post Processing Scripts to Custom Print Profiles

### ISSUE THREAD

**Issue by Motovader72** [Ultimaker/Cura#9392]
### Is your feature request related to a problem?

When I'm working in a certain machine environment and have added post processing scripts,
they remain in each machine environment no matter which print profile I choose.
I have to delete or alter the scripts per print.

### Describe the solution you'd like

Can the post processing scripts be saved to specific custom created print profiles?
Example:
I have a two color print that requires a Filament Change script. I have the print profile
customized for such prints and would like to be able to grab that print profile without
having to add the post processing scripts again. Say: PLA, 0.2 layer height, 50mm/s, 
200c nozzle, 60c bed temp, Filament Change @ layer 10. 

### Describe alternatives you've considered

At this time the only workaround seems to be creating multiple machine environments for the same machine. 

### Affected users and/or printers

I think it would be hugely beneficial for the scripts to be saved in custom print profiles rather
than the machine environment. 

![sfds](https://user-images.githubusercontent.com/69872960/110995349-d7b3df80-833f-11eb-8f1f-9c2b0834c57f.JPG)

**Comment by fvrmr** [comment]
Hi @Motovader72 thank you for your feature request. 
As you already noticed the post processing scripts are saved on printers the reason why is because the most post processing scripts are for printers or for prints and not for print profiles. It would be complex to save them for both, or change it to profiles.
An other work a round is saving it as a project file, project files also contains your settings and post processing scripts. 

Please let me know if that could work for you.
