### ISSUE TITLE
Problem with Shell initial layer horizontal expansion applying to supports

### ISSUE THREAD

**Issue by cmgreyhounds** [Ultimaker/Cura#9398]
### Application Version

4.8.0

### Platform

Windows 8

### Printer

Ender 3

### Reproduction steps

Entered a Shell initial layer horizontal expansion of -0.3mm, then added supports to a model with overhangs.

### Actual results

With an initial layer horizontal expansion of -0.3mm entered in Shell, it appears that the bottom footprint of the supports expanded toward the part. The part itself did contract -0.3mm but with the first layer of the supports extending out it causes them to tend to stick to the parts (dependent on the X-Y support distance). 

### Expected results

I expected the bottom of the supports to either be unaffected by Shell horizontal expansion, or to behave in the same way as the parts do, which in this case would be to reduce the OD of the first layer.

I can't attach a project file as Cura crashes if I try to save a project. This started with the install of 4.8.

But here is a screenshot of the model with initial layer horizontal expansion of -0.3, you can see the part on the right is undercut on the first layer as expected, but the support on the left appears to be expanded by the same amount. 

![horiz exp1](https://user-images.githubusercontent.com/55936405/111054843-80903680-8435-11eb-8240-049d5556db9e.JPG)

And then after setting Shell initial layer horizontal expansion to 0.0 and no other changes, they are as expected with no initial layer expansion.

![horiz exp 2](https://user-images.githubusercontent.com/55936405/111054844-8423bd80-8435-11eb-9c2f-5de77e5053c5.JPG)

**Comment by fvrmr** [comment]
Hi @cmgreyhounds thank you for your report. 

This is expected behaviour of Cura, but desired behaviour is another question. This is because with horizontal expansion we change the model. 

You could try to change the `xy distance` so the material doesn't stick to each other. Or you can use `conical support`. 

> I can't attach a project file as Cura crashes if I try to save a project. This started with the install of 4.8.

That's weird, if you want I could take a look at this by sharing your log file. You can find your log file here: `C:\Users\\<your username>\AppData\Roaming\cura\<Cura version>\cura.log`

Let me know when you have more questions.
