### ISSUE TITLE
Cura breaks on MacBook Air (M1)

### ISSUE THREAD

**Issue by Pheerink** [Ultimaker/Cura#9422]
### Application Version

Cura 4.8

### Platform

MacBook Air (MacOs Big Sur)

### Printer

Artillery X1 V4

### Reproduction steps

Slicing Works fine until you do a preview. Then the program hangs.

### Actual results

Distortion of the screen and program hangs

### Expected results

Normal operation

**Comment by fvrmr** [comment]
Hi @Pheerink thank you for your bug report.
This is a duplicate of #8745.
We are working on a solution and we already have done a test build that will fix this problem. Progress with the upgrade of the Qt version is still ongoing. There are other crashes still to solve now.

Because this is a duplicate I will close this issue.

**Comment by Pheerink** [comment]
Sorry couldn’t find it. Thanks anyway

Regards
Paul
