### ISSUE TITLE
Change wording for Feature request instruction

### ISSUE THREAD

**Issue by printingotb** [Ultimaker/Cura#9449]
### Is your feature request related to a problem?

Not really a problem, a tiny bit confusing.

### Describe the solution you'd like

Change the instructional text "Again, if possible, think about why these alternatives are not working out."
I can't find what instruction "Again.. not working out" is referring to?

### Describe alternatives you've considered

Spend my time on more important stuff ha!

### Affected users and/or printers

Those with a sharp eye

![Skärmklipp](https://user-images.githubusercontent.com/32172100/112444706-a0393000-8d4e-11eb-86a0-f452d635772f.PNG)

**Comment by fvrmr** [comment]
Hi @printingotb thank you for your sharp eye. 👁️ 
The again is referring to _if possible_, because it was mentioned at the previous header. And _not working out_ is referring to the alternatives that doesn't work.
But I also think that removing **Again** is better for that sentence! So I will change it. 😄

**Comment by printingotb** [comment]
Excellent :partying_face:
