### ISSUE TITLE
Seam relative to object or custom seam per object.

### ISSUE THREAD

**Issue by Zogar89** [Ultimaker/Cura#9573]
### Is your feature request related to a problem?

Currently we can only select absolute seam or relative seam towards the same place.

This removes flexibility when placing objects on the printing bed and forces the extruder to travel great distances to start each object with the problems that this entails.
![Relative Seam1](https://user-images.githubusercontent.com/11767960/114504143-c3942400-9c04-11eb-87b4-ef3a3a93d1f7.png)

### Describe the solution you'd like

I propose to be able to select the seams independently for each object or perhaps an easier solution is to put a third option, that the seam is relative to each object but does not change direction if we rotate the object, as is currently the case.

![Relative Seam2](https://user-images.githubusercontent.com/11767960/114504088-aa8b7300-9c04-11eb-9ab1-508277c880a2.png)

### Describe alternatives you've considered

This is already incorporated by PrusaSlicer with its modifiers so I hope my favorite program (Cura) is not left behind!

### Affected users and/or printers

All

**Comment by fvrmr** [comment]
Hi @Zogar89 thank you for your feature request.
You can already do this in Cura with modifiers! 😄 

Select the model and open the modifier menu. Then click on normal model as mesh type and select settings you want to apply for that model.

![Screenshot (152)](https://user-images.githubusercontent.com/77000924/114515791-096cde80-9c3d-11eb-8395-b790ce5baeae.png)

Let me know if that works for you!

**Comment by Asterchades** [comment]
There's also a checkbox to make the seam relative to the object, not the whole build plate. So instead of being closest to (for example) the centre rear of the plate, it puts it at the rear of the object instead. It won't automatically update on rotating, however, so if you set it to the Rear than it will always be at the Rear - even if that is actually the "Front" of the object after rotation.

Option is called "Z Seam Relative" and only shows when the Z Seam Alignment is set to "User Specified".

**Comment by Zogar89** [comment]
Thanks for that, I m really happy.

I generally use the overlay option a lot to modify parts of objects but I had not realized that I could modify entire objects.

I have some considerations to make in the overlay settings tool but it will be in another ticket.
