### ISSUE TITLE
Cannot restor backup from 4.8.0

### ISSUE THREAD

**Issue by DobbinPi** [Ultimaker/Cura#9729]
### Application Version

4.9.0

### Platform

Windows 10

### Printer

Creality Ender 3 Pro (although doesn't seem to make any difference to this bug)

### Reproduction steps

Launch Cura, select printer, login to Ultimaker account, select backup from 4.8.0 created 5 mins before installing 4.9.0 restart Cura no settings and have to add printer all over again.

### Actual results

No setting restored from backup

### Expected results

All setting should be restored from backup

### Checklist of files to include

- [X] Log file
- [ ] Project file

### Additional information & file uploads

[cura.log](https://github.com/Ultimaker/Cura/files/6403788/cura.log)

**Comment by fvrmr** [comment]
Hi @DobbinPi thank you for your bug report. 
I've tried it myself, but the backup restored all the settings. 

In your log file I can see that Cura is trying to restore the backup. So I would love to see your configuration folder. (help - show configuration folder). Could you share this folder of Cura 4.8 with me as a zip. 
If you share this, **please make sure** to delete the `cura.cfg` file because here you can find login information.
