### ISSUE TITLE
JSON code conventions

### ISSUE THREAD

**Issue by nickthetait** [Ultimaker/Cura#980]
I'm starting work on getting JSON files standardized. I've based the formatting on https://github.com/Ultimaker/Meta/blob/master/code_conventions.md Please take a peek at current state here: https://code.alephobjects.com/diffusion/CT/browse/master/resources/definitions/fdmprinter.def.json
Then click 'view raw file' to see formatting even clearer.

This is using some custom settings within Eclipse/JSON Editor Plugin then hitting the Edit -> Format JSON button. Want to check that this looks sensible before going further. Additionally should I update this for all the existing printer definitions?

**Comment by fieldOfView** [comment]
Having the code on your own system makes it a bit harder for use to compare the changes. The automated change seems to have made some strange decisions eg in line 849, 990, 1149, ...

We know we have quite a few violations against our own code conventions, but have decided against doing sweeping codestyle fixes because it makes tracking changes harder. In this case I don't think the benefits outweight the disadvantage of breaking git blame.

NB: we don't have official code conventions for JSON or qml. Especially the latter leads to discussion from time to time (semi colons, yes or no?)

**Comment by nallath** [comment]
I still think that we should have some official code conventions for both of them. On the forum someone also suggested using jsonmin to be able to add pseudo comments to the json file (which we then strip before parsing it as json)

**Comment by nickthetait** [comment]
So should I make a PR with these changes for just fdmprinter.def on master branch? Are they likely to be accepted?

**Comment by nickthetait** [comment]
Here's a better view of just the diff https://code.alephobjects.com/rCTdc77fbb671e4fd9f204a9793f56634a38a82f509#be0cfced

**Comment by thopiekar** [comment]
@nickthetait Alternatively just create a PR and set it here, if already done. We can discuss in the PR whether it is worth to merge it. (And often it is :wink: )
