### ISSUE TITLE
[MacOS] Settings menu does not respond to menu or Cmd-,

### ISSUE THREAD

**Issue by Linnie73** [Ultimaker/Cura#9802]
### Application Version

4.9.0

### Platform

Mac OS Catalina 10.15.7

### Printer

Creality CR6SE

### Reproduction steps

When you click on the Ultimaker Cura Menu at the top and click on Settings there is no response from the program. The new Store Custom Setting Visibility Set (just hovering to the right of the menu area for Settings) responds as normal. 
Cmd-, (universal keyboard shortcut for settings, also as indicated in the menu itself), does not respond. 

### Actual results

No response from the program after clicking on the Settings menu item or pressing the keyboard shortcut Cmd-, When Cmd-, is pressed, the menu bar lights up to indicate a button press was received but nothing happens. 
The workaround for me is to go to the Printer Selection button on the working screen, then Manage Printers and then jump to the General Settings. 

### Expected results

Expected the General Settings menu to open. 

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

I don't know what else to tell you.

**Comment by fvrmr** [comment]
Hi @Linnie73 thank you for your report. 
In Cura there is no shortcut for cmd-. So I assume this issue comes from the Custom Setting Visibilty Plugin. It seems to be related to: https://github.com/fieldOfView/Cura-SettingVisibilityProfileCreator/issues/1

I will close this issue since it is not a issue of Cura. Please report your issue to the plugin developer.
