### ISSUE TITLE
Preview Crashes on M1 Mac

### ISSUE THREAD

**Issue by joelkeep** [Ultimaker/Cura#9862]
### Application Version

4.9.1

### Platform

macOS Big Sur 11.2.3

### Printer

Ultimaker S5

### Reproduction steps

This has been happening for several versions of Cura now.  I've tried opening the preview after slicing on all of my prints for the last few months and the app crashes without fail.  The model looks like an explosion of lines that you see for a couple seconds before the app crashes.

### Actual results

The app crashes and closes by itself.
![Screen Shot 2021-05-14 at 3 54 24 PM](https://user-images.githubusercontent.com/68670377/118335401-d08a8880-b4cc-11eb-9bb8-656aea7f7606.png)

### Expected results

Preview mode should open where I can inspect the layers that are to be printed.

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

-

**Comment by fvrmr** [comment]
Hi @joelkeep thank you for your bug report.
This is a known bug. See https://github.com/Ultimaker/Cura/issues/8745
This is happening because Cura uses OpenGL libraries and with the new macbooks containing the M1 processing chips, Apple has introduced incompatibilities between the OpenGL libaries used and the latest firmware used by Macbooks. 

I will close this one because it is a duplicate.
