### ISSUE TITLE
apple m1 preview not supported 

### ISSUE THREAD

**Issue by piteke** [Ultimaker/Cura#9870]
### Application Version

4.9.1

### Platform

mac os big sur 11.3.1 Macbook air M1

### Printer

Ultimaker 3

### Reproduction steps

 I load the stl in the program and give the slice command, then I look at the preview

### Actual results

cura crash or does not show me the preview

### Expected results

should show me the preview

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

it does not work!!

**Comment by fvrmr** [comment]
Hi @piteke thank you for your bug report.
This is a known issue, you can find the duplicate here: https://github.com/Ultimaker/Cura/issues/8745

This is happening because Cura uses OpenGL libraries and with the new macbooks containing the M1 processing chips, Apple has introduced incompatibilities between the OpenGL libaries used and the latest firmware used by Macbooks.

I will close this one because it is a duplicate.
