### ISSUE TITLE
Cura 2.3.0 hangs on 'preparing to slice'

### ISSUE THREAD

**Issue by dwm101** [Ultimaker/Cura#988]
I've just installed Cura 2.3 to use with my Ultimaker 2 and no matter what model I open the system just sits on 'Preparing to slice' but doesn't actually do anything. Any thoughts?

![cura_hang](https://cloud.githubusercontent.com/assets/22194882/18511468/b1828e3c-7a7b-11e6-8a84-bb9d3212536d.jpg)

Edit: [cura.txt](https://github.com/Ultimaker/Cura/files/471978/cura.txt)

May be of some use- showing exception for 'startslicejob' whci hmust be related(?).

**Comment by sorvis** [comment]
The update to 2.3 broke slicing for me too. I found this error message repeated in my engine log:

`/usr/bin/CuraEngine: error while loading shared libraries: libArcus.so.2: cannot open shared object file: No such file or directory`

**Comment by Ghostkeeper** [comment]
Dwm101 seems to be running into a setting problem: The quality-changes profile is None. I have a sneaking suspicion it might be caused by a faulty upgrade of his settings from version 2.1. You might try deleting (or moving away) this folder: `C:\Users\<dwm101>\AppData\Local\cura`. You'll lose all your preferences and profiles doing so, though.

Sorvis is running into a build problem... libArcus isn't being included/installed properly?

**Comment by dwm101** [comment]
Yeah, I was wondering that actually- when I open 2.3 it mentions it's imported my custom profiles which could well be screwing things up. Will have a clear out and try again.

**Comment by Ghostkeeper** [comment]
Known bug then which has since been fixed.
