### ISSUE TITLE
Z9m4 from Zonestar

### ISSUE THREAD

**Issue by denjohn** [Ultimaker/Cura#9904]
### Application Version

4.9.1

### Platform

Windows 10

### Printer

zonestar z9m4

### Reproduction steps

tried to add zonestar's model z9m4 to cura

### Actual results

Please send the config for z9m4 for zonestar printer to gotoaman@gmail.com

### Expected results

I would like to use Cura with my zonestar z9m4

### Checklist of files to include

- [ ] Log file
- [ ] Project file

### Additional information & file uploads

no more to add

**Comment by fvrmr** [comment]
Hi @denjohn thank you for your report.
We don't maintain the config files for Zonestar printers, so I can't send them to you. For 3rd party printers we are dependent on our community to adding this files. 
You could add a custom printer, [see here](https://support.ultimaker.com/hc/en-us/articles/360012370160-How-to-add-a-custom-printer-to-Ultimaker-Cura) how to do that. 

I will close this issue, since we won't do this.
Hope you understand.
