### ISSUE TITLE
Cura 2.3.0 issue with platform adhesion around support structure

### ISSUE THREAD

**Issue by dwm101** [Ultimaker/Cura#992]
This isn't so much a bug as a request to maintain a feature. In 2.1.3 if only part of a model is in contact with the build plate the platform adhesion extends around the entire print, including the support structure. It appears that in 2.3.0 the platform adhesion is only added around the part itself meaning that there's nothing holding the support structure down apart from the limited contact the support makes on its own. I hope that makes sense... Pictures to help:

2.1.3:
![cura213](https://cloud.githubusercontent.com/assets/22194882/18551016/8f8fa46c-7b4e-11e6-9cb1-e183abee6785.jpg)

2.3.0:
![cura_230](https://cloud.githubusercontent.com/assets/22194882/18551023/99ad6150-7b4e-11e6-98ac-b1250a00d12e.jpg)

**Comment by Ghostkeeper** [comment]
Yes, we did some tweaks to that recently.

Originally the brim was added around the whole model. This presented a problem since you'd have parts where the brim was attached to the model and parts where the brim wasn't, which made a clear difference in the final print (you'd see the elephant foot where the brim was, so there was an asymmetry) and also presented a problem if there was support around the entire model since the model didn't attach to the build plate very well.

So we changed it to only create a brim around the mesh itself, not support. This presented another problem because support would often start warping and detaching from the build plate, especially with some of the new materials Ultimaker released in August. This is the state it was in when we released the beta, which you're seeing there.

So now we changed it again to build brim around the mesh as well as the support. The brim goes only around the pieces of support that are farther away from the mesh than the width of the brim. It now looks like this:

![brimundersupport](https://cloud.githubusercontent.com/assets/2448634/18579429/e4cd45e0-7bf5-11e6-80e3-098053f4eb1d.png)
